/**
 * AI Infrastructure Relationships (REL-AI)
 *
 * Covers AI compute hardware, AI service/platform, and cross-category connections.
 * These relationships capture how AI-specific infrastructure components interconnect
 * and how they integrate with traditional infrastructure.
 */

import type { ComponentRelationship } from '../types';
import {
  NVIDIA_AI_ENTERPRISE,
  HUGGINGFACE_DOCS,
  MLOPS_COMMUNITY,
  NIST_AI_RMF,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// AI Compute Relationships (REL-AI-001 ~ REL-AI-005)
// ---------------------------------------------------------------------------

export const aiComputeRelationships: ComponentRelationship[] = [
  {
    id: 'REL-AI-001',
    type: 'relationship',
    source: 'ai-cluster',
    target: 'gpu-server',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'AI clusters are composed of multiple GPU servers; without GPU nodes, the cluster cannot perform training or inference workloads',
    reasonKo: 'AI 클러스터는 여러 GPU 서버로 구성됩니다. GPU 노드 없이는 학습 또는 추론 워크로드를 수행할 수 없습니다',
    tags: ['ai', 'compute', 'gpu', 'cluster'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Multi-Node GPU Cluster Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-002',
    type: 'relationship',
    source: 'gpu-server',
    target: 'inference-engine',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'GPU servers dramatically accelerate inference engine throughput via parallel tensor computation, reducing latency by 10-100x over CPU-only deployments',
    reasonKo: 'GPU 서버는 병렬 텐서 연산을 통해 추론 엔진 처리량을 크게 향상시키며, CPU 전용 배포 대비 지연 시간을 10-100배 줄여줍니다',
    tags: ['ai', 'compute', 'gpu', 'inference', 'acceleration'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'GPU-Accelerated Inference')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-003',
    type: 'relationship',
    source: 'edge-device',
    target: 'inference-engine',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Edge AI devices benefit from local inference engines to reduce latency and enable offline operation without cloud dependency',
    reasonKo: '엣지 AI 디바이스는 지연 시간을 줄이고 클라우드 의존성 없이 오프라인 운영을 가능하게 하는 로컬 추론 엔진이 권장됩니다',
    tags: ['ai', 'edge', 'inference', 'on-device'],
    trust: {
      confidence: 0.8,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Edge AI Deployment')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-004',
    type: 'relationship',
    source: 'mobile-device',
    target: 'inference-engine',
    relationshipType: 'recommends',
    strength: 'weak',
    direction: 'downstream',
    reason: 'Mobile devices can run lightweight inference engines (ONNX Runtime, TFLite) for on-device AI processing with privacy benefits',
    reasonKo: '모바일 디바이스는 프라이버시 이점과 함께 온디바이스 AI 처리를 위해 경량 추론 엔진(ONNX Runtime, TFLite)을 실행할 수 있습니다',
    tags: ['ai', 'mobile', 'inference', 'on-device', 'privacy'],
    trust: {
      confidence: 0.75,
      sources: [withSection(NIST_AI_RMF, 'MAP 1.5 - Deployment Environment')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-005',
    type: 'relationship',
    source: 'gpu-server',
    target: 'training-platform',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'GPU servers in training clusters require a training platform (MLflow, W&B) to orchestrate distributed training jobs, track experiments, and manage checkpoints',
    reasonKo: '학습 클러스터의 GPU 서버는 분산 학습 작업 조율, 실험 추적, 체크포인트 관리를 위해 학습 플랫폼(MLflow, W&B)이 필수입니다',
    tags: ['ai', 'compute', 'gpu', 'training', 'mlops'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Training Infrastructure - Distributed Training')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
];

// ---------------------------------------------------------------------------
// AI Service Relationships (REL-AI-006 ~ REL-AI-015)
// ---------------------------------------------------------------------------

export const aiServiceRelationships: ComponentRelationship[] = [
  {
    id: 'REL-AI-006',
    type: 'relationship',
    source: 'ai-orchestrator',
    target: 'inference-engine',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'AI orchestrators (LangChain, CrewAI) require at least one inference engine to execute LLM calls and generate responses',
    reasonKo: 'AI 오케스트레이터(LangChain, CrewAI)는 LLM 호출 실행과 응답 생성을 위해 최소 하나의 추론 엔진이 필수입니다',
    tags: ['ai', 'orchestrator', 'inference', 'llm'],
    trust: {
      confidence: 0.85,
      sources: [withSection(HUGGINGFACE_DOCS, 'Inference Endpoints - Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-007',
    type: 'relationship',
    source: 'ai-orchestrator',
    target: 'vector-db',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI orchestrators benefit from vector databases for RAG (Retrieval-Augmented Generation), providing contextual knowledge to reduce hallucinations',
    reasonKo: 'AI 오케스트레이터는 환각을 줄이기 위한 맥락적 지식 제공을 위해 RAG(검색 증강 생성)용 벡터 데이터베이스가 권장됩니다',
    tags: ['ai', 'orchestrator', 'vector-db', 'rag'],
    trust: {
      confidence: 0.8,
      sources: [withSection(HUGGINGFACE_DOCS, 'RAG - Retrieval-Augmented Generation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-008',
    type: 'relationship',
    source: 'ai-orchestrator',
    target: 'embedding-service',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI orchestrators need embedding services to convert text into vector representations for semantic search and RAG pipelines',
    reasonKo: 'AI 오케스트레이터는 시맨틱 검색과 RAG 파이프라인을 위해 텍스트를 벡터 표현으로 변환하는 임베딩 서비스가 권장됩니다',
    tags: ['ai', 'orchestrator', 'embedding', 'rag'],
    trust: {
      confidence: 0.8,
      sources: [withSection(HUGGINGFACE_DOCS, 'Embeddings - Text Representation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-009',
    type: 'relationship',
    source: 'ai-gateway',
    target: 'inference-engine',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI gateways (LiteLLM) route requests to inference engines, providing unified API, rate limiting, and multi-model load balancing',
    reasonKo: 'AI 게이트웨이(LiteLLM)는 통합 API, 속도 제한, 다중 모델 로드 밸런싱을 제공하며 추론 엔진으로 요청을 라우팅합니다',
    tags: ['ai', 'gateway', 'inference', 'routing', 'load-balancing'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Model Serving - Gateway Pattern')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-010',
    type: 'relationship',
    source: 'inference-engine',
    target: 'ai-monitor',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Inference engines should report metrics to AI monitors for tracking model drift, latency, token usage, and response quality',
    reasonKo: '추론 엔진은 모델 드리프트, 지연 시간, 토큰 사용량, 응답 품질 추적을 위해 AI 모니터에 메트릭을 보고해야 합니다',
    tags: ['ai', 'inference', 'monitoring', 'drift-detection'],
    trust: {
      confidence: 0.8,
      sources: [withSection(NIST_AI_RMF, 'MEASURE 2.6 - AI System Monitoring')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-011',
    type: 'relationship',
    source: 'embedding-service',
    target: 'vector-db',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Embedding services produce vector representations that must be stored in a vector database for similarity search and retrieval',
    reasonKo: '임베딩 서비스는 유사도 검색과 검색을 위해 벡터 데이터베이스에 저장해야 하는 벡터 표현을 생성합니다',
    tags: ['ai', 'embedding', 'vector-db', 'storage'],
    trust: {
      confidence: 0.85,
      sources: [withSection(HUGGINGFACE_DOCS, 'Embeddings - Vector Storage')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-012',
    type: 'relationship',
    source: 'training-platform',
    target: 'model-registry',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Training platforms should push trained models to a registry for versioning, lineage tracking, and deployment promotion across environments',
    reasonKo: '학습 플랫폼은 버전 관리, 계보 추적, 환경 간 배포 프로모션을 위해 학습된 모델을 레지스트리에 푸시해야 합니다',
    tags: ['ai', 'training', 'model-registry', 'mlops', 'versioning'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Model Management - Registry')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-013',
    type: 'relationship',
    source: 'prompt-manager',
    target: 'ai-orchestrator',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Prompt managers (LangSmith) enhance AI orchestrators by providing prompt versioning, A/B testing, and performance analytics for prompt engineering',
    reasonKo: '프롬프트 관리자(LangSmith)는 프롬프트 버전 관리, A/B 테스트, 프롬프트 엔지니어링 성능 분석을 제공하여 AI 오케스트레이터를 강화합니다',
    tags: ['ai', 'prompt', 'orchestrator', 'versioning', 'analytics'],
    trust: {
      confidence: 0.75,
      sources: [withSection(MLOPS_COMMUNITY, 'Prompt Engineering - Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-014',
    type: 'relationship',
    source: 'model-registry',
    target: 'inference-engine',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Model registries serve as the source of truth for model artifacts that inference engines load; enables controlled rollout and rollback',
    reasonKo: '모델 레지스트리는 추론 엔진이 로드하는 모델 아티팩트의 신뢰할 수 있는 소스 역할을 하며, 제어된 롤아웃과 롤백을 가능하게 합니다',
    tags: ['ai', 'model-registry', 'inference', 'deployment', 'rollback'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Model Deployment - Registry Integration')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-015',
    type: 'relationship',
    source: 'ai-monitor',
    target: 'ai-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI monitors benefit from AI gateway integration for centralized request/response logging, cost tracking, and quality metrics across all models',
    reasonKo: 'AI 모니터는 모든 모델에 걸친 중앙 집중식 요청/응답 로깅, 비용 추적, 품질 메트릭을 위해 AI 게이트웨이 연동이 권장됩니다',
    tags: ['ai', 'monitoring', 'gateway', 'centralized', 'observability'],
    trust: {
      confidence: 0.75,
      sources: [withSection(NIST_AI_RMF, 'GOVERN 1.3 - AI System Oversight')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
];

// ---------------------------------------------------------------------------
// Cross-Category Relationships (REL-AI-016 ~ REL-AI-025)
// ---------------------------------------------------------------------------

export const aiCrossRelationships: ComponentRelationship[] = [
  {
    id: 'REL-AI-016',
    type: 'relationship',
    source: 'api-gateway',
    target: 'ai-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'API gateways should route AI/LLM traffic through a dedicated AI gateway for model-specific rate limiting, token accounting, and prompt security',
    reasonKo: 'API 게이트웨이는 모델별 속도 제한, 토큰 과금, 프롬프트 보안을 위해 AI/LLM 트래픽을 전용 AI 게이트웨이로 라우팅해야 합니다',
    tags: ['ai', 'api-gateway', 'ai-gateway', 'routing', 'security'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Model Serving - API Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-017',
    type: 'relationship',
    source: 'load-balancer',
    target: 'ai-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Load balancers should distribute AI inference traffic to AI gateways for high-availability multi-model serving with failover',
    reasonKo: '로드 밸런서는 장애 조치 기능이 있는 고가용성 다중 모델 서빙을 위해 AI 추론 트래픽을 AI 게이트웨이로 분산해야 합니다',
    tags: ['ai', 'load-balancer', 'ai-gateway', 'high-availability'],
    trust: {
      confidence: 0.8,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Production Deployment - Load Balancing')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-018',
    type: 'relationship',
    source: 'kubernetes',
    target: 'inference-engine',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Kubernetes enhances inference engines with auto-scaling, GPU scheduling, health checks, and rolling deployments for model serving',
    reasonKo: 'Kubernetes는 모델 서빙을 위한 오토스케일링, GPU 스케줄링, 헬스 체크, 롤링 배포로 추론 엔진을 강화합니다',
    tags: ['ai', 'kubernetes', 'inference', 'orchestration', 'scaling'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Kubernetes - GPU Operator for Inference')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-019',
    type: 'relationship',
    source: 'kubernetes',
    target: 'ai-cluster',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Kubernetes orchestrates AI cluster workloads with GPU-aware scheduling, multi-node job management, and resource quotas across training jobs',
    reasonKo: 'Kubernetes는 GPU 인식 스케줄링, 다중 노드 작업 관리, 학습 작업 간 리소스 쿼터로 AI 클러스터 워크로드를 조율합니다',
    tags: ['ai', 'kubernetes', 'cluster', 'gpu-scheduling', 'training'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Kubernetes - GPU Operator for Training')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-020',
    type: 'relationship',
    source: 'vector-db',
    target: 'elasticsearch',
    relationshipType: 'recommends',
    strength: 'weak',
    direction: 'bidirectional',
    reason: 'Vector databases complement Elasticsearch for hybrid search: vector similarity for semantic meaning plus full-text for keyword precision',
    reasonKo: '벡터 데이터베이스는 하이브리드 검색을 위해 Elasticsearch를 보완합니다: 의미론적 유사도 벡터 검색과 키워드 정밀도의 전문 검색',
    tags: ['ai', 'vector-db', 'elasticsearch', 'hybrid-search', 'rag'],
    trust: {
      confidence: 0.75,
      sources: [withSection(HUGGINGFACE_DOCS, 'RAG - Hybrid Search Strategies')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-021',
    type: 'relationship',
    source: 'ai-monitor',
    target: 'prometheus',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI monitors should export metrics (inference latency, token throughput, error rates) to Prometheus for unified infrastructure observability',
    reasonKo: 'AI 모니터는 통합 인프라 관측성을 위해 메트릭(추론 지연, 토큰 처리량, 오류율)을 Prometheus로 내보내야 합니다',
    tags: ['ai', 'monitoring', 'prometheus', 'metrics', 'observability'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Monitoring - Infrastructure Metrics')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-022',
    type: 'relationship',
    source: 'ai-monitor',
    target: 'grafana',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'AI monitors benefit from Grafana dashboards for visualizing model performance, drift detection alerts, and cost tracking over time',
    reasonKo: 'AI 모니터는 모델 성능 시각화, 드리프트 감지 알림, 시간별 비용 추적을 위해 Grafana 대시보드가 권장됩니다',
    tags: ['ai', 'monitoring', 'grafana', 'dashboard', 'visualization'],
    trust: {
      confidence: 0.75,
      sources: [withSection(MLOPS_COMMUNITY, 'Monitoring - Dashboards and Alerting')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-023',
    type: 'relationship',
    source: 'inference-engine',
    target: 'cache',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Inference engines should use caching (Redis, KV cache) for repeated prompts to reduce GPU compute costs and lower response latency',
    reasonKo: '추론 엔진은 GPU 연산 비용 절감과 응답 지연 감소를 위해 반복 프롬프트에 대한 캐싱(Redis, KV 캐시)을 사용해야 합니다',
    tags: ['ai', 'inference', 'cache', 'cost-optimization', 'latency'],
    trust: {
      confidence: 0.8,
      sources: [withSection(NVIDIA_AI_ENTERPRISE, 'Inference Optimization - KV Cache')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-024',
    type: 'relationship',
    source: 'model-registry',
    target: 'object-storage',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Model registries should use object storage (S3, GCS, MinIO) as the backend for large model artifacts, checkpoints, and dataset versions',
    reasonKo: '모델 레지스트리는 대용량 모델 아티팩트, 체크포인트, 데이터셋 버전을 위한 백엔드로 오브젝트 스토리지(S3, GCS, MinIO)를 사용해야 합니다',
    tags: ['ai', 'model-registry', 'object-storage', 'artifacts', 'mlops'],
    trust: {
      confidence: 0.8,
      sources: [withSection(MLOPS_COMMUNITY, 'Model Storage - Artifact Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
  {
    id: 'REL-AI-025',
    type: 'relationship',
    source: 'edge-device',
    target: 'wireless-ap',
    relationshipType: 'recommends',
    strength: 'weak',
    direction: 'upstream',
    reason: 'Edge AI devices typically connect through wireless access points for network connectivity, model updates, and telemetry reporting',
    reasonKo: '엣지 AI 디바이스는 네트워크 연결, 모델 업데이트, 텔레메트리 보고를 위해 일반적으로 무선 액세스 포인트를 통해 연결됩니다',
    tags: ['ai', 'edge', 'wireless', 'connectivity', 'iot'],
    trust: {
      confidence: 0.7,
      sources: [withSection(NIST_AI_RMF, 'MAP 1.5 - Edge Deployment Connectivity')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-24',
    },
  },
];
