/**
 * Cloud Relationships (REL-CLD) + Cloud-Native (REL-MSG, REL-API, REL-MON, REL-SRC)
 *
 * AWS VPC, Azure VNet, GCP Network, private cloud + messaging, API gw, monitoring, search
 */

import type { InfraNodeType } from '@/types/infra';
import type { ComponentRelationship, RelationshipType } from '../types';
import {
  NIST_800_53,
  NIST_800_144,
  RFC_7230,
  OWASP_API_TOP10,
  AWS_WAF_REL,
  AWS_WAF_SEC,
  AWS_WAF_PERF,
  AZURE_CAF,
  GCP_ARCH_FRAMEWORK,
  CNCF_SECURITY,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// Cloud Relationships (REL-CLD-001 ~ REL-CLD-008)
// ---------------------------------------------------------------------------

export const cloudRelationships: ComponentRelationship[] = [
  {
    id: 'REL-CLD-001',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'AWS VPC requires security groups/firewalls for network access control at the instance level',
    reasonKo: 'AWS VPC는 인스턴스 수준의 네트워크 접근 제어를 위해 보안 그룹/방화벽이 필수입니다',
    tags: ['cloud', 'aws', 'firewall', 'security-group'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_SEC, 'Infrastructure Protection - VPC Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-002',
    type: 'relationship',
    source: 'azure-vnet',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Azure VNet requires NSG/firewall for inbound and outbound traffic filtering',
    reasonKo: 'Azure VNet은 인바운드/아웃바운드 트래픽 필터링을 위해 NSG/방화벽이 필수입니다',
    tags: ['cloud', 'azure', 'firewall', 'nsg'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AZURE_CAF, 'Security - Network Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-003',
    type: 'relationship',
    source: 'gcp-network',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'GCP VPC network requires firewall rules for controlling traffic to and from instances',
    reasonKo: 'GCP VPC 네트워크는 인스턴스 간 트래픽 제어를 위해 방화벽 규칙이 필수입니다',
    tags: ['cloud', 'gcp', 'firewall', 'network'],
    trust: {
      confidence: 0.85,
      sources: [withSection(GCP_ARCH_FRAMEWORK, 'Security - Network Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-004',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'load-balancer',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Cloud VPCs should use load balancers for multi-AZ traffic distribution and auto-scaling',
    reasonKo: '클라우드 VPC는 다중 AZ 트래픽 분산과 Auto Scaling을 위해 로드 밸런서 사용이 권장됩니다',
    tags: ['cloud', 'aws', 'load-balancer', 'multi-az'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Load Balancing - Multi-AZ')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-005',
    type: 'relationship',
    source: 'gcp-network',
    target: 'iam',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'GCP networks should use IAM for resource-level access control and service account management',
    reasonKo: 'GCP 네트워크는 리소스 수준 접근 제어와 서비스 계정 관리를 위해 IAM 사용이 권장됩니다',
    tags: ['cloud', 'gcp', 'iam', 'access-control'],
    trust: {
      confidence: 0.85,
      sources: [withSection(GCP_ARCH_FRAMEWORK, 'Security - Identity and Access')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-006',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'backup',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Cloud VPCs should include backup services for data protection and disaster recovery',
    reasonKo: '클라우드 VPC는 데이터 보호와 재해 복구를 위해 백업 서비스 포함이 권장됩니다',
    tags: ['cloud', 'aws', 'backup', 'disaster-recovery'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Data Backup and Recovery')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-007',
    type: 'relationship',
    source: 'private-cloud',
    target: 'iam',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Private clouds should use IAM for tenant isolation and administrative access control',
    reasonKo: '프라이빗 클라우드는 테넌트 격리와 관리 접근 제어를 위해 IAM 사용이 권장됩니다',
    tags: ['cloud', 'private-cloud', 'iam', 'tenant-isolation'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_144, 'Section 4 - Security and Privacy Issues')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-CLD-008',
    type: 'relationship',
    source: 'private-cloud',
    target: 'backup',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Private clouds should include backup infrastructure for business continuity',
    reasonKo: '프라이빗 클라우드는 비즈니스 연속성을 위해 백업 인프라 포함이 권장됩니다',
    tags: ['cloud', 'private-cloud', 'backup', 'business-continuity'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_53, 'CP-9 - Information System Backup')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
];

// ---------------------------------------------------------------------------
// Cloud-Native Relationships (REL-MSG, REL-API, REL-MON, REL-SRC)
// ---------------------------------------------------------------------------

export const cloudNativeRelationships: ComponentRelationship[] = [
  {
    id: 'REL-MSG-001',
    type: 'relationship',
    source: 'app-server' as InfraNodeType,
    target: 'kafka' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'Application servers benefit from Kafka for asynchronous event-driven communication, decoupling producers from consumers',
    reasonKo: '애플리케이션 서버는 비동기 이벤트 기반 통신을 위해 Kafka를 사용하여 프로듀서와 컨슈머를 분리할 수 있습니다',
    tags: ['messaging', 'app-server', 'kafka', 'event-driven'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Event-Driven Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-MSG-002',
    type: 'relationship',
    source: 'kafka' as InfraNodeType,
    target: 'app-server' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'Kafka consumers typically run as application server processes to handle event processing and business logic',
    reasonKo: 'Kafka 컨슈머는 일반적으로 이벤트 처리 및 비즈니스 로직 수행을 위해 애플리케이션 서버 프로세스로 실행됩니다',
    tags: ['messaging', 'kafka', 'app-server', 'consumer'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Event-Driven Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-MSG-003',
    type: 'relationship',
    source: 'app-server' as InfraNodeType,
    target: 'rabbitmq' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'weak',
    direction: 'downstream',
    reason: 'RabbitMQ provides reliable message queuing for task distribution, request-reply patterns, and workload balancing',
    reasonKo: 'RabbitMQ는 작업 분배, 요청-응답 패턴, 워크로드 밸런싱을 위한 안정적인 메시지 큐잉을 제공합니다',
    tags: ['messaging', 'app-server', 'rabbitmq', 'queue'],
    trust: {
      confidence: 0.8,
      sources: [withSection(AWS_WAF_PERF, 'Asynchronous Processing')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-MSG-004',
    type: 'relationship',
    source: 'rabbitmq' as InfraNodeType,
    target: 'app-server' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'weak',
    direction: 'downstream',
    reason: 'RabbitMQ message consumers are typically application servers that process queued tasks and business logic',
    reasonKo: 'RabbitMQ 메시지 컨슈머는 일반적으로 큐에 쌓인 작업과 비즈니스 로직을 처리하는 애플리케이션 서버입니다',
    tags: ['messaging', 'rabbitmq', 'app-server', 'consumer'],
    trust: {
      confidence: 0.8,
      sources: [withSection(AWS_WAF_PERF, 'Asynchronous Processing')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-API-001',
    type: 'relationship',
    source: 'api-gateway' as InfraNodeType,
    target: 'app-server' as InfraNodeType,
    relationshipType: 'requires' as RelationshipType,
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'API gateway routes requests to backend application servers; it requires at least one upstream service',
    reasonKo: 'API 게이트웨이는 백엔드 애플리케이션 서버로 요청을 라우팅합니다. 최소 하나의 업스트림 서비스가 필요합니다',
    tags: ['network', 'api-gateway', 'app-server', 'routing'],
    trust: {
      confidence: 0.9,
      sources: [withSection(OWASP_API_TOP10, 'API Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-API-002',
    type: 'relationship',
    source: 'api-gateway' as InfraNodeType,
    target: 'web-server' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'API gateway can optionally route static content and SSR requests to web servers in addition to API backends',
    reasonKo: 'API 게이트웨이는 API 백엔드 외에도 선택적으로 정적 콘텐츠 및 SSR 요청을 웹 서버로 라우팅할 수 있습니다',
    tags: ['network', 'api-gateway', 'web-server', 'routing'],
    trust: {
      confidence: 0.8,
      sources: [withSection(RFC_7230, 'Section 2.3 - Intermediaries')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-MON-001',
    type: 'relationship',
    source: 'prometheus' as InfraNodeType,
    target: 'grafana' as InfraNodeType,
    relationshipType: 'enhances' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'Prometheus metrics are best visualized through Grafana dashboards for operational monitoring',
    reasonKo: 'Prometheus 메트릭은 운영 모니터링을 위해 Grafana 대시보드를 통해 시각화하는 것이 가장 효과적입니다',
    tags: ['monitoring', 'prometheus', 'grafana', 'visualization'],
    trust: {
      confidence: 0.9,
      sources: [withSection(CNCF_SECURITY, 'Observability - Monitoring')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-MON-002',
    type: 'relationship',
    source: 'app-server' as InfraNodeType,
    target: 'prometheus' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'Application servers should expose metrics endpoints for Prometheus scraping to enable monitoring and alerting',
    reasonKo: '애플리케이션 서버는 모니터링 및 알림을 위해 Prometheus 스크레이핑용 메트릭 엔드포인트를 노출해야 합니다',
    tags: ['monitoring', 'app-server', 'prometheus', 'metrics'],
    trust: {
      confidence: 0.85,
      sources: [withSection(CNCF_SECURITY, 'Observability - Application Metrics')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-SRC-001',
    type: 'relationship',
    source: 'app-server' as InfraNodeType,
    target: 'elasticsearch' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'weak',
    direction: 'downstream',
    reason: 'Application servers can leverage Elasticsearch for full-text search, log analytics, and fast data retrieval',
    reasonKo: '애플리케이션 서버는 전문 검색, 로그 분석, 빠른 데이터 검색을 위해 Elasticsearch를 활용할 수 있습니다',
    tags: ['search', 'app-server', 'elasticsearch', 'analytics'],
    trust: {
      confidence: 0.8,
      sources: [withSection(AWS_WAF_PERF, 'Search and Analytics')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
  {
    id: 'REL-SRC-002',
    type: 'relationship',
    source: 'kafka' as InfraNodeType,
    target: 'elasticsearch' as InfraNodeType,
    relationshipType: 'recommends' as RelationshipType,
    strength: 'strong',
    direction: 'downstream',
    reason: 'Kafka events are commonly streamed into Elasticsearch for real-time search, analytics, and log aggregation',
    reasonKo: 'Kafka 이벤트는 실시간 검색, 분석, 로그 집계를 위해 Elasticsearch로 스트리밍되는 것이 일반적입니다',
    tags: ['streaming', 'kafka', 'elasticsearch', 'pipeline'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Data Pipeline Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-14',
    },
  },
];
