/**
 * Core Dependencies - Mandatory Dependencies + Strong Recommendations
 *
 * mandatoryDependencies: REL-SEC / REL-NET / REL-CMP / REL-AUTH / REL-STR mandatory 'requires' relationships
 * strongRecommendations: REL-SEC / REL-NET / REL-CMP / REL-CLD / REL-AUTH strong 'recommends' relationships
 */

import type { ComponentRelationship } from '../types';
import {
  NIST_800_41,
  NIST_800_44,
  NIST_800_53,
  NIST_800_63B,
  NIST_800_77,
  NIST_800_81,
  NIST_800_123,
  NIST_800_125,
  NIST_800_144,
  RFC_7230,
  RFC_1034,
  CIS_V8_12,
  CIS_V8_13,
  OWASP_TOP10,
  OWASP_API_TOP10,
  AWS_WAF_REL,
  AWS_WAF_SEC,
  AWS_WAF_PERF,
  AZURE_CAF,
  CNCF_SECURITY,
  SANS_FIREWALL,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// Mandatory Dependencies (requires) — REL-SEC / REL-NET / REL-CMP
// ---------------------------------------------------------------------------

export const mandatoryDependencies: ComponentRelationship[] = [
  {
    id: 'REL-SEC-001',
    type: 'relationship',
    source: 'db-server',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Databases must reside in firewall-protected network segments to prevent unauthorized access',
    reasonKo: '데이터베이스는 무단 접근을 방지하기 위해 방화벽으로 보호되는 네트워크 세그먼트에 위치해야 합니다',
    tags: ['security', 'database', 'firewall', 'segmentation'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 2.1 - Network Segmentation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-002',
    type: 'relationship',
    source: 'vpn-gateway',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'VPN gateways must be placed behind firewalls; VPN alone does not provide network-layer access control',
    reasonKo: 'VPN 게이트웨이는 방화벽 뒤에 위치해야 합니다. VPN만으로는 네트워크 계층 접근 제어가 불가능합니다',
    tags: ['security', 'vpn', 'firewall', 'access-control'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_77, 'Section 3.2 - VPN Security Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-003',
    type: 'relationship',
    source: 'web-server',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Public-facing web servers require firewall protection to control inbound/outbound traffic',
    reasonKo: '공개 웹 서버는 인바운드/아웃바운드 트래픽 제어를 위해 방화벽 보호가 필수입니다',
    tags: ['security', 'web', 'firewall', 'perimeter'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_44, 'Section 8.2 - Network Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-001',
    type: 'relationship',
    source: 'switch-l2',
    target: 'switch-l3',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Layer 2 switches require a Layer 3 device (L3 switch or router) for inter-VLAN routing',
    reasonKo: 'L2 스위치는 VLAN 간 라우팅을 위해 L3 장비(L3 스위치 또는 라우터)가 필요합니다',
    tags: ['network', 'switch', 'routing', 'vlan'],
    trust: {
      confidence: 0.95,
      sources: [withSection(CIS_V8_12, '12.2 - Secure Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-002',
    type: 'relationship',
    source: 'cdn',
    target: 'dns',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'CDN relies on DNS for domain resolution and geographic traffic routing (GSLB)',
    reasonKo: 'CDN은 도메인 해석 및 지리적 트래픽 라우팅(GSLB)을 위해 DNS가 필수입니다',
    tags: ['network', 'cdn', 'dns', 'routing'],
    trust: {
      confidence: 1.0,
      sources: [withSection(RFC_1034, 'Section 3.6 - Resource Records')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-001',
    type: 'relationship',
    source: 'kubernetes',
    target: 'container',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Kubernetes orchestrates containers; it has no purpose without container workloads',
    reasonKo: 'Kubernetes는 컨테이너를 오케스트레이션합니다. 컨테이너 워크로드 없이는 의미가 없습니다',
    tags: ['compute', 'kubernetes', 'container', 'orchestration'],
    trust: {
      confidence: 0.7,
      sources: [withSection(CNCF_SECURITY, 'Container Orchestration')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-002',
    type: 'relationship',
    source: 'app-server',
    target: 'web-server',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Application servers in multi-tier architectures require a web/reverse-proxy frontend for client-facing HTTP handling',
    reasonKo: '멀티 티어 아키텍처에서 애플리케이션 서버는 클라이언트 HTTP 처리를 위해 웹/리버스 프록시 프론트엔드가 필요합니다',
    tags: ['compute', 'app-server', 'web-server', 'multi-tier'],
    trust: {
      confidence: 1.0,
      sources: [withSection(RFC_7230, 'Section 2.3 - Intermediaries')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-AUTH-001',
    type: 'relationship',
    source: 'sso',
    target: 'ldap-ad',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'SSO systems require a directory service (LDAP/AD) as the authoritative identity store',
    reasonKo: 'SSO 시스템은 인가된 ID 저장소로 디렉터리 서비스(LDAP/AD)가 필수입니다',
    tags: ['auth', 'sso', 'ldap', 'identity'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_63B, 'Section 4 - Authenticator Assurance Levels')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-AUTH-002',
    type: 'relationship',
    source: 'mfa',
    target: 'ldap-ad',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'MFA operates as an additional authentication factor on top of the primary identity store',
    reasonKo: 'MFA는 기본 ID 저장소 위에 추가 인증 요소로 동작합니다',
    tags: ['auth', 'mfa', 'ldap', 'multi-factor'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_63B, 'Section 4.2 - AAL2 Requirements')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-004',
    type: 'relationship',
    source: 'waf',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'WAF operates at application layer (L7) and requires network-layer firewall (L3/L4) for defense in depth',
    reasonKo: 'WAF는 애플리케이션 계층(L7)에서 동작하며, 심층 방어를 위해 네트워크 계층 방화벽(L3/L4)이 필요합니다',
    tags: ['security', 'waf', 'firewall', 'defense-in-depth'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 4.1 - Layered Firewall Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-STR-001',
    type: 'relationship',
    source: 'backup',
    target: 'san-nas',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Backup systems require primary storage (SAN/NAS) as the source data repository to back up',
    reasonKo: '백업 시스템은 백업 대상인 기본 스토리지(SAN/NAS)가 필요합니다',
    tags: ['storage', 'backup', 'san-nas', 'data-protection'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'CP-9 - Information System Backup')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
];

// ---------------------------------------------------------------------------
// Strong Recommendations (recommends) — REL-SEC / REL-NET / REL-CMP
// ---------------------------------------------------------------------------

export const strongRecommendations: ComponentRelationship[] = [
  {
    id: 'REL-SEC-010',
    type: 'relationship',
    source: 'web-server',
    target: 'waf',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'WAF provides OWASP Top 10 protection (SQL injection, XSS, CSRF) for web applications',
    reasonKo: 'WAF는 웹 애플리케이션에 대한 OWASP Top 10 보호(SQL 인젝션, XSS, CSRF)를 제공합니다',
    tags: ['security', 'web', 'waf', 'owasp'],
    trust: {
      confidence: 0.9,
      sources: [OWASP_TOP10],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-010',
    type: 'relationship',
    source: 'web-server',
    target: 'load-balancer',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'Load balancers distribute traffic for high availability and horizontal scalability of web tiers',
    reasonKo: '로드 밸런서는 웹 티어의 고가용성과 수평 확장성을 위해 트래픽을 분산합니다',
    tags: ['network', 'web', 'load-balancer', 'high-availability'],
    trust: {
      confidence: 0.85,
      sources: [AWS_WAF_REL],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-011',
    type: 'relationship',
    source: 'app-server',
    target: 'load-balancer',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'Application server clusters benefit from load balancing for session distribution and failover',
    reasonKo: '애플리케이션 서버 클러스터는 세션 분산 및 장애 조치를 위해 로드 밸런싱이 권장됩니다',
    tags: ['network', 'app-server', 'load-balancer', 'failover'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Design for Failure')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-011',
    type: 'relationship',
    source: 'web-server',
    target: 'cdn',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'CDN offloads static content delivery and provides DDoS mitigation for origin servers',
    reasonKo: 'CDN은 정적 콘텐츠 전송을 분산하고 오리진 서버에 대한 DDoS 완화를 제공합니다',
    tags: ['network', 'web', 'cdn', 'ddos', 'performance'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Content Delivery Network')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-012',
    type: 'relationship',
    source: 'firewall',
    target: 'ids-ips',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'IDS/IPS complements firewall with deep packet inspection and threat signature detection',
    reasonKo: 'IDS/IPS는 심층 패킷 검사와 위협 시그니처 탐지로 방화벽을 보완합니다',
    tags: ['security', 'firewall', 'ids-ips', 'defense-in-depth'],
    trust: {
      confidence: 0.95,
      sources: [withSection(CIS_V8_13, '13.3 - Deploy a Network Intrusion Detection Solution')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-010',
    type: 'relationship',
    source: 'app-server',
    target: 'cache',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Application server benefits from caching layer (Redis/Memcached) to reduce database load and improve read latency',
    reasonKo: '애플리케이션 서버는 캐시 계층(Redis/Memcached)을 통해 데이터베이스 부하를 줄이고 읽기 지연을 개선할 수 있습니다',
    tags: ['compute', 'app-server', 'cache', 'performance'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Caching Strategy')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-011',
    type: 'relationship',
    source: 'db-server',
    target: 'backup',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Database servers should have regular backups for disaster recovery and data protection',
    reasonKo: '데이터베이스 서버는 재해 복구 및 데이터 보호를 위해 정기적인 백업이 권장됩니다',
    tags: ['storage', 'database', 'backup', 'disaster-recovery'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'CP-9 - Information System Backup')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-012',
    type: 'relationship',
    source: 'web-server',
    target: 'dns',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Web servers need DNS for name resolution; DNSSEC prevents DNS spoofing attacks',
    reasonKo: '웹 서버는 이름 해석을 위해 DNS가 필요하며, DNSSEC는 DNS 스푸핑 공격을 방지합니다',
    tags: ['network', 'web', 'dns', 'security'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_81, 'Section 2 - DNS Security Threats')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-AUTH-010',
    type: 'relationship',
    source: 'vpn-gateway',
    target: 'mfa',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'VPN access should require multi-factor authentication to prevent credential-based attacks',
    reasonKo: 'VPN 접근은 자격 증명 기반 공격을 방지하기 위해 다요소 인증이 권장됩니다',
    tags: ['auth', 'vpn', 'mfa', 'zero-trust'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_63B, 'Section 4.3 - AAL3 Requirements')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-013',
    type: 'relationship',
    source: 'app-server',
    target: 'waf',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'API-serving application servers benefit from WAF rules for API security (OWASP API Top 10)',
    reasonKo: 'API를 제공하는 애플리케이션 서버는 API 보안(OWASP API Top 10)을 위한 WAF 규칙이 권장됩니다',
    tags: ['security', 'app-server', 'waf', 'api-security'],
    trust: {
      confidence: 0.9,
      sources: [OWASP_API_TOP10],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CLD-010',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'iam',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Cloud VPCs should use IAM for fine-grained resource access control and least-privilege policies',
    reasonKo: '클라우드 VPC는 세분화된 리소스 접근 제어와 최소 권한 정책을 위해 IAM 사용이 권장됩니다',
    tags: ['cloud', 'aws', 'iam', 'access-control'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_SEC, 'Identity and Access Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CLD-011',
    type: 'relationship',
    source: 'azure-vnet',
    target: 'iam',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Azure Virtual Networks should integrate with IAM (Azure AD) for identity-based network policies',
    reasonKo: 'Azure VNet은 ID 기반 네트워크 정책을 위해 IAM(Azure AD) 통합이 권장됩니다',
    tags: ['cloud', 'azure', 'iam', 'identity'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AZURE_CAF, 'Identity and Access Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-012',
    type: 'relationship',
    source: 'kubernetes',
    target: 'load-balancer',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'Kubernetes clusters need external load balancers (Ingress) for production traffic routing',
    reasonKo: 'Kubernetes 클러스터는 프로덕션 트래픽 라우팅을 위해 외부 로드 밸런서(Ingress)가 권장됩니다',
    tags: ['compute', 'kubernetes', 'load-balancer', 'ingress'],
    trust: {
      confidence: 0.7,
      sources: [withSection(CNCF_SECURITY, 'Ingress and Load Balancing')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-013',
    type: 'relationship',
    source: 'sd-wan',
    target: 'firewall',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'SD-WAN should integrate with firewalls for consistent security policy enforcement across branch sites',
    reasonKo: 'SD-WAN은 지사 간 일관된 보안 정책 적용을 위해 방화벽 통합이 권장됩니다',
    tags: ['network', 'sd-wan', 'firewall', 'branch-security'],
    trust: {
      confidence: 0.7,
      sources: [withSection(SANS_FIREWALL, 'Distributed Firewall Architectures')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-014',
    type: 'relationship',
    source: 'nac',
    target: 'ldap-ad',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'NAC should authenticate devices against the directory service for identity-based network admission',
    reasonKo: 'NAC는 ID 기반 네트워크 접근 허용을 위해 디렉터리 서비스와 연동이 권장됩니다',
    tags: ['security', 'nac', 'ldap', 'identity', 'zero-trust'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'AC-3 - Access Enforcement')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-015',
    type: 'relationship',
    source: 'dlp',
    target: 'firewall',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'DLP systems should work with firewalls to monitor and block sensitive data exfiltration at network boundaries',
    reasonKo: 'DLP 시스템은 네트워크 경계에서 민감 데이터 유출을 모니터링하고 차단하기 위해 방화벽과 연동이 권장됩니다',
    tags: ['security', 'dlp', 'firewall', 'data-protection'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'SC-7 - Boundary Protection')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CMP-013',
    type: 'relationship',
    source: 'vm',
    target: 'san-nas',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Virtual machines benefit from shared SAN/NAS storage for live migration and centralized management',
    reasonKo: '가상 머신은 라이브 마이그레이션과 중앙 관리를 위해 공유 SAN/NAS 스토리지가 권장됩니다',
    tags: ['compute', 'vm', 'san-nas', 'storage', 'migration'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_125, 'Section 4 - Virtualization Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CLD-012',
    type: 'relationship',
    source: 'private-cloud',
    target: 'firewall',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Private clouds should deploy firewalls for micro-segmentation between tenants and workloads',
    reasonKo: '프라이빗 클라우드는 테넌트 및 워크로드 간 마이크로 세그먼테이션을 위해 방화벽 배치가 권장됩니다',
    tags: ['cloud', 'private-cloud', 'firewall', 'segmentation'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_144, 'Section 4 - Security and Privacy Issues')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
];
