/**
 * Hybrid/Multi-Cloud + SASE/SOC Relationships
 *
 * hybridRelationships: REL-HYB cross-cloud connectivity
 * saseRelationships: REL-SASE secure access service edge + SOC
 */

import type { InfraNodeType } from '@/types/infra';
import type { ComponentRelationship } from '../types';
import {
  NIST_800_53,
  NIST_800_63B,
  NIST_800_77,
  NIST_800_144,
  NIST_800_145,
  NIST_800_207,
  CIS_V8_13,
  AWS_WAF_REL,
  AZURE_CAF,
  GCP_ARCH_FRAMEWORK,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// Hybrid/Multi-Cloud Relationships (REL-HYB-001 ~ REL-HYB-006)
// ---------------------------------------------------------------------------

export const hybridRelationships: ComponentRelationship[] = [
  {
    id: 'REL-HYB-001',
    type: 'relationship',
    source: 'private-cloud',
    target: 'aws-vpc',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'Hybrid cloud architectures benefit from connectivity between on-premise private cloud and public cloud VPCs',
    reasonKo: '하이브리드 클라우드 아키텍처는 온프레미스 프라이빗 클라우드와 퍼블릭 클라우드 VPC 간 연결이 권장됩니다',
    tags: ['hybrid', 'private-cloud', 'aws', 'connectivity'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_145, 'Section 3 - Cloud Deployment Models')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-HYB-002',
    type: 'relationship',
    source: 'private-cloud',
    target: 'azure-vnet',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'Hybrid deployments should connect private cloud to Azure VNet for workload migration and burst capacity',
    reasonKo: '하이브리드 배포는 워크로드 마이그레이션과 버스트 용량을 위해 프라이빗 클라우드와 Azure VNet 연결이 권장됩니다',
    tags: ['hybrid', 'private-cloud', 'azure', 'migration'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AZURE_CAF, 'Hybrid Cloud Strategy')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-HYB-003',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'vpn-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Cloud VPCs should use VPN gateways for secure Site-to-Site connectivity with on-premise infrastructure',
    reasonKo: '클라우드 VPC는 온프레미스 인프라와의 안전한 Site-to-Site 연결을 위해 VPN 게이트웨이 사용이 권장됩니다',
    tags: ['hybrid', 'aws', 'vpn', 'site-to-site'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Network Connectivity - VPN')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-HYB-004',
    type: 'relationship',
    source: 'azure-vnet',
    target: 'vpn-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Azure VNets should use VPN gateways for hybrid connectivity with ExpressRoute as backup',
    reasonKo: 'Azure VNet은 하이브리드 연결을 위해 VPN 게이트웨이 사용이 권장되며 ExpressRoute를 백업으로 활용합니다',
    tags: ['hybrid', 'azure', 'vpn', 'expressroute'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AZURE_CAF, 'Network - Hybrid Connectivity')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-HYB-005',
    type: 'relationship',
    source: 'aws-vpc',
    target: 'backup',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Multi-cloud architectures should replicate backups across cloud providers for disaster recovery',
    reasonKo: '멀티 클라우드 아키텍처는 재해 복구를 위해 클라우드 공급자 간 백업 복제가 권장됩니다',
    tags: ['hybrid', 'multi-cloud', 'backup', 'disaster-recovery'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Disaster Recovery - Multi-Region')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-HYB-006',
    type: 'relationship',
    source: 'gcp-network',
    target: 'vpn-gateway',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'GCP networks should use Cloud VPN for secure connectivity with on-premise and other cloud environments',
    reasonKo: 'GCP 네트워크는 온프레미스 및 타 클라우드 환경과의 안전한 연결을 위해 Cloud VPN 사용이 권장됩니다',
    tags: ['hybrid', 'gcp', 'vpn', 'multi-cloud'],
    trust: {
      confidence: 0.85,
      sources: [withSection(GCP_ARCH_FRAMEWORK, 'Networking - Hybrid Connectivity')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
];

// ---------------------------------------------------------------------------
// SASE/SOC Relationships (REL-SASE-001 ~ REL-SASE-010)
// ---------------------------------------------------------------------------

export const saseRelationships: ComponentRelationship[] = [
  {
    id: 'REL-SASE-001',
    type: 'relationship',
    source: 'sase-gateway' as InfraNodeType,
    target: 'sd-wan' as InfraNodeType,
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'SASE gateway requires SD-WAN for optimized traffic routing and WAN connectivity',
    reasonKo: 'SASE 게이트웨이는 최적화된 트래픽 라우팅과 WAN 연결을 위해 SD-WAN이 필요합니다',
    tags: ['sase', 'sd-wan', 'wan'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_207, 'Section 4 - SASE Deployment')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-002',
    type: 'relationship',
    source: 'sase-gateway' as InfraNodeType,
    target: 'ztna-broker' as InfraNodeType,
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'SASE gateway should include ZTNA broker for application-level zero trust access',
    reasonKo: 'SASE 게이트웨이는 애플리케이션 수준 제로 트러스트 접근을 위해 ZTNA 브로커 포함을 권장합니다',
    tags: ['sase', 'ztna', 'zero-trust'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_207, 'Section 3 - Zero Trust Architecture Components')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-003',
    type: 'relationship',
    source: 'sase-gateway' as InfraNodeType,
    target: 'casb' as InfraNodeType,
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'SASE architecture should include CASB for cloud application visibility and data protection',
    reasonKo: 'SASE 아키텍처는 클라우드 애플리케이션 가시성과 데이터 보호를 위해 CASB 포함을 권장합니다',
    tags: ['sase', 'casb', 'cloud-security'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_53, 'AC-4 - Information Flow Enforcement')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-004',
    type: 'relationship',
    source: 'ztna-broker' as InfraNodeType,
    target: 'iam' as InfraNodeType,
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'ZTNA broker requires IAM for identity-based access decisions and policy enforcement',
    reasonKo: 'ZTNA 브로커는 ID 기반 접근 결정과 정책 적용을 위해 IAM이 필요합니다',
    tags: ['ztna', 'iam', 'identity'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_207, 'Section 2 - Zero Trust Basics')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-005',
    type: 'relationship',
    source: 'ztna-broker' as InfraNodeType,
    target: 'mfa' as InfraNodeType,
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'ZTNA broker requires MFA for continuous identity verification',
    reasonKo: 'ZTNA 브로커는 지속적 ID 검증을 위해 MFA가 필요합니다',
    tags: ['ztna', 'mfa', 'authentication'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_63B, 'Section 5 - Authenticator Assurance Levels')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-006',
    type: 'relationship',
    source: 'siem' as InfraNodeType,
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'SIEM requires firewall log feeds for network security event correlation',
    reasonKo: 'SIEM은 네트워크 보안 이벤트 상관분석을 위해 방화벽 로그 피드가 필요합니다',
    tags: ['siem', 'firewall', 'log-analysis'],
    trust: {
      confidence: 0.90,
      sources: [withSection(NIST_800_53, 'AU-6 - Audit Review, Analysis, and Reporting')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-007',
    type: 'relationship',
    source: 'siem' as InfraNodeType,
    target: 'ids-ips',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'SIEM should ingest IDS/IPS alerts for comprehensive threat detection',
    reasonKo: 'SIEM은 포괄적 위협 탐지를 위해 IDS/IPS 경보를 수집해야 합니다',
    tags: ['siem', 'ids-ips', 'threat-detection'],
    trust: {
      confidence: 0.90,
      sources: [withSection(CIS_V8_13, 'Network Monitoring and Defense')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-008',
    type: 'relationship',
    source: 'soar' as InfraNodeType,
    target: 'siem' as InfraNodeType,
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'SOAR requires SIEM as primary alert source for automated incident response',
    reasonKo: 'SOAR는 자동 사고 대응을 위한 주요 경보 소스로 SIEM이 필요합니다',
    tags: ['soar', 'siem', 'automation'],
    trust: {
      confidence: 0.90,
      sources: [withSection(NIST_800_53, 'IR-4 - Incident Handling')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-009',
    type: 'relationship',
    source: 'casb' as InfraNodeType,
    target: 'siem' as InfraNodeType,
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'CASB should forward cloud security events to SIEM for centralized monitoring',
    reasonKo: 'CASB는 중앙 집중 모니터링을 위해 클라우드 보안 이벤트를 SIEM에 전달해야 합니다',
    tags: ['casb', 'siem', 'cloud-monitoring'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_144, 'Section 5 - Security')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
  {
    id: 'REL-SASE-010',
    type: 'relationship',
    source: 'sase-gateway' as InfraNodeType,
    target: 'siem' as InfraNodeType,
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'SASE gateway should send security logs to SIEM for visibility and compliance',
    reasonKo: 'SASE 게이트웨이는 가시성과 규정 준수를 위해 보안 로그를 SIEM에 전송해야 합니다',
    tags: ['sase', 'siem', 'logging'],
    trust: {
      confidence: 0.85,
      sources: [withSection(NIST_800_53, 'AU-3 - Content of Audit Records')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-10',
    },
  },
];
