/**
 * Security Relationships - Protections + Conflicts
 *
 * securityProtections: protects / enhances security-focused relationships
 * conflicts: REL-CON forbidden component combinations
 */

import type { ComponentRelationship } from '../types';
import {
  NIST_800_41,
  NIST_800_53,
  NIST_800_63B,
  NIST_800_94,
  NIST_800_123,
  NIST_800_125,
  RFC_7230,
  CIS_V8,
  CIS_V8_12,
  OWASP_TOP10,
  OWASP_WSTG,
  AWS_WAF_PERF,
  CNCF_SECURITY,
  SANS_CIS_TOP20,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// Security Protections (protects / enhances)
// ---------------------------------------------------------------------------

export const securityProtections: ComponentRelationship[] = [
  {
    id: 'REL-SEC-020',
    type: 'relationship',
    source: 'firewall',
    target: 'db-server',
    relationshipType: 'protects',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Firewall enforces network segmentation to isolate database tier from untrusted zones',
    reasonKo: '방화벽은 네트워크 세그먼테이션을 통해 데이터베이스 티어를 비신뢰 구간으로부터 격리합니다',
    tags: ['security', 'firewall', 'database', 'segmentation'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 2.1 - Network Segmentation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-021',
    type: 'relationship',
    source: 'waf',
    target: 'web-server',
    relationshipType: 'protects',
    strength: 'strong',
    direction: 'downstream',
    reason: 'WAF inspects HTTP/S traffic and blocks malicious payloads before they reach the web server',
    reasonKo: 'WAF는 HTTP/S 트래픽을 검사하여 악성 페이로드가 웹 서버에 도달하기 전에 차단합니다',
    tags: ['security', 'waf', 'web-server', 'application-security'],
    trust: {
      confidence: 0.9,
      sources: [OWASP_TOP10, withSection(OWASP_WSTG, 'Configuration and Deployment Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-022',
    type: 'relationship',
    source: 'ids-ips',
    target: 'firewall',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'IDS/IPS adds behavioral analysis and signature-based detection capabilities that complement stateful firewall inspection',
    reasonKo: 'IDS/IPS는 상태 기반 방화벽 검사를 보완하는 행위 분석 및 시그니처 기반 탐지 기능을 추가합니다',
    tags: ['security', 'ids-ips', 'firewall', 'defense-in-depth'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_94, 'Section 2.1 - Uses of IDPS Technologies')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-020',
    type: 'relationship',
    source: 'load-balancer',
    target: 'web-server',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Load balancer distributes incoming traffic across web server instances for improved throughput and fault tolerance',
    reasonKo: '로드 밸런서는 처리량 향상과 내결함성을 위해 웹 서버 인스턴스에 트래픽을 분산합니다',
    tags: ['network', 'load-balancer', 'web-server', 'high-availability'],
    trust: {
      confidence: 1.0,
      sources: [withSection(RFC_7230, 'Section 2.3 - Intermediaries')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-023',
    type: 'relationship',
    source: 'firewall',
    target: 'app-server',
    relationshipType: 'protects',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Firewall controls access to application servers, restricting traffic to only allowed ports and source IPs',
    reasonKo: '방화벽은 애플리케이션 서버에 대한 접근을 제어하여 허용된 포트와 소스 IP로만 트래픽을 제한합니다',
    tags: ['security', 'firewall', 'app-server', 'access-control'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_123, 'Section 5 - Securing the OS and Applications')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-021',
    type: 'relationship',
    source: 'cache',
    target: 'db-server',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'upstream',
    reason: 'Caching layer absorbs repeated read queries, reducing database connection pressure and query latency',
    reasonKo: '캐시 계층은 반복 읽기 쿼리를 흡수하여 데이터베이스 연결 부하와 쿼리 지연을 줄입니다',
    tags: ['performance', 'cache', 'database', 'optimization'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Caching')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-024',
    type: 'relationship',
    source: 'nac',
    target: 'switch-l2',
    relationshipType: 'protects',
    strength: 'strong',
    direction: 'downstream',
    reason: 'NAC enforces 802.1X authentication on switch ports to prevent unauthorized device connections',
    reasonKo: 'NAC는 스위치 포트에서 802.1X 인증을 적용하여 비인가 장치 연결을 방지합니다',
    tags: ['security', 'nac', 'switch', 'port-security'],
    trust: {
      confidence: 0.95,
      sources: [withSection(CIS_V8, 'Control 1 - Inventory and Control of Enterprise Assets')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-SEC-025',
    type: 'relationship',
    source: 'dlp',
    target: 'db-server',
    relationshipType: 'protects',
    strength: 'strong',
    direction: 'upstream',
    reason: 'DLP monitors database query results and file transfers to prevent sensitive data exfiltration',
    reasonKo: 'DLP는 민감 데이터 유출 방지를 위해 데이터베이스 쿼리 결과와 파일 전송을 모니터링합니다',
    tags: ['security', 'dlp', 'database', 'data-loss-prevention'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'AC-4 - Information Flow Enforcement')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-AUTH-020',
    type: 'relationship',
    source: 'mfa',
    target: 'vpn-gateway',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'upstream',
    reason: 'MFA adds a second authentication factor to VPN login, preventing credential stuffing and phishing attacks',
    reasonKo: 'MFA는 VPN 로그인에 2차 인증 요소를 추가하여 크리덴셜 스터핑과 피싱 공격을 방지합니다',
    tags: ['auth', 'mfa', 'vpn', 'credential-protection'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_63B, 'Section 5 - Authenticator and Verifier Requirements')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-AUTH-021',
    type: 'relationship',
    source: 'iam',
    target: 'kubernetes',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'downstream',
    reason: 'IAM provides RBAC integration for Kubernetes, enabling fine-grained pod and namespace access policies',
    reasonKo: 'IAM은 Kubernetes에 RBAC 통합을 제공하여 세분화된 파드 및 네임스페이스 접근 정책을 가능하게 합니다',
    tags: ['auth', 'iam', 'kubernetes', 'rbac'],
    trust: {
      confidence: 0.7,
      sources: [withSection(CNCF_SECURITY, 'Identity and Access Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-NET-022',
    type: 'relationship',
    source: 'cdn',
    target: 'web-server',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'upstream',
    reason: 'CDN caches static assets at edge locations, reducing origin server load and improving global latency',
    reasonKo: 'CDN은 엣지 로케이션에서 정적 자산을 캐시하여 오리진 서버 부하를 줄이고 글로벌 지연을 개선합니다',
    tags: ['network', 'cdn', 'web-server', 'performance', 'edge'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Content Delivery')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
];

// ---------------------------------------------------------------------------
// Conflicts / Forbidden Combinations (conflicts)
// ---------------------------------------------------------------------------

export const conflicts: ComponentRelationship[] = [
  {
    id: 'REL-CON-001',
    type: 'relationship',
    source: 'db-server',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Database servers must never be directly exposed to the internet; this is a critical security vulnerability',
    reasonKo: '데이터베이스 서버는 인터넷에 직접 노출되어서는 안 됩니다. 이는 심각한 보안 취약점입니다',
    tags: ['security', 'database', 'internet', 'critical'],
    trust: {
      confidence: 0.95,
      sources: [
        withSection(NIST_800_41, 'Section 2.1 - Network Segmentation'),
        withSection(NIST_800_123, 'Section 5 - Secure Network Configuration'),
      ],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-002',
    type: 'relationship',
    source: 'ldap-ad',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Directory services (LDAP/AD) must not be internet-accessible; exposes all user credentials to attack',
    reasonKo: '디렉터리 서비스(LDAP/AD)는 인터넷에 접근 가능해서는 안 됩니다. 모든 사용자 자격 증명이 공격에 노출됩니다',
    tags: ['security', 'ldap', 'internet', 'credential-exposure'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'AC-17 - Remote Access')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-003',
    type: 'relationship',
    source: 'san-nas',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'SAN/NAS storage should never be directly accessible from the internet; risks mass data exfiltration',
    reasonKo: 'SAN/NAS 스토리지는 인터넷에서 직접 접근 가능해서는 안 됩니다. 대규모 데이터 유출 위험이 있습니다',
    tags: ['security', 'storage', 'internet', 'data-exfiltration'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'SC-7 - Boundary Protection')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-004',
    type: 'relationship',
    source: 'app-server',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Application servers should not be directly internet-facing; use a reverse proxy or load balancer as frontend',
    reasonKo: '애플리케이션 서버는 인터넷에 직접 노출되면 안 됩니다. 리버스 프록시 또는 로드 밸런서를 프론트엔드로 사용하세요',
    tags: ['security', 'app-server', 'internet', 'reverse-proxy'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_123, 'Section 5.3 - Network Configuration')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-005',
    type: 'relationship',
    source: 'backup',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Backup storage must be isolated from internet access to prevent ransomware attacks on backup data',
    reasonKo: '백업 스토리지는 백업 데이터에 대한 랜섬웨어 공격을 방지하기 위해 인터넷 접근으로부터 격리되어야 합니다',
    tags: ['security', 'backup', 'internet', 'ransomware'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_53, 'CP-9 - Information System Backup')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-006',
    type: 'relationship',
    source: 'switch-l2',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'L2 switches have no routing or filtering capabilities and must not face the internet directly',
    reasonKo: 'L2 스위치는 라우팅이나 필터링 기능이 없으므로 인터넷에 직접 연결되어서는 안 됩니다',
    tags: ['network', 'switch', 'internet', 'architecture'],
    trust: {
      confidence: 0.95,
      sources: [withSection(CIS_V8_12, '12.2 - Secure Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-007',
    type: 'relationship',
    source: 'cache',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'In-memory caches (Redis/Memcached) have weak authentication and must never be internet-exposed',
    reasonKo: '인메모리 캐시(Redis/Memcached)는 인증이 취약하여 인터넷에 노출되어서는 안 됩니다',
    tags: ['security', 'cache', 'internet', 'authentication'],
    trust: {
      confidence: 0.7,
      sources: [withSection(SANS_CIS_TOP20, 'Control 12 - Network Infrastructure Management')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-008',
    type: 'relationship',
    source: 'web-server',
    target: 'db-server',
    relationshipType: 'conflicts',
    strength: 'weak',
    direction: 'downstream',
    reason: 'Web servers should generally not directly access databases; use an application tier for business logic separation (exception: simple LAMP stacks)',
    reasonKo: '웹 서버는 일반적으로 데이터베이스에 직접 접근하면 안 됩니다. 비즈니스 로직 분리를 위해 애플리케이션 티어를 사용하세요 (예외: 단순 LAMP 스택)',
    tags: ['architecture', 'web-server', 'database', 'separation-of-concerns'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_123, 'Section 5 - Application Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-CON-009',
    type: 'relationship',
    source: 'container',
    target: 'internet',
    relationshipType: 'conflicts',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Individual containers should not be directly internet-exposed; use an ingress controller or load balancer',
    reasonKo: '개별 컨테이너는 인터넷에 직접 노출되면 안 됩니다. 인그레스 컨트롤러 또는 로드 밸런서를 사용하세요',
    tags: ['security', 'container', 'internet', 'ingress'],
    trust: {
      confidence: 0.7,
      sources: [withSection(CNCF_SECURITY, 'Runtime Security - Network Policies')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
];
