/**
 * Telecom Relationships (REL-TEL)
 *
 * Dedicated line, PE/P router, MPLS, 5G, central office relationships
 */

import type { ComponentRelationship } from '../types';
import {
  NIST_800_41,
  RFC_3031,
  RFC_4364,
  ITU_G984,
  THREEGPP_23002,
  THREEGPP_38401,
  MEF_4,
  withSection,
} from '../sourceRegistry';

// ---------------------------------------------------------------------------
// Telecom Dependencies (REL-TEL)
// ---------------------------------------------------------------------------

export const telecomDependencies: ComponentRelationship[] = [
  {
    id: 'REL-TEL-001',
    type: 'relationship',
    source: 'dedicated-line',
    target: 'pe-router',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'CE-PE connection requires a PE router to terminate the dedicated line into the MPLS/VPN backbone',
    reasonKo: '전용회선의 CE-PE 연결은 MPLS/VPN 백본으로 종단하기 위해 PE 라우터가 필수입니다',
    tags: ['telecom', 'dedicated-line', 'pe-router', 'mpls'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_4364, 'Section 4 - CE-PE Connection')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-002',
    type: 'relationship',
    source: 'pe-router',
    target: 'p-router',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'MPLS Label Switched Paths (LSPs) require P routers as the backbone transit infrastructure',
    reasonKo: 'MPLS LSP(Label Switched Path)는 백본 전송 인프라로 P 라우터가 필수입니다',
    tags: ['telecom', 'pe-router', 'p-router', 'mpls', 'backbone'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_3031, 'Section 2.2 - Label Switching')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-003',
    type: 'relationship',
    source: 'pe-router',
    target: 'firewall',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'Security boundary between WAN (PE router) and internal network requires firewall enforcement',
    reasonKo: 'WAN(PE 라우터)과 내부 네트워크 간 보안 경계에는 방화벽 적용이 권장됩니다',
    tags: ['telecom', 'pe-router', 'firewall', 'wan-security'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 2.1 - Network Segmentation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-004',
    type: 'relationship',
    source: 'base-station',
    target: 'core-network',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: '5G gNB (base station) requires connection to the 5G Core network for control and user plane functions',
    reasonKo: '5G gNB(기지국)는 제어 플레인 및 사용자 플레인 기능을 위해 5G 코어 네트워크 연결이 필수입니다',
    tags: ['telecom', '5g', 'base-station', 'core-network'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_38401, 'Section 6 - NG-RAN Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-005',
    type: 'relationship',
    source: 'core-network',
    target: 'upf',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'UPF (User Plane Function) is a mandatory component of the 5G Core for user data routing and forwarding',
    reasonKo: 'UPF(User Plane Function)는 사용자 데이터 라우팅 및 포워딩을 위한 5G 코어의 필수 구성요소입니다',
    tags: ['telecom', '5g', 'core-network', 'upf'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_23002, 'Section 4 - Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-006',
    type: 'relationship',
    source: 'upf',
    target: 'idc',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'UPF data path must connect to a data center (IDC) for application and content delivery',
    reasonKo: 'UPF 데이터 경로는 애플리케이션 및 콘텐츠 전달을 위해 IDC(데이터센터)와 연결이 필수입니다',
    tags: ['telecom', '5g', 'upf', 'idc', 'data-path'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_23002, 'Section 4 - Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-007',
    type: 'relationship',
    source: 'customer-premise',
    target: 'dedicated-line',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Customer premise equipment (CE) connects to the carrier network via a leased/dedicated line',
    reasonKo: '고객 구내 장비(CE)는 전용회선을 통해 캐리어 네트워크에 연결됩니다',
    tags: ['telecom', 'customer-premise', 'dedicated-line', 'ce'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_4364, 'Section 4 - CE-PE Connection')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-008',
    type: 'relationship',
    source: 'dedicated-line',
    target: 'central-office',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Dedicated lines physically terminate at the central office (CO/POP) for carrier network access',
    reasonKo: '전용회선은 캐리어 네트워크 접속을 위해 국사(CO/POP)에서 물리적으로 종단됩니다',
    tags: ['telecom', 'dedicated-line', 'central-office', 'physical'],
    trust: {
      confidence: 0.85,
      sources: [withSection(MEF_4, 'Metro Ethernet Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-009',
    type: 'relationship',
    source: 'olt',
    target: 'central-office',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'OLT (Optical Line Terminal) resides in the central office as part of the GPON infrastructure',
    reasonKo: 'OLT(광선로 단말)는 GPON 인프라의 일부로 국사 내에 설치됩니다',
    tags: ['telecom', 'olt', 'central-office', 'gpon'],
    trust: {
      confidence: 0.85,
      sources: [ITU_G984],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-010',
    type: 'relationship',
    source: 'mpls-network',
    target: 'p-router',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'An MPLS network is composed of P routers that perform label switching in the backbone',
    reasonKo: 'MPLS 망은 백본에서 레이블 스위칭을 수행하는 P 라우터로 구성됩니다',
    tags: ['telecom', 'mpls-network', 'p-router', 'backbone'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_3031, 'Section 2.2 - Label Switching')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-011',
    type: 'relationship',
    source: 'ring-network',
    target: 'central-office',
    relationshipType: 'enhances',
    strength: 'strong',
    direction: 'bidirectional',
    reason: 'Ring topology provides redundant physical paths between central offices for high availability',
    reasonKo: '링 토폴로지는 국사 간 이중화된 물리 경로를 제공하여 고가용성을 확보합니다',
    tags: ['telecom', 'ring-network', 'central-office', 'redundancy'],
    trust: {
      confidence: 0.85,
      sources: [withSection(MEF_4, 'Metro Ethernet Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-012',
    type: 'relationship',
    source: 'corporate-internet',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Corporate internet boundary requires firewall for perimeter defense against external threats',
    reasonKo: '기업인터넷 경계는 외부 위협에 대한 경계 방어를 위해 방화벽이 필수입니다',
    tags: ['telecom', 'corporate-internet', 'firewall', 'perimeter'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 2.1 - Network Segmentation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-013',
    type: 'relationship',
    source: 'vpn-service',
    target: 'pe-router',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'BGP/MPLS VPN service depends on PE routers for VRF instantiation and route distribution',
    reasonKo: 'BGP/MPLS VPN 서비스는 VRF 인스턴스화 및 경로 분배를 위해 PE 라우터가 필수입니다',
    tags: ['telecom', 'vpn-service', 'pe-router', 'mpls-vpn'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_4364, 'Section 4.3 - VRF')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-014',
    type: 'relationship',
    source: 'metro-ethernet',
    target: 'pe-router',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Metro Ethernet service is delivered through PE routers at the carrier network edge',
    reasonKo: '메트로 이더넷 서비스는 캐리어 네트워크 엣지의 PE 라우터를 통해 제공됩니다',
    tags: ['telecom', 'metro-ethernet', 'pe-router', 'carrier'],
    trust: {
      confidence: 0.85,
      sources: [MEF_4],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-015',
    type: 'relationship',
    source: 'sd-wan-service',
    target: 'corporate-internet',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'downstream',
    reason: 'SD-WAN hybrid architecture leverages corporate internet as an underlay transport for cost-effective connectivity',
    reasonKo: 'SD-WAN 하이브리드 아키텍처는 비용 효율적인 연결을 위해 기업인터넷을 언더레이 전송으로 활용합니다',
    tags: ['telecom', 'sd-wan-service', 'corporate-internet', 'hybrid'],
    trust: {
      confidence: 0.85,
      sources: [withSection(MEF_4, 'Metro Ethernet Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-016',
    type: 'relationship',
    source: 'private-5g',
    target: 'upf',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Private 5G network requires a local UPF for on-premise data routing without traversing the public core',
    reasonKo: '5G 특화망은 공용 코어를 거치지 않는 온프레미스 데이터 라우팅을 위해 로컬 UPF가 필수입니다',
    tags: ['telecom', 'private-5g', 'upf', 'local-breakout'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_23002, 'Section 4 - Network Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-017',
    type: 'relationship',
    source: 'private-5g',
    target: 'base-station',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'Private 5G network requires gNB (base station) for radio access to end devices',
    reasonKo: '5G 특화망은 단말기 무선 접속을 위해 gNB(기지국)가 필수입니다',
    tags: ['telecom', 'private-5g', 'base-station', 'radio-access'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_38401, 'Section 6 - NG-RAN Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-018',
    type: 'relationship',
    source: 'idc',
    target: 'firewall',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'downstream',
    reason: 'IDC (Internet Data Center) security boundary requires firewall to protect hosted services and data',
    reasonKo: 'IDC(인터넷 데이터센터) 보안 경계는 호스팅 서비스와 데이터를 보호하기 위해 방화벽이 필수입니다',
    tags: ['telecom', 'idc', 'firewall', 'security-boundary'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 2.1 - Network Segmentation')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-019',
    type: 'relationship',
    source: 'central-office',
    target: 'p-router',
    relationshipType: 'recommends',
    strength: 'strong',
    direction: 'upstream',
    reason: 'Central offices connect to the backbone network via P routers for inter-CO traffic forwarding',
    reasonKo: '국사는 국사 간 트래픽 전달을 위해 P 라우터를 통해 백본 네트워크에 연결이 권장됩니다',
    tags: ['telecom', 'central-office', 'p-router', 'backbone'],
    trust: {
      confidence: 0.95,
      sources: [withSection(RFC_3031, 'Section 2.2 - Label Switching')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
  {
    id: 'REL-TEL-020',
    type: 'relationship',
    source: 'base-station',
    target: 'central-office',
    relationshipType: 'requires',
    strength: 'mandatory',
    direction: 'upstream',
    reason: 'Base station backhaul traffic is physically connected to the central office for aggregation and transport',
    reasonKo: '기지국 백홀 트래픽은 집선 및 전송을 위해 국사에 물리적으로 연결됩니다',
    tags: ['telecom', 'base-station', 'central-office', 'backhaul'],
    trust: {
      confidence: 0.85,
      sources: [withSection(THREEGPP_38401, 'Section 6 - NG-RAN Architecture')],
      upvotes: 0,
      downvotes: 0,
      lastReviewedAt: '2026-02-09',
    },
  },
];
