import { describe, it, expect } from 'vitest';
import { exportToTerraform, type TerraformExportOptions } from '@/lib/export/terraformExport';
import type { InfraSpec, InfraNodeSpec } from '@/types';

describe('TerraformExport', () => {
  // Helper to create a basic InfraSpec
  const createSpec = (nodes: InfraNodeSpec[], connections: { source: string; target: string }[] = []): InfraSpec => ({
    nodes,
    connections,
  });

  // Helper to create a node
  const createNode = (id: string, type: InfraNodeSpec['type'], label: string, zone?: string): InfraNodeSpec => ({
    id,
    type,
    label,
    zone,
  });

  describe('exportToTerraform', () => {
    describe('Basic Export', () => {
      it('should generate valid HCL for firewall', () => {
        const spec = createSpec([createNode('fw-1', 'firewall', 'Main Firewall')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_security_group');
        expect(result).toContain('fw_1');
        expect(result).toContain('Main Firewall');
        expect(result).toContain('ingress');
        expect(result).toContain('egress');
      });

      it('should generate valid HCL for load-balancer', () => {
        const spec = createSpec([createNode('lb-1', 'load-balancer', 'Application LB', 'internal')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_lb');
        expect(result).toContain('lb_1');
        expect(result).toContain('Application LB');
        expect(result).toContain('aws_lb_target_group');
        expect(result).toContain('aws_lb_listener');
        expect(result).toContain('internal           = true');
      });

      it('should generate valid HCL for web-server', () => {
        const spec = createSpec([createNode('web-1', 'web-server', 'Web Server', 'dmz')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_instance');
        expect(result).toContain('web_1');
        expect(result).toContain('Web Server');
        expect(result).toContain('Tier = "web"');
      });

      it('should generate valid HCL for db-server', () => {
        const spec = createSpec([createNode('db-1', 'db-server', 'Database')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_db_instance');
        expect(result).toContain('db_1');
        expect(result).toContain('Database');
        expect(result).toContain('engine');
        expect(result).toContain('mysql');
      });

      it('should generate valid HCL for WAF', () => {
        const spec = createSpec([createNode('waf-1', 'waf', 'Web Application Firewall')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_wafv2_web_acl');
        expect(result).toContain('waf_1');
        expect(result).toContain('AWSManagedRulesCommonRuleSet');
        expect(result).toContain('visibility_config');
      });
    });

    describe('Empty Spec Handling', () => {
      it('should handle empty spec', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec);

        expect(result).toContain('Terraform configuration generated by InfraFlow');
        expect(result).toContain('terraform {');
        expect(result).toContain('required_providers');
        expect(result).toContain('# ============= Resources =============');
      });

      it('should include header comment with timestamp', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec);

        expect(result).toContain('# Terraform configuration generated by InfraFlow');
        expect(result).toContain('# Provider: AWS');
        expect(result).toContain('# Generated:');
      });
    });

    describe('Provider Support', () => {
      it('should generate AWS provider block', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { provider: 'aws', region: 'us-east-1' });

        expect(result).toContain('provider "aws"');
        expect(result).toContain('region = "us-east-1"');
        expect(result).toContain('hashicorp/aws');
      });

      it('should generate Azure provider block', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { provider: 'azure' });

        expect(result).toContain('provider "azurerm"');
        expect(result).toContain('hashicorp/azurerm');
        expect(result).toContain('features {}');
      });

      it('should generate GCP provider block', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { provider: 'gcp', region: 'us-central1' });

        expect(result).toContain('provider "google"');
        expect(result).toContain('hashicorp/google');
        expect(result).toContain('region  = "us-central1"');
      });

      it('should use ap-northeast-2 as default region', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec);

        expect(result).toContain('region = "ap-northeast-2"');
      });
    });

    describe('Variables Block', () => {
      it('should include variables when includeVariables is true', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { includeVariables: true });

        expect(result).toContain('variable "db_username"');
        expect(result).toContain('variable "db_password"');
        expect(result).toContain('variable "project_id"');
        expect(result).toContain('sensitive   = true');
      });

      it('should exclude variables when includeVariables is false', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { includeVariables: false });

        expect(result).not.toContain('variable "db_username"');
        expect(result).not.toContain('variable "db_password"');
      });
    });

    describe('Outputs Block', () => {
      it('should include outputs when includeOutputs is true', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { includeOutputs: true });

        expect(result).toContain('# ============= Outputs =============');
        expect(result).toContain('output "vpc_id"');
        expect(result).toContain('value       = aws_vpc.main.id');
      });

      it('should exclude outputs when includeOutputs is false', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec, { includeOutputs: false });

        expect(result).not.toContain('output "vpc_id"');
      });
    });

    describe('All Required Resources', () => {
      it('should include all required resources for 3-tier architecture', () => {
        const spec = createSpec([
          createNode('web-1', 'web-server', 'Web Server'),
          createNode('app-1', 'app-server', 'App Server'),
          createNode('db-1', 'db-server', 'Database'),
          createNode('lb-1', 'load-balancer', 'Load Balancer'),
        ]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        // Verify all components are present
        expect(result).toContain('aws_instance');
        expect(result).toContain('aws_db_instance');
        expect(result).toContain('aws_lb');
        expect(result).toContain('web_1');
        expect(result).toContain('app_1');
        expect(result).toContain('db_1');
        expect(result).toContain('lb_1');
      });

      it('should generate resources for cloud components', () => {
        const spec = createSpec([
          createNode('vpc-1', 'aws-vpc', 'Main VPC'),
          createNode('vnet-1', 'azure-vnet', 'Azure VNet'),
          createNode('gcp-net-1', 'gcp-network', 'GCP Network'),
        ]);
        const result = exportToTerraform(spec);

        expect(result).toContain('aws_vpc');
        expect(result).toContain('azurerm_virtual_network');
        expect(result).toContain('google_compute_network');
      });

      it('should generate resources for storage components', () => {
        const spec = createSpec([
          createNode('s3-1', 'object-storage', 'S3 Bucket'),
          createNode('efs-1', 'san-nas', 'EFS Storage'),
          createNode('redis-1', 'cache', 'Redis Cache'),
        ]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_s3_bucket');
        expect(result).toContain('aws_efs_file_system');
        expect(result).toContain('aws_elasticache_cluster');
      });

      it('should generate resources for network components', () => {
        const spec = createSpec([
          createNode('router-1', 'router', 'Main Router'),
          createNode('dns-1', 'dns', 'Route53'),
          createNode('cdn-1', 'cdn', 'CloudFront'),
          createNode('vpn-1', 'vpn-gateway', 'VPN Gateway'),
        ]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_route_table');
        expect(result).toContain('aws_route53_zone');
        expect(result).toContain('aws_cloudfront_distribution');
        expect(result).toContain('aws_vpn_gateway');
      });

      it('should generate resources for compute components', () => {
        const spec = createSpec([
          createNode('k8s-1', 'kubernetes', 'EKS Cluster'),
          createNode('ecs-1', 'container', 'ECS Cluster'),
          createNode('vm-1', 'vm', 'EC2 Instance'),
        ]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_eks_cluster');
        expect(result).toContain('aws_ecs_cluster');
        expect(result).toContain('aws_instance');
      });

      it('should generate resources for auth components', () => {
        const spec = createSpec([
          createNode('iam-1', 'iam', 'IAM Role'),
        ]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('aws_iam_role');
        expect(result).toContain('assume_role_policy');
      });
    });

    describe('Node ID Sanitization', () => {
      it('should sanitize node IDs for Terraform resource names', () => {
        const spec = createSpec([createNode('my-firewall-1', 'firewall', 'My Firewall')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('my_firewall_1');
        expect(result).not.toContain('"my-firewall-1"');
      });

      it('should handle special characters in node IDs', () => {
        const spec = createSpec([createNode('fw@special#id!', 'firewall', 'Special Firewall')]);
        const result = exportToTerraform(spec, { provider: 'aws' });

        expect(result).toContain('fw_special_id_');
      });
    });

    describe('Unknown Node Types', () => {
      it('should add comment for unknown node types', () => {
        const spec: InfraSpec = {
          nodes: [
            { id: 'unknown-1', type: 'zone' as any, label: 'Unknown Zone' },
          ],
          connections: [],
        };
        const result = exportToTerraform(spec);

        expect(result).toContain('# Zone: Unknown Zone');
      });
    });

    describe('Non-AWS Provider Fallback', () => {
      it('should generate comments for non-AWS resources', () => {
        const spec = createSpec([
          createNode('fw-1', 'firewall', 'Firewall'),
          createNode('lb-1', 'load-balancer', 'LB'),
        ]);
        const result = exportToTerraform(spec, { provider: 'azure' });

        expect(result).toContain('# Firewall: Firewall');
        expect(result).toContain('# Load Balancer: LB');
      });
    });

    describe('Zone Assignment', () => {
      it('should use correct subnet based on zone', () => {
        const specDMZ = createSpec([createNode('web-1', 'web-server', 'Web Server', 'dmz')]);
        const resultDMZ = exportToTerraform(specDMZ, { provider: 'aws' });
        expect(resultDMZ).toContain('subnet.public');

        const specInternal = createSpec([createNode('app-1', 'app-server', 'App Server', 'internal')]);
        const resultInternal = exportToTerraform(specInternal, { provider: 'aws' });
        expect(resultInternal).toContain('subnet.private');
      });
    });

    describe('Options Configuration', () => {
      it('should apply default options correctly', () => {
        const spec = createSpec([]);
        const result = exportToTerraform(spec);

        // Default provider is AWS
        expect(result).toContain('provider "aws"');
        // Default region is ap-northeast-2
        expect(result).toContain('ap-northeast-2');
        // Default includeVariables is true
        expect(result).toContain('variable "db_username"');
        // Default includeOutputs is true
        expect(result).toContain('output "vpc_id"');
      });

      it('should apply custom options correctly', () => {
        const spec = createSpec([]);
        const options: TerraformExportOptions = {
          provider: 'gcp',
          region: 'europe-west1',
          includeVariables: false,
          includeOutputs: false,
        };
        const result = exportToTerraform(spec, options);

        expect(result).toContain('provider "google"');
        expect(result).toContain('europe-west1');
        expect(result).not.toContain('variable "db_username"');
        expect(result).not.toContain('output "vpc_id"');
      });
    });
  });
});
