/**
 * InfraFlow - PDF Report Generator
 *
 * 상세 PDF 보고서 생성 (메타데이터, 보안분석, 비용, 규정준수)
 */

import type { InfraSpec } from '@/types';
import { runSecurityAudit, checkAllCompliance, type SecurityAuditResult, type ComplianceReport } from '@/lib/audit';
import { estimateCost, compareCosts, formatCost, type CostBreakdown, type CloudProvider } from '@/lib/cost';

export interface ReportMetadata {
  title: string;
  author?: string;
  organization?: string;
  version?: string;
  createdAt: string;
}

export interface PDFReportOptions {
  metadata: ReportMetadata;
  includeArchitecture: boolean;
  includeSecurityAudit: boolean;
  includeCompliance: boolean;
  includeCostEstimate: boolean;
  provider?: CloudProvider;
  currency?: 'USD' | 'KRW';
  diagramImage?: string; // Base64 data URL
}

export interface ReportSection {
  title: string;
  content: string[];
  tables?: ReportTable[];
}

export interface ReportTable {
  headers: string[];
  rows: string[][];
}

/**
 * Generate comprehensive PDF report
 */
export async function generatePDFReport(
  spec: InfraSpec,
  options: PDFReportOptions
): Promise<Blob> {
  const { jsPDF } = await import('jspdf');

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = margin;

  // Helper functions
  const addNewPage = () => {
    pdf.addPage();
    yPos = margin;
  };

  const checkPageBreak = (neededHeight: number) => {
    if (yPos + neededHeight > pageHeight - margin) {
      addNewPage();
    }
  };

  const drawLine = () => {
    pdf.setDrawColor(200);
    pdf.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 5;
  };

  // ===== Cover Page =====
  pdf.setFillColor(24, 24, 27); // zinc-900
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(28);
  pdf.text(options.metadata.title || 'InfraFlow Report', pageWidth / 2, 80, { align: 'center' });

  // Subtitle
  pdf.setFontSize(14);
  pdf.setTextColor(156, 163, 175); // gray-400
  pdf.text('Infrastructure Architecture Report', pageWidth / 2, 95, { align: 'center' });

  // Diagram thumbnail if provided
  if (options.diagramImage) {
    try {
      pdf.addImage(options.diagramImage, 'PNG', margin + 20, 110, contentWidth - 40, 80);
    } catch {
      // Skip if image fails
    }
  }

  // Metadata
  yPos = 210;
  pdf.setFontSize(10);
  pdf.setTextColor(156, 163, 175);

  if (options.metadata.organization) {
    pdf.text(`Organization: ${options.metadata.organization}`, margin, yPos);
    yPos += 6;
  }
  if (options.metadata.author) {
    pdf.text(`Author: ${options.metadata.author}`, margin, yPos);
    yPos += 6;
  }
  if (options.metadata.version) {
    pdf.text(`Version: ${options.metadata.version}`, margin, yPos);
    yPos += 6;
  }
  pdf.text(`Generated: ${options.metadata.createdAt}`, margin, yPos);
  yPos += 6;
  pdf.text(`Generated by InfraFlow`, margin, yPos);

  // ===== Content Pages =====
  addNewPage();
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Table of Contents
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(18);
  pdf.text('Table of Contents', margin, yPos);
  yPos += 12;

  pdf.setFontSize(11);
  const tocItems: string[] = ['1. Executive Summary'];
  if (options.includeArchitecture) tocItems.push('2. Architecture Overview');
  if (options.includeSecurityAudit) tocItems.push('3. Security Audit');
  if (options.includeCompliance) tocItems.push('4. Compliance Status');
  if (options.includeCostEstimate) tocItems.push('5. Cost Estimation');

  for (const item of tocItems) {
    pdf.text(item, margin + 5, yPos);
    yPos += 7;
  }

  drawLine();
  yPos += 10;

  // ===== Executive Summary =====
  pdf.setFontSize(16);
  pdf.text('1. Executive Summary', margin, yPos);
  yPos += 10;

  pdf.setFontSize(10);
  const summaryText = [
    `This report provides a comprehensive analysis of the infrastructure architecture.`,
    ``,
    `Architecture Statistics:`,
    `- Total Components: ${spec.nodes.length}`,
    `- Total Connections: ${spec.connections.length}`,
    `- Security Components: ${spec.nodes.filter((n) => ['firewall', 'waf', 'ids-ips', 'nac', 'dlp', 'vpn-gateway'].includes(n.type)).length}`,
    `- Network Components: ${spec.nodes.filter((n) => ['router', 'switch-l2', 'switch-l3', 'load-balancer', 'cdn', 'dns'].includes(n.type)).length}`,
    `- Compute Components: ${spec.nodes.filter((n) => ['web-server', 'app-server', 'db-server', 'vm', 'container', 'kubernetes'].includes(n.type)).length}`,
  ];

  for (const line of summaryText) {
    checkPageBreak(6);
    pdf.text(line, margin, yPos);
    yPos += 5;
  }

  yPos += 10;

  // ===== Architecture Overview =====
  if (options.includeArchitecture) {
    checkPageBreak(40);
    pdf.setFontSize(16);
    pdf.text('2. Architecture Overview', margin, yPos);
    yPos += 10;

    // Component list
    pdf.setFontSize(10);
    pdf.text('Components:', margin, yPos);
    yPos += 6;

    const componentsByType: Record<string, string[]> = {};
    for (const node of spec.nodes) {
      if (!componentsByType[node.type]) {
        componentsByType[node.type] = [];
      }
      componentsByType[node.type].push(node.label);
    }

    for (const [type, labels] of Object.entries(componentsByType)) {
      checkPageBreak(6);
      pdf.text(`  - ${type}: ${labels.join(', ')}`, margin, yPos);
      yPos += 5;
    }

    yPos += 10;
  }

  // ===== Security Audit =====
  if (options.includeSecurityAudit) {
    const auditResult = runSecurityAudit(spec);

    checkPageBreak(40);
    pdf.setFontSize(16);
    pdf.text('3. Security Audit', margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.text(`Summary:`, margin, yPos);
    yPos += 6;
    pdf.text(`  - Critical: ${auditResult.summary.critical}`, margin, yPos);
    yPos += 5;
    pdf.text(`  - High: ${auditResult.summary.high}`, margin, yPos);
    yPos += 5;
    pdf.text(`  - Medium: ${auditResult.summary.medium}`, margin, yPos);
    yPos += 5;
    pdf.text(`  - Low: ${auditResult.summary.low}`, margin, yPos);
    yPos += 10;

    if (auditResult.findings.length > 0) {
      pdf.text('Findings:', margin, yPos);
      yPos += 6;

      for (const finding of auditResult.findings.slice(0, 10)) {
        checkPageBreak(15);
        pdf.setTextColor(
          finding.severity === 'critical' ? 220 :
          finding.severity === 'high' ? 234 :
          finding.severity === 'medium' ? 234 : 59,
          finding.severity === 'critical' ? 38 :
          finding.severity === 'high' ? 88 :
          finding.severity === 'medium' ? 179 : 130,
          finding.severity === 'critical' ? 38 :
          finding.severity === 'high' ? 12 :
          finding.severity === 'medium' ? 8 : 246
        );
        pdf.text(`  [${finding.severity.toUpperCase()}] ${finding.title}`, margin, yPos);
        pdf.setTextColor(100, 100, 100);
        yPos += 4;
        const descLines = pdf.splitTextToSize(`    ${finding.description}`, contentWidth - 10);
        for (const line of descLines) {
          checkPageBreak(5);
          pdf.text(line, margin, yPos);
          yPos += 4;
        }
        yPos += 3;
      }
      pdf.setTextColor(0, 0, 0);
    } else {
      pdf.text('No security issues found.', margin, yPos);
      yPos += 6;
    }

    yPos += 10;
  }

  // ===== Compliance Status =====
  if (options.includeCompliance) {
    const complianceReports = checkAllCompliance(spec);

    checkPageBreak(40);
    pdf.setFontSize(16);
    pdf.text('4. Compliance Status', margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);

    for (const report of complianceReports) {
      checkPageBreak(20);
      const scoreColor = report.score >= 80 ? [34, 197, 94] :
                        report.score >= 60 ? [234, 179, 8] : [239, 68, 68];
      pdf.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
      pdf.text(`${report.frameworkName}: ${report.score}%`, margin, yPos);
      pdf.setTextColor(100, 100, 100);
      pdf.text(`  (Pass: ${report.passed}, Fail: ${report.failed}, Partial: ${report.partial})`, margin + 60, yPos);
      yPos += 6;
    }

    pdf.setTextColor(0, 0, 0);
    yPos += 10;
  }

  // ===== Cost Estimation =====
  if (options.includeCostEstimate) {
    const provider = options.provider || 'aws';
    const currency = options.currency || 'USD';
    const costBreakdown = estimateCost(spec, { provider, currency });
    const comparison = compareCosts(spec);

    checkPageBreak(50);
    pdf.setFontSize(16);
    pdf.text('5. Cost Estimation', margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.text(`Provider: ${provider.toUpperCase()}`, margin, yPos);
    yPos += 6;

    pdf.setFontSize(12);
    pdf.text(`Monthly Cost: ${formatCost(costBreakdown.totalMonthlyCost, currency)}`, margin, yPos);
    yPos += 6;
    pdf.text(`Yearly Cost: ${formatCost(costBreakdown.totalYearlyCost, currency)}`, margin, yPos);
    yPos += 10;

    pdf.setFontSize(10);
    pdf.text('Cost by Category:', margin, yPos);
    yPos += 6;

    for (const [category, cost] of Object.entries(costBreakdown.byCategory)) {
      if (cost > 0) {
        checkPageBreak(5);
        pdf.text(`  - ${category}: ${formatCost(cost, currency)}`, margin, yPos);
        yPos += 5;
      }
    }

    yPos += 8;
    pdf.text('Provider Comparison (Monthly):', margin, yPos);
    yPos += 6;

    for (const [prov, breakdown] of Object.entries(comparison)) {
      checkPageBreak(5);
      pdf.text(`  - ${prov.toUpperCase()}: ${formatCost(breakdown.totalMonthlyCost, currency)}`, margin, yPos);
      yPos += 5;
    }
  }

  // ===== Footer on all pages =====
  const totalPages = pdf.getNumberOfPages();
  for (let i = 2; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`InfraFlow Report - Page ${i - 1} of ${totalPages - 1}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    pdf.text(options.metadata.createdAt, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  return pdf.output('blob');
}

/**
 * Quick export with default options
 */
export function getDefaultReportOptions(): PDFReportOptions {
  return {
    metadata: {
      title: 'Infrastructure Architecture Report',
      createdAt: new Date().toLocaleDateString('ko-KR', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      }),
    },
    includeArchitecture: true,
    includeSecurityAudit: true,
    includeCompliance: true,
    includeCostEstimate: true,
    provider: 'aws',
    currency: 'KRW',
  };
}
