/**
 * Network Failures (FAIL-NET-001 ~ FAIL-NET-010)
 */

import type { FailureScenario } from '../types';
import {
  withSection,
  NIST_800_41,
  NIST_800_53,
  NIST_800_81,
  CIS_V8_12,
  OWASP_TOP10,
  AWS_WAF_REL,
  AWS_WAF_PERF,
} from '../sourceRegistry';

export const NETWORK_FAILURES: FailureScenario[] = [
  {
    id: 'FAIL-NET-001',
    type: 'failure',
    component: 'firewall',
    titleKo: '방화벽 상태 테이블 고갈',
    scenarioKo:
      '대량의 동시 연결(DDoS, SYN Flood 등)로 인해 방화벽의 상태 테이블(session table)이 가득 차서 새로운 연결을 수립할 수 없게 되는 장애. 정상 트래픽까지 차단되어 전체 서비스가 중단될 수 있습니다.',
    impact: 'service-down',
    likelihood: 'medium',
    affectedComponents: ['web-server', 'app-server', 'load-balancer', 'dns'],
    preventionKo: [
      '방화벽 상태 테이블 크기를 모니터링하고 임계치(80%) 경보를 설정합니다',
      'DDoS 방어 솔루션을 방화벽 앞단에 배치합니다',
      '유휴 세션 타임아웃을 적절히 짧게 설정합니다(기본값보다 30~50% 단축)',
    ],
    mitigationKo: [
      '비정상 연결을 식별하여 긴급 차단 정책을 적용합니다',
      '방화벽 바이패스 모드를 활성화하여 핵심 서비스 트래픽만 허용합니다',
      '상태 테이블 크기를 동적으로 확장하거나 HA 페일오버를 트리거합니다',
    ],
    estimatedMTTR: '15분~1시간',
    tags: ['network', 'firewall', 'ddos', 'state-table', 'availability'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_41, 'Section 4.1 - Stateful Inspection Firewalls')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-002',
    type: 'failure',
    component: 'dns',
    titleKo: 'DNS 포이즈닝 공격',
    scenarioKo:
      '공격자가 DNS 캐시에 위조된 레코드를 삽입하여 사용자를 악성 서버로 리디렉션시키는 공격. 피싱, 데이터 탈취, 중간자 공격의 진입점이 됩니다.',
    impact: 'security-breach',
    likelihood: 'medium',
    affectedComponents: ['web-server', 'load-balancer', 'cdn'],
    preventionKo: [
      'DNSSEC를 구현하여 DNS 응답의 무결성을 검증합니다',
      'DNS 트래픽을 모니터링하고 비정상 쿼리 패턴을 탐지합니다',
      'DNS 서버 소프트웨어를 최신 버전으로 유지합니다',
    ],
    mitigationKo: [
      '오염된 DNS 캐시를 즉시 플러시합니다',
      '영향받는 도메인의 DNS 레코드를 수동으로 검증하고 복원합니다',
      '임시로 신뢰할 수 있는 외부 DNS 리졸버로 전환합니다',
    ],
    estimatedMTTR: '30분~2시간',
    tags: ['network', 'dns', 'poisoning', 'security', 'dnssec'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_81, 'Section 7 - Securing DNS')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-003',
    type: 'failure',
    component: 'dns',
    titleKo: 'DNS 서버 장애',
    scenarioKo:
      'DNS 서버가 하드웨어 고장, 소프트웨어 오류, 또는 DDoS 공격으로 응답 불가 상태가 됩니다. 모든 도메인 이름 해석이 실패하여 사실상 전체 네트워크 서비스가 중단됩니다.',
    impact: 'service-down',
    likelihood: 'low',
    affectedComponents: ['web-server', 'app-server', 'load-balancer', 'cdn', 'vpn-gateway'],
    preventionKo: [
      '이중화된 DNS 서버를 서로 다른 네트워크 세그먼트에 배치합니다',
      'DNS 서버의 헬스체크와 자동 페일오버를 구성합니다',
      '내부 DNS와 외부 DNS를 분리하여 운영합니다',
    ],
    mitigationKo: [
      '보조 DNS 서버로 자동 페일오버를 실행합니다',
      '로컬 DNS 캐시 TTL을 연장하여 캐시된 레코드로 임시 운영합니다',
      '핵심 서비스의 IP를 hosts 파일에 직접 등록합니다',
    ],
    estimatedMTTR: '15분~1시간',
    tags: ['network', 'dns', 'outage', 'availability', 'redundancy'],
    trust: {
      confidence: 0.95,
      sources: [withSection(NIST_800_81, 'Section 5 - DNS Architecture')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-004',
    type: 'failure',
    component: 'load-balancer',
    titleKo: '로드밸런서 헬스체크 실패',
    scenarioKo:
      '로드밸런서의 헬스체크 설정 오류 또는 네트워크 지연으로 정상 서버를 비정상으로 판단하여 트래픽 분배에서 제외합니다. 남은 서버에 트래픽이 집중되어 연쇄 장애가 발생할 수 있습니다.',
    impact: 'degraded',
    likelihood: 'high',
    affectedComponents: ['web-server', 'app-server'],
    preventionKo: [
      '헬스체크 임계값(타임아웃, 재시도 횟수)을 보수적으로 설정합니다',
      '헬스체크 엔드포인트가 실제 서비스 상태를 정확히 반영하도록 구현합니다',
      '헬스체크 결과 변경 시 알림을 설정하여 조기 감지합니다',
    ],
    mitigationKo: [
      '헬스체크 설정을 즉시 검토하고 임계값을 완화합니다',
      '수동으로 서버를 정상 풀에 재등록합니다',
      '헬스체크 방식을 TCP에서 HTTP로 전환하거나 반대로 조정합니다',
    ],
    estimatedMTTR: '5분~30분',
    tags: ['network', 'load-balancer', 'health-check', 'availability'],
    trust: {
      confidence: 0.9,
      sources: [withSection(AWS_WAF_REL, 'Health Checks - Best Practices')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-005',
    type: 'failure',
    component: 'router',
    titleKo: '라우터 크래시 및 라우팅 테이블 손상',
    scenarioKo:
      '라우터의 소프트웨어 버그, 메모리 오버플로우, 또는 잘못된 라우팅 업데이트로 인해 라우터가 비정상 종료됩니다. 라우팅 테이블 손상 시 패킷이 올바른 경로로 전달되지 않아 네트워크 분할이 발생합니다.',
    impact: 'service-down',
    likelihood: 'low',
    affectedComponents: ['firewall', 'switch-l3', 'load-balancer', 'web-server'],
    preventionKo: [
      '라우터 이중화(VRRP/HSRP)를 구성하여 자동 페일오버를 보장합니다',
      '라우팅 프로토콜 변경 전 스테이징 환경에서 검증합니다',
      '라우터 메모리 사용률과 CPU 사용률을 모니터링합니다',
    ],
    mitigationKo: [
      '대기 라우터로 페일오버를 트리거합니다',
      '라우팅 테이블을 마지막 정상 백업으로 복원합니다',
      '정적 라우팅을 임시 적용하여 핵심 경로를 복구합니다',
    ],
    estimatedMTTR: '15분~2시간',
    tags: ['network', 'router', 'crash', 'routing', 'availability'],
    trust: {
      confidence: 0.9,
      sources: [withSection(CIS_V8_12, '12.1 - Ensure Network Infrastructure is Up-to-Date')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-006',
    type: 'failure',
    component: 'switch-l2',
    titleKo: '스위치 루프(브로드캐스트 스톰)',
    scenarioKo:
      'STP(Spanning Tree Protocol) 장애 또는 잘못된 케이블 연결로 L2 스위치 간 루프가 발생합니다. 브로드캐스트 프레임이 무한 순환하여 네트워크 대역폭을 소진하고 전체 세그먼트가 마비됩니다.',
    impact: 'service-down',
    likelihood: 'medium',
    affectedComponents: ['switch-l3', 'router', 'web-server', 'app-server', 'db-server'],
    preventionKo: [
      'STP/RSTP를 올바르게 설정하고 BPDU Guard를 활성화합니다',
      '네트워크 토폴로지 변경 시 루프 검증 절차를 수행합니다',
      '스톰 컨트롤(Storm Control)을 모든 접근 포트에 설정합니다',
    ],
    mitigationKo: [
      '루프를 유발하는 포트를 즉시 비활성화합니다',
      'STP 토폴로지를 수동으로 재수렴시킵니다',
      '영향받는 세그먼트의 스위치를 순차적으로 재시작합니다',
    ],
    estimatedMTTR: '10분~1시간',
    tags: ['network', 'switch', 'loop', 'broadcast-storm', 'stp'],
    trust: {
      confidence: 0.9,
      sources: [withSection(CIS_V8_12, '12.2 - Establish and Maintain a Secure Network Architecture')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-007',
    type: 'failure',
    component: 'cdn',
    titleKo: 'CDN 캐시 포이즈닝',
    scenarioKo:
      '공격자가 CDN 캐시에 악성 콘텐츠를 삽입하여 다수의 사용자에게 변조된 콘텐츠를 전달하는 공격. 캐시 키 조작, Host 헤더 인젝션 등의 기법이 사용되며 광범위한 사용자에게 영향을 미칩니다.',
    impact: 'security-breach',
    likelihood: 'low',
    affectedComponents: ['web-server', 'load-balancer'],
    preventionKo: [
      '캐시 키를 명확히 정의하고 불필요한 헤더를 캐시 키에서 제외합니다',
      'Host 헤더 검증을 오리진 서버에서 수행합니다',
      'CDN에서 콘텐츠 무결성 검증(SRI)을 활성화합니다',
    ],
    mitigationKo: [
      '오염된 캐시를 전체 퍼지(purge)합니다',
      'CDN 바이패스 모드로 전환하여 오리진에서 직접 서비스합니다',
      '캐시 TTL을 최소화하고 오리진 응답을 검증합니다',
    ],
    estimatedMTTR: '30분~2시간',
    tags: ['network', 'cdn', 'cache-poisoning', 'security'],
    trust: {
      confidence: 0.85,
      sources: [withSection(OWASP_TOP10, 'A05:2021 - Security Misconfiguration')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-008',
    type: 'failure',
    component: 'sd-wan',
    titleKo: 'SD-WAN 터널 장애',
    scenarioKo:
      'SD-WAN 오버레이 터널이 ISP 장애, 암호화 키 불일치, 또는 컨트롤러 연결 끊김으로 인해 다운됩니다. 원격 지사와의 통신이 차단되고 백업 경로가 없으면 지사 업무가 완전히 중단됩니다.',
    impact: 'service-down',
    likelihood: 'medium',
    affectedComponents: ['router', 'vpn-gateway', 'firewall'],
    preventionKo: [
      '다중 ISP 회선을 확보하여 터널 이중화를 구성합니다',
      'SD-WAN 컨트롤러를 HA(High Availability) 모드로 운영합니다',
      '터널 상태 모니터링 및 자동 경로 전환을 설정합니다',
    ],
    mitigationKo: [
      '대체 ISP 회선을 통해 터널을 재수립합니다',
      '기존 MPLS 또는 VPN 경로로 긴급 전환합니다',
      'SD-WAN 컨트롤러를 재시작하고 터널 설정을 재배포합니다',
    ],
    estimatedMTTR: '15분~2시간',
    tags: ['network', 'sd-wan', 'tunnel', 'wan', 'connectivity'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_REL, 'Network Connectivity - Redundancy')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-009',
    type: 'failure',
    component: 'load-balancer',
    titleKo: '로드밸런서 세션 퍼시스턴스 장애',
    scenarioKo:
      '로드밸런서의 세션 어피니티(Sticky Session) 설정 오류로 인해 사용자 세션이 서로 다른 백엔드 서버로 분산됩니다. 장바구니 손실, 로그인 세션 끊김 등 사용자 경험이 심각하게 저하됩니다.',
    impact: 'degraded',
    likelihood: 'high',
    affectedComponents: ['web-server', 'app-server', 'cache'],
    preventionKo: [
      '세션 상태를 서버 외부(Redis, Memcached)에 저장하여 서버 독립적으로 관리합니다',
      '세션 퍼시스턴스 설정을 정기적으로 검증합니다',
      '세션 방식을 쿠키 기반에서 헤더 기반으로 표준화합니다',
    ],
    mitigationKo: [
      '세션 퍼시스턴스 설정을 즉시 검토하고 수정합니다',
      '외부 세션 스토어(Redis)로 긴급 전환합니다',
      '영향받는 사용자에게 재로그인을 안내합니다',
    ],
    estimatedMTTR: '10분~30분',
    tags: ['network', 'load-balancer', 'session', 'persistence', 'user-experience'],
    trust: {
      confidence: 0.85,
      sources: [withSection(AWS_WAF_PERF, 'Session Management - Load Balancing')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
  {
    id: 'FAIL-NET-010',
    type: 'failure',
    component: 'switch-l3',
    titleKo: 'L3 스위치 ACL 설정 오류',
    scenarioKo:
      'L3 스위치의 ACL(Access Control List) 규칙이 잘못 구성되어 정상 트래픽이 차단되거나 비인가 트래픽이 허용됩니다. 서비스 중단 또는 보안 위협이 동시에 발생할 수 있습니다.',
    impact: 'degraded',
    likelihood: 'high',
    affectedComponents: ['router', 'firewall', 'web-server', 'app-server'],
    preventionKo: [
      'ACL 변경 시 변경 관리(Change Management) 프로세스를 적용합니다',
      'ACL 규칙을 정기적으로 감사하고 불필요한 규칙을 정리합니다',
      'ACL 변경을 스테이징 환경에서 사전 검증합니다',
    ],
    mitigationKo: [
      '직전 ACL 설정으로 롤백합니다',
      '문제가 되는 ACL 규칙을 즉시 비활성화합니다',
      '트래픽 흐름을 모니터링하여 영향 범위를 확인합니다',
    ],
    estimatedMTTR: '5분~30분',
    tags: ['network', 'switch', 'acl', 'misconfiguration', 'access-control'],
    trust: {
      confidence: 0.9,
      sources: [withSection(NIST_800_53, 'AC-4 - Information Flow Enforcement')],
      lastReviewedAt: '2026-02-09',
      upvotes: 0,
      downvotes: 0,
    },
  },
];
