import { describe, it, expect } from 'vitest';
import { exportToKubernetes, type KubernetesExportOptions } from '../kubernetesExport';
import type { InfraSpec, InfraNodeSpec, InfraNodeType } from '@/types/infra';

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

function makeNode(overrides: Partial<InfraNodeSpec> = {}): InfraNodeSpec {
  return {
    id: 'node-1',
    type: 'web-server',
    label: 'Web Server',
    tier: 'dmz',
    ...overrides,
  };
}

function makeSpec(overrides: Partial<InfraSpec> = {}): InfraSpec {
  return {
    nodes: [],
    connections: [],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// 1. Header comment
// ---------------------------------------------------------------------------

describe('kubernetesExport', () => {
  describe('header comment', () => {
    it('should include InfraFlow attribution', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('Kubernetes manifests generated by InfraFlow');
    });

    it('should include the namespace in header', () => {
      const result = exportToKubernetes(makeSpec(), { namespace: 'production' });
      expect(result).toContain('Namespace: production');
    });

    it('should default to namespace "default"', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('Namespace: default');
    });

    it('should include Generated timestamp', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('Generated:');
    });
  });

  // ---------------------------------------------------------------------------
  // 2. Namespace resource
  // ---------------------------------------------------------------------------

  describe('namespace resource', () => {
    it('should generate namespace resource for non-default namespace', () => {
      const result = exportToKubernetes(makeSpec(), { namespace: 'production' });
      expect(result).toContain('kind: Namespace');
      expect(result).toContain('name: production');
      expect(result).toContain('managed-by: infraflow');
    });

    it('should NOT generate namespace resource when namespace is default', () => {
      const result = exportToKubernetes(makeSpec(), { namespace: 'default' });
      expect(result).not.toContain('kind: Namespace');
    });

    it('should NOT generate namespace resource when includeNamespace is false', () => {
      const result = exportToKubernetes(makeSpec(), {
        namespace: 'staging',
        includeNamespace: false,
      });
      expect(result).not.toContain('kind: Namespace');
    });

    it('should still reference namespace in resources even when not generating it', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec, {
        namespace: 'staging',
        includeNamespace: false,
      });
      expect(result).toContain('namespace: staging');
    });
  });

  // ---------------------------------------------------------------------------
  // 3. Default network policies
  // ---------------------------------------------------------------------------

  describe('default network policies', () => {
    it('should generate default-deny-ingress policy by default', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('name: default-deny-ingress');
      expect(result).toContain('kind: NetworkPolicy');
    });

    it('should generate allow-internal policy by default', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('name: allow-internal');
    });

    it('should omit network policies when includeNetworkPolicy is false', () => {
      const result = exportToKubernetes(makeSpec(), { includeNetworkPolicy: false });
      expect(result).not.toContain('default-deny-ingress');
      expect(result).not.toContain('allow-internal');
    });

    it('should use correct namespace in network policies', () => {
      const result = exportToKubernetes(makeSpec(), { namespace: 'prod' });
      // Both network policies should have namespace: prod
      const policyMatches = result.match(/namespace: prod/g);
      expect(policyMatches).not.toBeNull();
      expect(policyMatches!.length).toBeGreaterThanOrEqual(2);
    });
  });

  // ---------------------------------------------------------------------------
  // 4. Application Resources section header
  // ---------------------------------------------------------------------------

  describe('application resources section', () => {
    it('should include Application Resources section divider', () => {
      const result = exportToKubernetes(makeSpec());
      expect(result).toContain('# ============= Application Resources =============');
    });
  });

  // ---------------------------------------------------------------------------
  // 5. Security nodes
  // ---------------------------------------------------------------------------

  describe('firewall node', () => {
    it('should generate NetworkPolicy resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'Edge FW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: NetworkPolicy');
      expect(result).toContain('name: fw-1-firewall');
    });

    it('should include ingress rules for ports 443 and 80', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('port: 443');
      expect(result).toContain('port: 80');
    });

    it('should use custom namespace', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToKubernetes(spec, { namespace: 'security' });
      expect(result).toContain('namespace: security');
    });

    it('should include both Ingress and Egress policy types', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('- Ingress');
      expect(result).toContain('- Egress');
    });
  });

  describe('waf node', () => {
    it('should generate ConfigMap for WAF rules', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'waf-1', type: 'waf', label: 'WAF' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: ConfigMap');
      expect(result).toContain('name: waf-1-waf-rules');
    });

    it('should include ModSecurity configuration', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'waf-1', type: 'waf', label: 'WAF' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('SecRuleEngine On');
    });
  });

  describe('ids-ips node', () => {
    it('should generate DaemonSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ids-1', type: 'ids-ips', label: 'IDS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: DaemonSet');
      expect(result).toContain('name: ids-1-ids');
    });

    it('should use Falco image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ids-1', type: 'ids-ips', label: 'IDS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('falcosecurity/falco:latest');
    });

    it('should set privileged security context', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ids-1', type: 'ids-ips', label: 'IDS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('privileged: true');
    });
  });

  describe('security comment-only nodes', () => {
    const commentCases: Array<[InfraNodeType, string]> = [
      ['vpn-gateway', '# VPN Gateway:'],
      ['nac', '# NAC:'],
      ['dlp', '# DLP:'],
      ['sase-gateway', '# SASE Gateway:'],
      ['ztna-broker', '# ZTNA Broker:'],
      ['casb', '# CASB:'],
      ['siem', '# SIEM:'],
      ['soar', '# SOAR:'],
      ['cctv-camera', '# CCTV Camera:'],
      ['nvr', '# NVR:'],
      ['video-server', '# Video Server:'],
      ['access-control', '# Access Control:'],
    ];

    it.each(commentCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: `sec-1`, type: nodeType, label: 'Test' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 6. Network nodes
  // ---------------------------------------------------------------------------

  describe('network comment-only nodes', () => {
    const commentCases: Array<[InfraNodeType, string]> = [
      ['router', '# Router:'],
      ['switch-l2', '# L2 Switch:'],
      ['switch-l3', '# L3 Switch:'],
      ['sd-wan', '# SD-WAN:'],
      ['wireless-ap', '# Wireless AP:'],
      ['cdn', '# CDN:'],
    ];

    it.each(commentCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: 'net-1', type: nodeType, label: 'Test' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  describe('load-balancer node', () => {
    it('should generate Service with type LoadBalancer', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'App LB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Service');
      expect(result).toContain('name: lb-1-lb');
      expect(result).toContain('type: LoadBalancer');
    });

    it('should include http and https ports', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('port: 80');
      expect(result).toContain('port: 443');
    });

    it('should include aws nlb annotation', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('aws-load-balancer-type: "nlb"');
    });

    it('should select tier: web', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: web');
    });
  });

  describe('api-gateway node', () => {
    it('should generate Deployment with Kong image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('kong:3.4');
    });

    it('should generate accompanying Service with LoadBalancer type', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('type: LoadBalancer');
    });

    it('should use configured replica count', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToKubernetes(spec, { replicaCount: 5 });
      expect(result).toContain('replicas: 5');
    });

    it('should label tier as gateway', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: gateway');
    });

    it('should include resource limits', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('memory: "512Mi"');
      expect(result).toContain('cpu: "500m"');
    });
  });

  describe('dns node', () => {
    it('should generate Service with ClusterIP type', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dns-1', type: 'dns', label: 'DNS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Service');
      expect(result).toContain('name: dns-1-dns');
      expect(result).toContain('type: ClusterIP');
    });

    it('should expose port 53 UDP', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dns-1', type: 'dns', label: 'DNS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('port: 53');
      expect(result).toContain('protocol: UDP');
    });

    it('should select app: coredns', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dns-1', type: 'dns', label: 'DNS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('app: coredns');
    });
  });

  // ---------------------------------------------------------------------------
  // 7. Compute nodes — Deployment + Service
  // ---------------------------------------------------------------------------

  describe('web-server node', () => {
    it('should generate Deployment resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('name: web-1');
    });

    it('should generate accompanying ClusterIP Service', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Service');
      expect(result).toContain('type: ClusterIP');
    });

    it('should use port 80 for web tier', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 80');
    });

    it('should label with tier: web', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: web');
    });

    it('should use default replica count of 2', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('replicas: 2');
    });

    it('should use custom replica count', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec, { replicaCount: 5 });
      expect(result).toContain('replicas: 5');
    });

    it('should include managed-by: infraflow label', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('managed-by: infraflow');
    });

    it('should include resource requests and limits', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('memory: "128Mi"');
      expect(result).toContain('cpu: "100m"');
      expect(result).toContain('memory: "256Mi"');
      expect(result).toContain('cpu: "200m"');
    });

    it('should include readiness and liveness probes', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('readinessProbe:');
      expect(result).toContain('livenessProbe:');
      expect(result).toContain('path: /health');
    });
  });

  describe('app-server node', () => {
    it('should generate Deployment with port 8080', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'app-1', type: 'app-server', label: 'App' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('containerPort: 8080');
    });

    it('should label with tier: app', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'app-1', type: 'app-server', label: 'App' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: app');
    });
  });

  describe('container node', () => {
    it('should generate Deployment with port 8080 and tier container', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ctr-1', type: 'container', label: 'Container' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('tier: container');
      expect(result).toContain('containerPort: 8080');
    });
  });

  // ---------------------------------------------------------------------------
  // 8. Compute nodes — StatefulSet (db-server)
  // ---------------------------------------------------------------------------

  describe('db-server node', () => {
    it('should generate StatefulSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'MySQL DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: StatefulSet');
      expect(result).toContain('name: db-1');
    });

    it('should use MySQL image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('image: mysql:8.0');
    });

    it('should expose port 3306', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 3306');
    });

    it('should include volumeClaimTemplates for data', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('volumeClaimTemplates:');
      expect(result).toContain('storage: 10Gi');
      expect(result).toContain('ReadWriteOnce');
    });

    it('should reference secret for MYSQL_ROOT_PASSWORD', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('secretKeyRef:');
      expect(result).toContain('name: db-1-secret');
      expect(result).toContain('key: root-password');
    });

    it('should generate accompanying ClusterIP Service', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Service');
      expect(result).toContain('port: 3306');
    });

    it('should label with tier: database', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: database');
    });

    it('should include resource limits', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('memory: "1Gi"');
      expect(result).toContain('cpu: "500m"');
    });

    it('should use replica count of 1', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('replicas: 1');
    });
  });

  // ---------------------------------------------------------------------------
  // 9. Message queue nodes (StatefulSet)
  // ---------------------------------------------------------------------------

  describe('kafka node', () => {
    it('should generate StatefulSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: StatefulSet');
      expect(result).toContain('name: kafka-1');
    });

    it('should use confluent kafka image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('confluentinc/cp-kafka:7.5.0');
    });

    it('should expose ports 9092 and 9093', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 9092');
      expect(result).toContain('containerPort: 9093');
    });

    it('should request 50Gi storage', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 50Gi');
    });

    it('should have 3 replicas', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('replicas: 3');
    });

    it('should label with tier: messaging', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: messaging');
    });

    it('should generate ClusterIP service with plaintext and tls ports', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: plaintext');
      expect(result).toContain('name: tls');
    });
  });

  describe('rabbitmq node', () => {
    it('should generate StatefulSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RabbitMQ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: StatefulSet');
      expect(result).toContain('name: rmq-1');
    });

    it('should use rabbitmq management image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('rabbitmq:3.12-management');
    });

    it('should expose AMQP (5672) and management (15672) ports', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 5672');
      expect(result).toContain('containerPort: 15672');
    });

    it('should request 20Gi storage', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 20Gi');
    });

    it('should generate service with amqp and management named ports', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: amqp');
      expect(result).toContain('name: management');
    });
  });

  // ---------------------------------------------------------------------------
  // 10. Monitoring nodes
  // ---------------------------------------------------------------------------

  describe('prometheus node', () => {
    it('should generate StatefulSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prometheus' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: StatefulSet');
      expect(result).toContain('name: prom-1');
    });

    it('should use prom/prometheus image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('prom/prometheus:v2.48.0');
    });

    it('should expose port 9090', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 9090');
    });

    it('should request 50Gi storage', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 50Gi');
    });

    it('should have 1 replica', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('replicas: 1');
    });

    it('should label with tier: monitoring', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: monitoring');
    });
  });

  describe('grafana node', () => {
    it('should generate Deployment resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('name: graf-1');
    });

    it('should use grafana image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('grafana/grafana:10.2.0');
    });

    it('should expose port 3000', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 3000');
    });

    it('should reference grafana-secrets for admin password', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: grafana-secrets');
      expect(result).toContain('key: admin-password');
    });

    it('should include readiness and liveness probes on /api/health', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('path: /api/health');
      expect(result).toContain('readinessProbe:');
      expect(result).toContain('livenessProbe:');
    });

    it('should use configured replica count', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec, { replicaCount: 3 });
      expect(result).toContain('replicas: 3');
    });

    it('should label with tier: monitoring', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: monitoring');
    });
  });

  // ---------------------------------------------------------------------------
  // 11. Elasticsearch node (StatefulSet)
  // ---------------------------------------------------------------------------

  describe('elasticsearch node', () => {
    it('should generate StatefulSet resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: StatefulSet');
      expect(result).toContain('name: es-1');
    });

    it('should use official elasticsearch image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('docker.elastic.co/elasticsearch/elasticsearch:8.11.0');
    });

    it('should expose ports 9200 and 9300', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 9200');
      expect(result).toContain('containerPort: 9300');
    });

    it('should enable xpack security', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('xpack.security.enabled');
    });

    it('should request 100Gi storage', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 100Gi');
    });

    it('should label with tier: search', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: search');
    });

    it('should generate service with http and transport named ports', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: http');
      expect(result).toContain('name: transport');
    });
  });

  // ---------------------------------------------------------------------------
  // 12. Compute misc nodes
  // ---------------------------------------------------------------------------

  describe('vm and kubernetes comment nodes', () => {
    it('should generate comment for vm with KubeVirt suggestion', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vm-1', type: 'vm', label: 'VM' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# VM: Use KubeVirt');
    });

    it('should generate comment for kubernetes node', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'k8s-1', type: 'kubernetes', label: 'K8s' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# Kubernetes cluster:');
    });
  });

  // ---------------------------------------------------------------------------
  // 13. Storage nodes
  // ---------------------------------------------------------------------------

  describe('san-nas node', () => {
    it('should generate PersistentVolumeClaim', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'nas-1', type: 'san-nas', label: 'NAS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: PersistentVolumeClaim');
      expect(result).toContain('name: nas-1-pvc');
    });

    it('should use ReadWriteMany access mode', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'nas-1', type: 'san-nas', label: 'NAS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('ReadWriteMany');
    });

    it('should use efs-sc storage class', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'nas-1', type: 'san-nas', label: 'NAS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storageClassName: efs-sc');
    });

    it('should request 100Gi', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'nas-1', type: 'san-nas', label: 'NAS' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 100Gi');
    });
  });

  describe('storage node', () => {
    it('should generate PersistentVolumeClaim with ReadWriteOnce', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'st-1', type: 'storage', label: 'Storage' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: PersistentVolumeClaim');
      expect(result).toContain('name: st-1-pvc');
      expect(result).toContain('ReadWriteOnce');
    });

    it('should request 10Gi', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'st-1', type: 'storage', label: 'Storage' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('storage: 10Gi');
    });
  });

  describe('cache node', () => {
    it('should generate Deployment with redis image', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('redis:7-alpine');
    });

    it('should expose port 6379', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('containerPort: 6379');
    });

    it('should label with tier: cache', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('tier: cache');
    });

    it('should use 1 replica', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('replicas: 1');
    });

    it('should generate ClusterIP service', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('type: ClusterIP');
      expect(result).toContain('port: 6379');
    });
  });

  describe('storage comment-only nodes', () => {
    it('should generate comment for object-storage', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'os-1', type: 'object-storage', label: 'S3' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# Object Storage:');
    });

    it('should generate comment for backup', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'bak-1', type: 'backup', label: 'Backup' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# Backup: Use Velero');
    });
  });

  // ---------------------------------------------------------------------------
  // 14. Cloud nodes (all comments)
  // ---------------------------------------------------------------------------

  describe('cloud comment-only nodes', () => {
    const cloudCases: Array<[InfraNodeType, string]> = [
      ['aws-vpc', '# AWS VPC:'],
      ['azure-vnet', '# Azure VNet:'],
      ['gcp-network', '# GCP Network:'],
      ['private-cloud', '# Private Cloud:'],
    ];

    it.each(cloudCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: 'cloud-1', type: nodeType, label: 'Cloud' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 15. Auth nodes (all comments)
  // ---------------------------------------------------------------------------

  describe('auth comment-only nodes', () => {
    const authCases: Array<[InfraNodeType, string]> = [
      ['ldap-ad', '# LDAP/AD:'],
      ['sso', '# SSO:'],
      ['mfa', '# MFA:'],
      ['iam', '# IAM:'],
    ];

    it.each(authCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: 'auth-1', type: nodeType, label: 'Auth' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 16. External / zone nodes
  // ---------------------------------------------------------------------------

  describe('external / zone comment nodes', () => {
    it('should generate comment for user', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'user-1', type: 'user', label: 'User' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# User: External client');
    });

    it('should generate comment for internet', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'inet-1', type: 'internet', label: 'Internet' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# Internet: External network');
    });

    it('should generate comment for zone', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'zone-1', type: 'zone', label: 'DMZ' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# Zone: Network zone boundary');
    });
  });

  // ---------------------------------------------------------------------------
  // 17. Telecom / WAN nodes (all comments)
  // ---------------------------------------------------------------------------

  describe('telecom comment-only nodes', () => {
    const telecomCases: Array<[InfraNodeType, string]> = [
      ['central-office', '# Central Office:'],
      ['base-station', '# Base Station:'],
      ['olt', '# OLT:'],
      ['customer-premise', '# Customer Premise:'],
      ['idc', '# IDC:'],
    ];

    it.each(telecomCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: 'tel-1', type: nodeType, label: 'Test' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  describe('WAN comment-only nodes', () => {
    const wanCases: Array<[InfraNodeType, string]> = [
      ['pe-router', '# PE Router:'],
      ['p-router', '# P Router:'],
      ['mpls-network', '# MPLS Network:'],
      ['dedicated-line', '# Dedicated Line:'],
      ['metro-ethernet', '# Metro Ethernet:'],
      ['corporate-internet', '# Corporate Internet:'],
      ['vpn-service', '# VPN Service:'],
      ['sd-wan-service', '# SD-WAN Service:'],
      ['private-5g', '# Private 5G:'],
      ['core-network', '# Core Network:'],
      ['upf', '# UPF:'],
      ['ring-network', '# Ring Network:'],
    ];

    it.each(wanCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: 'wan-1', type: nodeType, label: 'Test' })],
        });
        const result = exportToKubernetes(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 18. Ingress generation
  // ---------------------------------------------------------------------------

  describe('ingress generation', () => {
    it('should generate Ingress when web-server exists and includeIngress is true', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec, { includeIngress: true });
      expect(result).toContain('kind: Ingress');
      expect(result).toContain('name: main-ingress');
    });

    it('should generate Ingress when load-balancer exists', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToKubernetes(spec, { includeIngress: true });
      expect(result).toContain('kind: Ingress');
    });

    it('should NOT generate Ingress when no web/lb nodes exist', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'app-1', type: 'app-server', label: 'App' })],
      });
      const result = exportToKubernetes(spec, { includeIngress: true });
      expect(result).not.toContain('kind: Ingress');
    });

    it('should NOT generate Ingress when includeIngress is false', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec, { includeIngress: false });
      expect(result).not.toContain('kind: Ingress');
    });

    it('should include TLS configuration', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec, { includeIngress: true });
      expect(result).toContain('tls:');
      expect(result).toContain('secretName: tls-secret');
    });

    it('should include nginx ingress class annotation', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kubernetes.io/ingress.class: nginx');
    });

    it('should include cert-manager annotation', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('cert-manager.io/cluster-issuer: letsencrypt-prod');
    });

    it('should include path rule for each web/lb node', () => {
      const spec = makeSpec({
        nodes: [
          makeNode({ id: 'web-1', type: 'web-server', label: 'Web 1' }),
          makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' }),
        ],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: web-1');
      expect(result).toContain('name: lb-1');
    });

    it('should include Ingress section divider', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('# ============= Ingress =============');
    });
  });

  // ---------------------------------------------------------------------------
  // 19. K8s name sanitization
  // ---------------------------------------------------------------------------

  describe('K8s name sanitization', () => {
    it('should convert to lowercase', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'MyWebServer', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: mywebserver');
    });

    it('should replace underscores with hyphens', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web_server_1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: web-server-1');
    });

    it('should collapse consecutive hyphens', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web--server', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: web-server');
    });

    it('should remove leading/trailing hyphens', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: '-web-', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: web');
    });

    it('should truncate to 63 characters', () => {
      const longId = 'a'.repeat(100);
      const spec = makeSpec({
        nodes: [makeNode({ id: longId, type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      // Sanitized name should be 63 chars max
      const sanitized = longId.substring(0, 63);
      expect(result).toContain(`name: ${sanitized}`);
    });

    it('should replace special characters with hyphens', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web.server@prod', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('name: web-server-prod');
    });
  });

  // ---------------------------------------------------------------------------
  // 20. Edge cases
  // ---------------------------------------------------------------------------

  describe('edge cases', () => {
    it('should handle empty spec (no nodes, no connections)', () => {
      const spec = makeSpec({ nodes: [], connections: [] });
      const result = exportToKubernetes(spec);
      expect(result).toContain('Kubernetes manifests generated by InfraFlow');
      expect(result).toContain('# ============= Application Resources =============');
    });

    it('should handle single node spec', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Solo Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('kind: Deployment');
      expect(result).toContain('app: solo-web');
    });

    it('should handle all options disabled', () => {
      const opts: KubernetesExportOptions = {
        includeNamespace: false,
        includeIngress: false,
        includeNetworkPolicy: false,
      };
      const result = exportToKubernetes(makeSpec(), opts);
      expect(result).not.toContain('kind: Namespace');
      expect(result).not.toContain('default-deny-ingress');
      expect(result).not.toContain('kind: Ingress');
    });

    it('should handle all options enabled with custom namespace', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const opts: KubernetesExportOptions = {
        namespace: 'production',
        includeNamespace: true,
        includeIngress: true,
        includeNetworkPolicy: true,
        replicaCount: 3,
      };
      const result = exportToKubernetes(spec, opts);
      expect(result).toContain('kind: Namespace');
      expect(result).toContain('name: production');
      expect(result).toContain('default-deny-ingress');
      expect(result).toContain('kind: Ingress');
      expect(result).toContain('replicas: 3');
    });
  });

  // ---------------------------------------------------------------------------
  // 21. Multi-node microservice architecture
  // ---------------------------------------------------------------------------

  describe('multi-node microservice architecture', () => {
    const microserviceSpec = makeSpec({
      name: 'Microservice App',
      nodes: [
        makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API Gateway' }),
        makeNode({ id: 'web-1', type: 'web-server', label: 'Frontend' }),
        makeNode({ id: 'app-1', type: 'app-server', label: 'User Service' }),
        makeNode({ id: 'app-2', type: 'app-server', label: 'Order Service' }),
        makeNode({ id: 'db-1', type: 'db-server', label: 'User DB' }),
        makeNode({ id: 'db-2', type: 'db-server', label: 'Order DB' }),
        makeNode({ id: 'kafka-1', type: 'kafka', label: 'Event Bus' }),
        makeNode({ id: 'redis-1', type: 'cache', label: 'Redis Cache' }),
        makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prometheus' }),
        makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' }),
      ],
      connections: [
        { source: 'apigw-1', target: 'web-1', flowType: 'request' as const },
        { source: 'web-1', target: 'app-1', flowType: 'request' as const },
        { source: 'web-1', target: 'app-2', flowType: 'request' as const },
        { source: 'app-1', target: 'db-1', flowType: 'request' as const },
        { source: 'app-2', target: 'db-2', flowType: 'request' as const },
        { source: 'app-1', target: 'kafka-1', flowType: 'request' as const },
        { source: 'app-2', target: 'kafka-1', flowType: 'request' as const },
        { source: 'app-1', target: 'redis-1', flowType: 'request' as const },
      ],
    });

    it('should generate Deployment for api-gateway, web, app servers, cache, and grafana', () => {
      const result = exportToKubernetes(microserviceSpec, { namespace: 'production' });
      const deploymentMatches = result.match(/kind: Deployment/g);
      expect(deploymentMatches).not.toBeNull();
      // api-gateway(1) + web(1) + app(2) + cache(1) + grafana(1) = 6
      expect(deploymentMatches!.length).toBe(6);
    });

    it('should generate StatefulSet for db, kafka, and prometheus', () => {
      const result = exportToKubernetes(microserviceSpec, { namespace: 'production' });
      const statefulSetMatches = result.match(/kind: StatefulSet/g);
      expect(statefulSetMatches).not.toBeNull();
      // db(2) + kafka(1) + prometheus(1) = 4
      expect(statefulSetMatches!.length).toBe(4);
    });

    it('should generate Service for each deployable resource', () => {
      const result = exportToKubernetes(microserviceSpec, { namespace: 'production' });
      const serviceMatches = result.match(/kind: Service/g);
      expect(serviceMatches).not.toBeNull();
      // Each of the 10 nodes except comments produce a service
      // api-gw(1) + web(1) + app(2) + db(2) + kafka(1) + cache(1) + prom(1) + grafana(1) = 10
      expect(serviceMatches!.length).toBe(10);
    });

    it('should use production namespace for all resources', () => {
      const result = exportToKubernetes(microserviceSpec, { namespace: 'production' });
      const nsMatches = result.match(/namespace: production/g);
      expect(nsMatches).not.toBeNull();
      // Many resources should reference production namespace
      expect(nsMatches!.length).toBeGreaterThan(5);
    });

    it('should generate Ingress with web-server path', () => {
      const result = exportToKubernetes(microserviceSpec, {
        namespace: 'production',
        includeIngress: true,
      });
      expect(result).toContain('kind: Ingress');
      expect(result).toContain('name: web-1');
    });

    it('should include Namespace resource for non-default namespace', () => {
      const result = exportToKubernetes(microserviceSpec, { namespace: 'production' });
      expect(result).toContain('kind: Namespace');
      expect(result).toContain('name: production');
    });
  });

  // ---------------------------------------------------------------------------
  // 22. Namespace handling edge cases
  // ---------------------------------------------------------------------------

  describe('namespace handling', () => {
    it('should default to "default" namespace when not specified', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToKubernetes(spec);
      expect(result).toContain('namespace: default');
    });

    it('should use custom namespace in all generated resources', () => {
      const spec = makeSpec({
        nodes: [
          makeNode({ id: 'web-1', type: 'web-server', label: 'Web' }),
          makeNode({ id: 'db-1', type: 'db-server', label: 'DB' }),
        ],
      });
      const result = exportToKubernetes(spec, { namespace: 'my-app' });
      // Verify namespace appears in Deployment, StatefulSet, and Service
      const nsMatches = result.match(/namespace: my-app/g);
      expect(nsMatches).not.toBeNull();
      expect(nsMatches!.length).toBeGreaterThanOrEqual(4); // web deploy+svc, db statefulset+svc
    });
  });
});
