import { describe, it, expect } from 'vitest';
import { exportToTerraform, type TerraformExportOptions } from '../terraformExport';
import type { InfraSpec, InfraNodeSpec, InfraNodeType } from '@/types/infra';

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

function makeNode(overrides: Partial<InfraNodeSpec> = {}): InfraNodeSpec {
  return {
    id: 'node-1',
    type: 'web-server',
    label: 'Web Server',
    tier: 'dmz',
    ...overrides,
  };
}

function makeSpec(overrides: Partial<InfraSpec> = {}): InfraSpec {
  return {
    nodes: [],
    connections: [],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// 1. Header & Provider block
// ---------------------------------------------------------------------------

describe('terraformExport', () => {
  describe('header comment', () => {
    it('should include InfraFlow attribution', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('Terraform configuration generated by InfraFlow');
    });

    it('should include the provider name in uppercase', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'aws' });
      expect(result).toContain('Provider: AWS');
    });

    it('should include Generated timestamp', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('Generated:');
    });
  });

  describe('provider block — AWS', () => {
    it('should include required_providers for aws', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'aws' });
      expect(result).toContain('hashicorp/aws');
      expect(result).toContain('~> 5.0');
    });

    it('should set the aws region from options', () => {
      const result = exportToTerraform(makeSpec(), {
        provider: 'aws',
        region: 'us-west-2',
      });
      expect(result).toContain('region = "us-west-2"');
    });

    it('should default to ap-northeast-2 region', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'aws' });
      expect(result).toContain('region = "ap-northeast-2"');
    });
  });

  describe('provider block — Azure', () => {
    it('should include required_providers for azurerm', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'azure' });
      expect(result).toContain('hashicorp/azurerm');
      expect(result).toContain('~> 3.0');
    });

    it('should include features block', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'azure' });
      expect(result).toContain('features {}');
    });
  });

  describe('provider block — GCP', () => {
    it('should include required_providers for google', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'gcp' });
      expect(result).toContain('hashicorp/google');
      expect(result).toContain('~> 5.0');
    });

    it('should reference var.project_id', () => {
      const result = exportToTerraform(makeSpec(), { provider: 'gcp' });
      expect(result).toContain('var.project_id');
    });
  });

  // ---------------------------------------------------------------------------
  // 2. Variables block
  // ---------------------------------------------------------------------------

  describe('variables block', () => {
    it('should include db_username variable by default', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('variable "db_username"');
      expect(result).toContain('sensitive   = true');
    });

    it('should include db_password variable by default', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('variable "db_password"');
    });

    it('should include project_id variable', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('variable "project_id"');
    });

    it('should omit variables when includeVariables is false', () => {
      const result = exportToTerraform(makeSpec(), { includeVariables: false });
      expect(result).not.toContain('variable "db_username"');
      expect(result).not.toContain('variable "db_password"');
    });
  });

  // ---------------------------------------------------------------------------
  // 3. Outputs block
  // ---------------------------------------------------------------------------

  describe('outputs block', () => {
    it('should include vpc_id output by default', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('output "vpc_id"');
      expect(result).toContain('aws_vpc.main.id');
    });

    it('should omit outputs when includeOutputs is false', () => {
      const result = exportToTerraform(makeSpec(), { includeOutputs: false });
      expect(result).not.toContain('output "vpc_id"');
    });
  });

  // ---------------------------------------------------------------------------
  // 4. Resources section header
  // ---------------------------------------------------------------------------

  describe('resources section', () => {
    it('should include Resources section divider', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('# ============= Resources =============');
    });

    it('should include Outputs section divider when outputs enabled', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('# ============= Outputs =============');
    });
  });

  // ---------------------------------------------------------------------------
  // 5. Security node types
  // ---------------------------------------------------------------------------

  describe('firewall node (aws)', () => {
    it('should generate aws_security_group resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'Main Firewall' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_security_group" "fw_1"');
      expect(result).toContain('name        = "Main Firewall"');
      expect(result).toContain('vpc_id      = aws_vpc.main.id');
    });

    it('should include ingress rule for port 443', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('from_port   = 443');
      expect(result).toContain('to_port     = 443');
    });

    it('should include egress rule allowing all', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('protocol    = "-1"');
    });

    it('should use description from node when available', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'fw-1',
          type: 'firewall',
          label: 'FW',
          description: 'Edge firewall',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('description = "Edge firewall"');
    });

    it('should fall back to comment for non-aws providers', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# Firewall: FW');
      expect(result).not.toContain('aws_security_group');
    });
  });

  describe('waf node (aws)', () => {
    it('should generate aws_wafv2_web_acl resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'waf-1', type: 'waf', label: 'Web ACL' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_wafv2_web_acl" "waf_1"');
      expect(result).toContain('scope       = "REGIONAL"');
    });

    it('should include AWSManagedRulesCommonRuleSet', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'waf-1', type: 'waf', label: 'WAF' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('AWSManagedRulesCommonRuleSet');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'waf-1', type: 'waf', label: 'WAF' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# WAF: WAF');
    });
  });

  describe('ids-ips node', () => {
    it('should generate a comment with GuardDuty suggestion', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ids-1', type: 'ids-ips', label: 'My IDS' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('# IDS/IPS: My IDS - Use GuardDuty');
    });
  });

  describe('vpn-gateway node (aws)', () => {
    it('should generate aws_vpn_gateway resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vpn-1', type: 'vpn-gateway', label: 'VPN GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_vpn_gateway" "vpn_1"');
      expect(result).toContain('vpc_id = aws_vpc.main.id');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vpn-1', type: 'vpn-gateway', label: 'VPN GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# VPN Gateway: VPN GW');
    });
  });

  describe('nac and dlp nodes', () => {
    it('should generate NAC comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'nac-1', type: 'nac', label: 'NAC' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# NAC: NAC');
    });

    it('should generate DLP comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dlp-1', type: 'dlp', label: 'DLP Engine' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# DLP: DLP Engine');
    });
  });

  // ---------------------------------------------------------------------------
  // 6. Network node types
  // ---------------------------------------------------------------------------

  describe('router node (aws)', () => {
    it('should generate aws_route_table resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rtr-1', type: 'router', label: 'Core Router' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_route_table" "rtr_1"');
      expect(result).toContain('cidr_block = "0.0.0.0/0"');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rtr-1', type: 'router', label: 'Core Router' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# Router: Core Router');
    });
  });

  describe('switch nodes', () => {
    it('should generate L2 switch comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'sw-1', type: 'switch-l2', label: 'Access SW' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# L2 Switch: Access SW');
    });

    it('should generate L3 switch comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'sw-2', type: 'switch-l3', label: 'Dist SW' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# L3 Switch: Dist SW');
    });
  });

  describe('load-balancer node (aws)', () => {
    it('should generate aws_lb resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'App LB' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_lb" "lb_1"');
      expect(result).toContain('load_balancer_type = "application"');
    });

    it('should generate target group and listener', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('aws_lb_target_group');
      expect(result).toContain('aws_lb_listener');
      expect(result).toContain('protocol          = "HTTPS"');
    });

    it('should set internal = true when zone is internal', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'lb-1',
          type: 'load-balancer',
          label: 'Internal LB',
          zone: 'internal',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('internal           = true');
    });

    it('should set internal = false when zone is not internal', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'lb-1',
          type: 'load-balancer',
          label: 'Ext LB',
          zone: 'dmz',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('internal           = false');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'lb-1', type: 'load-balancer', label: 'LB' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# Load Balancer: LB');
    });
  });

  describe('api-gateway node', () => {
    it('should generate aws_apigatewayv2_api for aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_apigatewayv2_api" "apigw_1"');
      expect(result).toContain('protocol_type = "HTTP"');
    });

    it('should generate aws_apigatewayv2_stage for aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('aws_apigatewayv2_stage');
      expect(result).toContain('auto_deploy = true');
    });

    it('should generate azurerm_api_management for azure', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('resource "azurerm_api_management" "apigw_1"');
      expect(result).toContain('sku_name            = "Consumption_0"');
    });

    it('should fall back to comment for gcp', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'apigw-1', type: 'api-gateway', label: 'API GW' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# API Gateway: API GW');
    });
  });

  describe('dns node (aws)', () => {
    it('should generate aws_route53_zone resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dns-1', type: 'dns', label: 'DNS' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_route53_zone" "dns_1"');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'dns-1', type: 'dns', label: 'DNS' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# DNS: DNS');
    });
  });

  describe('cdn node (aws)', () => {
    it('should generate aws_cloudfront_distribution resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'cdn-1', type: 'cdn', label: 'CDN' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_cloudfront_distribution" "cdn_1"');
      expect(result).toContain('viewer_protocol_policy = "redirect-to-https"');
    });

    it('should use description from node for comment field', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'cdn-1',
          type: 'cdn',
          label: 'CDN',
          description: 'Global CDN',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('comment             = "Global CDN"');
    });

    it('should fall back to label when description is absent', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'cdn-1', type: 'cdn', label: 'My CDN' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('comment             = "My CDN"');
    });
  });

  // ---------------------------------------------------------------------------
  // 7. Compute node types
  // ---------------------------------------------------------------------------

  describe('web-server node (aws)', () => {
    it('should generate aws_instance resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_instance" "web_1"');
      expect(result).toContain('instance_type          = "t3.medium"');
    });

    it('should tag with Tier = web', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('Tier = "web"');
    });

    it('should use public subnet when zone is dmz', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'web-1',
          type: 'web-server',
          label: 'Web',
          zone: 'dmz',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('aws_subnet.public[0].id');
    });

    it('should use private subnet when zone is not dmz', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'web-1',
          type: 'web-server',
          label: 'Web',
          zone: 'internal',
        })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('aws_subnet.private[0].id');
    });

    it('should fall back to comment for non-aws provider', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# WEB Server: Web');
    });
  });

  describe('app-server node (aws)', () => {
    it('should generate aws_instance with tier app', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'app-1', type: 'app-server', label: 'App' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_instance" "app_1"');
      expect(result).toContain('Tier = "app"');
    });
  });

  describe('db-server node (aws)', () => {
    it('should generate aws_db_instance resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'Primary DB' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_db_instance" "db_1"');
      expect(result).toContain('engine                 = "mysql"');
      expect(result).toContain('instance_class         = "db.t3.medium"');
    });

    it('should reference db_username and db_password variables', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('var.db_username');
      expect(result).toContain('var.db_password');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'db-1', type: 'db-server', label: 'DB' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# Database: DB');
    });
  });

  describe('container node (aws)', () => {
    it('should generate aws_ecs_cluster resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ecs-1', type: 'container', label: 'ECS' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_ecs_cluster" "ecs_1"');
      expect(result).toContain('containerInsights');
    });
  });

  describe('vm node (aws)', () => {
    it('should generate aws_instance with tier vm', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vm-1', type: 'vm', label: 'VM' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_instance" "vm_1"');
      expect(result).toContain('Tier = "vm"');
    });
  });

  describe('kubernetes node (aws)', () => {
    it('should generate aws_eks_cluster resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'eks-1', type: 'kubernetes', label: 'K8s' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_eks_cluster" "eks_1"');
      expect(result).toContain('aws_subnet.private[*].id');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'eks-1', type: 'kubernetes', label: 'K8s' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# Kubernetes: K8s');
    });
  });

  // ---------------------------------------------------------------------------
  // 8. Message queue & monitoring node types
  // ---------------------------------------------------------------------------

  describe('kafka node', () => {
    it('should generate aws_msk_cluster for aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_msk_cluster" "kafka_1"');
      expect(result).toContain('kafka_version          = "3.5.1"');
      expect(result).toContain('number_of_broker_nodes = 3');
    });

    it('should generate azurerm_eventhub_namespace for azure', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('resource "azurerm_eventhub_namespace" "kafka_1"');
    });

    it('should fall back to comment for gcp', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'kafka-1', type: 'kafka', label: 'Kafka' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# Kafka: Kafka');
    });
  });

  describe('rabbitmq node (aws)', () => {
    it('should generate aws_mq_broker resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RabbitMQ' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_mq_broker" "rmq_1"');
      expect(result).toContain('engine_type   = "RabbitMQ"');
      expect(result).toContain('CLUSTER_MULTI_AZ');
    });

    it('should reference rabbitmq_password variable', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('var.rabbitmq_password');
    });

    it('should fall back to not-implemented comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'rmq-1', type: 'rabbitmq', label: 'RMQ' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# RabbitMQ: RMQ');
      expect(result).toContain('not yet implemented');
    });
  });

  describe('prometheus node (aws)', () => {
    it('should generate aws_prometheus_workspace resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prometheus' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_prometheus_workspace" "prom_1"');
    });

    it('should fall back for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'prom-1', type: 'prometheus', label: 'Prom' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# Prometheus: Prom');
    });
  });

  describe('grafana node (aws)', () => {
    it('should generate aws_grafana_workspace resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_grafana_workspace" "graf_1"');
      expect(result).toContain('account_access_type      = "CURRENT_ACCOUNT"');
    });

    it('should fall back for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'graf-1', type: 'grafana', label: 'Grafana' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# Grafana: Grafana');
    });
  });

  // ---------------------------------------------------------------------------
  // 9. Cloud node types
  // ---------------------------------------------------------------------------

  describe('aws-vpc node', () => {
    it('should generate aws_vpc resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vpc-1', type: 'aws-vpc', label: 'Main VPC' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('resource "aws_vpc" "vpc_1"');
      expect(result).toContain('cidr_block           = "10.0.0.0/16"');
      expect(result).toContain('enable_dns_hostnames = true');
    });
  });

  describe('azure-vnet node', () => {
    it('should generate azurerm_virtual_network resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'vnet-1', type: 'azure-vnet', label: 'Main VNet' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('resource "azurerm_virtual_network" "vnet_1"');
      expect(result).toContain('address_space       = ["10.0.0.0/16"]');
    });
  });

  describe('gcp-network node', () => {
    it('should generate google_compute_network resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'gcpnet-1', type: 'gcp-network', label: 'GCP Net' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('resource "google_compute_network" "gcpnet_1"');
      expect(result).toContain('auto_create_subnetworks = false');
    });
  });

  describe('private-cloud node', () => {
    it('should generate a comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'pc-1', type: 'private-cloud', label: 'On-Prem' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Private Cloud: On-Prem');
    });
  });

  // ---------------------------------------------------------------------------
  // 10. Storage node types
  // ---------------------------------------------------------------------------

  describe('san-nas node (aws)', () => {
    it('should generate aws_efs_file_system resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'efs-1', type: 'san-nas', label: 'EFS' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_efs_file_system" "efs_1"');
      expect(result).toContain('encrypted      = true');
    });
  });

  describe('object-storage node (aws)', () => {
    it('should generate aws_s3_bucket resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 's3-1', type: 'object-storage', label: 'S3' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_s3_bucket" "s3_1"');
    });

    it('should enable versioning', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 's3-1', type: 'object-storage', label: 'S3' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('aws_s3_bucket_versioning');
      expect(result).toContain('status = "Enabled"');
    });
  });

  describe('cache node (aws)', () => {
    it('should generate aws_elasticache_cluster resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'redis-1', type: 'cache', label: 'Redis' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_elasticache_cluster" "redis_1"');
      expect(result).toContain('engine               = "redis"');
      expect(result).toContain('port                 = 6379');
    });
  });

  describe('elasticsearch node', () => {
    it('should generate aws_opensearch_domain for aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_opensearch_domain" "es_1"');
      expect(result).toContain('engine_version = "OpenSearch_2.11"');
      expect(result).toContain('encrypt_at_rest');
    });

    it('should generate azurerm_search_service for azure', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('resource "azurerm_search_service" "es_1"');
      expect(result).toContain('sku                 = "standard"');
    });

    it('should fall back to comment for gcp', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'es-1', type: 'elasticsearch', label: 'ES' })],
      });
      const result = exportToTerraform(spec, { provider: 'gcp' });
      expect(result).toContain('# Elasticsearch: ES');
    });
  });

  // ---------------------------------------------------------------------------
  // 11. Auth node types
  // ---------------------------------------------------------------------------

  describe('iam node (aws)', () => {
    it('should generate aws_iam_role resource', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'iam-1', type: 'iam', label: 'IAM Role' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_iam_role" "iam_1"');
      expect(result).toContain('sts:AssumeRole');
    });

    it('should fall back to comment for non-aws', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'iam-1', type: 'iam', label: 'IAM' })],
      });
      const result = exportToTerraform(spec, { provider: 'azure' });
      expect(result).toContain('# IAM: IAM');
    });
  });

  describe('auth comment-only nodes', () => {
    it('should generate LDAP/AD comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ldap-1', type: 'ldap-ad', label: 'AD' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# LDAP/AD: AD');
    });

    it('should generate SSO comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'sso-1', type: 'sso', label: 'SSO' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# SSO: SSO');
    });

    it('should generate MFA comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'mfa-1', type: 'mfa', label: 'MFA' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# MFA: MFA');
    });
  });

  // ---------------------------------------------------------------------------
  // 12. External / zone nodes
  // ---------------------------------------------------------------------------

  describe('external / zone nodes', () => {
    it('should generate user comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'user-1', type: 'user', label: 'User' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# User/Client - External entity');
    });

    it('should generate internet comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'inet-1', type: 'internet', label: 'Internet' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Internet - External network');
    });

    it('should generate zone comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'zone-1', type: 'zone', label: 'DMZ' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Zone: DMZ');
    });
  });

  // ---------------------------------------------------------------------------
  // 13. Telecom / WAN comment-only nodes
  // ---------------------------------------------------------------------------

  describe('telecom node types', () => {
    const telecomCases: Array<[InfraNodeType, string]> = [
      ['central-office', '# Central Office:'],
      ['base-station', '# Base Station:'],
      ['olt', '# OLT:'],
      ['customer-premise', '# Customer Premise:'],
      ['idc', '# IDC:'],
    ];

    it.each(telecomCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: `t-1`, type: nodeType, label: 'Test' })],
        });
        const result = exportToTerraform(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  describe('WAN node types', () => {
    const wanCases: Array<[InfraNodeType, string]> = [
      ['pe-router', '# PE Router:'],
      ['p-router', '# P Router:'],
      ['mpls-network', '# MPLS Network:'],
      ['dedicated-line', '# Dedicated Line:'],
      ['metro-ethernet', '# Metro Ethernet:'],
      ['corporate-internet', '# Corporate Internet:'],
      ['vpn-service', '# VPN Service:'],
      ['sd-wan-service', '# SD-WAN Service:'],
      ['private-5g', '# Private 5G:'],
      ['core-network', '# Core Network:'],
      ['upf', '# UPF:'],
      ['ring-network', '# Ring Network:'],
    ];

    it.each(wanCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: `w-1`, type: nodeType, label: 'Test' })],
        });
        const result = exportToTerraform(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 14. Security-specific nodes (SASE, ZTNA, CASB, SIEM, SOAR, etc.)
  // ---------------------------------------------------------------------------

  describe('security comment-only nodes', () => {
    const securityCases: Array<[InfraNodeType, string]> = [
      ['sase-gateway', '# SASE Gateway:'],
      ['ztna-broker', '# ZTNA Broker:'],
      ['casb', '# CASB:'],
      ['siem', '# SIEM:'],
      ['soar', '# SOAR:'],
      ['cctv-camera', '# CCTV Camera:'],
      ['nvr', '# NVR:'],
      ['video-server', '# Video Server:'],
      ['access-control', '# Access Control:'],
    ];

    it.each(securityCases)(
      'should generate comment for %s',
      (nodeType, expectedSubstring) => {
        const spec = makeSpec({
          nodes: [makeNode({ id: `sec-1`, type: nodeType, label: 'Test' })],
        });
        const result = exportToTerraform(spec);
        expect(result).toContain(expectedSubstring);
      },
    );
  });

  // ---------------------------------------------------------------------------
  // 15. ID sanitization
  // ---------------------------------------------------------------------------

  describe('ID sanitization', () => {
    it('should replace hyphens with underscores in resource IDs', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'my-web-server', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_instance" "my_web_server"');
    });

    it('should lowercase the resource ID', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'MyServer', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('"myserver"');
    });

    it('should replace special characters with underscores', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'server.1@prod', type: 'web-server', label: 'Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('"server_1_prod"');
    });
  });

  // ---------------------------------------------------------------------------
  // 16. Edge cases
  // ---------------------------------------------------------------------------

  describe('edge cases', () => {
    it('should handle empty spec (no nodes, no connections)', () => {
      const spec = makeSpec({ nodes: [], connections: [] });
      const result = exportToTerraform(spec);
      expect(result).toContain('Terraform configuration generated by InfraFlow');
      expect(result).toContain('# ============= Resources =============');
    });

    it('should handle single node spec', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'web-1', type: 'web-server', label: 'Solo Web' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('resource "aws_instance" "web_1"');
      expect(result).toContain('Name = "Solo Web"');
    });

    it('should handle special characters in labels', () => {
      const spec = makeSpec({
        nodes: [makeNode({
          id: 'fw-1',
          type: 'firewall',
          label: 'Firewall "Edge" <Corp>',
        })],
      });
      // Should not throw
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('Firewall "Edge" <Corp>');
    });

    it('should handle node without description (fallback default)', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'fw-1', type: 'firewall', label: 'FW' })],
      });
      const result = exportToTerraform(spec, { provider: 'aws' });
      expect(result).toContain('Managed by InfraFlow');
    });

    it('should handle options with all flags disabled', () => {
      const opts: TerraformExportOptions = {
        includeVariables: false,
        includeOutputs: false,
      };
      const result = exportToTerraform(makeSpec(), opts);
      expect(result).not.toContain('variable "');
      expect(result).not.toContain('output "');
    });

    it('should handle default options (all enabled)', () => {
      const result = exportToTerraform(makeSpec());
      expect(result).toContain('variable "db_username"');
      expect(result).toContain('output "vpc_id"');
    });
  });

  // ---------------------------------------------------------------------------
  // 17. Multi-node / 3-tier architecture
  // ---------------------------------------------------------------------------

  describe('multi-node 3-tier architecture', () => {
    const threeTierSpec = makeSpec({
      name: '3-Tier App',
      description: 'Web + App + DB architecture',
      nodes: [
        makeNode({ id: 'fw-1', type: 'firewall', label: 'Edge Firewall' }),
        makeNode({ id: 'lb-1', type: 'load-balancer', label: 'App LB', zone: 'dmz' }),
        makeNode({ id: 'web-1', type: 'web-server', label: 'Web Server', zone: 'dmz' }),
        makeNode({ id: 'web-2', type: 'web-server', label: 'Web Server 2', zone: 'dmz' }),
        makeNode({ id: 'app-1', type: 'app-server', label: 'App Server', zone: 'internal' }),
        makeNode({ id: 'db-1', type: 'db-server', label: 'MySQL DB', zone: 'data' }),
        makeNode({ id: 'cache-1', type: 'cache', label: 'Redis Cache' }),
      ],
      connections: [
        { source: 'fw-1', target: 'lb-1', flowType: 'request' },
        { source: 'lb-1', target: 'web-1', flowType: 'request' },
        { source: 'lb-1', target: 'web-2', flowType: 'request' },
        { source: 'web-1', target: 'app-1', flowType: 'request' },
        { source: 'app-1', target: 'db-1', flowType: 'request' },
        { source: 'app-1', target: 'cache-1', flowType: 'request' },
      ],
    });

    it('should generate all 7 resource blocks', () => {
      const result = exportToTerraform(threeTierSpec, { provider: 'aws' });
      expect(result).toContain('aws_security_group');
      expect(result).toContain('aws_lb');
      expect(result).toContain('aws_instance');
      expect(result).toContain('aws_db_instance');
      expect(result).toContain('aws_elasticache_cluster');
    });

    it('should have two web server instances', () => {
      const result = exportToTerraform(threeTierSpec, { provider: 'aws' });
      expect(result).toContain('"web_1"');
      expect(result).toContain('"web_2"');
    });

    it('should place web servers in public subnet (dmz zone)', () => {
      const result = exportToTerraform(threeTierSpec, { provider: 'aws' });
      // Both web-1 and web-2 have zone=dmz
      const matches = result.match(/aws_subnet\.public/g);
      expect(matches).not.toBeNull();
      expect(matches!.length).toBeGreaterThanOrEqual(2);
    });

    it('should place app server in private subnet', () => {
      const result = exportToTerraform(threeTierSpec, { provider: 'aws' });
      // app-1 zone = internal
      expect(result).toContain('resource "aws_instance" "app_1"');
    });

    it('should generate resources in order they appear in spec', () => {
      const result = exportToTerraform(threeTierSpec, { provider: 'aws' });
      const fwPos = result.indexOf('aws_security_group');
      const lbPos = result.indexOf('aws_lb');
      const webPos = result.indexOf('aws_instance');
      const dbPos = result.indexOf('aws_db_instance');
      expect(fwPos).toBeLessThan(lbPos);
      expect(lbPos).toBeLessThan(webPos);
      expect(webPos).toBeLessThan(dbPos);
    });
  });

  // ---------------------------------------------------------------------------
  // 18. Full options combinations
  // ---------------------------------------------------------------------------

  describe('full options combinations', () => {
    it('should produce minimal output with everything disabled', () => {
      const result = exportToTerraform(makeSpec(), {
        includeVariables: false,
        includeOutputs: false,
      });
      expect(result).toContain('# ============= Resources =============');
      expect(result).not.toContain('variable "');
      expect(result).not.toContain('output "');
    });

    it('should include variables but no outputs', () => {
      const result = exportToTerraform(makeSpec(), {
        includeVariables: true,
        includeOutputs: false,
      });
      expect(result).toContain('variable "db_username"');
      expect(result).not.toContain('output "');
    });

    it('should include outputs but no variables', () => {
      const result = exportToTerraform(makeSpec(), {
        includeVariables: false,
        includeOutputs: true,
      });
      expect(result).not.toContain('variable "db_username"');
      expect(result).toContain('output "vpc_id"');
    });
  });

  // ---------------------------------------------------------------------------
  // 19. Network-only misc nodes
  // ---------------------------------------------------------------------------

  describe('miscellaneous network nodes', () => {
    it('should generate sd-wan comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'sdwan-1', type: 'sd-wan', label: 'SD-WAN' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# SD-WAN: SD-WAN');
    });

    it('should generate wireless-ap comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'ap-1', type: 'wireless-ap', label: 'AP' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Wireless AP: AP');
    });
  });

  // ---------------------------------------------------------------------------
  // 20. Storage misc
  // ---------------------------------------------------------------------------

  describe('storage misc nodes', () => {
    it('should generate backup comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'bak-1', type: 'backup', label: 'Backup' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Backup: Backup');
    });

    it('should generate storage comment', () => {
      const spec = makeSpec({
        nodes: [makeNode({ id: 'st-1', type: 'storage', label: 'Storage' })],
      });
      const result = exportToTerraform(spec);
      expect(result).toContain('# Storage: Storage');
    });
  });
});
