/**
 * Terraform Export Module
 *
 * This module converts InfraFlow infrastructure specifications to Terraform HCL format.
 * It supports multiple cloud providers (AWS, Azure, GCP) and generates production-ready
 * Terraform configurations.
 *
 * @module lib/export/terraform
 *
 * @example
 * import { exportToTerraform } from '@/lib/export/terraform';
 *
 * const terraform = exportToTerraform(infraSpec, {
 *   provider: 'aws',
 *   region: 'ap-northeast-2',
 *   includeVariables: true,
 *   includeOutputs: true
 * });
 *
 * console.log(terraform);
 * // Outputs HCL configuration
 */

import { InfraSpec, InfraNodeSpec, InfraNodeType } from '@/types';
import { generateProviderBlock, generateVariablesBlock } from './helpers';
import { securityResourceMap } from './securityResources';
import { networkResourceMap } from './networkResources';
import { computeResourceMap } from './computeResources';
import { storageAndMiscResourceMap } from './storageResources';
import { aiResourceMap } from './aiResources';

// Re-export types
export type { TerraformExportOptions } from './types';

// Re-export for advanced usage
export { sanitizeId, generateEC2Instance, generateProviderBlock, generateVariablesBlock } from './helpers';

// Import type for internal use
import type { TerraformExportOptions } from './types';

/**
 * Combined resource map from all sub-modules.
 *
 * Merges security, network, compute, storage/misc, and AI resource generators
 * into a single lookup map keyed by InfraNodeType.
 */
const terraformResourceMap: Record<InfraNodeType, (node: InfraNodeSpec, provider: string) => string> = {
  ...securityResourceMap,
  ...networkResourceMap,
  ...computeResourceMap,
  ...storageAndMiscResourceMap,
  ...aiResourceMap,
} as Record<InfraNodeType, (node: InfraNodeSpec, provider: string) => string>;

/**
 * Exports an InfraSpec to Terraform HCL format.
 *
 * Converts an infrastructure specification into a complete Terraform configuration
 * including provider setup, variables, resources, and outputs.
 *
 * @param {InfraSpec} spec - The infrastructure specification to export
 * @param {TerraformExportOptions} [options={}] - Export configuration options
 * @returns {string} Complete Terraform HCL configuration
 *
 * @example
 * const terraform = exportToTerraform(spec, {
 *   provider: 'aws',
 *   region: 'us-west-2',
 *   includeVariables: true,
 *   includeOutputs: true
 * });
 *
 * // Save to file
 * fs.writeFileSync('main.tf', terraform);
 */
export function exportToTerraform(
  spec: InfraSpec,
  options: TerraformExportOptions = {}
): string {
  const {
    provider = 'aws',
    region = 'ap-northeast-2',
    includeVariables = true,
    includeOutputs = true,
  } = options;

  const sections: string[] = [];

  // Header comment
  sections.push(`# Terraform configuration generated by InfraFlow
# Provider: ${provider.toUpperCase()}
# Generated: ${new Date().toISOString()}
`);

  // Provider block
  sections.push(generateProviderBlock(provider, region));

  // Variables
  if (includeVariables) {
    sections.push(generateVariablesBlock());
  }

  // Resources
  sections.push('\n# ============= Resources =============\n');

  for (const node of spec.nodes) {
    const resourceGenerator = terraformResourceMap[node.type];
    if (resourceGenerator) {
      sections.push(resourceGenerator(node, provider));
    } else {
      sections.push(`# Unknown node type: ${node.type} - ${node.label}`);
    }
  }

  // Outputs
  if (includeOutputs) {
    sections.push('\n# ============= Outputs =============\n');
    sections.push(`
output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}
`);
  }

  return sections.join('\n');
}
