/**
 * Azure Cloud Services
 *
 * 35+ services across 25+ categories with architecture-decision fields.
 */

import type { CloudService } from '../types';
import { svcTrust } from '../types';

const t = svcTrust('azure');
const certs = ['SOC 2', 'ISO 27001', 'PCI DSS', 'HIPAA', 'FedRAMP'];

export const AZURE_SERVICES: CloudService[] = [
  // ========== Firewall ==========
  { id: 'CS-FW-AZ-001', provider: 'azure', componentType: 'firewall', serviceName: 'Azure Firewall', serviceNameKo: 'Azure 방화벽', status: 'active', features: ['L3-L7 filtering', 'Threat intelligence', 'FQDN filtering', 'DNS proxy'], featuresKo: ['L3-L7 필터링', '위협 인텔리전스', 'FQDN 필터링', 'DNS 프록시'], pricingTier: 'high', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'VNet perimeter and hub firewall', architectureRoleKo: 'VNet 경계 및 허브 방화벽', recommendedFor: ['Hub-spoke network security', 'Centralized egress filtering', 'Multi-VNet protection', 'Compliance environments'], recommendedForKo: ['허브-스포크 네트워크 보안', '중앙 집중식 송신 필터링', '다중 VNet 보호', '컴플라이언스 환경'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/firewall/', typicalMonthlyCostUsd: 900, supportedProtocols: ['TCP/UDP', 'HTTP/HTTPS', 'TLS', 'ICMP', 'DNAT'], haFeatures: ['Availability Zones', 'Auto-scaling', 'Active-active deployment'], securityCapabilities: ['TLS inspection', 'IDPS', 'Web categories filtering', 'Threat intelligence-based filtering'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== WAF ==========
  { id: 'CS-WAF-AZ-001', provider: 'azure', componentType: 'waf', serviceName: 'Azure WAF', serviceNameKo: 'Azure WAF', status: 'active', features: ['OWASP CRS', 'Custom rules', 'Bot protection', 'Rate limiting'], featuresKo: ['OWASP CRS', '커스텀 규칙', '봇 보호', '속도 제한'], pricingTier: 'medium', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Edge/CDN layer application protection', architectureRoleKo: '엣지/CDN 계층 애플리케이션 보호', recommendedFor: ['Web application protection', 'OWASP Top 10 defense', 'API security', 'Bot mitigation'], recommendedForKo: ['웹 애플리케이션 보호', 'OWASP Top 10 방어', 'API 보안', '봇 차단'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/web-application-firewall/', typicalMonthlyCostUsd: 60, supportedProtocols: ['HTTP/HTTPS', 'WebSocket'], haFeatures: ['Availability Zones', 'Multi-region via Front Door'], securityCapabilities: ['OWASP CRS 3.2', 'Bot protection', 'Rate limiting', 'Geo-filtering', 'Custom rules'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== Load Balancer ==========
  { id: 'CS-LB-AZ-001', provider: 'azure', componentType: 'load-balancer', serviceName: 'Azure Load Balancer', serviceNameKo: 'Azure 로드 밸런서', status: 'active', features: ['L4 load balancing', 'HA ports', 'Zone redundant', 'Outbound rules'], featuresKo: ['L4 로드 밸런싱', 'HA 포트', '영역 중복', '아웃바운드 규칙'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Network-layer traffic distribution', architectureRoleKo: '네트워크 계층 트래픽 분산', recommendedFor: ['TCP/UDP load balancing', 'High-availability architectures', 'NVA load balancing', 'Internal service distribution'], recommendedForKo: ['TCP/UDP 로드 밸런싱', '고가용성 아키텍처', 'NVA 로드 밸런싱', '내부 서비스 분산'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/load-balancer/', typicalMonthlyCostUsd: 20, supportedProtocols: ['TCP', 'UDP', 'HA Ports'], haFeatures: ['Availability Zones', 'Zone-redundant frontend', 'Cross-region load balancing'], securityCapabilities: ['NSG integration', 'Outbound rules', 'Private Link support'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },
  { id: 'CS-LB-AZ-002', provider: 'azure', componentType: 'load-balancer', serviceName: 'Azure Application Gateway', serviceNameKo: 'Azure 애플리케이션 게이트웨이', status: 'active', features: ['L7 routing', 'WAF integrated', 'SSL offloading', 'URL-based routing'], featuresKo: ['L7 라우팅', 'WAF 통합', 'SSL 오프로딩', 'URL 기반 라우팅'], pricingTier: 'medium', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Application-layer load balancing with WAF', architectureRoleKo: 'WAF 통합 애플리케이션 계층 로드 밸런싱', recommendedFor: ['HTTP/HTTPS applications', 'Multi-site hosting', 'SSL termination', 'Cookie-based session affinity'], recommendedForKo: ['HTTP/HTTPS 애플리케이션', '다중 사이트 호스팅', 'SSL 종료', '쿠키 기반 세션 유지'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/application-gateway/', typicalMonthlyCostUsd: 200, supportedProtocols: ['HTTP/HTTPS', 'HTTP/2', 'WebSocket', 'TLS 1.2/1.3'], haFeatures: ['Availability Zones', 'Autoscaling v2', 'Multi-site hosting'], securityCapabilities: ['Integrated WAF', 'SSL/TLS termination', 'End-to-end SSL', 'Custom error pages'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: false }, requiredCompanions: [{ componentType: 'azure-vnet', reason: 'Application Gateway must be deployed in a dedicated subnet within a VNet', reasonKo: 'Application Gateway는 VNet 내 전용 서브넷에 배포해야 합니다', severity: 'critical' }], recommendedCompanions: [{ componentType: 'prometheus', reason: 'Azure Monitor tracks backend health, request metrics, and WAF logs', reasonKo: 'Azure Monitor가 백엔드 상태, 요청 메트릭 및 WAF 로그를 추적합니다', severity: 'high' }, { componentType: 'waf', reason: 'Integrated WAF v2 protects web applications from common exploits', reasonKo: '통합 WAF v2가 일반적인 익스플로잇으로부터 웹 애플리케이션을 보호합니다', severity: 'high' }] },

  // ========== Web Server ==========
  { id: 'CS-WEB-AZ-001', provider: 'azure', componentType: 'web-server', serviceName: 'Azure App Service', serviceNameKo: 'Azure App Service', status: 'active', features: ['PaaS', 'Auto-scale', 'CI/CD integration', 'Deployment slots'], featuresKo: ['PaaS', '자동 확장', 'CI/CD 통합', '배포 슬롯'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'PaaS web application hosting', architectureRoleKo: 'PaaS 웹 애플리케이션 호스팅', recommendedFor: ['Web application hosting', '.NET/Java/PHP apps', 'Blue-green deployments', 'Auto-scaling web services'], recommendedForKo: ['웹 애플리케이션 호스팅', '.NET/Java/PHP 앱', '블루-그린 배포', '자동 확장 웹 서비스'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/app-service/', typicalMonthlyCostUsd: 55, supportedProtocols: ['HTTP/HTTPS', 'HTTP/2', 'WebSocket', 'FTP/FTPS'], haFeatures: ['Availability Zones', 'Auto-scale', 'Deployment slots', 'Traffic Manager integration'], securityCapabilities: ['Managed SSL certificates', 'IP restrictions', 'Managed identity', 'VNet integration', 'Private endpoints'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 30, maxRPOMinutes: 5, backupFrequency: 'daily', multiRegionSupported: true }, requiredCompanions: [{ componentType: 'azure-vnet', reason: 'VNet integration is required for private backend connectivity and secure resource access', reasonKo: 'VNet 통합은 프라이빗 백엔드 연결 및 안전한 리소스 접근에 필요합니다', severity: 'high' }], recommendedCompanions: [{ componentType: 'prometheus', reason: 'Azure Monitor and Application Insights provide APM and diagnostics', reasonKo: 'Azure Monitor와 Application Insights가 APM 및 진단을 제공합니다', severity: 'high' }, { componentType: 'storage', reason: 'Managed Disks provide persistent storage for App Service file systems', reasonKo: '관리 디스크가 App Service 파일 시스템에 영구 스토리지를 제공합니다', severity: 'medium' }] },

  // ========== App Server ==========
  { id: 'CS-APP-AZ-001', provider: 'azure', componentType: 'app-server', serviceName: 'Azure Container Apps', serviceNameKo: 'Azure Container Apps', status: 'active', features: ['Serverless containers', 'KEDA scaling', 'Dapr', 'Revision management'], featuresKo: ['서버리스 컨테이너', 'KEDA 스케일링', 'Dapr', '리비전 관리'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Serverless container application hosting', architectureRoleKo: '서버리스 컨테이너 애플리케이션 호스팅', recommendedFor: ['Microservice hosting', 'Event-driven processing', 'API backends', 'Background workers'], recommendedForKo: ['마이크로서비스 호스팅', '이벤트 기반 처리', 'API 백엔드', '백그라운드 워커'], sla: '99.95%', deploymentModel: 'serverless', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/container-apps/', typicalMonthlyCostUsd: 30, supportedProtocols: ['HTTP/HTTPS', 'gRPC', 'TCP'], haFeatures: ['Availability Zones', 'KEDA auto-scaling', 'Revision-based traffic splitting'], securityCapabilities: ['Managed identity', 'VNet integration', 'Secret management', 'mTLS between containers'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable', disasterRecovery: { multiRegionSupported: false } },

  // ========== Database ==========
  { id: 'CS-DB-AZ-001', provider: 'azure', componentType: 'db-server', serviceName: 'Azure SQL Database', serviceNameKo: 'Azure SQL 데이터베이스', status: 'active', features: ['Intelligent performance', 'Hyperscale', 'Serverless', 'Geo-replication'], featuresKo: ['지능형 성능', '하이퍼스케일', '서버리스', '지오 복제'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed relational database tier', architectureRoleKo: '관리형 관계형 데이터베이스 티어', recommendedFor: ['Enterprise SQL workloads', '.NET application backends', 'Serverless database needs', 'Global data distribution'], recommendedForKo: ['엔터프라이즈 SQL 워크로드', '.NET 애플리케이션 백엔드', '서버리스 데이터베이스 요구', '글로벌 데이터 분산'], sla: '99.995%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/azure-sql/', typicalMonthlyCostUsd: 200, supportedProtocols: ['TDS', 'ODBC', 'JDBC', 'ADO.NET', 'REST API'], haFeatures: ['Availability Zones', 'Auto-failover groups', 'Geo-replication', 'Hyperscale replicas'], securityCapabilities: ['TDE', 'Always Encrypted', 'Dynamic data masking', 'Row-level security', 'Azure Defender for SQL'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 30, maxRPOMinutes: 5, backupFrequency: 'continuous', multiRegionSupported: true }, requiredCompanions: [{ componentType: 'azure-vnet', reason: 'VNet integration required for private endpoint access to Azure SQL', reasonKo: 'Azure SQL에 대한 프라이빗 엔드포인트 접근을 위해 VNet 통합이 필요합니다', severity: 'high' }], recommendedCompanions: [{ componentType: 'prometheus', reason: 'Azure Monitor tracks DTU usage, query performance, and deadlock metrics', reasonKo: 'Azure Monitor가 DTU 사용량, 쿼리 성능 및 데드락 메트릭을 추적합니다', severity: 'high' }, { componentType: 'iam', reason: 'Entra ID authentication provides identity-based access without SQL passwords', reasonKo: 'Entra ID 인증이 SQL 비밀번호 없이 ID 기반 접근을 제공합니다', severity: 'medium' }] },

  // ========== DNS ==========
  { id: 'CS-DNS-AZ-001', provider: 'azure', componentType: 'dns', serviceName: 'Azure DNS', serviceNameKo: 'Azure DNS', status: 'active', features: ['Anycast', 'Private zones', 'Alias records', 'DNSSEC'], featuresKo: ['애니캐스트', '프라이빗 존', '별칭 레코드', 'DNSSEC'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'DNS hosting and resolution', architectureRoleKo: 'DNS 호스팅 및 해석', recommendedFor: ['Azure-native DNS hosting', 'Private DNS resolution', 'Hybrid DNS management', 'Traffic Manager integration'], recommendedForKo: ['Azure 네이티브 DNS 호스팅', '프라이빗 DNS 해석', '하이브리드 DNS 관리', 'Traffic Manager 통합'], sla: '100%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/dns/', typicalMonthlyCostUsd: 3, supportedProtocols: ['DNS/UDP', 'DNS/TCP', 'DNS over HTTPS'], haFeatures: ['Anycast routing', '100% SLA', 'Global name server distribution'], securityCapabilities: ['DNSSEC', 'Private DNS zones', 'VNet-linked DNS resolution'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== CDN ==========
  { id: 'CS-CDN-AZ-001', provider: 'azure', componentType: 'cdn', serviceName: 'Azure Front Door', serviceNameKo: 'Azure Front Door', status: 'active', features: ['Global load balancing', 'WAF', 'Private Link', 'Caching'], featuresKo: ['글로벌 로드 밸런싱', 'WAF', 'Private Link', '캐싱'], pricingTier: 'medium', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Global CDN and application delivery', architectureRoleKo: '글로벌 CDN 및 애플리케이션 전송', recommendedFor: ['Global web application delivery', 'Multi-region failover', 'API acceleration', 'Edge security with WAF'], recommendedForKo: ['글로벌 웹 애플리케이션 전송', '다중 리전 페일오버', 'API 가속', 'WAF 엣지 보안'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/frontdoor/', typicalMonthlyCostUsd: 50, supportedProtocols: ['HTTP/HTTPS', 'HTTP/2', 'WebSocket', 'TLS 1.2/1.3'], haFeatures: ['Global anycast', 'Instant failover', 'Multi-origin health probes'], securityCapabilities: ['Integrated WAF', 'Bot protection', 'DDoS protection', 'Private Link origins', 'Custom domain TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 1, multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'object-storage', reason: 'Azure Blob Storage serves as origin for static content delivery through Front Door', reasonKo: 'Azure Blob Storage가 Front Door를 통한 정적 콘텐츠 전송의 오리진으로 사용됩니다', severity: 'high' }, { componentType: 'waf', reason: 'Azure WAF integrated with Front Door provides edge application protection', reasonKo: 'Front Door와 통합된 Azure WAF가 엣지 애플리케이션 보호를 제공합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor tracks Front Door traffic metrics, cache hit ratio, and latency', reasonKo: 'Azure Monitor가 Front Door 트래픽 메트릭, 캐시 적중률 및 지연 시간을 추적합니다', severity: 'medium' }] },
  { id: 'CS-CDN-AZ-002', provider: 'azure', componentType: 'cdn', serviceName: 'Azure CDN (Classic)', serviceNameKo: 'Azure CDN (클래식)', status: 'deprecated', successor: 'Azure Front Door', successorKo: 'Azure Front Door', features: ['Static caching', 'Basic rules'], featuresKo: ['정적 캐싱', '기본 규칙'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', deploymentModel: 'managed' },

  // ========== Kubernetes ==========
  { id: 'CS-K8S-AZ-001', provider: 'azure', componentType: 'kubernetes', serviceName: 'Azure Kubernetes Service', serviceNameKo: 'Azure Kubernetes Service', status: 'active', features: ['Free control plane', 'KEDA', 'Azure Arc', 'GitOps integration'], featuresKo: ['무료 컨트롤 플레인', 'KEDA', 'Azure Arc', 'GitOps 통합'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Container orchestration platform', architectureRoleKo: '컨테이너 오케스트레이션 플랫폼', recommendedFor: ['Microservice architectures', 'Hybrid/multi-cloud with Arc', 'CI/CD pipeline orchestration', 'Windows container workloads'], recommendedForKo: ['마이크로서비스 아키텍처', 'Arc 하이브리드/멀티클라우드', 'CI/CD 파이프라인 오케스트레이션', 'Windows 컨테이너 워크로드'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/aks/', typicalMonthlyCostUsd: 0, supportedProtocols: ['HTTP/HTTPS', 'gRPC', 'TCP/UDP', 'Kubernetes API'], haFeatures: ['Availability Zones', 'Cluster autoscaler', 'Multi-node pool', 'Pod disruption budgets'], securityCapabilities: ['Azure Policy for AKS', 'Network policies', 'Managed identity', 'Azure Key Vault CSI driver', 'Workload identity'], operationalComplexity: 'complex', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 60, backupFrequency: 'daily', multiRegionSupported: true }, requiredCompanions: [{ componentType: 'azure-vnet', reason: 'AKS clusters must be deployed into a VNet for network isolation and policy enforcement', reasonKo: 'AKS 클러스터는 네트워크 격리 및 정책 적용을 위해 VNet에 배포해야 합니다', severity: 'critical' }], recommendedCompanions: [{ componentType: 'container', reason: 'Azure Container Registry provides private container image storage for AKS workloads', reasonKo: 'Azure Container Registry가 AKS 워크로드를 위한 프라이빗 컨테이너 이미지 스토리지를 제공합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor and Container Insights provide cluster and pod-level observability', reasonKo: 'Azure Monitor와 Container Insights가 클러스터 및 파드 수준 관측성을 제공합니다', severity: 'high' }, { componentType: 'load-balancer', reason: 'Azure Load Balancer or Application Gateway handles ingress traffic to AKS services', reasonKo: 'Azure Load Balancer 또는 Application Gateway가 AKS 서비스로의 인그레스 트래픽을 처리합니다', severity: 'high' }] },

  // ========== Container ==========
  { id: 'CS-CONT-AZ-001', provider: 'azure', componentType: 'container', serviceName: 'Azure Container Instances', serviceNameKo: 'Azure Container Instances', status: 'active', features: ['Serverless', 'Per-second billing', 'GPU support', 'VNet integration'], featuresKo: ['서버리스', '초당 과금', 'GPU 지원', 'VNet 통합'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Serverless container execution', architectureRoleKo: '서버리스 컨테이너 실행', recommendedFor: ['Burst workloads', 'CI/CD build agents', 'Batch processing', 'Simple container hosting'], recommendedForKo: ['버스트 워크로드', 'CI/CD 빌드 에이전트', '배치 처리', '단순 컨테이너 호스팅'], sla: '99.9%', deploymentModel: 'serverless', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/container-instances/', typicalMonthlyCostUsd: 20, supportedProtocols: ['HTTP/HTTPS', 'TCP/UDP'], haFeatures: ['Availability Zones', 'Container group restart policies'], securityCapabilities: ['VNet integration', 'Managed identity', 'Confidential containers'], operationalComplexity: 'simple', ecosystemMaturity: 'stable', disasterRecovery: { multiRegionSupported: false } },

  // ========== Cache ==========
  { id: 'CS-CACHE-AZ-001', provider: 'azure', componentType: 'cache', serviceName: 'Azure Cache for Redis', serviceNameKo: 'Azure Cache for Redis', status: 'active', features: ['Enterprise tier', 'Geo-replication', 'Flash storage', 'Redis modules'], featuresKo: ['엔터프라이즈 티어', '지오 복제', '플래시 스토리지', 'Redis 모듈'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'In-memory caching and session store', architectureRoleKo: '인메모리 캐싱 및 세션 저장소', recommendedFor: ['Session management', 'Real-time analytics', 'Message brokering', 'Content caching'], recommendedForKo: ['세션 관리', '실시간 분석', '메시지 브로커링', '콘텐츠 캐싱'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/', typicalMonthlyCostUsd: 200, supportedProtocols: ['Redis protocol', 'Redis Cluster protocol', 'TLS'], haFeatures: ['Availability Zones', 'Geo-replication', 'Automatic failover', 'Clustering'], securityCapabilities: ['TLS encryption', 'VNet integration', 'Private endpoints', 'Microsoft Entra authentication'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 15, maxRPOMinutes: 1, backupFrequency: 'hourly', multiRegionSupported: true } },

  // ========== Object Storage ==========
  { id: 'CS-OBJ-AZ-001', provider: 'azure', componentType: 'object-storage', serviceName: 'Azure Blob Storage', serviceNameKo: 'Azure Blob Storage', status: 'active', features: ['Hot/Cool/Archive tiers', 'Immutable storage', 'Lifecycle management', 'Data Lake Gen2'], featuresKo: ['핫/쿨/아카이브 티어', '불변 스토리지', '수명주기 관리', 'Data Lake Gen2'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Durable object storage for data lake and backups', architectureRoleKo: '데이터 레이크 및 백업을 위한 내구성 객체 스토리지', recommendedFor: ['Data lake storage', 'Backup and archive', 'Static content hosting', 'Big data analytics'], recommendedForKo: ['데이터 레이크 스토리지', '백업 및 아카이브', '정적 콘텐츠 호스팅', '빅데이터 분석'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/storage/blobs/', typicalMonthlyCostUsd: 20, supportedProtocols: ['REST API', 'Azure Data Lake Storage Gen2', 'NFS 3.0', 'SFTP'], haFeatures: ['LRS', 'ZRS', 'GRS', 'RA-GRS', 'GZRS', 'RA-GZRS'], securityCapabilities: ['Azure Key Vault integration', 'Customer-managed keys', 'Immutable storage', 'Soft delete', 'Encryption at rest'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { maxRPOMinutes: 0, backupFrequency: 'continuous', multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'cdn', reason: 'Azure Front Door/CDN accelerates Blob Storage content delivery globally', reasonKo: 'Azure Front Door/CDN이 Blob Storage 콘텐츠 전송을 글로벌로 가속합니다', severity: 'high' }, { componentType: 'iam', reason: 'Entra ID RBAC and SAS tokens control fine-grained access to blobs', reasonKo: 'Entra ID RBAC 및 SAS 토큰이 blob에 대한 세분화된 접근을 제어합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor tracks storage capacity, transaction metrics, and availability', reasonKo: 'Azure Monitor가 스토리지 용량, 트랜잭션 메트릭 및 가용성을 추적합니다', severity: 'medium' }] },

  // ========== Backup ==========
  { id: 'CS-BK-AZ-001', provider: 'azure', componentType: 'backup', serviceName: 'Azure Backup', serviceNameKo: 'Azure Backup', status: 'active', features: ['Multi-workload', 'Instant restore', 'Soft delete', 'Cross-region restore'], featuresKo: ['다중 워크로드', '즉시 복원', '소프트 삭제', '교차 리전 복원'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Centralized backup management', architectureRoleKo: '중앙 집중식 백업 관리', recommendedFor: ['VM backup', 'SQL/SAP HANA backup', 'File share backup', 'Cross-region disaster recovery'], recommendedForKo: ['VM 백업', 'SQL/SAP HANA 백업', '파일 공유 백업', '교차 리전 재해 복구'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/backup/', typicalMonthlyCostUsd: 15, supportedProtocols: ['MARS agent', 'MABS', 'REST API'], haFeatures: ['GRS vault replication', 'Cross-region restore', 'Multi-workload support'], securityCapabilities: ['Soft delete', 'MUA (multi-user authorization)', 'Encryption at rest', 'Private endpoints', 'Immutable vaults'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 120, maxRPOMinutes: 60, backupFrequency: 'daily', multiRegionSupported: true } },

  // ========== VPN Gateway ==========
  { id: 'CS-VPN-AZ-001', provider: 'azure', componentType: 'vpn-gateway', serviceName: 'Azure VPN Gateway', serviceNameKo: 'Azure VPN 게이트웨이', status: 'active', features: ['Site-to-site', 'Point-to-site', 'VPN over ExpressRoute', 'Active-active'], featuresKo: ['사이트간', '포인트투사이트', 'ExpressRoute VPN', '액티브-액티브'], pricingTier: 'medium', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Hybrid cloud encrypted connectivity', architectureRoleKo: '하이브리드 클라우드 암호화 연결', recommendedFor: ['On-premise to Azure connectivity', 'Branch office VPN', 'Multi-site connectivity', 'ExpressRoute backup path'], recommendedForKo: ['온프레미스-Azure 연결', '지점 VPN', '다중 사이트 연결', 'ExpressRoute 백업 경로'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/vpn-gateway/', typicalMonthlyCostUsd: 140, supportedProtocols: ['IPsec/IKEv2', 'OpenVPN', 'SSTP', 'BGP'], haFeatures: ['Active-active configuration', 'Availability Zones', 'ExpressRoute failover'], securityCapabilities: ['IPsec encryption', 'Certificate authentication', 'RADIUS integration', 'NAT-T support'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== IAM ==========
  { id: 'CS-IAM-AZ-001', provider: 'azure', componentType: 'iam', serviceName: 'Microsoft Entra ID', serviceNameKo: 'Microsoft Entra ID', status: 'active', features: ['SSO', 'Conditional access', 'PIM', 'Identity governance'], featuresKo: ['SSO', '조건부 접근', 'PIM', 'ID 거버넌스'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Identity and access management foundation', architectureRoleKo: 'ID 및 접근 관리 기반', recommendedFor: ['Enterprise identity management', 'SaaS SSO federation', 'Conditional access policies', 'Privileged identity management'], recommendedForKo: ['엔터프라이즈 ID 관리', 'SaaS SSO 연동', '조건부 접근 정책', '권한 있는 ID 관리'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/entra/identity/', typicalMonthlyCostUsd: 0, supportedProtocols: ['SAML 2.0', 'OpenID Connect', 'OAuth 2.0', 'WS-Federation', 'SCIM'], haFeatures: ['Global multi-region', '99.99% SLA', 'Automatic failover'], securityCapabilities: ['Conditional access', 'Privileged Identity Management', 'Identity Protection', 'Continuous access evaluation', 'Verified ID'], operationalComplexity: 'complex', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },
  { id: 'CS-IAM-AZ-002', provider: 'azure', componentType: 'iam', serviceName: 'Azure Active Directory', serviceNameKo: 'Azure Active Directory', status: 'deprecated', successor: 'Microsoft Entra ID', successorKo: 'Microsoft Entra ID', features: ['Identity management', 'MFA', 'SSPR'], featuresKo: ['ID 관리', 'MFA', 'SSPR'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', deploymentModel: 'managed' },

  // ========== SIEM ==========
  { id: 'CS-SIEM-AZ-001', provider: 'azure', componentType: 'siem', serviceName: 'Microsoft Sentinel', serviceNameKo: 'Microsoft Sentinel', status: 'active', features: ['Cloud-native SIEM', 'SOAR built-in', 'Fusion ML', 'Data connectors'], featuresKo: ['클라우드 네이티브 SIEM', 'SOAR 내장', 'Fusion ML', '데이터 커넥터'], pricingTier: 'high', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Cloud-native SIEM and SOAR', architectureRoleKo: '클라우드 네이티브 SIEM 및 SOAR', recommendedFor: ['Enterprise SIEM', 'Security orchestration', 'Multi-cloud threat detection', 'Incident response automation'], recommendedForKo: ['엔터프라이즈 SIEM', '보안 오케스트레이션', '멀티클라우드 위협 탐지', '인시던트 대응 자동화'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/sentinel/', typicalMonthlyCostUsd: 500, supportedProtocols: ['REST API', 'KQL', 'Syslog', 'CEF', 'Azure Monitor Agent'], haFeatures: ['Multi-workspace architecture', 'Cross-tenant management', 'Log Analytics redundancy'], securityCapabilities: ['Fusion ML detection', 'SOAR playbooks', 'UEBA', 'Threat intelligence integration', 'Hunting queries'], operationalComplexity: 'complex', ecosystemMaturity: 'mature', disasterRecovery: { backupFrequency: 'continuous', multiRegionSupported: true } },

  // ========== IDS/IPS ==========
  { id: 'CS-IDS-AZ-001', provider: 'azure', componentType: 'ids-ips', serviceName: 'Azure Firewall Premium IDS/IPS', serviceNameKo: 'Azure Firewall Premium IDS/IPS', status: 'active', features: ['Signature-based', 'TLS inspection', '58K+ signatures', 'IDPS categories'], featuresKo: ['시그니처 기반', 'TLS 검사', '58K+ 시그니처', 'IDPS 카테고리'], pricingTier: 'high', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Network-layer intrusion detection and prevention', architectureRoleKo: '네트워크 계층 침입 탐지 및 방지', recommendedFor: ['Encrypted traffic inspection', 'Compliance monitoring', 'Advanced threat protection', 'Hub-spoke security'], recommendedForKo: ['암호화 트래픽 검사', '컴플라이언스 모니터링', '고급 위협 보호', '허브-스포크 보안'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/firewall/premium-features', typicalMonthlyCostUsd: 1500, supportedProtocols: ['TCP/UDP', 'HTTP/HTTPS', 'TLS 1.0-1.3', 'ICMP'], haFeatures: ['Availability Zones', 'Auto-scaling', 'Active-active deployment'], securityCapabilities: ['TLS inspection', '58K+ IDPS signatures', 'URL filtering', 'Web categories', 'Threat intelligence feeds'], operationalComplexity: 'complex', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== SD-WAN ==========
  { id: 'CS-SDWAN-AZ-001', provider: 'azure', componentType: 'sd-wan', serviceName: 'Azure Virtual WAN', serviceNameKo: 'Azure Virtual WAN', status: 'active', features: ['Hub-spoke', 'SD-WAN integration', 'ExpressRoute', 'Routing intent'], featuresKo: ['허브-스포크', 'SD-WAN 통합', 'ExpressRoute', '라우팅 인텐트'], pricingTier: 'high', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Global WAN management and orchestration', architectureRoleKo: '글로벌 WAN 관리 및 오케스트레이션', recommendedFor: ['Branch connectivity', 'Global transit networking', 'SD-WAN integration', 'ExpressRoute management'], recommendedForKo: ['지점 연결', '글로벌 트랜짓 네트워킹', 'SD-WAN 통합', 'ExpressRoute 관리'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/virtual-wan/', typicalMonthlyCostUsd: 400, supportedProtocols: ['IPsec/IKEv2', 'BGP', 'ExpressRoute', 'OpenVPN', 'SD-WAN NVA'], haFeatures: ['Active-active hubs', 'Multi-hub routing', 'Automatic failover'], securityCapabilities: ['Azure Firewall integration', 'Routing intent policies', 'Encrypted branch connectivity', 'NVA in hub'], operationalComplexity: 'complex', ecosystemMaturity: 'stable', disasterRecovery: { multiRegionSupported: true } },

  // ========== MFA ==========
  { id: 'CS-MFA-AZ-001', provider: 'azure', componentType: 'mfa', serviceName: 'Entra ID MFA', serviceNameKo: 'Entra ID MFA', status: 'active', features: ['Push notification', 'Number matching', 'Passwordless', 'FIDO2 keys'], featuresKo: ['푸시 알림', '번호 매칭', '패스워드리스', 'FIDO2 키'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Multi-factor authentication', architectureRoleKo: '다중 인증', recommendedFor: ['Enterprise user authentication', 'Passwordless adoption', 'Conditional access enforcement', 'Phishing-resistant authentication'], recommendedForKo: ['엔터프라이즈 사용자 인증', '패스워드리스 도입', '조건부 접근 적용', '피싱 방지 인증'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/entra/identity/authentication/', typicalMonthlyCostUsd: 0, supportedProtocols: ['OATH TOTP', 'FIDO2', 'Microsoft Authenticator', 'SMS', 'Voice call'], haFeatures: ['Global availability', 'Fallback authentication methods', 'Conditional access integration'], securityCapabilities: ['Phishing-resistant MFA', 'Number matching', 'Passwordless authentication', 'Certificate-based authentication'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== VNet (NEW) ==========
  { id: 'CS-VPC-AZ-001', provider: 'azure', componentType: 'azure-vnet', serviceName: 'Azure Virtual Network', serviceNameKo: 'Azure Virtual Network', status: 'active', features: ['Subnets', 'NSGs', 'Service endpoints', 'VNet peering', 'Private Link'], featuresKo: ['서브넷', 'NSG', '서비스 엔드포인트', 'VNet 피어링', 'Private Link'], pricingTier: 'free', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Virtual network isolation foundation', architectureRoleKo: '가상 네트워크 격리 기반', recommendedFor: ['Network segmentation', 'Hub-spoke architectures', 'Hybrid cloud networking', 'Service isolation'], recommendedForKo: ['네트워크 세그멘테이션', '허브-스포크 아키텍처', '하이브리드 클라우드 네트워킹', '서비스 격리'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/virtual-network/', typicalMonthlyCostUsd: 0, supportedProtocols: ['TCP/UDP', 'IPv4', 'IPv6', 'VNet peering', 'Private Link'], haFeatures: ['Availability Zones', 'VNet peering (global)', 'Service endpoints'], securityCapabilities: ['NSG', 'ASG', 'DDoS Protection', 'Private Link', 'Service endpoints', 'VNet flow logs'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'firewall', reason: 'Azure Firewall provides centralized egress filtering and threat protection for VNet traffic', reasonKo: 'Azure Firewall이 VNet 트래픽에 대한 중앙 집중식 송신 필터링 및 위협 보호를 제공합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor with VNet flow logs provides network traffic visibility and diagnostics', reasonKo: 'Azure Monitor와 VNet 플로우 로그가 네트워크 트래픽 가시성 및 진단을 제공합니다', severity: 'high' }, { componentType: 'vpn-gateway', reason: 'VPN Gateway enables secure hybrid connectivity between VNet and on-premises networks', reasonKo: 'VPN Gateway가 VNet과 온프레미스 네트워크 간 안전한 하이브리드 연결을 가능하게 합니다', severity: 'medium' }] },

  // ========== Serverless (NEW) ==========
  { id: 'CS-SLS-AZ-001', provider: 'azure', componentType: 'app-server', serviceName: 'Azure Functions', serviceNameKo: 'Azure Functions', status: 'active', features: ['Event-driven', 'Durable functions', 'Bindings/Triggers', 'Premium plan'], featuresKo: ['이벤트 기반', 'Durable Functions', '바인딩/트리거', '프리미엄 플랜'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Serverless event-driven compute', architectureRoleKo: '서버리스 이벤트 기반 컴퓨팅', recommendedFor: ['Event-driven processing', 'Timer-based tasks', 'Workflow orchestration', 'IoT data processing'], recommendedForKo: ['이벤트 기반 처리', '타이머 기반 작업', '워크플로우 오케스트레이션', 'IoT 데이터 처리'], sla: '99.95%', deploymentModel: 'serverless', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/azure-functions/', typicalMonthlyCostUsd: 5, supportedProtocols: ['HTTP/HTTPS', 'Event Grid', 'Service Bus', 'Timer trigger', 'Blob trigger'], haFeatures: ['Availability Zones', 'Premium plan scaling', 'Durable Functions checkpointing'], securityCapabilities: ['Managed identity', 'VNet integration', 'Private endpoints', 'IP restrictions'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 15, backupFrequency: 'continuous', multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'api-gateway', reason: 'API Management exposes Azure Functions as managed API endpoints with throttling and auth', reasonKo: 'API Management가 Azure Functions를 스로틀링과 인증이 포함된 관리형 API 엔드포인트로 노출합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor tracks function invocations, failures, and execution duration', reasonKo: 'Azure Monitor가 함수 호출, 실패 및 실행 시간을 추적합니다', severity: 'high' }, { componentType: 'iam', reason: 'Managed identity enables secure access to Azure resources without storing credentials', reasonKo: '관리 ID가 자격 증명 저장 없이 Azure 리소스에 대한 안전한 접근을 가능하게 합니다', severity: 'medium' }] },

  // ========== Message Queue (NEW) ==========
  { id: 'CS-MQ-AZ-001', provider: 'azure', componentType: 'kafka', serviceName: 'Azure Event Hubs', serviceNameKo: 'Azure Event Hubs', status: 'active', features: ['Kafka-compatible', 'Capture to storage', 'Schema registry', 'Auto-inflate'], featuresKo: ['Kafka 호환', '스토리지 캡처', '스키마 레지스트리', '자동 확장'], pricingTier: 'medium', trust: t, serviceCategory: 'Messaging', serviceCategoryKo: '메시징', architectureRole: 'Distributed streaming platform', architectureRoleKo: '분산 스트리밍 플랫폼', recommendedFor: ['Real-time data ingestion', 'Kafka migration', 'Telemetry streaming', 'Event sourcing'], recommendedForKo: ['실시간 데이터 수집', 'Kafka 마이그레이션', '텔레메트리 스트리밍', '이벤트 소싱'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/event-hubs/', typicalMonthlyCostUsd: 300, supportedProtocols: ['AMQP 1.0', 'Kafka', 'HTTPS', 'Apache Avro'], haFeatures: ['Availability Zones', 'Geo-disaster recovery', 'Auto-inflate throughput units'], securityCapabilities: ['Managed identity', 'Customer-managed keys', 'Private endpoints', 'IP firewall rules'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 30, backupFrequency: 'continuous', multiRegionSupported: true } },
  { id: 'CS-MQ-AZ-002', provider: 'azure', componentType: 'rabbitmq', serviceName: 'Azure Service Bus', serviceNameKo: 'Azure Service Bus', status: 'active', features: ['Queues/Topics', 'Sessions', 'Dead-lettering', 'Transactions'], featuresKo: ['큐/토픽', '세션', '데드 레터링', '트랜잭션'], pricingTier: 'low', trust: t, serviceCategory: 'Messaging', serviceCategoryKo: '메시징', architectureRole: 'Enterprise message broker', architectureRoleKo: '엔터프라이즈 메시지 브로커', recommendedFor: ['Enterprise messaging', 'Order processing', 'Workload decoupling', 'Transactional workflows'], recommendedForKo: ['엔터프라이즈 메시징', '주문 처리', '워크로드 분리', '트랜잭션 워크플로우'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/service-bus-messaging/', typicalMonthlyCostUsd: 100, supportedProtocols: ['AMQP 1.0', 'HTTPS', 'SBMP'], haFeatures: ['Availability Zones', 'Geo-disaster recovery', 'Auto-forwarding', 'Duplicate detection'], securityCapabilities: ['Managed identity', 'SAS tokens', 'Private endpoints', 'IP firewall rules', 'Customer-managed keys'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 30, maxRPOMinutes: 0, backupFrequency: 'continuous', multiRegionSupported: true } },

  // ========== Monitoring (NEW) ==========
  { id: 'CS-MON-AZ-001', provider: 'azure', componentType: 'prometheus', serviceName: 'Azure Monitor', serviceNameKo: 'Azure Monitor', status: 'active', features: ['Metrics', 'Log Analytics', 'Application Insights', 'Alerts'], featuresKo: ['메트릭', 'Log Analytics', 'Application Insights', '알림'], pricingTier: 'low', trust: t, serviceCategory: 'Monitoring', serviceCategoryKo: '모니터링', architectureRole: 'Cloud-native observability platform', architectureRoleKo: '클라우드 네이티브 관측 플랫폼', recommendedFor: ['Infrastructure monitoring', 'Application performance monitoring', 'Log analytics', 'Automated alerting'], recommendedForKo: ['인프라 모니터링', '애플리케이션 성능 모니터링', '로그 분석', '자동 알림'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/azure-monitor/', typicalMonthlyCostUsd: 50, supportedProtocols: ['REST API', 'KQL', 'Azure Monitor Agent', 'Prometheus remote write', 'OpenTelemetry'], haFeatures: ['Multi-region workspace', 'Dedicated clusters', 'Data export redundancy'], securityCapabilities: ['RBAC', 'Customer-managed keys', 'Private Link', 'Data export controls'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { backupFrequency: 'continuous', multiRegionSupported: true } },

  // ========== Search (NEW) ==========
  { id: 'CS-SRCH-AZ-001', provider: 'azure', componentType: 'elasticsearch', serviceName: 'Azure AI Search', serviceNameKo: 'Azure AI Search', status: 'active', features: ['Full-text search', 'AI enrichment', 'Vector search', 'Semantic ranking'], featuresKo: ['전문 검색', 'AI 보강', '벡터 검색', '시맨틱 랭킹'], pricingTier: 'medium', trust: t, serviceCategory: 'Analytics', serviceCategoryKo: '분석', architectureRole: 'Full-text and AI-powered search', architectureRoleKo: '전문 및 AI 기반 검색', recommendedFor: ['Application search', 'Knowledge mining', 'RAG pattern implementation', 'Document intelligence'], recommendedForKo: ['애플리케이션 검색', '지식 마이닝', 'RAG 패턴 구현', '문서 인텔리전스'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/search/', typicalMonthlyCostUsd: 250, supportedProtocols: ['REST API', 'OData', '.NET SDK', 'Python SDK', 'Java SDK'], haFeatures: ['Availability Zones', 'Replica partitions', 'Multi-region deployment'], securityCapabilities: ['Customer-managed keys', 'Private endpoints', 'IP firewall rules', 'RBAC', 'Managed identity'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable', disasterRecovery: { backupFrequency: 'continuous', multiRegionSupported: false } },

  // ========== Block Storage (NEW) ==========
  { id: 'CS-STOR-AZ-001', provider: 'azure', componentType: 'storage', serviceName: 'Azure Managed Disks', serviceNameKo: 'Azure 관리 디스크', status: 'active', features: ['Premium SSD', 'Ultra Disk', 'Shared disks', 'Encryption'], featuresKo: ['프리미엄 SSD', 'Ultra Disk', '공유 디스크', '암호화'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Block storage for virtual machines', architectureRoleKo: '가상 머신용 블록 스토리지', recommendedFor: ['VM OS and data disks', 'High-IOPS databases', 'SAP HANA storage', 'Shared cluster storage'], recommendedForKo: ['VM OS 및 데이터 디스크', '고 IOPS 데이터베이스', 'SAP HANA 스토리지', '공유 클러스터 스토리지'], sla: '99.999%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview', maxCapacity: '64 TiB per disk, 160K IOPS', typicalMonthlyCostUsd: 60, supportedProtocols: ['SCSI', 'NVMe', 'REST API'], haFeatures: ['Availability Zones', 'ZRS disks', 'Shared disks for clustering', 'Incremental snapshots'], securityCapabilities: ['Server-side encryption', 'Azure Key Vault integration', 'Customer-managed keys', 'Double encryption', 'Private Link for disk access'], operationalComplexity: 'simple', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 60, backupFrequency: 'daily', multiRegionSupported: true } },

  // ========== API Gateway (NEW) ==========
  { id: 'CS-APIGW-AZ-001', provider: 'azure', componentType: 'api-gateway', serviceName: 'Azure API Management', serviceNameKo: 'Azure API Management', status: 'active', features: ['Developer portal', 'Policy engine', 'Monetization', 'Multi-region'], featuresKo: ['개발자 포털', '정책 엔진', '수익화', '다중 리전'], pricingTier: 'medium', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'API management and gateway', architectureRoleKo: 'API 관리 및 게이트웨이', recommendedFor: ['API lifecycle management', 'Developer ecosystem', 'API monetization', 'Backend API federation'], recommendedForKo: ['API 수명주기 관리', '개발자 생태계', 'API 수익화', '백엔드 API 연합'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/api-management/', typicalMonthlyCostUsd: 50, supportedProtocols: ['REST API', 'SOAP', 'GraphQL', 'WebSocket', 'gRPC'], haFeatures: ['Availability Zones', 'Multi-region deployment', 'Self-hosted gateway'], securityCapabilities: ['OAuth 2.0 validation', 'JWT validation', 'Client certificates', 'IP filtering', 'Rate limiting'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 30, backupFrequency: 'daily', multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'app-server', reason: 'Azure Functions and Container Apps serve as backends managed through API Management', reasonKo: 'Azure Functions와 Container Apps가 API Management를 통해 관리되는 백엔드 역할을 합니다', severity: 'high' }, { componentType: 'prometheus', reason: 'Azure Monitor tracks API request volumes, latency, and error rates', reasonKo: 'Azure Monitor가 API 요청량, 지연 시간 및 오류율을 추적합니다', severity: 'high' }, { componentType: 'waf', reason: 'WAF policies protect API endpoints from OWASP threats and bot attacks', reasonKo: 'WAF 정책이 OWASP 위협과 봇 공격으로부터 API 엔드포인트를 보호합니다', severity: 'medium' }] },

  // ========== NoSQL (NEW) ==========
  { id: 'CS-NOSQL-AZ-001', provider: 'azure', componentType: 'db-server', serviceName: 'Azure Cosmos DB', serviceNameKo: 'Azure Cosmos DB', status: 'active', features: ['Multi-model', 'Global distribution', 'Multi-master', '5 consistency levels'], featuresKo: ['다중 모델', '글로벌 분산', '다중 마스터', '5개 일관성 수준'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Globally distributed NoSQL database', architectureRoleKo: '글로벌 분산 NoSQL 데이터베이스', recommendedFor: ['Global-scale applications', 'Multi-region writes', 'IoT data storage', 'Real-time personalization'], recommendedForKo: ['글로벌 규모 애플리케이션', '다중 리전 쓰기', 'IoT 데이터 저장', '실시간 개인화'], sla: '99.999%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/azure/cosmos-db/', typicalMonthlyCostUsd: 100, supportedProtocols: ['SQL API', 'MongoDB API', 'Cassandra API', 'Gremlin API', 'Table API'], haFeatures: ['Multi-region writes', 'Automatic failover', 'Availability Zones', '5 consistency levels'], securityCapabilities: ['Always Encrypted', 'Customer-managed keys', 'Private endpoints', 'VNet service endpoints', 'RBAC'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { maxRTOMinutes: 0, maxRPOMinutes: 0, backupFrequency: 'continuous', multiRegionSupported: true }, recommendedCompanions: [{ componentType: 'prometheus', reason: 'Azure Monitor tracks RU consumption, throttling, latency, and partition-level diagnostics', reasonKo: 'Azure Monitor가 RU 소비, 스로틀링, 지연 시간 및 파티션 수준 진단을 추적합니다', severity: 'high' }, { componentType: 'iam', reason: 'Entra ID RBAC provides identity-based access control to Cosmos DB resources', reasonKo: 'Entra ID RBAC가 Cosmos DB 리소스에 대한 ID 기반 접근 제어를 제공합니다', severity: 'medium' }], conflictsWith: [{ componentType: 'db-server', reason: 'Using both Cosmos DB and Azure SQL for the same workload creates complexity; choose based on data model and consistency needs', reasonKo: '동일 워크로드에 Cosmos DB와 Azure SQL을 함께 사용하면 복잡성이 발생합니다; 데이터 모델과 일관성 요구에 따라 선택하세요' }] },

  // ========== DLP (NEW) ==========
  { id: 'CS-DLP-AZ-001', provider: 'azure', componentType: 'dlp', serviceName: 'Microsoft Purview Information Protection', serviceNameKo: 'Microsoft Purview 정보 보호', status: 'active', features: ['Sensitivity labels', 'Auto-classification', 'DLP policies', 'Encryption'], featuresKo: ['민감도 레이블', '자동 분류', 'DLP 정책', '암호화'], pricingTier: 'medium', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Data loss prevention and classification', architectureRoleKo: '데이터 유출 방지 및 분류', recommendedFor: ['M365 data protection', 'Regulatory compliance', 'Sensitive data classification', 'Email DLP'], recommendedForKo: ['M365 데이터 보호', '규제 컴플라이언스', '민감 데이터 분류', '이메일 DLP'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'subscription', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/purview/information-protection', typicalMonthlyCostUsd: 120, supportedProtocols: ['REST API', 'Microsoft Graph API', 'Exchange Web Services'], haFeatures: ['Multi-region service', 'M365 global infrastructure'], securityCapabilities: ['Sensitivity labels', 'Auto-classification', 'Rights management encryption', 'Exact data match', 'Endpoint DLP'], operationalComplexity: 'complex', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== SSO (NEW) ==========
  { id: 'CS-SSO-AZ-001', provider: 'azure', componentType: 'sso', serviceName: 'Entra ID SSO', serviceNameKo: 'Entra ID SSO', status: 'active', features: ['SAML/OIDC/WS-Fed', 'App gallery', 'Provisioning', 'Conditional access'], featuresKo: ['SAML/OIDC/WS-Fed', '앱 갤러리', '프로비저닝', '조건부 접근'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Centralized single sign-on', architectureRoleKo: '중앙 집중식 싱글 사인온', recommendedFor: ['Enterprise SaaS SSO', 'Application gallery integration', 'Automated provisioning', 'B2B collaboration'], recommendedForKo: ['엔터프라이즈 SaaS SSO', '앱 갤러리 통합', '자동 프로비저닝', 'B2B 협업'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/', typicalMonthlyCostUsd: 0, supportedProtocols: ['SAML 2.0', 'OpenID Connect', 'OAuth 2.0', 'WS-Federation', 'SCIM'], haFeatures: ['Global multi-region', 'Automatic failover', '99.99% SLA'], securityCapabilities: ['Conditional access', 'App proxy', 'Token protection', 'Cross-tenant access settings'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature', disasterRecovery: { multiRegionSupported: true } },

  // ========== LDAP / Directory (NEW) ==========
  { id: 'CS-LDAP-AZ-001', provider: 'azure', componentType: 'ldap-ad', serviceName: 'Entra Domain Services', serviceNameKo: 'Entra Domain Services', status: 'active', features: ['Managed AD DS', 'LDAP', 'Kerberos/NTLM', 'Group Policy'], featuresKo: ['관리형 AD DS', 'LDAP', 'Kerberos/NTLM', '그룹 정책'], pricingTier: 'medium', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Managed directory and LDAP service', architectureRoleKo: '관리형 디렉터리 및 LDAP 서비스', recommendedFor: ['Legacy app authentication', 'LDAP-dependent workloads', 'Domain join for VMs', 'Hybrid identity extension'], recommendedForKo: ['레거시 앱 인증', 'LDAP 종속 워크로드', 'VM 도메인 가입', '하이브리드 ID 확장'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://learn.microsoft.com/en-us/entra/identity/domain-services/', typicalMonthlyCostUsd: 110, supportedProtocols: ['LDAP', 'LDAPS', 'Kerberos', 'NTLM'], haFeatures: ['Replica sets across regions', 'Two domain controllers per set', 'Automatic patching'], securityCapabilities: ['Secure LDAP', 'Kerberos constrained delegation', 'Password hash synchronization', 'Fine-grained password policies'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable', disasterRecovery: { multiRegionSupported: true } },
];
