/**
 * Kakao Cloud Services
 *
 * 15+ services with GPU/AI specialization and Korean-first bilingual support.
 * ISMS-P certified, Kakao ecosystem integration.
 */

import type { CloudService } from '../types';
import { svcTrust } from '../types';

const t = svcTrust('kakao');
const certs = ['ISMS-P', 'ISO 27001', 'ISO 27017', 'CSA STAR'];

export const KAKAO_SERVICES: CloudService[] = [
  // ========== Compute ==========
  { id: 'CS-WEB-KAKAO-001', provider: 'kakao', componentType: 'web-server', serviceName: 'Virtual Machine', serviceNameKo: '가상 머신', status: 'active', features: ['Flexible instance types', 'Auto Scaling', 'SSD storage', 'Multi-zone placement'], featuresKo: ['유연한 인스턴스 타입', '오토 스케일링', 'SSD 스토리지', '다중 존 배치'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'General-purpose compute for web and application hosting', architectureRoleKo: '웹 및 애플리케이션 호스팅을 위한 범용 컴퓨팅', recommendedFor: ['Web hosting', 'Application servers', 'Development environments', 'Enterprise workloads'], recommendedForKo: ['웹 호스팅', '애플리케이션 서버', '개발 환경', '엔터프라이즈 워크로드'], sla: '99.95%', deploymentModel: 'self-managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/virtual-machine', typicalMonthlyCostUsd: 25, supportedProtocols: ['HTTP/HTTPS', 'SSH', 'RDP', 'TCP/UDP'], haFeatures: ['Auto Scaling', 'Multi-zone placement', 'Live migration'], securityCapabilities: ['Security Group', 'VPC isolation', 'Disk encryption'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-AIML-KAKAO-001', provider: 'kakao', componentType: 'gpu-server', serviceName: 'GPU Instance', serviceNameKo: 'GPU 인스턴스', status: 'active', features: ['NVIDIA A100/H100 GPUs', 'High-speed interconnect', 'ML framework support', 'Shared/dedicated options'], featuresKo: ['NVIDIA A100/H100 GPU', '고속 인터커넥트', 'ML 프레임워크 지원', '공유/전용 옵션'], pricingTier: 'high', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'GPU-accelerated compute for AI/ML', architectureRoleKo: 'AI/ML을 위한 GPU 가속 컴퓨팅', recommendedFor: ['Deep learning training', 'LLM fine-tuning', 'HPC workloads', 'AI inference'], recommendedForKo: ['딥러닝 학습', 'LLM 파인튜닝', 'HPC 워크로드', 'AI 추론'], sla: '99.95%', deploymentModel: 'self-managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1'], documentationUrl: 'https://docs.kakaocloud.com/service/gpu', typicalMonthlyCostUsd: 2000, supportedProtocols: ['SSH', 'HTTP/HTTPS', 'NCCL', 'RDMA'], haFeatures: ['Multi-GPU configurations', 'GPU monitoring'], securityCapabilities: ['VPC isolation', 'Security Group', 'Disk encryption'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },
  { id: 'CS-APP-KAKAO-001', provider: 'kakao', componentType: 'app-server', serviceName: 'Serverless', serviceNameKo: '서버리스', status: 'active', features: ['Event-driven compute', 'Auto-scaling', 'Multiple runtimes', 'Pay per execution'], featuresKo: ['이벤트 기반 컴퓨팅', '자동 확장', '다중 런타임', '실행당 과금'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Serverless event-driven compute', architectureRoleKo: '서버리스 이벤트 기반 컴퓨팅', recommendedFor: ['Event processing', 'API backends', 'Data pipelines', 'Scheduled tasks'], recommendedForKo: ['이벤트 처리', 'API 백엔드', '데이터 파이프라인', '예약 작업'], sla: '99.9%', deploymentModel: 'serverless', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1'], documentationUrl: 'https://docs.kakaocloud.com/service/serverless', typicalMonthlyCostUsd: 5, supportedProtocols: ['HTTP/HTTPS', 'Event triggers'], haFeatures: ['Auto-scaling', 'Multi-zone'], securityCapabilities: ['VPC integration', 'IAM roles'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },

  // ========== Kubernetes & Container ==========
  { id: 'CS-K8S-KAKAO-001', provider: 'kakao', componentType: 'kubernetes', serviceName: 'Kubernetes Engine', serviceNameKo: 'Kubernetes Engine', status: 'active', features: ['Managed Kubernetes', 'GPU node pools', 'Auto-scaling', 'VPC CNI'], featuresKo: ['관리형 Kubernetes', 'GPU 노드풀', '오토 스케일링', 'VPC CNI'], pricingTier: 'medium', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Container orchestration platform', architectureRoleKo: '컨테이너 오케스트레이션 플랫폼', recommendedFor: ['Microservice architectures', 'AI/ML workloads', 'CI/CD pipelines', 'Scalable applications'], recommendedForKo: ['마이크로서비스 아키텍처', 'AI/ML 워크로드', 'CI/CD 파이프라인', '확장 가능한 애플리케이션'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/kubernetes-engine', typicalMonthlyCostUsd: 72, supportedProtocols: ['HTTP/HTTPS', 'gRPC', 'TCP/UDP', 'Kubernetes API'], haFeatures: ['Multi-zone control plane', 'Cluster Autoscaler', 'Node auto-repair'], securityCapabilities: ['VPC CNI', 'Network Policies', 'RBAC'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },
  { id: 'CS-CONT-KAKAO-001', provider: 'kakao', componentType: 'container', serviceName: 'Container Registry', serviceNameKo: '컨테이너 레지스트리', status: 'active', features: ['Private Docker registry', 'Image scanning', 'Webhook support', 'Lifecycle policies'], featuresKo: ['프라이빗 Docker 레지스트리', '이미지 스캔', '웹훅 지원', '라이프사이클 정책'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Container image management', architectureRoleKo: '컨테이너 이미지 관리', recommendedFor: ['Container image storage', 'CI/CD pipelines', 'Kubernetes deployments', 'Image security'], recommendedForKo: ['컨테이너 이미지 저장', 'CI/CD 파이프라인', 'Kubernetes 배포', '이미지 보안'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1'], documentationUrl: 'https://docs.kakaocloud.com/service/container-registry', typicalMonthlyCostUsd: 5, supportedProtocols: ['Docker Registry API v2', 'HTTPS'], haFeatures: ['Multi-zone storage'], securityCapabilities: ['Image vulnerability scanning', 'Access control', 'HTTPS'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },

  // ========== Storage ==========
  { id: 'CS-OBJ-KAKAO-001', provider: 'kakao', componentType: 'object-storage', serviceName: 'Object Storage', serviceNameKo: '오브젝트 스토리지', status: 'active', features: ['S3-compatible API', 'Lifecycle management', 'CDN integration', 'Versioning'], featuresKo: ['S3 호환 API', '라이프사이클 관리', 'CDN 통합', '버전 관리'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Scalable object storage for unstructured data', architectureRoleKo: '비정형 데이터를 위한 확장 가능한 오브젝트 스토리지', recommendedFor: ['Data lakes', 'Media storage', 'Backup and archive', 'Static website hosting'], recommendedForKo: ['데이터 레이크', '미디어 스토리지', '백업 및 아카이브', '정적 웹사이트 호스팅'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/object-storage', typicalMonthlyCostUsd: 20, supportedProtocols: ['S3 API', 'HTTPS'], haFeatures: ['Multi-zone replication', 'Versioning', 'High durability'], securityCapabilities: ['Server-side encryption', 'Bucket policies', 'Access control'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },
  { id: 'CS-STOR-KAKAO-001', provider: 'kakao', componentType: 'storage', serviceName: 'Block Storage', serviceNameKo: '블록 스토리지', status: 'active', features: ['SSD/HDD options', 'Snapshots', 'Online resize', 'Encryption'], featuresKo: ['SSD/HDD 옵션', '스냅샷', '온라인 크기 변경', '암호화'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Block storage for virtual machines', architectureRoleKo: '가상 머신용 블록 스토리지', recommendedFor: ['Database storage', 'Boot volumes', 'Application data', 'High-IOPS workloads'], recommendedForKo: ['데이터베이스 스토리지', '부트 볼륨', '애플리케이션 데이터', '고 IOPS 워크로드'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/block-storage', typicalMonthlyCostUsd: 30, supportedProtocols: ['NVMe', 'SCSI'], haFeatures: ['Snapshots', 'Online resize', 'Replication'], securityCapabilities: ['Encryption at rest', 'Access control'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },

  // ========== Database ==========
  { id: 'CS-DB-KAKAO-001', provider: 'kakao', componentType: 'db-server', serviceName: 'MySQL', serviceNameKo: 'MySQL', status: 'active', features: ['Managed MySQL', 'Auto backup', 'Read replicas', 'Automatic failover'], featuresKo: ['관리형 MySQL', '자동 백업', '읽기 복제본', '자동 페일오버'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed relational database', architectureRoleKo: '관리형 관계형 데이터베이스', recommendedFor: ['Web applications', 'OLTP workloads', 'E-commerce platforms', 'SaaS backends'], recommendedForKo: ['웹 애플리케이션', 'OLTP 워크로드', '전자상거래 플랫폼', 'SaaS 백엔드'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/mysql', typicalMonthlyCostUsd: 150, supportedProtocols: ['MySQL', 'JDBC', 'ODBC'], haFeatures: ['Master-standby replication', 'Read replicas', 'Automatic failover'], securityCapabilities: ['Encryption at rest', 'VPC isolation', 'SSL/TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-DB-KAKAO-002', provider: 'kakao', componentType: 'db-server', serviceName: 'PostgreSQL', serviceNameKo: 'PostgreSQL', status: 'active', features: ['Managed PostgreSQL', 'Point-in-time recovery', 'Read replicas', 'Extensions support'], featuresKo: ['관리형 PostgreSQL', '시점 복구', '읽기 복제본', '확장 지원'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed advanced relational database', architectureRoleKo: '관리형 고급 관계형 데이터베이스', recommendedFor: ['Complex queries', 'Data analytics', 'GIS applications', 'Enterprise systems'], recommendedForKo: ['복잡한 쿼리', '데이터 분석', 'GIS 애플리케이션', '엔터프라이즈 시스템'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/postgresql', typicalMonthlyCostUsd: 160, supportedProtocols: ['PostgreSQL', 'JDBC', 'ODBC'], haFeatures: ['Streaming replication', 'Automatic failover', 'Read replicas'], securityCapabilities: ['Encryption at rest', 'VPC isolation', 'SSL/TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-CACHE-KAKAO-001', provider: 'kakao', componentType: 'cache', serviceName: 'Redis', serviceNameKo: 'Redis', status: 'active', features: ['Managed Redis', 'Cluster mode', 'Auto failover', 'Persistence options'], featuresKo: ['관리형 Redis', '클러스터 모드', '자동 페일오버', '지속성 옵션'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'In-memory caching and session store', architectureRoleKo: '인메모리 캐싱 및 세션 저장소', recommendedFor: ['Session management', 'Query caching', 'Real-time data', 'Rate limiting'], recommendedForKo: ['세션 관리', '쿼리 캐싱', '실시간 데이터', '속도 제한'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1'], documentationUrl: 'https://docs.kakaocloud.com/service/redis', typicalMonthlyCostUsd: 100, supportedProtocols: ['Redis', 'TLS'], haFeatures: ['Cluster mode', 'Automatic failover', 'Read replicas'], securityCapabilities: ['VPC isolation', 'AUTH', 'TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },

  // ========== Networking ==========
  { id: 'CS-LB-KAKAO-001', provider: 'kakao', componentType: 'load-balancer', serviceName: 'Load Balancer', serviceNameKo: '로드 밸런서', status: 'active', features: ['L4/L7 load balancing', 'Health checks', 'SSL termination', 'Sticky sessions'], featuresKo: ['L4/L7 로드 밸런싱', '헬스 체크', 'SSL 종료', '스티키 세션'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Application-layer traffic distribution', architectureRoleKo: '애플리케이션 계층 트래픽 분산', recommendedFor: ['High availability', 'HTTP/HTTPS workloads', 'Multi-server distribution', 'SSL offloading'], recommendedForKo: ['고가용성', 'HTTP/HTTPS 워크로드', '다중 서버 분산', 'SSL 오프로딩'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/load-balancer', typicalMonthlyCostUsd: 25, supportedProtocols: ['HTTP', 'HTTPS', 'TCP', 'UDP'], haFeatures: ['Multi-zone', 'Health monitoring', 'Auto-healing'], securityCapabilities: ['SSL/TLS termination', 'Security Group integration', 'DDoS protection'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-VPC-KAKAO-001', provider: 'kakao', componentType: 'aws-vpc', serviceName: 'VPC', serviceNameKo: 'VPC', status: 'active', features: ['Subnets', 'Route tables', 'Peering', 'NAT Gateway'], featuresKo: ['서브넷', '라우팅 테이블', '피어링', 'NAT 게이트웨이'], pricingTier: 'free', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Virtual network isolation foundation', architectureRoleKo: '가상 네트워크 격리 기반', recommendedFor: ['Network isolation', 'Multi-tier architectures', 'Security segmentation', 'Hybrid connectivity'], recommendedForKo: ['네트워크 격리', '다중 티어 아키텍처', '보안 세그멘테이션', '하이브리드 연결'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/vpc', typicalMonthlyCostUsd: 0, supportedProtocols: ['TCP/UDP', 'ICMP', 'IPv4'], haFeatures: ['Multi-zone subnets', 'VPC Peering', 'NAT Gateway'], securityCapabilities: ['Network ACL', 'Security Groups', 'Flow Logs'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-DNS-KAKAO-001', provider: 'kakao', componentType: 'dns', serviceName: 'DNS', serviceNameKo: 'DNS', status: 'active', features: ['Managed DNS', 'Record management', 'Health checks', 'API support'], featuresKo: ['관리형 DNS', '레코드 관리', '헬스 체크', 'API 지원'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'DNS resolution service', architectureRoleKo: 'DNS 해석 서비스', recommendedFor: ['Domain management', 'Service discovery', 'Load distribution', 'Health-check routing'], recommendedForKo: ['도메인 관리', '서비스 디스커버리', '부하 분산', '헬스 체크 라우팅'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://docs.kakaocloud.com/service/dns', typicalMonthlyCostUsd: 3, supportedProtocols: ['DNS', 'HTTPS'], haFeatures: ['Global resolution', 'Health check failover'], securityCapabilities: ['DNSSEC support', 'Access control'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },
  { id: 'CS-CDN-KAKAO-001', provider: 'kakao', componentType: 'cdn', serviceName: 'CDN', serviceNameKo: 'CDN', status: 'active', features: ['Korea-optimized PoPs', 'SSL/TLS', 'Real-time purge', 'Custom rules'], featuresKo: ['한국 최적화 PoP', 'SSL/TLS', '실시간 퍼지', '커스텀 규칙'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Content delivery network', architectureRoleKo: '콘텐츠 전송 네트워크', recommendedFor: ['Static content delivery', 'Video streaming', 'Web acceleration', 'API caching'], recommendedForKo: ['정적 콘텐츠 전송', '비디오 스트리밍', '웹 가속', 'API 캐싱'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://docs.kakaocloud.com/service/cdn', typicalMonthlyCostUsd: 25, supportedProtocols: ['HTTP/1.1', 'HTTP/2', 'HTTPS'], haFeatures: ['Korea PoP network', 'Origin failover', 'Real-time purge'], securityCapabilities: ['SSL/TLS', 'Access control', 'DDoS mitigation'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },

  // ========== AI ==========
  { id: 'CS-AIML-KAKAO-002', provider: 'kakao', componentType: 'ai-service', serviceName: 'Beyond AI', serviceNameKo: 'Beyond AI', status: 'active', features: ['ML platform', 'Model training', 'Model serving', 'Experiment tracking'], featuresKo: ['ML 플랫폼', '모델 학습', '모델 서빙', '실험 추적'], pricingTier: 'high', trust: t, serviceCategory: 'AI Service', serviceCategoryKo: 'AI 서비스', architectureRole: 'End-to-end ML platform', architectureRoleKo: '엔드투엔드 ML 플랫폼', recommendedFor: ['ML model development', 'AI pipeline orchestration', 'Model serving at scale', 'Enterprise AI'], recommendedForKo: ['ML 모델 개발', 'AI 파이프라인 오케스트레이션', '대규모 모델 서빙', '엔터프라이즈 AI'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Central-1'], documentationUrl: 'https://docs.kakaocloud.com/service/beyond-ai', typicalMonthlyCostUsd: 500, supportedProtocols: ['REST API', 'gRPC', 'HTTPS'], haFeatures: ['Auto-scaling inference', 'Multi-GPU training'], securityCapabilities: ['VPC isolation', 'API auth', 'Data encryption'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },

  // ========== Security ==========
  { id: 'CS-FW-KAKAO-001', provider: 'kakao', componentType: 'firewall', serviceName: 'Security Group', serviceNameKo: '보안 그룹', status: 'active', features: ['Stateful firewall', 'Inbound/outbound rules', 'Port-level control', 'Instance-level'], featuresKo: ['상태 기반 방화벽', '인바운드/아웃바운드 규칙', '포트 수준 제어', '인스턴스 수준'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Instance-level network access control', architectureRoleKo: '인스턴스 수준 네트워크 접근 제어', recommendedFor: ['Instance-level security', 'Micro-segmentation', 'Application isolation', 'Default security'], recommendedForKo: ['인스턴스 수준 보안', '마이크로 세그멘테이션', '애플리케이션 격리', '기본 보안'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: ['KR-Central-1', 'KR-Central-2'], documentationUrl: 'https://docs.kakaocloud.com/service/security-group', typicalMonthlyCostUsd: 0, supportedProtocols: ['TCP', 'UDP', 'ICMP'], haFeatures: ['Multi-zone replication', 'Stateful tracking'], securityCapabilities: ['Stateful L4 filtering', 'Ingress/egress control', 'VPC-level isolation'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },
];
