/**
 * KT Cloud Services
 *
 * 20+ services across IaaS/PaaS categories with Korean-first bilingual support.
 * ISMS-P certified, Korean enterprise focus.
 */

import type { CloudService } from '../types';
import { svcTrust } from '../types';

const t = svcTrust('kt');
const certs = ['ISMS-P', 'ISO 27001', 'ISO 27017', 'CSA STAR'];

export const KT_SERVICES: CloudService[] = [
  // ========== Compute ==========
  { id: 'CS-WEB-KT-001', provider: 'kt', componentType: 'web-server', serviceName: 'Server', serviceNameKo: '서버', status: 'active', features: ['Standard/High Memory/CPU types', 'Auto Scaling', 'Init Script', 'Monitoring'], featuresKo: ['Standard/High Memory/CPU 타입', '오토 스케일링', '초기화 스크립트', '모니터링'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'General-purpose compute instances', architectureRoleKo: '범용 컴퓨팅 인스턴스', recommendedFor: ['Web hosting', 'Application servers', 'Enterprise workloads', 'Development environments'], recommendedForKo: ['웹 호스팅', '애플리케이션 서버', '엔터프라이즈 워크로드', '개발 환경'], sla: '99.95%', deploymentModel: 'self-managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/computing-server', typicalMonthlyCostUsd: 25, supportedProtocols: ['HTTP/HTTPS', 'SSH', 'RDP', 'TCP/UDP'], haFeatures: ['Auto Scaling', 'Multi-zone', 'Monitoring'], securityCapabilities: ['Security Group', 'VPC isolation', 'Encryption'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },
  { id: 'CS-AIML-KT-001', provider: 'kt', componentType: 'gpu-server', serviceName: 'GPU Server', serviceNameKo: 'GPU 서버', status: 'active', features: ['NVIDIA GPU support', 'ML frameworks', 'High-speed networking', 'Flexible configurations'], featuresKo: ['NVIDIA GPU 지원', 'ML 프레임워크', '고속 네트워킹', '유연한 구성'], pricingTier: 'high', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'GPU-accelerated compute for AI/ML', architectureRoleKo: 'AI/ML을 위한 GPU 가속 컴퓨팅', recommendedFor: ['Deep learning', 'AI inference', 'Rendering', 'Scientific computing'], recommendedForKo: ['딥러닝', 'AI 추론', '렌더링', '과학 컴퓨팅'], sla: '99.95%', deploymentModel: 'self-managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/computing-gpu', typicalMonthlyCostUsd: 1500, supportedProtocols: ['SSH', 'HTTP/HTTPS', 'NCCL'], haFeatures: ['Multi-GPU', 'GPU monitoring'], securityCapabilities: ['VPC isolation', 'Security Group'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },
  { id: 'CS-APP-KT-001', provider: 'kt', componentType: 'app-server', serviceName: 'App Engine', serviceNameKo: '앱 엔진', status: 'active', features: ['PaaS platform', 'Auto-scaling', 'Multiple runtimes', 'Container support'], featuresKo: ['PaaS 플랫폼', '자동 확장', '다중 런타임', '컨테이너 지원'], pricingTier: 'low', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'PaaS application deployment', architectureRoleKo: 'PaaS 애플리케이션 배포', recommendedFor: ['Web application deployment', 'Rapid prototyping', 'Microservices', 'Container apps'], recommendedForKo: ['웹 애플리케이션 배포', '빠른 프로토타이핑', '마이크로서비스', '컨테이너 앱'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/computing-app-engine', typicalMonthlyCostUsd: 20, supportedProtocols: ['HTTP/HTTPS', 'TCP', 'WebSocket'], haFeatures: ['Auto-scaling', 'Rolling deployments'], securityCapabilities: ['VPC deployment', 'SSL/TLS'], operationalComplexity: 'simple', ecosystemMaturity: 'stable' },

  // ========== Kubernetes & Container ==========
  { id: 'CS-K8S-KT-001', provider: 'kt', componentType: 'kubernetes', serviceName: 'Kubernetes Service', serviceNameKo: 'Kubernetes 서비스', status: 'active', features: ['Managed Kubernetes', 'Auto-scaling', 'GPU node pools', 'Helm support'], featuresKo: ['관리형 Kubernetes', '오토 스케일링', 'GPU 노드풀', 'Helm 지원'], pricingTier: 'medium', trust: t, serviceCategory: 'Compute', serviceCategoryKo: '컴퓨팅', architectureRole: 'Container orchestration platform', architectureRoleKo: '컨테이너 오케스트레이션 플랫폼', recommendedFor: ['Container workloads', 'Microservices', 'CI/CD pipelines', 'AI/ML deployment'], recommendedForKo: ['컨테이너 워크로드', '마이크로서비스', 'CI/CD 파이프라인', 'AI/ML 배포'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/computing-kubernetes', typicalMonthlyCostUsd: 72, supportedProtocols: ['HTTP/HTTPS', 'gRPC', 'TCP/UDP', 'Kubernetes API'], haFeatures: ['Multi-zone control plane', 'Cluster Autoscaler'], securityCapabilities: ['VPC CNI', 'Network Policies', 'RBAC'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },

  // ========== Storage ==========
  { id: 'CS-OBJ-KT-001', provider: 'kt', componentType: 'object-storage', serviceName: 'Object Storage', serviceNameKo: '오브젝트 스토리지', status: 'active', features: ['S3-compatible API', 'Lifecycle management', 'Versioning', 'CDN integration'], featuresKo: ['S3 호환 API', '라이프사이클 관리', '버전 관리', 'CDN 통합'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Scalable object storage', architectureRoleKo: '확장 가능한 오브젝트 스토리지', recommendedFor: ['Data storage', 'Media hosting', 'Backup and archive', 'Static assets'], recommendedForKo: ['데이터 저장', '미디어 호스팅', '백업 및 아카이브', '정적 자산'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/storage-object-storage', typicalMonthlyCostUsd: 18, supportedProtocols: ['S3 API', 'HTTPS'], haFeatures: ['Multi-zone replication', 'Versioning', 'High durability'], securityCapabilities: ['Server-side encryption', 'Bucket policies'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },
  { id: 'CS-STOR-KT-001', provider: 'kt', componentType: 'storage', serviceName: 'Block Storage', serviceNameKo: '블록 스토리지', status: 'active', features: ['SSD/HDD volumes', 'Snapshots', 'Online resize', 'Encryption'], featuresKo: ['SSD/HDD 볼륨', '스냅샷', '온라인 크기 변경', '암호화'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Block storage for server instances', architectureRoleKo: '서버 인스턴스용 블록 스토리지', recommendedFor: ['Database storage', 'Boot volumes', 'Application data', 'High-performance storage'], recommendedForKo: ['데이터베이스 스토리지', '부트 볼륨', '애플리케이션 데이터', '고성능 스토리지'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/storage-block-storage', typicalMonthlyCostUsd: 25, supportedProtocols: ['NVMe', 'SCSI'], haFeatures: ['Snapshots', 'Replication', 'Online resize'], securityCapabilities: ['Encryption at rest', 'Access control'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },
  { id: 'CS-STOR-KT-002', provider: 'kt', componentType: 'san-nas', serviceName: 'NAS', serviceNameKo: 'NAS', status: 'active', features: ['Shared file storage', 'NFS/CIFS', 'Snapshot', 'Auto-scaling'], featuresKo: ['공유 파일 스토리지', 'NFS/CIFS', '스냅샷', '자동 확장'], pricingTier: 'medium', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Shared network-attached storage', architectureRoleKo: '공유 네트워크 연결 스토리지', recommendedFor: ['Shared file systems', 'Content management', 'Legacy applications', 'Multi-server access'], recommendedForKo: ['공유 파일 시스템', '콘텐츠 관리', '레거시 애플리케이션', '다중 서버 접근'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/storage-nas', typicalMonthlyCostUsd: 40, supportedProtocols: ['NFS', 'CIFS/SMB'], haFeatures: ['Auto-scaling', 'Snapshots'], securityCapabilities: ['Encryption at rest', 'ACL'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },
  { id: 'CS-BK-KT-001', provider: 'kt', componentType: 'backup', serviceName: 'Backup', serviceNameKo: '백업', status: 'active', features: ['Server backup', 'Scheduled backups', 'File-level restore', 'Cross-zone storage'], featuresKo: ['서버 백업', '스케줄 백업', '파일 수준 복원', '교차 존 스토리지'], pricingTier: 'low', trust: t, serviceCategory: 'Storage', serviceCategoryKo: '스토리지', architectureRole: 'Centralized backup service', architectureRoleKo: '중앙 집중식 백업 서비스', recommendedFor: ['Data protection', 'Compliance backups', 'Disaster recovery', 'File restore'], recommendedForKo: ['데이터 보호', '컴플라이언스 백업', '재해 복구', '파일 복원'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/storage-backup', typicalMonthlyCostUsd: 12, supportedProtocols: ['Agent-based', 'API'], haFeatures: ['Cross-zone storage', 'Scheduled backups'], securityCapabilities: ['Encryption', 'Access control'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },

  // ========== Database ==========
  { id: 'CS-DB-KT-001', provider: 'kt', componentType: 'db-server', serviceName: 'DBaaS for MySQL', serviceNameKo: 'DBaaS for MySQL', status: 'active', features: ['Managed MySQL', 'Auto backup', 'Read replicas', 'Automatic failover'], featuresKo: ['관리형 MySQL', '자동 백업', '읽기 복제본', '자동 페일오버'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed relational database', architectureRoleKo: '관리형 관계형 데이터베이스', recommendedFor: ['Web applications', 'OLTP workloads', 'E-commerce', 'SaaS backends'], recommendedForKo: ['웹 애플리케이션', 'OLTP 워크로드', '전자상거래', 'SaaS 백엔드'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/database-mysql', typicalMonthlyCostUsd: 140, supportedProtocols: ['MySQL', 'JDBC', 'ODBC'], haFeatures: ['Master-standby', 'Read replicas', 'Auto failover'], securityCapabilities: ['Encryption at rest', 'VPC isolation', 'SSL/TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },
  { id: 'CS-DB-KT-002', provider: 'kt', componentType: 'db-server', serviceName: 'DBaaS for PostgreSQL', serviceNameKo: 'DBaaS for PostgreSQL', status: 'active', features: ['Managed PostgreSQL', 'Auto backup', 'Point-in-time recovery', 'Read replicas'], featuresKo: ['관리형 PostgreSQL', '자동 백업', '시점 복구', '읽기 복제본'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed advanced relational database', architectureRoleKo: '관리형 고급 관계형 데이터베이스', recommendedFor: ['Complex queries', 'GIS applications', 'Analytics', 'Enterprise systems'], recommendedForKo: ['복잡한 쿼리', 'GIS 애플리케이션', '분석', '엔터프라이즈 시스템'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/database-postgresql', typicalMonthlyCostUsd: 150, supportedProtocols: ['PostgreSQL', 'JDBC', 'ODBC'], haFeatures: ['Streaming replication', 'Auto failover', 'Read replicas'], securityCapabilities: ['Encryption at rest', 'VPC isolation', 'SSL/TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-DB-KT-003', provider: 'kt', componentType: 'db-server', serviceName: 'DBaaS for MariaDB', serviceNameKo: 'DBaaS for MariaDB', status: 'active', features: ['Managed MariaDB', 'Auto backup', 'Galera Cluster', 'Automatic failover'], featuresKo: ['관리형 MariaDB', '자동 백업', 'Galera 클러스터', '자동 페일오버'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'Managed MariaDB relational database', architectureRoleKo: '관리형 MariaDB 관계형 데이터베이스', recommendedFor: ['MySQL-compatible workloads', 'Open-source preference', 'Web applications', 'Content management'], recommendedForKo: ['MySQL 호환 워크로드', '오픈소스 선호', '웹 애플리케이션', '콘텐츠 관리'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/database-mariadb', typicalMonthlyCostUsd: 130, supportedProtocols: ['MySQL/MariaDB', 'JDBC', 'ODBC'], haFeatures: ['Galera Cluster', 'Auto failover', 'Auto backup'], securityCapabilities: ['Encryption at rest', 'VPC isolation', 'SSL/TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-CACHE-KT-001', provider: 'kt', componentType: 'cache', serviceName: 'DBaaS for Redis', serviceNameKo: 'DBaaS for Redis', status: 'active', features: ['Managed Redis', 'Cluster mode', 'Auto failover', 'Persistence'], featuresKo: ['관리형 Redis', '클러스터 모드', '자동 페일오버', '영속성'], pricingTier: 'medium', trust: t, serviceCategory: 'Database', serviceCategoryKo: '데이터베이스', architectureRole: 'In-memory caching and session store', architectureRoleKo: '인메모리 캐싱 및 세션 저장소', recommendedFor: ['Session caching', 'Query caching', 'Real-time data', 'Rate limiting'], recommendedForKo: ['세션 캐싱', '쿼리 캐싱', '실시간 데이터', '속도 제한'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/database-redis', typicalMonthlyCostUsd: 90, supportedProtocols: ['Redis', 'TLS'], haFeatures: ['Cluster mode', 'Auto failover'], securityCapabilities: ['VPC isolation', 'AUTH', 'TLS'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },

  // ========== Networking ==========
  { id: 'CS-LB-KT-001', provider: 'kt', componentType: 'load-balancer', serviceName: 'Load Balancer', serviceNameKo: '로드 밸런서', status: 'active', features: ['L4/L7 load balancing', 'Health checks', 'SSL offloading', 'Sticky sessions'], featuresKo: ['L4/L7 로드 밸런싱', '헬스 체크', 'SSL 오프로딩', '스티키 세션'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Traffic distribution layer', architectureRoleKo: '트래픽 분산 계층', recommendedFor: ['High availability', 'Web application scaling', 'SSL termination', 'Multi-server distribution'], recommendedForKo: ['고가용성', '웹 애플리케이션 확장', 'SSL 종료', '다중 서버 분산'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/networking-load-balancer', typicalMonthlyCostUsd: 25, supportedProtocols: ['HTTP', 'HTTPS', 'TCP', 'UDP'], haFeatures: ['Multi-zone', 'Health monitoring', 'Auto-healing'], securityCapabilities: ['SSL/TLS termination', 'Security Group', 'DDoS protection'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },
  { id: 'CS-VPC-KT-001', provider: 'kt', componentType: 'aws-vpc', serviceName: 'VPC', serviceNameKo: 'VPC', status: 'active', features: ['Subnets', 'Route tables', 'NAT Gateway', 'VPC Peering'], featuresKo: ['서브넷', '라우팅 테이블', 'NAT 게이트웨이', 'VPC 피어링'], pricingTier: 'free', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Virtual network isolation', architectureRoleKo: '가상 네트워크 격리', recommendedFor: ['Network isolation', 'Multi-tier architectures', 'Security segmentation', 'Hybrid connectivity'], recommendedForKo: ['네트워크 격리', '다중 티어 아키텍처', '보안 세그멘테이션', '하이브리드 연결'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/networking-vpc', typicalMonthlyCostUsd: 0, supportedProtocols: ['TCP/UDP', 'ICMP', 'IPv4'], haFeatures: ['Multi-zone subnets', 'VPC Peering', 'NAT Gateway'], securityCapabilities: ['Network ACL', 'Security Groups'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },
  { id: 'CS-CDN-KT-001', provider: 'kt', componentType: 'cdn', serviceName: 'CDN', serviceNameKo: 'CDN', status: 'active', features: ['Korea-optimized PoPs', 'KT backbone integration', 'SSL/TLS', 'Real-time purge'], featuresKo: ['한국 최적화 PoP', 'KT 백본 통합', 'SSL/TLS', '실시간 퍼지'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Content delivery leveraging KT backbone', architectureRoleKo: 'KT 백본을 활용한 콘텐츠 전송', recommendedFor: ['Korean content delivery', 'Video streaming', 'Web acceleration', 'Large file distribution'], recommendedForKo: ['한국 콘텐츠 전송', '비디오 스트리밍', '웹 가속', '대용량 파일 배포'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://cloud.kt.com/portal/user-guide/networking-cdn', typicalMonthlyCostUsd: 20, supportedProtocols: ['HTTP/1.1', 'HTTP/2', 'HTTPS'], haFeatures: ['KT backbone PoPs', 'Origin failover', 'Real-time purge'], securityCapabilities: ['SSL/TLS', 'Access control', 'Token auth'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },
  { id: 'CS-VPN-KT-001', provider: 'kt', componentType: 'vpn-gateway', serviceName: 'VPN', serviceNameKo: 'VPN', status: 'active', features: ['IPsec VPN', 'Site-to-site', 'SSL VPN', 'KT network integration'], featuresKo: ['IPsec VPN', '사이트간', 'SSL VPN', 'KT 네트워크 통합'], pricingTier: 'low', trust: t, serviceCategory: 'Networking', serviceCategoryKo: '네트워킹', architectureRole: 'Hybrid cloud encrypted connectivity', architectureRoleKo: '하이브리드 클라우드 암호화 연결', recommendedFor: ['On-premise connectivity', 'Branch office connections', 'Remote access', 'Hybrid networking'], recommendedForKo: ['온프레미스 연결', '지점 연결', '원격 접속', '하이브리드 네트워킹'], sla: '99.95%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/networking-vpn', typicalMonthlyCostUsd: 25, supportedProtocols: ['IPsec', 'SSL/TLS', 'IKEv2'], haFeatures: ['Dual tunnels', 'Auto-reconnect'], securityCapabilities: ['AES-256 encryption', 'MFA support', 'Certificate auth'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },

  // ========== Security ==========
  { id: 'CS-FW-KT-001', provider: 'kt', componentType: 'firewall', serviceName: 'Firewall', serviceNameKo: '방화벽', status: 'active', features: ['Stateful inspection', 'L3/L4 filtering', 'IPS integration', 'Logging'], featuresKo: ['상태 기반 검사', 'L3/L4 필터링', 'IPS 통합', '로깅'], pricingTier: 'medium', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Network perimeter protection', architectureRoleKo: '네트워크 경계 보호', recommendedFor: ['VPC security', 'Network segmentation', 'Compliance environments', 'Traffic inspection'], recommendedForKo: ['VPC 보안', '네트워크 세그멘테이션', '컴플라이언스 환경', '트래픽 검사'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/security-firewall', typicalMonthlyCostUsd: 180, supportedProtocols: ['TCP/UDP', 'HTTP/HTTPS', 'ICMP'], haFeatures: ['Multi-zone', 'Auto failover'], securityCapabilities: ['Stateful inspection', 'IPS', 'DDoS protection', 'Logging'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-WAF-KT-001', provider: 'kt', componentType: 'waf', serviceName: 'WAF', serviceNameKo: 'WAF', status: 'active', features: ['OWASP Top 10', 'Bot protection', 'Rate limiting', 'Custom rules'], featuresKo: ['OWASP Top 10', '봇 보호', '속도 제한', '커스텀 규칙'], pricingTier: 'medium', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Web application protection', architectureRoleKo: '웹 애플리케이션 보호', recommendedFor: ['Web application security', 'API protection', 'Bot mitigation', 'Compliance'], recommendedForKo: ['웹 애플리케이션 보안', 'API 보호', '봇 차단', '컴플라이언스'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/security-waf', typicalMonthlyCostUsd: 120, supportedProtocols: ['HTTP/HTTPS'], haFeatures: ['Multi-zone', 'Auto-scaling'], securityCapabilities: ['OWASP Top 10', 'SQL injection', 'XSS prevention', 'Bot detection'], operationalComplexity: 'moderate', ecosystemMaturity: 'stable' },
  { id: 'CS-IAM-KT-001', provider: 'kt', componentType: 'iam', serviceName: 'IAM', serviceNameKo: 'IAM', status: 'active', features: ['Role-based access', 'Policy management', 'MFA', 'API access keys'], featuresKo: ['역할 기반 접근', '정책 관리', 'MFA', 'API 접근 키'], pricingTier: 'free', trust: t, serviceCategory: 'Security', serviceCategoryKo: '보안', architectureRole: 'Identity and access management', architectureRoleKo: 'ID 및 접근 관리', recommendedFor: ['Access control', 'Role management', 'Compliance auditing', 'API security'], recommendedForKo: ['접근 제어', '역할 관리', '컴플라이언스 감사', 'API 보안'], sla: '99.99%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: 'global', documentationUrl: 'https://cloud.kt.com/portal/user-guide/security-iam', typicalMonthlyCostUsd: 0, supportedProtocols: ['HTTPS', 'API'], haFeatures: ['Global availability'], securityCapabilities: ['RBAC', 'MFA', 'Policy-based', 'Access key rotation'], operationalComplexity: 'moderate', ecosystemMaturity: 'mature' },

  // ========== Monitoring ==========
  { id: 'CS-MON-KT-001', provider: 'kt', componentType: 'prometheus', serviceName: 'Monitoring', serviceNameKo: '모니터링', status: 'active', features: ['Resource monitoring', 'Custom metrics', 'Alerting', 'Dashboards'], featuresKo: ['리소스 모니터링', '커스텀 메트릭', '알림', '대시보드'], pricingTier: 'free', trust: t, serviceCategory: 'Monitoring', serviceCategoryKo: '모니터링', architectureRole: 'Cloud observability platform', architectureRoleKo: '클라우드 관측 플랫폼', recommendedFor: ['Infrastructure monitoring', 'Application performance', 'Alerting', 'Cost optimization'], recommendedForKo: ['인프라 모니터링', '애플리케이션 성능', '알림', '비용 최적화'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'free-tier', complianceCertifications: certs, regions: ['KR-Seoul', 'KR-Central'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/management-monitoring', typicalMonthlyCostUsd: 0, supportedProtocols: ['HTTP/HTTPS', 'Agent-based'], haFeatures: ['Built-in redundancy', 'Multi-zone'], securityCapabilities: ['Access control', 'Audit logging'], operationalComplexity: 'simple', ecosystemMaturity: 'mature' },

  // ========== AI ==========
  { id: 'CS-AIML-KT-002', provider: 'kt', componentType: 'inference-engine', serviceName: 'AI Platform', serviceNameKo: 'AI 플랫폼', status: 'active', features: ['ML pipeline', 'Model serving', 'AutoML', 'Korean NLP'], featuresKo: ['ML 파이프라인', '모델 서빙', 'AutoML', '한국어 NLP'], pricingTier: 'high', trust: t, serviceCategory: 'AI Service', serviceCategoryKo: 'AI 서비스', architectureRole: 'End-to-end AI/ML platform', architectureRoleKo: '엔드투엔드 AI/ML 플랫폼', recommendedFor: ['ML model development', 'AI applications', 'Korean NLP', 'Enterprise AI'], recommendedForKo: ['ML 모델 개발', 'AI 애플리케이션', '한국어 NLP', '엔터프라이즈 AI'], sla: '99.9%', deploymentModel: 'managed', pricingModel: 'pay-as-you-go', complianceCertifications: certs, regions: ['KR-Seoul'], documentationUrl: 'https://cloud.kt.com/portal/user-guide/ai-platform', typicalMonthlyCostUsd: 400, supportedProtocols: ['REST API', 'gRPC', 'HTTPS'], haFeatures: ['Auto-scaling', 'Multi-GPU'], securityCapabilities: ['VPC isolation', 'API auth', 'Data encryption'], operationalComplexity: 'complex', ecosystemMaturity: 'stable' },
];
