/**
 * Kubernetes Export Module
 *
 * This module converts InfraFlow infrastructure specifications to Kubernetes YAML manifests.
 * It generates production-ready Kubernetes resources including Deployments, Services,
 * StatefulSets, NetworkPolicies, and Ingress configurations.
 *
 * @module lib/export/kubernetes
 *
 * @example
 * import { exportToKubernetes } from '@/lib/export/kubernetes';
 *
 * const yaml = exportToKubernetes(infraSpec, {
 *   namespace: 'production',
 *   includeIngress: true,
 *   includeNetworkPolicy: true,
 *   replicaCount: 3
 * });
 *
 * console.log(yaml);
 * // Outputs Kubernetes YAML manifests
 */

import { InfraSpec, InfraNodeSpec, InfraNodeType } from '@/types';
import { generateNamespace, generateIngress, generateDefaultNetworkPolicy } from './helpers';
import { securityResourceMap } from './securityResources';
import { networkResourceMap } from './networkResources';
import { computeResourceMap } from './computeResources';
import { storageAndMiscResourceMap } from './storageResources';
import { aiResourceMap } from './aiResources';

// Re-export types
export type { KubernetesExportOptions } from './types';

// Re-export for advanced usage
export { sanitizeK8sName, generateDeployment, generateNamespace, generateIngress, generateDefaultNetworkPolicy } from './helpers';

// Import type for internal use
import type { KubernetesExportOptions } from './types';

/**
 * Combined resource map from all sub-modules.
 *
 * Merges security, network, compute, storage/misc, and AI resource generators
 * into a single lookup map keyed by InfraNodeType.
 */
const kubernetesResourceMap: Record<InfraNodeType, (node: InfraNodeSpec, options: KubernetesExportOptions) => string> = {
  ...securityResourceMap,
  ...networkResourceMap,
  ...computeResourceMap,
  ...storageAndMiscResourceMap,
  ...aiResourceMap,
} as Record<InfraNodeType, (node: InfraNodeSpec, options: KubernetesExportOptions) => string>;

/**
 * Exports an InfraSpec to Kubernetes YAML format.
 *
 * Converts an infrastructure specification into complete Kubernetes manifests
 * including namespace, network policies, deployments, services, and ingress.
 *
 * @param {InfraSpec} spec - The infrastructure specification to export
 * @param {KubernetesExportOptions} [options={}] - Export configuration options
 * @returns {string} Complete Kubernetes YAML manifests
 *
 * @example
 * const yaml = exportToKubernetes(spec, {
 *   namespace: 'production',
 *   includeIngress: true,
 *   includeNetworkPolicy: true,
 *   replicaCount: 3
 * });
 *
 * // Apply with kubectl
 * // kubectl apply -f manifests.yaml
 */
export function exportToKubernetes(
  spec: InfraSpec,
  options: KubernetesExportOptions = {}
): string {
  const {
    namespace = 'default',
    includeNamespace = true,
    includeIngress = true,
    includeNetworkPolicy = true,
  } = options;

  const sections: string[] = [];

  // Header comment
  sections.push(`# Kubernetes manifests generated by InfraFlow
# Namespace: ${namespace}
# Generated: ${new Date().toISOString()}
`);

  // Namespace
  if (includeNamespace && namespace !== 'default') {
    sections.push(generateNamespace(namespace));
  }

  // Network policies
  if (includeNetworkPolicy) {
    sections.push(generateDefaultNetworkPolicy(options));
  }

  // Resources
  sections.push('\n# ============= Application Resources =============\n');

  for (const node of spec.nodes) {
    const resourceGenerator = kubernetesResourceMap[node.type];
    if (resourceGenerator) {
      const resource = resourceGenerator(node, options);
      if (resource && !resource.startsWith('#')) {
        sections.push(resource);
      } else if (resource) {
        sections.push(`\n${resource}`);
      }
    } else {
      sections.push(`\n# Unknown node type: ${node.type} - ${node.label}`);
    }
  }

  // Ingress
  if (includeIngress) {
    const ingress = generateIngress(spec, options);
    if (ingress) {
      sections.push('\n# ============= Ingress =============');
      sections.push(ingress);
    }
  }

  return sections.join('\n');
}
