/**
 * Arista Networks — Product Catalog
 *
 * Hierarchical product tree covering Data Center Switching, Campus & Edge,
 * Routing, Network Observability, Network Management, and Security categories.
 *
 * Data sourced from https://www.arista.com/en/products
 * Last crawled: 2026-02-20
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Arista Networks Product Catalog
// ---------------------------------------------------------------------------

export const aristaCatalog: VendorCatalog = {
  vendorId: 'arista',
  vendorName: 'Arista Networks',
  vendorNameKo: '아리스타 네트웍스',
  headquarters: 'Santa Clara, CA, USA',
  website: 'https://www.arista.com',
  productPageUrl: 'https://www.arista.com/en/products',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-20',
  crawlSource: 'https://www.arista.com/en/products',
  stats: { totalProducts: 50, maxDepth: 2, categoriesCount: 6 },
  products: [
    // =========================================================================
    // 1. Data Center Switching
    // =========================================================================
    {
      nodeId: 'arista-dc-switching',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Data Center Switching',
      nameKo: '데이터센터 스위칭',
      description: 'High-performance fixed and modular switches for data center spine, leaf, and core roles with EOS (Extensible Operating System)',
      descriptionKo: 'EOS(확장형 운영체제) 기반 데이터센터 스파인, 리프, 코어 역할을 위한 고성능 고정형 및 모듈형 스위치',
      sourceUrl: 'https://www.arista.com/en/products/switches',
      infraNodeTypes: ['switch-l2', 'switch-l3'],
      children: [
        // -- 7500R3 Series --
        {
          nodeId: 'arista-7500r3',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7500R3 Series (Spine/Core)',
          nameKo: '7500R3 시리즈 (스파인/코어)',
          description: 'Modular spine and core platform with up to 576 ports of 100GbE or 144 ports of 400GbE. Powered by Jericho2 ASICs, designed for large-scale IP fabrics and cloud data centers.',
          descriptionKo: '최대 100GbE 576포트 또는 400GbE 144포트 지원 모듈형 스파인 및 코어 플랫폼. Jericho2 ASIC 기반, 대규모 IP 패브릭 및 클라우드 데이터센터 설계.',
          sourceUrl: 'https://www.arista.com/en/products/7500r3-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7500R3-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Data Center Spine / Core',
          architectureRoleKo: '데이터센터 스파인 / 코어',
          recommendedFor: [
            'Large-scale cloud data center spine',
            'Campus or DC core aggregation (400G uplinks)',
            'High-radix IP fabric with VXLAN/EVPN',
            'Internet peering / edge routing at scale',
          ],
          recommendedForKo: [
            '대규모 클라우드 데이터센터 스파인',
            '캠퍼스 또는 DC 코어 집선 (400G 업링크)',
            'VXLAN/EVPN 기반 고밀도 IP 패브릭',
            '대규모 인터넷 피어링 / 에지 라우팅',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'MPLS', 'PIM', 'IGMP', 'BFD',
          ],
          haFeatures: [
            'Hitless supervisor failover',
            'ISSU (In-Service Software Upgrade)',
            'GIR (Graceful Insertion and Removal)',
            'Dual supervisor redundancy',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'Control plane policing (CoPP)',
            'ACL (L2/L3/L4)',
            'FIPS 140-2 compliance',
          ],
          specs: {
            'Max Switching Capacity': '57.6 Tbps',
            'Max 100GbE Ports': '576',
            'Max 400GbE Ports': '144',
            'ASIC': 'Memory: DeepBuffer; Forwarding: Memory-based',
            'MAC Addresses': '1,024K',
            'IPv4 Routes': '1,024K',
            'IPv6 Routes': '512K',
            'Power Redundancy': 'N+1 / N+N',
          },
          children: [
            {
              nodeId: 'arista-7500r3-36cq',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7500R3-36CQ',
              nameKo: '7500R3-36CQ',
              description: '36-port 100GbE QSFP28 line card for 7500R3 chassis, 7.2 Tbps throughput',
              descriptionKo: '7500R3 섀시용 36포트 100GbE QSFP28 라인 카드, 7.2 Tbps 처리량',
              sourceUrl: 'https://www.arista.com/en/products/7500r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '36x 100GbE QSFP28',
                'Throughput': '7.2 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7500r3-48yc6',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7500R3-48YC6',
              nameKo: '7500R3-48YC6',
              description: '48-port 25GbE SFP28 + 6-port 100GbE QSFP28 line card for 7500R3 chassis',
              descriptionKo: '7500R3 섀시용 48포트 25GbE SFP28 + 6포트 100GbE QSFP28 라인 카드',
              sourceUrl: 'https://www.arista.com/en/products/7500r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 25GbE SFP28 + 6x 100GbE QSFP28',
                'Throughput': '2.4 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7500r3k-36cq',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7500R3K-36CQ',
              nameKo: '7500R3K-36CQ',
              description: 'Deep-buffer variant of 7500R3-36CQ with extended packet buffering for bursty workloads',
              descriptionKo: '버스트 워크로드를 위한 확장 패킷 버퍼링이 적용된 7500R3-36CQ 딥버퍼 변형',
              sourceUrl: 'https://www.arista.com/en/products/7500r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '36x 100GbE QSFP28',
                'Throughput': '7.2 Tbps',
                'Buffer': 'Deep buffer variant',
              },
              children: [],
            },
          ],
        },
        // -- 7800R3 Series --
        {
          nodeId: 'arista-7800r3',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7800R3 Series (High-Density Core)',
          nameKo: '7800R3 시리즈 (고밀도 코어)',
          description: 'High-density modular platform for 400GbE data center core and AI/ML network fabrics with up to 460.8 Tbps system capacity.',
          descriptionKo: '최대 460.8 Tbps 시스템 용량의 400GbE 데이터센터 코어 및 AI/ML 네트워크 패브릭용 고밀도 모듈형 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/7800r3-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7800R3-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Data Center Core / AI Fabric Spine',
          architectureRoleKo: '데이터센터 코어 / AI 패브릭 스파인',
          recommendedFor: [
            'Hyperscale and cloud provider core switches',
            'AI/ML GPU cluster network fabric spine',
            '400GbE high-density spine layer',
            'Multi-tier data center interconnect',
          ],
          recommendedForKo: [
            '하이퍼스케일 및 클라우드 프로바이더 코어 스위치',
            'AI/ML GPU 클러스터 네트워크 패브릭 스파인',
            '400GbE 고밀도 스파인 레이어',
            '다중 티어 데이터센터 인터커넥트',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'MPLS', 'PIM', 'RoCEv2',
          ],
          haFeatures: [
            'Hitless supervisor failover',
            'ISSU (In-Service Software Upgrade)',
            'Dual supervisor redundancy',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'Control plane policing (CoPP)',
            'ACL (L2/L3/L4)',
          ],
          specs: {
            'Max System Capacity': '460.8 Tbps',
            'Max 400GbE Ports': '576',
            'ASIC': 'Memory-based with deep buffers',
            'Operating Temp': '0°C to 40°C',
            'Power Redundancy': 'N+1 / N+N',
          },
          children: [
            {
              nodeId: 'arista-7800r3-48cq2',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7800R3-48CQ2',
              nameKo: '7800R3-48CQ2',
              description: '48-port 400GbE QSFP-DD line card for 7800R3 chassis',
              descriptionKo: '7800R3 섀시용 48포트 400GbE QSFP-DD 라인 카드',
              sourceUrl: 'https://www.arista.com/en/products/7800r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 400GbE QSFP-DD',
                'Throughput': '19.2 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7800r3-36p',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7800R3-36P',
              nameKo: '7800R3-36P',
              description: '36-port 400GbE line card with programmable packet processing for 7800R3 chassis',
              descriptionKo: '7800R3 섀시용 프로그래머블 패킷 처리 지원 36포트 400GbE 라인 카드',
              sourceUrl: 'https://www.arista.com/en/products/7800r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '36x 400GbE',
                'Throughput': '14.4 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7800r3-48yc',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7800R3-48YC',
              nameKo: '7800R3-48YC',
              description: '48-port 25GbE SFP28 line card for 7800R3 chassis with 100GbE QSFP28 uplinks',
              descriptionKo: '7800R3 섀시용 100GbE QSFP28 업링크 탑재 48포트 25GbE SFP28 라인 카드',
              sourceUrl: 'https://www.arista.com/en/products/7800r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 25GbE SFP28 + 8x 100GbE QSFP28',
                'Throughput': '4.0 Tbps',
              },
              children: [],
            },
          ],
        },
        // -- 7280R3 Series --
        {
          nodeId: 'arista-7280r3',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7280R3 Series (Leaf/Spine)',
          nameKo: '7280R3 시리즈 (리프/스파인)',
          description: 'Fixed-configuration leaf and spine switches with deep buffer architecture for 10G/25G/100G data center deployments.',
          descriptionKo: '10G/25G/100G 데이터센터 배포를 위한 딥버퍼 아키텍처 기반 고정형 리프 및 스파인 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/7280r3-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7280R3-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Data Center Leaf / Spine',
          architectureRoleKo: '데이터센터 리프 / 스파인',
          recommendedFor: [
            'Data center leaf or spine (VXLAN/EVPN fabric)',
            'Border leaf for DCI (Data Center Interconnect)',
            'Storage network front-end (RoCEv2 / iSCSI)',
            'Network services leaf (firewall, load balancer integration)',
          ],
          recommendedForKo: [
            '데이터센터 리프 또는 스파인 (VXLAN/EVPN 패브릭)',
            'DCI(데이터센터 인터커넥트) 보더 리프',
            '스토리지 네트워크 프론트엔드 (RoCEv2 / iSCSI)',
            '네트워크 서비스 리프 (방화벽, 로드밸런서 연동)',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'MPLS', 'PIM', 'RoCEv2', 'iSCSI',
          ],
          haFeatures: [
            'GIR (Graceful Insertion and Removal)',
            'MLAG (Multi-Chassis Link Aggregation)',
            'BFD (Bidirectional Forwarding Detection)',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'ACL (L2/L3/L4)',
            'DHCP snooping',
            'Dynamic ARP inspection',
          ],
          specs: {
            'Switching Capacity': 'Up to 12.8 Tbps',
            'Latency': '< 4 microseconds',
            'Buffer': 'Deep buffer (up to 32 GB)',
            'MAC Addresses': '256K',
            'IPv4 Routes': '512K',
          },
          children: [
            {
              nodeId: 'arista-7280r3-48yc6',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7280R3-48YC6',
              nameKo: '7280R3-48YC6',
              description: '48-port 25GbE SFP28 + 6-port 100GbE QSFP28 fixed switch with deep buffers',
              descriptionKo: '딥버퍼 탑재 48포트 25GbE SFP28 + 6포트 100GbE QSFP28 고정형 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7280r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 25GbE SFP28 + 6x 100GbE QSFP28',
                'Switching Capacity': '3.6 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7280r3-32c',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7280R3-32C',
              nameKo: '7280R3-32C',
              description: '32-port 100GbE QSFP28 fixed switch for spine or border leaf roles',
              descriptionKo: '스파인 또는 보더 리프 역할을 위한 32포트 100GbE QSFP28 고정형 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7280r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '32x 100GbE QSFP28',
                'Switching Capacity': '6.4 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7280r3-96s',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7280R3-96S',
              nameKo: '7280R3-96S',
              description: '96-port 10GbE SFP+ fixed switch for high-density server connectivity',
              descriptionKo: '고밀도 서버 연결을 위한 96포트 10GbE SFP+ 고정형 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7280r3-series',
              lifecycle: 'active',
              specs: {
                'Ports': '96x 10GbE SFP+',
                'Switching Capacity': '1.92 Tbps',
              },
              children: [],
            },
          ],
        },
        // -- 7060X Series --
        {
          nodeId: 'arista-7060x',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7060X Series (25/100G Leaf)',
          nameKo: '7060X 시리즈 (25/100G 리프)',
          description: 'Wire-speed 25G/100G fixed-configuration leaf switches optimized for low-latency data center ToR (Top-of-Rack) deployments.',
          descriptionKo: '저지연 데이터센터 ToR(Top-of-Rack) 배포에 최적화된 와이어 스피드 25G/100G 고정형 리프 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/7060x-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7060X-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Data Center Leaf (ToR)',
          architectureRoleKo: '데이터센터 리프 (ToR)',
          recommendedFor: [
            'Top-of-Rack leaf switch for server connectivity',
            'Spine in small/medium leaf-spine fabrics',
            'Low-latency workloads (HPC, financial trading)',
          ],
          recommendedForKo: [
            '서버 연결용 Top-of-Rack 리프 스위치',
            '중소규모 리프-스파인 패브릭 스파인',
            '저지연 워크로드 (HPC, 금융 트레이딩)',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'PIM',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
            'BFD (Bidirectional Forwarding Detection)',
            'GIR (Graceful Insertion and Removal)',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'ACL (L2/L3/L4)',
            'Storm control',
          ],
          specs: {
            'Switching Capacity': 'Up to 12.8 Tbps',
            'Latency': '< 1 microsecond (cut-through)',
            'MAC Addresses': '136K',
            'IPv4 Routes': '256K',
          },
          children: [
            {
              nodeId: 'arista-7060x5-64',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7060X5-64',
              nameKo: '7060X5-64',
              description: '64-port 400GbE QSFP-DD switch for next-gen spine and leaf deployments',
              descriptionKo: '차세대 스파인 및 리프 배포를 위한 64포트 400GbE QSFP-DD 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7060x-series',
              lifecycle: 'active',
              specs: {
                'Ports': '64x 400GbE QSFP-DD',
                'Switching Capacity': '12.8 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7060x4-32',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7060X4-32',
              nameKo: '7060X4-32',
              description: '32-port 100GbE QSFP28 wire-speed leaf switch with ultra-low latency',
              descriptionKo: '초저지연 와이어 스피드 32포트 100GbE QSFP28 리프 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7060x-series',
              lifecycle: 'active',
              specs: {
                'Ports': '32x 100GbE QSFP28',
                'Switching Capacity': '6.4 Tbps',
                'Latency': '< 500 ns',
              },
              children: [],
            },
            {
              nodeId: 'arista-7060x2-48',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7060X2-48',
              nameKo: '7060X2-48',
              description: '48-port 10GbE SFP+ + 4-port 100GbE QSFP28 leaf switch for legacy server migrations',
              descriptionKo: '레거시 서버 마이그레이션을 위한 48포트 10GbE SFP+ + 4포트 100GbE QSFP28 리프 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7060x-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 10GbE SFP+ + 4x 100GbE QSFP28',
                'Switching Capacity': '1.76 Tbps',
              },
              children: [],
            },
          ],
        },
        // -- 7050X Series --
        {
          nodeId: 'arista-7050x',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7050X Series (10/25/40G)',
          nameKo: '7050X 시리즈 (10/25/40G)',
          description: 'Cost-effective L2/L3 leaf switches for 10G/25G/40G data center access with wire-speed performance and low latency.',
          descriptionKo: '와이어 스피드 성능과 저지연을 갖춘 10G/25G/40G 데이터센터 액세스용 비용 효율적 L2/L3 리프 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/7050x-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7050X-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l2', 'switch-l3'],
          architectureRole: 'Data Center Access / Leaf',
          architectureRoleKo: '데이터센터 액세스 / 리프',
          recommendedFor: [
            'Standard data center ToR deployments',
            'Server farm access switching (10G/25G)',
            'Migration from legacy 1G/10G to 25G infrastructure',
          ],
          recommendedForKo: [
            '표준 데이터센터 ToR 배포',
            '서버 팜 액세스 스위칭 (10G/25G)',
            '레거시 1G/10G에서 25G 인프라로의 마이그레이션',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'VXLAN', 'EVPN', 'LACP', 'STP', 'PIM',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
            'BFD (Bidirectional Forwarding Detection)',
          ],
          securityCapabilities: [
            'ACL (L2/L3/L4)',
            'DHCP snooping',
            'Dynamic ARP inspection',
            'Port security',
          ],
          specs: {
            'Switching Capacity': 'Up to 3.2 Tbps',
            'Latency': '< 1 microsecond',
            'MAC Addresses': '96K',
            'IPv4 Routes': '128K',
          },
          children: [
            {
              nodeId: 'arista-7050x4-32s',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7050X4-32S',
              nameKo: '7050X4-32S',
              description: '32-port 25GbE SFP28 switch with 100GbE uplinks for server access',
              descriptionKo: '서버 액세스용 100GbE 업링크 탑재 32포트 25GbE SFP28 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7050x-series',
              lifecycle: 'active',
              specs: {
                'Ports': '32x 25GbE SFP28 + uplinks',
                'Switching Capacity': '1.6 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-7050x3-48yc12',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7050X3-48YC12',
              nameKo: '7050X3-48YC12',
              description: '48-port 25GbE SFP28 + 12-port 100GbE QSFP28 switch for high-density leaf',
              descriptionKo: '고밀도 리프용 48포트 25GbE SFP28 + 12포트 100GbE QSFP28 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7050x-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 25GbE SFP28 + 12x 100GbE QSFP28',
                'Switching Capacity': '3.2 Tbps',
              },
              children: [],
            },
          ],
        },
        // -- 7020R Series --
        {
          nodeId: 'arista-7020r',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7020R Series (Entry DC)',
          nameKo: '7020R 시리즈 (엔트리 DC)',
          description: 'Entry-level 1GbE/10GbE data center switches with full EOS feature set, ideal for small data centers and edge deployments.',
          descriptionKo: '소규모 데이터센터 및 에지 배포에 적합한 풀 EOS 기능 세트를 갖춘 엔트리급 1GbE/10GbE 데이터센터 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/7020r-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7020R-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l2'],
          architectureRole: 'Entry Data Center Access',
          architectureRoleKo: '엔트리 데이터센터 액세스',
          recommendedFor: [
            'Small data center or lab environments',
            'Edge site connectivity with consistent EOS management',
            'Out-of-band management network switching',
          ],
          recommendedForKo: [
            '소규모 데이터센터 또는 랩 환경',
            '일관된 EOS 관리가 가능한 에지 사이트 연결',
            '아웃오브밴드 관리 네트워크 스위칭',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'VXLAN', 'LACP', 'STP',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
          ],
          securityCapabilities: [
            'ACL (L2/L3)',
            'DHCP snooping',
            'Port security',
          ],
          specs: {
            'Ports': '32x 1GbE RJ45 + 10GbE uplinks',
            'Switching Capacity': '128 Gbps',
            'Latency': '< 1 microsecond',
          },
          children: [
            {
              nodeId: 'arista-7020r-32tm',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7020R-32TM',
              nameKo: '7020R-32TM',
              description: '32-port 1GbE RJ45 + 10GbE SFP+ uplinks entry data center switch',
              descriptionKo: '32포트 1GbE RJ45 + 10GbE SFP+ 업링크 엔트리 데이터센터 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7020r-series',
              lifecycle: 'active',
              specs: {
                'Ports': '32x 1GbE RJ45 + 2x 10GbE SFP+',
                'Switching Capacity': '128 Gbps',
              },
              children: [],
            },
          ],
        },
        // -- 7130 Series --
        {
          nodeId: 'arista-7130',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7130 Series (Ultra-Low Latency)',
          nameKo: '7130 시리즈 (초저지연)',
          description: 'FPGA-based ultra-low latency switches designed for financial trading, HPC, and specialized network applications requiring sub-microsecond latency.',
          descriptionKo: '서브 마이크로초 지연이 필요한 금융 트레이딩, HPC 및 특수 네트워크 애플리케이션을 위한 FPGA 기반 초저지연 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/7130-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/7130-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Ultra-Low Latency Trading / HPC',
          architectureRoleKo: '초저지연 트레이딩 / HPC',
          recommendedFor: [
            'Financial trading (matching engine connectivity)',
            'High-frequency trading (HFT) networks',
            'Ultra-low latency HPC interconnect',
            'Custom FPGA application hosting',
          ],
          recommendedForKo: [
            '금융 트레이딩 (매칭 엔진 연결)',
            '고빈도 트레이딩(HFT) 네트워크',
            '초저지연 HPC 인터커넥트',
            '커스텀 FPGA 애플리케이션 호스팅',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'PTP (IEEE 1588)', 'Multicast',
          ],
          haFeatures: [
            'Dual power supply',
            'Hot-swappable fan trays',
          ],
          securityCapabilities: [
            'ACL (L2/L3)',
            'Control plane policing',
          ],
          specs: {
            'Latency': '< 50 ns (FPGA fast-path)',
            'FPGA': 'Xilinx Ultrascale+',
            'Ports': 'Configurable 10G/25G/100G',
          },
          children: [
            {
              nodeId: 'arista-7130-48g3',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7130-48G3',
              nameKo: '7130-48G3',
              description: '48-port FPGA-based switch with Layer 1+ switching for ultra-low latency applications',
              descriptionKo: '초저지연 애플리케이션을 위한 Layer 1+ 스위칭 탑재 48포트 FPGA 기반 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7130-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 10GbE',
                'Latency': '< 50 ns',
                'FPGA': 'Xilinx Ultrascale+',
              },
              children: [],
            },
            {
              nodeId: 'arista-7130-96s',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '7130-96S',
              nameKo: '7130-96S',
              description: '96-port 10GbE FPGA switch with customizable applications for HFT and media networks',
              descriptionKo: 'HFT 및 미디어 네트워크용 커스터마이징 가능한 애플리케이션 탑재 96포트 10GbE FPGA 스위치',
              sourceUrl: 'https://www.arista.com/en/products/7130-series',
              lifecycle: 'active',
              specs: {
                'Ports': '96x 10GbE',
                'Latency': '< 50 ns',
                'FPGA': 'Xilinx Ultrascale+',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // 2. Campus & Edge
    // =========================================================================
    {
      nodeId: 'arista-campus',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Campus & Edge',
      nameKo: '캠퍼스 & 에지',
      description: 'Campus networking solutions with PoE, cognitive management, and unified EOS across campus access, distribution, and core layers.',
      descriptionKo: 'PoE, 인지형 관리 및 캠퍼스 액세스, 디스트리뷰션, 코어 레이어 전체에 통합 EOS를 제공하는 캠퍼스 네트워킹 솔루션.',
      sourceUrl: 'https://www.arista.com/en/products/campus',
      infraNodeTypes: ['switch-l2', 'switch-l3'],
      children: [
        // -- CCS-720XP Series --
        {
          nodeId: 'arista-720xp',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CCS-720XP Series (Campus PoE)',
          nameKo: 'CCS-720XP 시리즈 (캠퍼스 PoE)',
          description: 'Campus access switches with PoE++ (802.3bt) support, Wi-Fi 6E AP connectivity, and CloudVision management for unified campus fabric.',
          descriptionKo: 'PoE++ (802.3bt) 지원, Wi-Fi 6E AP 연결, 통합 캠퍼스 패브릭을 위한 CloudVision 관리 기능의 캠퍼스 액세스 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/720xp-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/720XP-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l2'],
          architectureRole: 'Campus Access Layer',
          architectureRoleKo: '캠퍼스 액세스 레이어',
          recommendedFor: [
            'Campus access layer (Wi-Fi AP and endpoint connectivity)',
            'PoE-powered device deployment (IP phones, cameras, APs)',
            'Micro-segmentation at the campus edge',
          ],
          recommendedForKo: [
            '캠퍼스 액세스 레이어 (Wi-Fi AP 및 엔드포인트 연결)',
            'PoE 전원 기기 배포 (IP 전화, 카메라, AP)',
            '캠퍼스 에지의 마이크로 세그멘테이션',
          ],
          supportedProtocols: [
            'OSPF', 'BGP', 'VXLAN', 'LACP', 'STP', 'LLDP',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
          ],
          securityCapabilities: [
            'IEEE 802.1X port-based access control',
            'DHCP snooping',
            'Dynamic ARP inspection',
            'ACL (L2/L3)',
          ],
          specs: {
            'PoE Budget': 'Up to 1440W (PoE++, 802.3bt)',
            'Ports': 'Up to 48x 1G/2.5G/5G PoE + uplinks',
            'Switching Capacity': '176 Gbps',
          },
          children: [
            {
              nodeId: 'arista-720xp-24zy2',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '720XP-24ZY2',
              nameKo: '720XP-24ZY2',
              description: '24-port mGig PoE++ campus access switch with 2x 25GbE uplinks',
              descriptionKo: '2x 25GbE 업링크 탑재 24포트 mGig PoE++ 캠퍼스 액세스 스위치',
              sourceUrl: 'https://www.arista.com/en/products/720xp-series',
              lifecycle: 'active',
              specs: {
                'Ports': '24x 1G/2.5G/5G PoE++ + 2x 25GbE SFP28',
                'PoE Budget': '720W',
              },
              children: [],
            },
            {
              nodeId: 'arista-720xp-48zc2',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '720XP-48ZC2',
              nameKo: '720XP-48ZC2',
              description: '48-port mGig PoE++ campus access switch with 2x 100GbE uplinks for high-density deployments',
              descriptionKo: '고밀도 배포를 위한 2x 100GbE 업링크 탑재 48포트 mGig PoE++ 캠퍼스 액세스 스위치',
              sourceUrl: 'https://www.arista.com/en/products/720xp-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 1G/2.5G/5G PoE++ + 2x 100GbE QSFP28',
                'PoE Budget': '1440W',
              },
              children: [],
            },
            {
              nodeId: 'arista-720xp-48y',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '720XP-48Y',
              nameKo: '720XP-48Y',
              description: '48-port 1GbE PoE+ campus access switch with 25GbE uplinks for standard endpoint deployments',
              descriptionKo: '표준 엔드포인트 배포를 위한 25GbE 업링크 탑재 48포트 1GbE PoE+ 캠퍼스 액세스 스위치',
              sourceUrl: 'https://www.arista.com/en/products/720xp-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 1GbE RJ45 PoE+ + 4x 25GbE SFP28',
                'PoE Budget': '740W',
              },
              children: [],
            },
          ],
        },
        // -- CCS-720DP Series --
        {
          nodeId: 'arista-720dp',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CCS-720DP Series (Distribution)',
          nameKo: 'CCS-720DP 시리즈 (디스트리뷰션)',
          description: 'Campus distribution switches providing L3 routing, VXLAN fabric support, and high-bandwidth aggregation for campus networks.',
          descriptionKo: 'L3 라우팅, VXLAN 패브릭 지원 및 캠퍼스 네트워크용 고대역폭 집선을 제공하는 캠퍼스 디스트리뷰션 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/720dp-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/720DP-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Campus Distribution',
          architectureRoleKo: '캠퍼스 디스트리뷰션',
          recommendedFor: [
            'Campus distribution layer aggregation',
            'VXLAN/EVPN campus fabric distribution node',
            'Inter-VLAN routing and policy enforcement',
          ],
          recommendedForKo: [
            '캠퍼스 디스트리뷰션 레이어 집선',
            'VXLAN/EVPN 캠퍼스 패브릭 디스트리뷰션 노드',
            'Inter-VLAN 라우팅 및 정책 적용',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'PIM',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
            'BFD (Bidirectional Forwarding Detection)',
            'GIR (Graceful Insertion and Removal)',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'ACL (L2/L3/L4)',
            'IEEE 802.1X',
          ],
          specs: {
            'Switching Capacity': 'Up to 3.2 Tbps',
            'Ports': 'Up to 48x 25GbE + 100GbE uplinks',
          },
          children: [
            {
              nodeId: 'arista-720dp-48zc2',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '720DP-48ZC2',
              nameKo: '720DP-48ZC2',
              description: '48-port 25GbE SFP28 + 100GbE QSFP28 uplinks distribution switch',
              descriptionKo: '48포트 25GbE SFP28 + 100GbE QSFP28 업링크 디스트리뷰션 스위치',
              sourceUrl: 'https://www.arista.com/en/products/720dp-series',
              lifecycle: 'active',
              specs: {
                'Ports': '48x 25GbE SFP28 + 6x 100GbE QSFP28',
                'Switching Capacity': '3.2 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-720dp-24s',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '720DP-24S',
              nameKo: '720DP-24S',
              description: '24-port 10GbE SFP+ distribution switch for mid-size campus aggregation',
              descriptionKo: '중규모 캠퍼스 집선을 위한 24포트 10GbE SFP+ 디스트리뷰션 스위치',
              sourceUrl: 'https://www.arista.com/en/products/720dp-series',
              lifecycle: 'active',
              specs: {
                'Ports': '24x 10GbE SFP+',
                'Switching Capacity': '480 Gbps',
              },
              children: [],
            },
          ],
        },
        // -- CCS-750CX Series --
        {
          nodeId: 'arista-750cx',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CCS-750CX Series (Campus Core)',
          nameKo: 'CCS-750CX 시리즈 (캠퍼스 코어)',
          description: 'Campus core switches with high-density 100GbE/400GbE ports for backbone aggregation, VXLAN/EVPN fabric spine, and WAN edge roles.',
          descriptionKo: '백본 집선, VXLAN/EVPN 패브릭 스파인 및 WAN 에지 역할을 위한 고밀도 100GbE/400GbE 포트 캠퍼스 코어 스위치.',
          sourceUrl: 'https://www.arista.com/en/products/750cx-series',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/750CX-Series-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['switch-l3'],
          architectureRole: 'Campus Core / WAN Edge',
          architectureRoleKo: '캠퍼스 코어 / WAN 에지',
          recommendedFor: [
            'Campus core backbone aggregation',
            'VXLAN/EVPN campus fabric spine',
            'WAN edge termination with high-speed uplinks',
          ],
          recommendedForKo: [
            '캠퍼스 코어 백본 집선',
            'VXLAN/EVPN 캠퍼스 패브릭 스파인',
            '고속 업링크를 갖춘 WAN 에지 터미네이션',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VXLAN', 'EVPN', 'MPLS', 'PIM',
          ],
          haFeatures: [
            'MLAG (Multi-Chassis Link Aggregation)',
            'GIR (Graceful Insertion and Removal)',
            'BFD (Bidirectional Forwarding Detection)',
          ],
          securityCapabilities: [
            'MACsec (IEEE 802.1AE)',
            'ACL (L2/L3/L4)',
            'Control plane policing (CoPP)',
          ],
          specs: {
            'Switching Capacity': '12.8 Tbps',
            'Ports': 'Up to 64x 100GbE or 32x 400GbE',
          },
          children: [
            {
              nodeId: 'arista-750cx-64',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '750CX-64',
              nameKo: '750CX-64',
              description: '64-port 100GbE QSFP28 campus core switch with optional 400GbE uplinks',
              descriptionKo: '400GbE 업링크 옵션 탑재 64포트 100GbE QSFP28 캠퍼스 코어 스위치',
              sourceUrl: 'https://www.arista.com/en/products/750cx-series',
              lifecycle: 'active',
              specs: {
                'Ports': '64x 100GbE QSFP28',
                'Switching Capacity': '12.8 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'arista-750cx-32d',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: '750CX-32D',
              nameKo: '750CX-32D',
              description: '32-port 400GbE QSFP-DD campus core switch for next-generation backbone aggregation',
              descriptionKo: '차세대 백본 집선을 위한 32포트 400GbE QSFP-DD 캠퍼스 코어 스위치',
              sourceUrl: 'https://www.arista.com/en/products/750cx-series',
              lifecycle: 'active',
              specs: {
                'Ports': '32x 400GbE QSFP-DD',
                'Switching Capacity': '12.8 Tbps',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =========================================================================
    // 3. Routing
    // =========================================================================
    {
      nodeId: 'arista-routing',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Routing',
      nameKo: '라우팅',
      description: 'Routing platforms leveraging EOS with full BGP/OSPF/IS-IS/MPLS capabilities for WAN, peering, and border leaf/router roles.',
      descriptionKo: 'WAN, 피어링, 보더 리프/라우터 역할을 위한 전체 BGP/OSPF/IS-IS/MPLS 기능을 갖춘 EOS 기반 라우팅 플랫폼.',
      sourceUrl: 'https://www.arista.com/en/products/routing',
      infraNodeTypes: ['router'],
      children: [
        {
          nodeId: 'arista-routing-7500r3',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7500R3 Universal Spine (Routing Mode)',
          nameKo: '7500R3 유니버설 스파인 (라우팅 모드)',
          description: '7500R3 platform configured as a universal routing spine with full-table BGP, MPLS, and segment routing support for WAN and peering.',
          descriptionKo: '풀 테이블 BGP, MPLS, 세그먼트 라우팅을 지원하는 WAN 및 피어링용 유니버설 라우팅 스파인으로 구성된 7500R3 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/7500r3-series',
          lifecycle: 'active',
          infraNodeTypes: ['router'],
          architectureRole: 'WAN Core / Internet Peering Router',
          architectureRoleKo: 'WAN 코어 / 인터넷 피어링 라우터',
          recommendedFor: [
            'Internet peering router (full BGP table)',
            'WAN core routing with MPLS/SR',
            'Large-scale multi-site interconnect',
          ],
          recommendedForKo: [
            '인터넷 피어링 라우터 (풀 BGP 테이블)',
            'MPLS/SR 기반 WAN 코어 라우팅',
            '대규모 멀티 사이트 인터커넥트',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'MPLS', 'Segment Routing', 'PIM', 'BFD',
          ],
          specs: {
            'Full BGP Table': 'Yes (2M+ routes)',
            'MPLS': 'LDP, RSVP-TE, Segment Routing',
          },
          children: [],
        },
        {
          nodeId: 'arista-routing-7280r3',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7280R3 (Border Leaf/Router)',
          nameKo: '7280R3 (보더 리프/라우터)',
          description: '7280R3 platform deployed as border leaf or WAN edge router with deep buffers and full routing stack for DCI and external peering.',
          descriptionKo: 'DCI 및 외부 피어링을 위한 딥버퍼와 풀 라우팅 스택을 갖춘 보더 리프 또는 WAN 에지 라우터로 배포되는 7280R3 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/7280r3-series',
          lifecycle: 'active',
          infraNodeTypes: ['router'],
          architectureRole: 'Border Leaf / WAN Edge Router',
          architectureRoleKo: '보더 리프 / WAN 에지 라우터',
          recommendedFor: [
            'Data center interconnect (DCI) border router',
            'WAN edge with deep buffer for bursty traffic',
            'External BGP peering point',
          ],
          recommendedForKo: [
            '데이터센터 인터커넥트(DCI) 보더 라우터',
            '버스트 트래픽을 위한 딥버퍼 WAN 에지',
            '외부 BGP 피어링 포인트',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'MPLS', 'VXLAN', 'EVPN', 'BFD',
          ],
          specs: {
            'Buffer': 'Deep buffer (up to 32 GB)',
            'Full BGP Table': 'Yes',
          },
          children: [],
        },
        {
          nodeId: 'arista-7010t',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7010T Series',
          nameKo: '7010T 시리즈',
          description: 'Compact 1GbE routing platform for small branch, lab, and management network deployments running full EOS.',
          descriptionKo: '풀 EOS를 실행하는 소규모 지사, 랩 및 관리 네트워크 배포용 컴팩트 1GbE 라우팅 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/7010t-series',
          lifecycle: 'active',
          infraNodeTypes: ['router'],
          architectureRole: 'Branch / Lab Router',
          architectureRoleKo: '지사 / 랩 라우터',
          recommendedFor: [
            'Small branch office routing',
            'Lab and test environment routing',
            'Management network routing',
          ],
          recommendedForKo: [
            '소규모 지사 라우팅',
            '랩 및 테스트 환경 라우팅',
            '관리 네트워크 라우팅',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'IS-IS', 'VRRP', 'BFD',
          ],
          specs: {
            'Ports': '48x 1GbE RJ45 + 4x 10GbE SFP+',
            'Switching Capacity': '176 Gbps',
            'Form Factor': '1RU',
          },
          children: [],
        },
      ],
    },

    // =========================================================================
    // 4. Network Observability
    // =========================================================================
    {
      nodeId: 'arista-observability',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Observability',
      nameKo: '네트워크 옵저버빌리티',
      description: 'Network monitoring, packet capture, and traffic analysis solutions for network visibility, troubleshooting, and security analytics.',
      descriptionKo: '네트워크 가시성, 트러블슈팅 및 보안 분석을 위한 네트워크 모니터링, 패킷 캡처, 트래픽 분석 솔루션.',
      sourceUrl: 'https://www.arista.com/en/products/network-observability',
      infraNodeTypes: ['siem'],
      children: [
        {
          nodeId: 'arista-dmf',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'DANZ Monitoring Fabric (DMF)',
          nameKo: 'DANZ 모니터링 패브릭 (DMF)',
          description: 'Software-defined network monitoring fabric providing packet aggregation, filtering, deduplication, and timestamping for network TAP and SPAN traffic analysis.',
          descriptionKo: '네트워크 TAP 및 SPAN 트래픽 분석을 위한 패킷 집선, 필터링, 중복 제거, 타임스탬핑을 제공하는 소프트웨어 정의 네트워크 모니터링 패브릭.',
          sourceUrl: 'https://www.arista.com/en/products/danz-monitoring-fabric',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/DMF-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['siem'],
          architectureRole: 'Network Monitoring / Packet Broker',
          architectureRoleKo: '네트워크 모니터링 / 패킷 브로커',
          recommendedFor: [
            'Network TAP aggregation and traffic distribution',
            'Security tool feeding (IDS/IPS, forensics)',
            'Network performance monitoring and troubleshooting',
            'Compliance-driven traffic capture and archival',
          ],
          recommendedForKo: [
            '네트워크 TAP 집선 및 트래픽 분배',
            '보안 도구 피딩 (IDS/IPS, 포렌식)',
            '네트워크 성능 모니터링 및 트러블슈팅',
            '컴플라이언스 기반 트래픽 캡처 및 보관',
          ],
          specs: {
            'Architecture': 'Software-defined monitoring fabric',
            'Features': 'Aggregation, filtering, dedup, timestamping',
            'Integration': 'TAP, SPAN, inline tool insertion',
          },
          children: [],
        },
        {
          nodeId: 'arista-7130-monitoring',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: '7130 Monitoring',
          nameKo: '7130 모니터링',
          description: '7130 FPGA platform configured for precision network monitoring, timestamping, and packet capture with nanosecond accuracy.',
          descriptionKo: '나노초 정확도의 정밀 네트워크 모니터링, 타임스탬핑 및 패킷 캡처용으로 구성된 7130 FPGA 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/7130-series',
          lifecycle: 'active',
          infraNodeTypes: ['siem'],
          architectureRole: 'Precision Monitoring / Timestamping',
          architectureRoleKo: '정밀 모니터링 / 타임스탬핑',
          recommendedFor: [
            'Nanosecond-precision packet timestamping',
            'Financial trading latency measurement',
            'Network forensics and compliance monitoring',
          ],
          recommendedForKo: [
            '나노초 정밀 패킷 타임스탬핑',
            '금융 트레이딩 지연 측정',
            '네트워크 포렌식 및 컴플라이언스 모니터링',
          ],
          specs: {
            'Timestamp Accuracy': '< 5 ns',
            'Platform': '7130 FPGA-based',
            'Features': 'Packet capture, timestamping, tap aggregation',
          },
          children: [],
        },
      ],
    },

    // =========================================================================
    // 5. Network Management
    // =========================================================================
    {
      nodeId: 'arista-management',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Management',
      nameKo: '네트워크 관리',
      description: 'Centralized network management, automation, and cloud operations platforms for Arista EOS-based infrastructure.',
      descriptionKo: 'Arista EOS 기반 인프라를 위한 중앙 집중형 네트워크 관리, 자동화 및 클라우드 운영 플랫폼.',
      sourceUrl: 'https://www.arista.com/en/products/eos/cloudvision',
      infraNodeTypes: ['private-cloud'],
      children: [
        {
          nodeId: 'arista-cloudvision',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CloudVision',
          nameKo: 'CloudVision',
          description: 'On-premises network management and automation platform providing real-time telemetry, configuration management, compliance, and network-wide analytics for Arista EOS devices.',
          descriptionKo: 'Arista EOS 장비를 위한 실시간 텔레메트리, 구성 관리, 컴플라이언스 및 네트워크 전체 분석을 제공하는 온프레미스 네트워크 관리 및 자동화 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/eos/cloudvision',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/CloudVision-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Network Management / Automation',
          architectureRoleKo: '네트워크 관리 / 자동화',
          recommendedFor: [
            'Centralized network configuration management',
            'Real-time streaming telemetry and analytics',
            'Change management and compliance auditing',
            'Network-wide software image management',
          ],
          recommendedForKo: [
            '중앙 집중형 네트워크 구성 관리',
            '실시간 스트리밍 텔레메트리 및 분석',
            '변경 관리 및 컴플라이언스 감사',
            '네트워크 전체 소프트웨어 이미지 관리',
          ],
          specs: {
            'Deployment': 'On-premises (VM or appliance)',
            'Telemetry': 'Streaming (gNMI, OpenConfig)',
            'API': 'RESTful, gRPC, eAPI',
            'Features': 'Config mgmt, compliance, image mgmt, analytics',
          },
          children: [],
        },
        {
          nodeId: 'arista-cvaas',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CloudVision as-a-Service (CVaaS)',
          nameKo: 'CloudVision as-a-Service (CVaaS)',
          description: 'Cloud-hosted version of CloudVision delivering network management, automation, and telemetry as a SaaS offering with zero on-premises infrastructure.',
          descriptionKo: '온프레미스 인프라 없이 네트워크 관리, 자동화, 텔레메트리를 SaaS로 제공하는 클라우드 호스팅 CloudVision.',
          sourceUrl: 'https://www.arista.com/en/products/eos/cloudvision-as-a-service',
          lifecycle: 'active',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Cloud-Hosted Network Management',
          architectureRoleKo: '클라우드 호스팅 네트워크 관리',
          recommendedFor: [
            'Multi-site network management from the cloud',
            'Organizations without on-prem management infrastructure',
            'Rapid deployment with SaaS-based operations',
          ],
          recommendedForKo: [
            '클라우드에서의 멀티 사이트 네트워크 관리',
            '온프레미스 관리 인프라가 없는 조직',
            'SaaS 기반 운영을 통한 신속한 배포',
          ],
          specs: {
            'Deployment': 'Cloud-hosted (SaaS)',
            'Features': 'Same as CloudVision + zero on-prem',
            'Connectivity': 'Secure TerminAttr agent to cloud',
          },
          children: [],
        },
        {
          nodeId: 'arista-cloudeos',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CloudEOS',
          nameKo: 'CloudEOS',
          description: 'Virtual EOS router for multi-cloud and hybrid-cloud environments, extending Arista EOS networking to AWS, Azure, and GCP with consistent management via CloudVision.',
          descriptionKo: 'CloudVision을 통한 일관된 관리로 Arista EOS 네트워킹을 AWS, Azure, GCP로 확장하는 멀티클라우드 및 하이브리드 클라우드 환경용 가상 EOS 라우터.',
          sourceUrl: 'https://www.arista.com/en/products/cloudeos',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/CloudEOS-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Multi-Cloud Virtual Router',
          architectureRoleKo: '멀티클라우드 가상 라우터',
          recommendedFor: [
            'Multi-cloud networking (AWS, Azure, GCP)',
            'Hybrid cloud connectivity with consistent policy',
            'Cloud-native transit gateway replacement',
          ],
          recommendedForKo: [
            '멀티클라우드 네트워킹 (AWS, Azure, GCP)',
            '일관된 정책의 하이브리드 클라우드 연결',
            '클라우드 네이티브 트랜짓 게이트웨이 대체',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'VXLAN', 'IPsec', 'GRE',
          ],
          specs: {
            'Deployment': 'VM on AWS / Azure / GCP',
            'EOS Version': 'Full EOS feature parity',
            'Management': 'CloudVision / CVaaS',
            'Tunneling': 'VXLAN, IPsec, GRE',
          },
          children: [],
        },
      ],
    },

    // =========================================================================
    // 6. Security
    // =========================================================================
    {
      nodeId: 'arista-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Security',
      nameKo: '보안',
      description: 'Network security solutions including network detection and response (NDR) and macro-segmentation for zero-trust architectures.',
      descriptionKo: '제로 트러스트 아키텍처를 위한 네트워크 탐지 및 대응(NDR) 및 매크로 세그멘테이션을 포함하는 네트워크 보안 솔루션.',
      sourceUrl: 'https://www.arista.com/en/products/network-security',
      infraNodeTypes: ['firewall', 'ids-ips'],
      children: [
        {
          nodeId: 'arista-ndr',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Arista NDR (Network Detection & Response)',
          nameKo: 'Arista NDR (네트워크 탐지 및 대응)',
          description: 'AI-driven network detection and response platform leveraging deep packet inspection and behavioral analytics to detect advanced threats, lateral movement, and ransomware in real-time.',
          descriptionKo: '실시간으로 고급 위협, 측면 이동 및 랜섬웨어를 탐지하기 위해 딥 패킷 인스펙션 및 행동 분석을 활용하는 AI 기반 네트워크 탐지 및 대응 플랫폼.',
          sourceUrl: 'https://www.arista.com/en/products/network-detection-and-response',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/NDR-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['ids-ips'],
          architectureRole: 'Network Threat Detection / NDR',
          architectureRoleKo: '네트워크 위협 탐지 / NDR',
          recommendedFor: [
            'Advanced threat detection (APT, ransomware)',
            'Lateral movement detection in data center',
            'SOC integration for network-level threat intelligence',
            'Encrypted traffic analysis without decryption',
          ],
          recommendedForKo: [
            '고급 위협 탐지 (APT, 랜섬웨어)',
            '데이터센터 내 측면 이동 탐지',
            '네트워크 수준 위협 인텔리전스를 위한 SOC 연동',
            '복호화 없는 암호화 트래픽 분석',
          ],
          specs: {
            'Detection Engine': 'AI/ML behavioral analytics',
            'Analysis': 'Deep packet inspection, metadata analysis',
            'Integration': 'SIEM, SOAR, CloudVision',
            'Deployment': 'Sensor-based (physical or virtual)',
          },
          children: [],
        },
        {
          nodeId: 'arista-mss',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'MSS (Macro-Segmentation)',
          nameKo: 'MSS (매크로 세그멘테이션)',
          description: 'Macro-segmentation service integrated with Arista switches for network-level zero-trust enforcement, inserting stateful firewall services into the VXLAN fabric without traffic hairpinning.',
          descriptionKo: '트래픽 헤어피닝 없이 VXLAN 패브릭에 스테이트풀 방화벽 서비스를 삽입하여 네트워크 수준 제로 트러스트를 적용하는 Arista 스위치 통합 매크로 세그멘테이션 서비스.',
          sourceUrl: 'https://www.arista.com/en/products/macro-segmentation-service',
          datasheetUrl: 'https://www.arista.com/assets/data/pdf/Datasheets/MSS-Data-Sheet.pdf',
          lifecycle: 'active',
          infraNodeTypes: ['firewall'],
          architectureRole: 'Network Zero-Trust Segmentation',
          architectureRoleKo: '네트워크 제로 트러스트 세그멘테이션',
          recommendedFor: [
            'Zero-trust macro-segmentation in VXLAN/EVPN fabrics',
            'Stateful firewall insertion without traffic hairpinning',
            'East-west traffic security enforcement',
            'Multi-vendor firewall service chaining',
          ],
          recommendedForKo: [
            'VXLAN/EVPN 패브릭의 제로 트러스트 매크로 세그멘테이션',
            '트래픽 헤어피닝 없는 스테이트풀 방화벽 삽입',
            '동-서 트래픽 보안 적용',
            '멀티벤더 방화벽 서비스 체이닝',
          ],
          specs: {
            'Architecture': 'Inline service insertion via VXLAN',
            'Integration': 'Palo Alto, Check Point, Fortinet firewalls',
            'Management': 'CloudVision MSS policy',
            'Enforcement': 'Stateful L4-L7 segmentation',
          },
          children: [],
        },
      ],
    },
  ],
};
