/**
 * Cloudflare --- Full Product Catalog
 *
 * Hierarchical product tree covering Application Services, Zero Trust / SASE,
 * Developer Platform, and Network Services categories.
 *
 * Data sourced from https://www.cloudflare.com/ (multiple product pages)
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Cloudflare Product Catalog
// ---------------------------------------------------------------------------

export const cloudflareCatalog: VendorCatalog = {
  vendorId: 'cloudflare',
  vendorName: 'Cloudflare',
  vendorNameKo: '클라우드플레어',
  headquarters: 'San Francisco, CA, USA',
  website: 'https://www.cloudflare.com',
  productPageUrl: 'https://www.cloudflare.com/products/',
  depthStructure: ['category', 'product-line', 'service'],
  depthStructureKo: ['카테고리', '제품 라인', '서비스'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.cloudflare.com/products/',
  stats: { totalProducts: 54, maxDepth: 2, categoriesCount: 4 },
  products: [
    // =====================================================================
    // 1. Application Services
    // =====================================================================
    {
      nodeId: 'cloudflare-application-services',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Application Services',
      nameKo: '애플리케이션 서비스',
      description:
        'Global CDN, DNS, WAF, DDoS protection, and load balancing for web applications',
      descriptionKo:
        '웹 애플리케이션을 위한 글로벌 CDN, DNS, WAF, DDoS 방어, 로드 밸런싱',
      sourceUrl: 'https://www.cloudflare.com/application-services/products/',
      infraNodeTypes: ['cdn', 'waf', 'dns', 'load-balancer'],
      children: [
        // -- CDN --------------------------------------------------------
        {
          nodeId: 'cloudflare-cdn-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CDN',
          nameKo: 'CDN',
          description:
            'Global content delivery network with edge caching across 330+ data centers, within 50 ms of 95% of Internet users',
          descriptionKo:
            '330개 이상 데이터 센터에서 에지 캐싱을 제공하는 글로벌 콘텐츠 전송 네트워크, 전세계 인터넷 사용자 95%에서 50ms 이내',
          sourceUrl: 'https://www.cloudflare.com/cdn/',
          infraNodeTypes: ['cdn'],
          architectureRole: 'Edge Delivery / Content Acceleration',
          architectureRoleKo: '에지 전송 / 콘텐츠 가속',
          recommendedFor: [
            'Global static and dynamic content acceleration',
            'Origin offload and bandwidth cost reduction',
            'Media-heavy websites and e-commerce',
            'Enterprise web application performance',
            'Multi-region content distribution',
          ],
          recommendedForKo: [
            '글로벌 정적/동적 콘텐츠 가속',
            '오리진 부하 분산 및 대역폭 비용 절감',
            '미디어 중심 웹사이트 및 전자상거래',
            '엔터프라이즈 웹 애플리케이션 성능',
            '멀티 리전 콘텐츠 배포',
          ],
          supportedProtocols: [
            'HTTP/1.1',
            'HTTP/2',
            'HTTP/3 (QUIC)',
            'TLS 1.3',
            'WebSocket',
            'gRPC',
          ],
          haFeatures: [
            'Anycast network with automatic failover',
            'Every service runs on every server in every data center',
            'Automatic origin health monitoring',
            'Global load balancing integration',
          ],
          securityCapabilities: [
            'Universal SSL/TLS',
            'Unmetered DDoS protection',
            'WAF integration',
            'Bot mitigation',
            'Hotlink protection',
          ],
          children: [
            {
              nodeId: 'cloudflare-cdn',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare CDN',
              nameKo: 'Cloudflare CDN',
              description:
                'Global content delivery network with 330+ PoPs, edge caching, image optimization, and integrated DDoS/WAF protection',
              descriptionKo:
                '330개 이상 PoP, 에지 캐싱, 이미지 최적화, DDoS/WAF 보호가 통합된 글로벌 콘텐츠 전송 네트워크',
              sourceUrl: 'https://www.cloudflare.com/cdn/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Edge Delivery / Content Acceleration',
              architectureRoleKo: '에지 전송 / 콘텐츠 가속',
              recommendedFor: [
                'Global website and application acceleration',
                'Static asset caching and delivery',
                'Image optimization with automatic WebP conversion',
                'Origin server offload and cost reduction',
              ],
              recommendedForKo: [
                '글로벌 웹사이트 및 애플리케이션 가속',
                '정적 자산 캐싱 및 전송',
                '자동 WebP 변환을 통한 이미지 최적화',
                '오리진 서버 부하 분산 및 비용 절감',
              ],
              specs: {
                'Global PoPs': '330+ cities',
                'Network Capacity': '477 Tbps',
                'Protocols': 'HTTP/1.1, HTTP/2, HTTP/3 (QUIC)',
                'TLS': 'TLS 1.3, Universal SSL',
                'Image Optimization': '~35% average size reduction',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-argo-smart-routing',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Argo Smart Routing',
              nameKo: 'Argo Smart Routing',
              description:
                'Intelligent traffic routing that detects and avoids network congestion, delivering ~30% faster web performance',
              descriptionKo:
                '네트워크 혼잡을 감지하고 우회하는 지능형 트래픽 라우팅, 약 30% 빠른 웹 성능 제공',
              sourceUrl:
                'https://www.cloudflare.com/products/argo-smart-routing/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'WAN Optimization / Intelligent Routing',
              architectureRoleKo: 'WAN 최적화 / 지능형 라우팅',
              recommendedFor: [
                'Latency-sensitive web applications',
                'Global SaaS platforms requiring optimized routing',
                'E-commerce with geographically distributed users',
              ],
              recommendedForKo: [
                '지연 시간에 민감한 웹 애플리케이션',
                '최적화된 라우팅이 필요한 글로벌 SaaS 플랫폼',
                '지리적으로 분산된 사용자의 전자상거래',
              ],
              specs: {
                'Performance Improvement': '~30% average',
                'Network Visibility': '93M+ HTTP req/sec analyzed',
                'Encryption': 'End-to-end across Cloudflare network',
                'Deployment': 'Cloud (global edge)',
                'Tiered Caching': 'Included',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-images',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Images',
              nameKo: 'Cloudflare Images',
              description:
                'Image storage, optimization, and delivery with automatic resizing, compression, and format conversion',
              descriptionKo:
                '자동 크기 조정, 압축, 형식 변환이 포함된 이미지 저장, 최적화 및 전송 서비스',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/cloudflare-images/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Media Optimization / Edge Delivery',
              architectureRoleKo: '미디어 최적화 / 에지 전송',
              recommendedFor: [
                'Image-heavy websites and media platforms',
                'E-commerce product image management',
                'Dynamic image transformation at edge',
              ],
              recommendedForKo: [
                '이미지 중심 웹사이트 및 미디어 플랫폼',
                '전자상거래 제품 이미지 관리',
                '에지에서의 동적 이미지 변환',
              ],
              specs: {
                'Formats': 'WebP, AVIF, JPEG, PNG, GIF, SVG',
                'Transformations': 'Resize, crop, compress, format convert',
                'Delivery': 'Global edge (330+ PoPs)',
                'Storage': 'Included with API',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-stream',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Stream',
              nameKo: 'Cloudflare Stream',
              description:
                'Serverless video streaming platform with encoding, storage, and adaptive bitrate delivery',
              descriptionKo:
                '인코딩, 저장, 적응형 비트레이트 전송이 포함된 서버리스 비디오 스트리밍 플랫폼',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/stream/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Media Streaming / Video Delivery',
              architectureRoleKo: '미디어 스트리밍 / 비디오 전송',
              recommendedFor: [
                'Video-on-demand and live streaming platforms',
                'Corporate video portals and training',
                'User-generated content platforms',
              ],
              recommendedForKo: [
                'VOD 및 라이브 스트리밍 플랫폼',
                '기업 비디오 포털 및 교육',
                '사용자 생성 콘텐츠 플랫폼',
              ],
              specs: {
                'Encoding': 'Automatic adaptive bitrate',
                'Delivery': 'Global edge (330+ PoPs)',
                'Player': 'Embedded player included',
                'Storage': 'Included per-minute pricing',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- DNS --------------------------------------------------------
        {
          nodeId: 'cloudflare-dns-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'DNS',
          nameKo: 'DNS',
          description:
            'Authoritative and recursive DNS with industry-leading 11ms average response time across 330+ cities',
          descriptionKo:
            '330개 이상 도시에서 업계 최고 평균 11ms 응답 시간의 권한 있는 DNS 및 재귀 DNS',
          sourceUrl: 'https://www.cloudflare.com/dns/',
          infraNodeTypes: ['dns'],
          architectureRole: 'DNS Resolution / Domain Management',
          architectureRoleKo: 'DNS 확인 / 도메인 관리',
          recommendedFor: [
            'Enterprise authoritative DNS hosting',
            'DNS-level DDoS protection',
            'Global DNS performance optimization',
            'DNSSEC implementation',
          ],
          recommendedForKo: [
            '엔터프라이즈 권한 있는 DNS 호스팅',
            'DNS 레벨 DDoS 방어',
            '글로벌 DNS 성능 최적화',
            'DNSSEC 구현',
          ],
          supportedProtocols: [
            'DNS',
            'DNS over HTTPS (DoH)',
            'DNS over TLS (DoT)',
            'DNSSEC',
          ],
          haFeatures: [
            'Anycast DNS across 330+ cities',
            'Automatic failover',
            '100% uptime SLA (Enterprise)',
            '23x capacity vs largest recorded DDoS',
          ],
          securityCapabilities: [
            'DNSSEC (one-click)',
            'Unmetered DDoS protection',
            'Email security DNS records (SPF, DKIM, DMARC)',
          ],
          children: [
            {
              nodeId: 'cloudflare-dns',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare DNS',
              nameKo: 'Cloudflare DNS',
              description:
                'Authoritative DNS with 11ms average response, DNSSEC, unmetered DDoS protection, and 13,000+ network interconnections',
              descriptionKo:
                '평균 11ms 응답, DNSSEC, 무제한 DDoS 방어, 13,000개 이상 네트워크 연동의 권한 있는 DNS',
              sourceUrl: 'https://www.cloudflare.com/dns/',
              infraNodeTypes: ['dns'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Authoritative DNS / Domain Management',
              architectureRoleKo: '권한 있는 DNS / 도메인 관리',
              recommendedFor: [
                'Enterprise domain hosting with ultra-low latency',
                'DNS-level DDoS mitigation',
                'DNSSEC-enabled secure resolution',
                'Multi-domain management at scale',
              ],
              recommendedForKo: [
                '초저지연 엔터프라이즈 도메인 호스팅',
                'DNS 레벨 DDoS 완화',
                'DNSSEC 기반 보안 확인',
                '대규모 멀티 도메인 관리',
              ],
              specs: {
                'Average Response Time': '11ms',
                'Global PoPs': '330+ cities',
                'Network Interconnections': '13,000+',
                'DDoS Capacity': '23x largest attack ever recorded',
                'DNSSEC': 'One-click enable',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-1111',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: '1.1.1.1',
              nameKo: '1.1.1.1',
              description:
                'Free public DNS resolver with privacy-first design, DNS over HTTPS/TLS, and malware/adult content filtering options',
              descriptionKo:
                '프라이버시 우선 설계, DNS over HTTPS/TLS, 멀웨어/성인 콘텐츠 필터링 옵션이 포함된 무료 공개 DNS 리졸버',
              sourceUrl: 'https://www.cloudflare.com/learning/dns/what-is-1.1.1.1/',
              infraNodeTypes: ['dns'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Public Recursive DNS Resolver',
              architectureRoleKo: '공개 재귀 DNS 리졸버',
              recommendedFor: [
                'Privacy-first DNS resolution for end users',
                'Enterprise recursive DNS with filtering',
                'Malware and phishing DNS-level blocking',
              ],
              recommendedForKo: [
                '최종 사용자를 위한 프라이버시 우선 DNS 확인',
                '필터링이 포함된 엔터프라이즈 재귀 DNS',
                '멀웨어 및 피싱 DNS 레벨 차단',
              ],
              specs: {
                'DNS Resolver': '1.1.1.1 / 1.0.0.1',
                'Protocols': 'DoH, DoT, DNS',
                'Filtering Variants': '1.1.1.2 (malware), 1.1.1.3 (malware+adult)',
                'Privacy': 'No query logging, APNIC audited',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- Load Balancing ----------------------------------------------
        {
          nodeId: 'cloudflare-lb-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Load Balancing',
          nameKo: '로드 밸런싱',
          description:
            'Global and local load balancing across L4-L7 protocols with health checks and near real-time failover',
          descriptionKo:
            '헬스 체크 및 실시간에 가까운 장애 조치를 통한 L4-L7 프로토콜 글로벌/로컬 로드 밸런싱',
          sourceUrl: 'https://www.cloudflare.com/load-balancing/',
          infraNodeTypes: ['load-balancer'],
          architectureRole: 'Global Traffic Management / Load Distribution',
          architectureRoleKo: '글로벌 트래픽 관리 / 부하 분산',
          recommendedFor: [
            'Multi-region application failover',
            'Global server load balancing (GSLB)',
            'Hybrid and multi-cloud traffic distribution',
          ],
          recommendedForKo: [
            '멀티 리전 애플리케이션 장애 조치',
            '글로벌 서버 로드 밸런싱 (GSLB)',
            '하이브리드 및 멀티 클라우드 트래픽 분산',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'TCP',
            'UDP',
            'DNS-based GSLB',
          ],
          haFeatures: [
            'Near real-time failover',
            'Active health checks',
            'Geographic steering',
            'Session affinity',
          ],
          children: [
            {
              nodeId: 'cloudflare-load-balancing',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Load Balancing',
              nameKo: 'Cloudflare 로드 밸런싱',
              description:
                'Global always-on load balancer across 330+ cities with L4-L7 support, health checks, geo-steering, and private network LB',
              descriptionKo:
                '330개 이상 도시에서 L4-L7 지원, 헬스 체크, 지리적 스티어링, 프라이빗 네트워크 LB를 갖춘 글로벌 상시 로드 밸런서',
              sourceUrl: 'https://www.cloudflare.com/load-balancing/',
              infraNodeTypes: ['load-balancer'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Global Traffic Management / Load Distribution',
              architectureRoleKo: '글로벌 트래픽 관리 / 부하 분산',
              recommendedFor: [
                'DNS-based global server load balancing',
                'Multi-cloud and hybrid origin failover',
                'Private network load balancing (PNLB)',
                'Latency-based geographic steering',
              ],
              recommendedForKo: [
                'DNS 기반 글로벌 서버 로드 밸런싱',
                '멀티 클라우드 및 하이브리드 오리진 장애 조치',
                '프라이빗 네트워크 로드 밸런싱 (PNLB)',
                '지연 시간 기반 지리적 스티어링',
              ],
              specs: {
                'Global PoPs': '330+ cities',
                'Protocols': 'HTTP/S, TCP, UDP',
                'Health Checks': 'Active, configurable intervals',
                'Steering Modes': 'Geo, latency, random, hash',
                'Private Network LB': 'Supported',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- WAF --------------------------------------------------------
        {
          nodeId: 'cloudflare-waf-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'WAF',
          nameKo: 'WAF',
          description:
            'Web Application Firewall with ML-powered threat detection, OWASP rulesets, and 126M+ HTTP req/sec processing',
          descriptionKo:
            'ML 기반 위협 탐지, OWASP 규칙 세트, 126M+ HTTP req/sec 처리의 웹 애플리케이션 방화벽',
          sourceUrl: 'https://www.cloudflare.com/waf/',
          infraNodeTypes: ['waf'],
          architectureRole: 'Application Security / Edge Protection',
          architectureRoleKo: '애플리케이션 보안 / 에지 보호',
          recommendedFor: [
            'Web application threat protection (SQLi, XSS)',
            'OWASP Top 10 compliance',
            'Bot management and credential stuffing prevention',
            'API protection and rate limiting',
          ],
          recommendedForKo: [
            '웹 애플리케이션 위협 방어 (SQLi, XSS)',
            'OWASP Top 10 준수',
            '봇 관리 및 크리덴셜 스터핑 방지',
            'API 보호 및 속도 제한',
          ],
          supportedProtocols: ['HTTP/1.1', 'HTTP/2', 'HTTP/3', 'WebSocket'],
          haFeatures: [
            'Global Anycast deployment',
            'Zero-day protection via managed rulesets',
            'Automatic ML-based rule updates',
          ],
          securityCapabilities: [
            'OWASP Core Rule Set',
            'Cloudflare Managed Rules',
            'ML-powered threat detection',
            'Custom WAF rules',
            'Credential stuffing detection',
            'Uploaded file malware scanning',
            'Exposed credential checks',
            'Terraform integration',
          ],
          children: [
            {
              nodeId: 'cloudflare-waf',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare WAF',
              nameKo: 'Cloudflare WAF',
              description:
                'Cloud-native WAF processing 126M+ HTTP req/sec with ML-powered threat detection, OWASP rulesets, and zero-day managed rules',
              descriptionKo:
                'ML 기반 위협 탐지, OWASP 규칙 세트, 제로데이 관리형 규칙으로 126M+ HTTP req/sec를 처리하는 클라우드 네이티브 WAF',
              sourceUrl: 'https://www.cloudflare.com/waf/',
              infraNodeTypes: ['waf'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Application Security / Edge WAF',
              architectureRoleKo: '애플리케이션 보안 / 에지 WAF',
              recommendedFor: [
                'Enterprise web application protection',
                'OWASP Top 10 vulnerability mitigation',
                'Zero-day exploit protection with managed rules',
                'Custom security policy enforcement',
              ],
              recommendedForKo: [
                '엔터프라이즈 웹 애플리케이션 보호',
                'OWASP Top 10 취약점 완화',
                '관리형 규칙을 통한 제로데이 익스플로잇 방어',
                '커스텀 보안 정책 적용',
              ],
              securityCapabilities: [
                'OWASP Core Rule Set',
                'Cloudflare Managed Rules',
                'ML-powered automatic blocking',
                'Custom rule builder',
                'Credential stuffing detection',
                'Malware scanning on uploads',
              ],
              specs: {
                'Peak Processing': '126M+ HTTP req/sec',
                'Rulesets': 'OWASP, Cloudflare Managed, Custom',
                'ML Detection': 'Automatic emerging threat blocking',
                'Terraform': 'Supported',
                'Global PoPs': '330+ cities',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-rate-limiting',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Advanced Rate Limiting',
              nameKo: 'Advanced Rate Limiting',
              description:
                'Granular rate limiting with configurable thresholds, request matching, and automatic mitigation for API and web traffic',
              descriptionKo:
                'API 및 웹 트래픽에 대한 구성 가능한 임계값, 요청 매칭, 자동 완화가 포함된 세분화된 속도 제한',
              sourceUrl: 'https://www.cloudflare.com/rate-limiting/',
              infraNodeTypes: ['waf'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'API Protection / Traffic Shaping',
              architectureRoleKo: 'API 보호 / 트래픽 셰이핑',
              recommendedFor: [
                'API abuse prevention and throttling',
                'Brute-force login attack mitigation',
                'DDoS layer 7 rate-based protection',
              ],
              recommendedForKo: [
                'API 남용 방지 및 스로틀링',
                '무차별 대입 로그인 공격 완화',
                'DDoS 레이어 7 속도 기반 보호',
              ],
              specs: {
                'Matching': 'URI, method, headers, IP, country',
                'Actions': 'Block, challenge, JS challenge, managed challenge',
                'Counting': 'Per IP, per session, per API key',
                'Integration': 'WAF custom rules engine',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-bot-management',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Bot Management',
              nameKo: 'Bot Management',
              description:
                'ML-powered bot detection and mitigation leveraging threat intelligence from 215B+ daily blocked threats',
              descriptionKo:
                '215B+ 일일 차단 위협의 위협 인텔리전스를 활용하는 ML 기반 봇 탐지 및 완화',
              sourceUrl: 'https://www.cloudflare.com/products/bot-management/',
              infraNodeTypes: ['waf'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Bot Detection / Fraud Prevention',
              architectureRoleKo: '봇 탐지 / 사기 방지',
              recommendedFor: [
                'Credential stuffing and account takeover prevention',
                'Content scraping protection',
                'Inventory hoarding and scalping prevention',
              ],
              recommendedForKo: [
                '크리덴셜 스터핑 및 계정 탈취 방지',
                '콘텐츠 스크래핑 보호',
                '재고 매점 및 스캘핑 방지',
              ],
              securityCapabilities: [
                'ML-based bot scoring',
                'JavaScript fingerprinting',
                'Behavioral analysis',
                'Managed challenge (Turnstile)',
              ],
              specs: {
                'Threat Intelligence': '215B+ threats blocked daily',
                'Detection': 'ML scoring, JS fingerprinting, behavioral',
                'Actions': 'Block, challenge, rate limit, log',
                'Integration': 'WAF + analytics dashboard',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-page-shield',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Page Shield',
              nameKo: 'Page Shield',
              description:
                'Client-side security monitoring that detects malicious third-party scripts, Magecart attacks, and supply chain threats',
              descriptionKo:
                '악성 서드파티 스크립트, Magecart 공격, 공급망 위협을 탐지하는 클라이언트 사이드 보안 모니터링',
              sourceUrl: 'https://www.cloudflare.com/page-shield/',
              infraNodeTypes: ['waf'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Client-Side Security / Supply Chain Protection',
              architectureRoleKo: '클라이언트 사이드 보안 / 공급망 보호',
              recommendedFor: [
                'E-commerce Magecart and card skimming prevention',
                'Third-party script monitoring and control',
                'PCI DSS client-side compliance',
              ],
              recommendedForKo: [
                '전자상거래 Magecart 및 카드 스키밍 방지',
                '서드파티 스크립트 모니터링 및 제어',
                'PCI DSS 클라이언트 사이드 준수',
              ],
              securityCapabilities: [
                'Third-party script monitoring',
                'Malicious JavaScript detection',
                'CSP management',
                'Supply chain attack alerting',
              ],
              specs: {
                'Monitoring': 'Real-time script inventory',
                'Detection': 'Malicious script, data exfiltration',
                'Alerts': 'New script, changed script, malicious',
                'Compliance': 'PCI DSS 6.4.3 / 11.6.1',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- DDoS Protection --------------------------------------------
        {
          nodeId: 'cloudflare-ddos-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'DDoS Protection',
          nameKo: 'DDoS 보호',
          description:
            'L3/4/7 DDoS mitigation with 477 Tbps network capacity, protecting web apps, TCP/UDP services, and network infrastructure',
          descriptionKo:
            '477 Tbps 네트워크 용량으로 웹 앱, TCP/UDP 서비스, 네트워크 인프라를 보호하는 L3/4/7 DDoS 완화',
          sourceUrl: 'https://www.cloudflare.com/ddos/',
          infraNodeTypes: ['cdn'],
          architectureRole: 'DDoS Mitigation / Network Protection',
          architectureRoleKo: 'DDoS 완화 / 네트워크 보호',
          recommendedFor: [
            'Enterprise DDoS protection for web applications',
            'Network infrastructure DDoS defense',
            'Always-on, unmetered mitigation',
          ],
          recommendedForKo: [
            '웹 애플리케이션 엔터프라이즈 DDoS 보호',
            '네트워크 인프라 DDoS 방어',
            '상시 활성, 무제한 완화',
          ],
          supportedProtocols: ['TCP', 'UDP', 'HTTP/HTTPS', 'GRE', 'BGP'],
          haFeatures: [
            '477 Tbps global mitigation capacity',
            'Anycast-based nearest-PoP mitigation',
            'Automatic attack detection and response',
          ],
          securityCapabilities: [
            'L3/4 volumetric attack mitigation',
            'L7 application-layer DDoS protection',
            'Protocol anomaly detection',
            'Adaptive rate limiting',
          ],
          children: [
            {
              nodeId: 'cloudflare-ddos-protection',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare DDoS Protection',
              nameKo: 'Cloudflare DDoS 보호',
              description:
                'Always-on L3/4/7 DDoS mitigation with 477 Tbps capacity across 330+ cities, mitigating attacks at the nearest edge',
              descriptionKo:
                '330개 이상 도시에서 477 Tbps 용량으로 가장 가까운 에지에서 공격을 완화하는 상시 L3/4/7 DDoS 방어',
              sourceUrl: 'https://www.cloudflare.com/ddos/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'DDoS Mitigation / Edge Protection',
              architectureRoleKo: 'DDoS 완화 / 에지 보호',
              recommendedFor: [
                'Always-on web application DDoS protection',
                'Unmetered mitigation without traffic caps',
                'Zero-performance-impact attack absorption',
              ],
              recommendedForKo: [
                '상시 웹 애플리케이션 DDoS 보호',
                '트래픽 제한 없는 무제한 완화',
                '성능 영향 없는 공격 흡수',
              ],
              specs: {
                'Network Capacity': '477 Tbps',
                'Mitigation Coverage': 'L3, L4, L7',
                'Global PoPs': '330+ cities',
                'Capacity vs Largest Attack': '23x',
                'Metering': 'Unmetered (all plans)',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-magic-transit',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Magic Transit',
              nameKo: 'Magic Transit',
              description:
                'Network-layer DDoS protection for on-prem infrastructure via BGP anycast, with 477 Tbps capacity and ~3s mitigation',
              descriptionKo:
                'BGP 애니캐스트를 통한 온프레미스 인프라용 네트워크 레이어 DDoS 방어, 477 Tbps 용량 및 ~3초 완화',
              sourceUrl: 'https://www.cloudflare.com/magic-transit/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Network DDoS Mitigation / On-Prem Protection',
              architectureRoleKo: '네트워크 DDoS 완화 / 온프레미스 보호',
              recommendedFor: [
                'Data center and on-prem network DDoS protection',
                'ISP and carrier-grade DDoS defense',
                'BGP-routed network IP protection',
              ],
              recommendedForKo: [
                '데이터센터 및 온프레미스 네트워크 DDoS 보호',
                'ISP 및 통신사급 DDoS 방어',
                'BGP 라우팅 네트워크 IP 보호',
              ],
              supportedProtocols: ['BGP', 'GRE', 'IPsec', 'PNI'],
              specs: {
                'Network Capacity': '477 Tbps',
                'Mitigation Time': '~3 seconds',
                'Routing': 'BGP Anycast',
                'Return Path': 'GRE tunnels, PNI, IPsec',
                'Layer Coverage': 'L3 (network layer)',
                'Deployment': 'Cloud (BGP anycast)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-spectrum',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Spectrum',
              nameKo: 'Spectrum',
              description:
                'TCP/UDP proxy and DDoS protection for non-HTTP services including gaming, email, and custom protocols',
              descriptionKo:
                '게임, 이메일, 커스텀 프로토콜 등 비HTTP 서비스를 위한 TCP/UDP 프록시 및 DDoS 보호',
              sourceUrl: 'https://www.cloudflare.com/products/cloudflare-spectrum/',
              infraNodeTypes: ['cdn'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'L4 Proxy / Non-HTTP DDoS Protection',
              architectureRoleKo: 'L4 프록시 / 비HTTP DDoS 보호',
              recommendedFor: [
                'Gaming server TCP/UDP DDoS protection',
                'Email and SSH service protection',
                'Custom protocol proxy and acceleration',
              ],
              recommendedForKo: [
                '게임 서버 TCP/UDP DDoS 보호',
                '이메일 및 SSH 서비스 보호',
                '커스텀 프로토콜 프록시 및 가속',
              ],
              specs: {
                'Protocols': 'TCP, UDP (any port)',
                'DDoS Protection': 'L3/L4 mitigation',
                'Use Cases': 'Gaming, email, SSH, FTP, custom',
                'Global PoPs': '330+ cities',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Zero Trust / SASE
    // =====================================================================
    {
      nodeId: 'cloudflare-zero-trust',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Zero Trust / SASE',
      nameKo: '제로 트러스트 / SASE',
      description:
        'Comprehensive SASE platform with ZTNA, SWG, CASB, DLP, email security, and browser isolation',
      descriptionKo:
        'ZTNA, SWG, CASB, DLP, 이메일 보안, 브라우저 격리가 포함된 종합 SASE 플랫폼',
      sourceUrl: 'https://www.cloudflare.com/zero-trust/products/',
      infraNodeTypes: ['sase-gateway', 'ztna-broker', 'vpn-gateway'],
      children: [
        // -- Access (ZTNA) -----------------------------------------------
        {
          nodeId: 'cloudflare-access-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloudflare Access',
          nameKo: 'Cloudflare Access',
          description:
            'Zero Trust Network Access replacing VPN with identity-aware proxy across 330+ cities',
          descriptionKo:
            '330개 이상 도시에서 아이덴티티 인식 프록시로 VPN을 대체하는 제로 트러스트 네트워크 액세스',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/access/',
          infraNodeTypes: ['ztna-broker'],
          architectureRole: 'Zero Trust Network Access / Identity Proxy',
          architectureRoleKo: '제로 트러스트 네트워크 액세스 / 아이덴티티 프록시',
          recommendedFor: [
            'VPN replacement with ZTNA',
            'Identity-based application access',
            'Contractor and third-party secure access',
            'SSH/RDP/VNC clientless access',
          ],
          recommendedForKo: [
            'ZTNA를 통한 VPN 대체',
            '아이덴티티 기반 애플리케이션 접근',
            '외주업체 및 서드파티 보안 접근',
            'SSH/RDP/VNC 클라이언트리스 접근',
          ],
          supportedProtocols: [
            'HTTPS',
            'SSH',
            'RDP',
            'VNC',
            'SAML',
            'OIDC',
            'mTLS',
          ],
          haFeatures: [
            'Global Anycast network (330+ cities)',
            'Multi-IdP concurrent support',
            'Automatic failover',
          ],
          securityCapabilities: [
            'Identity-aware proxy',
            'Device posture verification',
            'mTLS certificate authentication',
            'Context-based access policies',
            'Session duration controls',
            'Purpose justification enforcement',
          ],
          children: [
            {
              nodeId: 'cloudflare-access',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Access',
              nameKo: 'Cloudflare Access',
              description:
                'ZTNA solution providing identity-aware, least-privilege access to internal apps, infrastructure, and AI agents with device posture checks',
              descriptionKo:
                '디바이스 포스처 검사와 함께 내부 앱, 인프라, AI 에이전트에 아이덴티티 기반 최소 권한 접근을 제공하는 ZTNA 솔루션',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/access/',
              infraNodeTypes: ['ztna-broker'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Zero Trust Network Access / Identity Proxy',
              architectureRoleKo: '제로 트러스트 네트워크 액세스 / 아이덴티티 프록시',
              recommendedFor: [
                'Enterprise VPN replacement with zero trust',
                'Self-hosted and SaaS application access control',
                'Clientless SSH/VNC/RDP browser access',
                'Multi-IdP federated identity enforcement',
              ],
              recommendedForKo: [
                '제로 트러스트를 통한 엔터프라이즈 VPN 대체',
                '자체 호스팅 및 SaaS 애플리케이션 접근 제어',
                '클라이언트리스 SSH/VNC/RDP 브라우저 접근',
                '멀티 IdP 페더레이션 아이덴티티 적용',
              ],
              securityCapabilities: [
                'Identity-aware proxy',
                'Device posture verification',
                'mTLS authentication',
                'Context-based policies (geo, device, identity)',
                'Temporary authentication',
                'Purpose justification',
              ],
              specs: {
                'Global PoPs': '330+ cities in 125 countries',
                'Identity Providers': 'SAML, OIDC, multi-IdP concurrent',
                'Application Types': 'Self-hosted, SaaS, non-web (SSH/RDP/VNC)',
                'Device Platforms': 'Windows, Mac, iOS, Android, Linux, ChromeOS',
                'Authentication': 'mTLS, certificate-based, clientless',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- Gateway (SWG) -----------------------------------------------
        {
          nodeId: 'cloudflare-gateway-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloudflare Gateway',
          nameKo: 'Cloudflare Gateway',
          description:
            'Cloud-native Secure Web Gateway with DNS/HTTP filtering, threat prevention, and 50% faster than SWG alternatives',
          descriptionKo:
            'DNS/HTTP 필터링, 위협 방지, SWG 대안 대비 50% 빠른 클라우드 네이티브 보안 웹 게이트웨이',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/gateway/',
          infraNodeTypes: ['sase-gateway'],
          architectureRole: 'Secure Web Gateway / Internet Egress',
          architectureRoleKo: '보안 웹 게이트웨이 / 인터넷 이그레스',
          recommendedFor: [
            'Corporate internet security and filtering',
            'Ransomware and phishing prevention',
            'SaaS application traffic inspection',
          ],
          recommendedForKo: [
            '기업 인터넷 보안 및 필터링',
            '랜섬웨어 및 피싱 방지',
            'SaaS 애플리케이션 트래픽 검사',
          ],
          supportedProtocols: [
            'DNS',
            'HTTP/HTTPS',
            'TLS 1.3',
            'SSH',
            'IPv4',
            'IPv6',
          ],
          haFeatures: [
            'Global Anycast network',
            'Single-pass L3-L7 inspection',
            'No traffic backhauling',
          ],
          securityCapabilities: [
            'DNS and HTTP/S filtering',
            'TLS 1.3 inspection (unlimited)',
            'Antivirus scanning (PDF, ZIP, RAR)',
            'SSH proxying and command logging',
            'Threat category blocking (ransomware, phishing, C2)',
            'ML-powered threat detection',
          ],
          children: [
            {
              nodeId: 'cloudflare-gateway',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Gateway',
              nameKo: 'Cloudflare Gateway',
              description:
                'Cloud-native SWG with DNS/HTTP filtering, TLS inspection, AV scanning, SSH proxying, and single-pass L3-L7 inspection',
              descriptionKo:
                'DNS/HTTP 필터링, TLS 검사, AV 스캔, SSH 프록시, 싱글 패스 L3-L7 검사가 포함된 클라우드 네이티브 SWG',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/gateway/',
              infraNodeTypes: ['sase-gateway'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Secure Web Gateway / Internet Egress',
              architectureRoleKo: '보안 웹 게이트웨이 / 인터넷 이그레스',
              recommendedFor: [
                'Enterprise secure internet access',
                'DNS-level threat blocking (ransomware, phishing, C2)',
                'Full TLS inspection without performance loss',
                'SSH session proxying and audit logging',
              ],
              recommendedForKo: [
                '엔터프라이즈 보안 인터넷 접근',
                'DNS 레벨 위협 차단 (랜섬웨어, 피싱, C2)',
                '성능 저하 없는 전체 TLS 검사',
                'SSH 세션 프록시 및 감사 로깅',
              ],
              securityCapabilities: [
                'DNS and HTTP/S filtering',
                'TLS 1.3 unlimited inspection',
                'Antivirus scanning',
                'SSH proxying and logging',
                'DGA and DNS tunneling detection',
                'ML-powered threat intelligence',
              ],
              specs: {
                'Inspection': 'Single-pass L3-L7',
                'TLS Inspection': 'TLS 1.3, unlimited',
                'Protocols': 'DNS, HTTP/S, SSH, L4 firewall',
                'IPv6': 'Dual-stack supported',
                'Performance': '50% faster than SWG alternatives',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- Tunnel ------------------------------------------------------
        {
          nodeId: 'cloudflare-tunnel-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloudflare Tunnel',
          nameKo: 'Cloudflare Tunnel',
          description:
            'Secure outbound-only connection from origin servers to Cloudflare edge, eliminating inbound port exposure',
          descriptionKo:
            '오리진 서버에서 Cloudflare 에지로의 아웃바운드 전용 보안 연결, 인바운드 포트 노출 제거',
          sourceUrl: 'https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/',
          infraNodeTypes: ['vpn-gateway'],
          architectureRole: 'Secure Origin Connection / VPN Replacement',
          architectureRoleKo: '보안 오리진 연결 / VPN 대체',
          recommendedFor: [
            'Zero trust origin server connectivity',
            'VPN replacement for application exposure',
            'Secure connection without public IP',
          ],
          recommendedForKo: [
            '제로 트러스트 오리진 서버 연결',
            '애플리케이션 노출을 위한 VPN 대체',
            '공인 IP 없이 보안 연결',
          ],
          supportedProtocols: ['HTTPS', 'SSH', 'RDP', 'TCP', 'UDP'],
          haFeatures: [
            'Multiple tunnel replicas for redundancy',
            'Automatic reconnection',
            'Cloudflare Anycast failover',
          ],
          children: [
            {
              nodeId: 'cloudflare-tunnel',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Tunnel',
              nameKo: 'Cloudflare Tunnel',
              description:
                'Encrypted outbound-only tunnels from origins to Cloudflare edge, replacing VPN and eliminating inbound firewall rules',
              descriptionKo:
                '오리진에서 Cloudflare 에지로의 암호화된 아웃바운드 전용 터널, VPN 대체 및 인바운드 방화벽 규칙 제거',
              sourceUrl: 'https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/',
              infraNodeTypes: ['vpn-gateway'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Secure Origin Connection / VPN Replacement',
              architectureRoleKo: '보안 오리진 연결 / VPN 대체',
              recommendedFor: [
                'Exposing internal apps without public IPs or VPNs',
                'Zero trust origin connectivity',
                'Cloudflare Access integration for ZTNA',
              ],
              recommendedForKo: [
                '공인 IP 또는 VPN 없이 내부 앱 노출',
                '제로 트러스트 오리진 연결',
                'ZTNA를 위한 Cloudflare Access 통합',
              ],
              specs: {
                'Connection': 'Outbound-only encrypted tunnel',
                'Protocols': 'HTTPS, SSH, RDP, TCP, UDP',
                'Agent': 'cloudflared daemon',
                'Redundancy': 'Multiple replicas, auto-reconnect',
                'Firewall': 'No inbound rules required',
                'Deployment': 'Cloud + on-prem agent',
              },
              children: [],
            },
          ],
        },
        // -- Browser Isolation -------------------------------------------
        {
          nodeId: 'cloudflare-browser-isolation-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Browser Isolation',
          nameKo: '브라우저 격리',
          description:
            'Remote browser isolation executing web code away from endpoints without sacrificing performance',
          descriptionKo:
            '성능 저하 없이 엔드포인트에서 떨어진 곳에서 웹 코드를 실행하는 원격 브라우저 격리',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/browser-isolation/',
          infraNodeTypes: ['sase-gateway'],
          architectureRole: 'Remote Browser Isolation / Endpoint Protection',
          architectureRoleKo: '원격 브라우저 격리 / 엔드포인트 보호',
          recommendedFor: [
            'Zero-day browser exploit prevention',
            'Risky website safe access',
            'Data loss prevention via controlled rendering',
          ],
          recommendedForKo: [
            '제로데이 브라우저 익스플로잇 방지',
            '위험 웹사이트 안전 접근',
            '제어된 렌더링을 통한 데이터 유출 방지',
          ],
          securityCapabilities: [
            'Remote code execution isolation',
            'Copy/paste/print controls',
            'File download scanning',
            'Keyboard input protection',
          ],
          children: [
            {
              nodeId: 'cloudflare-browser-isolation',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Browser Isolation',
              nameKo: 'Cloudflare 브라우저 격리',
              description:
                'Remote browser isolation running web content on Cloudflare edge, streaming only safe rendering data to endpoints',
              descriptionKo:
                'Cloudflare 에지에서 웹 콘텐츠를 실행하고 안전한 렌더링 데이터만 엔드포인트로 스트리밍하는 원격 브라우저 격리',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/browser-isolation/',
              infraNodeTypes: ['sase-gateway'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Remote Browser Isolation / Endpoint Protection',
              architectureRoleKo: '원격 브라우저 격리 / 엔드포인트 보호',
              recommendedFor: [
                'High-risk user group web access isolation',
                'Phishing link safe rendering',
                'Contractor/BYOD browser security',
              ],
              recommendedForKo: [
                '고위험 사용자 그룹 웹 접근 격리',
                '피싱 링크 안전 렌더링',
                '외주업체/BYOD 브라우저 보안',
              ],
              securityCapabilities: [
                'Remote code execution isolation',
                'Copy/paste/print/download controls',
                'Keyboard input isolation',
                'Gateway integration for policy-based isolation',
              ],
              specs: {
                'Rendering': 'Network Vector Rendering (NVR)',
                'Latency': 'Near-native browsing experience',
                'Controls': 'Copy, paste, print, download, upload',
                'Integration': 'Gateway policies, Access',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- CASB --------------------------------------------------------
        {
          nodeId: 'cloudflare-casb-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloudflare CASB',
          nameKo: 'Cloudflare CASB',
          description:
            'Cloud Access Security Broker scanning SaaS apps and cloud environments for security risks and misconfigurations',
          descriptionKo:
            'SaaS 앱 및 클라우드 환경의 보안 위험과 잘못된 구성을 스캔하는 클라우드 접근 보안 중개자',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/casb/',
          infraNodeTypes: ['casb'],
          architectureRole: 'SaaS Security / Cloud Posture Management',
          architectureRoleKo: 'SaaS 보안 / 클라우드 포스처 관리',
          recommendedFor: [
            'SaaS application security posture monitoring',
            'Shadow IT discovery and control',
            'Cloud misconfiguration detection',
          ],
          recommendedForKo: [
            'SaaS 애플리케이션 보안 포스처 모니터링',
            '섀도우 IT 발견 및 제어',
            '클라우드 잘못된 구성 탐지',
          ],
          securityCapabilities: [
            'SaaS posture scanning',
            'API-driven SaaS integration',
            'Misconfiguration detection',
            'Shadow IT discovery',
          ],
          children: [
            {
              nodeId: 'cloudflare-casb',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare CASB',
              nameKo: 'Cloudflare CASB',
              description:
                'API-driven CASB scanning SaaS apps for security risks, posture issues, and shadow IT with automated remediation',
              descriptionKo:
                'SaaS 앱의 보안 위험, 포스처 이슈, 섀도우 IT를 자동 치료와 함께 스캔하는 API 기반 CASB',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/casb/',
              infraNodeTypes: ['casb'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'SaaS Security / Cloud Posture Management',
              architectureRoleKo: 'SaaS 보안 / 클라우드 포스처 관리',
              recommendedFor: [
                'SaaS misconfiguration and posture monitoring',
                'Sensitive data exposure detection in cloud apps',
                'Shadow IT discovery and risk scoring',
              ],
              recommendedForKo: [
                'SaaS 잘못된 구성 및 포스처 모니터링',
                '클라우드 앱의 민감 데이터 노출 탐지',
                '섀도우 IT 발견 및 위험 점수화',
              ],
              securityCapabilities: [
                'API-based SaaS scanning',
                'Posture findings and remediation',
                'Shadow IT risk scoring',
                'Data sharing and exposure detection',
              ],
              specs: {
                'Integration': 'API-based (Microsoft 365, Google, Salesforce, etc.)',
                'Scanning': 'Posture, sharing, misconfig, data exposure',
                'Remediation': 'Automated policy actions',
                'Shadow IT': 'Discovery and risk scoring',
                'Deployment': 'Cloud (API-based)',
              },
              children: [],
            },
          ],
        },
        // -- DLP ---------------------------------------------------------
        {
          nodeId: 'cloudflare-dlp-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloudflare DLP',
          nameKo: 'Cloudflare DLP',
          description:
            'Data Loss Prevention inspecting web, SaaS, email, and cloud traffic for sensitive data with AI-driven analysis',
          descriptionKo:
            'AI 기반 분석으로 웹, SaaS, 이메일, 클라우드 트래픽의 민감 데이터를 검사하는 데이터 유출 방지',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/dlp/',
          infraNodeTypes: ['dlp'],
          architectureRole: 'Data Protection / Exfiltration Prevention',
          architectureRoleKo: '데이터 보호 / 유출 방지',
          recommendedFor: [
            'PII and regulated data protection',
            'Intellectual property exfiltration prevention',
            'GenAI data leakage control',
          ],
          recommendedForKo: [
            'PII 및 규제 데이터 보호',
            '지적 재산 유출 방지',
            'GenAI 데이터 누출 제어',
          ],
          securityCapabilities: [
            'PII/PHI/financial data detection',
            'Custom detection patterns',
            'AI-driven context analysis',
            'Microsoft Purview label integration',
            'GenAI prompt/response scanning',
          ],
          children: [
            {
              nodeId: 'cloudflare-dlp',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare DLP',
              nameKo: 'Cloudflare DLP',
              description:
                'Unified DLP across web, SaaS, email, and cloud storage with AI-driven detection, Purview integration, and GenAI controls',
              descriptionKo:
                'AI 기반 탐지, Purview 통합, GenAI 제어가 포함된 웹, SaaS, 이메일, 클라우드 스토리지 전반의 통합 DLP',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/dlp/',
              infraNodeTypes: ['dlp'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Data Protection / Exfiltration Prevention',
              architectureRoleKo: '데이터 보호 / 유출 방지',
              recommendedFor: [
                'Cross-channel sensitive data protection (web, email, SaaS)',
                'Regulatory compliance (PCI-DSS, HIPAA, GDPR)',
                'GenAI prompt and response data leakage prevention',
              ],
              recommendedForKo: [
                '크로스 채널 민감 데이터 보호 (웹, 이메일, SaaS)',
                '규제 준수 (PCI-DSS, HIPAA, GDPR)',
                'GenAI 프롬프트 및 응답 데이터 유출 방지',
              ],
              securityCapabilities: [
                'PII, PHI, financial data detection',
                'Custom regex and keyword patterns',
                'AI/ML context analysis',
                'Microsoft Purview sensitivity labels',
                'Document and image scanning',
                'GenAI prompt/response inspection',
              ],
              specs: {
                'Channels': 'Web, SaaS, email, cloud storage (S3, GCS)',
                'Detection': 'Predefined, custom, AI-driven',
                'Labels': 'Microsoft Purview integration',
                'GenAI': 'Prompt and response scanning',
                'Audit': 'Compliance logging and reporting',
                'Deployment': 'Cloud (SASE inline)',
              },
              children: [],
            },
          ],
        },
        // -- Email Security ----------------------------------------------
        {
          nodeId: 'cloudflare-email-security-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Email Security',
          nameKo: '이메일 보안',
          description:
            'Preemptive email threat protection against phishing, BEC, and supply chain attacks (formerly Area 1)',
          descriptionKo:
            '피싱, BEC, 공급망 공격에 대한 선제적 이메일 위협 방어 (구 Area 1)',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/email-security/',
          infraNodeTypes: ['sase-gateway'],
          architectureRole: 'Email Security / Phishing Protection',
          architectureRoleKo: '이메일 보안 / 피싱 보호',
          recommendedFor: [
            'Advanced phishing and BEC prevention',
            'Email supply chain attack detection',
            'Microsoft 365 and Google Workspace protection',
          ],
          recommendedForKo: [
            '고급 피싱 및 BEC 방지',
            '이메일 공급망 공격 탐지',
            'Microsoft 365 및 Google Workspace 보호',
          ],
          securityCapabilities: [
            'Phishing detection (URL, attachment, text)',
            'Business Email Compromise (BEC) prevention',
            'Email supply chain attack detection',
            'Sender reputation and SPF/DKIM/DMARC',
          ],
          children: [
            {
              nodeId: 'cloudflare-email-security',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Email Security',
              nameKo: 'Cloudflare 이메일 보안',
              description:
                'Preemptive email threat protection against phishing, BEC, and supply chain attacks with ML-driven detection',
              descriptionKo:
                'ML 기반 탐지로 피싱, BEC, 공급망 공격에 대한 선제적 이메일 위협 방어',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/email-security/',
              infraNodeTypes: ['sase-gateway'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Email Security / Phishing Protection',
              architectureRoleKo: '이메일 보안 / 피싱 보호',
              recommendedFor: [
                'Enterprise phishing and BEC prevention',
                'Email-borne malware and ransomware blocking',
                'Office 365/Google Workspace email protection',
              ],
              recommendedForKo: [
                '엔터프라이즈 피싱 및 BEC 방지',
                '이메일 기반 멀웨어 및 랜섬웨어 차단',
                'Office 365/Google Workspace 이메일 보호',
              ],
              securityCapabilities: [
                'ML-driven phishing detection',
                'BEC impersonation detection',
                'Supply chain attack alerting',
                'URL and attachment detonation',
                'SPF/DKIM/DMARC enforcement',
              ],
              specs: {
                'Detection': 'ML-powered preemptive scanning',
                'Coverage': 'Phishing, BEC, supply chain, malware',
                'Integration': 'Microsoft 365, Google Workspace',
                'Deployment Modes': 'Inline (MX), API, journaling',
                'Deployment': 'Cloud (email gateway)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. Developer Platform
    // =====================================================================
    {
      nodeId: 'cloudflare-developer-platform',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Developer Platform',
      nameKo: '개발자 플랫폼',
      description:
        'Edge compute, serverless storage, and hosting platform built on Cloudflare global network',
      descriptionKo:
        'Cloudflare 글로벌 네트워크 기반의 에지 컴퓨트, 서버리스 스토리지, 호스팅 플랫폼',
      sourceUrl: 'https://www.cloudflare.com/developer-platform/products/',
      children: [
        // -- Workers (Compute) -------------------------------------------
        {
          nodeId: 'cloudflare-workers-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Workers',
          nameKo: 'Workers',
          description:
            'Serverless edge compute platform using V8 isolates with zero cold starts across 330+ global data centers',
          descriptionKo:
            '330개 이상 글로벌 데이터 센터에서 V8 아이솔레이트를 사용하는 제로 콜드 스타트 서버리스 에지 컴퓨트 플랫폼',
          sourceUrl: 'https://www.cloudflare.com/developer-platform/workers/',
          architectureRole: 'Edge Compute / Serverless Functions',
          architectureRoleKo: '에지 컴퓨트 / 서버리스 함수',
          recommendedFor: [
            'Serverless API and function deployment',
            'Edge-side rendering and compute',
            'AI agent and inference hosting',
          ],
          recommendedForKo: [
            '서버리스 API 및 함수 배포',
            '에지 사이드 렌더링 및 컴퓨트',
            'AI 에이전트 및 추론 호스팅',
          ],
          children: [
            {
              nodeId: 'cloudflare-workers',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Workers',
              nameKo: 'Cloudflare Workers',
              description:
                'Serverless compute platform using V8 isolates with virtually zero cold starts, deployed globally across 330+ data centers',
              descriptionKo:
                'V8 아이솔레이트를 사용하여 실질적으로 제로 콜드 스타트, 330개 이상 데이터 센터에 글로벌 배포되는 서버리스 컴퓨트 플랫폼',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/workers/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Edge Compute / Serverless Functions',
              architectureRoleKo: '에지 컴퓨트 / 서버리스 함수',
              recommendedFor: [
                'Globally distributed serverless APIs',
                'Edge-side rendering (React Router, Next.js)',
                'AI agent hosting and inference at edge',
              ],
              recommendedForKo: [
                '글로벌 분산 서버리스 API',
                '에지 사이드 렌더링 (React Router, Next.js)',
                '에지에서의 AI 에이전트 호스팅 및 추론',
              ],
              specs: {
                'Runtime': 'V8 isolates (not containers)',
                'Cold Start': 'Virtually zero',
                'Global PoPs': '330+ data centers',
                'Network Capacity': '477 Tbps',
                'Languages': 'JavaScript, TypeScript, Python, Rust, C/C++ (WASM)',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-workers-kv',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Workers KV',
              nameKo: 'Workers KV',
              description:
                'Globally distributed key-value storage with data replicated across 330+ locations for low-latency reads',
              descriptionKo:
                '330개 이상 위치에 데이터가 복제되어 저지연 읽기를 제공하는 글로벌 분산 키-값 스토리지',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/products/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Edge Key-Value Store',
              architectureRoleKo: '에지 키-값 저장소',
              recommendedFor: [
                'Configuration and feature flag storage at edge',
                'Session and authentication token caching',
                'Global low-latency metadata lookups',
              ],
              recommendedForKo: [
                '에지에서의 구성 및 기능 플래그 저장',
                '세션 및 인증 토큰 캐싱',
                '글로벌 저지연 메타데이터 조회',
              ],
              specs: {
                'Data Model': 'Key-value',
                'Consistency': 'Eventually consistent',
                'Replication': '330+ global locations',
                'Max Value Size': '25 MiB',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-durable-objects',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Durable Objects',
              nameKo: 'Durable Objects',
              description:
                'Stateful serverless compute with strong consistency, enabling real-time collaborative and interactive applications',
              descriptionKo:
                '강한 일관성을 갖춘 상태 유지 서버리스 컴퓨트, 실시간 협업 및 인터랙티브 애플리케이션 지원',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/products/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Stateful Edge Compute / Real-Time Coordination',
              architectureRoleKo: '상태 유지 에지 컴퓨트 / 실시간 조정',
              recommendedFor: [
                'Real-time collaborative applications (chat, gaming)',
                'Stateful workflow orchestration at edge',
                'Distributed locking and coordination',
              ],
              recommendedForKo: [
                '실시간 협업 애플리케이션 (채팅, 게임)',
                '에지에서의 상태 유지 워크플로 오케스트레이션',
                '분산 잠금 및 조정',
              ],
              specs: {
                'Consistency': 'Strong (single-leader)',
                'Storage': 'Transactional, durable',
                'WebSocket': 'Native Hibernatable WebSockets',
                'Alarms': 'Scheduled wake-up support',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- Storage -----------------------------------------------------
        {
          nodeId: 'cloudflare-storage-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Storage',
          nameKo: '스토리지',
          description:
            'S3-compatible object storage and serverless SQL database with zero egress fees',
          descriptionKo:
            '제로 이그레스 비용의 S3 호환 오브젝트 스토리지 및 서버리스 SQL 데이터베이스',
          sourceUrl: 'https://www.cloudflare.com/developer-platform/products/',
          infraNodeTypes: ['object-storage'],
          architectureRole: 'Cloud Storage / Serverless Database',
          architectureRoleKo: '클라우드 스토리지 / 서버리스 데이터베이스',
          recommendedFor: [
            'Cost-effective object storage without egress fees',
            'Serverless SQL database for edge applications',
            'Multi-cloud data storage',
          ],
          recommendedForKo: [
            '이그레스 비용 없는 비용 효율적 오브젝트 스토리지',
            '에지 애플리케이션용 서버리스 SQL 데이터베이스',
            '멀티 클라우드 데이터 스토리지',
          ],
          children: [
            {
              nodeId: 'cloudflare-r2',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'R2 Object Storage',
              nameKo: 'R2 오브젝트 스토리지',
              description:
                'S3-compatible object storage with zero egress fees, Workers integration, and standard/infrequent access tiers',
              descriptionKo:
                '제로 이그레스 비용, Workers 통합, 표준/비빈번 접근 티어를 갖춘 S3 호환 오브젝트 스토리지',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/r2/',
              infraNodeTypes: ['object-storage'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Object Storage / Data Lake',
              architectureRoleKo: '오브젝트 스토리지 / 데이터 레이크',
              recommendedFor: [
                'Zero-egress multi-cloud object storage',
                'AI/ML dataset and model checkpoint storage',
                'Apache Iceberg data lake analytics',
                'Media asset storage and delivery',
              ],
              recommendedForKo: [
                '제로 이그레스 멀티 클라우드 오브젝트 스토리지',
                'AI/ML 데이터셋 및 모델 체크포인트 저장',
                'Apache Iceberg 데이터 레이크 분석',
                '미디어 자산 저장 및 전송',
              ],
              specs: {
                'API': 'S3-compatible',
                'Egress Fees': '$0 (zero)',
                'Standard Storage': '$0.015/GB-month',
                'Infrequent Access': '$0.01/GB-month',
                'Free Tier': '10 GB/month',
                'Workers Integration': 'Native',
                'Deployment': 'Cloud (globally distributed)',
              },
              children: [],
            },
            {
              nodeId: 'cloudflare-d1',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'D1',
              nameKo: 'D1',
              description:
                'Serverless SQL database with point-in-time recovery, built natively for Workers edge compute',
              descriptionKo:
                'Workers 에지 컴퓨트를 위해 네이티브로 구축된 포인트인타임 복구 기능의 서버리스 SQL 데이터베이스',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/products/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Serverless SQL Database',
              architectureRoleKo: '서버리스 SQL 데이터베이스',
              recommendedFor: [
                'Edge application relational data storage',
                'Serverless backend with SQL queries',
                'Applications requiring point-in-time recovery',
              ],
              recommendedForKo: [
                '에지 애플리케이션 관계형 데이터 저장',
                'SQL 쿼리를 사용하는 서버리스 백엔드',
                '포인트인타임 복구가 필요한 애플리케이션',
              ],
              specs: {
                'Engine': 'SQLite-based',
                'Recovery': 'Point-in-time recovery',
                'Workers Integration': 'Native binding',
                'Replication': 'Read replicas (global)',
                'Deployment': 'Cloud (serverless)',
              },
              children: [],
            },
          ],
        },
        // -- Pages -------------------------------------------------------
        {
          nodeId: 'cloudflare-pages-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Pages',
          nameKo: 'Pages',
          description:
            'Full-stack JAMstack and framework hosting with Git integration and global deployment',
          descriptionKo:
            'Git 통합 및 글로벌 배포가 포함된 풀스택 JAMstack 및 프레임워크 호스팅',
          sourceUrl: 'https://www.cloudflare.com/developer-platform/pages/',
          architectureRole: 'Static / Full-Stack Hosting',
          architectureRoleKo: '정적 / 풀스택 호스팅',
          recommendedFor: [
            'JAMstack website deployment',
            'Framework-based full-stack applications',
            'CI/CD integrated static hosting',
          ],
          recommendedForKo: [
            'JAMstack 웹사이트 배포',
            '프레임워크 기반 풀스택 애플리케이션',
            'CI/CD 통합 정적 호스팅',
          ],
          children: [
            {
              nodeId: 'cloudflare-pages',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Pages',
              nameKo: 'Cloudflare Pages',
              description:
                'Full-stack web application hosting with Git-based CI/CD, framework support, and global edge deployment',
              descriptionKo:
                'Git 기반 CI/CD, 프레임워크 지원, 글로벌 에지 배포가 포함된 풀스택 웹 애플리케이션 호스팅',
              sourceUrl: 'https://www.cloudflare.com/developer-platform/pages/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Static / Full-Stack Hosting',
              architectureRoleKo: '정적 / 풀스택 호스팅',
              recommendedFor: [
                'Static website and JAMstack hosting',
                'Full-stack app deployment with Workers',
                'Git-integrated CI/CD workflow',
              ],
              recommendedForKo: [
                '정적 웹사이트 및 JAMstack 호스팅',
                'Workers와 함께하는 풀스택 앱 배포',
                'Git 통합 CI/CD 워크플로',
              ],
              specs: {
                'Frameworks': 'React, Next.js, Astro, SvelteKit, and more',
                'CI/CD': 'Git-based (GitHub, GitLab)',
                'Preview': 'Automatic preview deployments per branch',
                'Functions': 'Workers Functions included',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Network Services
    // =====================================================================
    {
      nodeId: 'cloudflare-network-services',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Services',
      nameKo: '네트워크 서비스',
      description:
        'Cloud-delivered WAN, firewall, device agent, and interconnect services replacing legacy network hardware',
      descriptionKo:
        '레거시 네트워크 하드웨어를 대체하는 클라우드 전송 WAN, 방화벽, 디바이스 에이전트, 인터커넥트 서비스',
      sourceUrl: 'https://www.cloudflare.com/network-services/',
      infraNodeTypes: ['sd-wan', 'firewall'],
      children: [
        // -- Magic WAN ---------------------------------------------------
        {
          nodeId: 'cloudflare-magic-wan-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Magic WAN',
          nameKo: 'Magic WAN',
          description:
            'Cloud-delivered SD-WAN connecting branches, headquarters, data centers, and cloud VPCs via Cloudflare network',
          descriptionKo:
            'Cloudflare 네트워크를 통해 지사, 본사, 데이터센터, 클라우드 VPC를 연결하는 클라우드 전송 SD-WAN',
          sourceUrl: 'https://www.cloudflare.com/magic-wan/',
          infraNodeTypes: ['sd-wan'],
          architectureRole: 'SD-WAN / WAN Connectivity',
          architectureRoleKo: 'SD-WAN / WAN 연결',
          recommendedFor: [
            'MPLS replacement with cloud-delivered WAN',
            'Branch-to-branch and multi-cloud connectivity',
            'SD-WAN with integrated security',
          ],
          recommendedForKo: [
            '클라우드 전송 WAN을 통한 MPLS 대체',
            '지사 간 및 멀티 클라우드 연결',
            '통합 보안이 포함된 SD-WAN',
          ],
          supportedProtocols: [
            'IPsec',
            'GRE',
            'WireGuard',
            'Anycast',
          ],
          haFeatures: [
            'Zero-touch configuration',
            'Automatic failover',
            'Multiple tunnel redundancy',
            'Cloudflare Anycast backbone',
          ],
          children: [
            {
              nodeId: 'cloudflare-magic-wan',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Magic WAN',
              nameKo: 'Magic WAN',
              description:
                'Cloud-delivered SD-WAN replacing MPLS with branch-to-branch, multi-cloud, and internet breakout connectivity',
              descriptionKo:
                '지사 간, 멀티 클라우드, 인터넷 브레이크아웃 연결로 MPLS를 대체하는 클라우드 전송 SD-WAN',
              sourceUrl: 'https://www.cloudflare.com/magic-wan/',
              infraNodeTypes: ['sd-wan'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'SD-WAN / WAN Connectivity',
              architectureRoleKo: 'SD-WAN / WAN 연결',
              recommendedFor: [
                'Enterprise MPLS-to-cloud WAN migration',
                'Multi-site branch connectivity',
                'Hybrid and multi-cloud network integration',
              ],
              recommendedForKo: [
                '엔터프라이즈 MPLS-클라우드 WAN 마이그레이션',
                '멀티 사이트 지사 연결',
                '하이브리드 및 멀티 클라우드 네트워크 통합',
              ],
              specs: {
                'Connectivity': 'Branch, HQ, DC, cloud VPC',
                'Tunnels': 'IPsec, GRE, WireGuard',
                'Onramp': 'Magic WAN Connector (physical/virtual)',
                'Configuration': 'Zero-touch deployment',
                'Security': 'Integrated FW, DDoS, ZTNA',
                'Deployment': 'Cloud (Anycast backbone)',
              },
              children: [],
            },
          ],
        },
        // -- Magic Firewall ----------------------------------------------
        {
          nodeId: 'cloudflare-magic-firewall-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Magic Firewall',
          nameKo: 'Magic Firewall',
          description:
            'Cloud-native firewall-as-a-service enforcing consistent network security policies across the entire WAN',
          descriptionKo:
            '전체 WAN에서 일관된 네트워크 보안 정책을 적용하는 클라우드 네이티브 서비스형 방화벽',
          sourceUrl: 'https://www.cloudflare.com/network-services/',
          infraNodeTypes: ['firewall'],
          architectureRole: 'Cloud Firewall / Network Policy Enforcement',
          architectureRoleKo: '클라우드 방화벽 / 네트워크 정책 적용',
          recommendedFor: [
            'Distributed network firewall without appliances',
            'Centralized WAN security policy management',
            'Zero trust network segmentation',
          ],
          recommendedForKo: [
            '어플라이언스 없는 분산 네트워크 방화벽',
            '중앙 집중식 WAN 보안 정책 관리',
            '제로 트러스트 네트워크 세그멘테이션',
          ],
          supportedProtocols: ['TCP', 'UDP', 'ICMP', 'GRE', 'IPsec'],
          haFeatures: [
            'Cloud-native with no single point of failure',
            'Consistent policy across all WAN edges',
            'No traffic backhauling',
          ],
          securityCapabilities: [
            'Network-layer packet filtering',
            'IP, port, and protocol rules',
            'Centralized policy management',
            'Zero trust enforcement',
          ],
          children: [
            {
              nodeId: 'cloudflare-magic-firewall',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Magic Firewall',
              nameKo: 'Magic Firewall',
              description:
                'Cloud-native network firewall enforcing consistent security policies across WAN without appliances or traffic backhauling',
              descriptionKo:
                '어플라이언스나 트래픽 백홀 없이 WAN 전반에 일관된 보안 정책을 적용하는 클라우드 네이티브 네트워크 방화벽',
              sourceUrl: 'https://www.cloudflare.com/network-services/',
              infraNodeTypes: ['firewall'],
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Cloud Firewall / Network Policy Enforcement',
              architectureRoleKo: '클라우드 방화벽 / 네트워크 정책 적용',
              recommendedFor: [
                'Replacing on-prem network firewalls with cloud FWaaS',
                'Centralized WAN-wide security policy enforcement',
                'Zero trust micro-segmentation',
              ],
              recommendedForKo: [
                '온프레미스 네트워크 방화벽을 클라우드 FWaaS로 대체',
                '중앙 집중식 WAN 전체 보안 정책 적용',
                '제로 트러스트 마이크로 세그멘테이션',
              ],
              securityCapabilities: [
                'Network-layer packet filtering',
                'IP / port / protocol rules',
                'Centralized policy dashboard',
                'No appliance maintenance',
              ],
              specs: {
                'Type': 'Firewall-as-a-Service (FWaaS)',
                'Filtering': 'L3/L4 packet inspection',
                'Policy': 'Centralized, WAN-wide',
                'Backhauling': 'Not required',
                'Integration': 'Magic WAN, Magic Transit',
                'Deployment': 'Cloud (global edge)',
              },
              children: [],
            },
          ],
        },
        // -- WARP --------------------------------------------------------
        {
          nodeId: 'cloudflare-warp-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'WARP',
          nameKo: 'WARP',
          description:
            'Device agent/client connecting endpoints to Cloudflare Zero Trust network with WireGuard-based encrypted tunnel',
          descriptionKo:
            'WireGuard 기반 암호화 터널로 엔드포인트를 Cloudflare 제로 트러스트 네트워크에 연결하는 디바이스 에이전트/클라이언트',
          sourceUrl: 'https://www.cloudflare.com/products/zero-trust/warp/',
          architectureRole: 'Device Agent / Endpoint Connector',
          architectureRoleKo: '디바이스 에이전트 / 엔드포인트 커넥터',
          recommendedFor: [
            'Endpoint onboarding to Zero Trust network',
            'Secure roaming user connectivity',
            'Device posture assessment and enforcement',
          ],
          recommendedForKo: [
            '제로 트러스트 네트워크에 엔드포인트 온보딩',
            '보안 로밍 사용자 연결',
            '디바이스 포스처 평가 및 적용',
          ],
          supportedProtocols: ['WireGuard', 'MASQUE', 'HTTPS'],
          children: [
            {
              nodeId: 'cloudflare-warp',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare WARP',
              nameKo: 'Cloudflare WARP',
              description:
                'Cross-platform device agent connecting endpoints to Cloudflare network via WireGuard tunnel for Zero Trust enforcement',
              descriptionKo:
                'WireGuard 터널을 통해 엔드포인트를 Cloudflare 네트워크에 연결하여 제로 트러스트를 적용하는 크로스 플랫폼 디바이스 에이전트',
              sourceUrl: 'https://www.cloudflare.com/products/zero-trust/warp/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Device Agent / Endpoint Connector',
              architectureRoleKo: '디바이스 에이전트 / 엔드포인트 커넥터',
              recommendedFor: [
                'Zero Trust device enrollment and connectivity',
                'Remote worker secure internet and app access',
                'Device posture checks for access policies',
              ],
              recommendedForKo: [
                '제로 트러스트 디바이스 등록 및 연결',
                '원격 근무자 보안 인터넷 및 앱 접근',
                '접근 정책을 위한 디바이스 포스처 검사',
              ],
              specs: {
                'Tunnel Protocol': 'WireGuard / MASQUE',
                'Platforms': 'Windows, macOS, Linux, iOS, Android, ChromeOS',
                'Split Tunnel': 'Include/exclude modes',
                'Device Posture': 'OS, disk encryption, firewall, etc.',
                'MDM': 'Managed deployment supported',
                'Deployment': 'Endpoint agent + cloud',
              },
              children: [],
            },
          ],
        },
        // -- Network Interconnect ----------------------------------------
        {
          nodeId: 'cloudflare-network-interconnect-line',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Network Interconnect',
          nameKo: '네트워크 인터커넥트',
          description:
            'Direct physical or virtual peering connections from on-prem networks to Cloudflare for enhanced reliability and security',
          descriptionKo:
            '향상된 안정성과 보안을 위해 온프레미스 네트워크에서 Cloudflare로의 직접 물리/가상 피어링 연결',
          sourceUrl: 'https://www.cloudflare.com/network-services/',
          architectureRole: 'Direct Interconnect / Private Peering',
          architectureRoleKo: '직접 인터커넥트 / 프라이빗 피어링',
          recommendedFor: [
            'High-performance direct connectivity to Cloudflare',
            'Dedicated bandwidth for Magic Transit or Magic WAN',
            'Latency-sensitive enterprise workloads',
          ],
          recommendedForKo: [
            'Cloudflare로의 고성능 직접 연결',
            'Magic Transit 또는 Magic WAN을 위한 전용 대역폭',
            '지연 시간에 민감한 엔터프라이즈 워크로드',
          ],
          supportedProtocols: ['BGP', 'PNI', 'GRE', 'IPsec'],
          children: [
            {
              nodeId: 'cloudflare-network-interconnect',
              depth: 2,
              depthLabel: 'Service',
              depthLabelKo: '서비스',
              name: 'Cloudflare Network Interconnect',
              nameKo: 'Cloudflare 네트워크 인터커넥트',
              description:
                'Direct physical (PNI) or virtual peering to Cloudflare network for dedicated, low-latency, and encrypted connectivity',
              descriptionKo:
                '전용, 저지연, 암호화된 연결을 위한 Cloudflare 네트워크로의 직접 물리(PNI) 또는 가상 피어링',
              sourceUrl: 'https://www.cloudflare.com/network-services/',
              lifecycle: 'active',
              formFactor: 'cloud',
              licensingModel: 'subscription',
              architectureRole: 'Direct Interconnect / Private Peering',
              architectureRoleKo: '직접 인터커넥트 / 프라이빗 피어링',
              recommendedFor: [
                'Dedicated private connectivity to Cloudflare',
                'Enterprise Magic Transit return path',
                'Low-latency peering for latency-critical apps',
              ],
              recommendedForKo: [
                'Cloudflare로의 전용 프라이빗 연결',
                '엔터프라이즈 Magic Transit 리턴 경로',
                '지연 시간이 중요한 앱을 위한 저지연 피어링',
              ],
              specs: {
                'Connection Types': 'PNI (physical), virtual interconnect',
                'Protocols': 'BGP, GRE, IPsec',
                'Bandwidth': 'Dedicated (10G/100G options)',
                'Encryption': 'End-to-end encrypted',
                'Locations': 'Major colocation facilities globally',
                'Deployment': 'Hybrid (on-prem + cloud)',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
