/**
 * F5 Networks -- Full Product Catalog
 *
 * Hierarchical product tree covering Application Delivery & Security,
 * NGINX, Distributed Cloud Services, and Security categories.
 *
 * Data sourced from https://www.f5.com/products
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// F5 Networks Product Catalog
// ---------------------------------------------------------------------------

export const f5Catalog: VendorCatalog = {
  vendorId: 'f5-networks',
  vendorName: 'F5 Networks',
  vendorNameKo: 'F5 네트웍스',
  headquarters: 'Seattle, WA, USA',
  website: 'https://www.f5.com',
  productPageUrl: 'https://www.f5.com/products',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.f5.com/products',
  // stats will be computed at the bottom of the file
  stats: { totalProducts: 0, maxDepth: 0, categoriesCount: 0 },
  products: [
    // =====================================================================
    // 1. Application Delivery & Security
    // =====================================================================
    {
      nodeId: 'f5-app-delivery-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Application Delivery & Security',
      nameKo: '애플리케이션 딜리버리 및 보안',
      description:
        'Hardware and software ADC platforms for load balancing, traffic management, and application security across on-premises, cloud, and hybrid environments',
      descriptionKo:
        '온프레미스, 클라우드 및 하이브리드 환경에서의 부하 분산, 트래픽 관리 및 애플리케이션 보안을 위한 하드웨어/소프트웨어 ADC 플랫폼',
      sourceUrl: 'https://www.f5.com/products/big-ip',
      infraNodeTypes: ['load-balancer', 'waf'],
      children: [
        // -----------------------------------------------------------------
        // BIG-IP
        // -----------------------------------------------------------------
        {
          nodeId: 'f5-bigip',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP',
          nameKo: 'BIG-IP',
          description:
            'Industry-leading application delivery controller platform with over 25 years of innovation, providing load balancing, SSL offloading, traffic management, WAF, and DDoS protection',
          descriptionKo:
            '25년 이상의 혁신을 가진 업계 최고의 ADC 플랫폼으로 부하 분산, SSL 오프로딩, 트래픽 관리, WAF 및 DDoS 보호 제공',
          sourceUrl: 'https://www.f5.com/products/big-ip',
          infraNodeTypes: ['load-balancer', 'waf'],
          architectureRole: 'Data Center / DMZ / Cloud Edge ADC',
          architectureRoleKo: '데이터센터 / DMZ / 클라우드 에지 ADC',
          recommendedFor: [
            'Enterprise data center application delivery',
            'Multi-cloud load balancing and traffic management',
            'Web application firewall and DDoS protection',
            'SSL/TLS offloading and orchestration',
            'DNS hyperscale and GSLB',
          ],
          recommendedForKo: [
            '엔터프라이즈 데이터센터 애플리케이션 딜리버리',
            '멀티클라우드 부하 분산 및 트래픽 관리',
            '웹 애플리케이션 방화벽 및 DDoS 보호',
            'SSL/TLS 오프로딩 및 오케스트레이션',
            'DNS 하이퍼스케일 및 GSLB',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'TCP',
            'UDP',
            'SSL/TLS',
            'HTTP/2',
            'HTTP/3',
            'WebSocket',
            'gRPC',
            'DNS',
            'SIP',
            'FTP',
            'SMTP',
            'DIAMETER',
            'RADIUS',
            'LDAP',
            'MQTT',
          ],
          haFeatures: [
            'Active-Active clustering',
            'Active-Standby HA',
            'Connection mirroring',
            'Config sync',
            'Auto-failover',
            'Network failover',
            'Device trust groups',
            'Traffic group failover',
          ],
          securityCapabilities: [
            'Advanced WAF (OWASP Top 10)',
            'L7 DDoS protection',
            'Bot defense',
            'SSL/TLS inspection and orchestration',
            'IP intelligence',
            'Credential theft protection',
            'API security (REST, GraphQL, gRPC)',
            'iRules traffic programmability',
            'Access policy management (APM)',
            'Network firewall (AFM)',
          ],
          children: [
            // ── BIG-IP iSeries ──
            {
              nodeId: 'f5-bigip-i2600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i2600',
              nameKo: 'BIG-IP i2600',
              description:
                'Entry-level iSeries ADC appliance for small deployments with 10 Gbps L4 throughput and 8 GbE interfaces',
              descriptionKo:
                '10 Gbps L4 처리량과 8 GbE 인터페이스를 갖춘 소규모 배포용 엔트리급 iSeries ADC 어플라이언스',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r2600',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '10 Gbps',
              architectureRole: 'Branch / Small Data Center ADC',
              architectureRoleKo: '지사 / 소규모 데이터센터 ADC',
              recommendedFor: [
                'Small branch office application delivery',
                'Entry-level SSL offloading',
                'Small-scale web application load balancing',
              ],
              recommendedForKo: [
                '소규모 지사 애플리케이션 딜리버리',
                '엔트리급 SSL 오프로딩',
                '소규모 웹 애플리케이션 부하 분산',
              ],
              specs: {
                'L4 Throughput': '10 Gbps',
                'L7 Throughput': '5 Gbps',
                'SSL TPS (RSA 2K)': '5,000',
                'Interfaces': '8x 1 GbE',
                'Form Factor': '1 RU',
                'Max Concurrent Connections': '3,000,000',
                'Power Supply': 'Single AC 250W',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i4600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i4600',
              nameKo: 'BIG-IP i4600',
              description:
                'Mid-range iSeries ADC appliance with 20 Gbps L4 throughput and 10 GbE SFP+ interfaces for medium enterprise deployments',
              descriptionKo:
                '20 Gbps L4 처리량과 10 GbE SFP+ 인터페이스를 갖춘 중견 기업 배포용 미드레인지 iSeries ADC 어플라이언스',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r4600',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '20 Gbps',
              architectureRole: 'Medium Data Center ADC',
              architectureRoleKo: '중형 데이터센터 ADC',
              recommendedFor: [
                'Medium enterprise application delivery',
                'SSL offloading with moderate TPS requirements',
                'Multi-application load balancing',
              ],
              recommendedForKo: [
                '중견 기업 애플리케이션 딜리버리',
                '중간 TPS 요구사항의 SSL 오프로딩',
                '멀티 애플리케이션 부하 분산',
              ],
              specs: {
                'L4 Throughput': '20 Gbps',
                'L7 Throughput': '10 Gbps',
                'SSL TPS (RSA 2K)': '10,000',
                'Interfaces': '8x 1/10 GbE SFP+',
                'Form Factor': '1 RU',
                'Max Concurrent Connections': '8,000,000',
                'Power Supply': 'Dual AC 300W',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i5600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i5600',
              nameKo: 'BIG-IP i5600',
              description:
                'Mid-range iSeries ADC with 40 Gbps L4 throughput, dual 10 GbE SFP+ and 1 GbE management for enterprise data centers',
              descriptionKo:
                '40 Gbps L4 처리량, 듀얼 10 GbE SFP+ 및 1 GbE 관리 포트를 갖춘 엔터프라이즈 데이터센터용 미드레인지 iSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r5600',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '40 Gbps',
              architectureRole: 'Enterprise Data Center ADC',
              architectureRoleKo: '엔터프라이즈 데이터센터 ADC',
              recommendedFor: [
                'Enterprise-grade application delivery',
                'High-volume SSL offloading',
                'Data center north-south traffic management',
              ],
              recommendedForKo: [
                '엔터프라이즈급 애플리케이션 딜리버리',
                '대용량 SSL 오프로딩',
                '데이터센터 남-북 트래픽 관리',
              ],
              specs: {
                'L4 Throughput': '40 Gbps',
                'L7 Throughput': '20 Gbps',
                'SSL TPS (RSA 2K)': '20,000',
                'Interfaces': '16x 1/10 GbE SFP+',
                'Form Factor': '1 RU',
                'Max Concurrent Connections': '16,000,000',
                'Power Supply': 'Dual AC 400W',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i7600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i7600',
              nameKo: 'BIG-IP i7600',
              description:
                'High-performance iSeries ADC with 80 Gbps L4 throughput and 25 GbE interfaces for large enterprise deployments',
              descriptionKo:
                '80 Gbps L4 처리량과 25 GbE 인터페이스를 갖춘 대규모 엔터프라이즈 배포용 고성능 iSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r5900',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '80 Gbps',
              architectureRole: 'Large Enterprise / Data Center ADC',
              architectureRoleKo: '대기업 / 데이터센터 ADC',
              recommendedFor: [
                'Large-scale enterprise application delivery',
                'High-throughput SSL processing',
                'Service provider traffic management',
              ],
              recommendedForKo: [
                '대규모 엔터프라이즈 애플리케이션 딜리버리',
                '고처리량 SSL 프로세싱',
                '서비스 프로바이더 트래픽 관리',
              ],
              specs: {
                'L4 Throughput': '80 Gbps',
                'L7 Throughput': '40 Gbps',
                'SSL TPS (RSA 2K)': '40,000',
                'Interfaces': '8x 25 GbE SFP28 + 8x 10 GbE SFP+',
                'Form Factor': '1 RU',
                'Max Concurrent Connections': '36,000,000',
                'Power Supply': 'Dual AC 500W',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i10600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i10600',
              nameKo: 'BIG-IP i10600',
              description:
                'High-end iSeries ADC with 160 Gbps L4 throughput for data center-scale application delivery and security',
              descriptionKo:
                '데이터센터 규모의 애플리케이션 딜리버리 및 보안을 위한 160 Gbps L4 처리량의 하이엔드 iSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r10600',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '160 Gbps',
              architectureRole: 'Data Center Core ADC',
              architectureRoleKo: '데이터센터 코어 ADC',
              recommendedFor: [
                'Data center core application delivery',
                'High-performance SSL/TLS termination',
                'Large-scale GSLB deployment',
              ],
              recommendedForKo: [
                '데이터센터 코어 애플리케이션 딜리버리',
                '고성능 SSL/TLS 종단',
                '대규모 GSLB 배포',
              ],
              specs: {
                'L4 Throughput': '160 Gbps',
                'L7 Throughput': '80 Gbps',
                'SSL TPS (RSA 2K)': '80,000',
                'Interfaces': '16x 10/25 GbE SFP28 + 4x 40/100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Max Concurrent Connections': '72,000,000',
                'Power Supply': 'Dual AC 850W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i11600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i11600',
              nameKo: 'BIG-IP i11600',
              description:
                'High-end iSeries ADC with FIPS 140-2 certified hardware security module for regulated environments',
              descriptionKo:
                '규제 환경을 위한 FIPS 140-2 인증 하드웨어 보안 모듈을 갖춘 하이엔드 iSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r10900',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '160 Gbps',
              architectureRole: 'Secure Data Center ADC / Government',
              architectureRoleKo: '보안 데이터센터 ADC / 공공기관',
              recommendedFor: [
                'Government and regulated industry deployments',
                'FIPS-compliant SSL/TLS termination',
                'Financial services application delivery',
              ],
              recommendedForKo: [
                '공공기관 및 규제 산업 배포',
                'FIPS 준수 SSL/TLS 종단',
                '금융 서비스 애플리케이션 딜리버리',
              ],
              specs: {
                'L4 Throughput': '160 Gbps',
                'L7 Throughput': '80 Gbps',
                'SSL TPS (RSA 2K)': '80,000',
                'Interfaces': '16x 10/25 GbE SFP28 + 4x 40/100 GbE QSFP28',
                'HSM': 'FIPS 140-2 Level 3',
                'Form Factor': '2 RU',
                'Power Supply': 'Dual AC 850W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-i15600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP i15600',
              nameKo: 'BIG-IP i15600',
              description:
                'Flagship iSeries ADC with 320 Gbps L4 throughput and 100 GbE interfaces for the largest data center deployments',
              descriptionKo:
                '최대 규모 데이터센터 배포를 위한 320 Gbps L4 처리량과 100 GbE 인터페이스의 플래그십 iSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              replacedBy: 'f5-bigip-r12900',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '320 Gbps',
              architectureRole: 'Data Center Core / Service Provider ADC',
              architectureRoleKo: '데이터센터 코어 / 서비스 프로바이더 ADC',
              recommendedFor: [
                'Hyperscale data center application delivery',
                'Service provider traffic management',
                'High-capacity SSL/TLS termination at scale',
              ],
              recommendedForKo: [
                '하이퍼스케일 데이터센터 애플리케이션 딜리버리',
                '서비스 프로바이더 트래픽 관리',
                '대규모 고용량 SSL/TLS 종단',
              ],
              specs: {
                'L4 Throughput': '320 Gbps',
                'L7 Throughput': '150 Gbps',
                'SSL TPS (RSA 2K)': '160,000',
                'Interfaces': '16x 25 GbE SFP28 + 8x 40/100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Max Concurrent Connections': '140,000,000',
                'Power Supply': 'Dual AC 1200W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              children: [],
            },
            // ── BIG-IP rSeries (Next-Generation Hardware) ──
            {
              nodeId: 'f5-bigip-r2600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r2600',
              nameKo: 'BIG-IP r2600',
              description:
                'Entry-level rSeries next-gen ADC appliance running F5OS with multi-tenancy support, 25 Gbps L4 throughput',
              descriptionKo:
                '멀티테넌시를 지원하는 F5OS 기반 엔트리급 rSeries 차세대 ADC 어플라이언스, 25 Gbps L4 처리량',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '25 Gbps',
              architectureRole: 'Branch / Edge Data Center ADC',
              architectureRoleKo: '지사 / 에지 데이터센터 ADC',
              recommendedFor: [
                'Branch office or edge data center ADC',
                'Entry-level multi-tenant application delivery',
                'SSL offloading for small-to-medium workloads',
              ],
              recommendedForKo: [
                '지사 또는 에지 데이터센터 ADC',
                '엔트리급 멀티테넌트 애플리케이션 딜리버리',
                '소중규모 워크로드를 위한 SSL 오프로딩',
              ],
              specs: {
                'L4 Throughput': '25 Gbps',
                'L7 Throughput': '12.5 Gbps',
                'SSL TPS (RSA 2K)': '10,000',
                'Interfaces': '8x 1/10 GbE SFP+ + 2x 25 GbE SFP28',
                'Form Factor': '1 RU',
                'Multi-Tenancy': 'Up to 4 tenants (F5OS)',
                'Max Concurrent Connections': '10,000,000',
                'Power Supply': 'Single AC 300W',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r4600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r4600',
              nameKo: 'BIG-IP r4600',
              description:
                'Mid-range rSeries ADC with 50 Gbps L4 throughput, F5OS multi-tenancy, and enhanced port density for enterprise workloads',
              descriptionKo:
                '50 Gbps L4 처리량, F5OS 멀티테넌시 및 향상된 포트 밀도를 갖춘 엔터프라이즈 워크로드용 미드레인지 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '50 Gbps',
              architectureRole: 'Enterprise Data Center ADC',
              architectureRoleKo: '엔터프라이즈 데이터센터 ADC',
              recommendedFor: [
                'Mid-size enterprise application delivery',
                'Multi-tenant ADC for department isolation',
                'Moderate-scale web application load balancing',
              ],
              recommendedForKo: [
                '중견 기업 애플리케이션 딜리버리',
                '부서 격리를 위한 멀티테넌트 ADC',
                '중규모 웹 애플리케이션 부하 분산',
              ],
              specs: {
                'L4 Throughput': '50 Gbps',
                'L7 Throughput': '25 Gbps',
                'SSL TPS (RSA 2K)': '20,000',
                'Interfaces': '8x 10/25 GbE SFP28 + 2x 40/100 GbE QSFP28',
                'Form Factor': '1 RU',
                'Multi-Tenancy': 'Up to 8 tenants (F5OS)',
                'Max Concurrent Connections': '24,000,000',
                'Power Supply': 'Dual AC 400W redundant',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r5600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r5600',
              nameKo: 'BIG-IP r5600',
              description:
                'Mid-high range rSeries ADC with 75 Gbps L4 throughput and 25/100 GbE interfaces for large enterprise deployments',
              descriptionKo:
                '75 Gbps L4 처리량과 25/100 GbE 인터페이스를 갖춘 대규모 엔터프라이즈 배포용 중상위급 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '75 Gbps',
              architectureRole: 'Large Enterprise Data Center ADC',
              architectureRoleKo: '대규모 엔터프라이즈 데이터센터 ADC',
              recommendedFor: [
                'Large enterprise application delivery',
                'High-volume SSL termination',
                'Data center consolidation with multi-tenancy',
              ],
              recommendedForKo: [
                '대규모 엔터프라이즈 애플리케이션 딜리버리',
                '대용량 SSL 종단',
                '멀티테넌시를 통한 데이터센터 통합',
              ],
              specs: {
                'L4 Throughput': '75 Gbps',
                'L7 Throughput': '40 Gbps',
                'SSL TPS (RSA 2K)': '40,000',
                'Interfaces': '12x 25 GbE SFP28 + 4x 100 GbE QSFP28',
                'Form Factor': '1 RU',
                'Multi-Tenancy': 'Up to 12 tenants (F5OS)',
                'Max Concurrent Connections': '40,000,000',
                'Power Supply': 'Dual AC 500W redundant',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r5900',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r5900',
              nameKo: 'BIG-IP r5900',
              description:
                'Performance-tier rSeries ADC with 100 Gbps L4 throughput, optimized for high-density SSL and multi-tenant workloads',
              descriptionKo:
                '100 Gbps L4 처리량, 고밀도 SSL 및 멀티테넌트 워크로드에 최적화된 퍼포먼스급 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '100 Gbps',
              architectureRole: 'Core Data Center / Service Provider ADC',
              architectureRoleKo: '코어 데이터센터 / 서비스 프로바이더 ADC',
              recommendedFor: [
                'High-performance data center ADC',
                'Service provider application delivery',
                'Multi-tenant SaaS infrastructure ADC',
              ],
              recommendedForKo: [
                '고성능 데이터센터 ADC',
                '서비스 프로바이더 애플리케이션 딜리버리',
                '멀티테넌트 SaaS 인프라 ADC',
              ],
              specs: {
                'L4 Throughput': '100 Gbps',
                'L7 Throughput': '50 Gbps',
                'SSL TPS (RSA 2K)': '60,000',
                'Interfaces': '16x 25 GbE SFP28 + 4x 100 GbE QSFP28',
                'Form Factor': '1 RU',
                'Multi-Tenancy': 'Up to 16 tenants (F5OS)',
                'Max Concurrent Connections': '56,000,000',
                'Power Supply': 'Dual AC 600W redundant',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r10600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r10600',
              nameKo: 'BIG-IP r10600',
              description:
                'High-end rSeries ADC with 200 Gbps L4 throughput and 100 GbE uplinks for large-scale data center and service provider environments',
              descriptionKo:
                '200 Gbps L4 처리량과 100 GbE 업링크를 갖춘 대규모 데이터센터 및 서비스 프로바이더 환경용 하이엔드 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '200 Gbps',
              architectureRole: 'Data Center Core / Carrier-Grade ADC',
              architectureRoleKo: '데이터센터 코어 / 캐리어급 ADC',
              recommendedFor: [
                'Large data center core ADC deployments',
                'Carrier-grade network traffic management',
                'Hyperscale multi-tenant application delivery',
              ],
              recommendedForKo: [
                '대규모 데이터센터 코어 ADC 배포',
                '캐리어급 네트워크 트래픽 관리',
                '하이퍼스케일 멀티테넌트 애플리케이션 딜리버리',
              ],
              specs: {
                'L4 Throughput': '200 Gbps',
                'L7 Throughput': '100 Gbps',
                'SSL TPS (RSA 2K)': '100,000',
                'Interfaces': '16x 25 GbE SFP28 + 8x 100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Multi-Tenancy': 'Up to 24 tenants (F5OS)',
                'Max Concurrent Connections': '80,000,000',
                'Power Supply': 'Dual AC 1100W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r10900',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r10900',
              nameKo: 'BIG-IP r10900',
              description:
                'High-end rSeries ADC with FIPS 140-2 certified HSM for government and financial regulated environments, 200 Gbps L4',
              descriptionKo:
                '공공기관 및 금융 규제 환경용 FIPS 140-2 인증 HSM 탑재 하이엔드 rSeries ADC, 200 Gbps L4',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '200 Gbps',
              architectureRole: 'Secure Data Center / Government ADC',
              architectureRoleKo: '보안 데이터센터 / 공공기관 ADC',
              recommendedFor: [
                'Government and military secure ADC deployments',
                'FIPS-compliant financial services infrastructure',
                'Regulated industry application delivery',
              ],
              recommendedForKo: [
                '공공기관 및 군사 보안 ADC 배포',
                'FIPS 준수 금융 서비스 인프라',
                '규제 산업 애플리케이션 딜리버리',
              ],
              specs: {
                'L4 Throughput': '200 Gbps',
                'L7 Throughput': '100 Gbps',
                'SSL TPS (RSA 2K)': '100,000',
                'HSM': 'FIPS 140-2 Level 3',
                'Interfaces': '16x 25 GbE SFP28 + 8x 100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Multi-Tenancy': 'Up to 24 tenants (F5OS)',
                'Power Supply': 'Dual AC 1100W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r12600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r12600',
              nameKo: 'BIG-IP r12600',
              description:
                'Flagship rSeries ADC with 400 Gbps L4 throughput for hyperscale data centers and service providers',
              descriptionKo:
                '하이퍼스케일 데이터센터 및 서비스 프로바이더를 위한 400 Gbps L4 처리량의 플래그십 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '400 Gbps',
              architectureRole: 'Hyperscale Data Center / Carrier ADC',
              architectureRoleKo: '하이퍼스케일 데이터센터 / 캐리어 ADC',
              recommendedFor: [
                'Hyperscale data center ADC deployments',
                'Carrier-grade high-throughput application delivery',
                'Enterprise consolidation with maximum tenancy',
              ],
              recommendedForKo: [
                '하이퍼스케일 데이터센터 ADC 배포',
                '캐리어급 고처리량 애플리케이션 딜리버리',
                '최대 테넌시를 통한 엔터프라이즈 통합',
              ],
              specs: {
                'L4 Throughput': '400 Gbps',
                'L7 Throughput': '200 Gbps',
                'SSL TPS (RSA 2K)': '200,000',
                'Interfaces': '16x 25 GbE SFP28 + 8x 100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Multi-Tenancy': 'Up to 32 tenants (F5OS)',
                'Max Concurrent Connections': '150,000,000',
                'Power Supply': 'Dual AC 1500W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'stable',
              children: [],
            },
            {
              nodeId: 'f5-bigip-r12900',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP r12900',
              nameKo: 'BIG-IP r12900',
              description:
                'Flagship rSeries ADC with FIPS HSM, 400 Gbps L4 throughput for hyperscale secure government and financial deployments',
              descriptionKo:
                'FIPS HSM 탑재, 하이퍼스케일 보안 공공기관 및 금융 배포를 위한 400 Gbps L4 처리량의 플래그십 rSeries ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '400 Gbps',
              architectureRole: 'Hyperscale Secure Data Center / Government ADC',
              architectureRoleKo: '하이퍼스케일 보안 데이터센터 / 공공기관 ADC',
              recommendedFor: [
                'Hyperscale government and defense ADC',
                'Maximum-security financial infrastructure',
                'FIPS-compliant carrier-grade deployments',
              ],
              recommendedForKo: [
                '하이퍼스케일 공공기관 및 국방 ADC',
                '최고 수준 보안 금융 인프라',
                'FIPS 준수 캐리어급 배포',
              ],
              specs: {
                'L4 Throughput': '400 Gbps',
                'L7 Throughput': '200 Gbps',
                'SSL TPS (RSA 2K)': '200,000',
                'HSM': 'FIPS 140-2 Level 3',
                'Interfaces': '16x 25 GbE SFP28 + 8x 100 GbE QSFP28',
                'Form Factor': '2 RU',
                'Multi-Tenancy': 'Up to 32 tenants (F5OS)',
                'Power Supply': 'Dual AC 1500W redundant',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'stable',
              children: [],
            },
            // ── BIG-IP VIPRION ──
            {
              nodeId: 'f5-bigip-viprion-b2250',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP VIPRION B2250',
              nameKo: 'BIG-IP VIPRION B2250',
              description:
                'VIPRION chassis blade delivering 80 Gbps L4 throughput per blade for modular scale-out architectures in C2400 chassis',
              descriptionKo:
                'C2400 섀시에서 블레이드당 80 Gbps L4 처리량을 제공하는 모듈형 스케일아웃 아키텍처용 VIPRION 섀시 블레이드',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'chassis',
              licensingModel: 'perpetual',
              maxThroughput: '80 Gbps',
              architectureRole: 'Data Center Core / Carrier-Grade ADC (chassis)',
              architectureRoleKo: '데이터센터 코어 / 캐리어급 ADC (섀시)',
              recommendedFor: [
                'Service provider modular ADC infrastructure',
                'Data center core traffic management with scale-out',
                'Carrier-grade NAT and CGNAT deployments',
              ],
              recommendedForKo: [
                '서비스 프로바이더 모듈형 ADC 인프라',
                '스케일아웃 방식의 데이터센터 코어 트래픽 관리',
                '캐리어급 NAT 및 CGNAT 배포',
              ],
              specs: {
                'L4 Throughput per Blade': '80 Gbps',
                'L7 Throughput per Blade': '40 Gbps',
                'SSL TPS (RSA 2K)': '40,000 per blade',
                'Chassis': 'C2400 (up to 4 blades)',
                'Interfaces per Blade': '16x 1/10 GbE SFP+',
                'Max Aggregate L4': '320 Gbps (4-blade C2400)',
                'Form Factor': '4 RU chassis',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              children: [],
            },
            {
              nodeId: 'f5-bigip-viprion-b4450',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP VIPRION B4450',
              nameKo: 'BIG-IP VIPRION B4450',
              description:
                'High-performance VIPRION chassis blade delivering 160 Gbps L4 throughput per blade for C4480 chassis, maximum scale-out ADC',
              descriptionKo:
                'C4480 섀시에서 블레이드당 160 Gbps L4 처리량을 제공하는 고성능 VIPRION 섀시 블레이드, 최대 스케일아웃 ADC',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'end-of-sale',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'chassis',
              licensingModel: 'perpetual',
              maxThroughput: '160 Gbps',
              architectureRole: 'Service Provider / Hyperscale Data Center ADC (chassis)',
              architectureRoleKo: '서비스 프로바이더 / 하이퍼스케일 데이터센터 ADC (섀시)',
              recommendedFor: [
                'Tier 1 service provider traffic management',
                'Hyperscale data center ADC with maximum throughput',
                'CGNAT and DNS at carrier scale',
              ],
              recommendedForKo: [
                'Tier 1 서비스 프로바이더 트래픽 관리',
                '최대 처리량의 하이퍼스케일 데이터센터 ADC',
                '캐리어 규모의 CGNAT 및 DNS',
              ],
              specs: {
                'L4 Throughput per Blade': '160 Gbps',
                'L7 Throughput per Blade': '80 Gbps',
                'SSL TPS (RSA 2K)': '80,000 per blade',
                'Chassis': 'C4480 (up to 8 blades)',
                'Interfaces per Blade': '8x 40 GbE QSFP+ + 16x 10 GbE SFP+',
                'Max Aggregate L4': '1.28 Tbps (8-blade C4480)',
                'Form Factor': '8 RU chassis',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              children: [],
            },
            // ── BIG-IP Virtual Edition ──
            {
              nodeId: 'f5-bigip-ve',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP Virtual Edition',
              nameKo: 'BIG-IP 가상 에디션',
              description:
                'Software-based BIG-IP running on VMware ESXi, KVM, Hyper-V, AWS, Azure, and GCP with flexible vCPU-based licensing',
              descriptionKo:
                'VMware ESXi, KVM, Hyper-V, AWS, Azure, GCP에서 실행되는 유연한 vCPU 기반 라이선스의 소프트웨어 기반 BIG-IP',
              sourceUrl: 'https://www.f5.com/trials/big-ip-virtual-edition',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'virtual',
              licensingModel: 'subscription',
              maxThroughput: '100 Gbps',
              architectureRole: 'Cloud / Virtual Data Center ADC',
              architectureRoleKo: '클라우드 / 가상 데이터센터 ADC',
              recommendedFor: [
                'Cloud-native application delivery in AWS, Azure, GCP',
                'Virtual data center load balancing',
                'DevOps and infrastructure-as-code ADC deployments',
                'Multi-cloud consistent traffic management',
              ],
              recommendedForKo: [
                'AWS, Azure, GCP에서의 클라우드 네이티브 애플리케이션 딜리버리',
                '가상 데이터센터 부하 분산',
                'DevOps 및 IaC ADC 배포',
                '멀티클라우드 일관된 트래픽 관리',
              ],
              specs: {
                'L4 Throughput': 'Up to 100 Gbps (license dependent)',
                'Supported Hypervisors': 'VMware ESXi, KVM, Hyper-V, Xen',
                'Cloud Platforms': 'AWS, Azure, GCP, OpenStack',
                'vCPU Options': '1, 2, 4, 8, 16 vCPUs',
                'Minimum Memory': '2 GB per vCPU',
                'Form Factor': 'Virtual',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              children: [],
            },
          ],
        },
        // -----------------------------------------------------------------
        // BIG-IP Next
        // -----------------------------------------------------------------
        {
          nodeId: 'f5-bigip-next',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP Next',
          nameKo: 'BIG-IP Next',
          description:
            'Next-generation BIG-IP platform built for modern, cloud-native environments with Kubernetes-native deployment, centralized management, and zero-trust architecture',
          descriptionKo:
            'Kubernetes 네이티브 배포, 중앙 관리 및 제로 트러스트 아키텍처를 갖춘 모던 클라우드 네이티브 환경을 위한 차세대 BIG-IP 플랫폼',
          sourceUrl: 'https://www.f5.com/products/big-ip',
          infraNodeTypes: ['load-balancer', 'waf'],
          architectureRole: 'Cloud-Native / Kubernetes ADC & Security',
          architectureRoleKo: '클라우드 네이티브 / Kubernetes ADC 및 보안',
          recommendedFor: [
            'Kubernetes-native application delivery',
            'Cloud-native microservices traffic management',
            'Zero-trust access for modern applications',
            'Service mesh integration',
          ],
          recommendedForKo: [
            'Kubernetes 네이티브 애플리케이션 딜리버리',
            '클라우드 네이티브 마이크로서비스 트래픽 관리',
            '모던 애플리케이션을 위한 제로 트러스트 접근',
            '서비스 메시 통합',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'TCP',
            'UDP',
            'SSL/TLS',
            'HTTP/2',
            'HTTP/3',
            'gRPC',
            'WebSocket',
          ],
          haFeatures: [
            'Kubernetes-native HA',
            'Multi-instance orchestration',
            'Config sync via BIG-IP Next Central Manager',
            'Rolling upgrades',
          ],
          securityCapabilities: [
            'WAF (OWASP Top 10)',
            'L7 DDoS protection',
            'Bot defense',
            'API security',
            'ZTNA (Zero Trust Network Access)',
          ],
          children: [
            {
              nodeId: 'f5-bigip-next-cnf',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP Next CNF',
              nameKo: 'BIG-IP Next CNF',
              description:
                'Cloud-native network function for 5G and telecom service providers, deployed as Kubernetes pods with service proxy capabilities',
              descriptionKo:
                '5G 및 통신 서비스 프로바이더용 클라우드 네이티브 네트워크 기능, Kubernetes 파드로 배포되며 서비스 프록시 기능 제공',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'container',
              licensingModel: 'subscription',
              maxThroughput: 'Variable (K8s resource dependent)',
              architectureRole: '5G / Telecom Cloud-Native ADC',
              architectureRoleKo: '5G / 통신 클라우드 네이티브 ADC',
              recommendedFor: [
                '5G core network traffic management',
                'Telecom cloud-native transformation',
                'Service provider Kubernetes-based infrastructure',
              ],
              recommendedForKo: [
                '5G 코어 네트워크 트래픽 관리',
                '통신 클라우드 네이티브 전환',
                '서비스 프로바이더 Kubernetes 기반 인프라',
              ],
              specs: {
                'Deployment': 'Kubernetes CNF (containerized)',
                'Architecture': 'Cloud-Native Network Function',
                'Supported K8s': 'OpenShift, Rancher, Tanzu, Native K8s',
                'Protocols': 'HTTP/2, gRPC, DIAMETER, SIP, GTP',
                'Form Factor': 'Container',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'emerging',
              children: [],
            },
            {
              nodeId: 'f5-bigip-next-spk',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP Next SPK',
              nameKo: 'BIG-IP Next SPK',
              description:
                'Service Proxy for Kubernetes providing ingress/egress traffic management and security for 5G service-based architecture',
              descriptionKo:
                '5G 서비스 기반 아키텍처를 위한 인그레스/이그레스 트래픽 관리 및 보안을 제공하는 Kubernetes용 서비스 프록시',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer', 'api-gateway'],
              formFactor: 'container',
              licensingModel: 'subscription',
              maxThroughput: 'Variable (K8s resource dependent)',
              architectureRole: '5G SBA Service Proxy',
              architectureRoleKo: '5G SBA 서비스 프록시',
              recommendedFor: [
                '5G SBA (Service-Based Architecture) service proxy',
                'Kubernetes ingress/egress for telecom workloads',
                'Signaling traffic management (SIP, DIAMETER)',
              ],
              recommendedForKo: [
                '5G SBA (서비스 기반 아키텍처) 서비스 프록시',
                '통신 워크로드를 위한 Kubernetes 인그레스/이그레스',
                '시그널링 트래픽 관리 (SIP, DIAMETER)',
              ],
              specs: {
                'Deployment': 'Kubernetes Service Proxy',
                'Architecture': 'Service-Based Architecture proxy',
                'Signaling Protocols': 'SIP, DIAMETER, GTP-C',
                'Data Plane': 'eBPF-accelerated',
                'Form Factor': 'Container',
              },
              operationalComplexity: 'complex',
              ecosystemMaturity: 'emerging',
              children: [],
            },
            {
              nodeId: 'f5-bigip-next-access',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'BIG-IP Next Access',
              nameKo: 'BIG-IP Next Access',
              description:
                'Zero-trust network access solution providing identity-aware, context-based application access for modern and legacy apps',
              descriptionKo:
                '모던 및 레거시 앱을 위한 ID 인식, 컨텍스트 기반 애플리케이션 접근을 제공하는 제로 트러스트 네트워크 접근 솔루션',
              sourceUrl: 'https://www.f5.com/products/big-ip',
              lifecycle: 'active',
              infraNodeTypes: ['load-balancer'],
              formFactor: 'virtual',
              licensingModel: 'subscription',
              maxThroughput: 'N/A (access proxy)',
              architectureRole: 'ZTNA / Secure Access Gateway',
              architectureRoleKo: 'ZTNA / 보안 접근 게이트웨이',
              recommendedFor: [
                'Zero-trust network access for remote workforce',
                'Legacy application secure access modernization',
                'Identity-aware application delivery',
              ],
              recommendedForKo: [
                '원격 근무자를 위한 제로 트러스트 네트워크 접근',
                '레거시 애플리케이션 보안 접근 현대화',
                'ID 인식 애플리케이션 딜리버리',
              ],
              specs: {
                'Deployment': 'Virtual / Cloud',
                'Authentication': 'SAML, OIDC, Kerberos, MFA',
                'SSO': 'SAML 2.0, OAuth 2.0, OIDC',
                'Device Posture': 'Endpoint compliance checking',
                'Form Factor': 'Virtual / Cloud',
              },
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'emerging',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. NGINX
    // =====================================================================
    {
      nodeId: 'f5-nginx',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'NGINX',
      nameKo: 'NGINX',
      description:
        'High-performance software load balancer, reverse proxy, web server, API gateway, and Kubernetes ingress controller platform',
      descriptionKo:
        '고성능 소프트웨어 부하 분산기, 리버스 프록시, 웹 서버, API 게이트웨이 및 Kubernetes 인그레스 컨트롤러 플랫폼',
      sourceUrl: 'https://www.f5.com/products/nginx',
      infraNodeTypes: ['load-balancer', 'api-gateway', 'web-server'],
      children: [
        {
          nodeId: 'f5-nginx-plus',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NGINX Plus',
          nameKo: 'NGINX Plus',
          description:
            'Commercial all-in-one cloud-native load balancer, reverse proxy, web server, content cache, and API gateway with enterprise support and advanced features',
          descriptionKo:
            '엔터프라이즈 지원 및 고급 기능을 갖춘 상용 올인원 클라우드 네이티브 부하 분산기, 리버스 프록시, 웹 서버, 콘텐츠 캐시 및 API 게이트웨이',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['load-balancer', 'api-gateway', 'web-server'],
          lifecycle: 'active',
          formFactor: 'virtual',
          licensingModel: 'subscription',
          architectureRole: 'Application Layer / Reverse Proxy / API Gateway',
          architectureRoleKo: '애플리케이션 레이어 / 리버스 프록시 / API 게이트웨이',
          recommendedFor: [
            'Software-defined load balancing for web applications',
            'API gateway for microservices architectures',
            'Reverse proxy and content caching layer',
            'High-performance web serving',
          ],
          recommendedForKo: [
            '웹 애플리케이션용 소프트웨어 정의 부하 분산',
            '마이크로서비스 아키텍처를 위한 API 게이트웨이',
            '리버스 프록시 및 콘텐츠 캐싱 레이어',
            '고성능 웹 서빙',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'HTTP/2',
            'HTTP/3 (QUIC)',
            'WebSocket',
            'gRPC',
            'TCP',
            'UDP',
            'SSL/TLS',
            'FastCGI',
            'uwsgi',
            'SCGI',
            'memcached',
          ],
          haFeatures: [
            'Active-Active clustering',
            'Active-Passive HA',
            'Zone sync for shared state',
            'Health checks (active/passive)',
            'DNS service discovery',
          ],
          specs: {
            'Type': 'Software load balancer / reverse proxy',
            'Deployment': 'Linux (bare metal, VM, container)',
            'Load Balancing': 'Round Robin, Least Connections, Hash, IP Hash, Least Time',
            'Session Persistence': 'Cookie, Route, Learn',
            'Rate Limiting': 'Per-connection and per-request',
            'Content Cache': 'Built-in HTTP cache with purge API',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-nginx-app-protect-waf',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 WAF for NGINX',
          nameKo: 'NGINX용 F5 WAF',
          description:
            'Comprehensive WAF security module for NGINX protecting applications and APIs from OWASP Top 10 and Layer 7 attacks',
          descriptionKo:
            'OWASP Top 10 및 Layer 7 공격으로부터 애플리케이션과 API를 보호하는 NGINX용 종합 WAF 보안 모듈',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'virtual',
          licensingModel: 'subscription',
          architectureRole: 'Application Security / WAF Layer',
          architectureRoleKo: '애플리케이션 보안 / WAF 레이어',
          recommendedFor: [
            'NGINX-based web application firewall',
            'API security for microservices',
            'DevSecOps WAF integration in CI/CD pipelines',
          ],
          recommendedForKo: [
            'NGINX 기반 웹 애플리케이션 방화벽',
            '마이크로서비스를 위한 API 보안',
            'CI/CD 파이프라인의 DevSecOps WAF 통합',
          ],
          securityCapabilities: [
            'OWASP Top 10 protection',
            'Bot protection',
            'L7 DDoS mitigation',
            'API security (REST, GraphQL)',
            'Threat campaign signatures',
            'Data guard (PII masking)',
            'Declarative policy-as-code',
          ],
          specs: {
            'Type': 'WAF module for NGINX',
            'Policy Engine': 'F5 Advanced WAF engine',
            'Deployment': 'NGINX Plus module / K8s sidecar',
            'API Protocols': 'REST, GraphQL, gRPC',
            'Threat Intelligence': 'F5 Threat Campaign feed',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-nginx-ingress-controller',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NGINX Ingress Controller',
          nameKo: 'NGINX 인그레스 컨트롤러',
          description:
            'Kubernetes-native ingress controller providing unified API gateway, load balancer, and security for containerized applications',
          descriptionKo:
            '컨테이너화된 애플리케이션을 위한 통합 API 게이트웨이, 부하 분산기 및 보안을 제공하는 Kubernetes 네이티브 인그레스 컨트롤러',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['load-balancer', 'api-gateway'],
          lifecycle: 'active',
          formFactor: 'container',
          licensingModel: 'subscription',
          architectureRole: 'Kubernetes Ingress / API Gateway',
          architectureRoleKo: 'Kubernetes 인그레스 / API 게이트웨이',
          recommendedFor: [
            'Kubernetes ingress traffic management',
            'Microservices API gateway in K8s',
            'Service mesh edge proxy',
          ],
          recommendedForKo: [
            'Kubernetes 인그레스 트래픽 관리',
            'K8s 내 마이크로서비스 API 게이트웨이',
            '서비스 메시 에지 프록시',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'HTTP/2',
            'gRPC',
            'WebSocket',
            'TCP',
            'UDP',
          ],
          specs: {
            'Type': 'Kubernetes Ingress Controller',
            'Deployment': 'K8s DaemonSet or Deployment',
            'K8s Distributions': 'EKS, AKS, GKE, OpenShift, Rancher, Vanilla K8s',
            'WAF Integration': 'NGINX App Protect WAF sidecar',
            'Observability': 'Prometheus metrics, NGINX Dashboard',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-nginx-instance-manager',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NGINX Instance Manager',
          nameKo: 'NGINX 인스턴스 매니저',
          description:
            'Centralized management platform for discovering, securing, managing, and monitoring all NGINX Open Source and NGINX Plus instances',
          descriptionKo:
            '모든 NGINX 오픈소스 및 NGINX Plus 인스턴스의 검색, 보안, 관리 및 모니터링을 위한 중앙 관리 플랫폼',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['load-balancer'],
          lifecycle: 'active',
          formFactor: 'virtual',
          licensingModel: 'subscription',
          architectureRole: 'NGINX Fleet Management',
          architectureRoleKo: 'NGINX 플릿 관리',
          recommendedFor: [
            'Enterprise-wide NGINX fleet management',
            'Centralized NGINX configuration and compliance',
            'NGINX vulnerability scanning and CVE tracking',
          ],
          recommendedForKo: [
            '전사 NGINX 플릿 관리',
            '중앙 집중식 NGINX 설정 및 컴플라이언스',
            'NGINX 취약점 스캔 및 CVE 추적',
          ],
          specs: {
            'Type': 'Management platform',
            'Manages': 'NGINX Open Source + NGINX Plus',
            'Features': 'Instance discovery, Config management, CVE scanning',
            'API': 'REST API for automation',
            'Deployment': 'On-premises or VM',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'stable',
          children: [],
        },
        {
          nodeId: 'f5-nginx-one',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NGINX One',
          nameKo: 'NGINX One',
          description:
            'SaaS-based unified management, observability, and security platform combining NGINX data plane with cloud management tools',
          descriptionKo:
            'NGINX 데이터 플레인과 클라우드 관리 도구를 결합한 SaaS 기반 통합 관리, 관찰 가능성 및 보안 플랫폼',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['load-balancer'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'SaaS NGINX Management & Observability',
          architectureRoleKo: 'SaaS NGINX 관리 및 관찰 가능성',
          recommendedFor: [
            'Cloud-managed NGINX deployment and monitoring',
            'SaaS-based application delivery management',
            'Unified observability for distributed NGINX fleet',
          ],
          recommendedForKo: [
            '클라우드 관리형 NGINX 배포 및 모니터링',
            'SaaS 기반 애플리케이션 딜리버리 관리',
            '분산 NGINX 플릿의 통합 관찰 가능성',
          ],
          specs: {
            'Type': 'SaaS management platform',
            'Features': 'Observability, Config management, Security posture',
            'Data Plane': 'NGINX Plus (enhanced)',
            'Deployment': 'SaaS (F5 managed)',
            'Integration': 'Terraform, CI/CD, Prometheus',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'emerging',
          children: [],
        },
        {
          nodeId: 'f5-nginx-gateway-fabric',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NGINX Gateway Fabric',
          nameKo: 'NGINX 게이트웨이 패브릭',
          description:
            'Kubernetes Gateway API implementation providing unified app, service, and API connectivity across hybrid and multicloud K8s environments',
          descriptionKo:
            '하이브리드 및 멀티클라우드 K8s 환경에서 통합 앱, 서비스 및 API 연결을 제공하는 Kubernetes Gateway API 구현',
          sourceUrl: 'https://www.f5.com/products/nginx',
          infraNodeTypes: ['load-balancer', 'api-gateway'],
          lifecycle: 'active',
          formFactor: 'container',
          licensingModel: 'subscription',
          architectureRole: 'Kubernetes Gateway API / Service Connectivity',
          architectureRoleKo: 'Kubernetes Gateway API / 서비스 연결',
          recommendedFor: [
            'Kubernetes Gateway API-based traffic management',
            'Multi-cluster service connectivity',
            'Hybrid/multicloud K8s application networking',
          ],
          recommendedForKo: [
            'Kubernetes Gateway API 기반 트래픽 관리',
            '멀티 클러스터 서비스 연결',
            '하이브리드/멀티클라우드 K8s 애플리케이션 네트워킹',
          ],
          supportedProtocols: [
            'HTTP/HTTPS',
            'HTTP/2',
            'gRPC',
            'TCP',
            'TLS',
          ],
          specs: {
            'Type': 'Kubernetes Gateway API implementation',
            'API Conformance': 'Gateway API v1.0+',
            'K8s Distributions': 'EKS, AKS, GKE, OpenShift, Vanilla K8s',
            'Deployment': 'Helm chart / YAML manifests',
            'Traffic Splitting': 'Weighted routing, header-based, canary',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'emerging',
          children: [],
        },
      ],
    },

    // =====================================================================
    // 3. Distributed Cloud Services
    // =====================================================================
    {
      nodeId: 'f5-distributed-cloud',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Distributed Cloud Services',
      nameKo: '분산 클라우드 서비스',
      description:
        'SaaS-based security, networking, and application management services for multi-cloud, hybrid, and edge environments with global PoP network',
      descriptionKo:
        '글로벌 PoP 네트워크를 갖춘 멀티클라우드, 하이브리드 및 에지 환경을 위한 SaaS 기반 보안, 네트워킹 및 애플리케이션 관리 서비스',
      sourceUrl: 'https://www.f5.com/cloud',
      infraNodeTypes: ['load-balancer', 'cdn', 'waf'],
      children: [
        {
          nodeId: 'f5-xc-waf',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud WAF',
          nameKo: 'F5 분산 클라우드 WAF',
          description:
            'SaaS-delivered WAF enforcing consistent security policies across data centers, clouds, and edge locations with AI-driven threat detection',
          descriptionKo:
            'AI 기반 위협 탐지를 통해 데이터센터, 클라우드 및 에지 전체에 일관된 보안 정책을 시행하는 SaaS 딜리버리 WAF',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Cloud-Edge WAF / Distributed Security',
          architectureRoleKo: '클라우드-에지 WAF / 분산 보안',
          recommendedFor: [
            'Multi-cloud consistent WAF policy enforcement',
            'Edge-based web application protection',
            'SaaS WAF for organizations without on-prem security teams',
          ],
          recommendedForKo: [
            '멀티클라우드 일관된 WAF 정책 시행',
            '에지 기반 웹 애플리케이션 보호',
            '온프레미스 보안팀이 없는 조직을 위한 SaaS WAF',
          ],
          securityCapabilities: [
            'OWASP Top 10 protection',
            'API discovery and security',
            'Bot defense',
            'Automated attack mitigation',
            'Threat intelligence integration',
            'Client-side protection (Magecart)',
          ],
          specs: {
            'Type': 'SaaS WAF',
            'Delivery': 'F5 Global Network PoPs',
            'Policy Engine': 'AI/ML-driven + signature-based',
            'API Discovery': 'Automated API endpoint discovery',
            'Compliance': 'PCI DSS, SOC 2',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'stable',
          children: [],
        },
        {
          nodeId: 'f5-xc-ddos',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud DDoS Protection',
          nameKo: 'F5 분산 클라우드 DDoS 보호',
          description:
            'Cloud-based L3-L7 DDoS mitigation service detecting and mitigating volumetric, protocol, and application-layer attacks globally',
          descriptionKo:
            '볼류메트릭, 프로토콜 및 애플리케이션 레이어 공격을 글로벌하게 탐지하고 완화하는 클라우드 기반 L3-L7 DDoS 완화 서비스',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Cloud DDoS Scrubbing / Upstream Protection',
          architectureRoleKo: '클라우드 DDoS 스크러빙 / 업스트림 보호',
          recommendedFor: [
            'Volumetric DDoS attack mitigation',
            'Always-on or on-demand DDoS protection',
            'Multi-cloud DDoS defense',
          ],
          recommendedForKo: [
            '볼류메트릭 DDoS 공격 완화',
            '상시 또는 온디맨드 DDoS 보호',
            '멀티클라우드 DDoS 방어',
          ],
          securityCapabilities: [
            'L3/L4 volumetric attack mitigation',
            'L7 application DDoS defense',
            'BGP-based route diversion',
            'DNS-based traffic scrubbing',
            'Real-time attack analytics',
          ],
          specs: {
            'Type': 'SaaS DDoS Protection',
            'Mitigation Capacity': 'Multi-Tbps global scrubbing',
            'Layers': 'L3, L4, L7',
            'Modes': 'Always-on, On-demand, Hybrid',
            'SLA': '99.99% uptime',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'stable',
          children: [],
        },
        {
          nodeId: 'f5-xc-app-connect',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud App Connect',
          nameKo: 'F5 분산 클라우드 앱 커넥트',
          description:
            'Secure multi-cloud networking service connecting distributed workloads across cloud providers, data centers, and edge with built-in security',
          descriptionKo:
            '내장 보안을 통해 클라우드 프로바이더, 데이터센터 및 에지 전체에 분산 워크로드를 연결하는 보안 멀티클라우드 네트워킹 서비스',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['load-balancer'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Multi-Cloud Networking / Service Connectivity',
          architectureRoleKo: '멀티클라우드 네트워킹 / 서비스 연결',
          recommendedFor: [
            'Multi-cloud application connectivity',
            'Hybrid cloud workload interconnection',
            'Secure cross-cloud service mesh',
          ],
          recommendedForKo: [
            '멀티클라우드 애플리케이션 연결',
            '하이브리드 클라우드 워크로드 상호 연결',
            '보안 크로스 클라우드 서비스 메시',
          ],
          specs: {
            'Type': 'SaaS Multi-Cloud Networking',
            'Connectivity': 'AWS, Azure, GCP, On-prem',
            'Encryption': 'End-to-end TLS',
            'Service Discovery': 'Automatic across environments',
            'Network Policies': 'Intent-based segmentation',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'stable',
          children: [],
        },
        {
          nodeId: 'f5-xc-dns',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud DNS',
          nameKo: 'F5 분산 클라우드 DNS',
          description:
            'Cloud-based authoritative DNS and DNS load balancing service with global resilience, DDoS protection, and DNSSEC support',
          descriptionKo:
            '글로벌 복원력, DDoS 보호 및 DNSSEC 지원을 갖춘 클라우드 기반 권한 DNS 및 DNS 부하 분산 서비스',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['dns'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Cloud DNS / Global Server Load Balancing',
          architectureRoleKo: '클라우드 DNS / 글로벌 서버 부하 분산',
          recommendedFor: [
            'Cloud-based authoritative DNS hosting',
            'DNS-based global server load balancing (GSLB)',
            'DNS DDoS protection and DNSSEC',
          ],
          recommendedForKo: [
            '클라우드 기반 권한 DNS 호스팅',
            'DNS 기반 글로벌 서버 부하 분산 (GSLB)',
            'DNS DDoS 보호 및 DNSSEC',
          ],
          specs: {
            'Type': 'SaaS DNS',
            'Features': 'Primary/Secondary DNS, GSLB, DNSSEC',
            'Anycast': 'Global anycast network',
            'Health Checks': 'Multi-protocol endpoint monitoring',
            'SLA': '100% uptime SLA',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'stable',
          children: [],
        },
        {
          nodeId: 'f5-xc-bot-defense',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud Bot Defense',
          nameKo: 'F5 분산 클라우드 봇 방어',
          description:
            'AI-driven bot management service detecting and mitigating sophisticated automated threats using client-side signals and behavioral analysis',
          descriptionKo:
            '클라이언트 측 신호와 행동 분석을 사용하여 고급 자동화 위협을 탐지하고 완화하는 AI 기반 봇 관리 서비스',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Bot Management / Fraud Prevention',
          architectureRoleKo: '봇 관리 / 사기 방지',
          recommendedFor: [
            'Credential stuffing and account takeover prevention',
            'Web scraping and content theft defense',
            'Automated fraud detection for e-commerce',
          ],
          recommendedForKo: [
            '크리덴셜 스터핑 및 계정 탈취 방지',
            '웹 스크래핑 및 콘텐츠 도용 방어',
            '전자상거래를 위한 자동화 사기 탐지',
          ],
          securityCapabilities: [
            'AI/ML-based bot classification',
            'Client-side signal collection (JavaScript)',
            'Device fingerprinting',
            'Behavioral analysis',
            'CAPTCHA-free mitigation',
          ],
          specs: {
            'Type': 'SaaS Bot Management',
            'Detection': 'AI/ML + JavaScript signal collection',
            'Integration': 'CDN, ADC, Origin-side',
            'Mitigation': 'Block, Redirect, Challenge, Delay',
            'Reporting': 'Real-time analytics dashboard',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-xc-cdn',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Distributed Cloud CDN',
          nameKo: 'F5 분산 클라우드 CDN',
          description:
            'Global content delivery network with integrated security, content caching, and edge compute capabilities for fast and secure digital experiences',
          descriptionKo:
            '빠르고 안전한 디지털 경험을 위한 통합 보안, 콘텐츠 캐싱 및 에지 컴퓨팅 기능을 갖춘 글로벌 콘텐츠 전송 네트워크',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['cdn'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Content Delivery / Edge Caching',
          architectureRoleKo: '콘텐츠 전송 / 에지 캐싱',
          recommendedFor: [
            'Global content delivery and acceleration',
            'Edge-based application delivery with security',
            'Video streaming and rich media delivery',
          ],
          recommendedForKo: [
            '글로벌 콘텐츠 전송 및 가속',
            '보안이 통합된 에지 기반 애플리케이션 딜리버리',
            '비디오 스트리밍 및 리치 미디어 전송',
          ],
          specs: {
            'Type': 'SaaS CDN',
            'PoPs': 'Global edge network',
            'Features': 'Content caching, Image optimization, Video delivery',
            'Security': 'Integrated WAF, DDoS, Bot defense',
            'Edge Compute': 'Container workloads at edge PoPs',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'stable',
          children: [],
        },
      ],
    },

    // =====================================================================
    // 4. Security
    // =====================================================================
    {
      nodeId: 'f5-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Security',
      nameKo: '보안',
      description:
        'Dedicated security solutions including advanced WAF, network firewall, access policy management, SSL orchestration, DDoS protection, and bot defense',
      descriptionKo:
        '고급 WAF, 네트워크 방화벽, 접근 정책 관리, SSL 오케스트레이션, DDoS 보호 및 봇 방어를 포함하는 전용 보안 솔루션',
      sourceUrl: 'https://www.f5.com/products/security/advanced-waf',
      infraNodeTypes: ['waf'],
      children: [
        {
          nodeId: 'f5-bigip-advanced-waf',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP Advanced WAF',
          nameKo: 'BIG-IP 어드밴스드 WAF',
          description:
            'Dedicated WAF module for BIG-IP providing machine learning-driven OWASP Top 10 protection, behavioral DoS, credential theft prevention, and in-browser data encryption',
          descriptionKo:
            '머신러닝 기반 OWASP Top 10 보호, 행동 DoS, 크리덴셜 도용 방지 및 브라우저 내 데이터 암호화를 제공하는 BIG-IP 전용 WAF 모듈',
          sourceUrl: 'https://www.f5.com/products/security/advanced-waf',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'appliance',
          licensingModel: 'perpetual',
          architectureRole: 'Application Security / WAF',
          architectureRoleKo: '애플리케이션 보안 / WAF',
          recommendedFor: [
            'Enterprise web application firewall',
            'API security with behavioral analytics',
            'PCI DSS compliance for web applications',
            'Credential theft and bot protection',
          ],
          recommendedForKo: [
            '엔터프라이즈 웹 애플리케이션 방화벽',
            '행동 분석 기반 API 보안',
            '웹 애플리케이션 PCI DSS 컴플라이언스',
            '크리덴셜 도용 및 봇 보호',
          ],
          securityCapabilities: [
            'OWASP Top 10 protection (ML-driven)',
            'Behavioral L7 DoS detection',
            'Bot defense and proactive bot detection',
            'Credential theft protection',
            'In-browser data encryption (DataSafe)',
            'API security (REST, GraphQL, GWT, XML)',
            'IP reputation and threat intelligence',
            'Declarative WAF policy-as-code',
          ],
          specs: {
            'Type': 'WAF module for BIG-IP',
            'Deployment': 'Hardware, Virtual, Cloud (AWS/Azure/GCP)',
            'Policy Engine': 'ML/AI + signature-based',
            'API Protocols': 'REST, GraphQL, GWT, XML',
            'Compliance': 'PCI DSS, HIPAA',
            'Automation': 'Declarative API (AS3), Terraform',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-bigip-afm',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP Advanced Firewall Manager',
          nameKo: 'BIG-IP 어드밴스드 방화벽 매니저',
          description:
            'High-performance network firewall module for BIG-IP protecting data centers and services from complex L3-L4 threats and massive DDoS attacks',
          descriptionKo:
            '복잡한 L3-L4 위협과 대규모 DDoS 공격으로부터 데이터센터와 서비스를 보호하는 BIG-IP 고성능 네트워크 방화벽 모듈',
          sourceUrl: 'https://www.f5.com/products/big-ip',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'appliance',
          licensingModel: 'perpetual',
          architectureRole: 'Data Center Network Firewall / DDoS Protection',
          architectureRoleKo: '데이터센터 네트워크 방화벽 / DDoS 보호',
          recommendedFor: [
            'Data center perimeter network firewall',
            'DDoS attack mitigation at network edge',
            'Service provider network security',
          ],
          recommendedForKo: [
            '데이터센터 경계 네트워크 방화벽',
            '네트워크 에지에서의 DDoS 공격 완화',
            '서비스 프로바이더 네트워크 보안',
          ],
          securityCapabilities: [
            'Network firewall (L3-L4)',
            'DDoS detection and mitigation',
            'IP intelligence and reputation',
            'Protocol anomaly detection',
            'Network address translation (NAT/CGNAT)',
            'SSH proxy',
            'DoS sweep protection',
          ],
          specs: {
            'Type': 'Network firewall module for BIG-IP',
            'Deployment': 'BIG-IP hardware/virtual platforms',
            'DDoS': 'Hardware-accelerated L3-L7 mitigation',
            'ACL Scale': 'Millions of concurrent ACL entries',
            'Logging': 'HSL, Remote syslog, SNMP',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-bigip-apm',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP Access Policy Manager',
          nameKo: 'BIG-IP 접근 정책 매니저',
          description:
            'Identity-aware access proxy providing secure access to applications with SSO, MFA, and Zero Trust capabilities for both modern and legacy apps',
          descriptionKo:
            '모던 및 레거시 앱을 위한 SSO, MFA 및 제로 트러스트 기능을 갖춘 ID 인식 접근 프록시',
          sourceUrl: 'https://www.f5.com/products/big-ip',
          infraNodeTypes: ['load-balancer'],
          lifecycle: 'active',
          formFactor: 'appliance',
          licensingModel: 'perpetual',
          architectureRole: 'Access Gateway / Identity Proxy / VPN',
          architectureRoleKo: '접근 게이트웨이 / ID 프록시 / VPN',
          recommendedFor: [
            'Secure remote access and VPN',
            'Application SSO federation',
            'Zero-trust application access proxy',
          ],
          recommendedForKo: [
            '보안 원격 접근 및 VPN',
            '애플리케이션 SSO 페더레이션',
            '제로 트러스트 애플리케이션 접근 프록시',
          ],
          securityCapabilities: [
            'SSL VPN (network access)',
            'SAML 2.0 / OAuth 2.0 / OIDC federation',
            'Multi-factor authentication (MFA)',
            'Endpoint compliance checking',
            'Per-request access policy (ZTNA)',
            'Web application proxy',
          ],
          specs: {
            'Type': 'Access policy module for BIG-IP',
            'Authentication': 'SAML, OAuth 2.0, OIDC, Kerberos, RADIUS, LDAP',
            'VPN': 'SSL VPN, Network Access, Web App proxy',
            'MFA': 'TOTP, Push, FIDO2, third-party',
            'Deployment': 'BIG-IP hardware/virtual platforms',
          },
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-bigip-sslo',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'BIG-IP SSL Orchestrator',
          nameKo: 'BIG-IP SSL 오케스트레이터',
          description:
            'Dynamic SSL/TLS decryption and traffic orchestration solution providing encrypted traffic visibility across security inspection chains',
          descriptionKo:
            '보안 검사 체인 전체에 암호화 트래픽 가시성을 제공하는 동적 SSL/TLS 복호화 및 트래픽 오케스트레이션 솔루션',
          sourceUrl: 'https://www.f5.com/products/big-ip',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'appliance',
          licensingModel: 'perpetual',
          architectureRole: 'SSL/TLS Visibility / Security Service Chain',
          architectureRoleKo: 'SSL/TLS 가시성 / 보안 서비스 체인',
          recommendedFor: [
            'Encrypted traffic inspection orchestration',
            'Security service chaining (IDS, DLP, sandbox)',
            'Ransomware detection in encrypted flows',
          ],
          recommendedForKo: [
            '암호화 트래픽 검사 오케스트레이션',
            '보안 서비스 체이닝 (IDS, DLP, 샌드박스)',
            '암호화 흐름에서의 랜섬웨어 탐지',
          ],
          securityCapabilities: [
            'SSL/TLS decryption and re-encryption',
            'Dynamic service chaining',
            'Policy-based traffic steering',
            'TLS 1.3 support',
            'Perfect Forward Secrecy (PFS)',
            'Selective bypass (compliance/privacy)',
          ],
          specs: {
            'Type': 'SSL orchestration module for BIG-IP',
            'TLS Versions': 'TLS 1.0 - 1.3',
            'Service Chain': 'Dynamic insertion of IDS, DLP, NGFW, Sandbox',
            'Deployment': 'Inline L2/L3, ICAP, TAP',
            'Cipher Support': 'RSA, ECDSA, PFS suites',
          },
          operationalComplexity: 'complex',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-silverline-ddos',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Silverline DDoS Protection',
          nameKo: 'F5 실버라인 DDoS 보호',
          description:
            'Cloud-based managed DDoS protection service backed by F5 SOC team providing always-on volumetric attack scrubbing',
          descriptionKo:
            'F5 SOC 팀이 지원하는 상시 볼류메트릭 공격 스크러빙을 제공하는 클라우드 기반 관리형 DDoS 보호 서비스',
          sourceUrl: 'https://www.f5.com/cloud',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Managed DDoS Scrubbing Service',
          architectureRoleKo: '관리형 DDoS 스크러빙 서비스',
          recommendedFor: [
            'Managed DDoS protection for enterprises',
            'BGP-based upstream DDoS scrubbing',
            'Organizations needing 24/7 SOC-backed DDoS defense',
          ],
          recommendedForKo: [
            '기업을 위한 관리형 DDoS 보호',
            'BGP 기반 업스트림 DDoS 스크러빙',
            '24/7 SOC 지원 DDoS 방어가 필요한 조직',
          ],
          securityCapabilities: [
            'Volumetric DDoS mitigation',
            'Application-layer DDoS defense',
            'BGP route diversion',
            '24/7 F5 SOC monitoring',
            'Hybrid on-prem + cloud protection',
          ],
          specs: {
            'Type': 'Managed DDoS service',
            'Scrubbing Capacity': 'Multi-Tbps',
            'SOC': 'F5 Security Operations Center (24/7)',
            'Modes': 'Always-on, Routed, Hybrid',
            'Reporting': 'Real-time portal + monthly reports',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'mature',
          children: [],
        },
        {
          nodeId: 'f5-shape-security',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'F5 Shape Security',
          nameKo: 'F5 쉐이프 시큐리티',
          description:
            'AI-powered fraud and abuse prevention platform defending against credential stuffing, account takeover, and sophisticated automated attacks',
          descriptionKo:
            '크리덴셜 스터핑, 계정 탈취 및 고급 자동화 공격으로부터 방어하는 AI 기반 사기 및 남용 방지 플랫폼',
          sourceUrl: 'https://www.f5.com/products',
          infraNodeTypes: ['waf'],
          lifecycle: 'active',
          formFactor: 'cloud',
          licensingModel: 'as-a-service',
          architectureRole: 'Fraud Prevention / Advanced Bot Defense',
          architectureRoleKo: '사기 방지 / 고급 봇 방어',
          recommendedFor: [
            'Financial services fraud prevention',
            'E-commerce account takeover defense',
            'Enterprise credential stuffing protection',
          ],
          recommendedForKo: [
            '금융 서비스 사기 방지',
            '전자상거래 계정 탈취 방어',
            '엔터프라이즈 크리덴셜 스터핑 보호',
          ],
          securityCapabilities: [
            'AI-based bot detection',
            'Credential stuffing prevention',
            'Account takeover protection',
            'Client-side signal analysis',
            'Real-time fraud scoring',
            'Automated attack retooling detection',
          ],
          specs: {
            'Type': 'SaaS Fraud/Bot defense',
            'AI Engine': 'Shape AI Cloud',
            'Detection': 'JavaScript signals + server-side ML',
            'Integration': 'Reverse proxy, CDN, Origin',
            'Industries': 'Financial, E-commerce, Healthcare, Government',
          },
          operationalComplexity: 'simple',
          ecosystemMaturity: 'mature',
          children: [],
        },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Compute and fix stats after catalog is defined
// ---------------------------------------------------------------------------

import { computeStats } from '../queryHelpers';

const computed = computeStats(f5Catalog.products);
f5Catalog.stats = computed;
