/**
 * Fortinet — Full Product Catalog
 *
 * Hierarchical product tree covering Network Security, SD-WAN & SASE,
 * Switching & Wireless, Security Operations, Zero Trust & Identity,
 * and Management & Analytics categories.
 *
 * Data sourced from https://www.fortinet.com/products
 * Last crawled: 2026-02-20
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Fortinet Product Catalog
// ---------------------------------------------------------------------------

export const fortinetCatalog: VendorCatalog = {
  vendorId: 'fortinet',
  vendorName: 'Fortinet',
  vendorNameKo: '포티넷',
  headquarters: 'Sunnyvale, CA, USA',
  website: 'https://www.fortinet.com',
  productPageUrl: 'https://www.fortinet.com/products',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-20',
  crawlSource: 'https://www.fortinet.com/products',
  stats: { totalProducts: 82, maxDepth: 2, categoriesCount: 6 },
  products: [
    // ═══════════════════════════════════════════════════════════════════════
    // 1. Network Security
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-network-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Security',
      nameKo: '네트워크 보안',
      description: 'Next-generation firewall, web gateway, DDoS protection, and deception solutions',
      descriptionKo: '차세대 방화벽, 웹 게이트웨이, DDoS 방어, 디셉션 솔루션',
      sourceUrl: 'https://www.fortinet.com/products/network-security',
      infraNodeTypes: ['firewall', 'ids-ips'],
      children: [
        // ── FortiGate Next-Gen Firewalls ──
        {
          nodeId: 'fortinet-fortigate',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiGate Next-Generation Firewalls',
          nameKo: 'FortiGate 차세대 방화벽',
          description: 'Industry-leading NGFW platform with integrated SD-WAN, IPS, SSL inspection, and AI-powered threat protection across hardware, virtual, and cloud form factors',
          descriptionKo: 'SD-WAN, IPS, SSL 검사, AI 기반 위협 방어가 통합된 업계 최고의 NGFW 플랫폼 (하드웨어, 가상, 클라우드 폼팩터)',
          sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall',
          infraNodeTypes: ['firewall'],
          architectureRole: 'Perimeter / Internal Segmentation / Data Center Edge',
          architectureRoleKo: '경계 / 내부 세그멘테이션 / 데이터센터 에지',
          recommendedFor: [
            'Enterprise perimeter security with SSL deep inspection',
            'Internal network segmentation (east-west)',
            'Branch office SD-WAN + security convergence',
            'Data center north-south traffic inspection',
            'Cloud workload protection (VM/container)',
          ],
          recommendedForKo: [
            'SSL 심층 검사를 통한 엔터프라이즈 경계 보안',
            '내부 네트워크 세그멘테이션 (동-서)',
            '지사 SD-WAN + 보안 통합',
            '데이터센터 남-북 트래픽 검사',
            '클라우드 워크로드 보호 (VM/컨테이너)',
          ],
          supportedProtocols: [
            'BGP', 'OSPF', 'RIP', 'IS-IS', 'PIM',
            'VXLAN', 'GRE', 'IPSec', 'SSL-VPN',
            'SD-WAN', 'ZTNA',
          ],
          haFeatures: [
            'Active-Active HA clustering',
            'Active-Passive HA',
            'VRRP',
            'Session synchronization',
            'Link failover',
            'Virtual domain (VDOM) partitioning',
          ],
          securityCapabilities: [
            'IPS (Intrusion Prevention System)',
            'Application Control',
            'SSL/TLS deep inspection',
            'Antivirus / Anti-malware',
            'Web filtering',
            'DNS filtering',
            'Sandboxing (FortiSandbox integration)',
            'FortiGuard AI-powered threat intelligence',
            'IoT device detection',
          ],
          children: [
            // ── Entry-Level ──
            {
              nodeId: 'fortinet-fortigate-40f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 40F',
              nameKo: 'FortiGate 40F',
              description: 'Entry-level desktop NGFW for small offices with 5 GE ports, 4.7 Gbps firewall throughput',
              descriptionKo: '소규모 사무실용 엔트리급 데스크톱 NGFW, 5 GE 포트, 4.7 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '4.7 Gbps',
                'IPS Throughput': '1 Gbps',
                'NGFW Throughput': '800 Mbps',
                'SSL VPN Throughput': '490 Mbps',
                'Interfaces': '5× GE RJ45',
                'Max Sessions': '700,000',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-60f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 60F',
              nameKo: 'FortiGate 60F',
              description: 'Entry-level NGFW for small branches with integrated SD-WAN, 10 GE ports, 10 Gbps firewall throughput',
              descriptionKo: 'SD-WAN 통합 소규모 지사용 엔트리급 NGFW, 10 GE 포트, 10 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'IPS Throughput': '1.4 Gbps',
                'NGFW Throughput': '1 Gbps',
                'SSL VPN Throughput': '900 Mbps',
                'Interfaces': '10× GE RJ45',
                'Max Sessions': '700,000',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-70f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 70F',
              nameKo: 'FortiGate 70F',
              description: 'Entry-level NGFW for small branches with PoE support, 12 GE ports, 10 Gbps firewall throughput',
              descriptionKo: 'PoE 지원 소규모 지사용 엔트리급 NGFW, 12 GE 포트, 10 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'IPS Throughput': '1.4 Gbps',
                'NGFW Throughput': '1 Gbps',
                'Interfaces': '12× GE RJ45 (4× PoE)',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-80f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 80F',
              nameKo: 'FortiGate 80F',
              description: 'Entry-level NGFW with high port density, 16 GE + 2 SFP ports, 10 Gbps firewall throughput',
              descriptionKo: '높은 포트 밀도의 엔트리급 NGFW, 16 GE + 2 SFP 포트, 10 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'IPS Throughput': '1.4 Gbps',
                'NGFW Throughput': '1 Gbps',
                'Interfaces': '16× GE RJ45 + 2× SFP',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-90g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 90G',
              nameKo: 'FortiGate 90G',
              description: 'Entry-level NGFW with SP5 ASIC, 26 Gbps firewall throughput, integrated Wi-Fi 6',
              descriptionKo: 'SP5 ASIC 탑재 엔트리급 NGFW, 26 Gbps 방화벽 처리량, Wi-Fi 6 통합',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '26 Gbps',
                'IPS Throughput': '4.2 Gbps',
                'NGFW Throughput': '3.5 Gbps',
                'ASIC': 'SP5',
                'Interfaces': '14× GE RJ45 + 2× SFP',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            // ── Mid-Range ──
            {
              nodeId: 'fortinet-fortigate-100f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 100F',
              nameKo: 'FortiGate 100F',
              description: 'Mid-range NGFW for medium branches, 20 Gbps firewall throughput, 1RU rack-mount',
              descriptionKo: '중규모 지사용 미드레인지 NGFW, 20 Gbps 방화벽 처리량, 1RU 랙마운트',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/mid-range',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '20 Gbps',
                'IPS Throughput': '2.6 Gbps',
                'NGFW Throughput': '1.6 Gbps',
                'Interfaces': '22× GE RJ45 + 2× 10GE SFP+',
                'Max Sessions': '1,500,000',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-200f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 200F',
              nameKo: 'FortiGate 200F',
              description: 'Mid-range NGFW for campus and mid-size enterprise, 27 Gbps firewall throughput',
              descriptionKo: '캠퍼스 및 중견 기업용 미드레인지 NGFW, 27 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/mid-range',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '27 Gbps',
                'IPS Throughput': '4 Gbps',
                'NGFW Throughput': '3 Gbps',
                'Interfaces': '18× GE RJ45 + 4× 10GE SFP+',
                'Max Sessions': '3,000,000',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-400f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 400F',
              nameKo: 'FortiGate 400F',
              description: 'Mid-range NGFW for large campus, 50 Gbps firewall throughput with NP7 ASIC',
              descriptionKo: '대규모 캠퍼스용 미드레인지 NGFW, NP7 ASIC 탑재, 50 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/mid-range',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '50 Gbps',
                'IPS Throughput': '8.5 Gbps',
                'NGFW Throughput': '6.1 Gbps',
                'ASIC': 'NP7',
                'Interfaces': '16× GE RJ45 + 8× 10GE SFP+ + 2× 25GE SFP28',
                'Max Sessions': '6,000,000',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-600f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 600F',
              nameKo: 'FortiGate 600F',
              description: 'Mid-range NGFW for enterprise edge, 80 Gbps firewall throughput with NP7 ASIC',
              descriptionKo: '엔터프라이즈 에지용 미드레인지 NGFW, NP7 ASIC 탑재, 80 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/mid-range',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '80 Gbps',
                'IPS Throughput': '12 Gbps',
                'NGFW Throughput': '9 Gbps',
                'ASIC': 'NP7',
                'Interfaces': '16× GE RJ45 + 8× 10GE SFP+ + 4× 25GE SFP28',
                'Max Sessions': '8,000,000',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            // ── High-End ──
            {
              nodeId: 'fortinet-fortigate-1000f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 1000F',
              nameKo: 'FortiGate 1000F',
              description: 'High-end NGFW for large enterprise, 198 Gbps firewall throughput with NP7 ASIC',
              descriptionKo: '대기업용 하이엔드 NGFW, NP7 ASIC 탑재, 198 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/high-end',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '198 Gbps',
                'IPS Throughput': '26 Gbps',
                'NGFW Throughput': '19.5 Gbps',
                'ASIC': 'NP7',
                'Interfaces': '4× 40/100GE QSFP28 + 16× 25GE SFP28 + 16× GE SFP',
                'Max Sessions': '20,000,000',
                'Form Factor': '2 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-1800f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 1800F',
              nameKo: 'FortiGate 1800F',
              description: 'High-end NGFW for large enterprise, 198 Gbps firewall throughput, high port density',
              descriptionKo: '대기업용 하이엔드 NGFW, 198 Gbps 방화벽 처리량, 고밀도 포트',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/high-end',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '198 Gbps',
                'IPS Throughput': '28 Gbps',
                'NGFW Throughput': '22 Gbps',
                'ASIC': 'NP7',
                'Interfaces': '4× 40/100GE QSFP28 + 24× 25GE SFP28 + 16× GE SFP',
                'Max Sessions': '24,000,000',
                'Form Factor': '2 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-2600f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 2600F',
              nameKo: 'FortiGate 2600F',
              description: 'High-end NGFW for large enterprise and service provider, 400 Gbps firewall throughput',
              descriptionKo: '대기업 및 서비스 프로바이더용 하이엔드 NGFW, 400 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/high-end',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '400 Gbps',
                'IPS Throughput': '45 Gbps',
                'NGFW Throughput': '34 Gbps',
                'ASIC': 'NP7',
                'Max Sessions': '40,000,000',
                'Form Factor': '2 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-3000f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 3000F',
              nameKo: 'FortiGate 3000F',
              description: 'High-end NGFW for data center edge, 500 Gbps firewall throughput with NP7 and CP9 ASICs',
              descriptionKo: '데이터센터 에지용 하이엔드 NGFW, NP7 및 CP9 ASIC 탑재, 500 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/high-end',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '500 Gbps',
                'IPS Throughput': '55 Gbps',
                'NGFW Throughput': '42 Gbps',
                'ASIC': 'NP7 + CP9',
                'Max Sessions': '55,000,000',
                'Form Factor': '3 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-3700f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 3700F',
              nameKo: 'FortiGate 3700F',
              description: 'High-end NGFW for data center and service provider, 800 Gbps firewall throughput',
              descriptionKo: '데이터센터 및 서비스 프로바이더용 하이엔드 NGFW, 800 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/high-end',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '800 Gbps',
                'IPS Throughput': '70 Gbps',
                'NGFW Throughput': '55 Gbps',
                'ASIC': 'NP7 + CP9',
                'Max Sessions': '80,000,000',
                'Form Factor': '3 RU',
              },
              children: [],
            },
            // ── Data Center ──
            {
              nodeId: 'fortinet-fortigate-4200f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 4200F',
              nameKo: 'FortiGate 4200F',
              description: 'Data center NGFW for hyperscale environments, 800 Gbps firewall throughput',
              descriptionKo: '하이퍼스케일 환경용 데이터센터 NGFW, 800 Gbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/data-center',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '800 Gbps',
                'IPS Throughput': '85 Gbps',
                'NGFW Throughput': '65 Gbps',
                'ASIC': 'NP7',
                'Form Factor': '4 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-4400f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 4400F',
              nameKo: 'FortiGate 4400F',
              description: 'Data center NGFW, 1.2 Tbps firewall throughput with dual NP7 ASICs',
              descriptionKo: '데이터센터 NGFW, 듀얼 NP7 ASIC 탑재, 1.2 Tbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/data-center',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '1.2 Tbps',
                'IPS Throughput': '100 Gbps',
                'NGFW Throughput': '80 Gbps',
                'ASIC': 'Dual NP7',
                'Form Factor': '4 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-4800f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 4800F',
              nameKo: 'FortiGate 4800F',
              description: 'Data center chassis-based NGFW, 2.4 Tbps firewall throughput',
              descriptionKo: '데이터센터 섀시형 NGFW, 2.4 Tbps 방화벽 처리량',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/data-center',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '2.4 Tbps',
                'IPS Throughput': '180 Gbps',
                'NGFW Throughput': '150 Gbps',
                'ASIC': 'NP7',
                'Form Factor': 'Chassis',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-6001f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 6001F',
              nameKo: 'FortiGate 6001F',
              description: 'Hyperscale data center NGFW blade, designed for FortiGate chassis systems',
              descriptionKo: '하이퍼스케일 데이터센터 NGFW 블레이드, FortiGate 섀시 시스템용',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/data-center',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '3 Tbps',
                'IPS Throughput': '220 Gbps',
                'Form Factor': 'Blade',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-7081f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 7081F',
              nameKo: 'FortiGate 7081F',
              description: 'Top-of-line chassis NGFW for service providers and hyperscale DC, up to 50+ Tbps',
              descriptionKo: '서비스 프로바이더 및 하이퍼스케일 DC용 최상위 섀시 NGFW, 50+ Tbps',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/data-center',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '50+ Tbps',
                'Form Factor': 'Chassis (8-slot)',
              },
              children: [],
            },
            // ── Rugged ──
            {
              nodeId: 'fortinet-fortigate-60f-rugged',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate Rugged 60F',
              nameKo: 'FortiGate Rugged 60F',
              description: 'Ruggedized NGFW for industrial and harsh environments, IP40-rated, wide temperature range',
              descriptionKo: '산업 및 가혹 환경용 러기드 NGFW, IP40 등급, 넓은 온도 범위',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/rugged',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'Rating': 'IP40',
                'Operating Temp': '-40°C to 70°C',
                'Form Factor': 'DIN rail / Wall mount',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-70f-rugged',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate Rugged 70F',
              nameKo: 'FortiGate Rugged 70F',
              description: 'Ruggedized NGFW for OT environments with built-in bypass and PoE support',
              descriptionKo: 'OT 환경용 러기드 NGFW, 내장 바이패스 및 PoE 지원',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/rugged',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'Rating': 'IP40',
                'Operating Temp': '-40°C to 70°C',
                'Features': 'Hardware bypass, PoE',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-80f-3g4g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate 80F-3G4G',
              nameKo: 'FortiGate 80F-3G4G',
              description: 'NGFW with built-in 3G/4G LTE modem for WAN failover in remote locations',
              descriptionKo: '원격지 WAN 장애 대비용 3G/4G LTE 모뎀 내장 NGFW',
              sourceUrl: 'https://www.fortinet.com/products/next-generation-firewall/entry-level',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '10 Gbps',
                'WAN': '3G/4G LTE built-in',
                'Interfaces': '16× GE RJ45 + 2× SFP',
              },
              children: [],
            },
            // ── Virtual ──
            {
              nodeId: 'fortinet-fortigate-vm',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate VM',
              nameKo: 'FortiGate VM',
              description: 'Virtual NGFW for VMware, Hyper-V, KVM, and cloud (AWS, Azure, GCP, OCI) environments',
              descriptionKo: 'VMware, Hyper-V, KVM 및 클라우드 (AWS, Azure, GCP, OCI) 환경용 가상 NGFW',
              sourceUrl: 'https://www.fortinet.com/products/private-cloud-security/fortigate-virtual-appliances',
              lifecycle: 'active',
              specs: {
                'Hypervisors': 'VMware ESXi, Microsoft Hyper-V, KVM, Xen',
                'Cloud': 'AWS, Azure, GCP, Oracle Cloud, IBM Cloud',
                'Max vCPU': 'Up to 32 vCPUs (license-dependent)',
                'Deployment': 'BYOL or Pay-as-you-go',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortigate-vmx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiGate VMX',
              nameKo: 'FortiGate VMX',
              description: 'Micro-segmentation virtual firewall for VMware NSX integration',
              descriptionKo: 'VMware NSX 통합용 마이크로 세그멘테이션 가상 방화벽',
              sourceUrl: 'https://www.fortinet.com/products/private-cloud-security/fortigate-vmx',
              lifecycle: 'active',
              specs: {
                'Platform': 'VMware NSX',
                'Use Case': 'East-West micro-segmentation',
              },
              children: [],
            },
          ],
        },
        // ── FortiProxy ──
        {
          nodeId: 'fortinet-fortiproxy',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiProxy',
          nameKo: 'FortiProxy',
          description: 'Secure web gateway (SWG) for advanced web filtering, DLP, and SSL inspection',
          descriptionKo: '고급 웹 필터링, DLP, SSL 검사를 위한 보안 웹 게이트웨이 (SWG)',
          sourceUrl: 'https://www.fortinet.com/products/secure-web-gateway/fortiproxy',
          infraNodeTypes: ['waf'],
          children: [],
        },
        // ── FortiDDoS ──
        {
          nodeId: 'fortinet-fortiddos',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiDDoS',
          nameKo: 'FortiDDoS',
          description: 'Dedicated DDoS protection appliance with 100% hardware-based detection and mitigation',
          descriptionKo: '100% 하드웨어 기반 탐지 및 완화를 제공하는 전용 DDoS 방어 어플라이언스',
          sourceUrl: 'https://www.fortinet.com/products/ddos-protection',
          infraNodeTypes: ['firewall'],
          children: [],
        },
        // ── FortiDeceptor ──
        {
          nodeId: 'fortinet-fortideceptor',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiDeceptor',
          nameKo: 'FortiDeceptor',
          description: 'Deception-based threat detection platform using decoys, lures, and honeypots',
          descriptionKo: '디코이, 루어, 허니팟을 활용한 디셉션 기반 위협 탐지 플랫폼',
          sourceUrl: 'https://www.fortinet.com/products/fortideceptor',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
        // ── FortiWeb ──
        {
          nodeId: 'fortinet-fortiweb',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiWeb',
          nameKo: 'FortiWeb',
          description: 'Web application firewall (WAF) with ML-based threat detection protecting web apps, APIs, and bots',
          descriptionKo: 'ML 기반 위협 탐지로 웹 앱, API, 봇을 보호하는 웹 애플리케이션 방화벽 (WAF)',
          sourceUrl: 'https://www.fortinet.com/products/web-application-firewall/fortiweb',
          infraNodeTypes: ['waf'],
          architectureRole: 'Web Application Protection / API Gateway Security',
          architectureRoleKo: '웹 애플리케이션 보호 / API 게이트웨이 보안',
          recommendedFor: [
            'OWASP Top 10 web application protection',
            'API security and bot mitigation',
            'PCI DSS compliance for web services',
          ],
          recommendedForKo: [
            'OWASP Top 10 웹 애플리케이션 보호',
            'API 보안 및 봇 완화',
            '웹 서비스 PCI DSS 컴플라이언스',
          ],
          children: [
            {
              nodeId: 'fortinet-fortiweb-100d',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiWeb 100D',
              nameKo: 'FortiWeb 100D',
              description: 'Entry-level WAF appliance for small and medium web applications',
              descriptionKo: '중소 규모 웹 애플리케이션용 엔트리급 WAF 어플라이언스',
              sourceUrl: 'https://www.fortinet.com/products/web-application-firewall/fortiweb',
              lifecycle: 'active',
              specs: {
                'HTTP Throughput': '100 Mbps',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiweb-400f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiWeb 400F',
              nameKo: 'FortiWeb 400F',
              description: 'Mid-range WAF for enterprise web applications with hardware-accelerated SSL',
              descriptionKo: '하드웨어 가속 SSL을 갖춘 엔터프라이즈 웹 애플리케이션용 미드레인지 WAF',
              sourceUrl: 'https://www.fortinet.com/products/web-application-firewall/fortiweb',
              lifecycle: 'active',
              specs: {
                'HTTP Throughput': '750 Mbps',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiweb-2000f',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiWeb 2000F',
              nameKo: 'FortiWeb 2000F',
              description: 'High-end WAF for large-scale enterprise and data center deployments',
              descriptionKo: '대규모 엔터프라이즈 및 데이터센터 배포용 하이엔드 WAF',
              sourceUrl: 'https://www.fortinet.com/products/web-application-firewall/fortiweb',
              lifecycle: 'active',
              specs: {
                'HTTP Throughput': '5 Gbps',
                'Form Factor': '2 RU',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiweb-vm',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiWeb VM',
              nameKo: 'FortiWeb VM',
              description: 'Virtual WAF for cloud and private data center environments (AWS, Azure, GCP)',
              descriptionKo: '클라우드 및 프라이빗 데이터센터 환경용 가상 WAF (AWS, Azure, GCP)',
              sourceUrl: 'https://www.fortinet.com/products/web-application-firewall/fortiweb',
              lifecycle: 'active',
              specs: {
                'Deployment': 'VMware, Hyper-V, KVM, AWS, Azure, GCP',
              },
              children: [],
            },
          ],
        },
        // ── FortiMail ──
        {
          nodeId: 'fortinet-fortimail',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiMail',
          nameKo: 'FortiMail',
          description: 'Secure email gateway with anti-spam, anti-malware, sandboxing, and DLP for inbound and outbound email',
          descriptionKo: '인바운드 및 아웃바운드 이메일을 위한 안티스팸, 안티멀웨어, 샌드박싱, DLP 기능의 보안 이메일 게이트웨이',
          sourceUrl: 'https://www.fortinet.com/products/email-security',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
        // ── FortiSandbox ──
        {
          nodeId: 'fortinet-fortisandbox',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiSandbox',
          nameKo: 'FortiSandbox',
          description: 'Advanced threat protection through sandboxing with AI/ML-based file analysis and zero-day detection',
          descriptionKo: 'AI/ML 기반 파일 분석 및 제로데이 탐지를 통한 샌드박싱 고급 위협 방어',
          sourceUrl: 'https://www.fortinet.com/products/sandbox/fortisandbox',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
        // ── FortiEDR ──
        {
          nodeId: 'fortinet-fortiedr',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiEDR',
          nameKo: 'FortiEDR',
          description: 'Endpoint detection and response with real-time pre- and post-infection protection and automated playbooks',
          descriptionKo: '실시간 감염 전후 보호 및 자동화된 플레이북을 갖춘 엔드포인트 탐지 및 대응',
          sourceUrl: 'https://www.fortinet.com/products/endpoint-security/fortiedr',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
        // ── FortiClient ──
        {
          nodeId: 'fortinet-forticlient',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiClient',
          nameKo: 'FortiClient',
          description: 'Unified endpoint security agent with VPN, ZTNA, vulnerability scanning, and web filtering',
          descriptionKo: 'VPN, ZTNA, 취약점 스캔, 웹 필터링 기능의 통합 엔드포인트 보안 에이전트',
          sourceUrl: 'https://www.fortinet.com/products/endpoint-security/forticlient',
          infraNodeTypes: ['vpn-gateway'],
          children: [],
        },
        // ── FortiIsolator ──
        {
          nodeId: 'fortinet-fortiisolator',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiIsolator',
          nameKo: 'FortiIsolator',
          description: 'Remote browser isolation solution protecting users from web-based threats via content rendering in isolation',
          descriptionKo: '격리된 콘텐츠 렌더링을 통해 웹 기반 위협으로부터 사용자를 보호하는 원격 브라우저 격리 솔루션',
          sourceUrl: 'https://www.fortinet.com/products/fortiisolator',
          infraNodeTypes: ['waf'],
          children: [],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // 2. SD-WAN & SASE
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-sdwan-sase',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'SD-WAN & SASE',
      nameKo: 'SD-WAN & SASE',
      description: 'Software-defined WAN and Secure Access Service Edge solutions',
      descriptionKo: '소프트웨어 정의 WAN 및 보안 액세스 서비스 에지 솔루션',
      sourceUrl: 'https://www.fortinet.com/products/sd-wan',
      infraNodeTypes: ['sd-wan', 'sase-gateway'],
      children: [
        // ── FortiSASE ──
        {
          nodeId: 'fortinet-fortisase',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiSASE',
          nameKo: 'FortiSASE',
          description: 'Cloud-delivered SASE solution combining SD-WAN, SWG, CASB, ZTNA, and FWaaS in a unified platform',
          descriptionKo: 'SD-WAN, SWG, CASB, ZTNA, FWaaS를 통합 플랫폼에서 제공하는 클라우드 기반 SASE 솔루션',
          sourceUrl: 'https://www.fortinet.com/products/sase',
          infraNodeTypes: ['sase-gateway'],
          architectureRole: 'Cloud Security Edge / Remote Access',
          architectureRoleKo: '클라우드 보안 에지 / 원격 액세스',
          recommendedFor: [
            'Remote and hybrid workforce secure access',
            'Branch-to-cloud direct connectivity',
            'SaaS application security and DLP',
          ],
          recommendedForKo: [
            '원격 및 하이브리드 근무자 보안 액세스',
            '지사에서 클라우드로의 직접 연결',
            'SaaS 애플리케이션 보안 및 DLP',
          ],
          children: [],
        },
        // ── Secure SD-WAN ──
        {
          nodeId: 'fortinet-secure-sdwan',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Secure SD-WAN',
          nameKo: 'Secure SD-WAN',
          description: 'Integrated SD-WAN within FortiGate NGFW providing application-aware routing, WAN optimization, and zero-trust security',
          descriptionKo: 'FortiGate NGFW에 통합된 SD-WAN으로 애플리케이션 인식 라우팅, WAN 최적화, 제로 트러스트 보안 제공',
          sourceUrl: 'https://www.fortinet.com/products/sd-wan',
          infraNodeTypes: ['sd-wan'],
          architectureRole: 'WAN Edge / Branch Connectivity',
          architectureRoleKo: 'WAN 에지 / 지사 연결',
          recommendedFor: [
            'Multi-site WAN with intelligent path selection',
            'MPLS-to-broadband migration',
            'Application-aware traffic steering',
          ],
          recommendedForKo: [
            '지능형 경로 선택이 적용된 멀티 사이트 WAN',
            'MPLS에서 브로드밴드로의 마이그레이션',
            '애플리케이션 인식 트래픽 스티어링',
          ],
          children: [],
        },
        // ── FortiExtender ──
        {
          nodeId: 'fortinet-fortiextender',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiExtender',
          nameKo: 'FortiExtender',
          description: 'LTE/5G wireless WAN extender for primary or backup connectivity with FortiGate management',
          descriptionKo: 'FortiGate 관리 기능을 갖춘 기본 또는 백업 연결용 LTE/5G 무선 WAN 익스텐더',
          sourceUrl: 'https://www.fortinet.com/products/fortiextender',
          infraNodeTypes: ['router'],
          children: [],
        },
        // ── FortiCASB ──
        {
          nodeId: 'fortinet-forticasb',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiCASB',
          nameKo: 'FortiCASB',
          description: 'Cloud access security broker providing visibility, compliance, data security, and threat protection for SaaS applications',
          descriptionKo: 'SaaS 애플리케이션에 대한 가시성, 컴플라이언스, 데이터 보안, 위협 방어를 제공하는 클라우드 액세스 보안 브로커',
          sourceUrl: 'https://www.fortinet.com/products/casb',
          infraNodeTypes: ['casb'],
          children: [],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // 3. Switching & Wireless
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-switching-wireless',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Switching & Wireless',
      nameKo: '스위칭 & 무선',
      description: 'Campus and data center switches, and wireless access points managed through FortiGate Security Fabric',
      descriptionKo: 'FortiGate 보안 패브릭을 통해 관리되는 캠퍼스 및 데이터센터 스위치, 무선 액세스 포인트',
      sourceUrl: 'https://www.fortinet.com/products/switches',
      infraNodeTypes: ['switch-l2', 'switch-l3'],
      children: [
        // ── FortiSwitch ──
        {
          nodeId: 'fortinet-fortiswitch',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiSwitch',
          nameKo: 'FortiSwitch',
          description: 'Secure Ethernet switches managed via FortiGate with integrated security policies, spanning campus to data center deployments',
          descriptionKo: 'FortiGate를 통해 관리되는 보안 이더넷 스위치, 통합 보안 정책 적용, 캠퍼스에서 데이터센터까지 지원',
          sourceUrl: 'https://www.fortinet.com/products/switches',
          infraNodeTypes: ['switch-l2', 'switch-l3'],
          architectureRole: 'Campus Access / Distribution / Data Center ToR',
          architectureRoleKo: '캠퍼스 액세스 / 디스트리뷰션 / 데이터센터 ToR',
          recommendedFor: [
            'FortiGate-managed campus access layer',
            'PoE for IP phones, cameras, and APs',
            'Data center top-of-rack switching',
            'Secure network segmentation with FortiLink',
          ],
          recommendedForKo: [
            'FortiGate 관리형 캠퍼스 액세스 레이어',
            'IP 전화기, 카메라, AP용 PoE',
            '데이터센터 탑 오브 랙 스위칭',
            'FortiLink 기반 보안 네트워크 세그멘테이션',
          ],
          children: [
            // ── Campus Series ──
            {
              nodeId: 'fortinet-fortiswitch-100-series',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 100 Series',
              nameKo: 'FortiSwitch 100 시리즈',
              description: 'Entry-level campus access switches with 8/24/48 GE ports and PoE options',
              descriptionKo: '8/24/48 GE 포트 및 PoE 옵션을 갖춘 엔트리급 캠퍼스 액세스 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-secure-access',
              lifecycle: 'active',
              specs: {
                'Ports': '8/24/48× GE RJ45',
                'Uplinks': '4× GE SFP',
                'PoE Budget': 'Up to 370W',
                'Switching Capacity': 'Up to 176 Gbps',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiswitch-200-series',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 200 Series',
              nameKo: 'FortiSwitch 200 시리즈',
              description: 'Mid-range campus switches with Layer 3 routing, 10GE uplinks, and enhanced PoE',
              descriptionKo: 'L3 라우팅, 10GE 업링크, 향상된 PoE를 제공하는 미드레인지 캠퍼스 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-secure-access',
              lifecycle: 'active',
              specs: {
                'Ports': '24/48× GE RJ45',
                'Uplinks': '4× 10GE SFP+',
                'PoE Budget': 'Up to 740W',
                'Switching Capacity': 'Up to 256 Gbps',
                'L3 Routing': 'Static, OSPF, RIP',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiswitch-400-series',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 400 Series',
              nameKo: 'FortiSwitch 400 시리즈',
              description: 'High-performance campus aggregation switches with 25GE/40GE uplinks and multi-rate access ports',
              descriptionKo: '25GE/40GE 업링크 및 멀티레이트 액세스 포트를 갖춘 고성능 캠퍼스 집선 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-secure-access',
              lifecycle: 'active',
              specs: {
                'Ports': '24/48× multi-rate (1G/2.5G/5G/10G)',
                'Uplinks': '4× 25GE SFP28 or 2× 40GE QSFP+',
                'PoE Budget': 'Up to 1480W',
                'Switching Capacity': 'Up to 880 Gbps',
              },
              children: [],
            },
            // ── Data Center Series ──
            {
              nodeId: 'fortinet-fortiswitch-1024e',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 1024E',
              nameKo: 'FortiSwitch 1024E',
              description: 'Data center switch with 24× 10GE SFP+ and 2× 40GE QSFP+ uplinks',
              descriptionKo: '24× 10GE SFP+ 및 2× 40GE QSFP+ 업링크를 갖춘 데이터센터 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-data-center',
              lifecycle: 'active',
              specs: {
                'Ports': '24× 10GE SFP+',
                'Uplinks': '2× 40GE QSFP+',
                'Switching Capacity': '480 Gbps',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiswitch-1048e',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 1048E',
              nameKo: 'FortiSwitch 1048E',
              description: 'Data center switch with 48× 10GE SFP+ and 6× 40GE QSFP+ uplinks',
              descriptionKo: '48× 10GE SFP+ 및 6× 40GE QSFP+ 업링크를 갖춘 데이터센터 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-data-center',
              lifecycle: 'active',
              specs: {
                'Ports': '48× 10GE SFP+',
                'Uplinks': '6× 40GE QSFP+',
                'Switching Capacity': '1.44 Tbps',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiswitch-3032e',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 3032E',
              nameKo: 'FortiSwitch 3032E',
              description: 'High-density data center spine switch with 32× 100GE QSFP28 ports',
              descriptionKo: '32× 100GE QSFP28 포트를 갖춘 고밀도 데이터센터 스파인 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-data-center',
              lifecycle: 'active',
              specs: {
                'Ports': '32× 100GE QSFP28',
                'Switching Capacity': '6.4 Tbps',
                'Form Factor': '1 RU',
              },
              children: [],
            },
            // ── Rugged Series ──
            {
              nodeId: 'fortinet-fortiswitch-112d-poe',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 112D-POE',
              nameKo: 'FortiSwitch 112D-POE',
              description: 'Ruggedized 8-port PoE switch for industrial OT environments with DIN rail mount',
              descriptionKo: '산업 OT 환경용 DIN 레일 마운트 러기드 8포트 PoE 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-rugged',
              lifecycle: 'active',
              specs: {
                'Ports': '8× GE PoE',
                'Uplinks': '4× GE SFP',
                'Rating': 'IP30',
                'Operating Temp': '-40°C to 75°C',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiswitch-124d-poe',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiSwitch 124D-POE',
              nameKo: 'FortiSwitch 124D-POE',
              description: 'Ruggedized 24-port PoE switch for industrial environments with DIN rail mount',
              descriptionKo: '산업 환경용 DIN 레일 마운트 러기드 24포트 PoE 스위치',
              sourceUrl: 'https://www.fortinet.com/products/switches/fortiswitch-rugged',
              lifecycle: 'active',
              specs: {
                'Ports': '24× GE PoE',
                'Uplinks': '4× GE SFP',
                'Rating': 'IP30',
                'Operating Temp': '-40°C to 75°C',
              },
              children: [],
            },
          ],
        },
        // ── FortiAP ──
        {
          nodeId: 'fortinet-fortiap',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiAP Wireless Access Points',
          nameKo: 'FortiAP 무선 액세스 포인트',
          description: 'Enterprise Wi-Fi 6/6E access points managed via FortiGate or FortiCloud, with integrated WIDS/WIPS',
          descriptionKo: 'FortiGate 또는 FortiCloud를 통해 관리되는 엔터프라이즈 Wi-Fi 6/6E 액세스 포인트, 통합 WIDS/WIPS',
          sourceUrl: 'https://www.fortinet.com/products/wireless/access-points',
          infraNodeTypes: ['switch-l2'],
          children: [
            // ── Indoor ──
            {
              nodeId: 'fortinet-fortiap-231g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiAP 231G',
              nameKo: 'FortiAP 231G',
              description: 'Tri-band Wi-Fi 6E indoor AP with 2× 2.5GE ports, up to 3.9 Gbps aggregate throughput',
              descriptionKo: '2× 2.5GE 포트, 최대 3.9 Gbps 집합 처리량의 트라이밴드 Wi-Fi 6E 실내 AP',
              sourceUrl: 'https://www.fortinet.com/products/wireless/access-points',
              lifecycle: 'active',
              specs: {
                'Standard': 'Wi-Fi 6E (802.11ax)',
                'Bands': 'Tri-band (2.4G + 5G + 6G)',
                'Max Throughput': '3.9 Gbps',
                'Ethernet': '2× 2.5GE',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiap-431g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiAP 431G',
              nameKo: 'FortiAP 431G',
              description: 'High-density tri-band Wi-Fi 6E indoor AP with 2× 5GE ports, up to 8.3 Gbps',
              descriptionKo: '2× 5GE 포트, 최대 8.3 Gbps의 고밀도 트라이밴드 Wi-Fi 6E 실내 AP',
              sourceUrl: 'https://www.fortinet.com/products/wireless/access-points',
              lifecycle: 'active',
              specs: {
                'Standard': 'Wi-Fi 6E (802.11ax)',
                'Bands': 'Tri-band (2.4G + 5G + 6G)',
                'Max Throughput': '8.3 Gbps',
                'Ethernet': '2× 5GE',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiap-441k',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiAP 441K',
              nameKo: 'FortiAP 441K',
              description: 'Premium Wi-Fi 7 indoor AP with 10GE uplink, ultra-high density deployment',
              descriptionKo: '10GE 업링크, 초고밀도 배포를 위한 프리미엄 Wi-Fi 7 실내 AP',
              sourceUrl: 'https://www.fortinet.com/products/wireless/access-points',
              lifecycle: 'active',
              specs: {
                'Standard': 'Wi-Fi 7 (802.11be)',
                'Bands': 'Tri-band (2.4G + 5G + 6G)',
                'Ethernet': '1× 10GE + 1× 5GE',
              },
              children: [],
            },
            // ── Outdoor ──
            {
              nodeId: 'fortinet-fortiap-234g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiAP 234G',
              nameKo: 'FortiAP 234G',
              description: 'Outdoor tri-band Wi-Fi 6E AP with IP67 rating for harsh outdoor environments',
              descriptionKo: 'IP67 등급의 가혹한 외부 환경용 야외 트라이밴드 Wi-Fi 6E AP',
              sourceUrl: 'https://www.fortinet.com/products/wireless/outdoor-access-points',
              lifecycle: 'active',
              specs: {
                'Standard': 'Wi-Fi 6E (802.11ax)',
                'Rating': 'IP67',
                'Operating Temp': '-40°C to 60°C',
              },
              children: [],
            },
            {
              nodeId: 'fortinet-fortiap-432g',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'FortiAP 432G',
              nameKo: 'FortiAP 432G',
              description: 'High-performance outdoor Wi-Fi 6E AP with IP67 rating and directional antenna options',
              descriptionKo: 'IP67 등급 및 지향성 안테나 옵션을 갖춘 고성능 야외 Wi-Fi 6E AP',
              sourceUrl: 'https://www.fortinet.com/products/wireless/outdoor-access-points',
              lifecycle: 'active',
              specs: {
                'Standard': 'Wi-Fi 6E (802.11ax)',
                'Rating': 'IP67',
                'Antenna': 'Internal + External options',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // 4. Security Operations
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-secops',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Security Operations',
      nameKo: '보안 운영',
      description: 'SIEM, SOAR, analytics, and extended detection & response (XDR) solutions',
      descriptionKo: 'SIEM, SOAR, 분석, 확장된 탐지 및 대응 (XDR) 솔루션',
      sourceUrl: 'https://www.fortinet.com/products/security-operations',
      infraNodeTypes: ['siem', 'soar'],
      children: [
        // ── FortiSIEM ──
        {
          nodeId: 'fortinet-fortisiem',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiSIEM',
          nameKo: 'FortiSIEM',
          description: 'Unified SIEM platform with UEBA, asset discovery, compliance reporting, and real-time event correlation',
          descriptionKo: 'UEBA, 자산 검색, 컴플라이언스 보고, 실시간 이벤트 상관분석을 제공하는 통합 SIEM 플랫폼',
          sourceUrl: 'https://www.fortinet.com/products/siem/fortisiem',
          infraNodeTypes: ['siem'],
          architectureRole: 'Security Operations Center (SOC)',
          architectureRoleKo: '보안 운영 센터 (SOC)',
          recommendedFor: [
            'Enterprise-wide log aggregation and correlation',
            'UEBA-based insider threat detection',
            'Compliance reporting (PCI DSS, HIPAA, SOX)',
          ],
          recommendedForKo: [
            '전사적 로그 집계 및 상관분석',
            'UEBA 기반 내부자 위협 탐지',
            '컴플라이언스 보고 (PCI DSS, HIPAA, SOX)',
          ],
          children: [],
        },
        // ── FortiSOAR ──
        {
          nodeId: 'fortinet-fortisoar',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiSOAR',
          nameKo: 'FortiSOAR',
          description: 'Security orchestration, automation, and response platform with 350+ connectors and visual playbook builder',
          descriptionKo: '350+ 커넥터와 시각적 플레이북 빌더를 갖춘 보안 오케스트레이션, 자동화 및 대응 플랫폼',
          sourceUrl: 'https://www.fortinet.com/products/fortisoar',
          infraNodeTypes: ['soar'],
          architectureRole: 'SOC Automation / Incident Response',
          architectureRoleKo: 'SOC 자동화 / 인시던트 대응',
          recommendedFor: [
            'SOC workflow automation and case management',
            'Multi-vendor security tool orchestration',
            'Incident response playbook execution',
          ],
          recommendedForKo: [
            'SOC 워크플로우 자동화 및 케이스 관리',
            '멀티 벤더 보안 도구 오케스트레이션',
            '인시던트 대응 플레이북 실행',
          ],
          children: [],
        },
        // ── FortiAnalyzer ──
        {
          nodeId: 'fortinet-fortianalyzer',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiAnalyzer',
          nameKo: 'FortiAnalyzer',
          description: 'Centralized log management, analytics, and reporting platform for the Fortinet Security Fabric',
          descriptionKo: '포티넷 보안 패브릭을 위한 중앙 집중식 로그 관리, 분석 및 보고 플랫폼',
          sourceUrl: 'https://www.fortinet.com/products/management/fortianalyzer',
          infraNodeTypes: ['siem'],
          children: [],
        },
        // ── FortiXDR ──
        {
          nodeId: 'fortinet-fortixdr',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiXDR',
          nameKo: 'FortiXDR',
          description: 'Extended detection and response with AI-driven investigation and automated incident triage',
          descriptionKo: 'AI 기반 조사 및 자동화된 인시던트 분류를 제공하는 확장된 탐지 및 대응',
          sourceUrl: 'https://www.fortinet.com/products/fortixdr',
          infraNodeTypes: ['siem'],
          children: [],
        },
        // ── FortiNDR ──
        {
          nodeId: 'fortinet-fortindr',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiNDR',
          nameKo: 'FortiNDR',
          description: 'Network detection and response using AI and deep neural networks for network traffic anomaly detection',
          descriptionKo: 'AI 및 심층 신경망을 활용한 네트워크 트래픽 이상 탐지 기반 네트워크 탐지 및 대응',
          sourceUrl: 'https://www.fortinet.com/products/network-detection-response',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
        // ── FortiRecon ──
        {
          nodeId: 'fortinet-fortirecon',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiRecon',
          nameKo: 'FortiRecon',
          description: 'Digital risk protection service for external attack surface management, brand protection, and dark web monitoring',
          descriptionKo: '외부 공격 표면 관리, 브랜드 보호, 다크 웹 모니터링을 위한 디지털 리스크 보호 서비스',
          sourceUrl: 'https://www.fortinet.com/products/fortirecon',
          infraNodeTypes: ['siem'],
          children: [],
        },
        // ── FortiGuard Labs ──
        {
          nodeId: 'fortinet-fortiguard',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiGuard Security Services',
          nameKo: 'FortiGuard 보안 서비스',
          description: 'AI-powered threat intelligence and security subscription services including IPS, antivirus, web filtering, and sandboxing',
          descriptionKo: 'IPS, 안티바이러스, 웹 필터링, 샌드박싱을 포함한 AI 기반 위협 인텔리전스 및 보안 구독 서비스',
          sourceUrl: 'https://www.fortinet.com/fortiguard/labs',
          infraNodeTypes: ['ids-ips'],
          children: [],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // 5. Zero Trust & Identity
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-zero-trust',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Zero Trust & Identity',
      nameKo: '제로 트러스트 & 아이덴티티',
      description: 'Network access control, identity management, multi-factor authentication, and zero trust network access',
      descriptionKo: '네트워크 접근 제어, ID 관리, 다중 인증, 제로 트러스트 네트워크 액세스',
      sourceUrl: 'https://www.fortinet.com/solutions/enterprise-midsize-business/network-access',
      infraNodeTypes: ['nac', 'ztna-broker'],
      children: [
        // ── FortiNAC ──
        {
          nodeId: 'fortinet-fortinac',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiNAC',
          nameKo: 'FortiNAC',
          description: 'Network access control solution for IoT device visibility, profiling, and automated policy enforcement',
          descriptionKo: 'IoT 디바이스 가시성, 프로파일링, 자동화된 정책 적용을 위한 네트워크 접근 제어 솔루션',
          sourceUrl: 'https://www.fortinet.com/products/network-access-control',
          infraNodeTypes: ['nac'],
          architectureRole: 'Network Access Control / IoT Security',
          architectureRoleKo: '네트워크 접근 제어 / IoT 보안',
          recommendedFor: [
            'IoT/OT device visibility and profiling',
            'BYOD onboarding and compliance enforcement',
            'Automated network segmentation based on device type',
          ],
          recommendedForKo: [
            'IoT/OT 디바이스 가시성 및 프로파일링',
            'BYOD 온보딩 및 컴플라이언스 적용',
            '디바이스 유형 기반 자동 네트워크 세그멘테이션',
          ],
          children: [],
        },
        // ── FortiAuthenticator ──
        {
          nodeId: 'fortinet-fortiauthenticator',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiAuthenticator',
          nameKo: 'FortiAuthenticator',
          description: 'Centralized identity management and authentication server with LDAP, RADIUS, SAML, and SSO support',
          descriptionKo: 'LDAP, RADIUS, SAML, SSO를 지원하는 중앙 집중식 ID 관리 및 인증 서버',
          sourceUrl: 'https://www.fortinet.com/products/identity-access-management/fortiauthenticator',
          infraNodeTypes: ['mfa', 'ldap-ad'],
          children: [],
        },
        // ── FortiToken ──
        {
          nodeId: 'fortinet-fortitoken',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiToken',
          nameKo: 'FortiToken',
          description: 'Multi-factor authentication tokens (hardware and mobile) for strong identity verification',
          descriptionKo: '강력한 신원 확인을 위한 다중 인증 토큰 (하드웨어 및 모바일)',
          sourceUrl: 'https://www.fortinet.com/products/identity-access-management/fortitoken',
          infraNodeTypes: ['mfa'],
          children: [],
        },
        // ── ZTNA ──
        {
          nodeId: 'fortinet-ztna',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiZTNA (Zero Trust Network Access)',
          nameKo: 'FortiZTNA (제로 트러스트 네트워크 액세스)',
          description: 'Zero trust network access integrated into FortiGate and FortiClient for per-session identity and posture verification',
          descriptionKo: 'FortiGate와 FortiClient에 통합된 세션별 신원 및 상태 검증 기반 제로 트러스트 네트워크 액세스',
          sourceUrl: 'https://www.fortinet.com/products/zero-trust-network-access',
          infraNodeTypes: ['ztna-broker'],
          architectureRole: 'Zero Trust Access Proxy',
          architectureRoleKo: '제로 트러스트 액세스 프록시',
          recommendedFor: [
            'VPN replacement with per-application access control',
            'Remote worker application access with continuous posture checks',
            'Microsegmentation of application access',
          ],
          recommendedForKo: [
            '애플리케이션별 접근 제어를 통한 VPN 대체',
            '지속적 상태 점검이 적용된 원격 근무자 애플리케이션 액세스',
            '애플리케이션 액세스의 마이크로 세그멘테이션',
          ],
          children: [],
        },
        // ── FortiDLP ──
        {
          nodeId: 'fortinet-fortidlp',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiDLP',
          nameKo: 'FortiDLP',
          description: 'Data loss prevention solution with endpoint, cloud, and email DLP policies and insider risk management',
          descriptionKo: '엔드포인트, 클라우드, 이메일 DLP 정책 및 내부자 위험 관리 기능의 데이터 유출 방지 솔루션',
          sourceUrl: 'https://www.fortinet.com/products/data-loss-prevention',
          infraNodeTypes: ['dlp'],
          children: [],
        },
        // ── FortiPAM ──
        {
          nodeId: 'fortinet-fortipam',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiPAM',
          nameKo: 'FortiPAM',
          description: 'Privileged access management for securing and monitoring access to critical infrastructure and applications',
          descriptionKo: '중요 인프라 및 애플리케이션에 대한 접근 보안 및 모니터링을 위한 권한 있는 액세스 관리',
          sourceUrl: 'https://www.fortinet.com/products/privileged-access-management',
          infraNodeTypes: ['iam'],
          children: [],
        },
      ],
    },

    // ═══════════════════════════════════════════════════════════════════════
    // 6. Management & Analytics
    // ═══════════════════════════════════════════════════════════════════════
    {
      nodeId: 'fortinet-management',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Management & Analytics',
      nameKo: '관리 & 분석',
      description: 'Centralized management, cloud-based operations, and migration tools for the Fortinet Security Fabric',
      descriptionKo: '포티넷 보안 패브릭을 위한 중앙 집중 관리, 클라우드 기반 운영, 마이그레이션 도구',
      sourceUrl: 'https://www.fortinet.com/products/management',
      infraNodeTypes: ['private-cloud'],
      children: [
        // ── FortiManager ──
        {
          nodeId: 'fortinet-fortimanager',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiManager',
          nameKo: 'FortiManager',
          description: 'Centralized network security management for FortiGate devices — policy management, firmware updates, and SD-WAN orchestration',
          descriptionKo: 'FortiGate 디바이스를 위한 중앙 집중식 네트워크 보안 관리 — 정책 관리, 펌웨어 업데이트, SD-WAN 오케스트레이션',
          sourceUrl: 'https://www.fortinet.com/products/management/fortimanager',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Central Management / NOC',
          architectureRoleKo: '중앙 관리 / NOC',
          recommendedFor: [
            'Multi-site FortiGate centralized policy management',
            'SD-WAN overlay orchestration',
            'Firmware and configuration lifecycle management',
          ],
          recommendedForKo: [
            '멀티 사이트 FortiGate 중앙 정책 관리',
            'SD-WAN 오버레이 오케스트레이션',
            '펌웨어 및 구성 수명주기 관리',
          ],
          children: [],
        },
        // ── FortiCloud ──
        {
          nodeId: 'fortinet-forticloud',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiCloud',
          nameKo: 'FortiCloud',
          description: 'Cloud-based management and analytics portal for FortiGate, FortiSwitch, and FortiAP devices',
          descriptionKo: 'FortiGate, FortiSwitch, FortiAP 디바이스를 위한 클라우드 기반 관리 및 분석 포털',
          sourceUrl: 'https://www.fortinet.com/products/management/forticloud',
          infraNodeTypes: ['private-cloud'],
          children: [],
        },
        // ── FortiConverter ──
        {
          nodeId: 'fortinet-forticonverter',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiConverter',
          nameKo: 'FortiConverter',
          description: 'Migration tool for converting third-party firewall policies to FortiGate configuration',
          descriptionKo: '서드파티 방화벽 정책을 FortiGate 구성으로 변환하는 마이그레이션 도구',
          sourceUrl: 'https://www.fortinet.com/products/management/forticonverter',
          infraNodeTypes: ['private-cloud'],
          children: [],
        },
        // ── FortiAIOps ──
        {
          nodeId: 'fortinet-fortiaiops',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiAIOps',
          nameKo: 'FortiAIOps',
          description: 'AI-powered IT operations platform for network anomaly detection, root cause analysis, and proactive remediation',
          descriptionKo: '네트워크 이상 감지, 근본 원인 분석, 사전 대응을 위한 AI 기반 IT 운영 플랫폼',
          sourceUrl: 'https://www.fortinet.com/products/fortiaiops',
          infraNodeTypes: ['private-cloud'],
          children: [],
        },
        // ── FortiPortal ──
        {
          nodeId: 'fortinet-fortiportal',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiPortal',
          nameKo: 'FortiPortal',
          description: 'Multi-tenant management and analytics portal for MSSPs and large enterprises',
          descriptionKo: 'MSSP 및 대기업을 위한 멀티테넌트 관리 및 분석 포털',
          sourceUrl: 'https://www.fortinet.com/products/management/fortiportal',
          infraNodeTypes: ['private-cloud'],
          children: [],
        },
        // ── FortiMonitor ──
        {
          nodeId: 'fortinet-fortimonitor',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'FortiMonitor',
          nameKo: 'FortiMonitor',
          description: 'Network performance monitoring and digital experience management for hybrid networks',
          descriptionKo: '하이브리드 네트워크를 위한 네트워크 성능 모니터링 및 디지털 경험 관리',
          sourceUrl: 'https://www.fortinet.com/products/fortimonitor',
          infraNodeTypes: ['private-cloud'],
          children: [],
        },
      ],
    },
  ],
};
