/**
 * HPE Aruba Networking -- Full Product Catalog
 *
 * Hierarchical product tree covering Wireless (Access Points, Controllers),
 * Switching (CX Series), Network Security (ClearPass, EdgeConnect SD-WAN),
 * Servers (ProLiant, Synergy), and Storage (Alletra) categories.
 *
 * Data sourced from https://www.arubanetworks.com/products/
 * Last crawled: 2026-02-23
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// HPE Aruba Networking Product Catalog
// ---------------------------------------------------------------------------

export const hpeArubaCatalog: VendorCatalog = {
  vendorId: 'hpe-aruba',
  vendorName: 'HPE Aruba Networking',
  vendorNameKo: 'HPE 아루바 네트워킹',
  headquarters: 'San Jose, CA, USA',
  website: 'https://www.arubanetworks.com',
  productPageUrl: 'https://www.arubanetworks.com/products/',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-23',
  crawlSource: 'https://www.arubanetworks.com/products/',
  stats: { totalProducts: 38, maxDepth: 2, categoriesCount: 5 },
  products: [
    // =====================================================================
    // 1. Wireless
    // =====================================================================
    {
      nodeId: 'hpe-aruba-wireless',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Wireless',
      nameKo: '무선',
      description:
        'HPE Aruba wireless networking portfolio including Wi-Fi 6, Wi-Fi 6E, and Wi-Fi 7 access points and centralized mobility controllers for enterprise campus and branch deployments',
      descriptionKo:
        '엔터프라이즈 캠퍼스 및 지사 배포를 위한 Wi-Fi 6, Wi-Fi 6E, Wi-Fi 7 액세스 포인트 및 중앙집중형 모빌리티 컨트롤러를 포함하는 HPE 아루바 무선 네트워킹 포트폴리오',
      sourceUrl: 'https://www.arubanetworks.com/products/wireless/',
      infraNodeTypes: ['wireless-ap'],
      children: [
        // -- Aruba Access Points --
        {
          nodeId: 'hpe-aruba-access-points',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Aruba Access Points',
          nameKo: '아루바 액세스 포인트',
          description:
            'Enterprise-grade indoor and outdoor wireless access points spanning Wi-Fi 6 through Wi-Fi 7 with IoT-ready radios and AI-powered RF management',
          descriptionKo:
            'IoT 지원 라디오와 AI 기반 RF 관리를 갖춘 Wi-Fi 6부터 Wi-Fi 7까지의 엔터프라이즈급 실내외 무선 액세스 포인트',
          sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/',
          infraNodeTypes: ['wireless-ap'],
          architectureRole: 'Wireless Access Layer',
          architectureRoleKo: '무선 액세스 레이어',
          recommendedFor: [
            'Enterprise campus Wi-Fi coverage',
            'High-density environments (auditoriums, stadiums, conference halls)',
            'Outdoor and harsh environment deployments',
            'IoT and location services with BLE/Zigbee',
            'Education and healthcare wireless infrastructure',
          ],
          recommendedForKo: [
            '엔터프라이즈 캠퍼스 Wi-Fi 커버리지',
            '고밀도 환경 (강당, 경기장, 컨퍼런스 홀)',
            '실외 및 가혹한 환경 배포',
            'BLE/Zigbee 기반 IoT 및 위치 서비스',
            '교육 및 의료 무선 인프라',
          ],
          supportedProtocols: [
            'Wi-Fi 6 (802.11ax)',
            'Wi-Fi 6E (802.11ax 6GHz)',
            'Wi-Fi 7 (802.11be)',
            'BLE 5.0',
            'Zigbee',
            '802.1X',
            'WPA3',
            'RADIUS',
          ],
          haFeatures: [
            'AP clustering for controller failover',
            'Dual uplink Ethernet for link redundancy',
            'Instant AP (IAP) autonomous mode fallback',
            'Zero-touch provisioning via Aruba Central',
          ],
          securityCapabilities: [
            'WPA3-Enterprise (192-bit)',
            'Enhanced Open (OWE)',
            'Dynamic segmentation with PEF (Policy Enforcement Firewall)',
            'Rogue AP detection and containment',
            'WIDS/WIPS (Wireless Intrusion Detection/Prevention)',
            'Air Monitor mode',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-ap-735',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba AP-735',
              nameKo: '아루바 AP-735',
              description:
                'Wi-Fi 7 flagship tri-band access point with 6GHz 320MHz channel support for maximum throughput and ultra-low latency enterprise wireless',
              descriptionKo:
                '최대 처리량과 초저지연 엔터프라이즈 무선을 위한 6GHz 320MHz 채널 지원 Wi-Fi 7 플래그십 트라이밴드 액세스 포인트',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/ap-730-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '18.4 Gbps',
              architectureRole: 'Wi-Fi 7 High-Density Wireless Access',
              architectureRoleKo: 'Wi-Fi 7 고밀도 무선 액세스',
              recommendedFor: [
                'Next-generation Wi-Fi 7 campus deployments',
                'Ultra-high-density environments requiring 320MHz channels',
                'Latency-sensitive applications (real-time collaboration, AR/VR)',
                'Future-proof enterprise wireless refresh',
              ],
              recommendedForKo: [
                '차세대 Wi-Fi 7 캠퍼스 배포',
                '320MHz 채널이 필요한 초고밀도 환경',
                '지연에 민감한 애플리케이션 (실시간 협업, AR/VR)',
                '미래 대비 엔터프라이즈 무선 리프레시',
              ],
              supportedProtocols: ['Wi-Fi 7 (802.11be)', '802.1X', 'WPA3', 'BLE 5.4', 'Zigbee'],
              haFeatures: ['AP clustering', 'Dual Ethernet uplink', 'IAP failover'],
              securityCapabilities: ['WPA3-Enterprise', 'OWE', 'Dynamic Segmentation', 'WIDS/WIPS'],
              specs: {
                'Wi-Fi Standard': 'Wi-Fi 7 (802.11be)',
                'Max Data Rate': '18.4 Gbps aggregate',
                'Radio Bands': '2.4GHz / 5GHz / 6GHz tri-band',
                'Max Channel Width': '320 MHz (6GHz)',
                'MIMO Configuration': 'Up to 4x4:4 per radio',
                'MLO Support': 'Multi-Link Operation supported',
                'IoT Radios': 'BLE 5.4, Zigbee',
                'Ethernet Ports': '1x 10GbE + 1x 5GbE',
                'PoE Requirement': '802.3bt (PoE++)',
                'Deployment': 'Indoor',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-ap-655',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba AP-655',
              nameKo: '아루바 AP-655',
              description:
                'Wi-Fi 6E tri-band indoor access point with 6GHz band support delivering up to 3.9 Gbps for high-performance enterprise wireless',
              descriptionKo:
                '고성능 엔터프라이즈 무선을 위해 최대 3.9 Gbps를 제공하는 6GHz 대역 지원 Wi-Fi 6E 트라이밴드 실내 액세스 포인트',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/ap-650-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '3.9 Gbps',
              architectureRole: 'Wi-Fi 6E High-Performance Wireless Access',
              architectureRoleKo: 'Wi-Fi 6E 고성능 무선 액세스',
              recommendedFor: [
                'Enterprise campus Wi-Fi 6E migration',
                'High-density office and meeting room deployments',
                'IoT convergence with BLE and Zigbee',
                'Healthcare and education environments',
              ],
              recommendedForKo: [
                '엔터프라이즈 캠퍼스 Wi-Fi 6E 마이그레이션',
                '고밀도 사무실 및 회의실 배포',
                'BLE 및 Zigbee를 통한 IoT 통합',
                '의료 및 교육 환경',
              ],
              supportedProtocols: ['Wi-Fi 6E (802.11ax)', '802.1X', 'WPA3', 'BLE 5.0', 'Zigbee'],
              haFeatures: ['AP clustering', 'Dual Ethernet uplink', 'IAP failover'],
              securityCapabilities: ['WPA3-Enterprise', 'OWE', 'Dynamic Segmentation', 'WIDS/WIPS'],
              specs: {
                'Wi-Fi Standard': 'Wi-Fi 6E (802.11ax)',
                'Max Data Rate': '3.9 Gbps aggregate',
                'Radio Bands': '2.4GHz / 5GHz / 6GHz tri-band',
                'MIMO Configuration': '4x4:4 (5GHz), 2x2:2 (2.4/6GHz)',
                'IoT Radios': 'BLE 5.0, Zigbee',
                'Ethernet Ports': '1x 2.5GbE + 1x 1GbE',
                'PoE Requirement': '802.3at (PoE+)',
                'Deployment': 'Indoor',
                'Antenna Type': 'Internal omni-directional',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-ap-635',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba AP-635',
              nameKo: '아루바 AP-635',
              description:
                'Wi-Fi 6E dual-band indoor access point delivering up to 3.6 Gbps for cost-effective enterprise wireless upgrades',
              descriptionKo:
                '비용 효율적인 엔터프라이즈 무선 업그레이드를 위해 최대 3.6 Gbps를 제공하는 Wi-Fi 6E 듀얼밴드 실내 액세스 포인트',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/ap-630-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '3.6 Gbps',
              architectureRole: 'Wi-Fi 6E Standard Wireless Access',
              architectureRoleKo: 'Wi-Fi 6E 표준 무선 액세스',
              recommendedFor: [
                'Enterprise Wi-Fi 6E refresh at scale',
                'Medium-density office environments',
                'Cost-effective 6GHz deployment',
                'Branch office wireless standardization',
              ],
              recommendedForKo: [
                '대규모 엔터프라이즈 Wi-Fi 6E 리프레시',
                '중밀도 사무실 환경',
                '비용 효율적인 6GHz 배포',
                '지사 무선 표준화',
              ],
              supportedProtocols: ['Wi-Fi 6E (802.11ax)', '802.1X', 'WPA3', 'BLE 5.0'],
              haFeatures: ['AP clustering', 'IAP failover'],
              securityCapabilities: ['WPA3-Enterprise', 'OWE', 'Dynamic Segmentation', 'WIDS/WIPS'],
              specs: {
                'Wi-Fi Standard': 'Wi-Fi 6E (802.11ax)',
                'Max Data Rate': '3.6 Gbps aggregate',
                'Radio Bands': '5GHz / 6GHz dual-band',
                'MIMO Configuration': '2x2:2 per radio',
                'IoT Radios': 'BLE 5.0',
                'Ethernet Ports': '1x 2.5GbE',
                'PoE Requirement': '802.3at (PoE+)',
                'Deployment': 'Indoor',
                'Antenna Type': 'Internal omni-directional',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-ap-567',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba AP-567',
              nameKo: '아루바 AP-567',
              description:
                'Wi-Fi 6 outdoor ruggedized access point with IP67 rating and external antenna connectors for harsh environment deployments',
              descriptionKo:
                'IP67 등급과 외부 안테나 커넥터를 갖춘 가혹한 환경 배포용 Wi-Fi 6 실외 강화 액세스 포인트',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/ap-560-series/',
              lifecycle: 'active',
              formFactor: 'rugged',
              licensingModel: 'subscription',
              maxThroughput: '2.4 Gbps',
              architectureRole: 'Outdoor / Industrial Wireless Access',
              architectureRoleKo: '실외 / 산업 무선 액세스',
              recommendedFor: [
                'Outdoor campus and parking lot Wi-Fi',
                'Stadium and large venue coverage',
                'Industrial and manufacturing floor deployments',
                'Extreme temperature and weather environments',
              ],
              recommendedForKo: [
                '실외 캠퍼스 및 주차장 Wi-Fi',
                '경기장 및 대형 행사장 커버리지',
                '산업 및 제조 현장 배포',
                '극한 온도 및 날씨 환경',
              ],
              supportedProtocols: ['Wi-Fi 6 (802.11ax)', '802.1X', 'WPA3', 'BLE 5.0'],
              haFeatures: ['AP clustering', 'Mesh networking', 'IAP failover'],
              securityCapabilities: ['WPA3-Enterprise', 'Dynamic Segmentation', 'WIDS/WIPS'],
              specs: {
                'Wi-Fi Standard': 'Wi-Fi 6 (802.11ax)',
                'Max Data Rate': '2.4 Gbps aggregate',
                'Radio Bands': '2.4GHz / 5GHz dual-band',
                'MIMO Configuration': '4x4:4 (5GHz), 2x2:2 (2.4GHz)',
                'Antenna Type': 'External N-type connectors',
                'IP Rating': 'IP67',
                'Operating Temperature': '-40C to 65C',
                'Ethernet Ports': '2x 2.5GbE (one with PoE-out)',
                'PoE Requirement': '802.3bt (PoE++)',
                'Deployment': 'Outdoor',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-ap-515',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba AP-515',
              nameKo: '아루바 AP-515',
              description:
                'Wi-Fi 6 entry-level indoor access point with 2x2 MIMO delivering up to 1.49 Gbps for standard office environments',
              descriptionKo:
                '표준 사무실 환경을 위해 최대 1.49 Gbps를 제공하는 2x2 MIMO Wi-Fi 6 엔트리급 실내 액세스 포인트',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/access-points/ap-510-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '1.49 Gbps',
              architectureRole: 'Wi-Fi 6 Entry Access Layer',
              architectureRoleKo: 'Wi-Fi 6 엔트리 액세스 레이어',
              recommendedFor: [
                'Standard office wireless coverage',
                'Budget-conscious Wi-Fi 6 deployment',
                'Small branch and remote office sites',
                'Conference rooms and common areas',
              ],
              recommendedForKo: [
                '표준 사무실 무선 커버리지',
                '비용 효율적인 Wi-Fi 6 배포',
                '소규모 지사 및 원격 사무소 사이트',
                '회의실 및 공용 공간',
              ],
              supportedProtocols: ['Wi-Fi 6 (802.11ax)', '802.1X', 'WPA3', 'BLE 5.0'],
              haFeatures: ['AP clustering', 'IAP failover'],
              securityCapabilities: ['WPA3-Enterprise', 'OWE', 'Dynamic Segmentation', 'WIDS/WIPS'],
              specs: {
                'Wi-Fi Standard': 'Wi-Fi 6 (802.11ax)',
                'Max Data Rate': '1.49 Gbps aggregate',
                'Radio Bands': '2.4GHz / 5GHz dual-band',
                'MIMO Configuration': '2x2:2 per radio',
                'IoT Radios': 'BLE 5.0',
                'Ethernet Ports': '1x 1GbE + 1x 1GbE (pass-through)',
                'PoE Requirement': '802.3af (PoE) / 802.3at (PoE+)',
                'Deployment': 'Indoor',
                'Antenna Type': 'Internal omni-directional',
              },
              children: [],
            },
          ],
        },

        // -- Aruba Controllers --
        {
          nodeId: 'hpe-aruba-controllers',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Aruba Controllers',
          nameKo: '아루바 컨트롤러',
          description:
            'Centralized wireless LAN controllers and mobility gateways for managing large-scale AP deployments with policy enforcement and traffic optimization',
          descriptionKo:
            '정책 적용 및 트래픽 최적화를 통한 대규모 AP 배포 관리를 위한 중앙집중형 무선 LAN 컨트롤러 및 모빌리티 게이트웨이',
          sourceUrl: 'https://www.arubanetworks.com/products/wireless/gateways-and-controllers/',
          infraNodeTypes: ['wireless-ap'],
          architectureRole: 'Wireless LAN Controller / Mobility Gateway',
          architectureRoleKo: '무선 LAN 컨트롤러 / 모빌리티 게이트웨이',
          recommendedFor: [
            'Large campus wireless centralized management',
            'Branch office mobility gateway aggregation',
            'Policy enforcement and dynamic segmentation',
            'Wireless intrusion detection coordination',
            'Guest access and onboarding management',
          ],
          recommendedForKo: [
            '대규모 캠퍼스 무선 중앙 관리',
            '지사 모빌리티 게이트웨이 통합',
            '정책 적용 및 동적 세그멘테이션',
            '무선 침입 탐지 조정',
            '게스트 액세스 및 온보딩 관리',
          ],
          supportedProtocols: [
            'GRE',
            'IPsec',
            'RADIUS',
            'TACACS+',
            'SNMP',
            '802.1X',
            'WPA3',
            'VXLAN',
          ],
          haFeatures: [
            'Controller clustering (N+1)',
            'VRRP for gateway redundancy',
            'AP failover to backup controller',
            'Hitless failover for client sessions',
          ],
          securityCapabilities: [
            'Integrated stateful firewall',
            'Dynamic segmentation',
            'Role-based access control (RBAC)',
            'Encrypted tunneling (IPsec/GRE)',
            'ClearPass integration for NAC',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-mobility-conductor',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba Mobility Conductor',
              nameKo: '아루바 모빌리티 컨덕터',
              description:
                'Centralized management and configuration platform for Aruba Mobility Controllers enabling single-pane-of-glass wireless network orchestration',
              descriptionKo:
                '단일 화면 무선 네트워크 오케스트레이션을 위한 아루바 모빌리티 컨트롤러의 중앙집중형 관리 및 구성 플랫폼',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/gateways-and-controllers/',
              lifecycle: 'active',
              formFactor: 'virtual',
              licensingModel: 'subscription',
              architectureRole: 'Wireless Network Orchestration / Centralized Management',
              architectureRoleKo: '무선 네트워크 오케스트레이션 / 중앙집중 관리',
              recommendedFor: [
                'Multi-site wireless network orchestration',
                'Centralized policy and configuration management',
                'Large-scale controller hierarchy management',
                'Automated firmware and configuration deployment',
              ],
              recommendedForKo: [
                '다중 사이트 무선 네트워크 오케스트레이션',
                '중앙집중형 정책 및 구성 관리',
                '대규모 컨트롤러 계층 관리',
                '자동화된 펌웨어 및 구성 배포',
              ],
              supportedProtocols: ['SNMP', 'RADIUS', 'TACACS+', 'REST API', 'SSH'],
              haFeatures: ['Active/Standby redundancy', 'Configuration sync', 'Automatic failover'],
              securityCapabilities: ['Role-based admin access', 'Audit logging', 'RBAC'],
              specs: {
                'Deployment Mode': 'Virtual appliance (VMware ESXi, Hyper-V, KVM)',
                'Max Managed Controllers': 'Up to 1,000 controllers',
                'Max Managed APs': 'Up to 100,000 APs',
                'Management Protocols': 'SNMP, REST API, CLI, Web UI',
                'HA Mode': 'Active/Standby with automatic failover',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-9200-gateway',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba 9200 Series Gateway',
              nameKo: '아루바 9200 시리즈 게이트웨이',
              description:
                'High-performance branch and campus gateway with integrated firewall, WAN optimization, and mobility controller functions delivering up to 40 Gbps throughput',
              descriptionKo:
                '통합 방화벽, WAN 최적화, 모빌리티 컨트롤러 기능을 갖추고 최대 40 Gbps 처리량을 제공하는 고성능 지사 및 캠퍼스 게이트웨이',
              sourceUrl: 'https://www.arubanetworks.com/products/wireless/gateways-and-controllers/9200-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '40 Gbps',
              architectureRole: 'Branch/Campus Gateway / Mobility Controller',
              architectureRoleKo: '지사/캠퍼스 게이트웨이 / 모빌리티 컨트롤러',
              recommendedFor: [
                'Branch office gateway with integrated security',
                'Campus wireless controller for large AP deployments',
                'SD-Branch with centralized management',
                'Secure WAN edge with policy enforcement',
              ],
              recommendedForKo: [
                '통합 보안을 갖춘 지사 게이트웨이',
                '대규모 AP 배포용 캠퍼스 무선 컨트롤러',
                '중앙 관리 기반 SD-Branch',
                '정책 적용을 갖춘 보안 WAN 엣지',
              ],
              supportedProtocols: ['GRE', 'IPsec', 'VXLAN', 'OSPF', 'BGP', 'RADIUS', '802.1X'],
              haFeatures: ['Controller clustering', 'VRRP', 'Hitless failover', 'Redundant power'],
              securityCapabilities: ['Integrated stateful firewall', 'IDS/IPS', 'Dynamic segmentation', 'IPsec VPN'],
              specs: {
                'Firewall Throughput': '40 Gbps',
                'Max APs Managed': 'Up to 2,048 per gateway',
                'Ports': '2x 10GbE SFP+ / 4x 10GbE SFP+ (model-dependent)',
                'Uplink Options': '1GbE, 10GbE SFP+',
                'Redundant Power': 'Dual power supply support',
                'Form Factor': '1U rack-mount',
                'Management': 'Aruba Central, CLI, Web UI',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Switching
    // =====================================================================
    {
      nodeId: 'hpe-aruba-switching',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Switching',
      nameKo: '스위칭',
      description:
        'HPE Aruba CX switching portfolio with a modern, programmable AOS-CX operating system spanning access, aggregation, campus core, and data center leaf-spine deployments',
      descriptionKo:
        '액세스, 어그리게이션, 캠퍼스 코어, 데이터센터 리프-스파인 배포를 아우르는 최신 프로그래머블 AOS-CX 운영체제를 갖춘 HPE 아루바 CX 스위칭 포트폴리오',
      sourceUrl: 'https://www.arubanetworks.com/products/switches/',
      infraNodeTypes: ['switch-l2', 'switch-l3'],
      children: [
        // -- Aruba CX Switching --
        {
          nodeId: 'hpe-aruba-cx-switching',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Aruba CX Switching',
          nameKo: '아루바 CX 스위칭',
          description:
            'Unified wired switching platform built on AOS-CX with REST APIs, Network Analytics Engine, and VSX for campus and data center fabric',
          descriptionKo:
            'REST API, 네트워크 분석 엔진, VSX를 갖추고 캠퍼스와 데이터센터 패브릭을 위한 AOS-CX 기반 통합 유선 스위칭 플랫폼',
          sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/',
          infraNodeTypes: ['switch-l2', 'switch-l3'],
          architectureRole: 'Campus / Data Center Wired Switching',
          architectureRoleKo: '캠퍼스 / 데이터센터 유선 스위칭',
          recommendedFor: [
            'Campus access and distribution layer switching',
            'Data center leaf-spine fabric deployment',
            'Micro-segmentation with dynamic segmentation',
            'IoT device connectivity and profiling',
            'SD-Branch wired infrastructure',
          ],
          recommendedForKo: [
            '캠퍼스 액세스 및 디스트리뷰션 레이어 스위칭',
            '데이터센터 리프-스파인 패브릭 배포',
            '동적 세그멘테이션을 통한 마이크로세그멘테이션',
            'IoT 장치 연결 및 프로파일링',
            'SD-Branch 유선 인프라',
          ],
          supportedProtocols: [
            'OSPF',
            'BGP',
            'EVPN-VXLAN',
            'VSX',
            'LACP',
            'LLDP',
            'SNMP',
            'sFlow',
            'REST API',
            '802.1X',
            'RADIUS',
          ],
          haFeatures: [
            'VSX (Virtual Switching Extension)',
            'MC-LAG',
            'VRRP',
            'In-Service Software Upgrade (ISSU)',
            'Hot-swappable power supplies and fans',
          ],
          securityCapabilities: [
            'Dynamic segmentation',
            'MACsec (802.1AE)',
            'ClearPass Policy Manager integration',
            'Access Control Lists (ACLs)',
            'DHCP snooping',
            'ARP protection',
            'Port security',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-cx-6200',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 6200',
              nameKo: '아루바 CX 6200',
              description:
                'Cost-effective Layer 2 access switch with 1GbE ports, PoE support, and stacking for small-to-medium campus edge deployments',
              descriptionKo:
                '중소규모 캠퍼스 엣지 배포를 위한 1GbE 포트, PoE 지원, 스태킹을 갖춘 비용 효율적인 레이어 2 액세스 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/6200-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '176 Gbps',
              architectureRole: 'Campus Access Layer',
              architectureRoleKo: '캠퍼스 액세스 레이어',
              recommendedFor: [
                'Campus edge access layer switching',
                'PoE-powered device connectivity (IP phones, APs, cameras)',
                'Small branch office wired networking',
                'Cost-effective enterprise access refresh',
              ],
              recommendedForKo: [
                '캠퍼스 엣지 액세스 레이어 스위칭',
                'PoE 기반 장치 연결 (IP 전화기, AP, 카메라)',
                '소규모 지사 유선 네트워킹',
                '비용 효율적인 엔터프라이즈 액세스 리프레시',
              ],
              supportedProtocols: ['LLDP', 'LACP', 'SNMP', 'sFlow', '802.1X', 'RADIUS'],
              haFeatures: ['Stacking (up to 8 units)', 'Hot-swappable PSU', 'Loop protection'],
              securityCapabilities: ['802.1X', 'DHCP snooping', 'ARP protection', 'Port security'],
              specs: {
                'Switching Capacity': '176 Gbps',
                'Port Configuration': '24/48x 1GbE + 4x 1GbE SFP',
                'PoE Budget': 'Up to 740W (PoE+)',
                'Stacking': 'Up to 8 units via VSF',
                'MAC Addresses': '16,384',
                'Operating System': 'AOS-CX',
                'Form Factor': '1U rack-mount',
                'Power Supply': 'Internal or external PoE PSU',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-cx-6300',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 6300',
              nameKo: '아루바 CX 6300',
              description:
                'Layer 3 access/aggregation switch with multi-gigabit ports, PoE++, and VSX for high-performance campus deployments',
              descriptionKo:
                '고성능 캠퍼스 배포를 위한 멀티기가비트 포트, PoE++, VSX를 갖춘 레이어 3 액세스/어그리게이션 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/6300-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '880 Gbps',
              architectureRole: 'Campus Access / Aggregation Layer',
              architectureRoleKo: '캠퍼스 액세스 / 어그리게이션 레이어',
              recommendedFor: [
                'Campus access with mGig uplinks for Wi-Fi 6/6E APs',
                'Aggregation/distribution layer in campus networks',
                'High-power PoE++ for IoT and smart building devices',
                'VSX-based resilient wired infrastructure',
              ],
              recommendedForKo: [
                'Wi-Fi 6/6E AP용 mGig 업링크를 갖춘 캠퍼스 액세스',
                '캠퍼스 네트워크의 어그리게이션/디스트리뷰션 레이어',
                'IoT 및 스마트 빌딩 장치용 고출력 PoE++',
                'VSX 기반 복원력 있는 유선 인프라',
              ],
              supportedProtocols: ['OSPF', 'BGP', 'VXLAN', 'VSX', 'LACP', 'LLDP', 'SNMP', 'sFlow', '802.1X'],
              haFeatures: ['VSX (Virtual Switching Extension)', 'VRRP', 'Hot-swappable PSU/fans'],
              securityCapabilities: ['MACsec', 'Dynamic segmentation', '802.1X', 'DHCP snooping', 'ACLs'],
              specs: {
                'Switching Capacity': 'Up to 880 Gbps',
                'Port Configuration': '24/48x 1G/2.5G/5G mGig + 4x SFP56 (50GbE)',
                'PoE Budget': 'Up to 1440W (PoE++, 802.3bt)',
                'VSX': 'Supported (active-active)',
                'MAC Addresses': '98,304',
                'IPv4 Routes': '10,000',
                'Operating System': 'AOS-CX',
                'Form Factor': '1U rack-mount',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-cx-6400',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 6400',
              nameKo: '아루바 CX 6400',
              description:
                'Modular chassis campus core and aggregation switch with up to 7.68 Tbps switching capacity and VSX for high-availability deployments',
              descriptionKo:
                '고가용성 배포를 위한 최대 7.68 Tbps 스위칭 용량과 VSX를 갖춘 모듈형 섀시 캠퍼스 코어 및 어그리게이션 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/6400-series/',
              lifecycle: 'active',
              formFactor: 'chassis',
              licensingModel: 'perpetual',
              maxThroughput: '7.68 Tbps',
              architectureRole: 'Campus Core / Aggregation',
              architectureRoleKo: '캠퍼스 코어 / 어그리게이션',
              recommendedFor: [
                'Campus core switching with modular scalability',
                'Large campus network aggregation',
                'High-availability enterprise backbone',
                'VSX-based active-active core deployment',
              ],
              recommendedForKo: [
                '모듈형 확장성을 갖춘 캠퍼스 코어 스위칭',
                '대규모 캠퍼스 네트워크 어그리게이션',
                '고가용성 엔터프라이즈 백본',
                'VSX 기반 액티브-액티브 코어 배포',
              ],
              supportedProtocols: ['OSPF', 'BGP', 'EVPN-VXLAN', 'VSX', 'LACP', 'SNMP', 'sFlow', 'REST API'],
              haFeatures: ['VSX', 'Redundant management modules', 'Redundant power/fans', 'ISSU'],
              securityCapabilities: ['MACsec', 'Dynamic segmentation', 'ACLs', 'ClearPass integration'],
              specs: {
                'Switching Capacity': '7.68 Tbps',
                'Chassis Slots': '5 I/O slots (CX 6405) or 10 I/O slots (CX 6410)',
                'Port Density': 'Up to 240x 1GbE or 96x 10GbE or 32x 100GbE',
                'VSX': 'Supported (active-active)',
                'Redundancy': 'Dual management modules, N+N power',
                'MAC Addresses': '196,608',
                'IPv4 Routes': '256,000',
                'Operating System': 'AOS-CX',
                'Form Factor': '5U/10U modular chassis',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-cx-8100',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 8100',
              nameKo: '아루바 CX 8100',
              description:
                'Data center leaf switch with 25/100GbE ports and EVPN-VXLAN fabric support for modern data center architectures',
              descriptionKo:
                '최신 데이터센터 아키텍처를 위한 25/100GbE 포트와 EVPN-VXLAN 패브릭 지원을 갖춘 데이터센터 리프 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/8100-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '3.2 Tbps',
              architectureRole: 'Data Center Leaf / Top-of-Rack',
              architectureRoleKo: '데이터센터 리프 / 탑오브랙',
              recommendedFor: [
                'Data center leaf/ToR switching',
                'EVPN-VXLAN fabric deployment',
                'Server connectivity with 25GbE',
                'Small-to-medium data center environments',
              ],
              recommendedForKo: [
                '데이터센터 리프/ToR 스위칭',
                'EVPN-VXLAN 패브릭 배포',
                '25GbE 서버 연결',
                '중소규모 데이터센터 환경',
              ],
              supportedProtocols: ['BGP', 'EVPN-VXLAN', 'OSPF', 'LACP', 'LLDP', 'sFlow', 'REST API'],
              haFeatures: ['VSX', 'MC-LAG', 'ECMP', 'Hot-swappable PSU/fans'],
              securityCapabilities: ['MACsec', 'ACLs', 'Micro-segmentation', 'ClearPass integration'],
              specs: {
                'Switching Capacity': '3.2 Tbps',
                'Port Configuration': '48x 25GbE SFP28 + 6x 100GbE QSFP28',
                'EVPN-VXLAN': 'Supported (BGP EVPN with VXLAN)',
                'VSX': 'Supported',
                'MAC Addresses': '196,608',
                'IPv4 Routes': '128,000',
                'Operating System': 'AOS-CX',
                'Form Factor': '1U rack-mount',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-cx-8360',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 8360',
              nameKo: '아루바 CX 8360',
              description:
                'Data center spine switch with 100/400GbE ports and EVPN-VXLAN for scalable data center fabric architectures',
              descriptionKo:
                '확장 가능한 데이터센터 패브릭 아키텍처를 위한 100/400GbE 포트와 EVPN-VXLAN을 갖춘 데이터센터 스파인 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/8360-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              maxThroughput: '12.8 Tbps',
              architectureRole: 'Data Center Spine',
              architectureRoleKo: '데이터센터 스파인',
              recommendedFor: [
                'Data center spine/aggregation switching',
                'Large-scale EVPN-VXLAN fabric spine tier',
                'High-bandwidth east-west traffic handling',
                'Campus or DC core backbone with 400GbE',
              ],
              recommendedForKo: [
                '데이터센터 스파인/어그리게이션 스위칭',
                '대규모 EVPN-VXLAN 패브릭 스파인 티어',
                '고대역폭 동서 트래픽 처리',
                '400GbE 기반 캠퍼스 또는 DC 코어 백본',
              ],
              supportedProtocols: ['BGP', 'EVPN-VXLAN', 'OSPF', 'ECMP', 'LACP', 'sFlow', 'REST API'],
              haFeatures: ['VSX', 'ECMP', 'Redundant PSU/fans', 'ISSU'],
              securityCapabilities: ['MACsec', 'ACLs', 'Micro-segmentation'],
              specs: {
                'Switching Capacity': 'Up to 12.8 Tbps',
                'Port Configuration': '32x 100GbE QSFP28 or 32x 400GbE QSFP-DD (model-dependent)',
                'EVPN-VXLAN': 'Supported',
                'VSX': 'Supported',
                'MAC Addresses': '288,000',
                'IPv4 Routes': '256,000',
                'Latency': 'Sub-microsecond',
                'Operating System': 'AOS-CX',
                'Form Factor': '1U rack-mount',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-cx-10000',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Aruba CX 10000',
              nameKo: '아루바 CX 10000',
              description:
                'Distributed services switch combining L2/L3 switching with stateful firewall, NAT, and micro-segmentation at line rate (6.4 Tbps)',
              descriptionKo:
                'L2/L3 스위칭과 라인 레이트(6.4 Tbps)의 상태 기반 방화벽, NAT, 마이크로세그멘테이션을 결합한 분산 서비스 스위치',
              sourceUrl: 'https://www.arubanetworks.com/products/switches/cx-switching/10000-series/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '6.4 Tbps',
              architectureRole: 'Data Center Distributed Services / Secure Leaf',
              architectureRoleKo: '데이터센터 분산 서비스 / 보안 리프',
              recommendedFor: [
                'East-west micro-segmentation at data center leaf',
                'Distributed stateful firewall replacing centralized FW bottleneck',
                'Zero Trust data center architecture',
                'Compliance-driven workload isolation',
              ],
              recommendedForKo: [
                '데이터센터 리프에서의 동서 마이크로세그멘테이션',
                '중앙집중형 FW 병목을 대체하는 분산 상태 기반 방화벽',
                '제로 트러스트 데이터센터 아키텍처',
                '컴플라이언스 기반 워크로드 격리',
              ],
              supportedProtocols: ['BGP', 'EVPN-VXLAN', 'OSPF', 'REST API', 'sFlow', 'NetFlow'],
              haFeatures: ['VSX', 'ECMP', 'Stateful firewall HA', 'Redundant PSU/fans'],
              securityCapabilities: [
                'Stateful firewall at line rate',
                'NAT at line rate',
                'Micro-segmentation (Pensando DPU)',
                'East-west traffic inspection',
                'Zero Trust enforcement',
              ],
              specs: {
                'Switching Capacity': '6.4 Tbps',
                'Stateful Firewall Throughput': '800 Gbps (line rate)',
                'Port Configuration': '48x 25GbE SFP28 + 8x 100GbE QSFP28',
                'DPU': 'AMD Pensando integrated',
                'EVPN-VXLAN': 'Supported',
                'NAT': 'Line-rate NAT',
                'MAC Addresses': '288,000',
                'IPv4 Routes': '256,000',
                'Operating System': 'AOS-CX',
                'Form Factor': '1U rack-mount',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. Network Security
    // =====================================================================
    {
      nodeId: 'hpe-aruba-network-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Security',
      nameKo: '네트워크 보안',
      description:
        'HPE Aruba network security portfolio including ClearPass NAC platform and EdgeConnect SD-WAN for secure connectivity and zero trust access control',
      descriptionKo:
        '보안 연결 및 제로 트러스트 접근 제어를 위한 ClearPass NAC 플랫폼과 EdgeConnect SD-WAN을 포함하는 HPE 아루바 네트워크 보안 포트폴리오',
      sourceUrl: 'https://www.arubanetworks.com/products/security/',
      infraNodeTypes: ['nac'],
      children: [
        // -- Aruba ClearPass --
        {
          nodeId: 'hpe-aruba-clearpass',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Aruba ClearPass',
          nameKo: '아루바 ClearPass',
          description:
            'Network access control (NAC) and policy management platform providing 802.1X authentication, device profiling, guest access, and endpoint posture assessment',
          descriptionKo:
            '802.1X 인증, 장치 프로파일링, 게스트 액세스, 엔드포인트 보안 상태 평가를 제공하는 네트워크 접근 제어(NAC) 및 정책 관리 플랫폼',
          sourceUrl: 'https://www.arubanetworks.com/products/security/network-access-control/',
          infraNodeTypes: ['nac'],
          architectureRole: 'Network Access Control / Policy Engine',
          architectureRoleKo: '네트워크 접근 제어 / 정책 엔진',
          recommendedFor: [
            'Enterprise-wide 802.1X NAC deployment',
            'BYOD and IoT device onboarding and profiling',
            'Guest and visitor network access management',
            'Compliance-driven endpoint posture enforcement',
            'Zero Trust network segmentation policy engine',
          ],
          recommendedForKo: [
            '엔터프라이즈 전체 802.1X NAC 배포',
            'BYOD 및 IoT 장치 온보딩 및 프로파일링',
            '게스트 및 방문자 네트워크 접근 관리',
            '컴플라이언스 기반 엔드포인트 보안 상태 적용',
            '제로 트러스트 네트워크 세그멘테이션 정책 엔진',
          ],
          supportedProtocols: [
            'RADIUS',
            'TACACS+',
            '802.1X',
            'SAML',
            'OAuth',
            'LDAP',
            'Kerberos',
            'SNMP',
            'Syslog',
            'REST API',
          ],
          haFeatures: [
            'Active/Standby cluster',
            'Publisher/Subscriber replication',
            'Automatic failover',
            'Database replication',
          ],
          securityCapabilities: [
            '802.1X authentication (EAP-TLS, PEAP, EAP-TTLS)',
            'MAC authentication bypass (MAB)',
            'Device profiling and fingerprinting',
            'Endpoint posture assessment (OnGuard)',
            'Certificate-based authentication',
            'Multi-factor authentication integration',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-clearpass-policy-manager',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ClearPass Policy Manager',
              nameKo: 'ClearPass 정책 관리자',
              description:
                'Core NAC platform providing 802.1X authentication, device profiling, role-based access control, and dynamic segmentation policy enforcement',
              descriptionKo:
                '802.1X 인증, 장치 프로파일링, 역할 기반 접근 제어, 동적 세그멘테이션 정책 적용을 제공하는 핵심 NAC 플랫폼',
              sourceUrl: 'https://www.arubanetworks.com/products/security/network-access-control/clearpass-policy-manager/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              architectureRole: 'Network Access Control Engine',
              architectureRoleKo: '네트워크 접근 제어 엔진',
              recommendedFor: [
                'Enterprise 802.1X wired and wireless NAC',
                'BYOD and IoT device profiling and policy',
                'Dynamic network segmentation enforcement',
                'Multi-vendor NAC integration',
              ],
              recommendedForKo: [
                '엔터프라이즈 802.1X 유무선 NAC',
                'BYOD 및 IoT 장치 프로파일링 및 정책',
                '동적 네트워크 세그멘테이션 적용',
                '멀티벤더 NAC 통합',
              ],
              supportedProtocols: ['RADIUS', 'TACACS+', '802.1X', 'LDAP', 'SAML', 'REST API'],
              haFeatures: ['Publisher/Subscriber cluster', 'Automatic failover', 'Database replication'],
              securityCapabilities: ['802.1X (EAP-TLS, PEAP)', 'MAB', 'Device profiling', 'Certificate auth'],
              specs: {
                'Deployment Mode': 'Hardware appliance or virtual (VMware, Hyper-V)',
                'Max Endpoints': 'Up to 500,000 endpoints per cluster',
                'Authentication Protocols': 'EAP-TLS, PEAP, EAP-TTLS, MAB',
                'Profiling Methods': 'DHCP, HTTP, SNMP, Nmap, WMI, Active Directory',
                'HA Mode': 'Publisher/Subscriber with auto-failover',
                'Management': 'Web UI, REST API, CLI',
                'Integration': 'Aruba, Cisco, Juniper, Palo Alto, Fortinet multi-vendor',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-clearpass-guest',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ClearPass Guest',
              nameKo: 'ClearPass 게스트',
              description:
                'Self-service guest access portal with customizable registration workflows, sponsor approval, and time-limited network access',
              descriptionKo:
                '맞춤형 등록 워크플로우, 스폰서 승인, 시간 제한 네트워크 접근을 갖춘 셀프서비스 게스트 액세스 포털',
              sourceUrl: 'https://www.arubanetworks.com/products/security/network-access-control/clearpass-guest/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              architectureRole: 'Guest Access Management',
              architectureRoleKo: '게스트 액세스 관리',
              recommendedFor: [
                'Visitor and contractor Wi-Fi onboarding',
                'Self-service guest registration portals',
                'Sponsor-approved network access workflows',
                'Time-limited and bandwidth-limited guest access',
              ],
              recommendedForKo: [
                '방문자 및 계약자 Wi-Fi 온보딩',
                '셀프서비스 게스트 등록 포털',
                '스폰서 승인 네트워크 접근 워크플로우',
                '시간 제한 및 대역폭 제한 게스트 접근',
              ],
              supportedProtocols: ['RADIUS', 'HTTPS', 'SMTP', 'SMS Gateway', 'REST API'],
              haFeatures: ['Integrated with ClearPass PM cluster', 'Database replication'],
              securityCapabilities: ['Captive portal', 'MAC registration', 'Social login', 'Access time limits'],
              specs: {
                'Portal Customization': 'Fully customizable HTML/CSS templates',
                'Registration Methods': 'Self-service, sponsor, social media login',
                'Access Control': 'Time-based, bandwidth-based, location-based',
                'Notification': 'Email, SMS for guest credentials',
                'Reporting': 'Guest activity audit trail and reporting',
                'Integration': 'Part of ClearPass Policy Manager platform',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-clearpass-onguard',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ClearPass OnGuard',
              nameKo: 'ClearPass OnGuard',
              description:
                'Endpoint posture assessment agent that validates device health (antivirus, patches, encryption) before granting network access',
              descriptionKo:
                '네트워크 접근 허용 전에 장치 상태(안티바이러스, 패치, 암호화)를 검증하는 엔드포인트 보안 상태 평가 에이전트',
              sourceUrl: 'https://www.arubanetworks.com/products/security/network-access-control/clearpass-onguard/',
              lifecycle: 'active',
              formFactor: 'virtual',
              licensingModel: 'subscription',
              architectureRole: 'Endpoint Posture Assessment',
              architectureRoleKo: '엔드포인트 보안 상태 평가',
              recommendedFor: [
                'Compliance-driven endpoint health verification',
                'Pre-admission posture checks for corporate devices',
                'Remediation workflows for non-compliant endpoints',
                'BYOD security posture enforcement',
              ],
              recommendedForKo: [
                '컴플라이언스 기반 엔드포인트 상태 검증',
                '기업 장치의 사전 접속 보안 상태 확인',
                '비준수 엔드포인트의 교정 워크플로우',
                'BYOD 보안 상태 적용',
              ],
              supportedProtocols: ['HTTPS', '802.1X', 'REST API'],
              haFeatures: ['Integrated with ClearPass PM cluster'],
              securityCapabilities: ['Antivirus status check', 'OS patch level validation', 'Disk encryption check', 'Firewall status check'],
              specs: {
                'Supported OS': 'Windows, macOS, Linux',
                'Agent Types': 'Persistent agent, dissolvable agent',
                'Health Checks': 'Antivirus, anti-spyware, firewall, OS patches, disk encryption',
                'Remediation': 'Auto-remediation or quarantine VLAN assignment',
                'Compliance Standards': 'PCI-DSS, HIPAA, SOX endpoint requirements',
                'Integration': 'Part of ClearPass Policy Manager platform',
              },
              children: [],
            },
          ],
        },

        // -- Aruba EdgeConnect SD-WAN --
        {
          nodeId: 'hpe-aruba-edgeconnect',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Aruba EdgeConnect SD-WAN',
          nameKo: '아루바 EdgeConnect SD-WAN',
          description:
            'Software-defined WAN platform (formerly Silver Peak) providing WAN optimization, path conditioning, and zero trust security for branch connectivity',
          descriptionKo:
            '지사 연결을 위한 WAN 최적화, 경로 컨디셔닝, 제로 트러스트 보안을 제공하는 소프트웨어 정의 WAN 플랫폼 (구 Silver Peak)',
          sourceUrl: 'https://www.arubanetworks.com/products/sd-wan/',
          infraNodeTypes: ['sd-wan'],
          architectureRole: 'SD-WAN Edge / WAN Optimization',
          architectureRoleKo: 'SD-WAN 엣지 / WAN 최적화',
          recommendedFor: [
            'Branch-to-cloud and branch-to-DC SD-WAN connectivity',
            'WAN optimization for latency-sensitive applications',
            'MPLS-to-broadband WAN migration',
            'Secure SD-WAN with integrated ZTNA',
            'Multi-cloud connectivity and SaaS optimization',
          ],
          recommendedForKo: [
            '지사-클라우드 및 지사-DC SD-WAN 연결',
            '지연에 민감한 애플리케이션의 WAN 최적화',
            'MPLS에서 브로드밴드 WAN 마이그레이션',
            '통합 ZTNA를 갖춘 보안 SD-WAN',
            '멀티클라우드 연결 및 SaaS 최적화',
          ],
          supportedProtocols: [
            'IPsec',
            'GRE',
            'OSPF',
            'BGP',
            'VXLAN',
            'MPLS',
            'REST API',
          ],
          haFeatures: [
            'Active/Active WAN link bonding',
            'Sub-second failover',
            'Path conditioning with FEC',
            'Dual appliance HA',
          ],
          securityCapabilities: [
            'Integrated next-gen firewall',
            'IDS/IPS',
            'URL/content filtering',
            'ZTNA (Zero Trust Network Access)',
            'WAN encryption (AES-256-GCM)',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-edgeconnect-enterprise',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'EdgeConnect Enterprise',
              nameKo: 'EdgeConnect 엔터프라이즈',
              description:
                'Full-featured SD-WAN appliance for branch and data center deployments with WAN optimization, integrated security, and centralized orchestration',
              descriptionKo:
                'WAN 최적화, 통합 보안, 중앙집중 오케스트레이션을 갖춘 지사 및 데이터센터 배포용 풀기능 SD-WAN 어플라이언스',
              sourceUrl: 'https://www.arubanetworks.com/products/sd-wan/edgeconnect/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '10 Gbps',
              architectureRole: 'Branch/DC SD-WAN Appliance',
              architectureRoleKo: '지사/DC SD-WAN 어플라이언스',
              recommendedFor: [
                'Enterprise branch office SD-WAN deployment',
                'Data center hub SD-WAN termination',
                'Multi-cloud on-ramp connectivity',
                'MPLS-to-internet WAN transformation',
              ],
              recommendedForKo: [
                '엔터프라이즈 지사 SD-WAN 배포',
                '데이터센터 허브 SD-WAN 터미네이션',
                '멀티클라우드 온랩프 연결',
                'MPLS에서 인터넷 WAN 전환',
              ],
              supportedProtocols: ['IPsec', 'GRE', 'OSPF', 'BGP', 'VXLAN', 'REST API'],
              haFeatures: ['Active/Active HA', 'WAN link bonding', 'Sub-second failover', 'Path conditioning (FEC)'],
              securityCapabilities: ['Integrated NGFW', 'IDS/IPS', 'URL filtering', 'ZTNA', 'AES-256-GCM encryption'],
              specs: {
                'WAN Throughput': 'Up to 10 Gbps (model-dependent)',
                'WAN Interfaces': '4x 1GbE / 2x 10GbE (model-dependent)',
                'LAN Interfaces': '4x 1GbE',
                'WAN Optimization': 'Boost with TCP/UDP acceleration, deduplication, compression',
                'Security': 'Zone-based stateful firewall, IDS/IPS, URL filtering',
                'Orchestration': 'Aruba Orchestrator centralized management',
                'Form Factor': '1U rack-mount desktop appliance',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-edgeconnect-microbranch',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'EdgeConnect Microbranch',
              nameKo: 'EdgeConnect 마이크로브랜치',
              description:
                'Compact SD-WAN solution for small branch offices leveraging Aruba APs as thin SD-WAN edges with gateway functions',
              descriptionKo:
                '아루바 AP를 씬 SD-WAN 엣지로 활용하는 소규모 지사용 컴팩트 SD-WAN 솔루션',
              sourceUrl: 'https://www.arubanetworks.com/products/sd-wan/edgeconnect-microbranch/',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '500 Mbps',
              architectureRole: 'Small Branch SD-WAN / Thin Edge',
              architectureRoleKo: '소규모 지사 SD-WAN / 씬 엣지',
              recommendedFor: [
                'Small retail and branch locations (1-10 users)',
                'SD-WAN for AP-only sites without dedicated appliance',
                'Cost-effective WAN connectivity for micro-branches',
                'Unified WLAN + SD-WAN management via Aruba Central',
              ],
              recommendedForKo: [
                '소규모 매장 및 지사 위치 (1-10 사용자)',
                '전용 어플라이언스 없이 AP 전용 사이트의 SD-WAN',
                '마이크로브랜치를 위한 비용 효율적인 WAN 연결',
                'Aruba Central을 통한 통합 WLAN + SD-WAN 관리',
              ],
              supportedProtocols: ['IPsec', 'GRE', 'DHCP', 'REST API'],
              haFeatures: ['Dual WAN uplink failover', 'Cloud-managed resilience'],
              securityCapabilities: ['Basic firewall', 'IPsec VPN', 'Dynamic segmentation'],
              specs: {
                'WAN Throughput': 'Up to 500 Mbps',
                'Deployment Model': 'Aruba AP as SD-WAN gateway (AP-based)',
                'WAN Interfaces': '1-2x WAN (via AP uplinks)',
                'Management': 'Aruba Central cloud-managed',
                'Security': 'IPsec VPN, basic stateful firewall',
                'Target Sites': '1-10 users per site',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Servers
    // =====================================================================
    {
      nodeId: 'hpe-aruba-servers',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Servers',
      nameKo: '서버',
      description:
        'HPE ProLiant and Synergy server portfolio spanning rack, tower, and composable form factors for enterprise data center workloads',
      descriptionKo:
        '엔터프라이즈 데이터센터 워크로드를 위한 랙, 타워, 컴포저블 폼팩터를 아우르는 HPE ProLiant 및 Synergy 서버 포트폴리오',
      sourceUrl: 'https://www.hpe.com/us/en/servers.html',
      infraNodeTypes: ['web-server', 'app-server', 'db-server', 'vm'],
      children: [
        // -- HPE ProLiant --
        {
          nodeId: 'hpe-aruba-proliant',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'HPE ProLiant',
          nameKo: 'HPE ProLiant',
          description:
            'Industry-standard x86 rack and tower servers with Intel Xeon Scalable processors, Silicon Root of Trust security, and iLO management for diverse enterprise workloads',
          descriptionKo:
            '다양한 엔터프라이즈 워크로드를 위한 Intel Xeon Scalable 프로세서, Silicon Root of Trust 보안, iLO 관리를 갖춘 산업 표준 x86 랙 및 타워 서버',
          sourceUrl: 'https://www.hpe.com/us/en/servers/proliant.html',
          infraNodeTypes: ['web-server', 'app-server', 'db-server', 'vm'],
          architectureRole: 'Data Center / Enterprise Compute',
          architectureRoleKo: '데이터센터 / 엔터프라이즈 컴퓨팅',
          recommendedFor: [
            'Enterprise data center virtualization (VMware, Hyper-V)',
            'Database and business-critical application hosting',
            'Cloud-native and containerized workloads',
            'AI/ML inference and training workloads',
            'High-performance computing (HPC)',
          ],
          recommendedForKo: [
            '엔터프라이즈 데이터센터 가상화 (VMware, Hyper-V)',
            '데이터베이스 및 비즈니스 크리티컬 애플리케이션 호스팅',
            '클라우드 네이티브 및 컨테이너 워크로드',
            'AI/ML 추론 및 훈련 워크로드',
            '고성능 컴퓨팅 (HPC)',
          ],
          supportedProtocols: [
            'PCIe Gen5',
            'iLO 6',
            'IPMI 2.0',
            'Redfish',
            'SNMP',
            'iSCSI',
            'FC (via HBA)',
            'NVMe-oF',
          ],
          haFeatures: [
            'Redundant hot-plug power supplies',
            'Hot-plug NVMe/SAS/SATA drives',
            'Redundant fans',
            'iLO remote management with Lifecycle Controller',
            'Hardware RAID with flash-backed cache',
          ],
          securityCapabilities: [
            'Silicon Root of Trust',
            'TPM 2.0',
            'Secure Boot with UEFI',
            'Server Configuration Lock',
            'Signed firmware updates',
            'Chassis intrusion detection',
            'AMD SEV / Intel SGX (model-dependent)',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-proliant-dl360-gen11',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ProLiant DL360 Gen11',
              nameKo: 'ProLiant DL360 Gen11',
              description:
                '1U dual-socket rack server with Intel Xeon 4th/5th Gen processors and PCIe Gen5 for dense data center compute workloads',
              descriptionKo:
                '고밀도 데이터센터 컴퓨팅 워크로드를 위한 Intel Xeon 4세대/5세대 프로세서와 PCIe Gen5를 갖춘 1U 듀얼소켓 랙 서버',
              sourceUrl: 'https://www.hpe.com/us/en/servers/proliant-dl360.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              architectureRole: 'Dense Data Center Compute / Virtualization Host',
              architectureRoleKo: '고밀도 데이터센터 컴퓨팅 / 가상화 호스트',
              recommendedFor: [
                'High-density rack server deployments',
                'VMware/Hyper-V virtualization hosts',
                'Web and application server farms',
                'Cloud-native containerized workloads',
              ],
              recommendedForKo: [
                '고밀도 랙 서버 배포',
                'VMware/Hyper-V 가상화 호스트',
                '웹 및 애플리케이션 서버 팜',
                '클라우드 네이티브 컨테이너 워크로드',
              ],
              supportedProtocols: ['PCIe Gen5', 'iLO 6', 'Redfish', 'IPMI 2.0', 'SNMP'],
              haFeatures: ['Redundant PSU', 'Hot-plug drives', 'Redundant fans', 'iLO remote management'],
              securityCapabilities: ['Silicon Root of Trust', 'TPM 2.0', 'Secure Boot', 'Server Configuration Lock'],
              specs: {
                Processor: 'Up to 2x Intel Xeon Scalable 4th/5th Gen (up to 60 cores per CPU)',
                'Max Memory': '32 DIMM slots, up to 4 TB DDR5',
                'Drive Bays': 'Up to 10x 2.5" SFF or 4x 3.5" LFF NVMe/SAS/SATA',
                'PCIe Slots': '3x PCIe Gen5 slots',
                'Network Ports': '1x OCP 3.0 slot + 4x 1GbE LOM',
                'Power Supply': '1+1 redundant up to 1600W',
                'Form Factor': '1U rack-mount',
                Management: 'iLO 6 with Lifecycle Controller',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-proliant-dl380-gen11',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ProLiant DL380 Gen11',
              nameKo: 'ProLiant DL380 Gen11',
              description:
                '2U dual-socket rack server (most popular ProLiant model) with Intel Xeon, 32 DIMM slots, and 8 PCIe Gen5 slots for versatile enterprise workloads',
              descriptionKo:
                '다양한 엔터프라이즈 워크로드를 위한 Intel Xeon, 32 DIMM 슬롯, 8개 PCIe Gen5 슬롯을 갖춘 2U 듀얼소켓 랙 서버 (가장 인기 있는 ProLiant 모델)',
              sourceUrl: 'https://www.hpe.com/us/en/servers/proliant-dl380.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              architectureRole: 'Versatile Enterprise Compute / Database Server',
              architectureRoleKo: '범용 엔터프라이즈 컴퓨팅 / 데이터베이스 서버',
              recommendedFor: [
                'General-purpose enterprise server consolidation',
                'Database hosting (SQL, Oracle, SAP HANA)',
                'Virtualization and private cloud infrastructure',
                'AI/ML inference with GPU acceleration',
              ],
              recommendedForKo: [
                '범용 엔터프라이즈 서버 통합',
                '데이터베이스 호스팅 (SQL, Oracle, SAP HANA)',
                '가상화 및 프라이빗 클라우드 인프라',
                'GPU 가속을 통한 AI/ML 추론',
              ],
              supportedProtocols: ['PCIe Gen5', 'iLO 6', 'Redfish', 'IPMI 2.0', 'SNMP', 'NVMe-oF'],
              haFeatures: ['Redundant PSU', 'Hot-plug drives', 'Redundant fans', 'Internal M.2 boot'],
              securityCapabilities: ['Silicon Root of Trust', 'TPM 2.0', 'Secure Boot', 'Server Configuration Lock'],
              specs: {
                Processor: 'Up to 2x Intel Xeon Scalable 4th/5th Gen (up to 60 cores per CPU)',
                'Max Memory': '32 DIMM slots, up to 4 TB DDR5',
                'Drive Bays': 'Up to 24x 2.5" SFF + 2x rear SFF NVMe/SAS/SATA',
                'PCIe Slots': '8x PCIe Gen5 slots',
                'Network Ports': '1x OCP 3.0 slot + 4x 1GbE LOM',
                'Power Supply': '1+1 redundant up to 1600W',
                'Form Factor': '2U rack-mount',
                Management: 'iLO 6 with Lifecycle Controller',
                'GPU Support': 'Up to 3x double-width GPU',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-proliant-dl560-gen11',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ProLiant DL560 Gen11',
              nameKo: 'ProLiant DL560 Gen11',
              description:
                '2U 4-socket rack server with up to 4 Intel Xeon Scalable processors and 64 DIMM slots for mission-critical in-memory and database workloads',
              descriptionKo:
                '미션 크리티컬 인메모리 및 데이터베이스 워크로드를 위한 최대 4개 Intel Xeon Scalable 프로세서와 64 DIMM 슬롯을 갖춘 2U 4소켓 랙 서버',
              sourceUrl: 'https://www.hpe.com/us/en/servers/proliant-dl560.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              architectureRole: 'Mission-Critical Compute / In-Memory Database',
              architectureRoleKo: '미션 크리티컬 컴퓨팅 / 인메모리 데이터베이스',
              recommendedFor: [
                'Mission-critical database (SAP HANA, Oracle RAC)',
                'Large-scale virtualization consolidation',
                'In-memory analytics and business intelligence',
                'High-memory enterprise applications (ERP, CRM)',
              ],
              recommendedForKo: [
                '미션 크리티컬 데이터베이스 (SAP HANA, Oracle RAC)',
                '대규모 가상화 통합',
                '인메모리 분석 및 비즈니스 인텔리전스',
                '대용량 메모리 엔터프라이즈 애플리케이션 (ERP, CRM)',
              ],
              supportedProtocols: ['PCIe Gen5', 'iLO 6', 'Redfish', 'IPMI 2.0', 'SNMP'],
              haFeatures: ['Redundant PSU', 'Hot-plug drives', 'Redundant fans', 'iLO advanced'],
              securityCapabilities: ['Silicon Root of Trust', 'TPM 2.0', 'Secure Boot', 'Server Configuration Lock'],
              specs: {
                Processor: 'Up to 4x Intel Xeon Scalable 4th/5th Gen',
                'Max Memory': '64 DIMM slots, up to 8 TB DDR5',
                'Drive Bays': 'Up to 16x 2.5" SFF NVMe/SAS/SATA',
                'PCIe Slots': '6x PCIe Gen5 slots',
                'Network Ports': '1x OCP 3.0 slot + 2x 1GbE LOM',
                'Power Supply': '2+2 redundant up to 1600W',
                'Form Factor': '2U rack-mount',
                Management: 'iLO 6 with Lifecycle Controller',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-proliant-ml350-gen11',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ProLiant ML350 Gen11',
              nameKo: 'ProLiant ML350 Gen11',
              description:
                'Dual-socket tower server with quiet operation, high expandability, and 32 DIMM slots for remote office and SMB environments',
              descriptionKo:
                '원격 사무소 및 중소기업 환경을 위한 저소음 운영, 높은 확장성, 32 DIMM 슬롯을 갖춘 듀얼소켓 타워 서버',
              sourceUrl: 'https://www.hpe.com/us/en/servers/proliant-ml350.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'perpetual',
              architectureRole: 'Remote Office / SMB / Edge Server',
              architectureRoleKo: '원격 사무소 / 중소기업 / 엣지 서버',
              recommendedFor: [
                'Remote office and branch office deployments',
                'Small-to-medium business server',
                'Edge computing with limited data center infrastructure',
                'File and print server consolidation',
              ],
              recommendedForKo: [
                '원격 사무소 및 지사 배포',
                '중소기업 서버',
                '제한적인 데이터센터 인프라의 엣지 컴퓨팅',
                '파일 및 프린트 서버 통합',
              ],
              supportedProtocols: ['PCIe Gen5', 'iLO 6', 'Redfish', 'IPMI 2.0', 'SNMP'],
              haFeatures: ['Redundant PSU (optional)', 'Hot-plug drives', 'iLO remote management'],
              securityCapabilities: ['Silicon Root of Trust', 'TPM 2.0', 'Secure Boot', 'Chassis intrusion detection'],
              specs: {
                Processor: 'Up to 2x Intel Xeon Scalable 4th/5th Gen',
                'Max Memory': '32 DIMM slots, up to 4 TB DDR5',
                'Drive Bays': 'Up to 16x 3.5" LFF or 24x 2.5" SFF',
                'PCIe Slots': '8x PCIe Gen5 slots',
                'Network Ports': '1x OCP 3.0 slot + 4x 1GbE LOM',
                'Power Supply': '1+1 redundant up to 1600W (optional)',
                'Form Factor': 'Tower (convertible to rack)',
                Management: 'iLO 6 with Lifecycle Controller',
                'Acoustic Level': 'Ultra-quiet operation for office environments',
              },
              children: [],
            },
          ],
        },

        // -- HPE Synergy --
        {
          nodeId: 'hpe-aruba-synergy',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'HPE Synergy',
          nameKo: 'HPE Synergy',
          description:
            'Composable infrastructure platform combining compute, storage, and fabric in a single frame with software-defined resource allocation',
          descriptionKo:
            '소프트웨어 정의 리소스 할당으로 단일 프레임에 컴퓨팅, 스토리지, 패브릭을 결합한 컴포저블 인프라스트럭처 플랫폼',
          sourceUrl: 'https://www.hpe.com/us/en/servers/composable.html',
          infraNodeTypes: ['web-server', 'app-server', 'db-server', 'vm'],
          architectureRole: 'Composable Infrastructure / Software-Defined Data Center',
          architectureRoleKo: '컴포저블 인프라스트럭처 / 소프트웨어 정의 데이터센터',
          recommendedFor: [
            'Software-defined composable infrastructure deployments',
            'Private cloud and hybrid cloud infrastructure',
            'Workload-optimized resource allocation',
            'High-density compute consolidation',
            'DevOps and CI/CD infrastructure automation',
          ],
          recommendedForKo: [
            '소프트웨어 정의 컴포저블 인프라 배포',
            '프라이빗 클라우드 및 하이브리드 클라우드 인프라',
            '워크로드 최적화 리소스 할당',
            '고밀도 컴퓨팅 통합',
            'DevOps 및 CI/CD 인프라 자동화',
          ],
          supportedProtocols: [
            'PCIe Gen5',
            'iLO 6',
            'Redfish',
            'OneView API',
            'FC (via Virtual Connect)',
            'Ethernet (via Virtual Connect)',
          ],
          haFeatures: [
            'Redundant frame link modules',
            'Redundant power supplies (N+N)',
            'Virtual Connect fabric redundancy',
            'Hot-plug compute and storage modules',
          ],
          securityCapabilities: [
            'Silicon Root of Trust',
            'TPM 2.0',
            'Secure Boot',
            'OneView role-based access control',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-synergy-12000',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Synergy 12000 Frame',
              nameKo: 'Synergy 12000 프레임',
              description:
                'Composable infrastructure chassis supporting up to 12 half-height or 6 full-height compute modules with integrated fabric and management',
              descriptionKo:
                '통합 패브릭과 관리를 갖추고 최대 12개 반높이 또는 6개 전높이 컴퓨팅 모듈을 지원하는 컴포저블 인프라스트럭처 섀시',
              sourceUrl: 'https://www.hpe.com/us/en/servers/composable.html',
              lifecycle: 'active',
              formFactor: 'chassis',
              licensingModel: 'perpetual',
              architectureRole: 'Composable Infrastructure Chassis',
              architectureRoleKo: '컴포저블 인프라스트럭처 섀시',
              recommendedFor: [
                'Composable infrastructure deployments',
                'Private cloud foundation infrastructure',
                'High-density compute consolidation',
                'Software-defined data center automation',
              ],
              recommendedForKo: [
                '컴포저블 인프라 배포',
                '프라이빗 클라우드 기반 인프라',
                '고밀도 컴퓨팅 통합',
                '소프트웨어 정의 데이터센터 자동화',
              ],
              supportedProtocols: ['PCIe Gen5', 'iLO 6', 'Redfish', 'OneView API'],
              haFeatures: ['Redundant frame link modules', 'N+N power', 'Hot-plug compute modules'],
              securityCapabilities: ['Silicon Root of Trust', 'TPM 2.0', 'Secure Boot', 'RBAC via OneView'],
              specs: {
                'Compute Modules': 'Up to 12x half-height or 6x full-height modules',
                'Fabric Modules': '6x Virtual Connect (Ethernet/FC)',
                'Power Supply': 'Up to 6x 2650W PSU (N+N redundant)',
                'Management': 'HPE OneView + iLO for composable management',
                'Networking': 'Up to 40GbE / 32Gb FC via Virtual Connect',
                'Form Factor': '10U composable frame',
                'Storage': 'Shared SAS storage via D3940 storage module',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 5. Storage
    // =====================================================================
    {
      nodeId: 'hpe-aruba-storage',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Storage',
      nameKo: '스토리지',
      description:
        'HPE Alletra storage portfolio providing unified block, file, and object storage with cloud-native data services and NVMe-first architecture',
      descriptionKo:
        '클라우드 네이티브 데이터 서비스와 NVMe 우선 아키텍처를 갖춘 통합 블록, 파일, 오브젝트 스토리지를 제공하는 HPE Alletra 스토리지 포트폴리오',
      sourceUrl: 'https://www.hpe.com/us/en/storage.html',
      infraNodeTypes: ['san-nas', 'storage'],
      children: [
        // -- HPE Alletra --
        {
          nodeId: 'hpe-aruba-alletra',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'HPE Alletra',
          nameKo: 'HPE Alletra',
          description:
            'Cloud-native disaggregated storage portfolio with unified block/file/object protocols, all-flash NVMe architecture, and data services as-a-service via HPE GreenLake',
          descriptionKo:
            'HPE GreenLake를 통한 as-a-service 데이터 서비스, 올플래시 NVMe 아키텍처, 통합 블록/파일/오브젝트 프로토콜을 갖춘 클라우드 네이티브 분리형 스토리지 포트폴리오',
          sourceUrl: 'https://www.hpe.com/us/en/storage/alletra.html',
          infraNodeTypes: ['san-nas', 'storage'],
          architectureRole: 'Primary Storage / Unified Data Platform',
          architectureRoleKo: '주 스토리지 / 통합 데이터 플랫폼',
          recommendedFor: [
            'Mission-critical database storage (Oracle, SAP HANA, SQL)',
            'Unified block/file/object workloads',
            'Virtualization datastores (VMware, Hyper-V)',
            'Cloud-native application persistent storage',
            'Storage-as-a-service via HPE GreenLake',
          ],
          recommendedForKo: [
            '미션 크리티컬 데이터베이스 스토리지 (Oracle, SAP HANA, SQL)',
            '통합 블록/파일/오브젝트 워크로드',
            '가상화 데이터스토어 (VMware, Hyper-V)',
            '클라우드 네이티브 애플리케이션 영구 스토리지',
            'HPE GreenLake를 통한 서비스형 스토리지',
          ],
          supportedProtocols: [
            'NVMe-oF (FC-NVMe, NVMe/TCP)',
            'FC (16/32Gb)',
            'iSCSI',
            'NFS',
            'SMB',
            'S3 (object)',
            'Redfish',
          ],
          haFeatures: [
            'Active/Active dual-controller',
            'Transparent failover',
            '99.9999% availability guarantee',
            'Non-disruptive upgrades',
          ],
          securityCapabilities: [
            'Data-at-rest encryption (AES-256)',
            'Data-in-flight encryption',
            'Role-based access control',
            'Audit logging',
            'FIPS 140-2 compliance',
          ],
          children: [
            {
              nodeId: 'hpe-aruba-alletra-mp',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Alletra MP (Multi-Protocol)',
              nameKo: 'Alletra MP (멀티 프로토콜)',
              description:
                'Unified multi-protocol all-flash storage array supporting block, file, and object on a single NVMe platform with cloud-native data services',
              descriptionKo:
                '클라우드 네이티브 데이터 서비스를 갖춘 단일 NVMe 플랫폼에서 블록, 파일, 오브젝트를 지원하는 통합 멀티 프로토콜 올플래시 스토리지 어레이',
              sourceUrl: 'https://www.hpe.com/us/en/storage/alletra-mp.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'as-a-service',
              maxThroughput: '1.2M IOPS',
              architectureRole: 'Unified Primary Storage / All-Flash Array',
              architectureRoleKo: '통합 주 스토리지 / 올플래시 어레이',
              recommendedFor: [
                'Mission-critical mixed-protocol storage consolidation',
                'Enterprise database primary storage',
                'VMware/Hyper-V datastore with guaranteed SLA',
                'Storage-as-a-service via HPE GreenLake',
              ],
              recommendedForKo: [
                '미션 크리티컬 혼합 프로토콜 스토리지 통합',
                '엔터프라이즈 데이터베이스 주 스토리지',
                'SLA 보장 VMware/Hyper-V 데이터스토어',
                'HPE GreenLake를 통한 서비스형 스토리지',
              ],
              supportedProtocols: ['NVMe-oF', 'FC (32Gb)', 'iSCSI', 'NFS', 'SMB', 'S3'],
              haFeatures: ['Active/Active controllers', '99.9999% availability', 'Non-disruptive upgrades', 'Transparent failover'],
              securityCapabilities: ['AES-256 encryption', 'FIPS 140-2', 'RBAC', 'Audit logging'],
              specs: {
                'Storage Media': 'All-flash NVMe SSD',
                'Max Raw Capacity': 'Up to 4.5 PB per array',
                'Max IOPS': '1.2M IOPS (100% random read)',
                'Protocols': 'Block (FC, iSCSI, NVMe-oF), File (NFS, SMB), Object (S3)',
                'Data Services': 'Thin provisioning, deduplication, compression, snapshots, replication',
                'Availability': '99.9999% guaranteed',
                'Management': 'HPE GreenLake / Data Services Cloud Console',
                'Form Factor': '2U rack-mount',
              },
              children: [],
            },
            {
              nodeId: 'hpe-aruba-alletra-storage-server',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Alletra Storage Server',
              nameKo: 'Alletra 스토리지 서버',
              description:
                'Software-defined storage solution built on HPE ProLiant servers for flexible, scale-out file and object storage workloads',
              descriptionKo:
                '유연한 스케일아웃 파일 및 오브젝트 스토리지 워크로드를 위해 HPE ProLiant 서버 기반으로 구축된 소프트웨어 정의 스토리지 솔루션',
              sourceUrl: 'https://www.hpe.com/us/en/storage/alletra-storage-server.html',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              architectureRole: 'Software-Defined Storage / Scale-Out File & Object',
              architectureRoleKo: '소프트웨어 정의 스토리지 / 스케일아웃 파일 및 오브젝트',
              recommendedFor: [
                'Scale-out file storage for unstructured data',
                'Object storage for cloud-native applications',
                'Media and entertainment large file workflows',
                'Backup target and archive storage',
              ],
              recommendedForKo: [
                '비정형 데이터를 위한 스케일아웃 파일 스토리지',
                '클라우드 네이티브 애플리케이션용 오브젝트 스토리지',
                '미디어 및 엔터테인먼트 대용량 파일 워크플로우',
                '백업 대상 및 아카이브 스토리지',
              ],
              supportedProtocols: ['NFS', 'SMB', 'S3', 'iSCSI', 'Redfish'],
              haFeatures: ['Scale-out cluster architecture', 'Data replication', 'Node failure tolerance'],
              securityCapabilities: ['AES-256 encryption', 'RBAC', 'Audit logging', 'WORM compliance'],
              specs: {
                'Platform': 'HPE ProLiant DL server-based',
                'Storage Type': 'Software-defined (file + object)',
                'Scale-Out': 'Up to 16 nodes per cluster',
                'Max Capacity': 'Petabyte-scale',
                'Protocols': 'NFS, SMB, S3, iSCSI',
                'Data Services': 'Erasure coding, replication, tiering, snapshots',
                'Management': 'HPE GreenLake / Data Services Cloud Console',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
