/**
 * Oracle -- Full Product Catalog
 *
 * Hierarchical product tree covering Oracle Database (On-Premises, Autonomous,
 * MySQL HeatWave, NoSQL), Engineered Systems (Exadata), Oracle Cloud
 * Infrastructure (Compute, Networking, Storage), and Data Management categories.
 *
 * Data sourced from https://www.oracle.com/database/
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Oracle Product Catalog
// ---------------------------------------------------------------------------

export const oracleCatalog: VendorCatalog = {
  vendorId: 'oracle',
  vendorName: 'Oracle',
  vendorNameKo: '오라클',
  headquarters: 'Austin, TX, USA',
  website: 'https://www.oracle.com',
  productPageUrl: 'https://www.oracle.com/database/',
  depthStructure: ['category', 'product-line', 'edition'],
  depthStructureKo: ['카테고리', '제품 라인', '에디션'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.oracle.com/database/',
  stats: { totalProducts: 40, maxDepth: 2, categoriesCount: 4 },
  products: [
    // =====================================================================
    // 1. Oracle Database
    // =====================================================================
    {
      nodeId: 'oracle-database',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Oracle Database',
      nameKo: 'Oracle 데이터베이스',
      description:
        'Industry-leading relational and multi-model database platform spanning on-premises, autonomous cloud, MySQL, and NoSQL offerings for enterprise data management',
      descriptionKo:
        '엔터프라이즈 데이터 관리를 위한 온프레미스, 자율 클라우드, MySQL, NoSQL을 아우르는 업계 최고의 관계형 및 멀티모델 데이터베이스 플랫폼',
      sourceUrl: 'https://www.oracle.com/database/',
      infraNodeTypes: ['db-server'],
      children: [
        // ── Oracle Database On-Premises ──
        {
          nodeId: 'oracle-db-on-premises',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle Database On-Premises',
          nameKo: 'Oracle Database 온프레미스',
          description:
            'Self-managed Oracle Database editions for on-premises data centers with full DBA control over installation, patching, and configuration',
          descriptionKo:
            '설치, 패치, 구성에 대한 완전한 DBA 제어 기능을 갖춘 온프레미스 데이터센터용 자체 관리형 Oracle Database 에디션',
          sourceUrl: 'https://www.oracle.com/database/technologies/',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Core Data Tier / Enterprise RDBMS',
          architectureRoleKo: '코어 데이터 계층 / 엔터프라이즈 RDBMS',
          recommendedFor: [
            'Mission-critical OLTP workloads requiring maximum control',
            'Regulated industries with strict data sovereignty requirements',
            'Legacy application modernization with Oracle compatibility',
            'High-performance transaction processing at scale',
          ],
          recommendedForKo: [
            '최대 제어가 필요한 미션 크리티컬 OLTP 워크로드',
            '엄격한 데이터 주권 요구사항이 있는 규제 산업',
            'Oracle 호환성을 갖춘 레거시 애플리케이션 현대화',
            '대규모 고성능 트랜잭션 처리',
          ],
          supportedProtocols: [
            'SQL',
            'PL/SQL',
            'JSON',
            'REST',
            'JDBC',
            'ODBC',
            'Oracle Net/TNS',
          ],
          haFeatures: [
            'Oracle RAC',
            'Data Guard',
            'GoldenGate',
            'Automatic Storage Management',
          ],
          securityCapabilities: [
            'Transparent Data Encryption (TDE)',
            'Database Vault',
            'Audit Vault',
            'Label Security',
            'Advanced Security Option',
          ],
          children: [
            {
              nodeId: 'oracle-db-23ai-enterprise',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle Database 23ai Enterprise Edition',
              nameKo: 'Oracle Database 23ai 엔터프라이즈 에디션',
              description:
                'Full-featured enterprise RDBMS with AI Vector Search, partitioning, RAC, Data Guard, and unlimited scalability for mission-critical workloads',
              descriptionKo:
                'AI 벡터 검색, 파티셔닝, RAC, Data Guard 및 무제한 확장성을 갖춘 미션 크리티컬 워크로드용 완전한 기능의 엔터프라이즈 RDBMS',
              sourceUrl: 'https://www.oracle.com/database/enterprise/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'appliance',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Core Data Tier / Mission-Critical RDBMS',
              architectureRoleKo: '코어 데이터 계층 / 미션 크리티컬 RDBMS',
              recommendedFor: [
                'Large-scale enterprise OLTP and mixed workloads',
                'Data warehousing and analytics with partitioning',
                'High availability deployments with RAC and Data Guard',
                'AI-powered applications with vector search capabilities',
                'Multi-tenant consolidation for ISVs and service providers',
              ],
              recommendedForKo: [
                '대규모 엔터프라이즈 OLTP 및 혼합 워크로드',
                '파티셔닝을 활용한 데이터 웨어하우징 및 분석',
                'RAC 및 Data Guard를 활용한 고가용성 배포',
                '벡터 검색 기능을 갖춘 AI 기반 애플리케이션',
                'ISV 및 서비스 제공업체를 위한 멀티테넌트 통합',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'JSON',
                'REST',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Oracle RAC',
                'Data Guard',
                'GoldenGate',
                'Automatic Storage Management',
              ],
              securityCapabilities: [
                'Transparent Data Encryption (TDE)',
                'Database Vault',
                'Audit Vault',
                'Label Security',
                'Advanced Security Option',
              ],
              specs: {
                'Max DB Size': 'Unlimited',
                'Max RAM': 'Unlimited',
                'Max CPUs': 'Unlimited',
                Partitioning: 'Yes (Enterprise option)',
                'Real Application Clusters (RAC)': 'Yes (Enterprise option)',
                'Data Guard': 'Yes',
                'AI Vector Search': 'Yes (built-in)',
                'In-Memory Column Store': 'Yes (Enterprise option)',
                'JSON Relational Duality': 'Yes',
                'Multitenant Architecture': 'Yes (up to 4,096 PDBs)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-db-23ai-standard',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle Database 23ai Standard Edition 2',
              nameKo: 'Oracle Database 23ai 스탠다드 에디션 2',
              description:
                'Cost-effective Oracle Database edition for mid-market deployments with 2-socket limit and essential enterprise features',
              descriptionKo:
                '2소켓 제한과 필수 엔터프라이즈 기능을 갖춘 중소규모 배포를 위한 비용 효율적인 Oracle Database 에디션',
              sourceUrl: 'https://www.oracle.com/database/standard-edition/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'appliance',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Mid-Market Data Tier / Department Database',
              architectureRoleKo: '중소규모 데이터 계층 / 부서 데이터베이스',
              recommendedFor: [
                'Mid-size enterprise and departmental applications',
                'Cost-sensitive Oracle deployments with standard HA needs',
                'Branch office and regional database servers',
              ],
              recommendedForKo: [
                '중소규모 엔터프라이즈 및 부서별 애플리케이션',
                '표준 HA 요구사항을 갖춘 비용 민감형 Oracle 배포',
                '지사 및 지역 데이터베이스 서버',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'JSON',
                'REST',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              haFeatures: ['Data Guard (basic)', 'Automatic Storage Management'],
              specs: {
                'Max Sockets': '2',
                'Max RAM': '128 GB',
                'Real Application Clusters (RAC)': 'No',
                Partitioning: 'No',
                'Data Guard': 'Basic only',
                'In-Memory Column Store': 'No',
                'AI Vector Search': 'Yes (built-in)',
                'JSON Relational Duality': 'Yes',
                'Max PDBs': '3',
              },
              children: [],
            },
            {
              nodeId: 'oracle-db-free',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle Database Free',
              nameKo: 'Oracle Database Free',
              description:
                'Free Oracle Database edition for development, testing, and learning with 12GB user data limit and 2 CPU/2GB RAM constraints',
              descriptionKo:
                '12GB 사용자 데이터 제한 및 2 CPU/2GB RAM 제약 조건을 갖춘 개발, 테스트, 학습용 무료 Oracle Database 에디션',
              sourceUrl: 'https://www.oracle.com/database/free/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'container',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Development / Testing / Learning',
              architectureRoleKo: '개발 / 테스트 / 학습',
              recommendedFor: [
                'Developer local testing and prototyping',
                'CI/CD pipeline database testing',
                'Oracle Database learning and certification prep',
              ],
              recommendedForKo: [
                '개발자 로컬 테스트 및 프로토타이핑',
                'CI/CD 파이프라인 데이터베이스 테스트',
                'Oracle Database 학습 및 자격증 준비',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'JSON',
                'REST',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              specs: {
                'Max User Data': '12 GB',
                'Max RAM': '2 GB',
                'Max CPUs': '2',
                'Container Image': 'Yes (Docker/Podman)',
                License: 'Free (no support)',
                'AI Vector Search': 'Yes (built-in)',
                'JSON Relational Duality': 'Yes',
              },
              children: [],
            },
          ],
        },

        // ── Oracle Autonomous Database ──
        {
          nodeId: 'oracle-autonomous-db',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle Autonomous Database',
          nameKo: 'Oracle 자율운영 데이터베이스',
          description:
            'Self-driving, self-securing, and self-repairing cloud database service that eliminates manual database administration tasks',
          descriptionKo:
            '수동 데이터베이스 관리 작업을 제거하는 자율 운영, 자율 보안, 자율 복구 클라우드 데이터베이스 서비스',
          sourceUrl: 'https://www.oracle.com/autonomous-database/',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Cloud-Native Self-Driving Database',
          architectureRoleKo: '클라우드 네이티브 자율운영 데이터베이스',
          recommendedFor: [
            'Organizations seeking to eliminate DBA overhead',
            'Cloud-first database deployments with automated operations',
            'Mixed OLTP/analytics workloads requiring elastic scaling',
            'Multi-cloud and hybrid cloud database strategies',
          ],
          recommendedForKo: [
            'DBA 오버헤드 제거를 원하는 조직',
            '자동화 운영을 갖춘 클라우드 우선 데이터베이스 배포',
            '탄력적 확장이 필요한 OLTP/분석 혼합 워크로드',
            '멀티클라우드 및 하이브리드 클라우드 데이터베이스 전략',
          ],
          supportedProtocols: [
            'SQL',
            'PL/SQL',
            'JSON',
            'REST',
            'JDBC',
            'ODBC',
            'Oracle Net/TNS',
            'MongoDB API',
          ],
          haFeatures: [
            'Auto-failover',
            'Auto-patching (zero downtime)',
            'Autonomous Data Guard',
            'Cross-region disaster recovery',
          ],
          securityCapabilities: [
            'Always-on encryption (TDE)',
            'Database Vault',
            'Data Safe',
            'Automatic security patching',
          ],
          children: [
            {
              nodeId: 'oracle-atp',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Autonomous Transaction Processing',
              nameKo: '자율 트랜잭션 처리',
              description:
                'Self-driving cloud database optimized for OLTP workloads with auto-scaling, auto-patching, and auto-tuning capabilities',
              descriptionKo:
                '자동 확장, 자동 패치, 자동 튜닝 기능을 갖춘 OLTP 워크로드에 최적화된 자율운영 클라우드 데이터베이스',
              sourceUrl: 'https://www.oracle.com/autonomous-database/autonomous-transaction-processing/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Cloud-Native OLTP Database',
              architectureRoleKo: '클라우드 네이티브 OLTP 데이터베이스',
              recommendedFor: [
                'Cloud-native OLTP applications with variable demand',
                'Microservices backends requiring automated database management',
                'SaaS applications needing elastic transaction processing',
              ],
              recommendedForKo: [
                '가변 수요를 가진 클라우드 네이티브 OLTP 애플리케이션',
                '자동화 데이터베이스 관리가 필요한 마이크로서비스 백엔드',
                '탄력적 트랜잭션 처리가 필요한 SaaS 애플리케이션',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'JSON',
                'REST',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Auto-failover',
                'Auto-patching (zero downtime)',
                'Autonomous Data Guard',
              ],
              specs: {
                'Auto-Scaling': 'Yes (CPU and storage)',
                'Auto-Patching': 'Yes (zero downtime)',
                'Auto-Tuning': 'Yes (SQL plan management)',
                'Max OCPUs': '128 per instance',
                'Max Storage': '384 TB per instance',
                'Encryption': 'Always-on TDE + network encryption',
                'SLA': '99.995% availability',
                'Backup': 'Automatic daily (60-day retention)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-adw',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Autonomous Data Warehouse',
              nameKo: '자율 데이터 웨어하우스',
              description:
                'Self-driving cloud data warehouse with auto-scaling, columnar processing, and built-in machine learning for analytics workloads',
              descriptionKo:
                '분석 워크로드를 위한 자동 확장, 컬럼형 처리, 내장 머신 러닝을 갖춘 자율운영 클라우드 데이터 웨어하우스',
              sourceUrl: 'https://www.oracle.com/autonomous-database/autonomous-data-warehouse/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Cloud Analytics / Data Warehouse',
              architectureRoleKo: '클라우드 분석 / 데이터 웨어하우스',
              recommendedFor: [
                'Enterprise data warehousing with automated optimization',
                'Self-service analytics and BI workloads',
                'Machine learning model training on warehouse data',
              ],
              recommendedForKo: [
                '자동 최적화를 갖춘 엔터프라이즈 데이터 웨어하우징',
                '셀프 서비스 분석 및 BI 워크로드',
                '웨어하우스 데이터에 대한 머신 러닝 모델 학습',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'JSON',
                'REST',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Auto-failover',
                'Auto-patching (zero downtime)',
                'Autonomous Data Guard',
              ],
              specs: {
                'Auto-Scaling': 'Yes (CPU and storage)',
                'Columnar Processing': 'Yes (automatic)',
                'Machine Learning': 'Built-in (OML)',
                'Max OCPUs': '128 per instance',
                'Max Storage': '384 TB per instance',
                'Data Tools': 'Built-in SQL Worksheet, Data Transforms, Catalog',
                'Encryption': 'Always-on TDE + network encryption',
                'SLA': '99.995% availability',
              },
              children: [],
            },
            {
              nodeId: 'oracle-ajd',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Autonomous JSON Database',
              nameKo: '자율 JSON 데이터베이스',
              description:
                'Cloud-native JSON document database with SODA API and MongoDB compatibility for modern application development',
              descriptionKo:
                '현대 애플리케이션 개발을 위한 SODA API 및 MongoDB 호환성을 갖춘 클라우드 네이티브 JSON 문서 데이터베이스',
              sourceUrl: 'https://www.oracle.com/autonomous-database/autonomous-json-database/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Cloud-Native Document Database',
              architectureRoleKo: '클라우드 네이티브 문서 데이터베이스',
              recommendedFor: [
                'Microservices with JSON-centric data models',
                'MongoDB migration to managed Oracle cloud',
                'Event-driven applications with flexible schemas',
              ],
              recommendedForKo: [
                'JSON 중심 데이터 모델을 가진 마이크로서비스',
                '관리형 Oracle 클라우드로의 MongoDB 마이그레이션',
                '유연한 스키마를 가진 이벤트 기반 애플리케이션',
              ],
              supportedProtocols: [
                'SODA API',
                'MongoDB API',
                'REST',
                'SQL',
                'JDBC',
                'ODBC',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Auto-failover',
                'Auto-patching (zero downtime)',
                'Autonomous Data Guard',
              ],
              specs: {
                'SODA API': 'Yes',
                'MongoDB Compatibility': 'Yes (MongoDB API)',
                'Auto-Scaling': 'Yes (CPU and storage)',
                'Max Storage': '20 GB (JSON collections)',
                'Full SQL Access': 'Yes (for JSON data)',
                'Encryption': 'Always-on TDE + network encryption',
                'SLA': '99.995% availability',
              },
              children: [],
            },
          ],
        },

        // ── MySQL HeatWave ──
        {
          nodeId: 'oracle-mysql-heatwave',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'MySQL HeatWave',
          nameKo: 'MySQL HeatWave',
          description:
            'Fully managed MySQL database service with integrated HeatWave in-memory query accelerator for combined OLTP and analytics',
          descriptionKo:
            'OLTP 및 분석 통합을 위한 HeatWave 인메모리 쿼리 가속기가 통합된 완전 관리형 MySQL 데이터베이스 서비스',
          sourceUrl: 'https://www.oracle.com/mysql/',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Converged OLTP+Analytics MySQL',
          architectureRoleKo: '통합 OLTP+분석 MySQL',
          recommendedFor: [
            'MySQL workloads requiring integrated real-time analytics',
            'OLTP applications needing ad-hoc analytical queries',
            'Cost-effective alternative to separate ETL-based analytics pipelines',
            'Machine learning on operational MySQL data',
          ],
          recommendedForKo: [
            '통합 실시간 분석이 필요한 MySQL 워크로드',
            '즉석 분석 쿼리가 필요한 OLTP 애플리케이션',
            '별도 ETL 기반 분석 파이프라인의 비용 효율적 대안',
            '운영 MySQL 데이터에 대한 머신 러닝',
          ],
          supportedProtocols: ['SQL', 'MySQL Wire Protocol', 'JDBC', 'ODBC', 'REST'],
          haFeatures: [
            'Multi-AD high availability',
            'Automatic failover',
            'Point-in-time recovery',
            'Read replicas',
          ],
          children: [
            {
              nodeId: 'oracle-mysql-heatwave-db',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'MySQL HeatWave',
              nameKo: 'MySQL HeatWave',
              description:
                'MySQL database service with HeatWave in-memory accelerator delivering up to 400x faster analytics alongside OLTP',
              descriptionKo:
                'OLTP와 함께 최대 400배 빠른 분석을 제공하는 HeatWave 인메모리 가속기가 포함된 MySQL 데이터베이스 서비스',
              sourceUrl: 'https://www.oracle.com/mysql/heatwave/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Converged OLTP + Real-Time Analytics',
              architectureRoleKo: '통합 OLTP + 실시간 분석',
              recommendedFor: [
                'MySQL applications needing real-time analytics without ETL',
                'Combined OLTP and OLAP on a single MySQL instance',
                'Cost-sensitive analytics replacing separate data warehouse',
              ],
              recommendedForKo: [
                'ETL 없이 실시간 분석이 필요한 MySQL 애플리케이션',
                '단일 MySQL 인스턴스에서의 OLTP 및 OLAP 통합',
                '별도 데이터 웨어하우스를 대체하는 비용 효율적 분석',
              ],
              supportedProtocols: ['SQL', 'MySQL Wire Protocol', 'JDBC', 'ODBC', 'REST'],
              haFeatures: [
                'Multi-AD high availability',
                'Automatic failover',
                'Read replicas',
              ],
              specs: {
                'Analytics Acceleration': 'Up to 400x faster than standard MySQL',
                'HeatWave Engine': 'In-memory massively parallel processing',
                'OLTP+OLAP': 'Single unified engine',
                'Auto ML': 'Built-in HeatWave AutoML',
                'Max HeatWave Nodes': '512 nodes',
                'Encryption': 'TLS in transit, AES-256 at rest',
                'Compatibility': 'MySQL 8.0 compatible',
              },
              children: [],
            },
            {
              nodeId: 'oracle-mysql-heatwave-lakehouse',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'MySQL HeatWave Lakehouse',
              nameKo: 'MySQL HeatWave Lakehouse',
              description:
                'HeatWave extension enabling analytics over data lake files in object storage supporting 36+ file formats',
              descriptionKo:
                '36개 이상의 파일 형식을 지원하는 오브젝트 스토리지의 데이터 레이크 파일에 대한 분석을 가능하게 하는 HeatWave 확장',
              sourceUrl: 'https://www.oracle.com/mysql/heatwave/lakehouse/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Data Lakehouse / Unified Analytics',
              architectureRoleKo: '데이터 레이크하우스 / 통합 분석',
              recommendedFor: [
                'Querying data lake files directly from MySQL without data movement',
                'Multi-format analytics across CSV, Parquet, Avro, JSON, and more',
                'Unified lakehouse architecture replacing separate analytics tools',
              ],
              recommendedForKo: [
                '데이터 이동 없이 MySQL에서 직접 데이터 레이크 파일 쿼리',
                'CSV, Parquet, Avro, JSON 등 다중 형식 분석',
                '별도 분석 도구를 대체하는 통합 레이크하우스 아키텍처',
              ],
              supportedProtocols: ['SQL', 'MySQL Wire Protocol', 'JDBC', 'ODBC', 'REST'],
              specs: {
                'Supported File Formats': '36+ (CSV, Parquet, Avro, JSON, ORC, etc.)',
                'Object Storage': 'OCI Object Storage, AWS S3-compatible',
                'Query Engine': 'HeatWave in-memory parallel processing',
                'Data Loading': 'Automatic parallel loading from object storage',
                'Schema Inference': 'Automatic schema detection',
                'Compression': 'Snappy, Zstd, LZ4, Gzip support',
              },
              children: [],
            },
          ],
        },

        // ── Oracle NoSQL Database ──
        {
          nodeId: 'oracle-nosql',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle NoSQL Database',
          nameKo: 'Oracle NoSQL 데이터베이스',
          description:
            'Distributed multi-model NoSQL database supporting key-value, document, and columnar data models with predictable low-latency',
          descriptionKo:
            '예측 가능한 저지연으로 키-값, 문서, 컬럼형 데이터 모델을 지원하는 분산 멀티모델 NoSQL 데이터베이스',
          sourceUrl: 'https://www.oracle.com/database/nosql/',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Distributed NoSQL Data Layer',
          architectureRoleKo: '분산 NoSQL 데이터 계층',
          recommendedFor: [
            'IoT and time-series data ingestion at scale',
            'Low-latency key-value lookups for session management',
            'Applications requiring flexible schema with horizontal scaling',
          ],
          recommendedForKo: [
            '대규모 IoT 및 시계열 데이터 수집',
            '세션 관리를 위한 저지연 키-값 조회',
            '수평 확장이 가능한 유연한 스키마가 필요한 애플리케이션',
          ],
          supportedProtocols: ['REST', 'JDBC', 'Oracle NoSQL SDK'],
          haFeatures: [
            'Multi-zone replication',
            'Automatic sharding',
            'Configurable consistency levels',
          ],
          children: [
            {
              nodeId: 'oracle-nosql-cloud',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle NoSQL Database Cloud',
              nameKo: 'Oracle NoSQL Database Cloud',
              description:
                'Fully managed NoSQL cloud service with auto-scaling, key-value/document/columnar models, and predictable single-digit millisecond latency',
              descriptionKo:
                '자동 확장, 키-값/문서/컬럼형 모델, 예측 가능한 한자릿수 밀리초 지연을 갖춘 완전 관리형 NoSQL 클라우드 서비스',
              sourceUrl: 'https://www.oracle.com/database/nosql/technologies/nosql/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Managed NoSQL / Serverless Data Store',
              architectureRoleKo: '관리형 NoSQL / 서버리스 데이터 스토어',
              recommendedFor: [
                'Serverless applications needing flexible NoSQL storage',
                'IoT data ingestion with auto-scaling throughput',
                'Global applications requiring multi-region replication',
              ],
              recommendedForKo: [
                '유연한 NoSQL 스토리지가 필요한 서버리스 애플리케이션',
                '자동 확장 처리량을 갖춘 IoT 데이터 수집',
                '다중 리전 복제가 필요한 글로벌 애플리케이션',
              ],
              supportedProtocols: ['REST', 'Oracle NoSQL SDK', 'JDBC'],
              specs: {
                'Data Models': 'Key-Value, Document (JSON), Columnar',
                'Auto-Scaling': 'Yes (throughput and storage)',
                'Latency': 'Single-digit millisecond (predictable)',
                'Replication': 'Multi-region, multi-zone',
                'Consistency': 'Configurable (eventual to strong)',
                'Free Tier': 'Yes (25 GB storage, 50M read/write units)',
                'Encryption': 'Always-on (at rest and in transit)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-nosql-on-premises',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle NoSQL Database On-Premises',
              nameKo: 'Oracle NoSQL Database 온프레미스',
              description:
                'Self-managed distributed NoSQL database for on-premises deployments with full control over cluster configuration and data locality',
              descriptionKo:
                '클러스터 구성 및 데이터 지역성에 대한 완전한 제어를 갖춘 온프레미스 배포용 자체 관리형 분산 NoSQL 데이터베이스',
              sourceUrl: 'https://www.oracle.com/database/nosql/technologies/nosql/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'appliance',
              infraNodeTypes: ['db-server'],
              architectureRole: 'On-Premises Distributed NoSQL',
              architectureRoleKo: '온프레미스 분산 NoSQL',
              recommendedFor: [
                'Data-sovereign deployments requiring on-premises control',
                'Air-gapped environments needing NoSQL capabilities',
                'High-throughput on-premises IoT data stores',
              ],
              recommendedForKo: [
                '온프레미스 제어가 필요한 데이터 주권 배포',
                'NoSQL 기능이 필요한 폐쇄망 환경',
                '고처리량 온프레미스 IoT 데이터 스토어',
              ],
              supportedProtocols: ['REST', 'Oracle NoSQL SDK', 'JDBC'],
              specs: {
                'Data Models': 'Key-Value, Document (JSON), Columnar',
                'Cluster Scaling': 'Horizontal (add storage nodes)',
                'Replication Factor': 'Configurable (typically 3)',
                'Consistency': 'Configurable (eventual to strong)',
                'Admin': 'Oracle NoSQL Admin Console',
                'Community Edition': 'Available (open source)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Engineered Systems
    // =====================================================================
    {
      nodeId: 'oracle-engineered-systems',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Engineered Systems',
      nameKo: '엔지니어드 시스템',
      description:
        'Purpose-built hardware-software integrated systems optimized for Oracle Database with extreme performance, availability, and security',
      descriptionKo:
        '극한 성능, 가용성, 보안을 갖춘 Oracle Database에 최적화된 목적별 하드웨어-소프트웨어 통합 시스템',
      sourceUrl: 'https://www.oracle.com/engineered-systems/',
      infraNodeTypes: ['db-server', 'storage'],
      children: [
        // ── Oracle Exadata ──
        {
          nodeId: 'oracle-exadata',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle Exadata',
          nameKo: 'Oracle Exadata',
          description:
            'Purpose-built database machine delivering extreme Oracle Database performance with Smart Scan offloading, RDMA networking, and persistent memory acceleration',
          descriptionKo:
            'Smart Scan 오프로딩, RDMA 네트워킹, 영속 메모리 가속을 통해 극한의 Oracle Database 성능을 제공하는 목적별 데이터베이스 머신',
          sourceUrl: 'https://www.oracle.com/engineered-systems/exadata/',
          infraNodeTypes: ['db-server', 'storage'],
          architectureRole: 'High-Performance Database Infrastructure',
          architectureRoleKo: '고성능 데이터베이스 인프라',
          recommendedFor: [
            'Mission-critical Oracle Database workloads requiring maximum performance',
            'Consolidation of multiple Oracle databases onto a single platform',
            'OLTP and data warehouse workloads with extreme I/O demands',
            'Hybrid cloud with Exadata Cloud@Customer and Cloud Service',
          ],
          recommendedForKo: [
            '최대 성능이 필요한 미션 크리티컬 Oracle Database 워크로드',
            '단일 플랫폼에 여러 Oracle 데이터베이스 통합',
            '극한 I/O 요구를 가진 OLTP 및 데이터 웨어하우스 워크로드',
            'Exadata Cloud@Customer 및 Cloud Service를 활용한 하이브리드 클라우드',
          ],
          supportedProtocols: [
            'SQL',
            'PL/SQL',
            'RDMA over Converged Ethernet (RoCE)',
            'InfiniBand',
            'Oracle Net/TNS',
            'iSCSI',
          ],
          haFeatures: [
            'Oracle RAC (included)',
            'Data Guard (included)',
            'Automatic Storage Management',
            'Online storage expansion',
            'Rolling patches',
          ],
          securityCapabilities: [
            'Exadata Secure Enclaves',
            'Transparent Data Encryption',
            'Database Vault',
            'Hardware Root of Trust',
          ],
          children: [
            {
              nodeId: 'oracle-exadata-x10m',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Exadata X10M',
              nameKo: 'Exadata X10M',
              description:
                'Latest generation Exadata Database Machine with 2x performance improvement, RDMA networking, persistent memory, and up to 4,608 CPU cores per rack',
              descriptionKo:
                '2배 성능 향상, RDMA 네트워킹, 영속 메모리, 랙당 최대 4,608 CPU 코어를 갖춘 최신 세대 Exadata 데이터베이스 머신',
              sourceUrl: 'https://www.oracle.com/engineered-systems/exadata/database-machine/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'chassis',
              infraNodeTypes: ['db-server', 'storage'],
              architectureRole: 'Mission-Critical Database Platform',
              architectureRoleKo: '미션 크리티컬 데이터베이스 플랫폼',
              recommendedFor: [
                'Highest-performance Oracle Database deployments',
                'Enterprise database consolidation at scale',
                'Real-time analytics on OLTP data with minimal latency',
              ],
              recommendedForKo: [
                '최고 성능 Oracle Database 배포',
                '대규모 엔터프라이즈 데이터베이스 통합',
                '최소 지연으로 OLTP 데이터에 대한 실시간 분석',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'RDMA over Converged Ethernet (RoCE)',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Oracle RAC (included)',
                'Data Guard (included)',
                'Rolling patches',
                'Automatic Storage Management',
              ],
              specs: {
                'Performance': '2x previous generation',
                'Max CPU Cores': 'Up to 4,608 per rack',
                'Networking': 'RDMA over Converged Ethernet (RoCE)',
                'Persistent Memory': 'Yes (Intel Optane)',
                'Smart Scan': 'Yes (SQL offload to storage)',
                'Max Database Servers': '8 per rack',
                'Max Storage Servers': '14 per rack',
                'Flash Storage': 'Up to 1.6 PB per rack',
                'Network Bandwidth': '100 Gbps RoCE per server',
                'Rack Form Factor': '42U or Quarter/Eighth rack',
              },
              children: [],
            },
            {
              nodeId: 'oracle-exadata-cloud-at-customer',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Exadata Cloud@Customer',
              nameKo: 'Exadata Cloud@Customer',
              description:
                'Exadata hardware deployed in customer data center with Oracle-managed cloud operations for data sovereignty and low-latency hybrid cloud',
              descriptionKo:
                '데이터 주권 및 저지연 하이브리드 클라우드를 위해 고객 데이터센터에 배포되고 Oracle이 관리하는 Exadata 하드웨어',
              sourceUrl: 'https://www.oracle.com/engineered-systems/exadata/cloud-at-customer/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'chassis',
              infraNodeTypes: ['db-server', 'storage'],
              architectureRole: 'Hybrid Cloud Database / Data Sovereign Exadata',
              architectureRoleKo: '하이브리드 클라우드 데이터베이스 / 데이터 주권 Exadata',
              recommendedFor: [
                'Regulated industries requiring data to remain on-premises',
                'Hybrid cloud with seamless OCI integration from customer DC',
                'Exadata performance with cloud-like consumption model',
              ],
              recommendedForKo: [
                '데이터가 온프레미스에 유지되어야 하는 규제 산업',
                '고객 DC에서 원활한 OCI 통합을 갖춘 하이브리드 클라우드',
                '클라우드형 소비 모델을 갖춘 Exadata 성능',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'RDMA over Converged Ethernet (RoCE)',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Oracle RAC (included)',
                'Data Guard (included)',
                'Oracle-managed patching',
              ],
              specs: {
                'Deployment': 'Customer data center (Oracle managed)',
                'OCI Integration': 'Full OCI control plane',
                'Billing': 'Pay-as-you-go or annual commitment',
                'Min Configuration': 'Quarter rack (2 DB servers, 3 storage servers)',
                'Networking': 'RDMA over Converged Ethernet (RoCE)',
                'Data Sovereignty': 'Data never leaves customer DC',
              },
              children: [],
            },
            {
              nodeId: 'oracle-exadata-cloud-service',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Exadata Cloud Service',
              nameKo: 'Exadata 클라우드 서비스',
              description:
                'Exadata performance delivered as a fully managed cloud service in OCI with elastic scaling and automated operations',
              descriptionKo:
                '탄력적 확장과 자동화 운영을 갖춘 OCI에서 완전 관리형 클라우드 서비스로 제공되는 Exadata 성능',
              sourceUrl: 'https://www.oracle.com/engineered-systems/exadata/cloud-service/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['db-server', 'storage'],
              architectureRole: 'Cloud-Native Exadata / Managed Database Platform',
              architectureRoleKo: '클라우드 네이티브 Exadata / 관리형 데이터베이스 플랫폼',
              recommendedFor: [
                'Cloud migration of on-premises Exadata workloads',
                'New Oracle Database deployments in public cloud',
                'Elastic database infrastructure with Exadata performance',
              ],
              recommendedForKo: [
                '온프레미스 Exadata 워크로드의 클라우드 마이그레이션',
                '퍼블릭 클라우드에서의 새로운 Oracle Database 배포',
                'Exadata 성능을 갖춘 탄력적 데이터베이스 인프라',
              ],
              supportedProtocols: [
                'SQL',
                'PL/SQL',
                'Oracle Net/TNS',
              ],
              haFeatures: [
                'Oracle RAC (included)',
                'Data Guard (included)',
                'Automatic patching',
                'Elastic scaling',
              ],
              specs: {
                'Deployment': 'OCI public cloud',
                'Elastic Scaling': 'Yes (CPU, storage independently)',
                'Min OCPUs': '2 per VM cluster',
                'Max OCPUs': '400+ per VM cluster',
                'Smart Scan': 'Yes (SQL offload to storage)',
                'Automated Patching': 'Yes (scheduled maintenance)',
                'Multi-VM Cluster': 'Yes (multiple databases per Exadata)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. Oracle Cloud Infrastructure
    // =====================================================================
    {
      nodeId: 'oracle-cloud-infrastructure',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Oracle Cloud Infrastructure',
      nameKo: 'Oracle 클라우드 인프라',
      description:
        'Enterprise-grade cloud platform offering compute, networking, and storage services with strong security isolation and competitive pricing',
      descriptionKo:
        '강력한 보안 격리와 경쟁력 있는 가격을 제공하는 엔터프라이즈급 클라우드 플랫폼 컴퓨팅, 네트워킹, 스토리지 서비스',
      sourceUrl: 'https://www.oracle.com/cloud/',
      infraNodeTypes: ['private-cloud'],
      children: [
        // ── OCI Compute ──
        {
          nodeId: 'oracle-oci-compute',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'OCI Compute',
          nameKo: 'OCI 컴퓨팅',
          description:
            'Flexible virtual machine and bare metal compute instances on OCI with Ampere Arm, AMD EPYC, and Intel Xeon processor options',
          descriptionKo:
            'Ampere Arm, AMD EPYC, Intel Xeon 프로세서 옵션을 갖춘 OCI의 유연한 가상 머신 및 베어메탈 컴퓨팅 인스턴스',
          sourceUrl: 'https://www.oracle.com/cloud/compute/',
          infraNodeTypes: ['vm', 'app-server'],
          architectureRole: 'Cloud Compute / Virtual Machine Host',
          architectureRoleKo: '클라우드 컴퓨팅 / 가상 머신 호스트',
          recommendedFor: [
            'General-purpose cloud compute workloads on OCI',
            'Cost-effective Arm-based compute with Ampere A2',
            'High-performance bare metal for database and HPC',
            'Cloud-native application hosting',
          ],
          recommendedForKo: [
            'OCI에서의 범용 클라우드 컴퓨팅 워크로드',
            'Ampere A2 기반 비용 효율적 Arm 컴퓨팅',
            '데이터베이스 및 HPC를 위한 고성능 베어메탈',
            '클라우드 네이티브 애플리케이션 호스팅',
          ],
          children: [
            {
              nodeId: 'oracle-oci-compute-instances',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Compute Instances',
              nameKo: 'OCI 컴퓨팅 인스턴스',
              description:
                'Flexible VM and bare metal instances with Ampere A2 (Arm), AMD EPYC, and Intel Xeon options for diverse cloud workloads',
              descriptionKo:
                '다양한 클라우드 워크로드를 위한 Ampere A2 (Arm), AMD EPYC, Intel Xeon 옵션의 유연한 VM 및 베어메탈 인스턴스',
              sourceUrl: 'https://www.oracle.com/cloud/compute/virtual-machines/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['vm', 'app-server'],
              architectureRole: 'Cloud VM / Bare Metal Compute',
              architectureRoleKo: '클라우드 VM / 베어메탈 컴퓨팅',
              recommendedFor: [
                'General-purpose cloud compute with flexible shapes',
                'Cost-effective Arm workloads with Ampere A2',
                'Bare metal instances for performance-sensitive applications',
              ],
              recommendedForKo: [
                '유연한 셰이프를 갖춘 범용 클라우드 컴퓨팅',
                'Ampere A2를 활용한 비용 효율적 Arm 워크로드',
                '성능에 민감한 애플리케이션을 위한 베어메탈 인스턴스',
              ],
              specs: {
                'Processors': 'Ampere A2 (Arm), AMD EPYC, Intel Xeon',
                'Flexible Shapes': 'Yes (1-80 OCPUs, custom memory ratio)',
                'Bare Metal': 'Yes (dedicated physical servers)',
                'Max OCPUs': '160 (bare metal)',
                'Max Memory': '2,048 GB (bare metal)',
                'GPU Instances': 'NVIDIA A100, H100 available',
                'Free Tier': 'Yes (1 OCPU, 1 GB RAM Arm instance)',
                'Burstable': 'Yes (E3/E4 Micro instances)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oci-container-instances',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Container Instances',
              nameKo: 'OCI 컨테이너 인스턴스',
              description:
                'Serverless container execution service for running containers without managing infrastructure or orchestration platforms',
              descriptionKo:
                '인프라나 오케스트레이션 플랫폼 관리 없이 컨테이너를 실행하는 서버리스 컨테이너 실행 서비스',
              sourceUrl: 'https://www.oracle.com/cloud/cloud-native/container-instances/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['container'],
              architectureRole: 'Serverless Container Execution',
              architectureRoleKo: '서버리스 컨테이너 실행',
              recommendedFor: [
                'Simple containerized workloads without Kubernetes overhead',
                'Batch jobs and scheduled container tasks',
                'CI/CD pipeline build runners',
              ],
              recommendedForKo: [
                'Kubernetes 오버헤드 없는 간단한 컨테이너화 워크로드',
                '배치 작업 및 예약된 컨테이너 태스크',
                'CI/CD 파이프라인 빌드 러너',
              ],
              specs: {
                'Max OCPUs': '64 per container instance',
                'Max Memory': '1,024 GB',
                'Container Runtime': 'OCI-compatible (Docker images)',
                'Networking': 'VCN integration with private/public subnets',
                'Registry': 'OCI Container Registry (OCIR)',
                'Billing': 'Per-second (OCPU + memory)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oke',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Kubernetes Engine (OKE)',
              nameKo: 'OCI Kubernetes 엔진 (OKE)',
              description:
                'Oracle-managed Kubernetes service with automated cluster lifecycle, virtual node pools, and deep OCI integration',
              descriptionKo:
                '자동 클러스터 라이프사이클, 가상 노드 풀, 깊은 OCI 통합을 갖춘 Oracle 관리형 Kubernetes 서비스',
              sourceUrl: 'https://www.oracle.com/cloud/cloud-native/kubernetes-engine/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['kubernetes'],
              architectureRole: 'Managed Kubernetes / Container Orchestration',
              architectureRoleKo: '관리형 Kubernetes / 컨테이너 오케스트레이션',
              recommendedFor: [
                'Cloud-native microservices on Oracle Cloud',
                'Kubernetes workloads with OCI-native networking and storage',
                'Hybrid Kubernetes with OKE and on-premises clusters',
              ],
              recommendedForKo: [
                'Oracle Cloud에서의 클라우드 네이티브 마이크로서비스',
                'OCI 네이티브 네트워킹 및 스토리지를 활용한 Kubernetes 워크로드',
                'OKE 및 온프레미스 클러스터를 활용한 하이브리드 Kubernetes',
              ],
              specs: {
                'Kubernetes Version': 'CNCF-certified, latest stable',
                'Control Plane': 'Free (Oracle managed)',
                'Virtual Nodes': 'Yes (serverless worker nodes)',
                'Node Pools': 'Managed and self-managed options',
                'Max Nodes': '1,000 per cluster',
                'Networking': 'VCN-native pod networking (OCI CNI)',
                'GPU Support': 'NVIDIA A100, H100 for ML/AI workloads',
              },
              children: [],
            },
          ],
        },

        // ── OCI Networking ──
        {
          nodeId: 'oracle-oci-networking',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'OCI Networking',
          nameKo: 'OCI 네트워킹',
          description:
            'Virtual cloud networking services including VCN, load balancing, and dedicated connectivity for OCI workloads',
          descriptionKo:
            'OCI 워크로드를 위한 VCN, 로드 밸런싱, 전용 연결을 포함한 가상 클라우드 네트워킹 서비스',
          sourceUrl: 'https://www.oracle.com/cloud/networking/',
          infraNodeTypes: ['router', 'load-balancer'],
          architectureRole: 'Cloud Network Fabric',
          architectureRoleKo: '클라우드 네트워크 패브릭',
          recommendedFor: [
            'OCI virtual network isolation and segmentation',
            'Application load balancing with SSL offload',
            'Hybrid connectivity between on-premises and OCI',
            'Low-latency dedicated connections to OCI',
          ],
          recommendedForKo: [
            'OCI 가상 네트워크 격리 및 세분화',
            'SSL 오프로드를 갖춘 애플리케이션 로드 밸런싱',
            '온프레미스와 OCI 간의 하이브리드 연결',
            'OCI로의 저지연 전용 연결',
          ],
          children: [
            {
              nodeId: 'oracle-oci-vcn',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Virtual Cloud Network (VCN)',
              nameKo: 'OCI 가상 클라우드 네트워크 (VCN)',
              description:
                'Software-defined virtual cloud network providing private, isolated network environments with subnets, route tables, and security lists',
              descriptionKo:
                '서브넷, 라우트 테이블, 보안 목록을 갖춘 프라이빗 격리 네트워크 환경을 제공하는 소프트웨어 정의 가상 클라우드 네트워크',
              sourceUrl: 'https://www.oracle.com/cloud/networking/virtual-cloud-network/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['router'],
              architectureRole: 'Cloud Virtual Network / Network Isolation',
              architectureRoleKo: '클라우드 가상 네트워크 / 네트워크 격리',
              recommendedFor: [
                'Network isolation for multi-tier OCI applications',
                'Hybrid cloud networking with VPN and FastConnect peering',
                'Zero-trust micro-segmentation with Network Security Groups',
              ],
              recommendedForKo: [
                '다계층 OCI 애플리케이션을 위한 네트워크 격리',
                'VPN 및 FastConnect 피어링을 통한 하이브리드 클라우드 네트워킹',
                '네트워크 보안 그룹을 활용한 제로트러스트 마이크로 세분화',
              ],
              supportedProtocols: ['TCP/IP', 'IPSec VPN', 'BGP', 'VXLAN'],
              specs: {
                'Max Subnets': '300 per VCN',
                'Max VCNs': '50 per region (expandable)',
                'Peering': 'Local and remote VCN peering',
                'Security Lists': 'Stateful and stateless rules',
                'Network Security Groups': 'Yes (per-resource firewalling)',
                'IPv6': 'Supported',
                'DRG': 'Dynamic Routing Gateway (hub-and-spoke)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oci-load-balancer',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Load Balancer',
              nameKo: 'OCI 로드 밸런서',
              description:
                'Managed Layer 4 and Layer 7 load balancer with SSL offloading, content-based routing, and up to 8 Gbps bandwidth',
              descriptionKo:
                'SSL 오프로딩, 콘텐츠 기반 라우팅, 최대 8Gbps 대역폭을 갖춘 관리형 L4/L7 로드 밸런서',
              sourceUrl: 'https://www.oracle.com/cloud/networking/load-balancing/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['load-balancer'],
              architectureRole: 'Cloud Application Load Balancer',
              architectureRoleKo: '클라우드 애플리케이션 로드 밸런서',
              recommendedFor: [
                'HTTP/HTTPS application traffic distribution',
                'SSL/TLS termination at the load balancer tier',
                'Multi-backend health checking and failover',
              ],
              recommendedForKo: [
                'HTTP/HTTPS 애플리케이션 트래픽 분배',
                '로드 밸런서 계층에서의 SSL/TLS 종료',
                '다중 백엔드 헬스체크 및 장애 조치',
              ],
              supportedProtocols: ['HTTP', 'HTTPS', 'TCP', 'HTTP/2', 'WebSocket'],
              specs: {
                'Layer': 'L4 (Network) and L7 (Application)',
                'Max Bandwidth': '8 Gbps (flexible)',
                'SSL Offload': 'Yes (TLS 1.2/1.3)',
                'Health Checks': 'HTTP, HTTPS, TCP',
                'Routing Policies': 'Round robin, IP hash, least connections',
                'Content-Based Routing': 'Yes (path, header, hostname)',
                'WebSocket': 'Supported',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oci-fastconnect',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI FastConnect',
              nameKo: 'OCI FastConnect',
              description:
                'Dedicated private connectivity between on-premises networks and OCI at 1, 10, or 100 Gbps with low latency and high reliability',
              descriptionKo:
                '낮은 지연과 높은 안정성으로 온프레미스 네트워크와 OCI 간 1, 10, 100 Gbps 전용 프라이빗 연결',
              sourceUrl: 'https://www.oracle.com/cloud/networking/fastconnect/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['router'],
              architectureRole: 'Dedicated Hybrid Cloud Connectivity',
              architectureRoleKo: '전용 하이브리드 클라우드 연결',
              recommendedFor: [
                'Low-latency hybrid cloud with predictable performance',
                'High-bandwidth data transfer between DC and OCI',
                'Regulatory compliant private connectivity (no public internet)',
              ],
              recommendedForKo: [
                '예측 가능한 성능을 갖춘 저지연 하이브리드 클라우드',
                'DC와 OCI 간 고대역폭 데이터 전송',
                '공용 인터넷 미사용 규제 준수 프라이빗 연결',
              ],
              supportedProtocols: ['BGP', 'IEEE 802.1Q (VLAN tagging)', 'LACP'],
              specs: {
                'Bandwidth Options': '1 Gbps, 10 Gbps, 100 Gbps',
                'Redundancy': 'Dual-path recommended (active/active)',
                'Latency': 'Sub-millisecond (colocation partners)',
                'Partners': 'Equinix, Megaport, AT&T, NTT, and more',
                'BGP Peering': 'Private and public peering options',
                'SLA': '99.95% availability',
              },
              children: [],
            },
          ],
        },

        // ── OCI Storage ──
        {
          nodeId: 'oracle-oci-storage',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'OCI Storage',
          nameKo: 'OCI 스토리지',
          description:
            'Cloud storage services including object, block, and file storage for diverse application and data workloads on OCI',
          descriptionKo:
            'OCI에서 다양한 애플리케이션 및 데이터 워크로드를 위한 오브젝트, 블록, 파일 스토리지를 포함한 클라우드 스토리지 서비스',
          sourceUrl: 'https://www.oracle.com/cloud/storage/',
          infraNodeTypes: ['object-storage', 'storage'],
          architectureRole: 'Cloud Storage Fabric',
          architectureRoleKo: '클라우드 스토리지 패브릭',
          recommendedFor: [
            'Object storage for unstructured data and backups',
            'High-performance block storage for databases and VMs',
            'Shared file systems for cloud-native applications',
            'Tiered storage with automatic cost optimization',
          ],
          recommendedForKo: [
            '비정형 데이터 및 백업을 위한 오브젝트 스토리지',
            '데이터베이스 및 VM을 위한 고성능 블록 스토리지',
            '클라우드 네이티브 애플리케이션을 위한 공유 파일 시스템',
            '자동 비용 최적화를 갖춘 계층형 스토리지',
          ],
          children: [
            {
              nodeId: 'oracle-oci-object-storage',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Object Storage',
              nameKo: 'OCI 오브젝트 스토리지',
              description:
                'S3-compatible object storage with 99.999999999% durability, lifecycle policies, and 10TB max object size for unstructured data',
              descriptionKo:
                '비정형 데이터를 위한 99.999999999% 내구성, 라이프사이클 정책, 10TB 최대 객체 크기를 갖춘 S3 호환 오브젝트 스토리지',
              sourceUrl: 'https://www.oracle.com/cloud/storage/object-storage/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['object-storage'],
              architectureRole: 'Cloud Object Storage / Data Lake Foundation',
              architectureRoleKo: '클라우드 오브젝트 스토리지 / 데이터 레이크 기반',
              recommendedFor: [
                'Unstructured data storage (images, videos, logs)',
                'Backup and disaster recovery target storage',
                'Data lake foundation for analytics workloads',
              ],
              recommendedForKo: [
                '비정형 데이터 저장 (이미지, 비디오, 로그)',
                '백업 및 재해 복구 대상 스토리지',
                '분석 워크로드를 위한 데이터 레이크 기반',
              ],
              supportedProtocols: ['S3-compatible API', 'Swift API', 'REST'],
              specs: {
                'Durability': '99.999999999% (11 nines)',
                'Max Object Size': '10 TB',
                'Storage Tiers': 'Standard, Infrequent Access, Archive',
                'Lifecycle Policies': 'Automatic tier migration',
                'Encryption': 'AES-256 (Oracle-managed or customer-managed keys)',
                'Versioning': 'Supported',
                'Replication': 'Cross-region replication available',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oci-block-volumes',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI Block Volumes',
              nameKo: 'OCI 블록 볼륨',
              description:
                'High-performance block storage for OCI compute instances with up to 32TB per volume and 700K IOPS Ultra High Performance tier',
              descriptionKo:
                '볼륨당 최대 32TB 및 700K IOPS 울트라 하이 퍼포먼스 계층을 갖춘 OCI 컴퓨팅 인스턴스용 고성능 블록 스토리지',
              sourceUrl: 'https://www.oracle.com/cloud/storage/block-volumes/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['storage'],
              architectureRole: 'Cloud Block Storage / Persistent Disk',
              architectureRoleKo: '클라우드 블록 스토리지 / 영속 디스크',
              recommendedFor: [
                'Database persistent storage on OCI compute',
                'High-IOPS applications requiring ultra-high performance',
                'Boot volumes and data disks for cloud instances',
              ],
              recommendedForKo: [
                'OCI 컴퓨팅의 데이터베이스 영속 스토리지',
                '울트라 하이 퍼포먼스가 필요한 고 IOPS 애플리케이션',
                '클라우드 인스턴스의 부트 볼륨 및 데이터 디스크',
              ],
              specs: {
                'Max Volume Size': '32 TB',
                'Max IOPS': '700,000 (Ultra High Performance)',
                'Performance Tiers': 'Lower Cost, Balanced, Higher Performance, Ultra High Performance',
                'Max Throughput': '2,680 MB/s (Ultra High Performance)',
                'Snapshots': 'Yes (incremental, cross-region copy)',
                'Encryption': 'AES-256 (always-on)',
                'Multi-Attach': 'Yes (read/write shareable)',
              },
              children: [],
            },
            {
              nodeId: 'oracle-oci-file-storage',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'OCI File Storage',
              nameKo: 'OCI 파일 스토리지',
              description:
                'Managed NFS file system service with NFSv3 support, up to 8 EB max capacity, and built-in snapshots for shared cloud storage',
              descriptionKo:
                'NFSv3 지원, 최대 8EB 용량, 내장 스냅샷을 갖춘 공유 클라우드 스토리지용 관리형 NFS 파일 시스템 서비스',
              sourceUrl: 'https://www.oracle.com/cloud/storage/file-storage/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['san-nas'],
              architectureRole: 'Cloud Shared File System / NFS',
              architectureRoleKo: '클라우드 공유 파일 시스템 / NFS',
              recommendedFor: [
                'Shared file storage across multiple compute instances',
                'Lift-and-shift of NFS-dependent applications to cloud',
                'Container persistent volumes via NFS',
              ],
              recommendedForKo: [
                '여러 컴퓨팅 인스턴스 간 공유 파일 스토리지',
                'NFS 의존 애플리케이션의 클라우드 리프트앤시프트',
                'NFS를 통한 컨테이너 영속 볼륨',
              ],
              supportedProtocols: ['NFSv3'],
              specs: {
                'Protocol': 'NFSv3',
                'Max Capacity': '8 EB per file system',
                'Snapshots': 'Yes (unlimited, instant)',
                'Clones': 'Yes (writable clones from snapshots)',
                'Encryption': 'AES-256 at rest',
                'IOPS': 'Scales with file system size',
                'Mount Targets': 'Multiple per VCN subnet',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Data Management
    // =====================================================================
    {
      nodeId: 'oracle-data-management',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Data Management',
      nameKo: '데이터 관리',
      description:
        'Data integration, replication, and analytics tools for enterprise data movement, transformation, and business intelligence',
      descriptionKo:
        '엔터프라이즈 데이터 이동, 변환, 비즈니스 인텔리전스를 위한 데이터 통합, 복제, 분석 도구',
      sourceUrl: 'https://www.oracle.com/database/data-management/',
      infraNodeTypes: ['db-server'],
      children: [
        // ── Oracle GoldenGate ──
        {
          nodeId: 'oracle-goldengate',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle GoldenGate',
          nameKo: 'Oracle GoldenGate',
          description:
            'Real-time data replication and change data capture (CDC) platform for heterogeneous database environments',
          descriptionKo:
            '이기종 데이터베이스 환경을 위한 실시간 데이터 복제 및 변경 데이터 캡처(CDC) 플랫폼',
          sourceUrl: 'https://www.oracle.com/integration/goldengate/',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Real-Time Data Replication / CDC',
          architectureRoleKo: '실시간 데이터 복제 / CDC',
          recommendedFor: [
            'Zero-downtime database migration between heterogeneous systems',
            'Real-time data streaming for operational analytics',
            'Active-active database replication for disaster recovery',
            'Cloud migration with continuous data synchronization',
          ],
          recommendedForKo: [
            '이기종 시스템 간 무중단 데이터베이스 마이그레이션',
            '운영 분석을 위한 실시간 데이터 스트리밍',
            '재해 복구를 위한 액티브-액티브 데이터베이스 복제',
            '지속적 데이터 동기화를 통한 클라우드 마이그레이션',
          ],
          supportedProtocols: ['Oracle Net/TNS', 'JDBC', 'ODBC', 'Kafka', 'REST'],
          haFeatures: [
            'Active-active replication',
            'Automatic conflict detection and resolution',
            'Checkpoint-based recovery',
          ],
          children: [
            {
              nodeId: 'oracle-goldengate-product',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle GoldenGate',
              nameKo: 'Oracle GoldenGate',
              description:
                'Enterprise real-time CDC and replication engine supporting Oracle, SQL Server, MySQL, PostgreSQL, and Kafka targets',
              descriptionKo:
                'Oracle, SQL Server, MySQL, PostgreSQL, Kafka 대상을 지원하는 엔터프라이즈 실시간 CDC 및 복제 엔진',
              sourceUrl: 'https://www.oracle.com/integration/goldengate/',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'appliance',
              infraNodeTypes: ['db-server'],
              architectureRole: 'Real-Time CDC / Data Replication Engine',
              architectureRoleKo: '실시간 CDC / 데이터 복제 엔진',
              recommendedFor: [
                'Cross-database real-time replication (Oracle, SQL Server, MySQL, PostgreSQL)',
                'Kafka streaming integration for event-driven architectures',
                'Zero-downtime migration and active-active DR setups',
              ],
              recommendedForKo: [
                '교차 데이터베이스 실시간 복제 (Oracle, SQL Server, MySQL, PostgreSQL)',
                '이벤트 기반 아키텍처를 위한 Kafka 스트리밍 통합',
                '무중단 마이그레이션 및 액티브-액티브 DR 설정',
              ],
              supportedProtocols: ['Oracle Net/TNS', 'JDBC', 'ODBC', 'Kafka', 'REST'],
              haFeatures: [
                'Active-active replication',
                'Automatic conflict detection and resolution',
                'Checkpoint-based recovery',
              ],
              specs: {
                'Supported Sources': 'Oracle, SQL Server, MySQL, PostgreSQL, DB2',
                'Supported Targets': 'Oracle, SQL Server, MySQL, PostgreSQL, Kafka, Hadoop, S3',
                'CDC Method': 'Log-based (minimal source impact)',
                'Latency': 'Sub-second replication',
                'Data Transformations': 'In-flight mapping, filtering, enrichment',
                'Conflict Resolution': 'Automatic (configurable policies)',
                'Cloud Service': 'Available as OCI GoldenGate',
              },
              children: [],
            },
          ],
        },

        // ── Oracle Data Integrator ──
        {
          nodeId: 'oracle-data-integrator',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle Data Integrator',
          nameKo: 'Oracle Data Integrator',
          description:
            'Enterprise ETL/ELT data integration platform for high-volume data movement and transformation across diverse sources',
          descriptionKo:
            '다양한 소스 간 대용량 데이터 이동 및 변환을 위한 엔터프라이즈 ETL/ELT 데이터 통합 플랫폼',
          sourceUrl: 'https://www.oracle.com/middleware/technologies/data-integrator.html',
          infraNodeTypes: ['db-server'],
          architectureRole: 'Data Integration / ETL Pipeline',
          architectureRoleKo: '데이터 통합 / ETL 파이프라인',
          recommendedFor: [
            'Enterprise data warehouse loading and transformation',
            'Cross-system data integration for master data management',
            'Batch and real-time data movement across heterogeneous sources',
          ],
          recommendedForKo: [
            '엔터프라이즈 데이터 웨어하우스 로딩 및 변환',
            '마스터 데이터 관리를 위한 시스템 간 데이터 통합',
            '이기종 소스 간 배치 및 실시간 데이터 이동',
          ],
          supportedProtocols: ['JDBC', 'ODBC', 'REST', 'SOAP', 'JMS'],
          children: [
            {
              nodeId: 'oracle-data-integrator-product',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle Data Integrator',
              nameKo: 'Oracle Data Integrator',
              description:
                'E-LT based data integration tool leveraging target database engines for high-performance transformations without a separate ETL server',
              descriptionKo:
                '별도의 ETL 서버 없이 대상 데이터베이스 엔진을 활용한 고성능 변환을 위한 E-LT 기반 데이터 통합 도구',
              sourceUrl: 'https://www.oracle.com/middleware/technologies/data-integrator.html',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'appliance',
              infraNodeTypes: ['db-server'],
              architectureRole: 'ETL/ELT Engine / Data Pipeline',
              architectureRoleKo: 'ETL/ELT 엔진 / 데이터 파이프라인',
              recommendedFor: [
                'Oracle-centric data warehouse ETL/ELT pipelines',
                'Heterogeneous data source integration (RDBMS, flat files, XML, Hadoop)',
                'Automated data quality and governance workflows',
              ],
              recommendedForKo: [
                'Oracle 중심 데이터 웨어하우스 ETL/ELT 파이프라인',
                '이기종 데이터 소스 통합 (RDBMS, 플랫 파일, XML, Hadoop)',
                '자동화된 데이터 품질 및 거버넌스 워크플로',
              ],
              supportedProtocols: ['JDBC', 'ODBC', 'REST', 'SOAP', 'JMS'],
              specs: {
                'Architecture': 'E-LT (Extract, Load, Transform in target DB)',
                'Supported Sources': 'Oracle, SQL Server, MySQL, PostgreSQL, flat files, XML, Hadoop',
                'Supported Targets': 'Oracle, SQL Server, MySQL, flat files, Hadoop',
                'Scheduling': 'Built-in agent-based scheduling',
                'Data Quality': 'Built-in profiling and validation',
                'GUI': 'ODI Studio (Eclipse-based)',
                'Cloud Service': 'Available as OCI Data Integration',
              },
              children: [],
            },
          ],
        },

        // ── Oracle Analytics Cloud ──
        {
          nodeId: 'oracle-analytics-cloud',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Oracle Analytics Cloud',
          nameKo: 'Oracle Analytics Cloud',
          description:
            'Cloud-native business intelligence and analytics platform with self-service visualization, augmented analytics, and enterprise reporting',
          descriptionKo:
            '셀프 서비스 시각화, 증강 분석, 엔터프라이즈 리포팅을 갖춘 클라우드 네이티브 비즈니스 인텔리전스 및 분석 플랫폼',
          sourceUrl: 'https://www.oracle.com/business-analytics/analytics-cloud/',
          infraNodeTypes: ['app-server'],
          architectureRole: 'Cloud BI / Analytics Platform',
          architectureRoleKo: '클라우드 BI / 분석 플랫폼',
          recommendedFor: [
            'Enterprise self-service BI and data visualization',
            'AI-powered augmented analytics and natural language queries',
            'Oracle-integrated reporting and dashboards',
          ],
          recommendedForKo: [
            '엔터프라이즈 셀프 서비스 BI 및 데이터 시각화',
            'AI 기반 증강 분석 및 자연어 쿼리',
            'Oracle 통합 리포팅 및 대시보드',
          ],
          supportedProtocols: ['REST', 'JDBC', 'ODBC'],
          children: [
            {
              nodeId: 'oracle-analytics-cloud-product',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Oracle Analytics Cloud',
              nameKo: 'Oracle Analytics Cloud',
              description:
                'Unified cloud analytics service combining self-service visualization, augmented ML insights, and enterprise-grade semantic models',
              descriptionKo:
                '셀프 서비스 시각화, 증강 ML 인사이트, 엔터프라이즈급 시맨틱 모델을 결합한 통합 클라우드 분석 서비스',
              sourceUrl: 'https://www.oracle.com/business-analytics/analytics-cloud/',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['app-server'],
              architectureRole: 'Cloud BI / Self-Service Analytics',
              architectureRoleKo: '클라우드 BI / 셀프 서비스 분석',
              recommendedFor: [
                'Self-service data exploration and dashboard creation',
                'Augmented analytics with built-in ML explanations',
                'Centralized enterprise BI with Oracle data source integration',
              ],
              recommendedForKo: [
                '셀프 서비스 데이터 탐색 및 대시보드 생성',
                '내장 ML 설명을 갖춘 증강 분석',
                'Oracle 데이터 소스 통합을 갖춘 중앙 집중식 엔터프라이즈 BI',
              ],
              supportedProtocols: ['REST', 'JDBC', 'ODBC'],
              specs: {
                'Visualization': 'Self-service drag-and-drop',
                'Augmented Analytics': 'Auto insights, explain, forecast',
                'Semantic Model': 'Enterprise-grade RPD semantic layer',
                'Data Connectivity': '50+ native connectors (Oracle, Snowflake, Salesforce, etc.)',
                'NLP': 'Natural language query interface',
                'Mobile': 'iOS and Android apps',
                'Embedding': 'REST API for embedding in custom apps',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
