/**
 * Palo Alto Networks — Full Product Catalog
 *
 * Hierarchical product tree covering Network Security, SASE & SD-WAN,
 * Cloud Security, Security Operations, Advanced Threat Prevention,
 * and Management categories.
 *
 * Data sourced from https://www.paloaltonetworks.com/network-security
 * Last crawled: 2026-02-20
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Palo Alto Networks Product Catalog
// ---------------------------------------------------------------------------

export const paloaltoCatalog: VendorCatalog = {
  vendorId: 'palo-alto-networks',
  vendorName: 'Palo Alto Networks',
  vendorNameKo: '팔로알토 네트웍스',
  headquarters: 'Santa Clara, CA, USA',
  website: 'https://www.paloaltonetworks.com',
  productPageUrl: 'https://www.paloaltonetworks.com/network-security',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-20',
  crawlSource: 'https://www.paloaltonetworks.com/network-security',
  stats: { totalProducts: 0, maxDepth: 2, categoriesCount: 6 }, // placeholder — computed below
  products: [
    // =====================================================================
    // 1. Network Security
    // =====================================================================
    {
      nodeId: 'pan-network-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Network Security',
      nameKo: '네트워크 보안',
      description: 'Next-generation firewalls for enterprise, branch, data center, and cloud environments',
      descriptionKo: '엔터프라이즈, 지사, 데이터센터, 클라우드 환경을 위한 차세대 방화벽',
      sourceUrl: 'https://www.paloaltonetworks.com/network-security',
      infraNodeTypes: ['firewall'],
      children: [
        // ── PA-Series (Hardware Firewalls) ──
        {
          nodeId: 'pan-pa-series',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'PA-Series Firewalls',
          nameKo: 'PA 시리즈 방화벽',
          description: 'Hardware-based next-generation firewalls with ML-powered threat prevention for branch, campus, data center, and service provider environments',
          descriptionKo: 'ML 기반 위협 차단 기능을 탑재한 하드웨어 차세대 방화벽 (지사, 캠퍼스, 데이터센터, 서비스 프로바이더 환경)',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall',
          infraNodeTypes: ['firewall'],
          architectureRole: 'Perimeter / Internal Segmentation / Data Center Edge',
          architectureRoleKo: '경계 방화벽 / 내부 세그멘테이션 / 데이터센터 에지',
          recommendedFor: [
            'Branch office perimeter security',
            'Campus network segmentation',
            'Data center north-south traffic inspection',
            'Service provider edge security',
            'Zero Trust micro-segmentation',
          ],
          recommendedForKo: [
            '지사 경계 보안',
            '캠퍼스 네트워크 세그멘테이션',
            '데이터센터 남북 트래픽 검사',
            '서비스 프로바이더 에지 보안',
            '제로 트러스트 마이크로 세그멘테이션',
          ],
          supportedProtocols: [
            'IPSec VPN', 'SSL VPN', 'BGP', 'OSPF', 'RIP',
            'VXLAN', 'SD-WAN', 'LLDP', 'BFD',
          ],
          haFeatures: [
            'Active/Active HA',
            'Active/Passive HA',
            'Session synchronization',
            'Path monitoring',
            'HA4 session backup link',
          ],
          securityCapabilities: [
            'App-ID (Application identification)',
            'Content-ID (Threat prevention)',
            'User-ID (User identification)',
            'WildFire (Cloud sandboxing)',
            'SSL/TLS Decryption',
            'DNS Security',
            'IoT Security',
            'Advanced URL Filtering',
          ],
          children: [
            // ── PA-400 Series ──
            {
              nodeId: 'pan-pa-410',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-410',
              nameKo: 'PA-410',
              description: 'Entry-level desktop NGFW for small branch offices. 2.4 Gbps firewall throughput.',
              descriptionKo: '소규모 지사용 엔트리급 데스크탑 NGFW. 방화벽 처리량 2.4 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '2.4 Gbps',
                'Threat Prevention Throughput': '1.0 Gbps',
                'IPSec VPN Throughput': '1.8 Gbps',
                'Max Sessions': '200,000',
                'New Sessions/sec': '39,000',
                'Interfaces': '7×GbE copper, 1×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-415',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-415',
              nameKo: 'PA-415',
              description: 'Desktop NGFW with fiber connectivity for small branches. 3.0 Gbps firewall throughput.',
              descriptionKo: '광섬유 연결 기능을 갖춘 소규모 지사용 데스크탑 NGFW. 방화벽 처리량 3.0 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '3.0 Gbps',
                'Threat Prevention Throughput': '1.5 Gbps',
                'IPSec VPN Throughput': '2.2 Gbps',
                'Max Sessions': '200,000',
                'New Sessions/sec': '52,000',
                'Interfaces': '7×GbE copper, 1×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-440',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-440',
              nameKo: 'PA-440',
              description: 'Desktop NGFW for medium branch offices. 3.7 Gbps firewall throughput.',
              descriptionKo: '중규모 지사용 데스크탑 NGFW. 방화벽 처리량 3.7 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '3.7 Gbps',
                'Threat Prevention Throughput': '1.6 Gbps',
                'IPSec VPN Throughput': '2.8 Gbps',
                'Max Sessions': '200,000',
                'New Sessions/sec': '52,000',
                'Interfaces': '8×GbE copper, 2×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-445',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-445',
              nameKo: 'PA-445',
              description: 'Desktop NGFW with PoE and fiber for medium branches. 4.0 Gbps firewall throughput.',
              descriptionKo: 'PoE 및 광섬유 지원 중규모 지사용 데스크탑 NGFW. 방화벽 처리량 4.0 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '4.0 Gbps',
                'Threat Prevention Throughput': '2.0 Gbps',
                'IPSec VPN Throughput': '3.0 Gbps',
                'Max Sessions': '200,000',
                'New Sessions/sec': '55,000',
                'Interfaces': '8×GbE copper (4×PoE), 2×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-450',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-450',
              nameKo: 'PA-450',
              description: 'Desktop NGFW for large branch offices. 5.2 Gbps firewall throughput.',
              descriptionKo: '대규모 지사용 데스크탑 NGFW. 방화벽 처리량 5.2 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '5.2 Gbps',
                'Threat Prevention Throughput': '2.7 Gbps',
                'IPSec VPN Throughput': '3.1 Gbps',
                'Max Sessions': '300,000',
                'New Sessions/sec': '69,000',
                'Interfaces': '8×GbE copper, 4×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-460',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-460',
              nameKo: 'PA-460',
              description: 'Desktop NGFW with PoE for large branches. 5.4 Gbps firewall throughput.',
              descriptionKo: 'PoE 지원 대규모 지사용 데스크탑 NGFW. 방화벽 처리량 5.4 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-400-series',
              lifecycle: 'active',
              infraNodeTypes: ['firewall'],
              architectureRole: 'Branch Perimeter / Small Campus Edge',
              architectureRoleKo: '지사 경계 / 소규모 캠퍼스 에지',
              recommendedFor: [
                'Large branch office perimeter with PoE',
                'Small campus edge security',
                'Retail store or clinic perimeter firewall',
              ],
              recommendedForKo: [
                'PoE 기능의 대규모 지사 경계',
                '소규모 캠퍼스 에지 보안',
                '소매점 또는 클리닉 경계 방화벽',
              ],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '5.4 Gbps',
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              disasterRecovery: {
                multiRegionSupported: false,
              },
              specs: {
                'Firewall Throughput': '5.4 Gbps',
                'Threat Prevention Throughput': '2.8 Gbps',
                'IPSec VPN Throughput': '3.2 Gbps',
                'Max Sessions': '400,000',
                'New Sessions/sec': '74,000',
                'Interfaces': '8×GbE copper (4×PoE), 4×SFP',
              },
              children: [],
            },
            // ── PA-800 Series ──
            {
              nodeId: 'pan-pa-820',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-820',
              nameKo: 'PA-820',
              description: 'Mid-range NGFW for medium enterprise branches. 940 Mbps threat prevention throughput.',
              descriptionKo: '중견기업 지사용 미드레인지 NGFW. 위협 차단 처리량 940 Mbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-800-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '1.8 Gbps',
                'Threat Prevention Throughput': '940 Mbps',
                'IPSec VPN Throughput': '1.0 Gbps',
                'Max Sessions': '128,000',
                'New Sessions/sec': '8,300',
                'Interfaces': '12×GbE copper, 4×SFP',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-850',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-850',
              nameKo: 'PA-850',
              description: 'Mid-range NGFW for medium enterprise sites. 1.9 Gbps threat prevention throughput.',
              descriptionKo: '중견기업 사이트용 미드레인지 NGFW. 위협 차단 처리량 1.9 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-800-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '3.8 Gbps',
                'Threat Prevention Throughput': '1.9 Gbps',
                'IPSec VPN Throughput': '2.2 Gbps',
                'Max Sessions': '192,000',
                'New Sessions/sec': '15,000',
                'Interfaces': '12×GbE copper, 4×SFP, 4×SFP+',
              },
              children: [],
            },
            // ── PA-1400 Series ──
            {
              nodeId: 'pan-pa-1410',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-1410',
              nameKo: 'PA-1410',
              description: 'Branch/small campus NGFW with ML-powered security. 7.9 Gbps firewall throughput.',
              descriptionKo: 'ML 기반 보안을 탑재한 지사/소규모 캠퍼스용 NGFW. 방화벽 처리량 7.9 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-1400-series',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '7.9 Gbps',
              specs: {
                'Firewall Throughput': '7.9 Gbps',
                'Threat Prevention Throughput': '4.6 Gbps',
                'IPSec VPN Throughput': '5.2 Gbps',
                'Max Sessions': '400,000',
                'New Sessions/sec': '75,000',
                'Interfaces': '12×GbE copper, 4×SFP+',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-1420',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-1420',
              nameKo: 'PA-1420',
              description: 'Branch/small campus NGFW with fiber and PoE. 10.5 Gbps firewall throughput.',
              descriptionKo: '광섬유 및 PoE 지원 지사/소규모 캠퍼스용 NGFW. 방화벽 처리량 10.5 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-1400-series',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '10.5 Gbps',
              specs: {
                'Firewall Throughput': '10.5 Gbps',
                'Threat Prevention Throughput': '6.2 Gbps',
                'IPSec VPN Throughput': '6.8 Gbps',
                'Max Sessions': '600,000',
                'New Sessions/sec': '100,000',
                'Interfaces': '12×GbE copper (4×PoE), 4×SFP+, 2×SFP28',
              },
              children: [],
            },
            // ── PA-3200 Series ──
            {
              nodeId: 'pan-pa-3220',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3220',
              nameKo: 'PA-3220',
              description: 'Enterprise edge NGFW for internet gateway deployments. 4.8 Gbps threat prevention throughput.',
              descriptionKo: '인터넷 게이트웨이 배치를 위한 엔터프라이즈 에지 NGFW. 위협 차단 처리량 4.8 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3200-series',
              lifecycle: 'end-of-sale',
              replacedBy: 'pan-pa-3410',
              specs: {
                'Firewall Throughput': '9.2 Gbps',
                'Threat Prevention Throughput': '4.8 Gbps',
                'IPSec VPN Throughput': '4.7 Gbps',
                'Max Sessions': '1,000,000',
                'New Sessions/sec': '56,000',
                'Interfaces': '12×GbE copper, 4×SFP, 4×SFP+',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-3250',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3250',
              nameKo: 'PA-3250',
              description: 'Enterprise edge NGFW with 40G interfaces. 6.4 Gbps threat prevention throughput.',
              descriptionKo: '40G 인터페이스를 갖춘 엔터프라이즈 에지 NGFW. 위협 차단 처리량 6.4 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3200-series',
              lifecycle: 'end-of-sale',
              replacedBy: 'pan-pa-3420',
              specs: {
                'Firewall Throughput': '13.3 Gbps',
                'Threat Prevention Throughput': '6.4 Gbps',
                'IPSec VPN Throughput': '6.8 Gbps',
                'Max Sessions': '2,000,000',
                'New Sessions/sec': '93,000',
                'Interfaces': '12×GbE copper, 8×SFP, 8×SFP+, 2×QSFP+',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-3260',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3260',
              nameKo: 'PA-3260',
              description: 'Enterprise edge NGFW with high-capacity storage. 8.4 Gbps threat prevention throughput.',
              descriptionKo: '대용량 스토리지를 갖춘 엔터프라이즈 에지 NGFW. 위협 차단 처리량 8.4 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3200-series',
              lifecycle: 'end-of-sale',
              replacedBy: 'pan-pa-3430',
              specs: {
                'Firewall Throughput': '15.8 Gbps',
                'Threat Prevention Throughput': '8.4 Gbps',
                'IPSec VPN Throughput': '8.1 Gbps',
                'Max Sessions': '4,000,000',
                'New Sessions/sec': '120,000',
                'Interfaces': '12×GbE copper, 8×SFP, 8×SFP+, 2×QSFP+',
              },
              children: [],
            },
            // ── PA-3400 Series ──
            {
              nodeId: 'pan-pa-3410',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3410',
              nameKo: 'PA-3410',
              description: 'Internet gateway NGFW for medium enterprise. 14.5 Gbps firewall throughput.',
              descriptionKo: '중규모 엔터프라이즈용 인터넷 게이트웨이 NGFW. 방화벽 처리량 14.5 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3400-series',
              lifecycle: 'active',
              infraNodeTypes: ['firewall'],
              architectureRole: 'Enterprise Internet Gateway',
              architectureRoleKo: '엔터프라이즈 인터넷 게이트웨이',
              recommendedFor: [
                'Medium enterprise internet gateway',
                'Campus perimeter with threat prevention',
                'Hybrid cloud edge security',
              ],
              recommendedForKo: [
                '중규모 엔터프라이즈 인터넷 게이트웨이',
                '위협 차단을 갖춘 캠퍼스 경계',
                '하이브리드 클라우드 에지 보안',
              ],
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '14.5 Gbps',
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              disasterRecovery: {
                multiRegionSupported: false,
              },
              specs: {
                'Firewall Throughput': '14.5 Gbps',
                'Threat Prevention Throughput': '7.8 Gbps',
                'IPSec VPN Throughput': '9.8 Gbps',
                'Max Sessions': '1,400,000',
                'New Sessions/sec': '145,000',
                'Interfaces': '12×GbE copper, 4×SFP+, 2×QSFP28',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-3420',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3420',
              nameKo: 'PA-3420',
              description: 'Internet gateway NGFW for large branches. 17.8 Gbps firewall throughput.',
              descriptionKo: '대규모 지사용 인터넷 게이트웨이 NGFW. 방화벽 처리량 17.8 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3400-series',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '17.8 Gbps',
              specs: {
                'Firewall Throughput': '17.8 Gbps',
                'Threat Prevention Throughput': '9.5 Gbps',
                'IPSec VPN Throughput': '12.5 Gbps',
                'Max Sessions': '1,800,000',
                'New Sessions/sec': '190,000',
                'Interfaces': '12×GbE copper, 8×SFP+, 2×QSFP28',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-3430',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3430',
              nameKo: 'PA-3430',
              description: 'Internet gateway NGFW for enterprise campus. 23.5 Gbps firewall throughput.',
              descriptionKo: '엔터프라이즈 캠퍼스용 인터넷 게이트웨이 NGFW. 방화벽 처리량 23.5 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3400-series',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '23.5 Gbps',
              specs: {
                'Firewall Throughput': '23.5 Gbps',
                'Threat Prevention Throughput': '13.2 Gbps',
                'IPSec VPN Throughput': '16.2 Gbps',
                'Max Sessions': '2,500,000',
                'New Sessions/sec': '225,000',
                'Interfaces': '12×GbE copper, 8×SFP+, 4×QSFP28',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-3440',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-3440',
              nameKo: 'PA-3440',
              description: 'Top-tier internet gateway NGFW. 28.5 Gbps firewall throughput.',
              descriptionKo: '최상위 인터넷 게이트웨이 NGFW. 방화벽 처리량 28.5 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-3400-series',
              lifecycle: 'active',
              formFactor: 'appliance',
              licensingModel: 'subscription',
              maxThroughput: '28.5 Gbps',
              specs: {
                'Firewall Throughput': '28.5 Gbps',
                'Threat Prevention Throughput': '16.5 Gbps',
                'IPSec VPN Throughput': '19.5 Gbps',
                'Max Sessions': '3,200,000',
                'New Sessions/sec': '280,000',
                'Interfaces': '12×GbE copper, 8×SFP+, 4×QSFP28',
              },
              children: [],
            },
            // ── PA-5200 Series ──
            {
              nodeId: 'pan-pa-5220',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5220',
              nameKo: 'PA-5220',
              description: 'High-performance data center NGFW. 18 Gbps firewall throughput, 9 Gbps threat prevention.',
              descriptionKo: '고성능 데이터센터 NGFW. 방화벽 18 Gbps, 위협 차단 9 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5200-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '18 Gbps',
                'Threat Prevention Throughput': '9 Gbps',
                'IPSec VPN Throughput': '9 Gbps',
                'Max Sessions': '4,000,000',
                'New Sessions/sec': '163,000',
                'Interfaces': '16×SFP+, 4×QSFP+, 8×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5250',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5250',
              nameKo: 'PA-5250',
              description: 'High-performance data center NGFW. 35 Gbps firewall throughput, 18 Gbps threat prevention.',
              descriptionKo: '고성능 데이터센터 NGFW. 방화벽 35 Gbps, 위협 차단 18 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5200-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '35 Gbps',
                'Threat Prevention Throughput': '18 Gbps',
                'IPSec VPN Throughput': '16 Gbps',
                'Max Sessions': '8,000,000',
                'New Sessions/sec': '350,000',
                'Interfaces': '16×SFP+, 4×QSFP+, 8×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5260',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5260',
              nameKo: 'PA-5260',
              description: 'High-performance data center NGFW. 60 Gbps firewall throughput, 30 Gbps threat prevention.',
              descriptionKo: '고성능 데이터센터 NGFW. 방화벽 60 Gbps, 위협 차단 30 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5200-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '60 Gbps',
                'Threat Prevention Throughput': '30 Gbps',
                'IPSec VPN Throughput': '24 Gbps',
                'Max Sessions': '32,000,000',
                'New Sessions/sec': '578,000',
                'Interfaces': '16×SFP+, 8×QSFP+, 12×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5280',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5280',
              nameKo: 'PA-5280',
              description: 'High-performance data center NGFW. 68 Gbps firewall throughput, 34 Gbps threat prevention.',
              descriptionKo: '고성능 데이터센터 NGFW. 방화벽 68 Gbps, 위협 차단 34 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5200-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '68 Gbps',
                'Threat Prevention Throughput': '34 Gbps',
                'IPSec VPN Throughput': '26 Gbps',
                'Max Sessions': '64,000,000',
                'New Sessions/sec': '900,000',
                'Interfaces': '16×SFP+, 8×QSFP+, 12×GbE copper',
              },
              children: [],
            },
            // ── PA-5400 Series ──
            {
              nodeId: 'pan-pa-5410',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5410',
              nameKo: 'PA-5410',
              description: 'Next-gen data center NGFW with dedicated processing. 30 Gbps threat prevention throughput.',
              descriptionKo: '전용 프로세싱의 차세대 데이터센터 NGFW. 위협 차단 처리량 30 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '53.5 Gbps',
                'Threat Prevention Throughput': '30 Gbps',
                'IPSec VPN Throughput': '29.5 Gbps',
                'Max Sessions': '15,000,000',
                'New Sessions/sec': '390,000',
                'Interfaces': '4×QSFP28, 12×SFP28, 14×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5420',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5420',
              nameKo: 'PA-5420',
              description: 'Next-gen data center NGFW. 39 Gbps threat prevention throughput.',
              descriptionKo: '차세대 데이터센터 NGFW. 위협 차단 처리량 39 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '68 Gbps',
                'Threat Prevention Throughput': '39 Gbps',
                'IPSec VPN Throughput': '38 Gbps',
                'Max Sessions': '30,000,000',
                'New Sessions/sec': '600,000',
                'Interfaces': '4×QSFP28, 12×SFP28, 14×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5430',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5430',
              nameKo: 'PA-5430',
              description: 'Next-gen data center NGFW. 49 Gbps threat prevention throughput.',
              descriptionKo: '차세대 데이터센터 NGFW. 위협 차단 처리량 49 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '82 Gbps',
                'Threat Prevention Throughput': '49 Gbps',
                'IPSec VPN Throughput': '46 Gbps',
                'Max Sessions': '45,000,000',
                'New Sessions/sec': '800,000',
                'Interfaces': '4×QSFP28, 12×SFP28, 14×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5440',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5440',
              nameKo: 'PA-5440',
              description: 'Next-gen data center NGFW. 60 Gbps threat prevention throughput.',
              descriptionKo: '차세대 데이터센터 NGFW. 위협 차단 처리량 60 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5400-series',
              lifecycle: 'active',
              specs: {
                'Firewall Throughput': '99 Gbps',
                'Threat Prevention Throughput': '60 Gbps',
                'IPSec VPN Throughput': '56 Gbps',
                'Max Sessions': '60,000,000',
                'New Sessions/sec': '1,100,000',
                'Interfaces': '8×QSFP28, 16×SFP28, 14×GbE copper',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-5450',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-5450',
              nameKo: 'PA-5450',
              description: 'Modular chassis-based data center NGFW with up to 6 DPCs. 150 Gbps threat prevention throughput.',
              descriptionKo: '최대 6개 DPC 모듈 장착 가능한 모듈형 섀시 기반 데이터센터 NGFW. 위협 차단 처리량 150 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-5400-series',
              lifecycle: 'active',
              infraNodeTypes: ['firewall'],
              architectureRole: 'Data Center Core Firewall',
              architectureRoleKo: '데이터센터 코어 방화벽',
              recommendedFor: [
                'Large data center perimeter security',
                'Service provider edge security',
                'High-throughput SSL decryption at scale',
                'Multi-tenant data center firewall',
              ],
              recommendedForKo: [
                '대규모 데이터센터 경계 보안',
                '서비스 프로바이더 에지 보안',
                '대규모 고처리량 SSL 복호화',
                '멀티테넌트 데이터센터 방화벽',
              ],
              formFactor: 'chassis',
              licensingModel: 'subscription',
              maxThroughput: '227 Gbps',
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              disasterRecovery: {
                multiRegionSupported: false,
              },
              specs: {
                'Firewall Throughput': '227 Gbps',
                'Threat Prevention Throughput': '150 Gbps',
                'IPSec VPN Throughput': '120 Gbps',
                'Max Sessions': '100,000,000',
                'New Sessions/sec': '2,500,000',
                'Interfaces': 'Up to 6 DPCs, modular',
                'Form Factor': '4RU chassis',
              },
              children: [],
            },
            // ── PA-7000 Series ──
            {
              nodeId: 'pan-pa-7050',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-7050',
              nameKo: 'PA-7050',
              description: 'Chassis-based NGFW for service providers and large data centers. 120 Gbps firewall throughput.',
              descriptionKo: '서비스 프로바이더 및 대규모 데이터센터용 섀시 기반 NGFW. 방화벽 120 Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-7000-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '120 Gbps',
                'Threat Prevention Throughput': '60 Gbps',
                'IPSec VPN Throughput': '48 Gbps',
                'Max Sessions': '80,000,000',
                'New Sessions/sec': '1,200,000',
                'Form Factor': '12RU chassis, up to 4 NPCs',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-7080',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-7080',
              nameKo: 'PA-7080',
              description: 'Chassis-based NGFW for the largest data center and service provider deployments. 200+ Gbps firewall throughput.',
              descriptionKo: '최대 규모 데이터센터 및 서비스 프로바이더 배치용 섀시 기반 NGFW. 방화벽 200+ Gbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-7000-series',
              lifecycle: 'end-of-sale',
              specs: {
                'Firewall Throughput': '200+ Gbps',
                'Threat Prevention Throughput': '100 Gbps',
                'IPSec VPN Throughput': '80 Gbps',
                'Max Sessions': '160,000,000',
                'New Sessions/sec': '2,400,000',
                'Form Factor': '19RU chassis, up to 10 NPCs',
              },
              children: [],
            },
            {
              nodeId: 'pan-pa-7500',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'PA-7500',
              nameKo: 'PA-7500',
              description: 'Next-gen chassis-based NGFW with FE400 networking processors. 1.5 Tbps App-ID performance.',
              descriptionKo: 'FE400 네트워킹 프로세서 탑재 차세대 섀시 기반 NGFW. App-ID 성능 1.5 Tbps.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/pa-7500-series',
              lifecycle: 'active',
              infraNodeTypes: ['firewall'],
              architectureRole: 'Hyperscale Data Center / Service Provider Core Firewall',
              architectureRoleKo: '하이퍼스케일 데이터센터 / 서비스 프로바이더 코어 방화벽',
              recommendedFor: [
                'Hyperscale data center security (1 Tbps+)',
                'Service provider core firewall',
                'Carrier-grade NAT and security',
                'Large enterprise consolidated security platform',
              ],
              recommendedForKo: [
                '하이퍼스케일 데이터센터 보안 (1 Tbps+)',
                '서비스 프로바이더 코어 방화벽',
                '캐리어급 NAT 및 보안',
                '대기업 통합 보안 플랫폼',
              ],
              formFactor: 'chassis',
              licensingModel: 'subscription',
              maxThroughput: '1.5 Tbps',
              operationalComplexity: 'complex',
              ecosystemMaturity: 'mature',
              disasterRecovery: {
                multiRegionSupported: false,
              },
              specs: {
                'Firewall Throughput': '1.5 Tbps',
                'Threat Prevention Throughput': '400+ Gbps',
                'Max Sessions': '400,000,000',
                'New Sessions/sec': '20,000,000',
                'Form Factor': 'Modular chassis with FE400 NPU',
                'Interfaces': 'Up to 7 NPCs, 400G QSFP-DD',
              },
              children: [],
            },
          ],
        },
        // ── VM-Series (Virtual Firewalls) ──
        {
          nodeId: 'pan-vm-series',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VM-Series (Virtual Firewalls)',
          nameKo: 'VM 시리즈 (가상 방화벽)',
          description: 'Software-based virtual NGFWs for public cloud, private cloud, and hybrid environments. Available on AWS, Azure, GCP, Oracle, and VMware.',
          descriptionKo: '퍼블릭, 프라이빗, 하이브리드 클라우드 환경을 위한 소프트웨어 기반 가상 NGFW. AWS, Azure, GCP, Oracle, VMware 지원.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
          infraNodeTypes: ['firewall'],
          architectureRole: 'Cloud Virtual Perimeter / East-West Segmentation',
          architectureRoleKo: '클라우드 가상 경계 / 동서 세그멘테이션',
          recommendedFor: [
            'Public cloud VPC/VNet perimeter security',
            'Private cloud north-south and east-west inspection',
            'Multi-cloud consistent security policy',
          ],
          recommendedForKo: [
            '퍼블릭 클라우드 VPC/VNet 경계 보안',
            '프라이빗 클라우드 남북/동서 트래픽 검사',
            '멀티 클라우드 일관된 보안 정책',
          ],
          children: [
            {
              nodeId: 'pan-vm-50',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'VM-50',
              nameKo: 'VM-50',
              description: 'Entry-level virtual NGFW for small workloads. Up to 200 Mbps firewall throughput.',
              descriptionKo: '소규모 워크로드용 엔트리급 가상 NGFW. 최대 200 Mbps 방화벽 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
              lifecycle: 'end-of-life',
              replacedBy: 'pan-sw-ngfw',
              specs: {
                'Firewall Throughput': '200 Mbps',
                'Threat Prevention Throughput': '100 Mbps',
                'Max Sessions': '64,000',
                'vCPUs': '2',
              },
              children: [],
            },
            {
              nodeId: 'pan-vm-100',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'VM-100',
              nameKo: 'VM-100',
              description: 'Virtual NGFW for medium workloads. Up to 2 Gbps firewall throughput.',
              descriptionKo: '중규모 워크로드용 가상 NGFW. 최대 2 Gbps 방화벽 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
              lifecycle: 'end-of-life',
              replacedBy: 'pan-sw-ngfw',
              specs: {
                'Firewall Throughput': '2 Gbps',
                'Threat Prevention Throughput': '1 Gbps',
                'Max Sessions': '250,000',
                'vCPUs': '2',
              },
              children: [],
            },
            {
              nodeId: 'pan-vm-300',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'VM-300',
              nameKo: 'VM-300',
              description: 'Virtual NGFW for large workloads. Up to 4 Gbps firewall throughput.',
              descriptionKo: '대규모 워크로드용 가상 NGFW. 최대 4 Gbps 방화벽 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
              lifecycle: 'end-of-life',
              replacedBy: 'pan-sw-ngfw',
              infraNodeTypes: ['firewall'],
              formFactor: 'virtual',
              licensingModel: 'subscription',
              maxThroughput: '4 Gbps',
              operationalComplexity: 'moderate',
              ecosystemMaturity: 'mature',
              disasterRecovery: {
                multiRegionSupported: true,
              },
              specs: {
                'Firewall Throughput': '4 Gbps',
                'Threat Prevention Throughput': '2 Gbps',
                'Max Sessions': '819,200',
                'vCPUs': '4',
              },
              children: [],
            },
            {
              nodeId: 'pan-vm-500',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'VM-500',
              nameKo: 'VM-500',
              description: 'Virtual NGFW for high-throughput workloads. Up to 8 Gbps firewall throughput.',
              descriptionKo: '고처리량 워크로드용 가상 NGFW. 최대 8 Gbps 방화벽 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
              lifecycle: 'end-of-life',
              replacedBy: 'pan-sw-ngfw',
              specs: {
                'Firewall Throughput': '8 Gbps',
                'Threat Prevention Throughput': '4 Gbps',
                'Max Sessions': '2,000,000',
                'vCPUs': '8',
              },
              children: [],
            },
            {
              nodeId: 'pan-vm-700',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'VM-700',
              nameKo: 'VM-700',
              description: 'Virtual NGFW for the most demanding workloads. Up to 16 Gbps firewall throughput.',
              descriptionKo: '최고 수준의 워크로드를 위한 가상 NGFW. 최대 16 Gbps 방화벽 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/vm-series',
              lifecycle: 'end-of-life',
              replacedBy: 'pan-sw-ngfw',
              specs: {
                'Firewall Throughput': '16 Gbps',
                'Threat Prevention Throughput': '8 Gbps',
                'Max Sessions': '10,000,000',
                'vCPUs': '16',
              },
              children: [],
            },
          ],
        },
        // ── CN-Series (Container Firewalls) ──
        {
          nodeId: 'pan-cn-series',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'CN-Series (Container Firewalls)',
          nameKo: 'CN 시리즈 (컨테이너 방화벽)',
          description: 'Kubernetes-native container NGFWs protecting east-west traffic between pods and namespaces. Deployed as a DaemonSet.',
          descriptionKo: '파드 및 네임스페이스 간 동서 트래픽을 보호하는 쿠버네티스 네이티브 컨테이너 NGFW. DaemonSet으로 배포.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/cn-series',
          infraNodeTypes: ['firewall', 'kubernetes'],
          architectureRole: 'Kubernetes Pod-to-Pod Security',
          architectureRoleKo: '쿠버네티스 파드 간 보안',
          recommendedFor: [
            'Kubernetes cluster east-west traffic inspection',
            'Container micro-segmentation',
            'DevSecOps pipeline integration',
          ],
          recommendedForKo: [
            '쿠버네티스 클러스터 동서 트래픽 검사',
            '컨테이너 마이크로 세그멘테이션',
            'DevSecOps 파이프라인 통합',
          ],
          children: [],
        },
        // ── Cloud NGFW ──
        {
          nodeId: 'pan-cloud-ngfw',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cloud NGFW',
          nameKo: '클라우드 NGFW',
          description: 'Cloud-managed NGFW-as-a-service for AWS and Azure. Palo Alto Networks manages infrastructure; customers configure policy.',
          descriptionKo: 'AWS 및 Azure용 클라우드 관리형 NGFW-as-a-Service. 인프라는 Palo Alto Networks가 관리하고 고객은 정책만 구성.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/cloud-ngfw',
          infraNodeTypes: ['firewall', 'aws-vpc'],
          architectureRole: 'Cloud-Native Managed Firewall Service',
          architectureRoleKo: '클라우드 네이티브 관리형 방화벽 서비스',
          recommendedFor: [
            'AWS VPC perimeter security without self-managing firewalls',
            'Azure VNet network security with auto-scaling',
            'Cloud-first organizations seeking FWaaS',
          ],
          recommendedForKo: [
            '방화벽 자체 관리 없이 AWS VPC 경계 보안',
            '자동 확장이 가능한 Azure VNet 네트워크 보안',
            'FWaaS를 원하는 클라우드 퍼스트 조직',
          ],
          children: [
            {
              nodeId: 'pan-cloud-ngfw-aws',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Cloud NGFW for AWS',
              nameKo: 'AWS용 클라우드 NGFW',
              description: 'NGFW-as-a-service delivered via AWS Marketplace. Auto-scaling, App-ID, Threat Prevention, URL Filtering built-in.',
              descriptionKo: 'AWS Marketplace를 통해 제공되는 NGFW-as-a-Service. 자동 확장, App-ID, 위협 차단, URL 필터링 내장.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/cloud-ngfw/aws',
              lifecycle: 'active',
              children: [],
            },
            {
              nodeId: 'pan-cloud-ngfw-azure',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Cloud NGFW for Azure',
              nameKo: 'Azure용 클라우드 NGFW',
              description: 'NGFW-as-a-service integrated with Azure vWAN and Virtual Network. ISV-native deployment.',
              descriptionKo: 'Azure vWAN 및 Virtual Network와 통합된 NGFW-as-a-Service. ISV 네이티브 배포.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall/cloud-ngfw/azure',
              lifecycle: 'active',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. SASE & SD-WAN
    // =====================================================================
    {
      nodeId: 'pan-sase',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'SASE & SD-WAN',
      nameKo: 'SASE 및 SD-WAN',
      description: 'Secure Access Service Edge and SD-WAN solutions for secure connectivity from any location',
      descriptionKo: '모든 위치에서 안전한 연결을 위한 SASE(보안 액세스 서비스 에지) 및 SD-WAN 솔루션',
      sourceUrl: 'https://www.paloaltonetworks.com/sase',
      infraNodeTypes: ['sase-gateway', 'sd-wan'],
      children: [
        // ── Prisma Access ──
        {
          nodeId: 'pan-prisma-access',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Prisma Access',
          nameKo: 'Prisma Access',
          description: 'Cloud-delivered SASE platform providing ZTNA 2.0, SWG, CASB, FWaaS, and DLP in a single service. 100+ global PoPs.',
          descriptionKo: 'ZTNA 2.0, SWG, CASB, FWaaS, DLP를 단일 서비스로 제공하는 클라우드 기반 SASE 플랫폼. 100개 이상의 글로벌 PoP.',
          sourceUrl: 'https://www.paloaltonetworks.com/sase/access',
          infraNodeTypes: ['sase-gateway'],
          architectureRole: 'Cloud SASE Edge / Zero Trust Access',
          architectureRoleKo: '클라우드 SASE 에지 / 제로 트러스트 액세스',
          recommendedFor: [
            'Remote workforce secure access (ZTNA)',
            'Branch office cloud-first connectivity',
            'SaaS application security and DLP',
            'Replacing legacy VPN with ZTNA 2.0',
          ],
          recommendedForKo: [
            '원격 근무자 보안 접속 (ZTNA)',
            '지사 클라우드 퍼스트 연결',
            'SaaS 애플리케이션 보안 및 DLP',
            '레거시 VPN을 ZTNA 2.0으로 대체',
          ],
          haFeatures: [
            '100+ global PoP redundancy',
            'Automatic failover to nearest PoP',
            'SLA-backed uptime guarantee',
          ],
          securityCapabilities: [
            'ZTNA 2.0 (Zero Trust Network Access)',
            'Secure Web Gateway (SWG)',
            'CASB (inline and API)',
            'FWaaS (Firewall as a Service)',
            'DLP (Data Loss Prevention)',
            'DNS Security',
          ],
          operationalComplexity: 'simple',
          ecosystemMaturity: 'mature',
          disasterRecovery: {
            multiRegionSupported: true,
          },
          children: [
            {
              nodeId: 'pan-prisma-access-browser',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Prisma Access Browser',
              nameKo: 'Prisma Access Browser',
              description: 'Enterprise browser with built-in SASE security. Secure access to web, SaaS, and private apps without a VPN client.',
              descriptionKo: 'SASE 보안이 내장된 엔터프라이즈 브라우저. VPN 클라이언트 없이 웹, SaaS, 프라이빗 앱에 안전하게 접속.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/access/browser',
              lifecycle: 'active',
              children: [],
            },
            {
              nodeId: 'pan-prisma-access-adem',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Autonomous DEM (ADEM)',
              nameKo: 'Autonomous DEM (ADEM)',
              description: 'AI-powered digital experience monitoring integrated with Prisma Access. End-to-end visibility from endpoint to application.',
              descriptionKo: 'Prisma Access와 통합된 AI 기반 디지털 경험 모니터링. 엔드포인트에서 애플리케이션까지 엔드투엔드 가시성.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/access/adem',
              lifecycle: 'active',
              children: [],
            },
          ],
        },
        // ── Prisma SD-WAN ──
        {
          nodeId: 'pan-prisma-sdwan',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Prisma SD-WAN',
          nameKo: 'Prisma SD-WAN',
          description: 'AI-powered next-gen SD-WAN (formerly CloudGenix) for branch office connectivity with integrated security. Application-defined policies.',
          descriptionKo: 'AI 기반 차세대 SD-WAN(구 CloudGenix). 통합 보안을 갖춘 지사 연결 솔루션. 애플리케이션 정의 정책.',
          sourceUrl: 'https://www.paloaltonetworks.com/sase/sd-wan',
          infraNodeTypes: ['sd-wan'],
          architectureRole: 'Branch SD-WAN Gateway',
          architectureRoleKo: '지사 SD-WAN 게이트웨이',
          recommendedFor: [
            'Branch office WAN optimization and resilience',
            'MPLS-to-internet migration',
            'Multi-link WAN aggregation with QoS',
          ],
          recommendedForKo: [
            '지사 WAN 최적화 및 복원력',
            'MPLS에서 인터넷으로의 마이그레이션',
            'QoS 기반 멀티 링크 WAN 집선',
          ],
          children: [
            {
              nodeId: 'pan-sdwan-ion-1200',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ION 1200',
              nameKo: 'ION 1200',
              description: 'Desktop SD-WAN appliance for small branches. Up to 500 Mbps throughput.',
              descriptionKo: '소규모 지사용 데스크탑 SD-WAN 어플라이언스. 최대 500 Mbps 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/sd-wan/ion',
              lifecycle: 'active',
              specs: {
                'WAN Throughput': '500 Mbps',
                'Interfaces': '4×GbE copper, 1×SFP',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'pan-sdwan-ion-2000',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ION 2000',
              nameKo: 'ION 2000',
              description: 'Compact SD-WAN appliance for medium branches. Up to 1 Gbps throughput.',
              descriptionKo: '중규모 지사용 컴팩트 SD-WAN 어플라이언스. 최대 1 Gbps 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/sd-wan/ion',
              lifecycle: 'active',
              specs: {
                'WAN Throughput': '1 Gbps',
                'Interfaces': '8×GbE copper, 2×SFP',
                'Form Factor': 'Desktop',
              },
              children: [],
            },
            {
              nodeId: 'pan-sdwan-ion-3200',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ION 3200',
              nameKo: 'ION 3200',
              description: 'Rackmount SD-WAN appliance for large branches and small campuses. Up to 2 Gbps throughput.',
              descriptionKo: '대규모 지사 및 소규모 캠퍼스용 랙마운트 SD-WAN 어플라이언스. 최대 2 Gbps 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/sd-wan/ion',
              lifecycle: 'active',
              specs: {
                'WAN Throughput': '2 Gbps',
                'Interfaces': '12×GbE copper, 4×SFP+',
                'Form Factor': '1RU rackmount',
              },
              children: [],
            },
            {
              nodeId: 'pan-sdwan-ion-9000',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'ION 9000',
              nameKo: 'ION 9000',
              description: 'High-performance SD-WAN appliance for data centers and large campuses. Up to 10 Gbps throughput.',
              descriptionKo: '데이터센터 및 대규모 캠퍼스용 고성능 SD-WAN 어플라이언스. 최대 10 Gbps 처리량.',
              sourceUrl: 'https://www.paloaltonetworks.com/sase/sd-wan/ion',
              lifecycle: 'active',
              specs: {
                'WAN Throughput': '10 Gbps',
                'Interfaces': '8×GbE copper, 4×SFP+, 2×SFP28',
                'Form Factor': '1RU rackmount',
              },
              children: [],
            },
          ],
        },
        // ── GlobalProtect ──
        {
          nodeId: 'pan-globalprotect',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'GlobalProtect',
          nameKo: 'GlobalProtect',
          description: 'VPN and endpoint protection solution extending NGFW policies to remote users. Available for Windows, macOS, Linux, iOS, Android.',
          descriptionKo: '원격 사용자에게 NGFW 정책을 확장하는 VPN 및 엔드포인트 보호 솔루션. Windows, macOS, Linux, iOS, Android 지원.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/globalprotect',
          infraNodeTypes: ['vpn-gateway'],
          architectureRole: 'Remote Access VPN Gateway',
          architectureRoleKo: '원격 액세스 VPN 게이트웨이',
          recommendedFor: [
            'Remote worker VPN connectivity',
            'Always-on security for roaming users',
            'Consistent NGFW policy enforcement for mobile devices',
          ],
          recommendedForKo: [
            '원격 근무자 VPN 연결',
            '로밍 사용자를 위한 상시 보안',
            '모바일 기기에 대한 일관된 NGFW 정책 적용',
          ],
          children: [],
        },
      ],
    },

    // =====================================================================
    // 3. Cloud Security
    // =====================================================================
    {
      nodeId: 'pan-cloud-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Cloud Security',
      nameKo: '클라우드 보안',
      description: 'Comprehensive cloud-native application protection platform (CNAPP) and SaaS security',
      descriptionKo: '포괄적인 클라우드 네이티브 애플리케이션 보호 플랫폼(CNAPP) 및 SaaS 보안',
      sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud',
      infraNodeTypes: ['casb', 'private-cloud'],
      children: [
        // ── Cortex Cloud ──
        {
          nodeId: 'pan-prisma-cloud',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cortex Cloud',
          nameKo: 'Cortex Cloud',
          description: 'Cloud-Native Application Protection Platform (CNAPP) providing CSPM, CWPP, CIEM, code security, and runtime protection across multi-cloud. Formerly Prisma Cloud.',
          descriptionKo: 'CSPM, CWPP, CIEM, 코드 보안, 런타임 보호를 제공하는 클라우드 네이티브 애플리케이션 보호 플랫폼(CNAPP). 멀티 클라우드 지원. 구 Prisma Cloud.',
          sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Cloud Security Posture Management / Workload Protection',
          architectureRoleKo: '클라우드 보안 태세 관리 / 워크로드 보호',
          recommendedFor: [
            'Multi-cloud security posture management (CSPM)',
            'Container and serverless workload protection (CWPP)',
            'Cloud infrastructure entitlement management (CIEM)',
            'IaC security scanning in CI/CD pipelines',
          ],
          recommendedForKo: [
            '멀티 클라우드 보안 태세 관리 (CSPM)',
            '컨테이너 및 서버리스 워크로드 보호 (CWPP)',
            '클라우드 인프라 권한 관리 (CIEM)',
            'CI/CD 파이프라인 IaC 보안 스캔',
          ],
          haFeatures: [
            'Multi-region cloud deployment',
            'Auto-scaling SaaS infrastructure',
          ],
          securityCapabilities: [
            'Cloud Security Posture Management (CSPM)',
            'Cloud Workload Protection (CWPP)',
            'Cloud Infrastructure Entitlement Management (CIEM)',
            'IaC Security Scanning',
            'Container/Serverless runtime protection',
          ],
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          disasterRecovery: {
            multiRegionSupported: true,
          },
          children: [
            {
              nodeId: 'pan-prisma-cloud-cspm',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Cloud Security Posture Management (CSPM)',
              nameKo: '클라우드 보안 태세 관리 (CSPM)',
              description: 'Continuous cloud misconfiguration detection and compliance monitoring for AWS, Azure, GCP, and OCI.',
              descriptionKo: 'AWS, Azure, GCP, OCI의 지속적 클라우드 설정 오류 탐지 및 컴플라이언스 모니터링.',
              sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud/cloud-security-posture-management',
              lifecycle: 'active',
              children: [],
            },
            {
              nodeId: 'pan-prisma-cloud-cwpp',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Cloud Workload Protection (CWPP)',
              nameKo: '클라우드 워크로드 보호 (CWPP)',
              description: 'Runtime protection for VMs, containers, and serverless functions. Vulnerability management and compliance.',
              descriptionKo: 'VM, 컨테이너, 서버리스 함수의 런타임 보호. 취약점 관리 및 컴플라이언스.',
              sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud/cloud-workload-protection',
              lifecycle: 'active',
              children: [],
            },
            {
              nodeId: 'pan-prisma-cloud-code-security',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Code Security',
              nameKo: '코드 보안',
              description: 'Shift-left security for IaC, open-source packages, and CI/CD pipelines. Integrated with Checkov, Bridgecrew.',
              descriptionKo: 'IaC, 오픈소스 패키지, CI/CD 파이프라인을 위한 시프트 레프트 보안. Checkov, Bridgecrew 통합.',
              sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud/code-security',
              lifecycle: 'active',
              children: [],
            },
            {
              nodeId: 'pan-prisma-cloud-ciem',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Cloud Infrastructure Entitlement Management (CIEM)',
              nameKo: '클라우드 인프라 권한 관리 (CIEM)',
              description: 'Identifies and remediates excessive cloud permissions across AWS, Azure, GCP.',
              descriptionKo: 'AWS, Azure, GCP 전반에 걸친 과도한 클라우드 권한 식별 및 수정.',
              sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-cloud/cloud-infrastructure-entitlement-management',
              lifecycle: 'active',
              children: [],
            },
          ],
        },
        // ── SaaS Security ──
        {
          nodeId: 'pan-saas-security',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'SaaS Security',
          nameKo: 'SaaS 보안',
          description: 'Next-gen CASB and SSPM providing inline and API-based security for SaaS applications. DLP, threat protection, compliance.',
          descriptionKo: 'SaaS 애플리케이션을 위한 인라인 및 API 기반 보안을 제공하는 차세대 CASB 및 SSPM. DLP, 위협 보호, 컴플라이언스.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/saas-security',
          infraNodeTypes: ['casb'],
          architectureRole: 'SaaS Application Security Broker',
          architectureRoleKo: 'SaaS 애플리케이션 보안 브로커',
          recommendedFor: [
            'Sanctioned and unsanctioned SaaS app visibility and control',
            'Data loss prevention for cloud applications',
            'SaaS security posture management (SSPM)',
          ],
          recommendedForKo: [
            '허가/비허가 SaaS 앱 가시성 및 제어',
            '클라우드 애플리케이션 데이터 유출 방지',
            'SaaS 보안 태세 관리 (SSPM)',
          ],
          children: [],
        },
      ],
    },

    // =====================================================================
    // 4. Security Operations
    // =====================================================================
    {
      nodeId: 'pan-secops',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Security Operations',
      nameKo: '보안 운영',
      description: 'AI-driven security operations platform for threat detection, investigation, and response',
      descriptionKo: 'AI 기반 위협 탐지, 조사, 대응을 위한 보안 운영 플랫폼',
      sourceUrl: 'https://www.paloaltonetworks.com/cortex',
      infraNodeTypes: ['siem', 'soar'],
      children: [
        // ── Cortex XDR ──
        {
          nodeId: 'pan-cortex-xdr',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cortex XDR',
          nameKo: 'Cortex XDR',
          description: 'Extended detection and response platform integrating network, endpoint, cloud, and third-party data. AI/ML-powered analytics with automated investigation.',
          descriptionKo: '네트워크, 엔드포인트, 클라우드, 서드파티 데이터를 통합하는 확장 탐지 및 대응 플랫폼. AI/ML 기반 분석 및 자동 조사.',
          sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-xdr',
          infraNodeTypes: ['siem'],
          architectureRole: 'SOC Detection & Response Hub',
          architectureRoleKo: 'SOC 탐지 및 대응 허브',
          recommendedFor: [
            'Endpoint detection and response (EDR)',
            'Cross-data-source threat correlation (XDR)',
            'Automated root cause analysis and investigation',
          ],
          recommendedForKo: [
            '엔드포인트 탐지 및 대응 (EDR)',
            '크로스 데이터 소스 위협 상관 분석 (XDR)',
            '자동 근본 원인 분석 및 조사',
          ],
          haFeatures: [
            'Cloud-hosted SaaS (always available)',
            'Multi-region data lake',
          ],
          securityCapabilities: [
            'Endpoint Detection and Response (EDR)',
            'Network Detection and Response (NDR)',
            'Cloud Detection and Response',
            'AI/ML behavioral analytics',
            'Automated root cause analysis',
          ],
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          disasterRecovery: {
            multiRegionSupported: true,
          },
          children: [],
        },
        // ── Cortex XSOAR ──
        {
          nodeId: 'pan-cortex-xsoar',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cortex XSOAR',
          nameKo: 'Cortex XSOAR',
          description: 'Security orchestration, automation, and response (SOAR) platform with 700+ integrations and automated playbooks.',
          descriptionKo: '700개 이상의 통합 및 자동화 플레이북을 갖춘 보안 오케스트레이션, 자동화 및 대응(SOAR) 플랫폼.',
          sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-xsoar',
          infraNodeTypes: ['soar'],
          architectureRole: 'SOC Automation & Orchestration',
          architectureRoleKo: 'SOC 자동화 및 오케스트레이션',
          recommendedFor: [
            'Security incident response automation',
            'SOC workflow orchestration across security tools',
            'Threat intelligence management and enrichment',
          ],
          recommendedForKo: [
            '보안 사고 대응 자동화',
            '보안 도구 전반의 SOC 워크플로우 오케스트레이션',
            '위협 인텔리전스 관리 및 강화',
          ],
          haFeatures: [
            'Cloud-hosted / On-prem HA',
            'Multi-tenant support',
          ],
          securityCapabilities: [
            'Playbook-driven incident response automation',
            '700+ third-party integrations',
            'Case management and collaboration',
            'Threat intelligence management (TIM)',
          ],
          operationalComplexity: 'moderate',
          ecosystemMaturity: 'mature',
          disasterRecovery: {
            multiRegionSupported: true,
          },
          children: [],
        },
        // ── Cortex XSIAM ──
        {
          nodeId: 'pan-cortex-xsiam',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cortex XSIAM',
          nameKo: 'Cortex XSIAM',
          description: 'AI-driven security operations platform unifying SIEM, SOAR, ASM, and XDR. Autonomous SOC with ML-based alert triage and incident resolution.',
          descriptionKo: 'SIEM, SOAR, ASM, XDR을 통합하는 AI 기반 보안 운영 플랫폼. ML 기반 알림 분류 및 인시던트 해결의 자율 SOC.',
          sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-xsiam',
          infraNodeTypes: ['siem', 'soar'],
          architectureRole: 'Unified AI-Driven SOC Platform',
          architectureRoleKo: '통합 AI 기반 SOC 플랫폼',
          recommendedFor: [
            'Autonomous SOC with AI-driven alert triage',
            'Consolidating SIEM, SOAR, and XDR into a single platform',
            'Reducing SOC analyst workload with ML automation',
          ],
          recommendedForKo: [
            'AI 기반 알림 분류를 통한 자율 SOC',
            'SIEM, SOAR, XDR을 단일 플랫폼으로 통합',
            'ML 자동화로 SOC 분석가 업무 부담 경감',
          ],
          children: [],
        },
        // ── Cortex Xpanse ──
        {
          nodeId: 'pan-cortex-xpanse',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Cortex Xpanse',
          nameKo: 'Cortex Xpanse',
          description: 'Attack surface management (ASM) platform discovering internet-facing assets and exposures. Continuous monitoring of shadow IT.',
          descriptionKo: '인터넷 노출 자산 및 취약 노출을 발견하는 공격 표면 관리(ASM) 플랫폼. 섀도우 IT 지속적 모니터링.',
          sourceUrl: 'https://www.paloaltonetworks.com/cortex/cortex-xpanse',
          infraNodeTypes: ['siem'],
          architectureRole: 'Attack Surface Discovery & Monitoring',
          architectureRoleKo: '공격 표면 탐색 및 모니터링',
          recommendedFor: [
            'External attack surface discovery and monitoring',
            'Shadow IT and unknown asset detection',
            'M&A due diligence security assessment',
          ],
          recommendedForKo: [
            '외부 공격 표면 탐색 및 모니터링',
            '섀도우 IT 및 미확인 자산 탐지',
            'M&A 실사 보안 평가',
          ],
          children: [],
        },
        // ── Unit 42 ──
        {
          nodeId: 'pan-unit42',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Unit 42 Threat Intelligence',
          nameKo: 'Unit 42 위협 인텔리전스',
          description: 'Elite threat intelligence and incident response team providing research, consulting, and managed threat hunting services.',
          descriptionKo: '연구, 컨설팅, 관리형 위협 헌팅 서비스를 제공하는 최고 수준의 위협 인텔리전스 및 인시던트 대응 팀.',
          sourceUrl: 'https://www.paloaltonetworks.com/unit42',
          infraNodeTypes: ['siem'],
          architectureRole: 'Threat Intelligence Feed & Incident Response',
          architectureRoleKo: '위협 인텔리전스 피드 및 인시던트 대응',
          recommendedFor: [
            'Advanced threat intelligence integration',
            'Incident response retainer services',
            'Proactive threat hunting and advisory',
          ],
          recommendedForKo: [
            '고급 위협 인텔리전스 통합',
            '인시던트 대응 리테이너 서비스',
            '선제적 위협 헌팅 및 자문',
          ],
          children: [],
        },
      ],
    },

    // =====================================================================
    // 5. Advanced Threat Prevention
    // =====================================================================
    {
      nodeId: 'pan-threat-prevention',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Advanced Threat Prevention',
      nameKo: '고급 위협 차단',
      description: 'Cloud-delivered security services for threat prevention, URL filtering, sandboxing, DNS security, and IoT security',
      descriptionKo: '위협 차단, URL 필터링, 샌드박싱, DNS 보안, IoT 보안을 위한 클라우드 기반 보안 서비스',
      sourceUrl: 'https://www.paloaltonetworks.com/network-security/advanced-threat-prevention',
      infraNodeTypes: ['ids-ips', 'waf'],
      children: [
        // ── Advanced Threat Prevention (ATP) ──
        {
          nodeId: 'pan-atp',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Advanced Threat Prevention',
          nameKo: '고급 위협 차단',
          description: 'Inline ML-based IPS service that detects and blocks zero-day exploits, C2 traffic, and evasive threats in real time. Cloud-delivered subscription for NGFW.',
          descriptionKo: '제로데이 익스플로잇, C2 트래픽, 회피형 위협을 실시간으로 탐지/차단하는 인라인 ML 기반 IPS 서비스. NGFW용 클라우드 기반 구독.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/advanced-threat-prevention',
          infraNodeTypes: ['ids-ips'],
          architectureRole: 'Inline Threat Prevention (IPS)',
          architectureRoleKo: '인라인 위협 차단 (IPS)',
          recommendedFor: [
            'Inline zero-day exploit prevention',
            'Command and control traffic detection',
            'Evasive and encrypted threat blocking',
          ],
          recommendedForKo: [
            '인라인 제로데이 익스플로잇 차단',
            'C2(명령제어) 트래픽 탐지',
            '회피형 및 암호화 위협 차단',
          ],
          children: [],
        },
        // ── Advanced URL Filtering ──
        {
          nodeId: 'pan-url-filtering',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Advanced URL Filtering',
          nameKo: '고급 URL 필터링',
          description: 'ML-powered web security preventing phishing, malware downloads, and credential theft. Real-time classification of new and unknown URLs.',
          descriptionKo: '피싱, 악성코드 다운로드, 자격증명 탈취를 방지하는 ML 기반 웹 보안. 신규 및 미확인 URL 실시간 분류.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/advanced-url-filtering',
          infraNodeTypes: ['waf'],
          architectureRole: 'Web Security Gateway / URL Filter',
          architectureRoleKo: '웹 보안 게이트웨이 / URL 필터',
          recommendedFor: [
            'Phishing and credential theft prevention',
            'Web content filtering and policy enforcement',
            'Real-time protection against malicious URLs',
          ],
          recommendedForKo: [
            '피싱 및 자격증명 탈취 방지',
            '웹 콘텐츠 필터링 및 정책 적용',
            '악성 URL에 대한 실시간 보호',
          ],
          children: [],
        },
        // ── WildFire ──
        {
          nodeId: 'pan-wildfire',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'WildFire',
          nameKo: 'WildFire',
          description: 'Cloud-based malware analysis and sandboxing service. Analyzes files across PE, APK, PDF, Office, and script formats in multi-technique sandbox.',
          descriptionKo: '클라우드 기반 악성코드 분석 및 샌드박싱 서비스. PE, APK, PDF, Office, 스크립트 형식의 파일을 다중 기법 샌드박스에서 분석.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/wildfire',
          infraNodeTypes: ['ids-ips'],
          architectureRole: 'Cloud Sandboxing / Malware Analysis',
          architectureRoleKo: '클라우드 샌드박싱 / 악성코드 분석',
          recommendedFor: [
            'Unknown malware detection via cloud sandboxing',
            'Zero-day threat intelligence generation',
            'File-based threat analysis for emails and web traffic',
          ],
          recommendedForKo: [
            '클라우드 샌드박싱을 통한 미확인 악성코드 탐지',
            '제로데이 위협 인텔리전스 생성',
            '이메일 및 웹 트래픽의 파일 기반 위협 분석',
          ],
          children: [],
        },
        // ── DNS Security ──
        {
          nodeId: 'pan-dns-security',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'DNS Security',
          nameKo: 'DNS 보안',
          description: 'Cloud-delivered DNS-layer protection blocking malicious domains, DNS tunneling, and newly registered domains (NRDs). ML-powered real-time analysis.',
          descriptionKo: '악성 도메인, DNS 터널링, 신규 등록 도메인(NRD)을 차단하는 클라우드 기반 DNS 계층 보호. ML 기반 실시간 분석.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/dns-security',
          infraNodeTypes: ['dns'],
          architectureRole: 'DNS Threat Protection Layer',
          architectureRoleKo: 'DNS 위협 보호 계층',
          recommendedFor: [
            'DNS-layer malicious domain blocking',
            'DNS tunneling detection and prevention',
            'DGA (domain generation algorithm) detection',
          ],
          recommendedForKo: [
            'DNS 계층 악성 도메인 차단',
            'DNS 터널링 탐지 및 차단',
            'DGA(도메인 생성 알고리즘) 탐지',
          ],
          children: [],
        },
        // ── IoT Security ──
        {
          nodeId: 'pan-iot-security',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'IoT Security',
          nameKo: 'IoT 보안',
          description: 'ML-powered IoT device discovery, profiling, risk assessment, and policy enforcement. Agentless identification of all connected devices.',
          descriptionKo: 'ML 기반 IoT 디바이스 탐지, 프로파일링, 위험 평가, 정책 적용. 에이전트 없이 모든 연결 디바이스 식별.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/iot-security',
          infraNodeTypes: ['nac'],
          architectureRole: 'IoT/OT Device Security',
          architectureRoleKo: 'IoT/OT 디바이스 보안',
          recommendedFor: [
            'IoT/OT device discovery and classification',
            'Medical device (IoMT) security in healthcare',
            'Industrial control system (ICS/SCADA) visibility',
          ],
          recommendedForKo: [
            'IoT/OT 디바이스 탐지 및 분류',
            '의료 기관 의료 장비(IoMT) 보안',
            '산업 제어 시스템(ICS/SCADA) 가시성',
          ],
          children: [],
        },
      ],
    },

    // =====================================================================
    // 6. Management
    // =====================================================================
    {
      nodeId: 'pan-management',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Management',
      nameKo: '관리',
      description: 'Centralized management and cloud-based operations platforms for Palo Alto Networks security infrastructure',
      descriptionKo: 'Palo Alto Networks 보안 인프라를 위한 중앙 관리 및 클라우드 기반 운영 플랫폼',
      sourceUrl: 'https://www.paloaltonetworks.com/network-security/panorama',
      infraNodeTypes: ['private-cloud'],
      children: [
        // ── Panorama ──
        {
          nodeId: 'pan-panorama',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Panorama',
          nameKo: 'Panorama',
          description: 'Centralized management platform for Palo Alto Networks NGFWs. Supports up to 10,000+ firewalls with template stacks, device groups, and role-based access.',
          descriptionKo: 'Palo Alto Networks NGFW를 위한 중앙 관리 플랫폼. 템플릿 스택, 디바이스 그룹, 역할 기반 접근제어로 10,000대 이상의 방화벽 관리 지원.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/panorama',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'NGFW Centralized Management',
          architectureRoleKo: 'NGFW 중앙 관리',
          recommendedFor: [
            'Multi-firewall centralized policy management',
            'Log aggregation and compliance reporting',
            'Large-scale NGFW deployment orchestration',
          ],
          recommendedForKo: [
            '다중 방화벽 중앙 정책 관리',
            '로그 집계 및 컴플라이언스 리포팅',
            '대규모 NGFW 배포 오케스트레이션',
          ],
          haFeatures: [
            'Active/Passive HA (dedicated or virtual)',
            'Panorama Interconnect for distributed management',
          ],
          securityCapabilities: [
            'Centralized policy management',
            'Log aggregation and correlation',
            'Role-based access control (RBAC)',
            'Compliance reporting',
          ],
          operationalComplexity: 'complex',
          ecosystemMaturity: 'mature',
          disasterRecovery: {
            multiRegionSupported: true,
          },
          children: [
            {
              nodeId: 'pan-panorama-m-600',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'M-600 Appliance',
              nameKo: 'M-600 어플라이언스',
              description: 'High-performance dedicated Panorama management appliance. Manages up to 10,000 firewalls with 16TB log storage.',
              descriptionKo: '고성능 전용 Panorama 관리 어플라이언스. 16TB 로그 스토리지로 최대 10,000대 방화벽 관리.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/panorama',
              lifecycle: 'active',
              specs: {
                'Managed Firewalls': 'Up to 10,000',
                'Log Storage': '16 TB (RAID 10)',
                'Form Factor': '2RU rackmount',
                'Memory': '256 GB',
              },
              children: [],
            },
            {
              nodeId: 'pan-panorama-m-300',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'M-300 Appliance',
              nameKo: 'M-300 어플라이언스',
              description: 'Mid-range dedicated Panorama management appliance. Manages up to 5,000 firewalls.',
              descriptionKo: '미드레인지 전용 Panorama 관리 어플라이언스. 최대 5,000대 방화벽 관리.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/panorama',
              lifecycle: 'active',
              specs: {
                'Managed Firewalls': 'Up to 5,000',
                'Log Storage': '8 TB (RAID 10)',
                'Form Factor': '1RU rackmount',
                'Memory': '128 GB',
              },
              children: [],
            },
            {
              nodeId: 'pan-panorama-virtual',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Panorama Virtual Appliance',
              nameKo: 'Panorama 가상 어플라이언스',
              description: 'Virtual Panorama instance deployable on VMware ESXi, KVM, Hyper-V, or public cloud. Flexible sizing.',
              descriptionKo: 'VMware ESXi, KVM, Hyper-V 또는 퍼블릭 클라우드에 배포 가능한 가상 Panorama 인스턴스. 유연한 사이징.',
              sourceUrl: 'https://www.paloaltonetworks.com/network-security/panorama',
              lifecycle: 'active',
              children: [],
            },
          ],
        },
        // ── Strata Cloud Manager ──
        {
          nodeId: 'pan-strata-cloud-manager',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Strata Cloud Manager',
          nameKo: 'Strata Cloud Manager',
          description: 'AI-powered cloud management service for unified network security operations. Single pane of glass for NGFW, SASE, and cloud security with AIOps.',
          descriptionKo: '통합 네트워크 보안 운영을 위한 AI 기반 클라우드 관리 서비스. NGFW, SASE, 클라우드 보안을 위한 AIOps 기반 단일 관리 화면.',
          sourceUrl: 'https://www.paloaltonetworks.com/network-security/strata-cloud-manager',
          infraNodeTypes: ['private-cloud'],
          architectureRole: 'Cloud-Based Unified Security Management',
          architectureRoleKo: '클라우드 기반 통합 보안 관리',
          recommendedFor: [
            'Unified management of NGFW + SASE + Cloud NGFW',
            'AIOps-driven policy optimization and health monitoring',
            'Configuration drift detection and best practice recommendations',
          ],
          recommendedForKo: [
            'NGFW + SASE + Cloud NGFW 통합 관리',
            'AIOps 기반 정책 최적화 및 상태 모니터링',
            '설정 드리프트 탐지 및 모범 사례 추천',
          ],
          children: [],
        },
      ],
    },
  ],
};

// ---------------------------------------------------------------------------
// Compute and fix stats after catalog is defined
// ---------------------------------------------------------------------------

import { computeStats } from '../queryHelpers';

const computed = computeStats(paloaltoCatalog.products);
paloaltoCatalog.stats = computed;
