/**
 * Schneider Electric (APC) -- Full Product Catalog
 *
 * Hierarchical product tree covering Uninterruptible Power Supply (UPS),
 * Power Distribution, Cooling, Racks & Enclosures, and Management & Monitoring
 * categories for data center physical infrastructure.
 *
 * Data sourced from https://www.se.com/us/en/work/products/critical-power-cooling-and-racks.jsp
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Schneider Electric Product Catalog
// ---------------------------------------------------------------------------

export const schneiderCatalog: VendorCatalog = {
  vendorId: 'schneider-electric',
  vendorName: 'Schneider Electric',
  vendorNameKo: '슈나이더 일렉트릭',
  headquarters: 'Rueil-Malmaison, France',
  website: 'https://www.se.com',
  productPageUrl: 'https://www.se.com/us/en/work/products/critical-power-cooling-and-racks.jsp',
  depthStructure: ['category', 'product-line', 'series'],
  depthStructureKo: ['카테고리', '제품 라인', '시리즈'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.se.com/us/en/work/products/critical-power-cooling-and-racks.jsp',
  stats: { totalProducts: 44, maxDepth: 2, categoriesCount: 5 },
  products: [
    // =====================================================================
    // 1. Uninterruptible Power Supply (UPS)
    // =====================================================================
    {
      nodeId: 'schneider-ups',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Uninterruptible Power Supply (UPS)',
      nameKo: '무정전 전원 장치 (UPS)',
      description: 'Single-phase and three-phase UPS systems for edge, SMB, and enterprise data center power protection',
      descriptionKo: '엣지, 중소기업, 엔터프라이즈 데이터센터 전력 보호를 위한 단상 및 3상 UPS 시스템',
      sourceUrl: 'https://www.se.com/us/en/product-category/88000-uninterruptible-power-supply-ups-/',
      infraNodeTypes: [],
      children: [
        // -- Smart-UPS (Single Phase, SMB/Edge) --
        {
          nodeId: 'schneider-smart-ups',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Smart-UPS',
          nameKo: 'Smart-UPS',
          description: 'Single-phase line-interactive and online UPS for server rooms, network closets, and edge computing environments (750VA-10kVA)',
          descriptionKo: '서버실, 네트워크 클로젯, 엣지 컴퓨팅 환경을 위한 단상 라인 인터랙티브 및 온라인 UPS (750VA-10kVA)',
          sourceUrl: 'https://www.se.com/us/en/product-category/88065-smart-ups/',
          infraNodeTypes: [],
          architectureRole: 'Edge / Server Room / Network Closet Power Protection',
          architectureRoleKo: '엣지 / 서버실 / 네트워크 클로젯 전력 보호',
          recommendedFor: [
            'Edge computing and micro data center deployments',
            'Server room and network closet UPS protection',
            'Small and medium business IT infrastructure',
            'Branch office and retail IT power backup',
            'VoIP and network equipment protection',
          ],
          recommendedForKo: [
            '엣지 컴퓨팅 및 마이크로 데이터센터 구축',
            '서버실 및 네트워크 클로젯 UPS 보호',
            '중소기업 IT 인프라',
            '지사 및 매장 IT 전력 백업',
            'VoIP 및 네트워크 장비 보호',
          ],
          haFeatures: [
            'Hot-swappable batteries',
            'Automatic bypass on overload',
            'Parallel operation (SRT models)',
            'SmartSlot network management',
          ],
          children: [
            {
              nodeId: 'schneider-smart-ups-srt',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Smart-UPS SRT',
              nameKo: 'Smart-UPS SRT',
              description: 'Online double-conversion UPS (1-10kVA) for critical edge and server room applications requiring highest power quality',
              descriptionKo: '최고 전력 품질이 필요한 중요 엣지 및 서버실 애플리케이션을 위한 온라인 이중변환 UPS (1-10kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/62108-apc-smart-ups-on-line/',
              lifecycle: 'active',
              architectureRole: 'Edge / Server Room Critical Power Protection',
              architectureRoleKo: '엣지 / 서버실 중요 전력 보호',
              recommendedFor: [
                'Critical edge computing deployments',
                'Server rooms with sensitive equipment',
                'Medical and laboratory IT environments',
                'High-density network closets',
              ],
              recommendedForKo: [
                '중요 엣지 컴퓨팅 구축',
                '민감 장비가 있는 서버실',
                '의료 및 실험실 IT 환경',
                '고밀도 네트워크 클로젯',
              ],
              specs: {
                'Capacity Range': '1-10 kVA',
                'Topology': 'Online double-conversion',
                'Form Factor': 'Rack/Tower convertible',
                'Input Voltage': '120V / 208V / 230V',
                'Output Power Factor': '0.9',
                'Transfer Time': '0 ms (no break)',
                'Battery Type': 'Sealed lead-acid',
                'Efficiency': 'Up to 95%',
                'Management': 'SmartSlot, LCD display',
                'Rack Height': '2U-6U',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-smart-ups-smt',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Smart-UPS SMT',
              nameKo: 'Smart-UPS SMT',
              description: 'Line-interactive UPS (750VA-3kVA) for cost-effective server and network equipment protection',
              descriptionKo: '비용 효율적인 서버 및 네트워크 장비 보호를 위한 라인 인터랙티브 UPS (750VA-3kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/60990-apc-smart-ups/',
              lifecycle: 'active',
              architectureRole: 'SMB / Network Closet Power Protection',
              architectureRoleKo: '중소기업 / 네트워크 클로젯 전력 보호',
              recommendedFor: [
                'Small and medium business servers',
                'Network switches and routers',
                'Point-of-sale systems',
                'VoIP and telecom equipment',
              ],
              recommendedForKo: [
                '중소기업 서버',
                '네트워크 스위치 및 라우터',
                'POS 시스템',
                'VoIP 및 통신 장비',
              ],
              specs: {
                'Capacity Range': '750VA-3 kVA',
                'Topology': 'Line-interactive',
                'Form Factor': 'Rack/Tower convertible',
                'Input Voltage': '120V / 230V',
                'Output Power Factor': '0.8',
                'Transfer Time': '< 5 ms',
                'Battery Type': 'Sealed lead-acid',
                'Efficiency': 'Up to 98%',
                'Management': 'SmartSlot, LCD display',
                'Rack Height': '2U-4U',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-smart-ups-smx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Smart-UPS SMX',
              nameKo: 'Smart-UPS SMX',
              description: 'Extended runtime line-interactive UPS (1.5-3kVA) with external battery packs for rack and tower deployments',
              descriptionKo: '랙 및 타워 구축을 위한 외부 배터리 팩 지원 확장 런타임 라인 인터랙티브 UPS (1.5-3kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/61079-apc-smart-ups-x/',
              lifecycle: 'active',
              architectureRole: 'Server Room / Wiring Closet Extended Runtime Protection',
              architectureRoleKo: '서버실 / 배선실 확장 런타임 보호',
              recommendedFor: [
                'Server rooms requiring extended runtime',
                'Wiring closets and distribution frames',
                'Medical device power protection',
                'Industrial control systems',
              ],
              recommendedForKo: [
                '확장 런타임이 필요한 서버실',
                '배선실 및 배선반',
                '의료 기기 전력 보호',
                '산업 제어 시스템',
              ],
              specs: {
                'Capacity Range': '1.5-3 kVA',
                'Topology': 'Line-interactive',
                'Form Factor': 'Rack/Tower convertible',
                'Input Voltage': '120V / 208V / 230V',
                'Output Power Factor': '0.9',
                'Transfer Time': '< 5 ms',
                'Battery Type': 'Sealed lead-acid (external battery packs)',
                'Efficiency': 'Up to 97%',
                'Management': 'SmartSlot, LCD display',
                'Rack Height': '2U',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },

        // -- Galaxy (3-Phase Enterprise) --
        {
          nodeId: 'schneider-galaxy',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Galaxy',
          nameKo: 'Galaxy',
          description: 'Three-phase UPS systems for medium to large enterprise data centers with high efficiency, scalability, and redundancy (10-1500kVA)',
          descriptionKo: '고효율, 확장성, 이중화를 갖춘 중대형 엔터프라이즈 데이터센터용 3상 UPS 시스템 (10-1500kVA)',
          sourceUrl: 'https://www.se.com/us/en/product-category/88070-3-phase-ups/',
          infraNodeTypes: [],
          architectureRole: 'Enterprise Data Center / Critical Facility 3-Phase Power Protection',
          architectureRoleKo: '엔터프라이즈 데이터센터 / 중요 시설 3상 전력 보호',
          recommendedFor: [
            'Enterprise and colocation data centers',
            'Hospital and healthcare facility critical power',
            'Financial trading floor infrastructure',
            'Industrial manufacturing critical processes',
            'Government and military data centers',
          ],
          recommendedForKo: [
            '엔터프라이즈 및 코로케이션 데이터센터',
            '병원 및 의료 시설 중요 전력',
            '금융 트레이딩 플로어 인프라',
            '산업 제조 핵심 프로세스',
            '정부 및 군사 데이터센터',
          ],
          haFeatures: [
            'N+1 / 2N / 2(N+1) redundancy configurations',
            'Hot-swappable power modules',
            'Parallel operation (up to 6 units)',
            'Static bypass and maintenance bypass',
            'ECOnversion mode for 99% efficiency',
          ],
          children: [
            {
              nodeId: 'schneider-galaxy-vs',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Galaxy VS',
              nameKo: 'Galaxy VS',
              description: 'Compact 3-phase UPS (10-150kVA) with high efficiency for small to medium data centers and edge computing',
              descriptionKo: '중소형 데이터센터 및 엣지 컴퓨팅을 위한 고효율 컴팩트 3상 UPS (10-150kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/62234-galaxy-vs/',
              lifecycle: 'active',
              architectureRole: 'Small/Medium Data Center 3-Phase Power',
              architectureRoleKo: '중소형 데이터센터 3상 전력',
              recommendedFor: [
                'Small to medium enterprise data centers',
                'Edge computing and micro data centers',
                'Light industrial and commercial facilities',
                'Healthcare IT infrastructure',
              ],
              recommendedForKo: [
                '중소 엔터프라이즈 데이터센터',
                '엣지 컴퓨팅 및 마이크로 데이터센터',
                '경공업 및 상업 시설',
                '의료 IT 인프라',
              ],
              specs: {
                'Capacity Range': '10-150 kVA',
                'Topology': 'Online double-conversion',
                'Phase': '3-phase',
                'Efficiency': 'Up to 99% (ECO mode)',
                'Footprint': 'Compact — 0.58 m2',
                'Battery Options': 'VRLA / Li-ion',
                'Parallel Capability': 'Up to 4 units',
                'Management': 'EcoStruxure IT compatible',
                'Operating Temperature': '0-40 C',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-galaxy-vx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Galaxy VX',
              nameKo: 'Galaxy VX',
              description: 'Large 3-phase UPS (500-1500kVA) for Tier III/IV data centers with modular architecture and 99% efficiency',
              descriptionKo: '모듈식 아키텍처와 99% 효율의 Tier III/IV 데이터센터용 대형 3상 UPS (500-1500kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/62479-galaxy-vx/',
              lifecycle: 'active',
              architectureRole: 'Large Enterprise / Colocation Data Center Power',
              architectureRoleKo: '대형 엔터프라이즈 / 코로케이션 데이터센터 전력',
              recommendedFor: [
                'Tier III/IV data centers',
                'Colocation and wholesale data centers',
                'Large enterprise campus data centers',
                'Hyperscale edge deployments',
              ],
              recommendedForKo: [
                'Tier III/IV 데이터센터',
                '코로케이션 및 도매 데이터센터',
                '대형 엔터프라이즈 캠퍼스 데이터센터',
                '하이퍼스케일 엣지 구축',
              ],
              specs: {
                'Capacity Range': '500-1500 kVA',
                'Topology': 'Online double-conversion',
                'Phase': '3-phase',
                'Efficiency': 'Up to 99% (ECOnversion mode)',
                'Modular Design': '100 kVA / 200 kVA modules',
                'Parallel Capability': 'Up to 6 units',
                'Battery Options': 'VRLA / Li-ion / Flywheel',
                'Footprint': 'From 1.0 m2',
                'Management': 'EcoStruxure IT compatible',
                'Operating Temperature': '0-40 C',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-galaxy-vxl',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Galaxy VXL',
              nameKo: 'Galaxy VXL',
              description: 'Lithium-ion 3-phase UPS (500-1250kVA) with 99% efficiency, 50% smaller footprint, and 3x battery lifespan',
              descriptionKo: '99% 효율, 50% 작은 설치면적, 3배 배터리 수명의 리튬이온 3상 UPS (500-1250kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/65584-galaxy-vl/',
              lifecycle: 'active',
              architectureRole: 'Large Data Center Li-ion Power Protection',
              architectureRoleKo: '대형 데이터센터 리튬이온 전력 보호',
              recommendedFor: [
                'Space-constrained data centers',
                'Sustainability-focused green data centers',
                'Colocation facilities with density requirements',
                'Financial and telecom critical facilities',
              ],
              recommendedForKo: [
                '공간 제약이 있는 데이터센터',
                '지속가능성 중심 친환경 데이터센터',
                '밀도 요구가 있는 코로케이션 시설',
                '금융 및 통신 핵심 시설',
              ],
              specs: {
                'Capacity Range': '500-1250 kVA',
                'Topology': 'Online double-conversion',
                'Phase': '3-phase',
                'Efficiency': 'Up to 99% (ECOnversion mode)',
                'Battery Type': 'Lithium-ion',
                'Battery Lifespan': '15+ years (3x VRLA)',
                'Footprint Reduction': '50% vs VRLA equivalent',
                'Parallel Capability': 'Up to 6 units',
                'Management': 'EcoStruxure IT compatible',
                'Operating Temperature': '0-40 C',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-galaxy-vm',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Galaxy VM',
              nameKo: 'Galaxy VM',
              description: 'Medium 3-phase UPS (160-225kVA) for medium data centers and critical facility applications',
              descriptionKo: '중형 데이터센터 및 중요 시설 애플리케이션을 위한 3상 UPS (160-225kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/61617-galaxy-vm/',
              lifecycle: 'active',
              architectureRole: 'Medium Data Center / Critical Facility Power',
              architectureRoleKo: '중형 데이터센터 / 중요 시설 전력',
              recommendedFor: [
                'Medium enterprise data centers',
                'Hospital and healthcare critical power',
                'University and research facility IT',
                'Regional government data centers',
              ],
              recommendedForKo: [
                '중형 엔터프라이즈 데이터센터',
                '병원 및 의료 중요 전력',
                '대학 및 연구 시설 IT',
                '지방 정부 데이터센터',
              ],
              specs: {
                'Capacity Range': '160-225 kVA',
                'Topology': 'Online double-conversion',
                'Phase': '3-phase',
                'Efficiency': 'Up to 99% (ECO mode)',
                'Parallel Capability': 'Up to 4 units',
                'Battery Options': 'VRLA / Li-ion',
                'Management': 'EcoStruxure IT compatible',
                'Operating Temperature': '0-40 C',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },

        // -- Symmetra (Modular Redundant) --
        {
          nodeId: 'schneider-symmetra',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Symmetra',
          nameKo: 'Symmetra',
          description: 'Scalable modular UPS architecture with N+1 redundancy for mission-critical data center applications (16-500kVA)',
          descriptionKo: '미션 크리티컬 데이터센터 애플리케이션을 위한 N+1 이중화 확장형 모듈식 UPS 아키텍처 (16-500kVA)',
          sourceUrl: 'https://www.se.com/us/en/product-category/88075-symmetra/',
          infraNodeTypes: [],
          architectureRole: 'Mission-Critical Data Center Modular Power',
          architectureRoleKo: '미션 크리티컬 데이터센터 모듈식 전력',
          recommendedFor: [
            'Mission-critical enterprise data centers',
            'Scalable pay-as-you-grow power deployments',
            'Facilities requiring N+1 internal redundancy',
            'Tier III/IV data center power architecture',
          ],
          recommendedForKo: [
            '미션 크리티컬 엔터프라이즈 데이터센터',
            '확장형 성장에 따른 투자 전력 구축',
            'N+1 내부 이중화가 필요한 시설',
            'Tier III/IV 데이터센터 전력 아키텍처',
          ],
          haFeatures: [
            'N+1 internal modular redundancy',
            'Hot-swappable power and battery modules',
            'Integrated static bypass',
            'Maintenance bypass',
            'Scalable power-on-demand',
          ],
          children: [
            {
              nodeId: 'schneider-symmetra-px',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Symmetra PX',
              nameKo: 'Symmetra PX',
              description: 'Scalable modular UPS (16-500kVA) with internal N+1 redundancy and pay-as-you-grow architecture',
              descriptionKo: '내부 N+1 이중화와 성장에 따른 투자 아키텍처를 갖춘 확장형 모듈식 UPS (16-500kVA)',
              sourceUrl: 'https://www.se.com/us/en/product-range/844-symmetra-px/',
              lifecycle: 'active',
              architectureRole: 'Mission-Critical Modular Power Infrastructure',
              architectureRoleKo: '미션 크리티컬 모듈식 전력 인프라',
              recommendedFor: [
                'Enterprise data centers with phased growth',
                'Facilities needing built-in redundancy without parallel units',
                'Mission-critical applications requiring 99.999% uptime',
                'Data centers with variable power demand',
              ],
              recommendedForKo: [
                '단계적 성장을 하는 엔터프라이즈 데이터센터',
                '병렬 장치 없이 내장 이중화가 필요한 시설',
                '99.999% 가동률이 필요한 미션 크리티컬 애플리케이션',
                '가변적 전력 수요가 있는 데이터센터',
              ],
              specs: {
                'Capacity Range': '16-500 kVA',
                'Topology': 'Online double-conversion (modular)',
                'Phase': '3-phase',
                'Module Size': '16 kVA power modules',
                'Redundancy': 'N+1 internal redundancy',
                'Efficiency': 'Up to 96%',
                'Scalability': 'Add modules as demand grows',
                'Battery': 'Hot-swappable battery modules',
                'Management': 'EcoStruxure IT compatible',
              },
              formFactor: 'chassis',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Power Distribution
    // =====================================================================
    {
      nodeId: 'schneider-power-distribution',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Power Distribution',
      nameKo: '전력 분배',
      description: 'Rack-level and facility-level power distribution units for data center and IT equipment power delivery',
      descriptionKo: '데이터센터 및 IT 장비 전력 공급을 위한 랙 레벨 및 시설 레벨 전력 분배 장치',
      sourceUrl: 'https://www.se.com/us/en/product-category/88105-power-distribution/',
      infraNodeTypes: [],
      children: [
        // -- Rack PDU --
        {
          nodeId: 'schneider-rack-pdu',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Rack PDU',
          nameKo: 'Rack PDU',
          description: 'Rack-mounted power distribution units with basic, metered, and switched variants for granular per-outlet power management',
          descriptionKo: '세밀한 콘센트별 전력 관리를 위한 기본형, 미터링형, 스위칭형 랙 장착 전력 분배 장치',
          sourceUrl: 'https://www.se.com/us/en/product-category/88110-rack-power-distribution/',
          infraNodeTypes: [],
          architectureRole: 'Rack-Level Power Distribution',
          architectureRoleKo: '랙 레벨 전력 분배',
          recommendedFor: [
            'Data center rack power delivery and management',
            'Server room per-outlet monitoring',
            'Remote outlet switching for power cycling',
            'PUE optimization and energy auditing',
            'Colocation tenant power metering',
          ],
          recommendedForKo: [
            '데이터센터 랙 전력 공급 및 관리',
            '서버실 콘센트별 모니터링',
            '원격 콘센트 스위칭으로 전원 사이클링',
            'PUE 최적화 및 에너지 감사',
            '코로케이션 테넌트 전력 미터링',
          ],
          haFeatures: [
            'Dual-feed (A+B) rack PDU configurations',
            'Hot-swappable modules',
            'SNMP/HTTP remote monitoring',
          ],
          children: [
            {
              nodeId: 'schneider-basic-rack-pdu',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Basic Rack PDU',
              nameKo: 'Basic Rack PDU',
              description: 'Cost-effective rack PDU providing reliable power distribution without metering or switching capabilities',
              descriptionKo: '미터링이나 스위칭 기능 없이 안정적인 전력 분배를 제공하는 비용 효율적 랙 PDU',
              sourceUrl: 'https://www.se.com/us/en/product-range/7536-rack-pdu-basic/',
              lifecycle: 'active',
              architectureRole: 'Basic Rack Power Distribution',
              architectureRoleKo: '기본 랙 전력 분배',
              recommendedFor: [
                'Low-cost rack power distribution',
                'Non-critical IT environments',
                'Lab and development environments',
              ],
              recommendedForKo: [
                '저비용 랙 전력 분배',
                '비핵심 IT 환경',
                '실험실 및 개발 환경',
              ],
              specs: {
                'Type': 'Basic (no metering)',
                'Input': 'Single-feed',
                'Outlets': '10-42 outlets (model dependent)',
                'Mounting': '0U vertical / 1U horizontal',
                'Input Voltage': '120V / 208V / 230V',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-metered-rack-pdu',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Metered Rack PDU',
              nameKo: 'Metered Rack PDU',
              description: 'Rack PDU with real-time current, voltage, and power metering for capacity planning and energy management',
              descriptionKo: '용량 계획 및 에너지 관리를 위한 실시간 전류, 전압, 전력 미터링 랙 PDU',
              sourceUrl: 'https://www.se.com/us/en/product-range/7534-rack-pdu-metered/',
              lifecycle: 'active',
              architectureRole: 'Monitored Rack Power Distribution',
              architectureRoleKo: '모니터링 랙 전력 분배',
              recommendedFor: [
                'Data center capacity planning',
                'Energy efficiency monitoring',
                'Colocation power billing',
                'PUE measurement and optimization',
              ],
              recommendedForKo: [
                '데이터센터 용량 계획',
                '에너지 효율 모니터링',
                '코로케이션 전력 과금',
                'PUE 측정 및 최적화',
              ],
              specs: {
                'Type': 'Metered (aggregate metering)',
                'Metering': 'Current (A), Voltage (V), Power (kW), Energy (kWh)',
                'Outlets': '10-42 outlets (model dependent)',
                'Mounting': '0U vertical / 1U horizontal',
                'Management': 'SNMP v3, HTTP/HTTPS, SSH',
                'Input Voltage': '120V / 208V / 230V',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-switched-rack-pdu',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Switched Rack PDU',
              nameKo: 'Switched Rack PDU',
              description: 'Rack PDU with per-outlet remote on/off switching and metering for maximum power control flexibility',
              descriptionKo: '최대 전력 제어 유연성을 위한 콘센트별 원격 온/오프 스위칭 및 미터링 랙 PDU',
              sourceUrl: 'https://www.se.com/us/en/product-range/7535-rack-pdu-switched/',
              lifecycle: 'active',
              architectureRole: 'Managed Rack Power Distribution',
              architectureRoleKo: '관리형 랙 전력 분배',
              recommendedFor: [
                'Remote power cycling of unresponsive equipment',
                'Controlled power sequencing during rack deployment',
                'Colocation facilities with tenant power management',
                'Lab environments needing remote reboot capability',
              ],
              recommendedForKo: [
                '응답 없는 장비의 원격 전원 사이클링',
                '랙 배포 중 제어된 전원 순서 지정',
                '테넌트 전력 관리가 필요한 코로케이션 시설',
                '원격 재부팅 기능이 필요한 실험실 환경',
              ],
              specs: {
                'Type': 'Switched (per-outlet on/off)',
                'Switching': 'Per-outlet remote on/off/reboot',
                'Metering': 'Current (A), Voltage (V), Power (kW)',
                'Outlets': '8-24 switched outlets',
                'Mounting': '0U vertical / 1U horizontal',
                'Management': 'SNMP v3, HTTP/HTTPS, SSH, Telnet',
                'Input Voltage': '120V / 208V / 230V',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-metered-by-outlet-rack-pdu',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Metered-by-Outlet Rack PDU',
              nameKo: 'Metered-by-Outlet Rack PDU',
              description: 'Premium rack PDU with individual per-outlet power metering for precise per-device energy tracking and chargeback',
              descriptionKo: '정밀한 장치별 에너지 추적 및 차지백을 위한 개별 콘센트별 전력 미터링 프리미엄 랙 PDU',
              sourceUrl: 'https://www.se.com/us/en/product-range/62842-rack-pdu-metered-by-outlet-with-switching/',
              lifecycle: 'active',
              architectureRole: 'Per-Device Power Metering and Distribution',
              architectureRoleKo: '장치별 전력 미터링 및 분배',
              recommendedFor: [
                'Colocation per-device power billing',
                'Precision capacity management',
                'Per-server power profiling',
                'Data center energy optimization programs',
              ],
              recommendedForKo: [
                '코로케이션 장치별 전력 과금',
                '정밀 용량 관리',
                '서버별 전력 프로파일링',
                '데이터센터 에너지 최적화 프로그램',
              ],
              specs: {
                'Type': 'Metered-by-Outlet',
                'Metering': 'Per-outlet current (A), voltage (V), power (kW), energy (kWh)',
                'Outlets': '18-42 metered outlets',
                'Mounting': '0U vertical',
                'Management': 'SNMP v3, HTTP/HTTPS, SSH',
                'Input Voltage': '120V / 208V / 230V',
                'Accuracy': '+/- 1% billing grade',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },

        // -- Busway --
        {
          nodeId: 'schneider-busway',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Busway',
          nameKo: 'Busway',
          description: 'Overhead busway systems for flexible and efficient power distribution in data center and industrial environments',
          descriptionKo: '데이터센터 및 산업 환경에서 유연하고 효율적인 전력 분배를 위한 오버헤드 버스웨이 시스템',
          sourceUrl: 'https://www.se.com/us/en/product-category/88200-busway/',
          infraNodeTypes: [],
          architectureRole: 'Facility-Level Overhead Power Distribution',
          architectureRoleKo: '시설 레벨 오버헤드 전력 분배',
          recommendedFor: [
            'Large data center overhead power distribution',
            'Flexible power tap-off for rack rows',
            'Facilities requiring rapid reconfigurations',
          ],
          recommendedForKo: [
            '대형 데이터센터 오버헤드 전력 분배',
            '랙 열을 위한 유연한 전력 탭오프',
            '빠른 재구성이 필요한 시설',
          ],
          children: [
            {
              nodeId: 'schneider-canalis',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Canalis Busway',
              nameKo: 'Canalis 버스웨이',
              description: 'Overhead busway system for flexible, tool-free power tap-off distribution across data center rows',
              descriptionKo: '데이터센터 열 전체에 유연한 무공구 전력 탭오프 분배를 위한 오버헤드 버스웨이 시스템',
              sourceUrl: 'https://www.se.com/us/en/product-range/62584-canalis/',
              lifecycle: 'active',
              architectureRole: 'Data Center Overhead Power Bus',
              architectureRoleKo: '데이터센터 오버헤드 전력 버스',
              recommendedFor: [
                'New data center builds with overhead power',
                'Facilities needing rapid row reconfiguration',
                'High-density rack deployments',
              ],
              recommendedForKo: [
                '오버헤드 전력이 있는 신규 데이터센터 구축',
                '빠른 열 재구성이 필요한 시설',
                '고밀도 랙 구축',
              ],
              specs: {
                'Rating': '40-5000 A',
                'Installation': 'Overhead ceiling mount',
                'Tap-Off': 'Tool-free plug-in tap-off boxes',
                'Protection': 'IP55 rated',
                'Standards': 'IEC 61439-6, UL 857',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. Cooling
    // =====================================================================
    {
      nodeId: 'schneider-cooling',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Cooling',
      nameKo: '냉각',
      description: 'Row-based, room-based, and liquid cooling solutions for data center thermal management',
      descriptionKo: '데이터센터 열 관리를 위한 열 기반, 실 기반, 액체 냉각 솔루션',
      sourceUrl: 'https://www.se.com/us/en/product-category/88300-cooling/',
      infraNodeTypes: [],
      children: [
        // -- InRow Cooling --
        {
          nodeId: 'schneider-inrow',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'InRow Cooling',
          nameKo: 'InRow 냉각',
          description: 'Row-based precision cooling units deployed between racks for close-coupled, high-efficiency thermal management',
          descriptionKo: '랙 사이에 배치하는 근접 결합 고효율 열 관리를 위한 열 기반 정밀 냉각 유닛',
          sourceUrl: 'https://www.se.com/us/en/product-category/88305-inrow-cooling/',
          infraNodeTypes: [],
          architectureRole: 'Row-Based Data Center Cooling',
          architectureRoleKo: '열 기반 데이터센터 냉각',
          recommendedFor: [
            'High-density rack cooling (10-30kW per rack)',
            'Hot/cold aisle containment configurations',
            'Data center retrofits and capacity expansion',
            'Edge and micro data center thermal management',
            'Colocation mixed-density environments',
          ],
          recommendedForKo: [
            '고밀도 랙 냉각 (랙당 10-30kW)',
            '핫/콜드 아일 격리 구성',
            '데이터센터 개조 및 용량 확장',
            '엣지 및 마이크로 데이터센터 열 관리',
            '코로케이션 혼합 밀도 환경',
          ],
          haFeatures: [
            'N+1 cooling redundancy configurations',
            'Variable speed fans for efficiency',
            'EcoStruxure IT monitoring integration',
          ],
          children: [
            {
              nodeId: 'schneider-inrow-rc',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'InRow RC',
              nameKo: 'InRow RC',
              description: 'Chilled water row-based cooling unit (5-13kW) for moderate density racks with existing chilled water infrastructure',
              descriptionKo: '기존 냉수 인프라가 있는 중밀도 랙을 위한 냉수 열 기반 냉각 유닛 (5-13kW)',
              sourceUrl: 'https://www.se.com/us/en/product-range/2855-inrow-rc/',
              lifecycle: 'active',
              architectureRole: 'Row-Based Chilled Water Cooling',
              architectureRoleKo: '열 기반 냉수 냉각',
              recommendedFor: [
                'Data centers with existing chilled water plants',
                'Moderate density rack environments',
                'Energy-efficient cooling deployments',
              ],
              recommendedForKo: [
                '기존 냉수 플랜트가 있는 데이터센터',
                '중밀도 랙 환경',
                '에너지 효율적인 냉각 구축',
              ],
              specs: {
                'Cooling Capacity': '5-13 kW',
                'Cooling Medium': 'Chilled water',
                'Airflow': 'Close-coupled, horizontal',
                'Form Factor': 'In-row (between racks)',
                'Rack Compatibility': '600mm row width',
                'Fan Type': 'Variable speed EC fans',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-inrow-rd',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'InRow RD',
              nameKo: 'InRow RD',
              description: 'Direct expansion row-based cooling unit (25-47kW) for high-density rack environments without chilled water',
              descriptionKo: '냉수 없이 고밀도 랙 환경을 위한 직접 팽창 열 기반 냉각 유닛 (25-47kW)',
              sourceUrl: 'https://www.se.com/us/en/product-range/2861-inrow-rd/',
              lifecycle: 'active',
              architectureRole: 'Row-Based Direct Expansion Cooling',
              architectureRoleKo: '열 기반 직접 팽창 냉각',
              recommendedFor: [
                'High-density rack environments (15-30kW/rack)',
                'Sites without chilled water infrastructure',
                'Rapid deployment cooling solutions',
                'Edge computing thermal management',
              ],
              recommendedForKo: [
                '고밀도 랙 환경 (15-30kW/랙)',
                '냉수 인프라가 없는 사이트',
                '빠른 구축 냉각 솔루션',
                '엣지 컴퓨팅 열 관리',
              ],
              specs: {
                'Cooling Capacity': '25-47 kW',
                'Cooling Medium': 'Direct expansion (DX)',
                'Airflow': 'Close-coupled, horizontal',
                'Form Factor': 'In-row (between racks)',
                'Rack Compatibility': '600mm row width',
                'Fan Type': 'Variable speed EC fans',
                'Refrigerant': 'R410A',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-inrow-dx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'InRow DX',
              nameKo: 'InRow DX',
              description: 'Self-contained air-cooled in-row cooling unit (30-50kW) for high-density environments with integrated compressor',
              descriptionKo: '통합 컴프레서를 갖춘 고밀도 환경을 위한 자체 포함 공랭식 인라인 냉각 유닛 (30-50kW)',
              sourceUrl: 'https://www.se.com/us/en/product-range/2849-inrow-dx/',
              lifecycle: 'active',
              architectureRole: 'Self-Contained Row-Based Cooling',
              architectureRoleKo: '자체 포함 열 기반 냉각',
              recommendedFor: [
                'Standalone high-density cooling without external plant',
                'Data center expansions and retrofits',
                'Edge deployments needing self-contained cooling',
              ],
              recommendedForKo: [
                '외부 플랜트 없이 독립형 고밀도 냉각',
                '데이터센터 확장 및 개조',
                '자체 포함 냉각이 필요한 엣지 구축',
              ],
              specs: {
                'Cooling Capacity': '30-50 kW',
                'Cooling Medium': 'Air-cooled DX (self-contained)',
                'Airflow': 'Close-coupled, horizontal',
                'Form Factor': 'In-row (between racks)',
                'Compressor': 'Integrated scroll compressor',
                'Fan Type': 'Variable speed EC fans',
                'Refrigerant': 'R410A',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },

        // -- Uniflair (Room Cooling) --
        {
          nodeId: 'schneider-uniflair',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Uniflair',
          nameKo: 'Uniflair',
          description: 'Room-based precision air conditioning systems for large data halls and mission-critical environments',
          descriptionKo: '대형 데이터홀 및 미션 크리티컬 환경을 위한 실 기반 정밀 공조 시스템',
          sourceUrl: 'https://www.se.com/us/en/product-category/88310-room-cooling/',
          infraNodeTypes: [],
          architectureRole: 'Room-Based Data Center Cooling',
          architectureRoleKo: '실 기반 데이터센터 냉각',
          recommendedFor: [
            'Large data hall perimeter cooling',
            'Legacy data center floor cooling',
            'Raised floor underfloor air delivery',
            'Mission-critical room-level thermal control',
          ],
          recommendedForKo: [
            '대형 데이터홀 경계 냉각',
            '레거시 데이터센터 바닥 냉각',
            '이중 바닥 하부 공기 공급',
            '미션 크리티컬 실 레벨 열 제어',
          ],
          haFeatures: [
            'N+1 unit redundancy',
            'Intelligent group control',
            'Hot standby operation',
          ],
          children: [
            {
              nodeId: 'schneider-uniflair-le',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Uniflair LE',
              nameKo: 'Uniflair LE',
              description: 'Large room precision air conditioning (12-174kW) with chilled water or direct expansion for raised floor data centers',
              descriptionKo: '이중 바닥 데이터센터를 위한 냉수 또는 직접 팽창 방식의 대형 실 정밀 공조 (12-174kW)',
              sourceUrl: 'https://www.se.com/us/en/product-range/62397-uniflair-le/',
              lifecycle: 'active',
              architectureRole: 'Large Data Hall Room Cooling',
              architectureRoleKo: '대형 데이터홀 실 냉각',
              recommendedFor: [
                'Large enterprise data halls',
                'Raised floor cooling configurations',
                'Legacy data center modernization',
              ],
              recommendedForKo: [
                '대형 엔터프라이즈 데이터홀',
                '이중 바닥 냉각 구성',
                '레거시 데이터센터 현대화',
              ],
              specs: {
                'Cooling Capacity': '12-174 kW',
                'Cooling Medium': 'Chilled water / DX',
                'Airflow': 'Downflow (raised floor) / Upflow',
                'Form Factor': 'Floor-standing perimeter unit',
                'Fan Type': 'EC variable speed fans',
                'Humidification': 'Optional electrode humidifier',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-uniflair-tdcv',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Uniflair TDCV',
              nameKo: 'Uniflair TDCV',
              description: 'Close-coupled direct expansion cooling system designed for targeted high-density hot spot management',
              descriptionKo: '목표 지향적 고밀도 핫스팟 관리를 위해 설계된 근접 결합 직접 팽창 냉각 시스템',
              sourceUrl: 'https://www.se.com/us/en/product-range/62399-uniflair-tdcv/',
              lifecycle: 'active',
              architectureRole: 'Close-Coupled Hot Spot Cooling',
              architectureRoleKo: '근접 결합 핫스팟 냉각',
              recommendedFor: [
                'High-density hot spot supplemental cooling',
                'Targeted rack-level thermal relief',
                'Ceiling-mounted overhead cooling',
              ],
              recommendedForKo: [
                '고밀도 핫스팟 보충 냉각',
                '목표 지향적 랙 레벨 열 완화',
                '천장 장착 오버헤드 냉각',
              ],
              specs: {
                'Cooling Medium': 'Direct expansion (DX)',
                'Deployment': 'Close-coupled / ceiling-mounted',
                'Airflow': 'Overhead targeted supply',
                'Fan Type': 'EC variable speed fans',
                'Application': 'Supplemental / hot spot cooling',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },

        // -- Liquid Cooling --
        {
          nodeId: 'schneider-liquid-cooling',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Liquid Cooling',
          nameKo: '액체 냉각',
          description: 'Advanced liquid cooling solutions including direct-to-chip and rear door heat exchangers for ultra-high-density computing',
          descriptionKo: '초고밀도 컴퓨팅을 위한 직접칩 냉각 및 후면 도어 열 교환기를 포함한 첨단 액체 냉각 솔루션',
          sourceUrl: 'https://www.se.com/us/en/product-category/88315-liquid-cooling/',
          infraNodeTypes: [],
          architectureRole: 'High-Density Liquid Cooling Infrastructure',
          architectureRoleKo: '고밀도 액체 냉각 인프라',
          recommendedFor: [
            'GPU/AI compute clusters with 30+ kW per rack',
            'High-performance computing (HPC) data centers',
            'Data centers transitioning to liquid cooling',
            'Sustainability-focused cooling upgrades',
          ],
          recommendedForKo: [
            '랙당 30kW 이상의 GPU/AI 컴퓨팅 클러스터',
            '고성능 컴퓨팅 (HPC) 데이터센터',
            '액체 냉각으로 전환하는 데이터센터',
            '지속가능성 중심 냉각 업그레이드',
          ],
          haFeatures: [
            'Redundant coolant pumps',
            'Leak detection sensors',
            'Coolant distribution unit (CDU) redundancy',
          ],
          children: [
            {
              nodeId: 'schneider-ecostruxure-liquid-cooling',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'EcoStruxure Liquid Cooling',
              nameKo: 'EcoStruxure 액체 냉각',
              description: 'Direct-to-chip liquid cooling system with coolant distribution unit (CDU) for GPU/AI server cooling at 100+ kW per rack',
              descriptionKo: '랙당 100kW 이상의 GPU/AI 서버 냉각을 위한 냉매 분배 장치 (CDU) 포함 직접칩 액체 냉각 시스템',
              sourceUrl: 'https://www.se.com/us/en/product-range/65678-ecostruxure-liquid-cooling/',
              lifecycle: 'active',
              architectureRole: 'Direct-to-Chip AI/HPC Cooling',
              architectureRoleKo: '직접칩 AI/HPC 냉각',
              recommendedFor: [
                'AI/ML training clusters (NVIDIA DGX/HGX)',
                'HPC and supercomputing environments',
                'Data centers with 50-100+ kW per rack',
              ],
              recommendedForKo: [
                'AI/ML 학습 클러스터 (NVIDIA DGX/HGX)',
                'HPC 및 슈퍼컴퓨팅 환경',
                '랙당 50-100kW 이상의 데이터센터',
              ],
              specs: {
                'Cooling Method': 'Direct-to-chip liquid cooling',
                'Capacity': '100+ kW per rack',
                'CDU Capacity': 'Up to 350 kW per CDU',
                'Coolant': 'Warm water (25-45 C)',
                'PUE Impact': '< 1.1 PUE contribution',
                'Monitoring': 'EcoStruxure IT integrated',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-rear-door-hx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'Rear Door Heat Exchangers',
              nameKo: '후면 도어 열 교환기',
              description: 'Passive and active rear-door heat exchangers that replace standard rack doors to capture exhaust heat at the source',
              descriptionKo: '배기열을 소스에서 포착하기 위해 표준 랙 도어를 대체하는 수동 및 능동 후면 도어 열 교환기',
              sourceUrl: 'https://www.se.com/us/en/product-range/62585-netshelter-rear-door-heat-exchangers/',
              lifecycle: 'active',
              architectureRole: 'Rack-Level Passive/Active Cooling',
              architectureRoleKo: '랙 레벨 수동/능동 냉각',
              recommendedFor: [
                'Retrofit cooling for existing high-density racks',
                'Supplemental cooling for 10-30 kW racks',
                'Data centers without hot aisle containment',
              ],
              recommendedForKo: [
                '기존 고밀도 랙의 개조 냉각',
                '10-30kW 랙의 보충 냉각',
                '핫 아일 격리가 없는 데이터센터',
              ],
              specs: {
                'Cooling Capacity': 'Up to 32 kW per rack',
                'Type': 'Passive (chilled water) / Active (fans)',
                'Coolant': 'Chilled water',
                'Installation': 'Replaces standard rear rack door',
                'Compatibility': 'NetShelter SX 42U/48U racks',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Racks & Enclosures
    // =====================================================================
    {
      nodeId: 'schneider-racks',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Racks & Enclosures',
      nameKo: '랙 및 인클로저',
      description: 'Server racks, network enclosures, and containment systems for data center and edge environments',
      descriptionKo: '데이터센터 및 엣지 환경을 위한 서버 랙, 네트워크 인클로저, 격리 시스템',
      sourceUrl: 'https://www.se.com/us/en/product-category/88400-racks-and-enclosures/',
      infraNodeTypes: [],
      children: [
        // -- NetShelter --
        {
          nodeId: 'schneider-netshelter',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'NetShelter',
          nameKo: 'NetShelter',
          description: 'Industry-leading server rack and enclosure family for data center, server room, and edge computing deployments',
          descriptionKo: '데이터센터, 서버실, 엣지 컴퓨팅 구축을 위한 업계 최고의 서버 랙 및 인클로저 제품군',
          sourceUrl: 'https://www.se.com/us/en/product-category/88405-netshelter/',
          infraNodeTypes: [],
          architectureRole: 'Data Center Physical Infrastructure / Rack Housing',
          architectureRoleKo: '데이터센터 물리적 인프라 / 랙 하우징',
          recommendedFor: [
            'Enterprise data center server racks',
            'Colocation standardized rack deployments',
            'Edge computing and branch office enclosures',
            'Soundproofed AV and office environments',
            'Network and telecommunications housing',
          ],
          recommendedForKo: [
            '엔터프라이즈 데이터센터 서버 랙',
            '코로케이션 표준화 랙 구축',
            '엣지 컴퓨팅 및 지사 인클로저',
            '방음 AV 및 사무 환경',
            '네트워크 및 통신 하우징',
          ],
          haFeatures: [
            'Cable management for redundant power paths',
            'Hot/cold aisle containment compatible',
            'Seismic Zone 4 rated options',
          ],
          children: [
            {
              nodeId: 'schneider-netshelter-sx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'NetShelter SX',
              nameKo: 'NetShelter SX',
              description: 'Standard 42U/48U server rack with 600/750mm widths, tool-free mounting, and hot/cold aisle containment support',
              descriptionKo: '600/750mm 폭, 무공구 장착, 핫/콜드 아일 격리 지원의 표준 42U/48U 서버 랙',
              sourceUrl: 'https://www.se.com/us/en/product-range/870-netshelter-sx/',
              lifecycle: 'active',
              architectureRole: 'Standard Data Center Server Rack',
              architectureRoleKo: '표준 데이터센터 서버 랙',
              recommendedFor: [
                'Enterprise and colocation data center standard rack',
                'Hot/cold aisle containment configurations',
                'High-density server and storage deployments',
                'OEM and white-label data center builds',
              ],
              recommendedForKo: [
                '엔터프라이즈 및 코로케이션 데이터센터 표준 랙',
                '핫/콜드 아일 격리 구성',
                '고밀도 서버 및 스토리지 구축',
                'OEM 및 화이트 라벨 데이터센터 구축',
              ],
              specs: {
                'Rack Units': '42U / 48U',
                'Width': '600mm / 750mm',
                'Depth': '1070mm / 1200mm',
                'Load Capacity': 'Up to 1360 kg (3000 lbs)',
                'Mounting': 'Tool-free, square-hole',
                'Containment': 'Hot/cold aisle containment compatible',
                'Cable Management': 'Vertical and horizontal options',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-netshelter-av',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'NetShelter AV',
              nameKo: 'NetShelter AV',
              description: 'AV-optimized enclosure with ventilated panels and cable access for audio/visual and broadcast equipment',
              descriptionKo: '오디오/비주얼 및 방송 장비를 위한 환기 패널과 케이블 접근이 가능한 AV 최적화 인클로저',
              sourceUrl: 'https://www.se.com/us/en/product-range/871-netshelter-av/',
              lifecycle: 'active',
              architectureRole: 'AV/Broadcast Equipment Housing',
              architectureRoleKo: 'AV/방송 장비 하우징',
              recommendedFor: [
                'Conference room and boardroom AV equipment',
                'Broadcast and production studio racks',
                'Educational institution media rooms',
              ],
              recommendedForKo: [
                '회의실 및 이사회실 AV 장비',
                '방송 및 제작 스튜디오 랙',
                '교육 기관 미디어 룸',
              ],
              specs: {
                'Rack Units': '24U / 42U',
                'Width': '600mm',
                'Design': 'Ventilated panels, split rear doors',
                'Cable Access': 'Top and bottom cable entry',
                'Casters': 'Included for mobility',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-netshelter-cx',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'NetShelter CX',
              nameKo: 'NetShelter CX',
              description: 'Soundproofed server enclosure for office and non-data-center environments, reducing noise to conversational levels',
              descriptionKo: '사무실 및 비데이터센터 환경을 위한 방음 서버 인클로저로, 소음을 대화 수준으로 감소',
              sourceUrl: 'https://www.se.com/us/en/product-range/1646-netshelter-cx/',
              lifecycle: 'active',
              architectureRole: 'Office / Non-DC Server Enclosure',
              architectureRoleKo: '사무실 / 비DC 서버 인클로저',
              recommendedFor: [
                'Office and open workspace server deployments',
                'Retail and branch office IT closets',
                'Noise-sensitive environments (hospitals, studios)',
              ],
              recommendedForKo: [
                '사무실 및 개방형 업무공간 서버 구축',
                '매장 및 지사 IT 클로젯',
                '소음에 민감한 환경 (병원, 스튜디오)',
              ],
              specs: {
                'Rack Units': '18U / 24U / 38U',
                'Noise Reduction': '< 40 dBA at 1m',
                'Design': 'Soundproofed, furniture-grade',
                'Ventilation': 'Active cooling with noise dampening',
                'Load Capacity': 'Up to 250 kg',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-netshelter-sv',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'NetShelter SV',
              nameKo: 'NetShelter SV',
              description: 'Value-line server rack for cost-sensitive IT deployments with essential features and easy assembly',
              descriptionKo: '필수 기능과 쉬운 조립으로 비용에 민감한 IT 구축을 위한 보급형 서버 랙',
              sourceUrl: 'https://www.se.com/us/en/product-range/2817-netshelter-sv/',
              lifecycle: 'active',
              architectureRole: 'Budget Server Rack',
              architectureRoleKo: '보급형 서버 랙',
              recommendedFor: [
                'Small business and SOHO IT infrastructure',
                'Development and test lab racks',
                'Education and training environments',
              ],
              recommendedForKo: [
                '소기업 및 SOHO IT 인프라',
                '개발 및 테스트 랩 랙',
                '교육 및 훈련 환경',
              ],
              specs: {
                'Rack Units': '42U / 48U',
                'Width': '600mm / 800mm',
                'Depth': '1060mm / 1200mm',
                'Load Capacity': 'Up to 1000 kg (2200 lbs)',
                'Assembly': 'Flat-packed, easy assembly',
                'Design': 'Perforated front and rear doors',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 5. Management & Monitoring
    // =====================================================================
    {
      nodeId: 'schneider-management',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Management & Monitoring',
      nameKo: '관리 및 모니터링',
      description: 'Data center infrastructure management (DCIM), cloud monitoring, and network management solutions',
      descriptionKo: '데이터센터 인프라 관리 (DCIM), 클라우드 모니터링, 네트워크 관리 솔루션',
      sourceUrl: 'https://www.se.com/us/en/product-category/88500-management-and-monitoring/',
      infraNodeTypes: [],
      children: [
        // -- EcoStruxure IT --
        {
          nodeId: 'schneider-ecostruxure-it',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'EcoStruxure IT',
          nameKo: 'EcoStruxure IT',
          description: 'Cloud-based DCIM platform for real-time monitoring, alerting, capacity planning, and data center lifecycle management',
          descriptionKo: '실시간 모니터링, 알림, 용량 계획, 데이터센터 수명 주기 관리를 위한 클라우드 기반 DCIM 플랫폼',
          sourceUrl: 'https://www.se.com/us/en/product-category/88505-ecostruxure-it/',
          infraNodeTypes: ['grafana'],
          architectureRole: 'Data Center Infrastructure Management (DCIM)',
          architectureRoleKo: '데이터센터 인프라 관리 (DCIM)',
          recommendedFor: [
            'Multi-site data center monitoring and management',
            'Real-time alerting and incident response',
            'Capacity planning and asset lifecycle management',
            'PUE monitoring and sustainability reporting',
            'Colocation tenant portal and SLA management',
          ],
          recommendedForKo: [
            '멀티사이트 데이터센터 모니터링 및 관리',
            '실시간 알림 및 인시던트 대응',
            '용량 계획 및 자산 수명 주기 관리',
            'PUE 모니터링 및 지속가능성 보고',
            '코로케이션 테넌트 포털 및 SLA 관리',
          ],
          supportedProtocols: [
            'SNMP v1/v2c/v3',
            'Modbus TCP/IP',
            'BACnet/IP',
            'HTTP/HTTPS REST API',
          ],
          haFeatures: [
            'Cloud-hosted SaaS architecture',
            'Multi-site dashboard',
            'Redundant data collection gateways',
          ],
          children: [
            {
              nodeId: 'schneider-ecostruxure-it-expert',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'EcoStruxure IT Expert',
              nameKo: 'EcoStruxure IT Expert',
              description: 'Cloud-native DCIM platform for vendor-agnostic monitoring of UPS, cooling, PDU, and environmental sensors across multiple sites',
              descriptionKo: '여러 사이트의 UPS, 냉각, PDU, 환경 센서를 벤더 무관하게 모니터링하는 클라우드 네이티브 DCIM 플랫폼',
              sourceUrl: 'https://www.se.com/us/en/product-range/62166-ecostruxure-it-expert/',
              lifecycle: 'active',
              infraNodeTypes: ['grafana'],
              architectureRole: 'Cloud DCIM Monitoring Platform',
              architectureRoleKo: '클라우드 DCIM 모니터링 플랫폼',
              recommendedFor: [
                'Multi-site data center monitoring',
                'Edge computing site remote management',
                'Colocation operator DCIM',
                'Vendor-agnostic infrastructure visibility',
              ],
              recommendedForKo: [
                '멀티사이트 데이터센터 모니터링',
                '엣지 컴퓨팅 사이트 원격 관리',
                '코로케이션 운영자 DCIM',
                '벤더 무관 인프라 가시성',
              ],
              specs: {
                'Deployment': 'Cloud-hosted SaaS',
                'Monitoring': 'UPS, PDU, Cooling, Environment sensors',
                'Vendor Support': 'Multi-vendor (SNMP-based)',
                'Mobile App': 'iOS / Android',
                'Alerting': 'Email, SMS, push notifications',
                'API': 'RESTful API for integration',
              },
              licensingModel: 'subscription',
              children: [],
            },
            {
              nodeId: 'schneider-ecostruxure-it-advisor',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'EcoStruxure IT Advisor',
              nameKo: 'EcoStruxure IT Advisor',
              description: 'Advanced DCIM capacity planning and analytics platform for optimizing data center power, cooling, and space utilization',
              descriptionKo: '데이터센터 전력, 냉각, 공간 활용 최적화를 위한 고급 DCIM 용량 계획 및 분석 플랫폼',
              sourceUrl: 'https://www.se.com/us/en/product-range/63464-ecostruxure-it-advisor/',
              lifecycle: 'active',
              infraNodeTypes: ['grafana'],
              architectureRole: 'DCIM Capacity Planning & Analytics',
              architectureRoleKo: 'DCIM 용량 계획 및 분석',
              recommendedFor: [
                'Data center capacity planning and forecasting',
                'Asset lifecycle management',
                'CFD thermal analysis and optimization',
                'Compliance reporting and auditing',
              ],
              recommendedForKo: [
                '데이터센터 용량 계획 및 예측',
                '자산 수명 주기 관리',
                'CFD 열 분석 및 최적화',
                '규정 준수 보고 및 감사',
              ],
              specs: {
                'Deployment': 'On-premises / Cloud hybrid',
                'Analytics': '3D visualization, CFD modeling',
                'Planning': 'Power, cooling, and space capacity',
                'Reporting': 'Compliance, energy, asset reports',
                'Integration': 'BMS, CMDB, ITSM connectors',
              },
              licensingModel: 'subscription',
              children: [],
            },
          ],
        },

        // -- Network Management Cards --
        {
          nodeId: 'schneider-nmc',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Network Management Cards',
          nameKo: '네트워크 관리 카드',
          description: 'Hardware cards for remote monitoring and management of APC UPS systems and environmental conditions via network protocols',
          descriptionKo: '네트워크 프로토콜을 통한 APC UPS 시스템 및 환경 상태의 원격 모니터링 및 관리를 위한 하드웨어 카드',
          sourceUrl: 'https://www.se.com/us/en/product-category/88510-network-management-cards/',
          infraNodeTypes: ['grafana'],
          architectureRole: 'UPS / Infrastructure Network Monitoring Interface',
          architectureRoleKo: 'UPS / 인프라 네트워크 모니터링 인터페이스',
          recommendedFor: [
            'Remote UPS monitoring and management over IP',
            'Environmental monitoring (temperature, humidity)',
            'SNMP integration with enterprise NMS',
            'Automated shutdown orchestration',
          ],
          recommendedForKo: [
            'IP를 통한 원격 UPS 모니터링 및 관리',
            '환경 모니터링 (온도, 습도)',
            '엔터프라이즈 NMS와의 SNMP 통합',
            '자동 종료 오케스트레이션',
          ],
          supportedProtocols: [
            'SNMP v1/v2c/v3',
            'HTTP/HTTPS',
            'SSH',
            'Telnet',
            'Modbus',
          ],
          children: [
            {
              nodeId: 'schneider-ap9641',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'AP9641 UPS Network Management Card 3',
              nameKo: 'AP9641 UPS 네트워크 관리 카드 3',
              description: 'UPS network management card with environmental monitoring support, SNMP v3, and EcoStruxure IT integration',
              descriptionKo: '환경 모니터링 지원, SNMP v3, EcoStruxure IT 통합의 UPS 네트워크 관리 카드',
              sourceUrl: 'https://www.se.com/us/en/product-range/61935-ups-network-management-cards/',
              lifecycle: 'active',
              infraNodeTypes: ['grafana'],
              architectureRole: 'UPS Remote Management Interface',
              architectureRoleKo: 'UPS 원격 관리 인터페이스',
              recommendedFor: [
                'Remote UPS monitoring via SNMP/HTTP',
                'Environmental sensor integration',
                'Automated graceful server shutdown',
              ],
              recommendedForKo: [
                'SNMP/HTTP를 통한 원격 UPS 모니터링',
                '환경 센서 통합',
                '자동 정상 서버 종료',
              ],
              specs: {
                'Protocols': 'SNMP v1/v2c/v3, HTTP/HTTPS, SSH, Telnet',
                'Environmental': 'Temperature, humidity sensor port',
                'Interface': '10/100 Ethernet (RJ45)',
                'Compatibility': 'Smart-UPS, Symmetra',
                'Security': 'SNMPv3, SSL/TLS, RADIUS',
              },
              formFactor: 'appliance',
              children: [],
            },
            {
              nodeId: 'schneider-ap9643',
              depth: 2,
              depthLabel: 'Series',
              depthLabelKo: '시리즈',
              name: 'AP9643 UPS Network Management Card 3 with Environmental Monitoring',
              nameKo: 'AP9643 UPS 네트워크 관리 카드 3 (환경 모니터링 포함)',
              description: 'Advanced UPS network management card with integrated temperature/humidity sensor and dry contact I/O for environmental monitoring',
              descriptionKo: '환경 모니터링을 위한 통합 온도/습도 센서 및 건접점 I/O가 있는 고급 UPS 네트워크 관리 카드',
              sourceUrl: 'https://www.se.com/us/en/product-range/61935-ups-network-management-cards/',
              lifecycle: 'active',
              infraNodeTypes: ['grafana'],
              architectureRole: 'UPS + Environmental Monitoring Interface',
              architectureRoleKo: 'UPS + 환경 모니터링 인터페이스',
              recommendedFor: [
                'Server rooms without dedicated environmental monitoring',
                'Edge sites requiring temperature/humidity tracking',
                'Integration with building management systems',
              ],
              recommendedForKo: [
                '전용 환경 모니터링이 없는 서버실',
                '온도/습도 추적이 필요한 엣지 사이트',
                '빌딩 관리 시스템과의 통합',
              ],
              specs: {
                'Protocols': 'SNMP v1/v2c/v3, HTTP/HTTPS, SSH, Telnet',
                'Environmental': 'Integrated temp/humidity sensor + 2 dry contact I/O',
                'Interface': '10/100 Ethernet (RJ45)',
                'Compatibility': 'Smart-UPS, Symmetra, Galaxy',
                'Security': 'SNMPv3, SSL/TLS, RADIUS',
                'Sensor Expansion': 'Up to 16 external temp/humidity sensors',
              },
              formFactor: 'appliance',
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
