/**
 * Veeam Software -- Full Product Catalog
 *
 * Hierarchical product tree covering Data Platform, Cloud & SaaS Protection,
 * Monitoring & Analytics, and Cyber Resilience categories.
 *
 * Data sourced from https://www.veeam.com
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// Veeam Software Product Catalog
// ---------------------------------------------------------------------------

export const veeamCatalog: VendorCatalog = {
  vendorId: 'veeam',
  vendorName: 'Veeam Software',
  vendorNameKo: '빔 소프트웨어',
  headquarters: 'Columbus, OH, USA',
  website: 'https://www.veeam.com',
  productPageUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
  depthStructure: ['category', 'product-line', 'edition'],
  depthStructureKo: ['카테고리', '제품 라인', '에디션'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.veeam.com',
  stats: { totalProducts: 31, maxDepth: 2, categoriesCount: 4 },
  products: [
    // =====================================================================
    // 1. Data Platform
    // =====================================================================
    {
      nodeId: 'veeam-data-platform',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Data Platform',
      nameKo: '데이터 플랫폼',
      description: 'Comprehensive data backup, recovery, monitoring, and orchestration platform for hybrid and multi-cloud environments',
      descriptionKo: '하이브리드 및 멀티클라우드 환경을 위한 종합 데이터 백업, 복구, 모니터링, 오케스트레이션 플랫폼',
      sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
      infraNodeTypes: ['backup'],
      children: [
        // -- Veeam Data Platform (integrated suite) --
        {
          nodeId: 'veeam-data-platform-suite',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Data Platform',
          nameKo: 'Veeam 데이터 플랫폼',
          description: 'Flagship integrated suite combining backup, monitoring, and recovery orchestration with AI-powered threat detection and zero-trust data resilience',
          descriptionKo: 'AI 기반 위협 탐지 및 제로 트러스트 데이터 복원력을 갖춘 백업, 모니터링, 복구 오케스트레이션 통합 플래그십 제품',
          sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Data Protection & Disaster Recovery',
          architectureRoleKo: '데이터 보호 및 재해 복구',
          recommendedFor: [
            'Enterprise hybrid cloud backup and recovery',
            'Zero-trust data resilience architecture',
            'Compliance-driven backup with audit reporting (GDPR, HIPAA, SOC 2)',
            'Multi-platform workload protection (VMware, Hyper-V, Nutanix, cloud)',
            'Ransomware recovery with immutable backups',
          ],
          recommendedForKo: [
            '엔터프라이즈 하이브리드 클라우드 백업 및 복구',
            '제로 트러스트 데이터 복원력 아키텍처',
            '감사 보고서를 포함한 컴플라이언스 기반 백업 (GDPR, HIPAA, SOC 2)',
            '멀티 플랫폼 워크로드 보호 (VMware, Hyper-V, Nutanix, 클라우드)',
            '불변 백업을 통한 랜섬웨어 복구',
          ],
          supportedProtocols: [
            'S3', 'NFS', 'SMB/CIFS', 'iSCSI', 'Fibre Channel',
            'REST API', 'SAML', 'LDAP', 'Kerberos',
          ],
          haFeatures: [
            'Built-in backup server high availability with automatic failover',
            'Snapshot orchestration across environments',
            'AI-guided recovery verification',
            'Multiple recovery point redundancy',
            'Continuous Data Protection (CDP)',
          ],
          securityCapabilities: [
            'Zero Trust Data Resilience architecture',
            'Immutable backup storage (WORM)',
            'Inline malware scanning with YARA rules',
            'IOC threat scanning and anomaly detection',
            'AES-256 encryption in transit and at rest',
            'RBAC with SAML SSO integration',
            'Four-eyes approval for sensitive operations',
            'Cleanroom recovery validation',
            'Security & Compliance Analyzer',
          ],
          children: [
            {
              nodeId: 'veeam-data-platform-foundation',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Data Platform Foundation',
              nameKo: 'Veeam 데이터 플랫폼 파운데이션',
              description: 'Essential backup and recovery capabilities for data protection with immutable storage and cross-platform instant recovery',
              descriptionKo: '불변 스토리지 및 크로스 플랫폼 즉시 복구를 갖춘 데이터 보호를 위한 필수 백업 및 복구 기능',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Included Components': 'Veeam Backup & Replication',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Cloud Platforms': 'AWS, Azure, Google Cloud',
                'Physical OS Support': 'Windows, Linux, macOS, Unix (AIX, Solaris)',
                'Application Support': 'Microsoft Exchange/SQL/SharePoint, Oracle, SAP HANA, PostgreSQL, MongoDB',
                'Recovery Type': 'Instant Recovery (seconds-level RTO)',
                'Deployment Model': 'On-premises software appliance or cloud',
                'Licensing': 'Universal per-workload subscription',
              },
              children: [],
            },
            {
              nodeId: 'veeam-data-platform-advanced',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Data Platform Advanced',
              nameKo: 'Veeam 데이터 플랫폼 어드밴스드',
              description: 'Backup and recovery with AI-powered observability, monitoring, and enhanced cyber resilience features',
              descriptionKo: 'AI 기반 옵저버빌리티, 모니터링 및 향상된 사이버 복원력 기능을 갖춘 백업 및 복구',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Included Components': 'Veeam Backup & Replication, Veeam ONE',
                'AI Features': 'Veeam Intelligence, anomaly detection, threat assessment',
                'Monitoring': 'Real-time infrastructure monitoring and reporting',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Cloud Platforms': 'AWS, Azure, Google Cloud',
                'Physical OS Support': 'Windows, Linux, macOS, Unix (AIX, Solaris)',
                'Application Support': 'Microsoft Exchange/SQL/SharePoint, Oracle, SAP HANA, PostgreSQL, MongoDB',
                'Licensing': 'Universal per-workload subscription',
              },
              children: [],
            },
            {
              nodeId: 'veeam-data-platform-premium',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Data Platform Premium',
              nameKo: 'Veeam 데이터 플랫폼 프리미엄',
              description: 'Full-suite data platform with backup, monitoring, recovery orchestration, compliance reporting, and Veeam Cyber Secure incident response',
              descriptionKo: '백업, 모니터링, 복구 오케스트레이션, 컴플라이언스 보고 및 Veeam Cyber Secure 사고 대응을 포함한 풀 스위트 데이터 플랫폼',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Included Components': 'Veeam Backup & Replication, Veeam ONE, Veeam Recovery Orchestrator',
                'Orchestration': 'Automated DR orchestration with compliance documentation',
                'AI Features': 'Veeam Intelligence, anomaly detection, threat assessment',
                'Monitoring': 'Real-time infrastructure monitoring and reporting',
                'Compliance': 'Dynamic Documentation for audit-ready reports (GDPR, HIPAA, SOC 2)',
                'Incident Response': 'Veeam Cyber Secure Program included',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Licensing': 'Universal per-workload subscription',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Backup & Replication --
        {
          nodeId: 'veeam-backup-replication',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup & Replication',
          nameKo: 'Veeam 백업 및 복제',
          description: 'Core backup engine providing instant recovery, replication, and CDP for virtual, physical, cloud, and container workloads across 7+ hypervisors',
          descriptionKo: '7개 이상의 하이퍼바이저에 걸쳐 가상, 물리, 클라우드, 컨테이너 워크로드를 위한 즉시 복구, 복제, CDP를 제공하는 핵심 백업 엔진',
          sourceUrl: 'https://www.veeam.com/products/veeam-data-platform/backup-recovery.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Data Protection & Disaster Recovery',
          architectureRoleKo: '데이터 보호 및 재해 복구',
          recommendedFor: [
            'VMware and Hyper-V virtual machine backup',
            'Physical server backup (Windows, Linux, macOS, Unix)',
            'Application-aware backup (SQL, Oracle, SAP HANA)',
            'Continuous Data Protection for near-zero RPO',
            'Cross-platform disaster recovery',
          ],
          recommendedForKo: [
            'VMware 및 Hyper-V 가상 머신 백업',
            '물리 서버 백업 (Windows, Linux, macOS, Unix)',
            '애플리케이션 인식 백업 (SQL, Oracle, SAP HANA)',
            '제로에 가까운 RPO를 위한 연속 데이터 보호',
            '크로스 플랫폼 재해 복구',
          ],
          supportedProtocols: [
            'S3', 'NFS', 'SMB/CIFS', 'iSCSI', 'Fibre Channel',
            'REST API', 'SAML', 'LDAP',
          ],
          haFeatures: [
            'Built-in backup server high availability',
            'Automatic failover to standby backup server',
            'Continuous Data Protection (CDP)',
            'Snapshot orchestration',
            'Portable self-describing backup format',
          ],
          securityCapabilities: [
            'Immutable backup storage (WORM)',
            'Zero Trust access controls',
            'Inline malware analysis with YARA rules',
            'IOC threat scanning',
            'AES-256 encryption',
            'RBAC with SAML SSO',
            'Four-eyes approval',
            'Security & Compliance Analyzer',
          ],
          children: [
            {
              nodeId: 'veeam-backup-replication-community',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup & Replication Community Edition',
              nameKo: 'Veeam 백업 및 복제 커뮤니티 에디션',
              description: 'Free edition supporting up to 10 workloads for small environments, home labs, and evaluation purposes',
              descriptionKo: '소규모 환경, 홈 랩, 평가 목적으로 최대 10개 워크로드를 지원하는 무료 에디션',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform/backup-recovery.html',
              lifecycle: 'active',
              licensingModel: 'perpetual',
              formFactor: 'virtual',
              specs: {
                'Max Workloads': '10',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV',
                'Physical OS Support': 'Windows, Linux',
                'NAS Backup': 'Supported',
                'Cloud Backup': 'Not included',
                'Licensing': 'Free (perpetual)',
                'Support': 'Community forum only',
              },
              children: [],
            },
            {
              nodeId: 'veeam-backup-replication-standard',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup & Replication Standard',
              nameKo: 'Veeam 백업 및 복제 스탠다드',
              description: 'Standard backup and replication for SMB with instant recovery and full platform support',
              descriptionKo: '즉시 복구 및 전체 플랫폼 지원을 갖춘 SMB용 표준 백업 및 복제',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform/backup-recovery.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Workload Limit': 'Unlimited',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Physical OS Support': 'Windows, Linux, macOS, Unix',
                'NAS Backup': 'Supported',
                'Cloud Backup': 'AWS, Azure, Google Cloud',
                'Instant Recovery': 'Supported',
                'Replication': 'Supported',
              },
              children: [],
            },
            {
              nodeId: 'veeam-backup-replication-enterprise',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup & Replication Enterprise',
              nameKo: 'Veeam 백업 및 복제 엔터프라이즈',
              description: 'Enterprise backup with advanced features including WAN acceleration, storage snapshots integration, and enhanced scalability',
              descriptionKo: 'WAN 가속, 스토리지 스냅샷 통합, 향상된 확장성을 포함한 고급 기능을 갖춘 엔터프라이즈 백업',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform/backup-recovery.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Workload Limit': 'Unlimited',
                'WAN Acceleration': 'Supported',
                'Storage Snapshots': 'HP, NetApp, Dell EMC integration',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Physical OS Support': 'Windows, Linux, macOS, Unix (AIX, Solaris)',
                'Application Support': 'Microsoft Exchange/SQL/SharePoint, Oracle, SAP HANA, PostgreSQL, MongoDB',
                'Tape Support': 'Supported',
              },
              children: [],
            },
            {
              nodeId: 'veeam-backup-replication-enterprise-plus',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup & Replication Enterprise Plus',
              nameKo: 'Veeam 백업 및 복제 엔터프라이즈 플러스',
              description: 'Top-tier edition with all enterprise features plus scale-out backup repository, advanced multi-tenancy, and Veeam ONE monitoring integration',
              descriptionKo: '스케일아웃 백업 리포지토리, 고급 멀티테넌시, Veeam ONE 모니터링 통합을 포함한 모든 엔터프라이즈 기능을 갖춘 최상위 에디션',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform/backup-recovery.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Workload Limit': 'Unlimited',
                'Scale-Out Backup Repository': 'Supported',
                'WAN Acceleration': 'Supported',
                'Storage Snapshots': 'HP, NetApp, Dell EMC integration',
                'Multi-Tenancy': 'Advanced RBAC with tenant isolation',
                'Supported Hypervisors': 'VMware, Hyper-V, Nutanix AHV, Oracle Linux VM, RHV, Proxmox, Scale Computing',
                'Application Support': 'Microsoft Exchange/SQL/SharePoint, Oracle, SAP HANA, PostgreSQL, MongoDB',
                'Monitoring': 'Veeam ONE integration available',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Cloud & SaaS Protection
    // =====================================================================
    {
      nodeId: 'veeam-cloud-saas',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Cloud & SaaS Protection',
      nameKo: '클라우드 및 SaaS 보호',
      description: 'Native cloud and SaaS application backup solutions for AWS, Azure, Google Cloud, Microsoft 365, and Salesforce',
      descriptionKo: 'AWS, Azure, Google Cloud, Microsoft 365, Salesforce를 위한 네이티브 클라우드 및 SaaS 애플리케이션 백업 솔루션',
      sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
      infraNodeTypes: ['backup'],
      children: [
        // -- Veeam Backup for Microsoft 365 --
        {
          nodeId: 'veeam-backup-m365',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup for Microsoft 365',
          nameKo: 'Veeam Microsoft 365 백업',
          description: 'SaaS-based backup and recovery for Exchange Online, SharePoint, OneDrive, Teams, and Entra ID with unlimited storage',
          descriptionKo: 'Exchange Online, SharePoint, OneDrive, Teams, Entra ID를 위한 무제한 스토리지 SaaS 기반 백업 및 복구',
          sourceUrl: 'https://www.veeam.com/products/saas/microsoft-office-365-entra-id-backup-service.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'SaaS Data Protection',
          architectureRoleKo: 'SaaS 데이터 보호',
          recommendedFor: [
            'Microsoft 365 data protection and compliance',
            'Entra ID identity threat recovery',
            'eDiscovery and regulatory compliance',
            'Ransomware recovery for SaaS data',
          ],
          recommendedForKo: [
            'Microsoft 365 데이터 보호 및 컴플라이언스',
            'Entra ID 신원 위협 복구',
            'eDiscovery 및 규정 준수',
            'SaaS 데이터 랜섬웨어 복구',
          ],
          securityCapabilities: [
            'AES-256 encryption in transit and at rest',
            'Multi-factor authentication (MFA)',
            'Zero-trust security approach',
            'Service-level immutability',
            'Logically air-gapped storage',
          ],
          children: [
            {
              nodeId: 'veeam-backup-m365-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup for Microsoft 365',
              nameKo: 'Veeam Microsoft 365 백업',
              description: 'Full-featured SaaS backup for Microsoft 365 including Exchange, SharePoint, OneDrive, Teams, and Entra ID with granular recovery and unlimited storage',
              descriptionKo: 'Exchange, SharePoint, OneDrive, Teams, Entra ID를 포함한 세분화 복구 및 무제한 스토리지의 완전 기능 Microsoft 365 SaaS 백업',
              sourceUrl: 'https://www.veeam.com/products/saas/microsoft-office-365-entra-id-backup-service.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Protected Workloads': 'Exchange Online, SharePoint, OneDrive, Teams, Entra ID',
                'Storage': 'Unlimited (included)',
                'Data Residency': '60+ Azure regions, 140+ countries',
                'Storage Redundancy': 'Locally redundant (3 copies within region)',
                'Foundation Tier': '$2.63/user/month (M365 only)',
                'Advanced Tier': '$3.33/user/month (adds Entra ID)',
                'Premium Tier': '$7/user/month (adds M365 DR)',
                'Deployment Model': 'Fully managed SaaS',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Backup for Salesforce --
        {
          nodeId: 'veeam-backup-salesforce',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup for Salesforce',
          nameKo: 'Veeam Salesforce 백업',
          description: 'Automated backup, granular recovery, and sandbox seeding for Salesforce data and metadata with three-layer encryption',
          descriptionKo: '3중 암호화를 갖춘 Salesforce 데이터 및 메타데이터의 자동 백업, 세분화 복구, 샌드박스 시딩',
          sourceUrl: 'https://www.veeam.com/products/saas/salesforce-backup-service.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'SaaS Data Protection',
          architectureRoleKo: 'SaaS 데이터 보호',
          recommendedFor: [
            'Salesforce data and metadata backup',
            'Regulatory compliance for CRM data',
            'Sandbox seeding with production data',
            'Salesforce storage optimization through archiving',
          ],
          recommendedForKo: [
            'Salesforce 데이터 및 메타데이터 백업',
            'CRM 데이터 규정 준수',
            '프로덕션 데이터를 활용한 샌드박스 시딩',
            '아카이빙을 통한 Salesforce 스토리지 최적화',
          ],
          securityCapabilities: [
            'Three-layer encryption (host, database, configuration)',
            'Service-level immutability',
            'SSO and MFA',
            'RBAC',
            'AWS BYOK encryption',
            'Data masking for sandbox seeding',
          ],
          children: [
            {
              nodeId: 'veeam-backup-salesforce-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup for Salesforce',
              nameKo: 'Veeam Salesforce 백업',
              description: 'SaaS or self-managed backup for Salesforce data, metadata, and files with granular compare-and-restore and unlimited storage',
              descriptionKo: '세분화 비교 복원 및 무제한 스토리지를 갖춘 Salesforce 데이터, 메타데이터, 파일 SaaS 또는 자체 관리 백업',
              sourceUrl: 'https://www.veeam.com/products/saas/salesforce-backup-service.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Protected Data': 'Accounts, Contacts, Leads, Opportunities, Cases, Files, Metadata',
                'Salesforce Clouds': 'Sales, Service, Experience Cloud',
                'Storage': 'Unlimited (included)',
                'Deployment Options': 'SaaS (Veeam Data Cloud) or self-managed (on-premises/AWS/Azure)',
                'Backup Method': 'Automated incremental sync',
                'Restore': 'Granular compare and restore',
                'Salesforce Requirement': 'Enterprise or Unlimited edition',
                'Licensing': 'Per active Salesforce user',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Backup for AWS --
        {
          nodeId: 'veeam-backup-aws',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup for AWS',
          nameKo: 'Veeam AWS 백업',
          description: 'Native policy-based backup for AWS workloads including EC2, RDS, EFS, S3, DynamoDB, and VPC with cross-account and cross-region recovery',
          descriptionKo: 'EC2, RDS, EFS, S3, DynamoDB, VPC를 포함한 크로스 계정 및 크로스 리전 복구를 갖춘 AWS 워크로드용 네이티브 정책 기반 백업',
          sourceUrl: 'https://www.veeam.com/products/cloud/aws-backup.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Cloud-Native Data Protection',
          architectureRoleKo: '클라우드 네이티브 데이터 보호',
          recommendedFor: [
            'AWS workload backup and disaster recovery',
            'Cross-account and cross-region data protection',
            'Hybrid cloud backup (AWS to on-premises)',
            'Cost-optimized backup lifecycle management',
          ],
          recommendedForKo: [
            'AWS 워크로드 백업 및 재해 복구',
            '크로스 계정 및 크로스 리전 데이터 보호',
            '하이브리드 클라우드 백업 (AWS에서 온프레미스)',
            '비용 최적화 백업 라이프사이클 관리',
          ],
          securityCapabilities: [
            'Immutable WORM backup',
            'Logically air-gapped storage',
            'Least-privilege IAM with AWS Organizations RBAC',
            'AES-256 encryption',
            'Web proxy security',
          ],
          children: [
            {
              nodeId: 'veeam-backup-aws-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup for AWS',
              nameKo: 'Veeam AWS 백업',
              description: 'Policy-based AWS-native backup for EC2, EBS, RDS, EFS, DynamoDB, Aurora, S3, Redshift, FSx, and VPC with automated protection and lifecycle management',
              descriptionKo: 'EC2, EBS, RDS, EFS, DynamoDB, Aurora, S3, Redshift, FSx, VPC를 위한 자동 보호 및 라이프사이클 관리를 갖춘 정책 기반 AWS 네이티브 백업',
              sourceUrl: 'https://www.veeam.com/products/cloud/aws-backup.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'AWS Services': 'EC2, EBS, RDS, EFS, DynamoDB, Aurora, S3, S3 Glacier, Redshift, FSx, VPC, Outposts',
                'Backup Target': 'Amazon S3',
                'Recovery Options': 'Full instance, file-level, cross-account, cross-region',
                'Automation': 'Policy-based auto-detection and protection',
                'Cost Optimization': 'Backup lifecycling to object storage',
                'Free Tier': 'Community Edition available',
                'Deployment': 'AWS Marketplace or standalone',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Backup for Azure --
        {
          nodeId: 'veeam-backup-azure',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup for Azure',
          nameKo: 'Veeam Azure 백업',
          description: 'Native policy-based backup for Azure workloads including VMs, SQL, Files, Blob, and Cosmos DB with immutable and air-gapped storage',
          descriptionKo: 'VM, SQL, Files, Blob, Cosmos DB를 포함한 불변 및 에어갭 스토리지를 갖춘 Azure 워크로드용 네이티브 정책 기반 백업',
          sourceUrl: 'https://www.veeam.com/products/cloud/azure-backup.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Cloud-Native Data Protection',
          architectureRoleKo: '클라우드 네이티브 데이터 보호',
          recommendedFor: [
            'Azure VM and managed disk backup',
            'Azure SQL and Cosmos DB data protection',
            'Hybrid cloud disaster recovery',
            'Azure cost optimization with backup lifecycle management',
          ],
          recommendedForKo: [
            'Azure VM 및 관리형 디스크 백업',
            'Azure SQL 및 Cosmos DB 데이터 보호',
            '하이브리드 클라우드 재해 복구',
            '백업 라이프사이클 관리를 통한 Azure 비용 최적화',
          ],
          securityCapabilities: [
            'Immutable WORM backup',
            'Logically air-gapped storage',
            'RBAC with least-privilege IAM',
            'AES-256 encryption in transit and at rest',
            'Azure Well-Architected Framework compliance',
          ],
          children: [
            {
              nodeId: 'veeam-backup-azure-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup for Azure',
              nameKo: 'Veeam Azure 백업',
              description: 'Policy-based Azure-native backup for VMs, SQL, Files, Blob Storage, Cosmos DB, and VNets with 7x compression and cool-tier optimization',
              descriptionKo: 'VM, SQL, Files, Blob Storage, Cosmos DB, VNet을 위한 7배 압축 및 쿨 티어 최적화를 갖춘 정책 기반 Azure 네이티브 백업',
              sourceUrl: 'https://www.veeam.com/products/cloud/azure-backup.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Azure Services': 'VMs, Managed Disks, Azure SQL, Azure Files, Blob Storage, Cosmos DB, VNets',
                'Compression': 'Up to 7x reduction',
                'Recovery Options': 'Full instance, file-level, cross-region',
                'SaaS Pricing': '$42/TB/month (all-inclusive)',
                'Storage Tiers': 'Hot, Cool, Archive',
                'Deployment': 'SaaS (Veeam Data Cloud), self-managed, or partner-managed',
                'Free Tier': 'Community Edition available',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Backup for Google Cloud --
        {
          nodeId: 'veeam-backup-gcp',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Backup for Google Cloud',
          nameKo: 'Veeam Google Cloud 백업',
          description: 'Native policy-based backup for Google Cloud workloads with automated snapshot management and cross-region recovery',
          descriptionKo: '자동 스냅샷 관리 및 크로스 리전 복구를 갖춘 Google Cloud 워크로드용 네이티브 정책 기반 백업',
          sourceUrl: 'https://www.veeam.com/products/cloud/google-cloud-backup.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Cloud-Native Data Protection',
          architectureRoleKo: '클라우드 네이티브 데이터 보호',
          recommendedFor: [
            'Google Cloud VM and disk backup',
            'Multi-cloud data protection strategy',
            'GCP disaster recovery',
            'Hybrid cloud backup lifecycle management',
          ],
          recommendedForKo: [
            'Google Cloud VM 및 디스크 백업',
            '멀티클라우드 데이터 보호 전략',
            'GCP 재해 복구',
            '하이브리드 클라우드 백업 라이프사이클 관리',
          ],
          securityCapabilities: [
            'Immutable backup storage',
            'Logically air-gapped storage',
            'RBAC with least-privilege IAM',
            'Encryption in transit and at rest',
          ],
          children: [
            {
              nodeId: 'veeam-backup-gcp-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Backup for Google Cloud',
              nameKo: 'Veeam Google Cloud 백업',
              description: 'Policy-based GCP-native backup for Compute Engine instances and persistent disks with automated protection and cross-region recovery',
              descriptionKo: 'Compute Engine 인스턴스 및 영구 디스크를 위한 자동 보호 및 크로스 리전 복구를 갖춘 정책 기반 GCP 네이티브 백업',
              sourceUrl: 'https://www.veeam.com/products/cloud/google-cloud-backup.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'GCP Services': 'Compute Engine VMs, Persistent Disks, Cloud Storage',
                'Backup Target': 'Google Cloud Storage',
                'Recovery Options': 'Full instance, file-level, cross-region',
                'Automation': 'Policy-based auto-detection and protection',
                'Cost Optimization': 'Backup lifecycling across storage classes',
                'Deployment': 'GCP Marketplace or standalone',
                'Free Tier': 'Community Edition available',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. Monitoring & Analytics
    // =====================================================================
    {
      nodeId: 'veeam-monitoring-analytics',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Monitoring & Analytics',
      nameKo: '모니터링 및 분석',
      description: 'Infrastructure monitoring, intelligent diagnostics, and disaster recovery orchestration with compliance automation',
      descriptionKo: '컴플라이언스 자동화를 갖춘 인프라 모니터링, 지능형 진단, 재해 복구 오케스트레이션',
      sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
      infraNodeTypes: ['backup'],
      children: [
        // -- Veeam ONE --
        {
          nodeId: 'veeam-one',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam ONE',
          nameKo: 'Veeam ONE',
          description: 'AI-powered monitoring, analytics, and reporting for backup infrastructure with real-time alerting, capacity planning, and intelligent diagnostics',
          descriptionKo: '실시간 알림, 용량 계획, 지능형 진단을 갖춘 백업 인프라를 위한 AI 기반 모니터링, 분석, 보고',
          sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Backup Infrastructure Monitoring & Observability',
          architectureRoleKo: '백업 인프라 모니터링 및 옵저버빌리티',
          recommendedFor: [
            'Backup infrastructure health monitoring',
            'Proactive capacity planning and resource optimization',
            'SLA compliance tracking and reporting',
            'Intelligent anomaly detection for backup environments',
          ],
          recommendedForKo: [
            '백업 인프라 상태 모니터링',
            '선제적 용량 계획 및 리소스 최적화',
            'SLA 컴플라이언스 추적 및 보고',
            '백업 환경을 위한 지능형 이상 탐지',
          ],
          securityCapabilities: [
            'RBAC for monitoring access',
            'Anomaly detection and alerting',
            'Audit-ready reporting',
            'Integration with SIEM/SOC tools',
          ],
          children: [
            {
              nodeId: 'veeam-one-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam ONE',
              nameKo: 'Veeam ONE',
              description: 'Comprehensive monitoring and analytics for Veeam backup infrastructure with AI-powered intelligence, 300+ preset alarms, and customizable dashboards',
              descriptionKo: 'AI 기반 인텔리전스, 300개 이상의 사전 설정 알람, 커스터마이저블 대시보드를 갖춘 Veeam 백업 인프라를 위한 종합 모니터링 및 분석',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Monitoring Targets': 'Veeam Backup & Replication, VMware, Hyper-V, Nutanix',
                'Preset Alarms': '300+',
                'Reporting': 'Customizable dashboards and reports',
                'AI Features': 'Veeam Intelligence diagnostics',
                'Capacity Planning': 'Predictive analytics',
                'Deployment': 'On-premises or cloud',
                'Included In': 'Veeam Data Platform Advanced and Premium',
              },
              children: [],
            },
          ],
        },
        // -- Veeam Recovery Orchestrator --
        {
          nodeId: 'veeam-recovery-orchestrator',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Recovery Orchestrator',
          nameKo: 'Veeam 복구 오케스트레이터',
          description: 'Automated disaster recovery orchestration with one-click failover, compliance documentation, and recovery verification testing',
          descriptionKo: '원클릭 장애 조치, 컴플라이언스 문서화, 복구 검증 테스트를 갖춘 자동 재해 복구 오케스트레이션',
          sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Disaster Recovery Orchestration & Compliance',
          architectureRoleKo: '재해 복구 오케스트레이션 및 컴플라이언스',
          recommendedFor: [
            'Automated disaster recovery planning and testing',
            'Regulatory compliance documentation (GDPR, HIPAA, SOC 2)',
            'One-click site failover for business continuity',
            'DR readiness verification and audit reporting',
          ],
          recommendedForKo: [
            '자동 재해 복구 계획 및 테스트',
            '규정 준수 문서화 (GDPR, HIPAA, SOC 2)',
            '비즈니스 연속성을 위한 원클릭 사이트 장애 조치',
            'DR 준비 상태 검증 및 감사 보고',
          ],
          haFeatures: [
            'One-click site failover',
            'Automated recovery testing without production impact',
            'Dynamic documentation for DR plans',
            'Recovery point verification',
          ],
          securityCapabilities: [
            'Compliance reporting (GDPR, HIPAA, SOC 2)',
            'Audit-ready documentation generation',
            'Automated recovery verification',
            'RBAC for orchestration access',
          ],
          children: [
            {
              nodeId: 'veeam-recovery-orchestrator-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Recovery Orchestrator',
              nameKo: 'Veeam 복구 오케스트레이터',
              description: 'Enterprise DR orchestration engine with automated failover plans, non-disruptive testing, and compliance report generation for regulatory frameworks',
              descriptionKo: '자동 장애 조치 계획, 비파괴 테스트, 규제 프레임워크용 컴플라이언스 보고서 생성을 갖춘 엔터프라이즈 DR 오케스트레이션 엔진',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Orchestration': 'Automated DR plans with dependency mapping',
                'Testing': 'Non-disruptive automated DR testing',
                'Compliance': 'Dynamic Documentation for GDPR, HIPAA, SOC 2',
                'Failover': 'One-click site failover',
                'Recovery Verification': 'Automated recovery point verification',
                'Deployment': 'On-premises',
                'Included In': 'Veeam Data Platform Premium',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Cyber Resilience
    // =====================================================================
    {
      nodeId: 'veeam-cyber-resilience',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Cyber Resilience',
      nameKo: '사이버 복원력',
      description: 'Ransomware incident response, Kubernetes-native data protection, and cyber security programs for enterprise resilience',
      descriptionKo: '엔터프라이즈 복원력을 위한 랜섬웨어 사고 대응, Kubernetes 네이티브 데이터 보호, 사이버 보안 프로그램',
      sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
      infraNodeTypes: ['backup'],
      children: [
        // -- Veeam Cyber Secure --
        {
          nodeId: 'veeam-cyber-secure',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Veeam Cyber Secure',
          nameKo: 'Veeam 사이버 시큐어',
          description: 'Comprehensive ransomware incident response program combining Veeam technology, expert support, and financial guarantee for rapid recovery',
          descriptionKo: '신속한 복구를 위해 Veeam 기술, 전문가 지원, 재정 보증을 결합한 종합 랜섬웨어 사고 대응 프로그램',
          sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
          infraNodeTypes: ['backup'],
          architectureRole: 'Ransomware Recovery & Incident Response',
          architectureRoleKo: '랜섬웨어 복구 및 사고 대응',
          recommendedFor: [
            'Enterprise ransomware recovery guarantee',
            'Pre-incident security posture assessment',
            'Post-incident rapid recovery support',
            'Cyber insurance risk reduction',
          ],
          recommendedForKo: [
            '엔터프라이즈 랜섬웨어 복구 보증',
            '사고 전 보안 태세 평가',
            '사고 후 신속한 복구 지원',
            '사이버 보험 리스크 감소',
          ],
          securityCapabilities: [
            'Pre-incident security posture review',
            'Dedicated incident response team',
            'Ransomware recovery financial guarantee',
            'Threat assessment and remediation guidance',
            'Integration with Veeam Data Platform threat detection',
          ],
          children: [
            {
              nodeId: 'veeam-cyber-secure-program',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Veeam Cyber Secure Program',
              nameKo: 'Veeam 사이버 시큐어 프로그램',
              description: 'Enterprise incident response program with dedicated CISO support, pre-incident assessments, 24/7 response team, and ransomware recovery financial guarantee',
              descriptionKo: '전담 CISO 지원, 사전 사고 평가, 24/7 대응팀, 랜섬웨어 복구 재정 보증을 갖춘 엔터프라이즈 사고 대응 프로그램',
              sourceUrl: 'https://www.veeam.com/products/veeam-data-platform.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Program Type': 'Incident response service',
                'Support': '24/7 dedicated incident response team',
                'Pre-Incident': 'Security posture assessment and hardening review',
                'Post-Incident': 'Expert-guided recovery and remediation',
                'Financial Guarantee': 'Ransomware recovery warranty',
                'Prerequisite': 'Veeam Data Platform Premium',
                'Deployment': 'Service-based (no software deployment)',
              },
              children: [],
            },
          ],
        },
        // -- Kasten by Veeam --
        {
          nodeId: 'veeam-kasten',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'Kasten by Veeam',
          nameKo: 'Kasten by Veeam',
          description: 'Kubernetes-native data protection platform providing application-aware backup, disaster recovery, and cross-cluster mobility for containerized workloads',
          descriptionKo: '컨테이너화된 워크로드를 위한 애플리케이션 인식 백업, 재해 복구, 크로스 클러스터 이동성을 제공하는 Kubernetes 네이티브 데이터 보호 플랫폼',
          sourceUrl: 'https://www.veeam.com/products/cloud/kubernetes-data-protection.html',
          infraNodeTypes: ['backup', 'kubernetes'],
          architectureRole: 'Kubernetes Data Protection & Application Mobility',
          architectureRoleKo: 'Kubernetes 데이터 보호 및 애플리케이션 이동성',
          recommendedFor: [
            'Kubernetes workload backup and disaster recovery',
            'Cloud-native application mobility across clusters',
            'Multi-cluster Kubernetes data protection',
            'KubeVirt VM protection alongside containers',
            'Compliance for containerized environments',
          ],
          recommendedForKo: [
            'Kubernetes 워크로드 백업 및 재해 복구',
            '클러스터 간 클라우드 네이티브 애플리케이션 이동성',
            '멀티 클러스터 Kubernetes 데이터 보호',
            '컨테이너와 함께 KubeVirt VM 보호',
            '컨테이너화된 환경의 컴플라이언스',
          ],
          supportedProtocols: [
            'Kubernetes API', 'CSI', 'S3', 'REST API',
          ],
          haFeatures: [
            'Multi-cluster centralized management',
            'Policy-driven automated protection',
            'Cross-cluster application mobility',
            'Granular and full application restore',
          ],
          securityCapabilities: [
            'End-to-end encryption',
            'Immutable backups',
            'Granular RBAC per application',
            'Multi-tenant environment support',
            'SIEM integration for threat detection',
            'Least-privilege permission model',
          ],
          children: [
            {
              nodeId: 'veeam-kasten-k10',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Kasten K10',
              nameKo: 'Kasten K10',
              description: 'Kubernetes-native backup and DR platform supporting EKS, AKS, GKE, OpenShift, Rancher, and 10+ distributions with Helm-based deployment and policy automation',
              descriptionKo: 'EKS, AKS, GKE, OpenShift, Rancher 및 10개 이상의 배포판을 지원하며 Helm 기반 배포 및 정책 자동화를 갖춘 Kubernetes 네이티브 백업 및 DR 플랫폼',
              sourceUrl: 'https://www.veeam.com/products/cloud/kubernetes-data-protection.html',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'container',
              specs: {
                'K8s Distributions': 'EKS, AKS, GKE, OpenShift, Rancher, Nutanix KE, DigitalOcean, K3S, Oracle OKE, upstream K8s',
                'Applications': 'MongoDB, PostgreSQL, MySQL, Elasticsearch, Kafka, Cassandra, Amazon RDS, SQL Server',
                'Storage Support': 'Block, File, Object (AWS, Azure, GCP, Ceph, MinIO, Pure, NetApp, 20+ CSI providers)',
                'Installation': 'Single Helm command or marketplace',
                'Management': 'Multi-cluster centralized dashboard',
                'Air-Gap Support': 'Offline/air-gapped installations supported',
                'KubeVirt Support': 'VM protection on OpenShift Virtualization',
                'Free Trial': 'Enterprise trial up to 500 nodes / 60 days',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
