/**
 * VMware by Broadcom -- Full Product Catalog
 *
 * Hierarchical product tree covering Cloud Infrastructure, Networking & Security,
 * App Platform, Management & Automation, End-User Computing, and Security categories.
 *
 * Data sourced from https://www.vmware.com
 * Last crawled: 2026-02-22
 */

import type { VendorCatalog } from '../types';

// ---------------------------------------------------------------------------
// VMware by Broadcom Product Catalog
// ---------------------------------------------------------------------------

export const vmwareCatalog: VendorCatalog = {
  vendorId: 'vmware',
  vendorName: 'VMware by Broadcom',
  vendorNameKo: 'VMware (브로드컴)',
  headquarters: 'Palo Alto, CA, USA',
  website: 'https://www.vmware.com',
  productPageUrl: 'https://www.vmware.com/products.html',
  depthStructure: ['category', 'product-line', 'edition'],
  depthStructureKo: ['카테고리', '제품 라인', '에디션'],
  lastCrawled: '2026-02-22',
  crawlSource: 'https://www.vmware.com/products.html',
  stats: { totalProducts: 41, maxDepth: 2, categoriesCount: 6 },
  products: [
    // =====================================================================
    // 1. Cloud Infrastructure
    // =====================================================================
    {
      nodeId: 'vmware-cloud-infrastructure',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Cloud Infrastructure',
      nameKo: '클라우드 인프라',
      description: 'Software-defined compute, storage, and networking for private and hybrid cloud deployments',
      descriptionKo: '프라이빗 및 하이브리드 클라우드 배포를 위한 소프트웨어 정의 컴퓨팅, 스토리지, 네트워킹',
      sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure.html',
      infraNodeTypes: ['vm', 'private-cloud'],
      children: [
        // -- VMware Cloud Foundation --
        {
          nodeId: 'vmware-vcf',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Cloud Foundation',
          nameKo: 'VMware 클라우드 파운데이션',
          description: 'Integrated SDDC platform combining vSphere, vSAN, NSX, and Aria Suite for full-stack private cloud infrastructure',
          descriptionKo: 'vSphere, vSAN, NSX, Aria Suite를 결합한 풀스택 프라이빗 클라우드 인프라용 통합 SDDC 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vmware-cloud-foundation',
          infraNodeTypes: ['vm', 'private-cloud'],
          architectureRole: 'Private Cloud / SDDC Foundation',
          architectureRoleKo: '프라이빗 클라우드 / SDDC 기반',
          recommendedFor: [
            'Enterprise private cloud deployment',
            'Hybrid cloud infrastructure with consistent operations',
            'Multi-site SDDC with lifecycle automation',
            'Consolidation of compute, storage, and networking into a single platform',
            'VMware-to-cloud migration with workload portability',
          ],
          recommendedForKo: [
            '엔터프라이즈 프라이빗 클라우드 배포',
            '일관된 운영을 갖춘 하이브리드 클라우드 인프라',
            '라이프사이클 자동화를 갖춘 멀티 사이트 SDDC',
            '컴퓨팅, 스토리지, 네트워킹을 단일 플랫폼으로 통합',
            '워크로드 이식성을 갖춘 VMware-클라우드 마이그레이션',
          ],
          supportedProtocols: [
            'vSphere API', 'REST API', 'NFS', 'iSCSI', 'Fibre Channel',
            'VXLAN', 'Geneve', 'BGP', 'OSPF', 'LACP', 'VLAN',
          ],
          haFeatures: [
            'vSphere HA with automatic VM restart',
            'vSAN stretched cluster for site-level resilience',
            'NSX multi-site networking',
            'SDDC Manager automated lifecycle management',
            'Proactive HA with hardware health monitoring',
          ],
          securityCapabilities: [
            'NSX Distributed Firewall for microsegmentation',
            'vSphere Trust Authority (TPM-based attestation)',
            'VM Encryption (AES-NI)',
            'vSAN data-at-rest encryption',
            'Role-based access control with vCenter SSO',
            'Secure Boot for ESXi hosts',
          ],
          children: [
            {
              nodeId: 'vmware-vcf-standard',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'VCF Standard',
              nameKo: 'VCF 스탠다드',
              description: 'Core SDDC stack with vSphere, vSAN, and NSX networking for private cloud compute, storage, and network virtualization',
              descriptionKo: '프라이빗 클라우드 컴퓨팅, 스토리지, 네트워크 가상화를 위한 vSphere, vSAN, NSX 네트워킹의 핵심 SDDC 스택',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vmware-cloud-foundation',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Included Components': 'vSphere Enterprise Plus, vSAN Enterprise, NSX Enterprise Plus, SDDC Manager',
                'Max Hosts per Cluster': '64',
                'Max VMs per Host': '1,024',
                'vSAN Max Capacity': 'Up to 4 PB per cluster',
                'NSX Networking': 'Distributed switching, routing, load balancing',
                'Lifecycle Management': 'SDDC Manager automated upgrades',
                'Deployment Model': 'On-premises bare-metal',
                'Minimum Hosts': '4 (consolidated) or 2+2 (management + workload)',
              },
              children: [],
            },
            {
              nodeId: 'vmware-vcf-advanced',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'VCF Advanced',
              nameKo: 'VCF 어드밴스드',
              description: 'Full SDDC stack with Aria automation suite for self-service provisioning, multi-cloud management, and infrastructure-as-code',
              descriptionKo: '셀프 서비스 프로비저닝, 멀티클라우드 관리, IaC를 위한 Aria 자동화 제품군을 포함한 풀 SDDC 스택',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vmware-cloud-foundation',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Included Components': 'VCF Standard + Aria Suite (Operations, Automation, Logs)',
                'Aria Automation': 'Infrastructure-as-code, self-service catalog, multi-cloud provisioning',
                'Aria Operations': 'Capacity planning, performance optimization, cost management',
                'Aria Operations for Logs': 'Centralized log analytics and troubleshooting',
                'Max Hosts per Cluster': '64',
                'Max VMs per Host': '1,024',
                'Deployment Model': 'On-premises bare-metal',
                'Multi-Cloud Support': 'AWS, Azure, GCP workload management via Aria',
              },
              children: [],
            },
          ],
        },
        // -- vSphere --
        {
          nodeId: 'vmware-vsphere',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware vSphere',
          nameKo: 'VMware vSphere',
          description: 'Industry-leading server virtualization platform with ESXi hypervisor and vCenter management for enterprise compute workloads',
          descriptionKo: '엔터프라이즈 컴퓨팅 워크로드를 위한 ESXi 하이퍼바이저 및 vCenter 관리를 갖춘 업계 선도적 서버 가상화 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsphere',
          infraNodeTypes: ['vm'],
          architectureRole: 'Compute Virtualization Layer',
          architectureRoleKo: '컴퓨팅 가상화 계층',
          recommendedFor: [
            'Enterprise server consolidation and virtualization',
            'Business-critical application hosting (databases, ERP, CRM)',
            'Development and test environment provisioning',
            'AI/ML workloads with GPU passthrough and DPU offloading',
            'Disaster recovery with vMotion and Storage vMotion',
          ],
          recommendedForKo: [
            '엔터프라이즈 서버 통합 및 가상화',
            '비즈니스 크리티컬 애플리케이션 호스팅 (데이터베이스, ERP, CRM)',
            '개발 및 테스트 환경 프로비저닝',
            'GPU 패스스루 및 DPU 오프로딩을 통한 AI/ML 워크로드',
            'vMotion 및 Storage vMotion을 통한 재해 복구',
          ],
          supportedProtocols: [
            'NFS v3/v4.1', 'iSCSI', 'Fibre Channel', 'FCoE',
            'VMFS', 'vSAN', 'RDMA/RoCE v2', 'NVMe-oF',
            'vSphere API', 'REST API', 'CIM/WBEM',
          ],
          haFeatures: [
            'vSphere HA with automatic VM restart',
            'vSphere Fault Tolerance (zero downtime for critical VMs)',
            'vMotion (live migration with zero downtime)',
            'Storage vMotion (live storage migration)',
            'Proactive HA with hardware health monitoring',
            'vSphere Replication for DR',
          ],
          securityCapabilities: [
            'vSphere Trust Authority (vTA) with TPM 2.0 attestation',
            'VM Encryption (AES-256-XTS)',
            'vMotion Encryption',
            'Secure Boot for ESXi and VMs',
            'vSphere Native Key Provider',
            'Identity Federation with ADFS/Okta/Entra ID',
          ],
          children: [
            {
              nodeId: 'vmware-vsphere-standard',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'vSphere Standard',
              nameKo: 'vSphere 스탠다드',
              description: 'Core hypervisor platform with ESXi and vCenter Server for basic server virtualization and management',
              descriptionKo: '기본 서버 가상화 및 관리를 위한 ESXi 및 vCenter 서버의 핵심 하이퍼바이저 플랫폼',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsphere',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Hypervisor': 'ESXi 8.0',
                'Max vCPUs per VM': '768',
                'Max RAM per VM': '24 TB',
                'Max Hosts per vCenter': '2,500',
                'Max VMs per Host': '1,024',
                'vMotion': 'Supported',
                'Storage vMotion': 'Supported',
                'HA': 'Supported',
                'DRS': 'Not included',
              },
              children: [],
            },
            {
              nodeId: 'vmware-vsphere-foundation',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'vSphere Foundation',
              nameKo: 'vSphere 파운데이션',
              description: 'vSphere with integrated vSAN storage for hyper-converged infrastructure without separate SAN/NAS',
              descriptionKo: '별도의 SAN/NAS 없이 하이퍼컨버지드 인프라를 위한 vSAN 스토리지가 통합된 vSphere',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsphere',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Hypervisor': 'ESXi 8.0',
                'Included Storage': 'vSAN 8',
                'Max vCPUs per VM': '768',
                'Max RAM per VM': '24 TB',
                'Max Hosts per vCenter': '2,500',
                'Max VMs per Host': '1,024',
                'HCI': 'vSAN-based hyper-converged storage',
                'vMotion': 'Supported',
                'HA': 'Supported',
              },
              children: [],
            },
            {
              nodeId: 'vmware-vsphere-enterprise-plus',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'vSphere Enterprise Plus',
              nameKo: 'vSphere 엔터프라이즈 플러스',
              description: 'Full-feature virtualization with DRS, Fault Tolerance, GPU/DPU passthrough, and advanced lifecycle management',
              descriptionKo: 'DRS, 내결함성, GPU/DPU 패스스루, 고급 라이프사이클 관리를 포함한 전체 기능 가상화',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsphere',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Hypervisor': 'ESXi 8.0',
                'Max vCPUs per VM': '768',
                'Max RAM per VM': '24 TB',
                'Max Hosts per vCenter': '2,500',
                'Max VMs per Host': '1,024',
                'DRS': 'Distributed Resource Scheduler for automatic load balancing',
                'Fault Tolerance': 'Zero downtime protection (up to 8 vCPUs)',
                'GPU Passthrough': 'NVIDIA vGPU, AMD MxGPU, Intel GVT-g',
                'DPU Support': 'NVIDIA BlueField, AMD Pensando, Intel IPU',
                'Lifecycle Manager': 'vSphere Lifecycle Manager (vLCM) with desired-state model',
              },
              children: [],
            },
          ],
        },
        // -- vSAN --
        {
          nodeId: 'vmware-vsan',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware vSAN',
          nameKo: 'VMware vSAN',
          description: 'Software-defined hyper-converged storage integrated with vSphere for flash-optimized, policy-driven data services',
          descriptionKo: '플래시 최적화, 정책 기반 데이터 서비스를 위해 vSphere와 통합된 소프트웨어 정의 하이퍼컨버지드 스토리지',
          sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsan',
          infraNodeTypes: ['storage', 'san-nas'],
          architectureRole: 'Hyper-Converged Storage Layer',
          architectureRoleKo: '하이퍼컨버지드 스토리지 계층',
          recommendedFor: [
            'Hyper-converged infrastructure replacing traditional SAN/NAS',
            'VDI and desktop storage with deduplication and compression',
            'Stretched cluster deployments for metro-area disaster recovery',
            'Edge and ROBO sites with 2-node vSAN clusters',
            'High-performance database storage with NVMe and RDMA',
          ],
          recommendedForKo: [
            '기존 SAN/NAS를 대체하는 하이퍼컨버지드 인프라',
            '중복 제거 및 압축을 갖춘 VDI 및 데스크톱 스토리지',
            '메트로 지역 재해 복구를 위한 스트레치 클러스터 배포',
            '2노드 vSAN 클러스터를 갖춘 엣지 및 ROBO 사이트',
            'NVMe 및 RDMA를 갖춘 고성능 데이터베이스 스토리지',
          ],
          supportedProtocols: [
            'vSAN', 'NFS v3/v4.1', 'iSCSI', 'RDMA/RoCE v2',
            'NVMe', 'vSphere API', 'REST API',
          ],
          haFeatures: [
            'vSAN stretched cluster (cross-site replication)',
            'Configurable failure tolerance (FTT 0-3)',
            'Automatic data rebalancing',
            'vSAN HCI Mesh for disaggregated storage sharing',
            'Witness appliance for 2-node clusters',
          ],
          securityCapabilities: [
            'Data-at-rest encryption (AES-256-XTS)',
            'Data-in-transit encryption',
            'FIPS 140-2 validated encryption',
            'vSAN Native Key Provider (no external KMS required)',
            'Secure Erase (cryptographic erase on decommission)',
          ],
          children: [
            {
              nodeId: 'vmware-vsan-enterprise',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'vSAN',
              nameKo: 'vSAN',
              description: 'Software-defined HCI storage with deduplication, compression, encryption, stretched clusters, and vSAN HCI Mesh',
              descriptionKo: '중복 제거, 압축, 암호화, 스트레치 클러스터, vSAN HCI 메시를 갖춘 소프트웨어 정의 HCI 스토리지',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/vsan',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Storage Architecture': 'Distributed object store with SPBM policy management',
                'Max Hosts per Cluster': '64',
                'Max Capacity per Cluster': '4 PB',
                'Deduplication & Compression': 'Supported (up to 7:1 reduction)',
                'Encryption': 'Data-at-rest and data-in-transit (AES-256-XTS)',
                'Stretched Cluster': 'Supported for metro DR (up to 100ms RTT)',
                'HCI Mesh': 'Cross-cluster storage sharing without data migration',
                'RAID Levels': 'RAID-1, RAID-5/6 (erasure coding)',
                'Min Hosts': '2 (with witness) or 3 (standard)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 2. Networking & Security
    // =====================================================================
    {
      nodeId: 'vmware-networking-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Networking & Security',
      nameKo: '네트워킹 및 보안',
      description: 'Software-defined networking, microsegmentation, and advanced load balancing for data center and multi-cloud environments',
      descriptionKo: '데이터 센터 및 멀티클라우드 환경을 위한 소프트웨어 정의 네트워킹, 마이크로세그멘테이션, 고급 로드 밸런싱',
      sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx',
      infraNodeTypes: ['switch-l3', 'firewall'],
      children: [
        // -- NSX --
        {
          nodeId: 'vmware-nsx',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware NSX',
          nameKo: 'VMware NSX',
          description: 'Network virtualization and security platform providing distributed switching, routing, firewalling, and load balancing',
          descriptionKo: '분산 스위칭, 라우팅, 방화벽, 로드 밸런싱을 제공하는 네트워크 가상화 및 보안 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx',
          infraNodeTypes: ['switch-l3', 'firewall'],
          architectureRole: 'Network Virtualization & Microsegmentation',
          architectureRoleKo: '네트워크 가상화 및 마이크로세그멘테이션',
          recommendedFor: [
            'Data center network virtualization with overlay networking',
            'Zero-trust microsegmentation for east-west traffic',
            'Multi-tier application network isolation',
            'Network security policy automation',
            'Hybrid cloud networking with consistent policy',
          ],
          recommendedForKo: [
            '오버레이 네트워킹을 갖춘 데이터 센터 네트워크 가상화',
            '동-서 트래픽을 위한 제로 트러스트 마이크로세그멘테이션',
            '멀티 티어 애플리케이션 네트워크 격리',
            '네트워크 보안 정책 자동화',
            '일관된 정책을 갖춘 하이브리드 클라우드 네트워킹',
          ],
          supportedProtocols: [
            'Geneve', 'VXLAN', 'BGP', 'OSPF', 'ECMP',
            'BFD', 'DHCP', 'DNS', 'NAT', 'IPSec VPN',
            'SSL VPN', 'REST API', 'LACP', 'VLAN',
          ],
          haFeatures: [
            'Active-active edge cluster deployment',
            'NSX Manager cluster (3-node)',
            'Stateful failover for distributed firewall',
            'Multi-site federation with stretched networking',
            'BFD-based fast failover detection',
          ],
          securityCapabilities: [
            'Distributed Firewall (L2-L7 stateful filtering)',
            'Context-aware microsegmentation by VM identity',
            'IDS/IPS (NSX Distributed IDS)',
            'URL filtering and FQDN whitelisting',
            'Endpoint protection (Guest Introspection)',
            'TLS inspection and decryption',
          ],
          children: [
            {
              nodeId: 'vmware-nsx-networking',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'NSX Networking',
              nameKo: 'NSX 네트워킹',
              description: 'Virtual switching, routing, and load balancing for software-defined data center networking',
              descriptionKo: '소프트웨어 정의 데이터 센터 네트워킹을 위한 가상 스위칭, 라우팅, 로드 밸런싱',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              infraNodeTypes: ['switch-l3'],
              specs: {
                'Virtual Switching': 'N-VDS (NSX Virtual Distributed Switch)',
                'Routing': 'Tier-0 and Tier-1 distributed routing (BGP, OSPF, ECMP)',
                'Load Balancing': 'L4 TCP/UDP load balancing',
                'VPN': 'IPSec and SSL VPN gateway',
                'NAT': 'SNAT, DNAT, Reflexive NAT',
                'DHCP/DNS': 'Built-in DHCP relay and DNS forwarding',
                'Max Logical Switches': '10,000 per NSX Manager',
                'Overlay Protocol': 'Geneve encapsulation',
              },
              children: [],
            },
            {
              nodeId: 'vmware-nsx-dfw',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'NSX Distributed Firewall',
              nameKo: 'NSX 분산 방화벽',
              description: 'Kernel-level microsegmentation firewall enforced at every vNIC for zero-trust east-west security',
              descriptionKo: '제로 트러스트 동-서 보안을 위해 모든 vNIC에서 적용되는 커널 수준 마이크로세그멘테이션 방화벽',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              infraNodeTypes: ['firewall'],
              specs: {
                'Firewall Type': 'Distributed stateful L2-L7 firewall',
                'Enforcement Point': 'Hypervisor kernel (vNIC level)',
                'Throughput': 'Near-line-rate (scales with host count)',
                'Policy Objects': 'VM, IP, MAC, AD group, tag-based',
                'IDS/IPS': 'Distributed IDS with signature-based detection',
                'URL Filtering': 'FQDN-based allow/deny rules',
                'Max Rules per Section': '1,000',
                'Max Sections': '10,000',
              },
              children: [],
            },
            {
              nodeId: 'vmware-nsx-alb',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'NSX Advanced Load Balancer (Avi)',
              nameKo: 'NSX 고급 로드 밸런서 (Avi)',
              description: 'Software-defined L4-L7 load balancer with auto-scaling, WAF, and application analytics (formerly Avi Networks)',
              descriptionKo: '자동 확장, WAF, 애플리케이션 분석을 갖춘 소프트웨어 정의 L4-L7 로드 밸런서 (구 Avi Networks)',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx-advanced-load-balancer',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              infraNodeTypes: ['load-balancer'],
              specs: {
                'Load Balancing': 'L4-L7 with SSL offloading',
                'WAF': 'Integrated Web Application Firewall (OWASP CRS)',
                'Auto-Scaling': 'Elastic Service Engine scaling based on demand',
                'Analytics': 'Real-time application performance analytics',
                'Multi-Cloud': 'VMware, AWS, Azure, GCP, OpenStack, Kubernetes',
                'Max Virtual Services': '1,000+ per Controller',
                'SSL/TLS': 'TLS 1.3, hardware SSL offload, certificate management',
                'Health Monitoring': '20+ health check types including custom scripts',
              },
              children: [],
            },
          ],
        },
        // -- NSX+ --
        {
          nodeId: 'vmware-nsx-plus',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware NSX+',
          nameKo: 'VMware NSX+',
          description: 'Cloud-delivered multi-cloud networking and security service extending NSX capabilities across cloud environments',
          descriptionKo: '클라우드 환경 전반에 NSX 기능을 확장하는 클라우드 제공 멀티클라우드 네트워킹 및 보안 서비스',
          sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx-plus',
          infraNodeTypes: ['switch-l3', 'firewall'],
          architectureRole: 'Multi-Cloud Networking & Security',
          architectureRoleKo: '멀티클라우드 네트워킹 및 보안',
          recommendedFor: [
            'Multi-cloud network connectivity (AWS, Azure, GCP)',
            'Consistent security policy across cloud environments',
            'Cloud-native distributed firewall and microsegmentation',
            'Centralized multi-cloud network operations',
          ],
          recommendedForKo: [
            '멀티클라우드 네트워크 연결 (AWS, Azure, GCP)',
            '클라우드 환경 전반에 일관된 보안 정책',
            '클라우드 네이티브 분산 방화벽 및 마이크로세그멘테이션',
            '중앙 집중식 멀티클라우드 네트워크 운영',
          ],
          supportedProtocols: [
            'Geneve', 'BGP', 'IPSec VPN', 'REST API',
            'AWS Transit Gateway', 'Azure VNet Peering', 'GCP Cloud Interconnect',
          ],
          haFeatures: [
            'Cloud-managed control plane (SaaS)',
            'Multi-region active-active networking',
            'Automated failover across cloud regions',
          ],
          securityCapabilities: [
            'Cloud-native distributed firewall',
            'Microsegmentation across multi-cloud VMs and containers',
            'Centralized policy management',
            'Threat intelligence integration',
          ],
          children: [
            {
              nodeId: 'vmware-nsx-plus-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'NSX+',
              nameKo: 'NSX+',
              description: 'SaaS-delivered multi-cloud networking and security with centralized management, distributed firewall, and cross-cloud connectivity',
              descriptionKo: '중앙 관리, 분산 방화벽, 크로스 클라우드 연결을 갖춘 SaaS 제공 멀티클라우드 네트워킹 및 보안',
              sourceUrl: 'https://www.vmware.com/products/cloud-infrastructure/nsx-plus',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Delivery Model': 'SaaS (cloud-managed)',
                'Supported Clouds': 'AWS, Azure, GCP',
                'Distributed Firewall': 'Multi-cloud microsegmentation',
                'Connectivity': 'Cross-cloud VPN and transit networking',
                'Policy Management': 'Centralized multi-cloud policy console',
                'Monitoring': 'Cloud-native flow visibility and analytics',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 3. App Platform
    // =====================================================================
    {
      nodeId: 'vmware-app-platform',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'App Platform',
      nameKo: '앱 플랫폼',
      description: 'Kubernetes and application platform services for building, running, and managing modern cloud-native applications',
      descriptionKo: '최신 클라우드 네이티브 애플리케이션의 빌드, 실행, 관리를 위한 쿠버네티스 및 애플리케이션 플랫폼 서비스',
      sourceUrl: 'https://www.vmware.com/products/app-platform',
      infraNodeTypes: ['kubernetes', 'container'],
      children: [
        // -- Tanzu Platform --
        {
          nodeId: 'vmware-tanzu',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Tanzu Platform',
          nameKo: 'VMware Tanzu 플랫폼',
          description: 'Enterprise Kubernetes management platform for multi-cluster operations, developer self-service, and application lifecycle management',
          descriptionKo: '멀티클러스터 운영, 개발자 셀프 서비스, 애플리케이션 라이프사이클 관리를 위한 엔터프라이즈 쿠버네티스 관리 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/app-platform/tanzu',
          infraNodeTypes: ['kubernetes', 'container'],
          architectureRole: 'Kubernetes Management & App Platform',
          architectureRoleKo: '쿠버네티스 관리 및 앱 플랫폼',
          recommendedFor: [
            'Multi-cluster Kubernetes fleet management',
            'Enterprise container platform standardization',
            'Developer self-service portal for Kubernetes namespaces',
            'Application modernization and microservices migration',
            'Hybrid cloud Kubernetes across on-premises and public cloud',
          ],
          recommendedForKo: [
            '멀티클러스터 쿠버네티스 플릿 관리',
            '엔터프라이즈 컨테이너 플랫폼 표준화',
            '쿠버네티스 네임스페이스를 위한 개발자 셀프 서비스 포털',
            '애플리케이션 현대화 및 마이크로서비스 마이그레이션',
            '온프레미스 및 퍼블릭 클라우드 전반의 하이브리드 클라우드 쿠버네티스',
          ],
          supportedProtocols: [
            'Kubernetes API', 'Helm', 'Carvel', 'OCI Registry',
            'gRPC', 'REST API', 'Prometheus', 'OpenTelemetry',
          ],
          haFeatures: [
            'Multi-cluster management with centralized control',
            'Automated cluster lifecycle management',
            'Self-healing Kubernetes node pools',
            'Cross-cluster application failover',
          ],
          securityCapabilities: [
            'Kubernetes RBAC with enterprise identity integration',
            'Policy-as-code with OPA/Gatekeeper',
            'Container image scanning and signing',
            'Network policy enforcement',
            'Pod security standards enforcement',
          ],
          children: [
            {
              nodeId: 'vmware-tanzu-platform',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Tanzu Platform',
              nameKo: 'Tanzu 플랫폼',
              description: 'Unified Kubernetes management with multi-cluster operations, supply chain security, and developer portal',
              descriptionKo: '멀티클러스터 운영, 공급망 보안, 개발자 포털을 갖춘 통합 쿠버네티스 관리',
              sourceUrl: 'https://www.vmware.com/products/app-platform/tanzu',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Kubernetes Distributions': 'TKG, EKS, AKS, GKE, OpenShift, Rancher',
                'Cluster Management': 'Centralized multi-cluster lifecycle operations',
                'Developer Portal': 'Self-service application deployment and namespace management',
                'Supply Chain': 'Secure software supply chain with image signing and scanning',
                'Observability': 'Built-in Prometheus, Grafana, and distributed tracing',
                'GitOps': 'Flux CD-based continuous delivery',
              },
              children: [],
            },
            {
              nodeId: 'vmware-tanzu-application-service',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Tanzu Application Service',
              nameKo: 'Tanzu 애플리케이션 서비스',
              description: 'Cloud Foundry-based PaaS for rapid application deployment with buildpacks, auto-scaling, and zero-downtime rolling updates',
              descriptionKo: '빌드팩, 자동 확장, 제로 다운타임 롤링 업데이트를 갖춘 빠른 애플리케이션 배포를 위한 Cloud Foundry 기반 PaaS',
              sourceUrl: 'https://www.vmware.com/products/app-platform/tanzu-application-service',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Platform': 'Cloud Foundry (cf push model)',
                'Buildpacks': 'Java, .NET, Node.js, Go, Python, Ruby, PHP',
                'Auto-Scaling': 'CPU/memory/HTTP-based application auto-scaling',
                'Deployment': 'Blue-green and rolling deployments with zero downtime',
                'Service Mesh': 'Built-in Envoy-based service mesh',
                'Logging': 'Centralized log aggregation (Loggregator)',
              },
              children: [],
            },
            {
              nodeId: 'vmware-tanzu-spring-runtime',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Tanzu Spring Runtime',
              nameKo: 'Tanzu 스프링 런타임',
              description: 'Commercial Spring Boot and Spring Framework support with CVE patches, LTS releases, and enterprise SLA',
              descriptionKo: 'CVE 패치, LTS 릴리스, 엔터프라이즈 SLA를 갖춘 상용 Spring Boot 및 Spring Framework 지원',
              sourceUrl: 'https://www.vmware.com/products/app-platform/spring-runtime',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Frameworks': 'Spring Boot, Spring Framework, Spring Cloud, Spring Security',
                'LTS Support': 'Extended LTS releases beyond open-source EOL',
                'CVE Patching': 'Priority security patches with SLA',
                'Compatibility': 'JDK 8, 11, 17, 21 (OpenJDK and commercial JDKs)',
                'Observability': 'Spring Boot Actuator, Micrometer, Wavefront integration',
                'Support SLA': '24/7 enterprise support with 1-hour critical response',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 4. Management & Automation
    // =====================================================================
    {
      nodeId: 'vmware-management-automation',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Management & Automation',
      nameKo: '관리 및 자동화',
      description: 'Multi-cloud operations management, infrastructure automation, and log analytics for IT operations',
      descriptionKo: 'IT 운영을 위한 멀티클라우드 운영 관리, 인프라 자동화, 로그 분석',
      sourceUrl: 'https://www.vmware.com/products/aria',
      infraNodeTypes: ['grafana'],
      children: [
        // -- Aria Operations --
        {
          nodeId: 'vmware-aria-operations',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Aria Operations',
          nameKo: 'VMware Aria 오퍼레이션스',
          description: 'AI-driven multi-cloud monitoring, capacity planning, and cost optimization platform for infrastructure and applications',
          descriptionKo: '인프라 및 애플리케이션을 위한 AI 기반 멀티클라우드 모니터링, 용량 계획, 비용 최적화 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/aria-operations',
          infraNodeTypes: ['grafana'],
          architectureRole: 'Multi-Cloud Monitoring & Operations',
          architectureRoleKo: '멀티클라우드 모니터링 및 운영',
          recommendedFor: [
            'VMware environment performance monitoring and alerting',
            'Multi-cloud capacity planning and right-sizing',
            'Infrastructure cost optimization (showback/chargeback)',
            'Compliance and configuration drift detection',
            'Proactive troubleshooting with AI/ML anomaly detection',
          ],
          recommendedForKo: [
            'VMware 환경 성능 모니터링 및 알림',
            '멀티클라우드 용량 계획 및 적정 규모 산정',
            '인프라 비용 최적화 (쇼백/차지백)',
            '컴플라이언스 및 구성 드리프트 감지',
            'AI/ML 이상 감지를 통한 사전 문제 해결',
          ],
          supportedProtocols: [
            'vSphere API', 'REST API', 'SNMP', 'SMTP',
            'Syslog', 'Webhook', 'ServiceNow API',
          ],
          haFeatures: [
            'Clustered analytics nodes for HA',
            'Continuous availability with automated failover',
            'Multi-node collector redundancy',
          ],
          securityCapabilities: [
            'Regulatory compliance dashboards (PCI, HIPAA, DISA STIG)',
            'Configuration drift detection and remediation',
            'RBAC with vCenter SSO integration',
          ],
          children: [
            {
              nodeId: 'vmware-aria-operations-standard',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Aria Operations',
              nameKo: 'Aria 오퍼레이션스',
              description: 'Multi-cloud monitoring and capacity planning with AI-driven anomaly detection, right-sizing, and cost optimization',
              descriptionKo: 'AI 기반 이상 감지, 적정 규모 산정, 비용 최적화를 갖춘 멀티클라우드 모니터링 및 용량 계획',
              sourceUrl: 'https://www.vmware.com/products/aria-operations',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Monitoring Scope': 'vSphere, vSAN, NSX, AWS, Azure, GCP, Kubernetes',
                'AI/ML Analytics': 'Predictive capacity, anomaly detection, what-if analysis',
                'Dashboards': '100+ pre-built dashboards, custom dashboard builder',
                'Cost Management': 'Showback, chargeback, cost optimization recommendations',
                'Compliance': 'PCI-DSS, HIPAA, DISA STIG, ISO 27001, CIS benchmarks',
                'Max Monitored Objects': '100,000+ per analytics cluster',
                'Data Retention': 'Up to 6 months (configurable)',
              },
              children: [],
            },
            {
              nodeId: 'vmware-aria-operations-logs',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Aria Operations for Logs',
              nameKo: 'Aria 오퍼레이션스 포 로그',
              description: 'Centralized log analytics for VMware and multi-cloud environments with real-time search, alerting, and integration with Aria Operations',
              descriptionKo: '실시간 검색, 알림, Aria Operations 통합을 갖춘 VMware 및 멀티클라우드 환경을 위한 중앙 집중식 로그 분석',
              sourceUrl: 'https://www.vmware.com/products/aria-operations-for-logs',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Log Sources': 'vSphere, NSX, vSAN, Linux, Windows, AWS CloudWatch, containers',
                'Ingestion Rate': 'Up to 125,000 events per second per cluster',
                'Search': 'Real-time full-text search with regex and structured queries',
                'Alerting': 'Threshold and anomaly-based alerts with webhook/email/SNMP',
                'Integration': 'Native Aria Operations context-aware launch',
                'Retention': 'Configurable retention with archive to NFS/object storage',
              },
              children: [],
            },
          ],
        },
        // -- Aria Automation --
        {
          nodeId: 'vmware-aria-automation',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Aria Automation',
          nameKo: 'VMware Aria 오토메이션',
          description: 'Multi-cloud infrastructure-as-code and self-service automation platform for provisioning, governance, and day-2 operations',
          descriptionKo: '프로비저닝, 거버넌스, Day-2 운영을 위한 멀티클라우드 IaC 및 셀프 서비스 자동화 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/aria-automation',
          infraNodeTypes: ['grafana'],
          architectureRole: 'Infrastructure Automation & Self-Service',
          architectureRoleKo: '인프라 자동화 및 셀프 서비스',
          recommendedFor: [
            'Multi-cloud infrastructure provisioning automation',
            'Developer self-service portal with approval workflows',
            'Governance and compliance enforcement via policy-as-code',
            'Day-2 operations automation (resize, snapshot, decommission)',
            'Terraform and Ansible orchestration integration',
          ],
          recommendedForKo: [
            '멀티클라우드 인프라 프로비저닝 자동화',
            '승인 워크플로우를 갖춘 개발자 셀프 서비스 포털',
            '코드형 정책을 통한 거버넌스 및 컴플라이언스 적용',
            'Day-2 운영 자동화 (크기 조정, 스냅샷, 해제)',
            'Terraform 및 Ansible 오케스트레이션 통합',
          ],
          supportedProtocols: [
            'REST API', 'Terraform Provider', 'Ansible',
            'vSphere API', 'AWS API', 'Azure API', 'GCP API',
            'Kubernetes API', 'SAML', 'LDAP',
          ],
          haFeatures: [
            'Clustered deployment for high availability',
            'Load-balanced API endpoints',
            'External PostgreSQL HA for catalog persistence',
          ],
          securityCapabilities: [
            'Policy-as-code guardrails for multi-cloud provisioning',
            'RBAC with project-level isolation',
            'Approval workflow with multi-level sign-off',
            'Credential management with HashiCorp Vault integration',
          ],
          children: [
            {
              nodeId: 'vmware-aria-automation-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Aria Automation',
              nameKo: 'Aria 오토메이션',
              description: 'Infrastructure-as-code platform with self-service catalog, policy governance, and multi-cloud provisioning for vSphere, AWS, Azure, and GCP',
              descriptionKo: 'vSphere, AWS, Azure, GCP를 위한 셀프 서비스 카탈로그, 정책 거버넌스, 멀티클라우드 프로비저닝을 갖춘 IaC 플랫폼',
              sourceUrl: 'https://www.vmware.com/products/aria-automation',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Supported Clouds': 'vSphere, AWS, Azure, GCP, VMware Cloud on AWS',
                'IaC Engine': 'Cloud Assembly with YAML blueprints + Terraform integration',
                'Service Catalog': 'Self-service portal with custom forms and approval workflows',
                'Governance': 'Policy-as-code with ABX extensibility (Python, Node.js, PowerShell)',
                'Orchestration': 'Workflow engine (vRealize Orchestrator) with 10,000+ pre-built actions',
                'Config Management': 'SaltStack-based configuration compliance and drift remediation',
              },
              children: [],
            },
          ],
        },
        // -- Aria Guard --
        {
          nodeId: 'vmware-aria-guard',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Aria Guard',
          nameKo: 'VMware Aria 가드',
          description: 'Ransomware recovery orchestration platform with isolated recovery environments and automated recovery plan validation',
          descriptionKo: '격리된 복구 환경 및 자동화된 복구 계획 검증을 갖춘 랜섬웨어 복구 오케스트레이션 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/aria-guard',
          infraNodeTypes: ['grafana'],
          architectureRole: 'Ransomware Recovery Orchestration',
          architectureRoleKo: '랜섬웨어 복구 오케스트레이션',
          recommendedFor: [
            'Ransomware recovery planning and automated validation',
            'Isolated recovery environment (IRE) orchestration',
            'Business continuity and disaster recovery testing',
            'Compliance-driven recovery documentation',
          ],
          recommendedForKo: [
            '랜섬웨어 복구 계획 및 자동화된 검증',
            '격리된 복구 환경 (IRE) 오케스트레이션',
            '비즈니스 연속성 및 재해 복구 테스트',
            '컴플라이언스 기반 복구 문서화',
          ],
          supportedProtocols: [
            'vSphere API', 'REST API', 'SAML', 'LDAP',
          ],
          haFeatures: [
            'Automated recovery plan validation',
            'Air-gapped recovery environment orchestration',
            'Scheduled recovery testing workflows',
          ],
          securityCapabilities: [
            'Isolated Recovery Environment (IRE) with network isolation',
            'Malware scanning before recovery',
            'Immutable recovery snapshots',
            'Audit-ready recovery documentation',
          ],
          children: [
            {
              nodeId: 'vmware-aria-guard-edition',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Aria Guard',
              nameKo: 'Aria 가드',
              description: 'Ransomware recovery orchestration with automated IRE provisioning, recovery plan testing, and compliance reporting',
              descriptionKo: '자동화된 IRE 프로비저닝, 복구 계획 테스트, 컴플라이언스 보고를 갖춘 랜섬웨어 복구 오케스트레이션',
              sourceUrl: 'https://www.vmware.com/products/aria-guard',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Recovery Environment': 'Automated Isolated Recovery Environment (IRE) provisioning',
                'Recovery Testing': 'Scheduled and on-demand recovery plan validation',
                'Malware Scanning': 'Pre-recovery malware and integrity verification',
                'Reporting': 'Audit-ready compliance documentation for NIST, SOC 2',
                'Integration': 'vSphere, vSAN, NSX for network-isolated recovery',
                'Recovery Orchestration': 'Step-by-step guided recovery with rollback support',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 5. End-User Computing
    // =====================================================================
    {
      nodeId: 'vmware-end-user-computing',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'End-User Computing',
      nameKo: '엔드유저 컴퓨팅',
      description: 'Digital workspace, unified endpoint management, and virtual desktop infrastructure for the modern workforce',
      descriptionKo: '현대 워크포스를 위한 디지털 워크스페이스, 통합 엔드포인트 관리, 가상 데스크톱 인프라',
      sourceUrl: 'https://www.vmware.com/products/workspace-one',
      infraNodeTypes: ['vm', 'sso'],
      children: [
        // -- Workspace ONE --
        {
          nodeId: 'vmware-workspace-one',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Workspace ONE',
          nameKo: 'VMware 워크스페이스 원',
          description: 'Intelligence-driven digital workspace platform integrating unified endpoint management, SSO, and conditional access',
          descriptionKo: '통합 엔드포인트 관리, SSO, 조건부 접근을 통합한 인텔리전스 기반 디지털 워크스페이스 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/workspace-one',
          infraNodeTypes: ['sso', 'iam'],
          architectureRole: 'Digital Workspace & Endpoint Management',
          architectureRoleKo: '디지털 워크스페이스 및 엔드포인트 관리',
          recommendedFor: [
            'Enterprise unified endpoint management (mobile, desktop, IoT)',
            'Zero-trust conditional access enforcement',
            'Single sign-on across SaaS and on-premises applications',
            'BYOD and remote workforce enablement',
            'Endpoint compliance and automated remediation',
          ],
          recommendedForKo: [
            '엔터프라이즈 통합 엔드포인트 관리 (모바일, 데스크톱, IoT)',
            '제로 트러스트 조건부 접근 적용',
            'SaaS 및 온프레미스 애플리케이션 전반의 싱글 사인온',
            'BYOD 및 원격 워크포스 지원',
            '엔드포인트 컴플라이언스 및 자동 교정',
          ],
          supportedProtocols: [
            'SAML 2.0', 'OAuth 2.0', 'OIDC', 'SCIM',
            'REST API', 'LDAP', 'Kerberos', 'RADIUS',
            'Apple MDM', 'Android Enterprise', 'Windows MDM',
          ],
          haFeatures: [
            'Cloud-hosted SaaS with 99.9% SLA',
            'Multi-region deployment for global workforce',
            'On-premises HA with load-balanced UAG appliances',
          ],
          securityCapabilities: [
            'Conditional access with risk-based authentication',
            'Certificate-based authentication',
            'Device compliance posture checks',
            'Data Loss Prevention (DLP) policies',
            'Remote wipe and selective wipe',
            'Tunnel VPN per-app micro-tunnel',
          ],
          children: [
            {
              nodeId: 'vmware-workspace-one-uem',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Workspace ONE UEM',
              nameKo: '워크스페이스 원 UEM',
              description: 'Unified endpoint management for mobile, desktop, rugged, and IoT devices with OTA provisioning and compliance enforcement',
              descriptionKo: 'OTA 프로비저닝 및 컴플라이언스 적용을 갖춘 모바일, 데스크톱, 러기드, IoT 디바이스를 위한 통합 엔드포인트 관리',
              sourceUrl: 'https://www.vmware.com/products/workspace-one/unified-endpoint-management',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Supported Platforms': 'iOS, Android, Windows 10/11, macOS, ChromeOS, Linux, tvOS',
                'Device Management': 'MDM, MAM, MCM, MEM (full EMM suite)',
                'Enrollment': 'Zero-touch (Apple DEP, Android Zero-Touch, Windows Autopilot)',
                'Compliance Engine': 'Real-time device posture checks with automated actions',
                'App Management': 'Enterprise app catalog, app wrapping, per-app VPN',
                'Max Managed Devices': '500,000+ per deployment',
                'Deployment': 'SaaS (cloud-hosted) or on-premises',
              },
              children: [],
            },
            {
              nodeId: 'vmware-workspace-one-access',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Workspace ONE Access',
              nameKo: '워크스페이스 원 액세스',
              description: 'Identity and access management with SSO, MFA, and conditional access for enterprise applications',
              descriptionKo: '엔터프라이즈 애플리케이션을 위한 SSO, MFA, 조건부 접근을 갖춘 ID 및 접근 관리',
              sourceUrl: 'https://www.vmware.com/products/workspace-one/access',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              infraNodeTypes: ['sso'],
              specs: {
                'SSO': 'SAML 2.0, OAuth 2.0, OpenID Connect, WS-Federation',
                'MFA': 'VMware Verify, TOTP, FIDO2/WebAuthn, third-party MFA',
                'Conditional Access': 'Device compliance, network location, risk score policies',
                'Directory Integration': 'Active Directory, LDAP, Okta, Azure AD/Entra ID',
                'App Catalog': 'Unified portal for SaaS, virtual, and on-premises apps',
                'Max Users': 'Unlimited (cloud SaaS tier)',
              },
              children: [],
            },
          ],
        },
        // -- Horizon --
        {
          nodeId: 'vmware-horizon',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Horizon',
          nameKo: 'VMware 호라이즌',
          description: 'Virtual desktop and application delivery platform for secure remote access with on-premises, cloud, or hybrid deployment',
          descriptionKo: '온프레미스, 클라우드, 하이브리드 배포를 통한 안전한 원격 접근을 위한 가상 데스크톱 및 애플리케이션 전달 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/desktop-hypervisor/horizon',
          infraNodeTypes: ['vm'],
          architectureRole: 'Virtual Desktop Infrastructure (VDI)',
          architectureRoleKo: '가상 데스크톱 인프라 (VDI)',
          recommendedFor: [
            'Enterprise VDI for secure remote workforce',
            'GPU-accelerated virtual desktops for CAD/engineering',
            'Desktop-as-a-Service (DaaS) on public cloud',
            'RDSH application publishing for legacy apps',
            'Healthcare and financial services secure desktop delivery',
          ],
          recommendedForKo: [
            '안전한 원격 워크포스를 위한 엔터프라이즈 VDI',
            'CAD/엔지니어링을 위한 GPU 가속 가상 데스크톱',
            '퍼블릭 클라우드의 서비스형 데스크톱 (DaaS)',
            '레거시 앱을 위한 RDSH 애플리케이션 퍼블리싱',
            '의료 및 금융 서비스 보안 데스크톱 전달',
          ],
          supportedProtocols: [
            'Blast Extreme', 'PCoIP', 'RDP',
            'REST API', 'SAML 2.0', 'RADIUS',
          ],
          haFeatures: [
            'Connection Server HA with load balancing',
            'Cloud Pod Architecture for multi-site federation',
            'Instant Clone technology for fast desktop provisioning',
            'vSphere HA integration for desktop pools',
          ],
          securityCapabilities: [
            'Blast Extreme HTTPS/TLS encryption',
            'Smart card and certificate authentication',
            'Two-factor authentication (RADIUS, RSA SecurID)',
            'USB and clipboard redirection policies',
            'Watermarking for data leak prevention',
          ],
          children: [
            {
              nodeId: 'vmware-horizon-8',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Horizon 8',
              nameKo: '호라이즌 8',
              description: 'Full-featured VDI and DaaS platform with Instant Clone, Blast Extreme protocol, and multi-cloud deployment options',
              descriptionKo: 'Instant Clone, Blast Extreme 프로토콜, 멀티클라우드 배포 옵션을 갖춘 전체 기능 VDI 및 DaaS 플랫폼',
              sourceUrl: 'https://www.vmware.com/products/desktop-hypervisor/horizon',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Desktop Types': 'Full Clone, Instant Clone, Linked Clone, RDSH Published',
                'Display Protocol': 'Blast Extreme (adaptive codec, H.264/H.265, UDP optimization)',
                'GPU Support': 'NVIDIA vGPU, AMD MxGPU, Intel GVT-g',
                'Max Desktops per Pod': '12,000',
                'Cloud Pod Federation': 'Up to 250,000 desktops across 50 pods',
                'DaaS': 'Horizon Cloud on Azure, AWS, GCP',
                'Multimedia': 'Skype/Teams/Zoom optimization (offload to client)',
                'Printing': 'VMware Integrated Printing (no print driver installation)',
              },
              children: [],
            },
          ],
        },
      ],
    },

    // =====================================================================
    // 6. Security
    // =====================================================================
    {
      nodeId: 'vmware-security',
      depth: 0,
      depthLabel: 'Category',
      depthLabelKo: '카테고리',
      name: 'Security',
      nameKo: '보안',
      description: 'Endpoint detection and response, workload security, and application control for enterprise threat protection',
      descriptionKo: '엔터프라이즈 위협 보호를 위한 엔드포인트 탐지 및 대응, 워크로드 보안, 애플리케이션 제어',
      sourceUrl: 'https://www.vmware.com/products/carbon-black',
      infraNodeTypes: ['firewall'],
      children: [
        // -- Carbon Black --
        {
          nodeId: 'vmware-carbon-black',
          depth: 1,
          depthLabel: 'Product Line',
          depthLabelKo: '제품 라인',
          name: 'VMware Carbon Black',
          nameKo: 'VMware 카본 블랙',
          description: 'Cloud-native endpoint and workload security platform with EDR, NGAV, and behavioral analytics for advanced threat protection',
          descriptionKo: '고급 위협 보호를 위한 EDR, NGAV, 행동 분석을 갖춘 클라우드 네이티브 엔드포인트 및 워크로드 보안 플랫폼',
          sourceUrl: 'https://www.vmware.com/products/carbon-black',
          infraNodeTypes: ['firewall', 'ids-ips'],
          architectureRole: 'Endpoint & Workload Security',
          architectureRoleKo: '엔드포인트 및 워크로드 보안',
          recommendedFor: [
            'Enterprise endpoint detection and response (EDR)',
            'Next-generation antivirus for advanced threats',
            'Server and container workload hardening',
            'Application whitelisting for critical systems',
            'SOC investigation and threat hunting',
          ],
          recommendedForKo: [
            '엔터프라이즈 엔드포인트 탐지 및 대응 (EDR)',
            '고급 위협을 위한 차세대 안티바이러스',
            '서버 및 컨테이너 워크로드 보안 강화',
            '중요 시스템을 위한 애플리케이션 화이트리스팅',
            'SOC 조사 및 위협 헌팅',
          ],
          supportedProtocols: [
            'REST API', 'Syslog', 'CEF', 'TAXII/STIX',
            'Webhook', 'SAML 2.0', 'LDAP',
          ],
          haFeatures: [
            'Cloud-native SaaS platform (99.9% SLA)',
            'Sensor auto-update with rollback',
            'Multi-tenant console for MSSP',
          ],
          securityCapabilities: [
            'Behavioral EDR with process tree analysis',
            'Streaming Prevention (NGAV) with ML models',
            'Live Response for remote investigation',
            'Threat intelligence with VMware TAU',
            'MITRE ATT&CK mapping for detections',
            'Vulnerability assessment (OS and application)',
          ],
          children: [
            {
              nodeId: 'vmware-carbon-black-endpoint',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Carbon Black Cloud Endpoint',
              nameKo: '카본 블랙 클라우드 엔드포인트',
              description: 'Cloud-delivered EDR and NGAV for endpoints with behavioral analysis, threat hunting, and automated response',
              descriptionKo: '행동 분석, 위협 헌팅, 자동 대응을 갖춘 엔드포인트용 클라우드 제공 EDR 및 NGAV',
              sourceUrl: 'https://www.vmware.com/products/carbon-black/endpoint',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Protection': 'NGAV (Streaming Prevention) + Behavioral EDR',
                'Supported OS': 'Windows 7-11, Windows Server 2008-2022, macOS 10.14+, Linux (RHEL, Ubuntu, SUSE, Amazon Linux)',
                'Detection Engine': 'Behavioral analysis, ML models, reputation scoring',
                'Investigation': 'Live Response remote shell, process tree visualization',
                'Threat Intelligence': 'VMware TAU with MITRE ATT&CK mapping',
                'Deployment': 'Single lightweight sensor (~25 MB)',
                'Console': 'Cloud-hosted multi-tenant console',
              },
              children: [],
            },
            {
              nodeId: 'vmware-carbon-black-workload',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Carbon Black Cloud Workload',
              nameKo: '카본 블랙 클라우드 워크로드',
              description: 'Server and container workload protection with vulnerability assessment, hardening, and runtime security for data center and cloud workloads',
              descriptionKo: '데이터 센터 및 클라우드 워크로드를 위한 취약점 평가, 보안 강화, 런타임 보안을 갖춘 서버 및 컨테이너 워크로드 보호',
              sourceUrl: 'https://www.vmware.com/products/carbon-black/workload',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'cloud',
              specs: {
                'Protection Scope': 'Physical servers, VMs, containers (Docker, Kubernetes)',
                'Vulnerability Assessment': 'OS and application CVE scanning with prioritization',
                'vSphere Integration': 'Agentless via vCenter (Carbon Black Cloud Workload Appliance)',
                'Container Security': 'Kubernetes cluster visibility, container runtime protection',
                'Hardening': 'CIS benchmark compliance checks with remediation guidance',
                'Supported Platforms': 'Windows Server, Linux (RHEL, Ubuntu, SUSE, Amazon Linux), vSphere ESXi',
              },
              children: [],
            },
            {
              nodeId: 'vmware-carbon-black-app-control',
              depth: 2,
              depthLabel: 'Edition',
              depthLabelKo: '에디션',
              name: 'Carbon Black App Control',
              nameKo: '카본 블랙 앱 컨트롤',
              description: 'Application allowlisting and change control solution for locking down critical infrastructure and PCI/HIPAA-regulated systems',
              descriptionKo: '중요 인프라 및 PCI/HIPAA 규제 시스템 잠금을 위한 애플리케이션 허용 목록 및 변경 제어 솔루션',
              sourceUrl: 'https://www.vmware.com/products/carbon-black/app-control',
              lifecycle: 'active',
              licensingModel: 'subscription',
              formFactor: 'virtual',
              specs: {
                'Core Function': 'Application allowlisting (default-deny enforcement)',
                'Change Control': 'File integrity monitoring with change tracking',
                'Compliance': 'PCI-DSS, HIPAA, NIST 800-53 compliance templates',
                'Supported OS': 'Windows Server 2008-2022, Windows 7-11, RHEL, CentOS',
                'Deployment': 'On-premises server with endpoint agents',
                'Trust Engine': 'Software reputation via cloud-based trust rating',
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
