/**
 * AI Software Catalog — Embedding Services
 *
 * Libraries and services for generating vector embeddings from text, images, and multimodal data.
 */

import type { AISoftware } from './types';

export const embeddingServices: AISoftware[] = [
  {
    id: 'AI-EMB-001',
    name: 'SentenceTransformers',
    nameKo: 'SentenceTransformers',
    category: 'embedding',
    license: 'open-source',
    infraNodeTypes: ['embedding-service'],
    architectureRole: 'Text embedding and semantic similarity library',
    architectureRoleKo: '텍스트 임베딩 및 의미 유사도 라이브러리',
    recommendedFor: [
      'Semantic text search and similarity',
      'RAG embedding generation',
      'Sentence-level text encoding',
      'Custom embedding model fine-tuning',
    ],
    recommendedForKo: [
      '시맨틱 텍스트 검색 및 유사도',
      'RAG 임베딩 생성',
      '문장 수준 텍스트 인코딩',
      '커스텀 임베딩 모델 파인튜닝',
    ],
    supportedModels: ['all-MiniLM-L6-v2', 'all-mpnet-base-v2', 'multilingual-e5-large', 'BGE'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon'],
    deploymentModel: ['local', 'server'],
    minRequirements: { ram: '4GB', storage: '5GB' },
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://www.sbert.net/',
    description: 'Python framework for state-of-the-art sentence, text, and image embeddings with hundreds of pre-trained models.',
    descriptionKo: '수백 개의 사전 학습 모델로 최신 문장, 텍스트, 이미지 임베딩을 제공하는 Python 프레임워크입니다.',
  },
  {
    id: 'AI-EMB-002',
    name: 'CLIP',
    nameKo: 'CLIP',
    category: 'embedding',
    license: 'open-source',
    infraNodeTypes: ['embedding-service'],
    architectureRole: 'Multimodal vision-language embedding model',
    architectureRoleKo: '멀티모달 비전-언어 임베딩 모델',
    recommendedFor: [
      'Image-text similarity search',
      'Zero-shot image classification',
      'Multimodal retrieval systems',
      'Visual content understanding',
    ],
    recommendedForKo: [
      '이미지-텍스트 유사도 검색',
      '제로샷 이미지 분류',
      '멀티모달 검색 시스템',
      '시각 콘텐츠 이해',
    ],
    supportedModels: ['ViT-B/32', 'ViT-L/14', 'ViT-H/14', 'OpenCLIP variants'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon'],
    deploymentModel: ['local', 'server'],
    minRequirements: { ram: '8GB', vram: '4GB', storage: '10GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://github.com/openai/CLIP/blob/main/README.md',
    description: 'OpenAI contrastive language-image pre-training model for generating joint embeddings of images and text.',
    descriptionKo: '이미지와 텍스트의 결합 임베딩을 생성하는 OpenAI 대조 언어-이미지 사전 학습 모델입니다.',
  },
  {
    id: 'AI-EMB-003',
    name: 'Nomic Embed',
    nameKo: 'Nomic Embed',
    category: 'embedding',
    license: 'open-source',
    infraNodeTypes: ['embedding-service'],
    architectureRole: 'High-performance open embedding model',
    architectureRoleKo: '고성능 오픈 임베딩 모델',
    recommendedFor: [
      'Long-context document embedding',
      'Open-source RAG pipelines',
      'Cost-effective embedding generation',
      'Local and cloud hybrid deployment',
    ],
    recommendedForKo: [
      '긴 컨텍스트 문서 임베딩',
      '오픈소스 RAG 파이프라인',
      '비용 효율적 임베딩 생성',
      '로컬 및 클라우드 하이브리드 배포',
    ],
    supportedModels: ['nomic-embed-text-v1.5', 'nomic-embed-vision-v1.5'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon'],
    deploymentModel: ['local', 'server', 'cloud'],
    minRequirements: { ram: '4GB', storage: '3GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.nomic.ai/atlas/models/embed',
    description: 'Open-source, auditable text and vision embedding models with long-context support and competitive benchmark scores.',
    descriptionKo: '긴 컨텍스트 지원과 경쟁력 있는 벤치마크 성능을 갖춘 오픈소스, 감사 가능한 텍스트 및 비전 임베딩 모델입니다.',
  },
  {
    id: 'AI-EMB-004',
    name: 'Jina Embeddings',
    nameKo: 'Jina Embeddings',
    category: 'embedding',
    license: 'freemium',
    infraNodeTypes: ['embedding-service'],
    architectureRole: 'Multilingual embedding service with API',
    architectureRoleKo: 'API 기반 다국어 임베딩 서비스',
    recommendedFor: [
      'Multilingual text embedding',
      'API-first embedding integration',
      'Cross-lingual search systems',
      'Production embedding pipelines',
    ],
    recommendedForKo: [
      '다국어 텍스트 임베딩',
      'API 우선 임베딩 통합',
      '교차 언어 검색 시스템',
      '프로덕션 임베딩 파이프라인',
    ],
    supportedModels: ['jina-embeddings-v3', 'jina-clip-v2', 'jina-reranker-v2'],
    supportedHardware: ['CPU', 'NVIDIA GPU'],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '4GB', storage: '5GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://jina.ai/embeddings/',
    description: 'Multilingual embedding models with long-context support, available as both self-hosted and cloud API service.',
    descriptionKo: '긴 컨텍스트를 지원하는 다국어 임베딩 모델로, 자체 호스팅 및 클라우드 API 서비스로 제공됩니다.',
  },
];
