/**
 * AI Software Catalog — AI Gateways
 *
 * API gateways and proxy layers for managing and routing AI model requests.
 */

import type { AISoftware } from './types';

export const gateways: AISoftware[] = [
  {
    id: 'AI-GW-001',
    name: 'LiteLLM',
    nameKo: 'LiteLLM',
    category: 'gateway',
    license: 'open-source',
    infraNodeTypes: ['ai-gateway'],
    architectureRole: 'Unified LLM API proxy',
    architectureRoleKo: '통합 LLM API 프록시',
    recommendedFor: [
      'Multi-provider LLM routing',
      'OpenAI-compatible API standardization',
      'LLM cost management and tracking',
      'Self-hosted LLM gateway',
    ],
    recommendedForKo: [
      '멀티 프로바이더 LLM 라우팅',
      'OpenAI 호환 API 표준화',
      'LLM 비용 관리 및 추적',
      '자체 호스팅 LLM 게이트웨이',
    ],
    deploymentModel: ['server'],
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.litellm.ai/',
    description: 'Lightweight proxy that provides a unified OpenAI-compatible API for 100+ LLM providers with cost tracking and load balancing.',
    descriptionKo: '비용 추적과 로드 밸런싱을 갖춘 100개 이상의 LLM 프로바이더에 대한 통합 OpenAI 호환 API를 제공하는 경량 프록시입니다.',
  },
  {
    id: 'AI-GW-002',
    name: 'Kong AI Gateway',
    nameKo: 'Kong AI 게이트웨이',
    category: 'gateway',
    license: 'freemium',
    infraNodeTypes: ['ai-gateway'],
    architectureRole: 'Enterprise AI API gateway',
    architectureRoleKo: '엔터프라이즈 AI API 게이트웨이',
    recommendedFor: [
      'Enterprise AI API management',
      'Multi-model traffic governance',
      'AI rate limiting and security',
      'Existing Kong infrastructure extension',
    ],
    recommendedForKo: [
      '엔터프라이즈 AI API 관리',
      '멀티모델 트래픽 거버넌스',
      'AI 속도 제한 및 보안',
      '기존 Kong 인프라 확장',
    ],
    deploymentModel: ['server', 'cloud'],
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://docs.konghq.com/gateway/',
    description: 'Enterprise-grade API gateway with AI-specific plugins for traffic management, security, and observability across LLM providers.',
    descriptionKo: 'LLM 프로바이더 전반의 트래픽 관리, 보안, 관측성을 위한 AI 전용 플러그인을 갖춘 엔터프라이즈급 API 게이트웨이입니다.',
  },
  {
    id: 'AI-GW-003',
    name: 'Portkey',
    nameKo: 'Portkey',
    category: 'gateway',
    license: 'freemium',
    infraNodeTypes: ['ai-gateway'],
    architectureRole: 'AI observability and gateway platform',
    architectureRoleKo: 'AI 관측성 및 게이트웨이 플랫폼',
    recommendedFor: [
      'LLM request routing and fallback',
      'AI application observability',
      'Prompt versioning and management',
      'Multi-provider reliability engineering',
    ],
    recommendedForKo: [
      'LLM 요청 라우팅 및 폴백',
      'AI 애플리케이션 관측성',
      '프롬프트 버전 관리',
      '멀티 프로바이더 신뢰성 엔지니어링',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'small',
    maturity: 'growing',
    documentationUrl: 'https://docs.portkey.ai/',
    description: 'AI gateway with built-in observability, automatic retries, fallbacks, and caching for production LLM applications.',
    descriptionKo: '프로덕션 LLM 애플리케이션을 위한 내장 관측성, 자동 재시도, 폴백, 캐싱을 갖춘 AI 게이트웨이입니다.',
  },
  {
    id: 'AI-GW-004',
    name: 'OpenRouter',
    nameKo: 'OpenRouter',
    category: 'gateway',
    license: 'commercial',
    infraNodeTypes: ['ai-gateway'],
    architectureRole: 'Multi-model AI routing service',
    architectureRoleKo: '멀티모델 AI 라우팅 서비스',
    recommendedFor: [
      'Access to multiple LLM providers via single API',
      'Model comparison and benchmarking',
      'Cost-optimized model selection',
      'Rapid prototyping with diverse models',
    ],
    recommendedForKo: [
      '단일 API로 다중 LLM 프로바이더 접근',
      '모델 비교 및 벤치마킹',
      '비용 최적화 모델 선택',
      '다양한 모델로 빠른 프로토타이핑',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://openrouter.ai/docs/',
    description: 'Unified API service for accessing hundreds of AI models from multiple providers with transparent pricing.',
    descriptionKo: '투명한 가격으로 다수 프로바이더의 수백 개 AI 모델에 접근하는 통합 API 서비스입니다.',
  },
];
