/**
 * AI Software Catalog — Inference Engines
 *
 * Local and server-based LLM inference runtimes for running AI models.
 */

import type { AISoftware } from './types';

export const inferenceEngines: AISoftware[] = [
  {
    id: 'AI-INF-001',
    name: 'Ollama',
    nameKo: '올라마',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'Local LLM inference runtime',
    architectureRoleKo: '로컬 LLM 추론 런타임',
    recommendedFor: [
      'Local development and prototyping',
      'Edge AI deployment',
      'Privacy-sensitive inference',
      'Offline AI capabilities',
    ],
    recommendedForKo: [
      '로컬 개발 및 프로토타이핑',
      '엣지 AI 배포',
      '개인정보 민감 추론',
      '오프라인 AI 기능',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Gemma', 'Phi', 'CodeLlama', 'Qwen'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon', 'AMD GPU'],
    deploymentModel: ['local', 'edge'],
    minRequirements: { ram: '8GB', storage: '10GB' },
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://github.com/ollama/ollama/blob/main/docs/README.md',
    description: 'Simple local LLM runtime that makes it easy to run large language models on personal hardware with a single command.',
    descriptionKo: '간단한 명령어로 개인 하드웨어에서 대형 언어 모델을 쉽게 실행할 수 있는 로컬 LLM 런타임입니다.',
  },
  {
    id: 'AI-INF-002',
    name: 'vLLM',
    nameKo: 'vLLM',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'High-throughput LLM serving engine',
    architectureRoleKo: '고처리량 LLM 서빙 엔진',
    recommendedFor: [
      'Production LLM serving',
      'High-concurrency API endpoints',
      'Batch inference workloads',
      'Multi-model serving',
    ],
    recommendedForKo: [
      '프로덕션 LLM 서빙',
      '고동시성 API 엔드포인트',
      '배치 추론 워크로드',
      '멀티모델 서빙',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Falcon', 'GPT-NeoX', 'Qwen', 'Yi'],
    supportedHardware: ['NVIDIA GPU', 'AMD GPU', 'TPU'],
    deploymentModel: ['server'],
    minRequirements: { ram: '16GB', vram: '16GB', storage: '50GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'growing',
    documentationUrl: 'https://docs.vllm.ai/',
    description: 'High-throughput LLM serving engine with PagedAttention for efficient memory management, supporting continuous batching.',
    descriptionKo: 'PagedAttention을 통한 효율적 메모리 관리와 연속 배칭을 지원하는 고처리량 LLM 서빙 엔진입니다.',
  },
  {
    id: 'AI-INF-003',
    name: 'Text Generation Inference (TGI)',
    nameKo: 'TGI (텍스트 생성 추론)',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'Production-grade text generation server',
    architectureRoleKo: '프로덕션급 텍스트 생성 서버',
    recommendedFor: [
      'Hugging Face model deployment',
      'Production text generation APIs',
      'Cloud-based inference services',
      'Enterprise LLM serving',
    ],
    recommendedForKo: [
      'Hugging Face 모델 배포',
      '프로덕션 텍스트 생성 API',
      '클라우드 기반 추론 서비스',
      '엔터프라이즈 LLM 서빙',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Falcon', 'StarCoder', 'BLOOM', 'GPT-NeoX'],
    supportedHardware: ['NVIDIA GPU', 'AMD GPU', 'Intel Gaudi', 'AWS Inferentia'],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '16GB', vram: '16GB', storage: '50GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://huggingface.co/docs/text-generation-inference/',
    description: 'Hugging Face production-ready inference server for LLMs with tensor parallelism, quantization, and streaming support.',
    descriptionKo: '텐서 병렬 처리, 양자화, 스트리밍을 지원하는 Hugging Face의 프로덕션용 LLM 추론 서버입니다.',
  },
  {
    id: 'AI-INF-004',
    name: 'llama.cpp',
    nameKo: 'llama.cpp',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'Lightweight CPU/edge inference runtime',
    architectureRoleKo: '경량 CPU/엣지 추론 런타임',
    recommendedFor: [
      'CPU-only inference',
      'Edge device deployment',
      'Embedded AI systems',
      'Resource-constrained environments',
    ],
    recommendedForKo: [
      'CPU 전용 추론',
      '엣지 디바이스 배포',
      '임베디드 AI 시스템',
      '리소스 제한 환경',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Gemma', 'Phi', 'GGUF models'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon', 'AMD GPU', 'Vulkan'],
    deploymentModel: ['local', 'edge'],
    minRequirements: { ram: '4GB', storage: '5GB' },
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://github.com/ggerganov/llama.cpp/blob/master/README.md',
    description: 'C/C++ implementation for efficient LLM inference on CPUs and edge devices, with GGUF quantization format support.',
    descriptionKo: 'GGUF 양자화 포맷을 지원하는 CPU 및 엣지 디바이스에서의 효율적 LLM 추론을 위한 C/C++ 구현체입니다.',
  },
  {
    id: 'AI-INF-005',
    name: 'LM Studio',
    nameKo: 'LM 스튜디오',
    category: 'inference',
    license: 'freemium',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'Desktop LLM application with GUI',
    architectureRoleKo: 'GUI 기반 데스크톱 LLM 애플리케이션',
    recommendedFor: [
      'Non-technical user LLM access',
      'Local model experimentation',
      'Desktop AI assistant setup',
      'Model evaluation and comparison',
    ],
    recommendedForKo: [
      '비기술 사용자 LLM 접근',
      '로컬 모델 실험',
      '데스크톱 AI 어시스턴트 설정',
      '모델 평가 및 비교',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Gemma', 'Phi', 'GGUF models'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon', 'AMD GPU'],
    deploymentModel: ['local'],
    minRequirements: { ram: '8GB', storage: '10GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://lmstudio.ai/docs',
    description: 'User-friendly desktop application for discovering, downloading, and running local LLMs with an intuitive GUI.',
    descriptionKo: '직관적인 GUI로 로컬 LLM을 발견, 다운로드, 실행할 수 있는 사용자 친화적 데스크톱 애플리케이션입니다.',
  },
  {
    id: 'AI-INF-006',
    name: 'MLX',
    nameKo: 'MLX',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'Apple Silicon-optimized ML framework',
    architectureRoleKo: 'Apple Silicon 최적화 ML 프레임워크',
    recommendedFor: [
      'Apple Silicon-based inference',
      'macOS ML development',
      'Edge AI on Apple devices',
      'Research and experimentation on Mac',
    ],
    recommendedForKo: [
      'Apple Silicon 기반 추론',
      'macOS ML 개발',
      'Apple 디바이스 엣지 AI',
      'Mac 기반 연구 및 실험',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Gemma', 'Phi', 'Stable Diffusion'],
    supportedHardware: ['Apple Silicon'],
    deploymentModel: ['local', 'edge'],
    minRequirements: { ram: '8GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://ml-explore.github.io/mlx/build/html/index.html',
    description: 'Apple ML framework optimized for Apple Silicon with unified memory architecture, enabling efficient on-device inference.',
    descriptionKo: '통합 메모리 아키텍처를 활용하여 디바이스 내 효율적 추론을 가능하게 하는 Apple Silicon 최적화 ML 프레임워크입니다.',
  },
  {
    id: 'AI-INF-007',
    name: 'LocalAI',
    nameKo: 'LocalAI',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'OpenAI-compatible local inference server',
    architectureRoleKo: 'OpenAI 호환 로컬 추론 서버',
    recommendedFor: [
      'OpenAI API drop-in replacement',
      'Self-hosted AI infrastructure',
      'Multi-modal local inference',
      'Air-gapped AI deployments',
    ],
    recommendedForKo: [
      'OpenAI API 대체 솔루션',
      '자체 호스팅 AI 인프라',
      '멀티모달 로컬 추론',
      '에어갭 AI 배포',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'GPT4All', 'Whisper', 'Stable Diffusion'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'Apple Silicon'],
    deploymentModel: ['local', 'server'],
    minRequirements: { ram: '8GB', storage: '15GB' },
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://localai.io/docs/',
    description: 'Free, open-source OpenAI-compatible API server for running LLMs, image generation, and audio models locally.',
    descriptionKo: 'LLM, 이미지 생성, 오디오 모델을 로컬에서 실행하는 무료 오픈소스 OpenAI 호환 API 서버입니다.',
  },
  {
    id: 'AI-INF-008',
    name: 'TensorRT-LLM',
    nameKo: 'TensorRT-LLM',
    category: 'inference',
    license: 'open-source',
    infraNodeTypes: ['inference-engine'],
    architectureRole: 'NVIDIA GPU-optimized high-performance inference',
    architectureRoleKo: 'NVIDIA GPU 최적화 고성능 추론',
    recommendedFor: [
      'NVIDIA GPU production serving',
      'Maximum inference throughput',
      'Enterprise-scale AI deployment',
      'Data center inference optimization',
    ],
    recommendedForKo: [
      'NVIDIA GPU 프로덕션 서빙',
      '최대 추론 처리량',
      '엔터프라이즈급 AI 배포',
      '데이터 센터 추론 최적화',
    ],
    supportedModels: ['LLaMA', 'GPT', 'Falcon', 'Mistral', 'Baichuan', 'Qwen'],
    supportedHardware: ['NVIDIA GPU'],
    deploymentModel: ['server'],
    minRequirements: { ram: '32GB', vram: '24GB', storage: '100GB' },
    operationalComplexity: 'high',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://nvidia.github.io/TensorRT-LLM/',
    description: 'NVIDIA toolkit for optimizing and deploying LLMs with maximum performance on NVIDIA GPUs using TensorRT acceleration.',
    descriptionKo: 'TensorRT 가속을 활용하여 NVIDIA GPU에서 최대 성능으로 LLM을 최적화하고 배포하는 NVIDIA 툴킷입니다.',
  },
];
