/**
 * AI Software Catalog — Monitoring Tools
 *
 * Observability, evaluation, and monitoring platforms for AI/ML systems.
 */

import type { AISoftware } from './types';

export const monitoringTools: AISoftware[] = [
  {
    id: 'AI-MON-001',
    name: 'LangSmith',
    nameKo: '랭스미스',
    category: 'monitoring',
    license: 'freemium',
    infraNodeTypes: ['ai-monitor', 'prompt-manager'],
    architectureRole: 'LLM application tracing and evaluation platform',
    architectureRoleKo: 'LLM 애플리케이션 추적 및 평가 플랫폼',
    recommendedFor: [
      'LangChain application debugging',
      'LLM response evaluation and scoring',
      'Prompt iteration and A/B testing',
      'Production LLM trace monitoring',
    ],
    recommendedForKo: [
      'LangChain 애플리케이션 디버깅',
      'LLM 응답 평가 및 스코어링',
      '프롬프트 반복 및 A/B 테스트',
      '프로덕션 LLM 트레이스 모니터링',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'growing',
    documentationUrl: 'https://docs.smith.langchain.com/',
    description: 'Platform for debugging, testing, evaluating, and monitoring LLM applications with deep LangChain integration.',
    descriptionKo: 'LangChain 심층 통합으로 LLM 애플리케이션의 디버깅, 테스트, 평가, 모니터링을 지원하는 플랫폼입니다.',
  },
  {
    id: 'AI-MON-002',
    name: 'MLflow',
    nameKo: 'MLflow',
    category: 'monitoring',
    license: 'open-source',
    infraNodeTypes: ['ai-monitor', 'training-platform'],
    architectureRole: 'ML lifecycle management platform',
    architectureRoleKo: 'ML 생명주기 관리 플랫폼',
    recommendedFor: [
      'ML experiment tracking',
      'Model registry and versioning',
      'ML pipeline reproducibility',
      'Multi-framework model deployment',
    ],
    recommendedForKo: [
      'ML 실험 추적',
      '모델 레지스트리 및 버전 관리',
      'ML 파이프라인 재현성',
      '멀티 프레임워크 모델 배포',
    ],
    deploymentModel: ['server'],
    minRequirements: { ram: '8GB', storage: '20GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://mlflow.org/docs/latest/index.html',
    description: 'Open-source platform for managing the end-to-end ML lifecycle including experiment tracking, model registry, and deployment.',
    descriptionKo: '실험 추적, 모델 레지스트리, 배포를 포함한 엔드투엔드 ML 생명주기를 관리하는 오픈소스 플랫폼입니다.',
  },
  {
    id: 'AI-MON-003',
    name: 'Evidently',
    nameKo: 'Evidently',
    category: 'monitoring',
    license: 'open-source',
    infraNodeTypes: ['ai-monitor'],
    architectureRole: 'ML model monitoring and data drift detection',
    architectureRoleKo: 'ML 모델 모니터링 및 데이터 드리프트 감지',
    recommendedFor: [
      'Model performance monitoring',
      'Data and prediction drift detection',
      'ML model quality reporting',
      'Pre-deployment model validation',
    ],
    recommendedForKo: [
      '모델 성능 모니터링',
      '데이터 및 예측 드리프트 감지',
      'ML 모델 품질 보고',
      '배포 전 모델 검증',
    ],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '4GB', storage: '10GB' },
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.evidentlyai.com/',
    description: 'Open-source ML monitoring tool for tracking data drift, model performance degradation, and data quality in production.',
    descriptionKo: '프로덕션에서 데이터 드리프트, 모델 성능 저하, 데이터 품질을 추적하는 오픈소스 ML 모니터링 도구입니다.',
  },
  {
    id: 'AI-MON-004',
    name: 'WhyLabs',
    nameKo: 'WhyLabs',
    category: 'monitoring',
    license: 'commercial',
    infraNodeTypes: ['ai-monitor'],
    architectureRole: 'AI observability and security platform',
    architectureRoleKo: 'AI 관측성 및 보안 플랫폼',
    recommendedFor: [
      'Enterprise AI observability',
      'LLM security and guardrails',
      'Real-time data quality monitoring',
      'ML pipeline anomaly detection',
    ],
    recommendedForKo: [
      '엔터프라이즈 AI 관측성',
      'LLM 보안 및 가드레일',
      '실시간 데이터 품질 모니터링',
      'ML 파이프라인 이상 감지',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'small',
    maturity: 'growing',
    documentationUrl: 'https://docs.whylabs.ai/',
    description: 'AI observability platform providing data and model monitoring with built-in LLM security guardrails and drift detection.',
    descriptionKo: '내장 LLM 보안 가드레일과 드리프트 감지를 제공하는 데이터 및 모델 모니터링 AI 관측성 플랫폼입니다.',
  },
  {
    id: 'AI-MON-005',
    name: 'Helicone',
    nameKo: 'Helicone',
    category: 'monitoring',
    license: 'freemium',
    infraNodeTypes: ['ai-monitor'],
    architectureRole: 'LLM usage analytics and cost tracking',
    architectureRoleKo: 'LLM 사용 분석 및 비용 추적',
    recommendedFor: [
      'LLM API cost monitoring',
      'Request-level latency tracking',
      'Prompt and response logging',
      'LLM usage analytics dashboards',
    ],
    recommendedForKo: [
      'LLM API 비용 모니터링',
      '요청 수준 지연 시간 추적',
      '프롬프트 및 응답 로깅',
      'LLM 사용 분석 대시보드',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.helicone.ai/',
    description: 'Lightweight LLM observability platform for tracking costs, latency, and usage patterns across AI API providers.',
    descriptionKo: 'AI API 프로바이더 전반의 비용, 지연 시간, 사용 패턴을 추적하는 경량 LLM 관측성 플랫폼입니다.',
  },
];
