/**
 * AI Software Catalog — Orchestrators
 *
 * Frameworks for building LLM-powered applications, agent pipelines, and RAG systems.
 */

import type { AISoftware } from './types';

export const orchestrators: AISoftware[] = [
  {
    id: 'AI-ORC-001',
    name: 'LangChain',
    nameKo: '랭체인',
    category: 'orchestrator',
    license: 'open-source',
    infraNodeTypes: ['ai-orchestrator'],
    architectureRole: 'LLM application orchestration framework',
    architectureRoleKo: 'LLM 애플리케이션 오케스트레이션 프레임워크',
    recommendedFor: [
      'RAG pipeline development',
      'Multi-step LLM chains',
      'Agent-based AI systems',
      'LLM application prototyping',
    ],
    recommendedForKo: [
      'RAG 파이프라인 개발',
      '멀티스텝 LLM 체인',
      '에이전트 기반 AI 시스템',
      'LLM 애플리케이션 프로토타이핑',
    ],
    deploymentModel: ['local', 'server', 'cloud'],
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://python.langchain.com/docs/',
    description: 'Comprehensive framework for developing LLM-powered applications with chains, agents, memory, and tool integrations.',
    descriptionKo: '체인, 에이전트, 메모리, 도구 통합을 갖춘 LLM 기반 애플리케이션 개발 종합 프레임워크입니다.',
  },
  {
    id: 'AI-ORC-002',
    name: 'LlamaIndex',
    nameKo: '라마인덱스',
    category: 'orchestrator',
    license: 'open-source',
    infraNodeTypes: ['ai-orchestrator'],
    architectureRole: 'Data framework for LLM applications',
    architectureRoleKo: 'LLM 애플리케이션용 데이터 프레임워크',
    recommendedFor: [
      'Knowledge-augmented generation',
      'Document Q&A systems',
      'Structured data querying with LLMs',
      'Enterprise data integration with AI',
    ],
    recommendedForKo: [
      '지식 증강 생성',
      '문서 Q&A 시스템',
      'LLM 기반 구조화 데이터 쿼리',
      '엔터프라이즈 데이터 AI 통합',
    ],
    deploymentModel: ['local', 'server', 'cloud'],
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'growing',
    documentationUrl: 'https://docs.llamaindex.ai/',
    description: 'Data framework for connecting custom data sources to LLMs, specializing in retrieval-augmented generation (RAG).',
    descriptionKo: '검색 증강 생성(RAG)에 특화된, 커스텀 데이터 소스를 LLM에 연결하는 데이터 프레임워크입니다.',
  },
  {
    id: 'AI-ORC-003',
    name: 'CrewAI',
    nameKo: 'CrewAI',
    category: 'orchestrator',
    license: 'open-source',
    infraNodeTypes: ['ai-orchestrator'],
    architectureRole: 'Multi-agent AI orchestration platform',
    architectureRoleKo: '멀티 에이전트 AI 오케스트레이션 플랫폼',
    recommendedFor: [
      'Multi-agent collaboration systems',
      'Role-based AI task delegation',
      'Complex workflow automation',
      'Autonomous AI team orchestration',
    ],
    recommendedForKo: [
      '멀티 에이전트 협업 시스템',
      '역할 기반 AI 작업 위임',
      '복잡한 워크플로우 자동화',
      '자율 AI 팀 오케스트레이션',
    ],
    deploymentModel: ['server'],
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.crewai.com/',
    description: 'Framework for orchestrating role-playing AI agents that collaborate to complete complex tasks autonomously.',
    descriptionKo: '복잡한 작업을 자율적으로 완료하기 위해 협업하는 역할 기반 AI 에이전트를 오케스트레이션하는 프레임워크입니다.',
  },
  {
    id: 'AI-ORC-004',
    name: 'AutoGen',
    nameKo: 'AutoGen',
    category: 'orchestrator',
    license: 'open-source',
    infraNodeTypes: ['ai-orchestrator'],
    architectureRole: 'Multi-agent conversation framework',
    architectureRoleKo: '멀티 에이전트 대화 프레임워크',
    recommendedFor: [
      'Multi-agent conversational AI',
      'Code generation and execution agents',
      'Human-in-the-loop AI workflows',
      'Research-oriented agent systems',
    ],
    recommendedForKo: [
      '멀티 에이전트 대화형 AI',
      '코드 생성 및 실행 에이전트',
      '휴먼인더루프 AI 워크플로우',
      '연구 지향 에이전트 시스템',
    ],
    deploymentModel: ['server'],
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://microsoft.github.io/autogen/',
    description: 'Microsoft framework enabling multi-agent conversations where agents can chat, execute code, and collaborate with humans.',
    descriptionKo: '에이전트가 대화하고, 코드를 실행하고, 인간과 협업할 수 있는 멀티 에이전트 대화를 가능하게 하는 Microsoft 프레임워크입니다.',
  },
  {
    id: 'AI-ORC-005',
    name: 'Haystack',
    nameKo: 'Haystack',
    category: 'orchestrator',
    license: 'open-source',
    infraNodeTypes: ['ai-orchestrator'],
    architectureRole: 'Production NLP/LLM pipeline framework',
    architectureRoleKo: '프로덕션 NLP/LLM 파이프라인 프레임워크',
    recommendedFor: [
      'Production search and QA systems',
      'NLP pipeline orchestration',
      'Document processing workflows',
      'Enterprise search with LLMs',
    ],
    recommendedForKo: [
      '프로덕션 검색 및 QA 시스템',
      'NLP 파이프라인 오케스트레이션',
      '문서 처리 워크플로우',
      'LLM 기반 엔터프라이즈 검색',
    ],
    deploymentModel: ['server', 'cloud'],
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'mature',
    documentationUrl: 'https://docs.haystack.deepset.ai/',
    description: 'deepset framework for building production-ready NLP and LLM pipelines with modular, composable components.',
    descriptionKo: '모듈형, 조합 가능한 컴포넌트로 프로덕션급 NLP 및 LLM 파이프라인을 구축하는 deepset 프레임워크입니다.',
  },
];
