/**
 * AI Software Catalog — Training Platforms
 *
 * Platforms and tools for fine-tuning, training, and managing AI/ML models.
 */

import type { AISoftware } from './types';

export const trainingPlatforms: AISoftware[] = [
  {
    id: 'AI-TRN-001',
    name: 'Hugging Face Hub',
    nameKo: '허깅페이스 허브',
    category: 'training',
    license: 'freemium',
    infraNodeTypes: ['training-platform'],
    architectureRole: 'ML model hosting and collaboration hub',
    architectureRoleKo: 'ML 모델 호스팅 및 협업 허브',
    recommendedFor: [
      'Pre-trained model discovery and download',
      'Model fine-tuning with Transformers',
      'Dataset hosting and sharing',
      'ML community collaboration',
    ],
    recommendedForKo: [
      '사전 학습 모델 검색 및 다운로드',
      'Transformers 기반 모델 파인튜닝',
      '데이터셋 호스팅 및 공유',
      'ML 커뮤니티 협업',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'BERT', 'GPT-NeoX', 'Stable Diffusion', 'Whisper'],
    supportedHardware: ['CPU', 'NVIDIA GPU', 'AMD GPU', 'TPU'],
    deploymentModel: ['cloud', 'server'],
    minRequirements: { ram: '16GB', storage: '50GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://huggingface.co/docs',
    description: 'The largest open platform for sharing and collaborating on ML models, datasets, and applications.',
    descriptionKo: 'ML 모델, 데이터셋, 애플리케이션을 공유하고 협업하는 최대 오픈 플랫폼입니다.',
  },
  {
    id: 'AI-TRN-002',
    name: 'Weights & Biases',
    nameKo: 'Weights & Biases',
    category: 'training',
    license: 'freemium',
    infraNodeTypes: ['training-platform'],
    architectureRole: 'ML experiment tracking and collaboration platform',
    architectureRoleKo: 'ML 실험 추적 및 협업 플랫폼',
    recommendedFor: [
      'ML experiment tracking and visualization',
      'Hyperparameter sweep optimization',
      'Model training reproducibility',
      'Team ML project collaboration',
    ],
    recommendedForKo: [
      'ML 실험 추적 및 시각화',
      '하이퍼파라미터 스윕 최적화',
      '모델 학습 재현성',
      '팀 ML 프로젝트 협업',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://docs.wandb.ai/',
    description: 'ML developer platform for experiment tracking, model versioning, hyperparameter sweeps, and collaborative dashboards.',
    descriptionKo: '실험 추적, 모델 버전 관리, 하이퍼파라미터 스윕, 협업 대시보드를 위한 ML 개발자 플랫폼입니다.',
  },
  {
    id: 'AI-TRN-003',
    name: 'Axolotl',
    nameKo: 'Axolotl',
    category: 'training',
    license: 'open-source',
    infraNodeTypes: ['training-platform'],
    architectureRole: 'Streamlined LLM fine-tuning toolkit',
    architectureRoleKo: '간소화된 LLM 파인튜닝 툴킷',
    recommendedFor: [
      'LoRA and QLoRA fine-tuning',
      'Multi-GPU distributed training',
      'Custom dataset fine-tuning workflows',
      'Efficient LLM adaptation',
    ],
    recommendedForKo: [
      'LoRA 및 QLoRA 파인튜닝',
      '멀티 GPU 분산 학습',
      '커스텀 데이터셋 파인튜닝 워크플로우',
      '효율적 LLM 적응',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Falcon', 'Phi', 'Qwen'],
    supportedHardware: ['NVIDIA GPU'],
    deploymentModel: ['server'],
    minRequirements: { ram: '32GB', vram: '24GB', storage: '100GB' },
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://github.com/axolotl-ai-cloud/axolotl/blob/main/README.md',
    description: 'Streamlined tool for fine-tuning LLMs with support for LoRA, QLoRA, and full fine-tuning via simple YAML configuration.',
    descriptionKo: '간단한 YAML 설정으로 LoRA, QLoRA, 풀 파인튜닝을 지원하는 LLM 파인튜닝 간소화 도구입니다.',
  },
  {
    id: 'AI-TRN-004',
    name: 'Unsloth',
    nameKo: 'Unsloth',
    category: 'training',
    license: 'open-source',
    infraNodeTypes: ['training-platform'],
    architectureRole: 'Memory-efficient LLM fine-tuning accelerator',
    architectureRoleKo: '메모리 효율적 LLM 파인튜닝 가속기',
    recommendedFor: [
      'Low-VRAM LLM fine-tuning',
      'Fast LoRA training on consumer GPUs',
      'Cost-effective model adaptation',
      'Rapid prototyping of fine-tuned models',
    ],
    recommendedForKo: [
      '저 VRAM LLM 파인튜닝',
      '소비자 GPU에서의 빠른 LoRA 학습',
      '비용 효율적 모델 적응',
      '파인튜닝 모델의 빠른 프로토타이핑',
    ],
    supportedModels: ['LLaMA', 'Mistral', 'Gemma', 'Phi', 'Qwen'],
    supportedHardware: ['NVIDIA GPU'],
    deploymentModel: ['server'],
    minRequirements: { ram: '16GB', vram: '8GB', storage: '30GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.unsloth.ai/',
    description: 'Optimized LLM fine-tuning library that reduces memory usage by 60% and increases training speed by 2x with no accuracy loss.',
    descriptionKo: '정확도 손실 없이 메모리 사용량을 60% 줄이고 학습 속도를 2배 높이는 최적화된 LLM 파인튜닝 라이브러리입니다.',
  },
];
