/**
 * AI Software Catalog — Vector Databases
 *
 * Specialized databases for storing and querying high-dimensional vector embeddings.
 */

import type { AISoftware } from './types';

export const vectorDatabases: AISoftware[] = [
  {
    id: 'AI-VDB-001',
    name: 'ChromaDB',
    nameKo: '크로마DB',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'Lightweight embedding database',
    architectureRoleKo: '경량 임베딩 데이터베이스',
    recommendedFor: [
      'RAG application prototyping',
      'Local development vector storage',
      'Small to medium embedding datasets',
      'Python-native AI pipelines',
    ],
    recommendedForKo: [
      'RAG 애플리케이션 프로토타이핑',
      '로컬 개발 벡터 스토리지',
      '소규모~중규모 임베딩 데이터셋',
      'Python 네이티브 AI 파이프라인',
    ],
    deploymentModel: ['local', 'server'],
    minRequirements: { ram: '4GB', storage: '5GB' },
    operationalComplexity: 'low',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://docs.trychroma.com/',
    description: 'Open-source embedding database designed for simplicity, with an easy-to-use Python API for AI applications.',
    descriptionKo: 'AI 애플리케이션을 위한 사용하기 쉬운 Python API를 갖춘 단순성을 위해 설계된 오픈소스 임베딩 데이터베이스입니다.',
  },
  {
    id: 'AI-VDB-002',
    name: 'Pinecone',
    nameKo: '파인콘',
    category: 'vector-db',
    license: 'commercial',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'Managed cloud vector database',
    architectureRoleKo: '관리형 클라우드 벡터 데이터베이스',
    recommendedFor: [
      'Production-scale vector search',
      'Enterprise RAG systems',
      'Serverless vector storage',
      'High-availability semantic search',
    ],
    recommendedForKo: [
      '프로덕션 규모 벡터 검색',
      '엔터프라이즈 RAG 시스템',
      '서버리스 벡터 스토리지',
      '고가용성 시맨틱 검색',
    ],
    deploymentModel: ['cloud'],
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://docs.pinecone.io/',
    description: 'Fully managed cloud-native vector database with serverless architecture for high-performance similarity search at scale.',
    descriptionKo: '대규모 고성능 유사도 검색을 위한 서버리스 아키텍처의 완전 관리형 클라우드 네이티브 벡터 데이터베이스입니다.',
  },
  {
    id: 'AI-VDB-003',
    name: 'Milvus',
    nameKo: '밀버스',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'Distributed vector database for enterprise',
    architectureRoleKo: '엔터프라이즈용 분산 벡터 데이터베이스',
    recommendedFor: [
      'Billion-scale vector search',
      'Multi-tenant vector storage',
      'Hybrid search (vector + scalar)',
      'Enterprise AI platform backbone',
    ],
    recommendedForKo: [
      '수십억 규모 벡터 검색',
      '멀티테넌트 벡터 스토리지',
      '하이브리드 검색 (벡터 + 스칼라)',
      '엔터프라이즈 AI 플랫폼 백본',
    ],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '16GB', storage: '50GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://milvus.io/docs/',
    description: 'Open-source distributed vector database built for scalable similarity search with support for billions of vectors.',
    descriptionKo: '수십억 벡터를 지원하는 확장 가능한 유사도 검색을 위한 오픈소스 분산 벡터 데이터베이스입니다.',
  },
  {
    id: 'AI-VDB-004',
    name: 'Weaviate',
    nameKo: '위비에이트',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'AI-native vector search engine',
    architectureRoleKo: 'AI 네이티브 벡터 검색 엔진',
    recommendedFor: [
      'Multimodal search applications',
      'GraphQL-based vector queries',
      'Generative search with RAG',
      'Hybrid vector and keyword search',
    ],
    recommendedForKo: [
      '멀티모달 검색 애플리케이션',
      'GraphQL 기반 벡터 쿼리',
      'RAG 기반 생성형 검색',
      '하이브리드 벡터 및 키워드 검색',
    ],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '8GB', storage: '20GB' },
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://weaviate.io/developers/weaviate',
    description: 'AI-native vector database with built-in vectorization modules, supporting multimodal data and generative search.',
    descriptionKo: '내장 벡터화 모듈을 갖춘 AI 네이티브 벡터 데이터베이스로, 멀티모달 데이터와 생성형 검색을 지원합니다.',
  },
  {
    id: 'AI-VDB-005',
    name: 'Qdrant',
    nameKo: '큐드란트',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'High-performance vector similarity engine',
    architectureRoleKo: '고성능 벡터 유사도 엔진',
    recommendedFor: [
      'Real-time recommendation systems',
      'Filtering with vector search',
      'High-performance similarity matching',
      'Rust-based production deployments',
    ],
    recommendedForKo: [
      '실시간 추천 시스템',
      '필터링 기반 벡터 검색',
      '고성능 유사도 매칭',
      'Rust 기반 프로덕션 배포',
    ],
    deploymentModel: ['server', 'cloud'],
    minRequirements: { ram: '8GB', storage: '20GB' },
    operationalComplexity: 'medium',
    communitySize: 'medium',
    maturity: 'growing',
    documentationUrl: 'https://qdrant.tech/documentation/',
    description: 'Rust-based vector similarity search engine with advanced filtering, payload storage, and high throughput.',
    descriptionKo: '고급 필터링, 페이로드 저장, 높은 처리량을 제공하는 Rust 기반 벡터 유사도 검색 엔진입니다.',
  },
  {
    id: 'AI-VDB-006',
    name: 'pgvector',
    nameKo: 'pgvector',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'PostgreSQL vector search extension',
    architectureRoleKo: 'PostgreSQL 벡터 검색 확장',
    recommendedFor: [
      'Adding vector search to existing PostgreSQL',
      'Unified relational + vector storage',
      'Small to medium vector datasets',
      'Teams with PostgreSQL expertise',
    ],
    recommendedForKo: [
      '기존 PostgreSQL에 벡터 검색 추가',
      '관계형 + 벡터 통합 스토리지',
      '소규모~중규모 벡터 데이터셋',
      'PostgreSQL 전문 팀',
    ],
    deploymentModel: ['server'],
    operationalComplexity: 'low',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://github.com/pgvector/pgvector/blob/master/README.md',
    description: 'PostgreSQL extension for vector similarity search, enabling AI capabilities in existing PostgreSQL databases.',
    descriptionKo: '기존 PostgreSQL 데이터베이스에서 AI 기능을 활성화하는 벡터 유사도 검색 PostgreSQL 확장입니다.',
  },
  {
    id: 'AI-VDB-007',
    name: 'FAISS',
    nameKo: 'FAISS',
    category: 'vector-db',
    license: 'open-source',
    infraNodeTypes: ['vector-db'],
    architectureRole: 'High-performance vector search library',
    architectureRoleKo: '고성능 벡터 검색 라이브러리',
    recommendedFor: [
      'Research and experimentation',
      'GPU-accelerated similarity search',
      'Billion-scale nearest neighbor search',
      'Custom vector search pipelines',
    ],
    recommendedForKo: [
      '연구 및 실험',
      'GPU 가속 유사도 검색',
      '수십억 규모 최근접 이웃 검색',
      '커스텀 벡터 검색 파이프라인',
    ],
    supportedHardware: ['CPU', 'NVIDIA GPU'],
    deploymentModel: ['local', 'server'],
    minRequirements: { ram: '8GB' },
    operationalComplexity: 'medium',
    communitySize: 'large',
    maturity: 'mature',
    documentationUrl: 'https://faiss.ai/',
    description: 'Meta library for efficient similarity search and clustering of dense vectors, supporting both CPU and GPU.',
    descriptionKo: 'CPU와 GPU를 모두 지원하는 밀집 벡터의 효율적 유사도 검색 및 클러스터링을 위한 Meta 라이브러리입니다.',
  },
];
